# This file is auto generated by a custom script.
# With how EVN plugins work, we essentially have to reconstruct any objects we want to modify.
# This file contains a table of character data used in EV Nova.

from typing import Dict, TypedDict, List, Set 

char_columns = {
    "resource_type": "Resource Type",
    "id": "ID",
    "name": "Name",
    "cash": "Cash",
    "ship_type": "Ship Type",
    "system_1": "System 1",
    "system_2": "System 2",
    "system_3": "System 3",
    "system_4": "System 4",
    "government_1": "Government 1",
    "status_1": "Status 1",
    "government_2": "Government 2",
    "status_2": "Status 2",
    "government_3": "Government 3",
    "status_3": "Status 3",
    "government_4": "Government 4",
    "status_4": "Status 4",
    "combat_rating": "Combat Rating",
    "intro_pict_1": "Intro Pict 1",
    "intro_pict_2": "Intro Pict 2",
    "intro_pict_3": "Intro Pict 3",
    "intro_pict_4": "Intro Pict 4",
    "pict_delay_1": "Pict Delay 1",
    "pict_delay_2": "Pict Delay 2",
    "pict_delay_3": "Pict Delay 3",
    "pict_delay_4": "Pict Delay 4",
    "intro_text": "Intro Text",
    "on_start": "On Start",
    "start_day": "Start Day",
    "start_month": "Start Month",
    "start_year": "Start Year",
    "date_prefix": "Date Prefix",
    "date_suffix": "Date Suffix",
    "flags": "Flags",
    "end_of_resource": "End-of-resource"
}
        

class CharDict(TypedDict, total=False): 
    resource_type: str
    id: str
    name: str
    cash: str
    ship_type: str
    system_1: str
    system_2: str
    system_3: str
    system_4: str
    government_1: str
    status_1: str
    government_2: str
    status_2: str
    government_3: str
    status_3: str
    government_4: str
    status_4: str
    combat_rating: str
    intro_pict_1: str
    intro_pict_2: str
    intro_pict_3: str
    intro_pict_4: str
    pict_delay_1: str
    pict_delay_2: str
    pict_delay_3: str
    pict_delay_4: str
    intro_text: str
    on_start: str
    start_day: str
    start_month: str
    start_year: str
    date_prefix: str
    date_suffix: str
    flags: str
    end_of_resource: str


char_table: Dict[int, CharDict] = {
    128: {
            "Resource Type": "char",
            "ID": "128",
            "Name": ".Trader",
            "Cash": "25000",
            "Ship Type": "128",
            "System 1": "128",
            "System 2": "136",
            "System 3": "170",
            "System 4": "184",
            "Government 1": "-1",
            "Status 1": "-1",
            "Government 2": "-1",
            "Status 2": "-1",
            "Government 3": "-1",
            "Status 3": "-1",
            "Government 4": "-1",
            "Status 4": "-1",
            "Combat Rating": "0",
            "Intro Pict 1": "8200",
            "Intro Pict 2": "8201",
            "Intro Pict 3": "8202",
            "Intro Pict 4": "-1",
            "Pict Delay 1": "45",
            "Pict Delay 2": "45",
            "Pict Delay 3": "45",
            "Pict Delay 4": "-1",
            "Intro Text": "-1",
            "On Start": "",
            "Start Day": "23",
            "Start Month": "6",
            "Start Year": "1177",
            "Date Prefix": "",
            "Date Suffix": " NC",
            "Flags": "0x0001",
            "End-of-resource": "EOR",
        }
}