# This file is auto generated by a custom script.
# With how EVN plugins work, we essentially have to reconstruct any objects we want to modify.
# This file contains a table of character data used in EV Nova.

from typing import Dict, TypedDict, List, Set 

char_columns = {
    "resource_type": "Resource Type",
    "id": "ID",
    "name": "Name",
    "cash": "Cash",
    "ship_type": "Ship Type",
    "system_1": "System 1",
    "system_2": "System 2",
    "system_3": "System 3",
    "system_4": "System 4",
    "government_1": "Government 1",
    "status_1": "Status 1",
    "government_2": "Government 2",
    "status_2": "Status 2",
    "government_3": "Government 3",
    "status_3": "Status 3",
    "government_4": "Government 4",
    "status_4": "Status 4",
    "combat_rating": "Combat Rating",
    "intro_pict_1": "Intro Pict 1",
    "intro_pict_2": "Intro Pict 2",
    "intro_pict_3": "Intro Pict 3",
    "intro_pict_4": "Intro Pict 4",
    "pict_delay_1": "Pict Delay 1",
    "pict_delay_2": "Pict Delay 2",
    "pict_delay_3": "Pict Delay 3",
    "pict_delay_4": "Pict Delay 4",
    "intro_text": "Intro Text",
    "on_start": "On Start",
    "start_day": "Start Day",
    "start_month": "Start Month",
    "start_year": "Start Year",
    "date_prefix": "Date Prefix",
    "date_suffix": "Date Suffix",
    "flags": "Flags",
    "end_of_resource": "End-of-resource"
}
        

class CharDict(TypedDict, total=False): 
    resource_type: str
    id: int
    name: str
    cash: int
    ship_type: int
    system_1: int
    system_2: int
    system_3: int
    system_4: int
    government_1: int
    status_1: int
    government_2: int
    status_2: int
    government_3: int
    status_3: int
    government_4: int
    status_4: int
    combat_rating: int
    intro_pict_1: int
    intro_pict_2: int
    intro_pict_3: int
    intro_pict_4: int
    pict_delay_1: int
    pict_delay_2: int
    pict_delay_3: int
    pict_delay_4: int
    intro_text: int
    on_start: str
    start_day: int
    start_month: int
    start_year: int
    date_prefix: str
    date_suffix: str
    flags: int
    end_of_resource: str


char_table: Dict[int, CharDict] = {
    128: {
        "resource_type": "char",
        "id": "128",
        "name": ".Trader",
        "cash": "25000",
        "ship_type": "128",
        "system_1": "128",
        "system_2": "136",
        "system_3": "170",
        "system_4": "184",
        "government_1": "-1",
        "status_1": "-1",
        "government_2": "-1",
        "status_2": "-1",
        "government_3": "-1",
        "status_3": "-1",
        "government_4": "-1",
        "status_4": "-1",
        "combat_rating": "0",
        "intro_pict_1": "-1",
        "intro_pict_2": "-1",
        "intro_pict_3": "-1",
        "intro_pict_4": "-1",
        "pict_delay_1": "-1",
        "pict_delay_2": "-1",
        "pict_delay_3": "-1",
        "pict_delay_4": "-1",
        "intro_text": "-1",
        "on_start": "",
        "start_day": "23",
        "start_month": "6",
        "start_year": "1177",
        "date_prefix": "",
        "date_suffix": " NC",
        "flags": "0x0001",
        "end_of_resource": "EOR"
    },
    129: {
        "resource_type": "char",
        "id": "129",
        "name": ".Head Start",
        "cash": "500000",
        "ship_type": "165", # mod starbridge
        "system_1": "128",
        "system_2": "136",
        "system_3": "170",
        "system_4": "184",
        "government_1": "-1",
        "status_1": "-1",
        "government_2": "-1",
        "status_2": "-1",
        "government_3": "-1",
        "status_3": "-1",
        "government_4": "-1",
        "status_4": "-1",
        "combat_rating": "1600",
        "intro_pict_1": "-1",
        "intro_pict_2": "-1",
        "intro_pict_3": "-1",
        "intro_pict_4": "-1",
        "pict_delay_1": "-1",
        "pict_delay_2": "-1",
        "pict_delay_3": "-1",
        "pict_delay_4": "-1",
        "intro_text": "-1",
        "on_start": "",
        "start_day": "23",
        "start_month": "6",
        "start_year": "1177",
        "date_prefix": "",
        "date_suffix": " NC",
        "flags": "0x0000",
        "end_of_resource": "EOR"
    }
}