class ItemData:
    def __init__(self, name, region, type):
        self.name = name
        self.region = region
        self.type = type


items_data = {
    ItemData("Item", "BurnedTower1F", "overworld"),
    ItemData("Item", "BurnedTowerB1F", "overworld"),
    ItemData("Item 1", "DarkCaveBlackthornEntrance", "overworld"),
    ItemData("Item 2", "DarkCaveBlackthornEntrance", "overworld"),
    ItemData("Item 1", "DarkCaveVioletEntrance", "overworld"),
    ItemData("Item 2", "DarkCaveVioletEntrance", "overworld"),
    ItemData("Item 3", "DarkCaveVioletEntrance", "overworld"),
    ItemData("Item 4", "DarkCaveVioletEntrance", "overworld"),
    ItemData("Item 1", "DragonsDenB1F", "overworld"),
    ItemData("Item 2", "DragonsDenB1F", "overworld"),
    ItemData("Item 3", "DragonsDenB1F", "overworld"),
    ItemData("Item", "FightingDojo", "overworld"),
    ItemData("Item 1", "GoldenrodDeptStoreB1F", "overworld"),
    ItemData("Item 2", "GoldenrodDeptStoreB1F", "overworld"),
    ItemData("Item 3", "GoldenrodDeptStoreB1F", "overworld"),
    ItemData("Item 4", "GoldenrodDeptStoreB1F", "overworld"),
    ItemData("Item", "GoldenrodUnderground", "overworld"),
    ItemData("Item 1", "GoldenrodUndergroundSwitchRoomEntrances", "overworld"),
    ItemData("Item 2", "GoldenrodUndergroundSwitchRoomEntrances", "overworld"),
    ItemData("Item 1", "GoldenrodUndergroundWarehouse", "overworld"),
    ItemData("Item 2", "GoldenrodUndergroundWarehouse", "overworld"),
    ItemData("Item 3", "GoldenrodUndergroundWarehouse", "overworld"),
    ItemData("Item 1", "IcePath1F", "overworld"),
    ItemData("Item 2", "IcePath1F", "overworld"),
    ItemData("Item 3", "IcePath1F", "overworld"),
    ItemData("Item", "IcePathB1F", "overworld"),
    ItemData("Item", "IcePathB2FBlackthornSide", "overworld"),
    ItemData("Item 1", "IcePathB2FMahoganySide", "overworld"),
    ItemData("Item 2", "IcePathB2FMahoganySide", "overworld"),
    ItemData("Item", "IcePathB3F", "overworld"),
    ItemData("Item 1", "IlexForest", "overworld"),
    ItemData("Item 2", "IlexForest", "overworld"),
    ItemData("Item 3", "IlexForest", "overworld"),
    ItemData("Item 4", "IlexForest", "overworld"),
    ItemData("Item 1", "LakeOfRage", "overworld"),
    ItemData("Item 2", "LakeOfRage", "overworld"),
    ItemData("Item 1", "MountMortar1FInside", "overworld"),
    ItemData("Item 2", "MountMortar1FInside", "overworld"),
    ItemData("Item 3", "MountMortar1FInside", "overworld"),
    ItemData("Item 4", "MountMortar1FInside", "overworld"),
    ItemData("Item 5", "MountMortar1FInside", "overworld"),
    ItemData("Item 6", "MountMortar1FInside", "overworld"),
    ItemData("Item 7", "MountMortar1FInside", "overworld"),
    ItemData("Item 1", "MountMortar1FOutside", "overworld"),
    ItemData("Item 2", "MountMortar1FOutside", "overworld"),
    ItemData("Item 1", "MountMortar2FInside", "overworld"),
    ItemData("Item 2", "MountMortar2FInside", "overworld"),
    ItemData("Item 3", "MountMortar2FInside", "overworld"),
    ItemData("Item 4", "MountMortar2FInside", "overworld"),
    ItemData("Item 5", "MountMortar2FInside", "overworld"),
    ItemData("Item 6", "MountMortar2FInside", "overworld"),
    ItemData("Item 1", "MountMortarB1F", "overworld"),
    ItemData("Item 2", "MountMortarB1F", "overworld"),
    ItemData("Item 3", "MountMortarB1F", "overworld"),
    ItemData("Item 4", "MountMortarB1F", "overworld"),
    ItemData("Item 5", "MountMortarB1F", "overworld"),
    ItemData("Item 1", "NationalPark", "overworld"),
    ItemData("Item 2", "NationalPark", "overworld"),
    ItemData("Item 1", "NationalParkBugContest", "overworld"),
    ItemData("Item 2", "NationalParkBugContest", "overworld"),
    ItemData("Item", "OlivineLighthouse3F", "overworld"),
    ItemData("Item 1", "OlivineLighthouse5F", "overworld"),
    ItemData("Item 1", "OlivineLighthouse5F", "overworld"),
    ItemData("Item 1", "OlivineLighthouse5F", "overworld"),
    ItemData("Item", "OlivineLighthouse6F", "overworld"),
    ItemData("Item", "RadioTower5F", "overworld"),
    ItemData("Item 1", "RockTunnel1F", "overworld"),
    ItemData("Item 2", "RockTunnel1F", "overworld"),
    ItemData("Item 1", "RockTunnelB1F", "overworld"),
    ItemData("Item 2", "RockTunnelB1F", "overworld"),
    ItemData("Item 3", "RockTunnelB1F", "overworld"),
    ItemData("Item 1", "Route12", "overworld"),
    ItemData("Item 2", "Route12", "overworld"),
    ItemData("Item", "Route15", "overworld"),
    ItemData("Item 1", "Route2", "overworld"),
    ItemData("Item 2", "Route2", "overworld"),
    ItemData("Item 3", "Route2", "overworld"),
    ItemData("Item 4", "Route2", "overworld"),
    ItemData("Item", "Route25", "overworld"),
    ItemData("Item", "Route26", "overworld"),
    ItemData("Item 1", "Route27", "overworld"),
    ItemData("Item 2", "Route27", "overworld"),
    ItemData("Item", "Route29", "overworld"),
    ItemData("Item", "Route30", "overworld"),
    ItemData("Item 1", "Route31", "overworld"),
    ItemData("Item 2", "Route31", "overworld"),
    ItemData("Item 1", "Route32", "overworld"),
    ItemData("Item 2", "Route32", "overworld"),
    ItemData("Item", "Route34", "overworld"),
    ItemData("Item", "Route35", "overworld"),
    ItemData("Item", "Route4", "overworld"),
    ItemData("Item 1", "Route42", "overworld"),
    ItemData("Item 2", "Route42", "overworld"),
    ItemData("Item", "Route43", "overworld"),
    ItemData("Item 1", "Route44", "overworld"),
    ItemData("Item 2", "Route44", "overworld"),
    ItemData("Item 3", "Route44", "overworld"),
    ItemData("Item 1", "Route45", "overworld"),
    ItemData("Item 2", "Route45", "overworld"),
    ItemData("Item 3", "Route45", "overworld"),
    ItemData("Item 4", "Route45", "overworld"),
    ItemData("Item", "Route46", "overworld"),
    ItemData("Item 1", "RuinsOfAlphAerodactylItemRoom", "overworld"),
    ItemData("Item 2", "RuinsOfAlphAerodactylItemRoom", "overworld"),
    ItemData("Item 3", "RuinsOfAlphAerodactylItemRoom", "overworld"),
    ItemData("Item 4", "RuinsOfAlphAerodactylItemRoom", "overworld"),
    ItemData("Item 1", "RuinsOfAlphHoOhItemRoom", "overworld"),
    ItemData("Item 2", "RuinsOfAlphHoOhItemRoom", "overworld"),
    ItemData("Item 3", "RuinsOfAlphHoOhItemRoom", "overworld"),
    ItemData("Item 4", "RuinsOfAlphHoOhItemRoom", "overworld"),
    ItemData("Item 1", "RuinsOfAlphKabutoItemRoom", "overworld"),
    ItemData("Item 2", "RuinsOfAlphKabutoItemRoom", "overworld"),
    ItemData("Item 3", "RuinsOfAlphKabutoItemRoom", "overworld"),
    ItemData("Item 4", "RuinsOfAlphKabutoItemRoom", "overworld"),
    ItemData("Item 1", "RuinsOfAlphOmanyteItemRoom", "overworld"),
    ItemData("Item 2", "RuinsOfAlphOmanyteItemRoom", "overworld"),
    ItemData("Item 3", "RuinsOfAlphOmanyteItemRoom", "overworld"),
    ItemData("Item 4", "RuinsOfAlphOmanyteItemRoom", "overworld"),
    ItemData("Item 1", "SilverCaveItemRooms", "overworld"),
    ItemData("Item 2", "SilverCaveItemRooms", "overworld"),
    ItemData("Item 1", "SilverCaveRoom1", "overworld"),
    ItemData("Item 2", "SilverCaveRoom1", "overworld"),
    ItemData("Item 3", "SilverCaveRoom1", "overworld"),
    ItemData("Item 4", "SilverCaveRoom1", "overworld"),
    ItemData("Item 1", "SilverCaveRoom2", "overworld"),
    ItemData("Item 2", "SilverCaveRoom2", "overworld"),
    ItemData("Item 3", "SilverCaveRoom2", "overworld"),
    ItemData("Item", "SlowpokeWellB1F", "overworld"),
    ItemData("Item", "SlowpokeWellB2F", "overworld"),
    ItemData("Item", "SproutTower1F", "overworld"),
    ItemData("Item", "SproutTower2F", "overworld"),
    ItemData("Item 1", "SproutTower3F", "overworld"),
    ItemData("Item 2", "SproutTower3F", "overworld"),
    ItemData("Item 1", "TeamRocketBaseB1F", "overworld"),
    ItemData("Item 2", "TeamRocketBaseB1F", "overworld"),
    ItemData("Item 3", "TeamRocketBaseB1F", "overworld"),
    ItemData("Item", "TeamRocketBaseB2F", "overworld"),
    ItemData("Item 1", "TeamRocketBaseB3F", "overworld"),
    ItemData("Item 2", "TeamRocketBaseB3F", "overworld"),
    ItemData("Item 3", "TeamRocketBaseB3F", "overworld"),
    ItemData("Item 4", "TeamRocketBaseB3F", "overworld"),
    ItemData("Item 5", "TeamRocketBaseB3F", "overworld"),
    ItemData("Item", "TinTower3F", "overworld"),
    ItemData("Item 1", "TinTower4F", "overworld"),
    ItemData("Item 2", "TinTower4F", "overworld"),
    ItemData("Item 3", "TinTower4F", "overworld"),
    ItemData("Item", "TinTower5F", "overworld"),
    ItemData("Item", "TinTower6F", "overworld"),
    ItemData("Item", "TinTower7F", "overworld"),
    ItemData("Item 1", "TinTower8F", "overworld"),
    ItemData("Item 2", "TinTower8F", "overworld"),
    ItemData("Item 3", "TinTower8F", "overworld"),
    ItemData("Item", "TinTower9F", "overworld"),
    ItemData("Item", "TohjoFalls", "overworld"),
    ItemData("Item 1", "UnionCave1F", "overworld"),
    ItemData("Item 2", "UnionCave1F", "overworld"),
    ItemData("Item 3", "UnionCave1F", "overworld"),
    ItemData("Item 4", "UnionCave1F", "overworld"),
    ItemData("Item 1", "UnionCaveB1F", "overworld"),
    ItemData("Item 1", "UnionCaveB1F", "overworld"),
    ItemData("Item 1", "UnionCaveB2F", "overworld"),
    ItemData("Item 2", "UnionCaveB2F", "overworld"),
    ItemData("Item 1", "VictoryRoad", "overworld"),
    ItemData("Item 2", "VictoryRoad", "overworld"),
    ItemData("Item 3", "VictoryRoad", "overworld"),
    ItemData("Item 4", "VictoryRoad", "overworld"),
    ItemData("Item 5", "VictoryRoad", "overworld"),
    ItemData("Item 1", "VioletCity", "overworld"),
    ItemData("Item 2", "VioletCity", "overworld"),
    ItemData("Item 1", "WhirlIslandB1F", "overworld"),
    ItemData("Item 2", "WhirlIslandB1F", "overworld"),
    ItemData("Item 3", "WhirlIslandB1F", "overworld"),
    ItemData("Item 4", "WhirlIslandB1F", "overworld"),
    ItemData("Item 5", "WhirlIslandB1F", "overworld"),
    ItemData("Item 1", "WhirlIslandB2F", "overworld"),
    ItemData("Item 2", "WhirlIslandB2F", "overworld"),
    ItemData("Item 3", "WhirlIslandB2F", "overworld"),
    ItemData("Item", "WhirlIslandNE", "overworld"),
    ItemData("Item", "WhirlIslandSW", "overworld"),

    ItemData("Hidden Item", "AzaleaTown", "hidden"),
    ItemData("Hidden Item 1", "BurnedTower1F", "hidden"),
    ItemData("Hidden Item 2", "BurnedTower1F", "hidden"),
    ItemData("Hidden Item", "CeladonCity", "hidden"),
    ItemData("Hidden Item 1", "CeruleanCity", "hidden"),
    ItemData("Hidden Item 2", "CeruleanGym", "hidden"),
    ItemData("Hidden Item 1", "CianwoodCity", "hidden"),
    ItemData("Hidden Item 2", "CianwoodCity", "hidden"),
    ItemData("Hidden Item", "CinnabarIsland", "hidden"),
    ItemData("Hidden Item", "DarkCaveVioletEntrance", "hidden"),
    ItemData("Hidden Item", "DiglettsCave", "hidden"),
    ItemData("Hidden Item 1", "DragonsDenB1F", "hidden"),
    ItemData("Hidden Item 2", "DragonsDenB1F", "hidden"),
    ItemData("Hidden Item 3", "DragonsDenB1F", "hidden"),
    ItemData("Hidden Item", "EcruteakCity", "hidden"),
    ItemData("Hidden Item 1", "GoldenrodUnderground", "hidden"),
    ItemData("Hidden Item 2", "GoldenrodUnderground", "hidden"),
    ItemData("Hidden Item 3", "GoldenrodUnderground", "hidden"),
    ItemData("Hidden Item 1", "GoldenrodUndergroundSwitchRoomEntrances", "hidden"),
    ItemData("Hidden Item 2", "GoldenrodUndergroundSwitchRoomEntrances", "hidden"),
    ItemData("Hidden Item", "IcePathB1F", "hidden"),
    ItemData("Hidden Item", "IcePathB2FBlackthornSide", "hidden"),
    ItemData("Hidden Item", "IcePathB2FMahoganySide", "hidden"),
    ItemData("Hidden Item 1", "IlexForest", "hidden"),
    ItemData("Hidden Item 2", "IlexForest", "hidden"),
    ItemData("Hidden Item 3", "IlexForest", "hidden"),
    ItemData("Hidden Item 1", "LakeOfRage", "hidden"),
    ItemData("Hidden Item 2", "LakeOfRage", "hidden"),
    ItemData("Hidden Item 3", "LakeOfRage", "hidden"),
    ItemData("Hidden Item", "MountMoonSquare", "hidden"),
    ItemData("Hidden Item", "MountMortar1FInside", "hidden"),
    ItemData("Hidden Item", "MountMortar1FOutside", "hidden"),
    ItemData("Hidden Item", "MountMortar2FInside", "hidden"),
    ItemData("Hidden Item", "MountMortarB1F", "hidden"),
    ItemData("Hidden Item", "NationalPark", "hidden"),
    ItemData("Hidden Item", "NationalParkBugContest", "hidden"),
    ItemData("Hidden Item", "OlivineLighthouse5F", "hidden"),
    ItemData("Hidden Item", "OlivinePort", "hidden"),
    ItemData("Hidden Item 1", "RockTunnel1F", "hidden"),
    ItemData("Hidden Item 2", "RockTunnel1F", "hidden"),
    ItemData("Hidden Item", "RockTunnelB1F", "hidden"),
    ItemData("Hidden Item", "Route11", "hidden"),
    ItemData("Hidden Item", "Route12", "hidden"),
    ItemData("Hidden Item", "Route13", "hidden"),
    ItemData("Hidden Item 1", "Route17", "hidden"),
    ItemData("Hidden Item 1", "Route17", "hidden"),
    ItemData("Hidden Item 1", "Route2", "hidden"),
    ItemData("Hidden Item 2", "Route2", "hidden"),
    ItemData("Hidden Item 3", "Route2", "hidden"),
    ItemData("Hidden Item 4", "Route2", "hidden"),
    ItemData("Hidden Item", "Route25", "hidden"),
    ItemData("Hidden Item", "Route28", "hidden"),
    ItemData("Hidden Item", "Route30", "hidden"),
    ItemData("Hidden Item 1", "Route32", "hidden"),
    ItemData("Hidden Item 2", "Route32", "hidden"),
    ItemData("Hidden Item 1", "Route34", "hidden"),
    ItemData("Hidden Item 2", "Route34", "hidden"),
    ItemData("Hidden Item", "Route37", "hidden"),
    ItemData("Hidden Item", "Route39", "hidden"),
    ItemData("Hidden Item", "Route4", "hidden"),
    ItemData("Hidden Item", "Route40", "hidden"),
    ItemData("Hidden Item", "Route41", "hidden"),
    ItemData("Hidden Item", "Route42", "hidden"),
    ItemData("Hidden Item", "Route44", "hidden"),
    ItemData("Hidden Item", "Route45", "hidden"),
    ItemData("Hidden Item", "Route9", "hidden"),
    ItemData("Hidden Item", "SilverCaveOutside", "hidden"),
    ItemData("Hidden Item 1", "SilverCaveRoom1", "hidden"),
    ItemData("Hidden Item 2", "SilverCaveRoom1", "hidden"),
    ItemData("Hidden Item", "SilverCaveRoom2", "hidden"),
    ItemData("Hidden Item", "TeamRocketBaseB1F", "hidden"),
    ItemData("Hidden Item", "TeamRocketBaseB2F", "hidden"),
    ItemData("Hidden Item", "TinTower4F", "hidden"),
    ItemData("Hidden Item 1", "TinTower5F", "hidden"),
    ItemData("Hidden Item 2", "TinTower5F", "hidden"),
    ItemData("Hidden Item 1", "UndergroundPath", "hidden"),
    ItemData("Hidden Item 2", "UndergroundPath", "hidden"),
    ItemData("Hidden Item", "VermilionCity", "hidden"),
    ItemData("Hidden Item", "VermilionPort", "hidden"),
    ItemData("Hidden Item 1", "VictoryRoad", "hidden"),
    ItemData("Hidden Item 2", "VictoryRoad", "hidden"),
    ItemData("Hidden Item", "VioletCity", "hidden"),
    ItemData("Hidden Item 1", "WhirlIslandB1F", "hidden"),
    ItemData("Hidden Item 2", "WhirlIslandB1F", "hidden"),
    ItemData("Hidden Item 3", "WhirlIslandB1F", "hidden"),

    ItemData("NPC Item", "AzaleaGym", "npc"),
    ItemData("NPC Item", "AzaleaTown", "npc"),
    ItemData("NPC Item", "BattleTower1F", "npc"),
    ItemData("NPC Item 1", "BillsHouse", "npc"),
    ItemData("NPC Item 2", "BillsHouse", "npc"),
    ItemData("NPC Item 3", "BillsHouse", "npc"),
    ItemData("NPC Item 4", "BillsHouse", "npc"),
    ItemData("NPC Item 5", "BillsHouse", "npc"),
    ItemData("NPC Item", "BlackthornCity", "npc"),
    ItemData("NPC Item", "BlackthornGym1F", "npc"),
    ItemData("NPC Item", "CeladonCafe", "npc"),
    ItemData("NPC Item 1", "CeladonDeptStore6F", "npc"),
    ItemData("NPC Item 2", "CeladonDeptStore6F", "npc"),
    ItemData("NPC Item 3", "CeladonDeptStore6F", "npc"),
    ItemData("NPC Item 1", "CeladonGameCornerPrizeRoom", "npc"),
    ItemData("NPC Item 2", "CeladonGameCornerPrizeRoom", "npc"),
    ItemData("NPC Item 3", "CeladonGameCornerPrizeRoom", "npc"),
    ItemData("NPC Item", "CeladonGym", "npc"),
    ItemData("NPC Item", "CeladonMansionRoofHouse", "npc"),
    ItemData("NPC Item", "CharcoalKiln", "npc"),
    ItemData("NPC Item", "CherrygroveCity", "npc"),
    ItemData("NPC Item", "CianwoodCity", "npc"),
    ItemData("NPC Item", "CianwoodGym", "npc"),
    ItemData("NPC Item", "CianwoodPharmacy", "npc"),
    ItemData("NPC Item", "CopycatsHouse2F", "npc"),
    ItemData("NPC Item", "DanceTheater", "npc"),
    ItemData("NPC Item", "DarkCaveBlackthornEntrance", "npc"),
    ItemData("NPC Item", "DragonsDenB1F", "npc"),
    ItemData("NPC Item", "EcruteakGym", "npc"),
    ItemData("NPC Item", "EcruteakItemfinderHouse", "npc"),
    ItemData("NPC Item 1", "ElmsLab", "npc"),
    ItemData("NPC Item 2", "ElmsLab", "npc"),
    ItemData("NPC Item 3", "ElmsLab", "npc"),
    ItemData("NPC Item 4", "ElmsLab", "npc"),
    ItemData("NPC Item 5", "ElmsLab", "npc"),
    ItemData("NPC Item 1", "FastShipCabins_SE_SSE_CaptainsCabin", "npc"),
    ItemData("NPC Item 2", "FastShipCabins_SE_SSE_CaptainsCabin", "npc"),
    ItemData("NPC Item", "FuchsiaGym", "npc"),
    ItemData("NPC Item", "GoldenrodBikeShop", "npc"),
    ItemData("NPC Item 1", "GoldenrodDeptStore5F", "npc"),
    ItemData("NPC Item 2", "GoldenrodDeptStore5F", "npc"),
    ItemData("NPC Item 1", "GoldenrodDeptStore6F", "npc"),
    ItemData("NPC Item 2", "GoldenrodDeptStore6F", "npc"),
    ItemData("NPC Item 3", "GoldenrodDeptStore6F", "npc"),
    ItemData("NPC Item", "GoldenrodFlowerShop", "npc"),
    ItemData("NPC Item 1", "GoldenrodGameCorner", "npc"),
    ItemData("NPC Item 2", "GoldenrodGameCorner", "npc"),
    ItemData("NPC Item 3", "GoldenrodGameCorner", "npc"),
    ItemData("NPC Item", "GoldenrodGym", "npc"),
    ItemData("NPC Item 1", "GoldenrodPokecenter1F", "npc"),
    ItemData("NPC Item 2", "GoldenrodPokecenter1F", "npc"),
    ItemData("NPC Item 3", "GoldenrodPokecenter1F", "npc"),
    ItemData("NPC Item 4", "GoldenrodPokecenter1F", "npc"),
    ItemData("NPC Item", "GoldenrodUndergroundWarehouse", "npc"),
    ItemData("NPC Item 1", "IlexForest", "npc"),
    ItemData("NPC Item 2", "IlexForest", "npc"),
    ItemData("NPC Item 1", "KurtsHouse", "npc"),
    ItemData("NPC Item 2", "KurtsHouse", "npc"),
    ItemData("NPC Item 3", "KurtsHouse", "npc"),
    ItemData("NPC Item 4", "KurtsHouse", "npc"),
    ItemData("NPC Item 5", "KurtsHouse", "npc"),
    ItemData("NPC Item 6", "KurtsHouse", "npc"),
    ItemData("NPC Item 7", "KurtsHouse", "npc"),
    ItemData("NPC Item 8", "KurtsHouse", "npc"),
    ItemData("NPC Item 1", "LakeOfRage", "npc"),
    ItemData("NPC Item 2", "LakeOfRage", "npc"),
    ItemData("NPC Item", "LakeOfRageHiddenPowerHouse", "npc"),
    ItemData("NPC Item", "LakeOfRageMagikarpHouse", "npc"),
    ItemData("NPC Item", "MahoganyGym", "npc"),
    ItemData("NPC Item", "MahoganyTown", "npc"),
    ItemData("NPC Item 1", "MrPokemonsHouse", "npc"),
    ItemData("NPC Item 2", "MrPokemonsHouse", "npc"),
    ItemData("NPC Item", "MrPsychicsHouse", "npc"),
    ItemData("NPC Item 1", "NationalPark", "npc"),
    ItemData("NPC Item 2", "NationalPark", "npc"),
    ItemData("NPC Item", "OlivineCafe", "npc"),
    ItemData("NPC Item", "OlivineGoodRodHouse", "npc"),
    ItemData("NPC Item", "OlivineGym", "npc"),
    ItemData("NPC Item 1", "OlivineLighthouse2F", "npc"),
    ItemData("NPC Item 2", "OlivineLighthouse2F", "npc"),
    ItemData("NPC Item", "PewterCity", "npc"),
    ItemData("NPC Item 1", "PokemonFanClub", "npc"),
    ItemData("NPC Item 2", "PokemonFanClub", "npc"),
    ItemData("NPC Item", "PowerPlant", "npc"),
    ItemData("NPC Item 1", "RadioTower1F", "npc"),
    ItemData("NPC Item 2", "RadioTower1F", "npc"),
    ItemData("NPC Item 3", "RadioTower1F", "npc"),
    ItemData("NPC Item", "RadioTower2F", "npc"),
    ItemData("NPC Item", "RadioTower3F", "npc"),
    ItemData("NPC Item", "RadioTower4F", "npc"),
    ItemData("NPC Item 1", "RadioTower5F", "npc"),
    ItemData("NPC Item 2", "RadioTower5F", "npc"),
    ItemData("NPC Item", "Route12SuperRodHouse", "npc"),
    ItemData("NPC Item", "Route25", "npc"),
    ItemData("NPC Item", "Route27", "npc"),
    ItemData("NPC Item", "Route27SandstormHouse", "npc"),
    ItemData("NPC Item", "Route28SteelWingHouse", "npc"),
    ItemData("NPC Item", "Route29", "npc"),
    ItemData("NPC Item", "Route2NuggetHouse", "npc"),
    ItemData("NPC Item 1", "Route30", "npc"),
    ItemData("NPC Item 2", "Route30", "npc"),
    ItemData("NPC Item", "Route30BerryHouse", "npc"),
    ItemData("NPC Item 1", "Route31", "npc"),
    ItemData("NPC Item 2", "Route31", "npc"),
    ItemData("NPC Item 3", "Route31", "npc"),
    ItemData("NPC Item 4", "Route31", "npc"),
    ItemData("NPC Item 5", "Route31", "npc"),
    ItemData("NPC Item 1", "Route32", "npc"),
    ItemData("NPC Item 2", "Route32", "npc"),
    ItemData("NPC Item 3", "Route32", "npc"),
    ItemData("NPC Item", "Route32Pokecenter1F", "npc"),
    ItemData("NPC Item 1", "Route34", "npc"),
    ItemData("NPC Item 2", "Route34", "npc"),
    ItemData("NPC Item", "Route34IlexForestGate", "npc"),
    ItemData("NPC Item", "Route35GoldenrodGate", "npc"),
    ItemData("NPC Item 1", "Route36", "npc"),
    ItemData("NPC Item 2", "Route36", "npc"),
    ItemData("NPC Item 3", "Route36", "npc"),
    ItemData("NPC Item 1", "Route36NationalParkGate", "npc"),
    ItemData("NPC Item 2", "Route36NationalParkGate", "npc"),
    ItemData("NPC Item 3", "Route36NationalParkGate", "npc"),
    ItemData("NPC Item 4", "Route36NationalParkGate", "npc"),
    ItemData("NPC Item", "Route37", "npc"),
    ItemData("NPC Item", "Route38", "npc"),
    ItemData("NPC Item", "Route39", "npc"),
    ItemData("NPC Item 1", "Route39Farmhouse", "npc"),
    ItemData("NPC Item 2", "Route39Farmhouse", "npc"),
    ItemData("NPC Item", "Route40", "npc"),
    ItemData("NPC Item", "Route42", "npc"),
    ItemData("NPC Item", "Route43", "npc"),
    ItemData("NPC Item", "Route43Gate", "npc"),
    ItemData("NPC Item 1", "Route44", "npc"),
    ItemData("NPC Item 2", "Route44", "npc"),
    ItemData("NPC Item 3", "Route44", "npc"),
    ItemData("NPC Item 4", "Route44", "npc"),
    ItemData("NPC Item 5", "Route44", "npc"),
    ItemData("NPC Item 1", "Route45", "npc"),
    ItemData("NPC Item 2", "Route45", "npc"),
    ItemData("NPC Item 3", "Route45", "npc"),
    ItemData("NPC Item 1", "Route46", "npc"),
    ItemData("NPC Item 2", "Route46", "npc"),
    ItemData("NPC Item", "Route5CleanseTagHouse", "npc"),
    ItemData("NPC Item", "SilphCo1F", "npc"),
    ItemData("NPC Item", "SlowpokeWellB2F", "npc"),
    ItemData("NPC Item", "SproutTower3F", "npc"),
    ItemData("NPC Item", "TeamRocketBaseB2F", "npc"),
    ItemData("NPC Item", "TinTower1F", "npc"),
    ItemData("NPC Item", "VermilionCity", "npc"),
    ItemData("NPC Item", "VioletGym", "npc"),
    ItemData("NPC Item", "ViridianCity", "npc")

}
