# WARNING: THIS FILE HAS BEEN GENERATED!
# Modifications to this file will not be kept.
# If you need to change something here, check out codegen.py and the templates directory.


from .items import items_dict
from .types.locations import AccessInfo, LocationData
from .types.shops import ShopData
from .types.condition import *
from .locations import locations_dict

shop_dict: dict[str, ShopData] = {
    'Harbor Items': ShopData(internal_name='rookieHarborItems', name='Harbor Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind')])),
    'Harbor Items + Blue Ice': ShopData(internal_name='rookieHarborItems', name='Harbor Items + Blue Ice', metadata={'shops': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind'), ItemCondition(item_name='Blue Ice Shade', amount=1)])),
    'Harbor Items + Red Flame': ShopData(internal_name='rookieHarborItems', name='Harbor Items + Red Flame', metadata={'shops': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind'), ItemCondition(item_name='Red Flame Shade', amount=1)])),
    'Harbor Items + Green Seed': ShopData(internal_name='rookieHarborItems', name='Harbor Items + Green Seed', metadata={'shops': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind'), ItemCondition(item_name='Green Seed Shade', amount=1)])),
    'Harbor Weapons': ShopData(internal_name='rookieHarborWeapons', name='Harbor Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind')])),
    'Harbor Weapons + Red Flame': ShopData(internal_name='rookieHarborWeapons', name='Harbor Weapons + Red Flame', metadata={'shops': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind'), ItemCondition(item_name='Red Flame Shade', amount=1)])),
    'Harbor North Weapons': ShopData(internal_name='rookieHarborWeaponsNorth', name='Harbor North Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '19', 'open': 'open8'})),
    "Tara's Shop": ShopData(internal_name='rookieHarborTara', name="Tara's Shop", metadata={'shops': True}, access=AccessInfo(region={'linear': '2', 'open': 'open2'}, cond=[VariableCondition(name='canGrind')])),
    'Harbor Backer Items': ShopData(internal_name='rookieBacker', name='Harbor Backer Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '19', 'open': 'open8'})),
    'Bergen Items': ShopData(internal_name='bergenVillageItems', name='Bergen Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    'Bergen Items + Blue Ice': ShopData(internal_name='bergenVillageItems', name='Bergen Items + Blue Ice', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Blue Ice Shade', amount=1)])),
    'Bergen Items + Red Flame': ShopData(internal_name='bergenVillageItems', name='Bergen Items + Red Flame', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Red Flame Shade', amount=1)])),
    'Bergen Items + Green Seed': ShopData(internal_name='bergenVillageItems', name='Bergen Items + Green Seed', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'}, cond=[ItemCondition(item_name='Green Seed Shade', amount=1)])),
    'Bergen Weapons': ShopData(internal_name='bergenVillageWeapons', name='Bergen Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    "Hermit's Hut": ShopData(internal_name='bergenHermit', name="Hermit's Hut", metadata={'shops': True}, access=AccessInfo(region={'linear': '3', 'open': 'open3'})),
    "Ba'kii Items": ShopData(internal_name='bakiItems', name="Ba'kii Items", metadata={'shops': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'})),
    "Ba'kii Items + Blue Ice": ShopData(internal_name='bakiItems', name="Ba'kii Items + Blue Ice", metadata={'shops': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'}, cond=[ItemCondition(item_name='Blue Ice Shade', amount=1)])),
    "Ba'kii Items + Green Seed": ShopData(internal_name='bakiItems', name="Ba'kii Items + Green Seed", metadata={'shops': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'}, cond=[ItemCondition(item_name='Green Seed Shade', amount=1)])),
    "Ba'kii Weapons": ShopData(internal_name='bakiWeapons', name="Ba'kii Weapons", metadata={'shops': True}, access=AccessInfo(region={'linear': '11', 'open': 'open5'})),
    'Basin Vending Machine': ShopData(internal_name='basinVendingMachines', name='Basin Vending Machine', metadata={'shops': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'})),
    'Basin Items': ShopData(internal_name='basinItems', name='Basin Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'})),
    'Basin Weapons': ShopData(internal_name='basinWeapons', name='Basin Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'})),
    'Calzone Shop': ShopData(internal_name='basinMushroom', name='Calzone Shop', metadata={'shops': True}, access=AccessInfo(region={'linear': '23', 'open': 'open10'}, cond=[ItemCondition(item_name='Wave', amount=1)])),
    'Ridge Weapons': ShopData(internal_name='sapphireWeapons', name='Ridge Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '31', 'open': 'open16'})),
    'Ridge Items': ShopData(internal_name='sapphireItems', name='Ridge Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '31', 'open': 'open16'})),
    'Rhombus Weapons': ShopData(internal_name='rhombusWeapons1', name='Rhombus Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '33', 'open': 'open20'}, cond=[VariableCondition(name='canGrind')])),
    'Rhombus Items': ShopData(internal_name='rhombusItems1', name='Rhombus Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '33', 'open': 'open20'}, cond=[VariableCondition(name='canGrind')])),
    'Rhombus Curios': ShopData(internal_name='rhombusCurios', name='Rhombus Curios', metadata={'shops': True}, access=AccessInfo(region={'linear': '33', 'open': 'open20'}, cond=[VariableCondition(name='canGrind')])),
    'Rhombus Backer Items': ShopData(internal_name='rhombusBacker', name='Rhombus Backer Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '33', 'open': 'open20'}, cond=[VariableCondition(name='canGrind')])),
    'Vermillion Weapons': ShopData(internal_name='aridWeapons', name='Vermillion Weapons', metadata={'shops': True}, access=AccessInfo(region={'linear': '22', 'open': 'open18'})),
    'Vermillion Items': ShopData(internal_name='aridItems', name='Vermillion Items', metadata={'shops': True}, access=AccessInfo(region={'linear': '22', 'open': 'open18'})),
}

per_shop_locations: dict[str, dict[int, LocationData]] = {
    "Harbor Items": {
        1: locations_dict['Shop Slot: Sandwich (Harbor Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Harbor Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Harbor Items)'],
        366: locations_dict['Shop Slot: Just Water (Harbor Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Harbor Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Harbor Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Harbor Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Harbor Items)'],
    },
    "Harbor Items + Blue Ice": {
        353: locations_dict['Shop Slot: Kebab Roll (Harbor Items + Blue Ice)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Harbor Items + Blue Ice)'],
    },
    "Harbor Items + Red Flame": {
        110: locations_dict['Shop Slot: Bergen Ice Cream (Harbor Items + Red Flame)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Harbor Items + Red Flame)'],
    },
    "Harbor Items + Green Seed": {
        290: locations_dict['Shop Slot: Salted Peanuts (Harbor Items + Green Seed)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Harbor Items + Green Seed)"],
        331: locations_dict['Shop Slot: Snack Mix (Harbor Items + Green Seed)'],
    },
    "Harbor Weapons": {
        31: locations_dict['Shop Slot: Bronze Goggles (Harbor Weapons)'],
        29: locations_dict['Shop Slot: Bronze Edge (Harbor Weapons)'],
        30: locations_dict['Shop Slot: Bronze Mail (Harbor Weapons)'],
        32: locations_dict['Shop Slot: Bronze Boots (Harbor Weapons)'],
        118: locations_dict['Shop Slot: Iron Goggles (Harbor Weapons)'],
        113: locations_dict['Shop Slot: Iron Edge (Harbor Weapons)'],
        122: locations_dict['Shop Slot: Iron Mail (Harbor Weapons)'],
        121: locations_dict['Shop Slot: Iron Boots (Harbor Weapons)'],
    },
    "Harbor Weapons + Red Flame": {
        264: locations_dict['Shop Slot: Silver Goggles (Harbor Weapons + Red Flame)'],
        266: locations_dict['Shop Slot: Silver Edge (Harbor Weapons + Red Flame)'],
        268: locations_dict['Shop Slot: Silver Mail (Harbor Weapons + Red Flame)'],
        270: locations_dict['Shop Slot: Silver Boots (Harbor Weapons + Red Flame)'],
    },
    "Harbor North Weapons": {
        204: locations_dict['Shop Slot: Steel Goggles (Harbor North Weapons)'],
        205: locations_dict['Shop Slot: Steel Edge (Harbor North Weapons)'],
        206: locations_dict['Shop Slot: Steel Mail (Harbor North Weapons)'],
        207: locations_dict['Shop Slot: Steel Boots (Harbor North Weapons)'],
        264: locations_dict['Shop Slot: Silver Goggles (Harbor North Weapons)'],
        266: locations_dict['Shop Slot: Silver Edge (Harbor North Weapons)'],
        268: locations_dict['Shop Slot: Silver Mail (Harbor North Weapons)'],
        270: locations_dict['Shop Slot: Silver Boots (Harbor North Weapons)'],
    },
    "Tara's Shop": {
        1: locations_dict["Shop Slot: Sandwich (Tara's Shop)"],
    },
    "Harbor Backer Items": {
        382: locations_dict['Shop Slot: Rising Super Star (Harbor Backer Items)'],
        490: locations_dict['Shop Slot: Dk Pepper (Harbor Backer Items)'],
        491: locations_dict['Shop Slot: Cheese Spaetzle (Harbor Backer Items)'],
        315: locations_dict['Shop Slot: Maultasche (Harbor Backer Items)'],
        493: locations_dict['Shop Slot: Durian (Harbor Backer Items)'],
        494: locations_dict['Shop Slot: PengoPop (Harbor Backer Items)'],
        495: locations_dict['Shop Slot: Spicy Beat-0-Type (Harbor Backer Items)'],
        316: locations_dict['Shop Slot: Werewolf Stick (Harbor Backer Items)'],
        516: locations_dict['Shop Slot: Mooncake (Harbor Backer Items)'],
        496: locations_dict['Shop Slot: Guacamole Toast (Harbor Backer Items)'],
        551: locations_dict['Shop Slot: Willis Waldmahl (Harbor Backer Items)'],
        637: locations_dict['Shop Slot: Pumpkin Spice Cof. (Harbor Backer Items)'],
    },
    "Bergen Items": {
        1: locations_dict['Shop Slot: Sandwich (Bergen Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Bergen Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Bergen Items)'],
        366: locations_dict['Shop Slot: Just Water (Bergen Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Bergen Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Bergen Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Bergen Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Bergen Items)'],
    },
    "Bergen Items + Blue Ice": {
        353: locations_dict['Shop Slot: Kebab Roll (Bergen Items + Blue Ice)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Bergen Items + Blue Ice)'],
    },
    "Bergen Items + Red Flame": {
        110: locations_dict['Shop Slot: Bergen Ice Cream (Bergen Items + Red Flame)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Bergen Items + Red Flame)'],
    },
    "Bergen Items + Green Seed": {
        290: locations_dict['Shop Slot: Salted Peanuts (Bergen Items + Green Seed)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Bergen Items + Green Seed)"],
        331: locations_dict['Shop Slot: Snack Mix (Bergen Items + Green Seed)'],
    },
    "Bergen Weapons": {
        118: locations_dict['Shop Slot: Iron Goggles (Bergen Weapons)'],
        113: locations_dict['Shop Slot: Iron Edge (Bergen Weapons)'],
        122: locations_dict['Shop Slot: Iron Mail (Bergen Weapons)'],
        121: locations_dict['Shop Slot: Iron Boots (Bergen Weapons)'],
    },
    "Hermit's Hut": {
        77: locations_dict["Shop Slot: Chili Con Carne (Hermit's Hut)"],
        165: locations_dict["Shop Slot: Sweet Lemonjuice (Hermit's Hut)"],
        3: locations_dict["Shop Slot: Sweet Berry Tea (Hermit's Hut)"],
    },
    "Ba'kii Items": {
        1: locations_dict["Shop Slot: Sandwich (Ba'kii Items)"],
        27: locations_dict["Shop Slot: Hi-Sandwich (Ba'kii Items)"],
        2: locations_dict["Shop Slot: Green Leaf Tea (Ba'kii Items)"],
        366: locations_dict["Shop Slot: Just Water (Ba'kii Items)"],
        64: locations_dict["Shop Slot: Spicy Bun (Ba'kii Items)"],
        70: locations_dict["Shop Slot: Fruit Drink (Ba'kii Items)"],
        73: locations_dict["Shop Slot: Rice Cracker (Ba'kii Items)"],
        67: locations_dict["Shop Slot: Veggie Sticks (Ba'kii Items)"],
        110: locations_dict["Shop Slot: Bergen Ice Cream (Ba'kii Items)"],
        165: locations_dict["Shop Slot: Sweet Lemonjuice (Ba'kii Items)"],
    },
    "Ba'kii Items + Blue Ice": {
        353: locations_dict["Shop Slot: Kebab Roll (Ba'kii Items + Blue Ice)"],
        355: locations_dict["Shop Slot: Meaty Risotto (Ba'kii Items + Blue Ice)"],
    },
    "Ba'kii Items + Green Seed": {
        290: locations_dict["Shop Slot: Salted Peanuts (Ba'kii Items + Green Seed)"],
        291: locations_dict["Shop Slot: Cup o' Coffee (Ba'kii Items + Green Seed)"],
        331: locations_dict["Shop Slot: Snack Mix (Ba'kii Items + Green Seed)"],
    },
    "Ba'kii Weapons": {
        118: locations_dict["Shop Slot: Iron Goggles (Ba'kii Weapons)"],
        113: locations_dict["Shop Slot: Iron Edge (Ba'kii Weapons)"],
        122: locations_dict["Shop Slot: Iron Mail (Ba'kii Weapons)"],
        121: locations_dict["Shop Slot: Iron Boots (Ba'kii Weapons)"],
        204: locations_dict["Shop Slot: Steel Goggles (Ba'kii Weapons)"],
        205: locations_dict["Shop Slot: Steel Edge (Ba'kii Weapons)"],
        206: locations_dict["Shop Slot: Steel Mail (Ba'kii Weapons)"],
        207: locations_dict["Shop Slot: Steel Boots (Ba'kii Weapons)"],
    },
    "Basin Vending Machine": {
        1: locations_dict['Shop Slot: Sandwich (Basin Vending Machine)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Basin Vending Machine)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Basin Vending Machine)'],
        366: locations_dict['Shop Slot: Just Water (Basin Vending Machine)'],
        64: locations_dict['Shop Slot: Spicy Bun (Basin Vending Machine)'],
        70: locations_dict['Shop Slot: Fruit Drink (Basin Vending Machine)'],
        73: locations_dict['Shop Slot: Rice Cracker (Basin Vending Machine)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Basin Vending Machine)'],
        110: locations_dict['Shop Slot: Bergen Ice Cream (Basin Vending Machine)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Basin Vending Machine)'],
        290: locations_dict['Shop Slot: Salted Peanuts (Basin Vending Machine)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Basin Vending Machine)"],
        331: locations_dict['Shop Slot: Snack Mix (Basin Vending Machine)'],
        353: locations_dict['Shop Slot: Kebab Roll (Basin Vending Machine)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Basin Vending Machine)'],
    },
    "Basin Items": {
        1: locations_dict['Shop Slot: Sandwich (Basin Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Basin Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Basin Items)'],
        366: locations_dict['Shop Slot: Just Water (Basin Items)'],
        353: locations_dict['Shop Slot: Kebab Roll (Basin Items)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Basin Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Basin Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Basin Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Basin Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Basin Items)'],
        110: locations_dict['Shop Slot: Bergen Ice Cream (Basin Items)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Basin Items)'],
        290: locations_dict['Shop Slot: Salted Peanuts (Basin Items)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Basin Items)"],
        331: locations_dict['Shop Slot: Snack Mix (Basin Items)'],
    },
    "Basin Weapons": {
        264: locations_dict['Shop Slot: Silver Goggles (Basin Weapons)'],
        266: locations_dict['Shop Slot: Silver Edge (Basin Weapons)'],
        268: locations_dict['Shop Slot: Silver Mail (Basin Weapons)'],
        270: locations_dict['Shop Slot: Silver Boots (Basin Weapons)'],
        265: locations_dict['Shop Slot: Titan Goggles (Basin Weapons)'],
        267: locations_dict['Shop Slot: Titan Edge (Basin Weapons)'],
        269: locations_dict['Shop Slot: Titan Mail (Basin Weapons)'],
        271: locations_dict['Shop Slot: Titan Boots (Basin Weapons)'],
    },
    "Calzone Shop": {
        346: locations_dict['Shop Slot: One Up (Calzone Shop)'],
    },
    "Ridge Weapons": {
        265: locations_dict['Shop Slot: Titan Goggles (Ridge Weapons)'],
        267: locations_dict['Shop Slot: Titan Edge (Ridge Weapons)'],
        269: locations_dict['Shop Slot: Titan Mail (Ridge Weapons)'],
        271: locations_dict['Shop Slot: Titan Boots (Ridge Weapons)'],
        393: locations_dict['Shop Slot: Cobalt Goggles (Ridge Weapons)'],
        394: locations_dict['Shop Slot: Cobalt Edge (Ridge Weapons)'],
        395: locations_dict['Shop Slot: Cobalt Mail (Ridge Weapons)'],
        396: locations_dict['Shop Slot: Cobalt Boots (Ridge Weapons)'],
    },
    "Ridge Items": {
        1: locations_dict['Shop Slot: Sandwich (Ridge Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Ridge Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Ridge Items)'],
        366: locations_dict['Shop Slot: Just Water (Ridge Items)'],
        353: locations_dict['Shop Slot: Kebab Roll (Ridge Items)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Ridge Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Ridge Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Ridge Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Ridge Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Ridge Items)'],
        110: locations_dict['Shop Slot: Bergen Ice Cream (Ridge Items)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Ridge Items)'],
        290: locations_dict['Shop Slot: Salted Peanuts (Ridge Items)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Ridge Items)"],
        331: locations_dict['Shop Slot: Snack Mix (Ridge Items)'],
    },
    "Rhombus Weapons": {
        393: locations_dict['Shop Slot: Cobalt Goggles (Rhombus Weapons)'],
        394: locations_dict['Shop Slot: Cobalt Edge (Rhombus Weapons)'],
        395: locations_dict['Shop Slot: Cobalt Mail (Rhombus Weapons)'],
        396: locations_dict['Shop Slot: Cobalt Boots (Rhombus Weapons)'],
        397: locations_dict['Shop Slot: Laser Goggles (Rhombus Weapons)'],
        398: locations_dict['Shop Slot: Laser Edge (Rhombus Weapons)'],
        399: locations_dict['Shop Slot: Laser Mail (Rhombus Weapons)'],
        400: locations_dict['Shop Slot: Laser Boots (Rhombus Weapons)'],
    },
    "Rhombus Items": {
        1: locations_dict['Shop Slot: Sandwich (Rhombus Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Rhombus Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Rhombus Items)'],
        366: locations_dict['Shop Slot: Just Water (Rhombus Items)'],
        353: locations_dict['Shop Slot: Kebab Roll (Rhombus Items)'],
        355: locations_dict['Shop Slot: Meaty Risotto (Rhombus Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Rhombus Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Rhombus Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Rhombus Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Rhombus Items)'],
        110: locations_dict['Shop Slot: Bergen Ice Cream (Rhombus Items)'],
        165: locations_dict['Shop Slot: Sweet Lemonjuice (Rhombus Items)'],
        290: locations_dict['Shop Slot: Salted Peanuts (Rhombus Items)'],
        291: locations_dict["Shop Slot: Cup o' Coffee (Rhombus Items)"],
        331: locations_dict['Shop Slot: Snack Mix (Rhombus Items)'],
    },
    "Rhombus Curios": {
        501: locations_dict['Shop Slot: Chest Detector (Rhombus Curios)'],
    },
    "Rhombus Backer Items": {
        382: locations_dict['Shop Slot: Rising Super Star (Rhombus Backer Items)'],
        490: locations_dict['Shop Slot: Dk Pepper (Rhombus Backer Items)'],
        491: locations_dict['Shop Slot: Cheese Spaetzle (Rhombus Backer Items)'],
        315: locations_dict['Shop Slot: Maultasche (Rhombus Backer Items)'],
        493: locations_dict['Shop Slot: Durian (Rhombus Backer Items)'],
        494: locations_dict['Shop Slot: PengoPop (Rhombus Backer Items)'],
        495: locations_dict['Shop Slot: Spicy Beat-0-Type (Rhombus Backer Items)'],
        316: locations_dict['Shop Slot: Werewolf Stick (Rhombus Backer Items)'],
        516: locations_dict['Shop Slot: Mooncake (Rhombus Backer Items)'],
        496: locations_dict['Shop Slot: Guacamole Toast (Rhombus Backer Items)'],
        551: locations_dict['Shop Slot: Willis Waldmahl (Rhombus Backer Items)'],
        637: locations_dict['Shop Slot: Pumpkin Spice Cof. (Rhombus Backer Items)'],
    },
    "Vermillion Weapons": {
        204: locations_dict['Shop Slot: Steel Goggles (Vermillion Weapons)'],
        205: locations_dict['Shop Slot: Steel Edge (Vermillion Weapons)'],
        206: locations_dict['Shop Slot: Steel Mail (Vermillion Weapons)'],
        207: locations_dict['Shop Slot: Steel Boots (Vermillion Weapons)'],
        264: locations_dict['Shop Slot: Silver Goggles (Vermillion Weapons)'],
        266: locations_dict['Shop Slot: Silver Edge (Vermillion Weapons)'],
        268: locations_dict['Shop Slot: Silver Mail (Vermillion Weapons)'],
        270: locations_dict['Shop Slot: Silver Boots (Vermillion Weapons)'],
    },
    "Vermillion Items": {
        1: locations_dict['Shop Slot: Sandwich (Vermillion Items)'],
        27: locations_dict['Shop Slot: Hi-Sandwich (Vermillion Items)'],
        2: locations_dict['Shop Slot: Green Leaf Tea (Vermillion Items)'],
        366: locations_dict['Shop Slot: Just Water (Vermillion Items)'],
        64: locations_dict['Shop Slot: Spicy Bun (Vermillion Items)'],
        70: locations_dict['Shop Slot: Fruit Drink (Vermillion Items)'],
        73: locations_dict['Shop Slot: Rice Cracker (Vermillion Items)'],
        67: locations_dict['Shop Slot: Veggie Sticks (Vermillion Items)'],
    },
    
}

global_shop_locations: dict[int, LocationData] = {
    1: locations_dict['Global Shop Slot: Sandwich'],
    27: locations_dict['Global Shop Slot: Hi-Sandwich'],
    2: locations_dict['Global Shop Slot: Green Leaf Tea'],
    366: locations_dict['Global Shop Slot: Just Water'],
    64: locations_dict['Global Shop Slot: Spicy Bun'],
    70: locations_dict['Global Shop Slot: Fruit Drink'],
    73: locations_dict['Global Shop Slot: Rice Cracker'],
    67: locations_dict['Global Shop Slot: Veggie Sticks'],
    353: locations_dict['Global Shop Slot: Kebab Roll'],
    355: locations_dict['Global Shop Slot: Meaty Risotto'],
    110: locations_dict['Global Shop Slot: Bergen Ice Cream'],
    165: locations_dict['Global Shop Slot: Sweet Lemonjuice'],
    290: locations_dict['Global Shop Slot: Salted Peanuts'],
    291: locations_dict["Global Shop Slot: Cup o' Coffee"],
    331: locations_dict['Global Shop Slot: Snack Mix'],
    31: locations_dict['Global Shop Slot: Bronze Goggles'],
    29: locations_dict['Global Shop Slot: Bronze Edge'],
    30: locations_dict['Global Shop Slot: Bronze Mail'],
    32: locations_dict['Global Shop Slot: Bronze Boots'],
    118: locations_dict['Global Shop Slot: Iron Goggles'],
    113: locations_dict['Global Shop Slot: Iron Edge'],
    122: locations_dict['Global Shop Slot: Iron Mail'],
    121: locations_dict['Global Shop Slot: Iron Boots'],
    264: locations_dict['Global Shop Slot: Silver Goggles'],
    266: locations_dict['Global Shop Slot: Silver Edge'],
    268: locations_dict['Global Shop Slot: Silver Mail'],
    270: locations_dict['Global Shop Slot: Silver Boots'],
    204: locations_dict['Global Shop Slot: Steel Goggles'],
    205: locations_dict['Global Shop Slot: Steel Edge'],
    206: locations_dict['Global Shop Slot: Steel Mail'],
    207: locations_dict['Global Shop Slot: Steel Boots'],
    382: locations_dict['Global Shop Slot: Rising Super Star'],
    490: locations_dict['Global Shop Slot: Dk Pepper'],
    491: locations_dict['Global Shop Slot: Cheese Spaetzle'],
    315: locations_dict['Global Shop Slot: Maultasche'],
    493: locations_dict['Global Shop Slot: Durian'],
    494: locations_dict['Global Shop Slot: PengoPop'],
    495: locations_dict['Global Shop Slot: Spicy Beat-0-Type'],
    316: locations_dict['Global Shop Slot: Werewolf Stick'],
    516: locations_dict['Global Shop Slot: Mooncake'],
    496: locations_dict['Global Shop Slot: Guacamole Toast'],
    551: locations_dict['Global Shop Slot: Willis Waldmahl'],
    637: locations_dict['Global Shop Slot: Pumpkin Spice Cof.'],
    77: locations_dict['Global Shop Slot: Chili Con Carne'],
    3: locations_dict['Global Shop Slot: Sweet Berry Tea'],
    265: locations_dict['Global Shop Slot: Titan Goggles'],
    267: locations_dict['Global Shop Slot: Titan Edge'],
    269: locations_dict['Global Shop Slot: Titan Mail'],
    271: locations_dict['Global Shop Slot: Titan Boots'],
    346: locations_dict['Global Shop Slot: One Up'],
    393: locations_dict['Global Shop Slot: Cobalt Goggles'],
    394: locations_dict['Global Shop Slot: Cobalt Edge'],
    395: locations_dict['Global Shop Slot: Cobalt Mail'],
    396: locations_dict['Global Shop Slot: Cobalt Boots'],
    397: locations_dict['Global Shop Slot: Laser Goggles'],
    398: locations_dict['Global Shop Slot: Laser Edge'],
    399: locations_dict['Global Shop Slot: Laser Mail'],
    400: locations_dict['Global Shop Slot: Laser Boots'],
    501: locations_dict['Global Shop Slot: Chest Detector'],
}

shop_unlock_by_id = {
    1: items_dict['Global Slot Unlock: Sandwich', 1],
    27: items_dict['Global Slot Unlock: Hi-Sandwich', 1],
    2: items_dict['Global Slot Unlock: Green Leaf Tea', 1],
    366: items_dict['Global Slot Unlock: Just Water', 1],
    64: items_dict['Global Slot Unlock: Spicy Bun', 1],
    70: items_dict['Global Slot Unlock: Fruit Drink', 1],
    73: items_dict['Global Slot Unlock: Rice Cracker', 1],
    67: items_dict['Global Slot Unlock: Veggie Sticks', 1],
    353: items_dict['Global Slot Unlock: Kebab Roll', 1],
    355: items_dict['Global Slot Unlock: Meaty Risotto', 1],
    110: items_dict['Global Slot Unlock: Bergen Ice Cream', 1],
    165: items_dict['Global Slot Unlock: Sweet Lemonjuice', 1],
    290: items_dict['Global Slot Unlock: Salted Peanuts', 1],
    291: items_dict["Global Slot Unlock: Cup o' Coffee", 1],
    331: items_dict['Global Slot Unlock: Snack Mix', 1],
    31: items_dict['Global Slot Unlock: Bronze Goggles', 1],
    29: items_dict['Global Slot Unlock: Bronze Edge', 1],
    30: items_dict['Global Slot Unlock: Bronze Mail', 1],
    32: items_dict['Global Slot Unlock: Bronze Boots', 1],
    118: items_dict['Global Slot Unlock: Iron Goggles', 1],
    113: items_dict['Global Slot Unlock: Iron Edge', 1],
    122: items_dict['Global Slot Unlock: Iron Mail', 1],
    121: items_dict['Global Slot Unlock: Iron Boots', 1],
    264: items_dict['Global Slot Unlock: Silver Goggles', 1],
    266: items_dict['Global Slot Unlock: Silver Edge', 1],
    268: items_dict['Global Slot Unlock: Silver Mail', 1],
    270: items_dict['Global Slot Unlock: Silver Boots', 1],
    204: items_dict['Global Slot Unlock: Steel Goggles', 1],
    205: items_dict['Global Slot Unlock: Steel Edge', 1],
    206: items_dict['Global Slot Unlock: Steel Mail', 1],
    207: items_dict['Global Slot Unlock: Steel Boots', 1],
    382: items_dict['Global Slot Unlock: Rising Super Star', 1],
    490: items_dict['Global Slot Unlock: Dk Pepper', 1],
    491: items_dict['Global Slot Unlock: Cheese Spaetzle', 1],
    315: items_dict['Global Slot Unlock: Maultasche', 1],
    493: items_dict['Global Slot Unlock: Durian', 1],
    494: items_dict['Global Slot Unlock: PengoPop', 1],
    495: items_dict['Global Slot Unlock: Spicy Beat-0-Type', 1],
    316: items_dict['Global Slot Unlock: Werewolf Stick', 1],
    516: items_dict['Global Slot Unlock: Mooncake', 1],
    496: items_dict['Global Slot Unlock: Guacamole Toast', 1],
    551: items_dict['Global Slot Unlock: Willis Waldmahl', 1],
    637: items_dict['Global Slot Unlock: Pumpkin Spice Cof.', 1],
    77: items_dict['Global Slot Unlock: Chili Con Carne', 1],
    3: items_dict['Global Slot Unlock: Sweet Berry Tea', 1],
    265: items_dict['Global Slot Unlock: Titan Goggles', 1],
    267: items_dict['Global Slot Unlock: Titan Edge', 1],
    269: items_dict['Global Slot Unlock: Titan Mail', 1],
    271: items_dict['Global Slot Unlock: Titan Boots', 1],
    346: items_dict['Global Slot Unlock: One Up', 1],
    393: items_dict['Global Slot Unlock: Cobalt Goggles', 1],
    394: items_dict['Global Slot Unlock: Cobalt Edge', 1],
    395: items_dict['Global Slot Unlock: Cobalt Mail', 1],
    396: items_dict['Global Slot Unlock: Cobalt Boots', 1],
    397: items_dict['Global Slot Unlock: Laser Goggles', 1],
    398: items_dict['Global Slot Unlock: Laser Edge', 1],
    399: items_dict['Global Slot Unlock: Laser Mail', 1],
    400: items_dict['Global Slot Unlock: Laser Boots', 1],
    501: items_dict['Global Slot Unlock: Chest Detector', 1],
}

shop_unlock_by_shop = {
    'rookieHarborItems': items_dict['Shop Unlock: Harbor Items', 1],
    'rookieHarborWeapons': items_dict['Shop Unlock: Harbor Weapons', 1],
    'rookieHarborWeaponsNorth': items_dict['Shop Unlock: Harbor North Weapons', 1],
    'rookieHarborTara': items_dict["Shop Unlock: Tara's Shop", 1],
    'rookieBacker': items_dict['Shop Unlock: Harbor Backer Items', 1],
    'bergenVillageItems': items_dict['Shop Unlock: Bergen Items', 1],
    'bergenVillageWeapons': items_dict['Shop Unlock: Bergen Weapons', 1],
    'bergenHermit': items_dict["Shop Unlock: Hermit's Hut", 1],
    'bakiItems': items_dict["Shop Unlock: Ba'kii Items", 1],
    'bakiWeapons': items_dict["Shop Unlock: Ba'kii Weapons", 1],
    'basinVendingMachines': items_dict['Shop Unlock: Basin Vending Machine', 1],
    'basinItems': items_dict['Shop Unlock: Basin Items', 1],
    'basinWeapons': items_dict['Shop Unlock: Basin Weapons', 1],
    'basinMushroom': items_dict['Shop Unlock: Calzone Shop', 1],
    'sapphireWeapons': items_dict['Shop Unlock: Ridge Weapons', 1],
    'sapphireItems': items_dict['Shop Unlock: Ridge Items', 1],
    'rhombusWeapons1': items_dict['Shop Unlock: Rhombus Weapons', 1],
    'rhombusItems1': items_dict['Shop Unlock: Rhombus Items', 1],
    'rhombusCurios': items_dict['Shop Unlock: Rhombus Curios', 1],
    'rhombusBacker': items_dict['Shop Unlock: Rhombus Backer Items', 1],
    'aridWeapons': items_dict['Shop Unlock: Vermillion Weapons', 1],
    'aridItems': items_dict['Shop Unlock: Vermillion Items', 1],
}

shop_unlock_by_shop_and_id = {
    ('rookieHarborItems', 1): items_dict['Slot Unlock: Sandwich (Harbor Items)', 1],
    ('rookieHarborItems', 27): items_dict['Slot Unlock: Hi-Sandwich (Harbor Items)', 1],
    ('rookieHarborItems', 2): items_dict['Slot Unlock: Green Leaf Tea (Harbor Items)', 1],
    ('rookieHarborItems', 366): items_dict['Slot Unlock: Just Water (Harbor Items)', 1],
    ('rookieHarborItems', 64): items_dict['Slot Unlock: Spicy Bun (Harbor Items)', 1],
    ('rookieHarborItems', 70): items_dict['Slot Unlock: Fruit Drink (Harbor Items)', 1],
    ('rookieHarborItems', 73): items_dict['Slot Unlock: Rice Cracker (Harbor Items)', 1],
    ('rookieHarborItems', 67): items_dict['Slot Unlock: Veggie Sticks (Harbor Items)', 1],
    ('rookieHarborItems', 353): items_dict['Slot Unlock: Kebab Roll (Harbor Items + Blue Ice)', 1],
    ('rookieHarborItems', 355): items_dict['Slot Unlock: Meaty Risotto (Harbor Items + Blue Ice)', 1],
    ('rookieHarborItems', 110): items_dict['Slot Unlock: Bergen Ice Cream (Harbor Items + Red Flame)', 1],
    ('rookieHarborItems', 165): items_dict['Slot Unlock: Sweet Lemonjuice (Harbor Items + Red Flame)', 1],
    ('rookieHarborItems', 290): items_dict['Slot Unlock: Salted Peanuts (Harbor Items + Green Seed)', 1],
    ('rookieHarborItems', 291): items_dict["Slot Unlock: Cup o' Coffee (Harbor Items + Green Seed)", 1],
    ('rookieHarborItems', 331): items_dict['Slot Unlock: Snack Mix (Harbor Items + Green Seed)', 1],
    ('rookieHarborWeapons', 31): items_dict['Slot Unlock: Bronze Goggles (Harbor Weapons)', 1],
    ('rookieHarborWeapons', 29): items_dict['Slot Unlock: Bronze Edge (Harbor Weapons)', 1],
    ('rookieHarborWeapons', 30): items_dict['Slot Unlock: Bronze Mail (Harbor Weapons)', 1],
    ('rookieHarborWeapons', 32): items_dict['Slot Unlock: Bronze Boots (Harbor Weapons)', 1],
    ('rookieHarborWeapons', 118): items_dict['Slot Unlock: Iron Goggles (Harbor Weapons)', 1],
    ('rookieHarborWeapons', 113): items_dict['Slot Unlock: Iron Edge (Harbor Weapons)', 1],
    ('rookieHarborWeapons', 122): items_dict['Slot Unlock: Iron Mail (Harbor Weapons)', 1],
    ('rookieHarborWeapons', 121): items_dict['Slot Unlock: Iron Boots (Harbor Weapons)', 1],
    ('rookieHarborWeapons', 264): items_dict['Slot Unlock: Silver Goggles (Harbor Weapons + Red Flame)', 1],
    ('rookieHarborWeapons', 266): items_dict['Slot Unlock: Silver Edge (Harbor Weapons + Red Flame)', 1],
    ('rookieHarborWeapons', 268): items_dict['Slot Unlock: Silver Mail (Harbor Weapons + Red Flame)', 1],
    ('rookieHarborWeapons', 270): items_dict['Slot Unlock: Silver Boots (Harbor Weapons + Red Flame)', 1],
    ('rookieHarborWeaponsNorth', 204): items_dict['Slot Unlock: Steel Goggles (Harbor North Weapons)', 1],
    ('rookieHarborWeaponsNorth', 205): items_dict['Slot Unlock: Steel Edge (Harbor North Weapons)', 1],
    ('rookieHarborWeaponsNorth', 206): items_dict['Slot Unlock: Steel Mail (Harbor North Weapons)', 1],
    ('rookieHarborWeaponsNorth', 207): items_dict['Slot Unlock: Steel Boots (Harbor North Weapons)', 1],
    ('rookieHarborWeaponsNorth', 264): items_dict['Slot Unlock: Silver Goggles (Harbor North Weapons)', 1],
    ('rookieHarborWeaponsNorth', 266): items_dict['Slot Unlock: Silver Edge (Harbor North Weapons)', 1],
    ('rookieHarborWeaponsNorth', 268): items_dict['Slot Unlock: Silver Mail (Harbor North Weapons)', 1],
    ('rookieHarborWeaponsNorth', 270): items_dict['Slot Unlock: Silver Boots (Harbor North Weapons)', 1],
    ('rookieHarborTara', 1): items_dict["Slot Unlock: Sandwich (Tara's Shop)", 1],
    ('rookieBacker', 382): items_dict['Slot Unlock: Rising Super Star (Harbor Backer Items)', 1],
    ('rookieBacker', 490): items_dict['Slot Unlock: Dk Pepper (Harbor Backer Items)', 1],
    ('rookieBacker', 491): items_dict['Slot Unlock: Cheese Spaetzle (Harbor Backer Items)', 1],
    ('rookieBacker', 315): items_dict['Slot Unlock: Maultasche (Harbor Backer Items)', 1],
    ('rookieBacker', 493): items_dict['Slot Unlock: Durian (Harbor Backer Items)', 1],
    ('rookieBacker', 494): items_dict['Slot Unlock: PengoPop (Harbor Backer Items)', 1],
    ('rookieBacker', 495): items_dict['Slot Unlock: Spicy Beat-0-Type (Harbor Backer Items)', 1],
    ('rookieBacker', 316): items_dict['Slot Unlock: Werewolf Stick (Harbor Backer Items)', 1],
    ('rookieBacker', 516): items_dict['Slot Unlock: Mooncake (Harbor Backer Items)', 1],
    ('rookieBacker', 496): items_dict['Slot Unlock: Guacamole Toast (Harbor Backer Items)', 1],
    ('rookieBacker', 551): items_dict['Slot Unlock: Willis Waldmahl (Harbor Backer Items)', 1],
    ('rookieBacker', 637): items_dict['Slot Unlock: Pumpkin Spice Cof. (Harbor Backer Items)', 1],
    ('bergenVillageItems', 1): items_dict['Slot Unlock: Sandwich (Bergen Items)', 1],
    ('bergenVillageItems', 27): items_dict['Slot Unlock: Hi-Sandwich (Bergen Items)', 1],
    ('bergenVillageItems', 2): items_dict['Slot Unlock: Green Leaf Tea (Bergen Items)', 1],
    ('bergenVillageItems', 366): items_dict['Slot Unlock: Just Water (Bergen Items)', 1],
    ('bergenVillageItems', 64): items_dict['Slot Unlock: Spicy Bun (Bergen Items)', 1],
    ('bergenVillageItems', 70): items_dict['Slot Unlock: Fruit Drink (Bergen Items)', 1],
    ('bergenVillageItems', 73): items_dict['Slot Unlock: Rice Cracker (Bergen Items)', 1],
    ('bergenVillageItems', 67): items_dict['Slot Unlock: Veggie Sticks (Bergen Items)', 1],
    ('bergenVillageItems', 353): items_dict['Slot Unlock: Kebab Roll (Bergen Items + Blue Ice)', 1],
    ('bergenVillageItems', 355): items_dict['Slot Unlock: Meaty Risotto (Bergen Items + Blue Ice)', 1],
    ('bergenVillageItems', 110): items_dict['Slot Unlock: Bergen Ice Cream (Bergen Items + Red Flame)', 1],
    ('bergenVillageItems', 165): items_dict['Slot Unlock: Sweet Lemonjuice (Bergen Items + Red Flame)', 1],
    ('bergenVillageItems', 290): items_dict['Slot Unlock: Salted Peanuts (Bergen Items + Green Seed)', 1],
    ('bergenVillageItems', 291): items_dict["Slot Unlock: Cup o' Coffee (Bergen Items + Green Seed)", 1],
    ('bergenVillageItems', 331): items_dict['Slot Unlock: Snack Mix (Bergen Items + Green Seed)', 1],
    ('bergenVillageWeapons', 118): items_dict['Slot Unlock: Iron Goggles (Bergen Weapons)', 1],
    ('bergenVillageWeapons', 113): items_dict['Slot Unlock: Iron Edge (Bergen Weapons)', 1],
    ('bergenVillageWeapons', 122): items_dict['Slot Unlock: Iron Mail (Bergen Weapons)', 1],
    ('bergenVillageWeapons', 121): items_dict['Slot Unlock: Iron Boots (Bergen Weapons)', 1],
    ('bergenHermit', 77): items_dict["Slot Unlock: Chili Con Carne (Hermit's Hut)", 1],
    ('bergenHermit', 165): items_dict["Slot Unlock: Sweet Lemonjuice (Hermit's Hut)", 1],
    ('bergenHermit', 3): items_dict["Slot Unlock: Sweet Berry Tea (Hermit's Hut)", 1],
    ('bakiItems', 1): items_dict["Slot Unlock: Sandwich (Ba'kii Items)", 1],
    ('bakiItems', 27): items_dict["Slot Unlock: Hi-Sandwich (Ba'kii Items)", 1],
    ('bakiItems', 2): items_dict["Slot Unlock: Green Leaf Tea (Ba'kii Items)", 1],
    ('bakiItems', 366): items_dict["Slot Unlock: Just Water (Ba'kii Items)", 1],
    ('bakiItems', 64): items_dict["Slot Unlock: Spicy Bun (Ba'kii Items)", 1],
    ('bakiItems', 70): items_dict["Slot Unlock: Fruit Drink (Ba'kii Items)", 1],
    ('bakiItems', 73): items_dict["Slot Unlock: Rice Cracker (Ba'kii Items)", 1],
    ('bakiItems', 67): items_dict["Slot Unlock: Veggie Sticks (Ba'kii Items)", 1],
    ('bakiItems', 110): items_dict["Slot Unlock: Bergen Ice Cream (Ba'kii Items)", 1],
    ('bakiItems', 165): items_dict["Slot Unlock: Sweet Lemonjuice (Ba'kii Items)", 1],
    ('bakiItems', 353): items_dict["Slot Unlock: Kebab Roll (Ba'kii Items + Blue Ice)", 1],
    ('bakiItems', 355): items_dict["Slot Unlock: Meaty Risotto (Ba'kii Items + Blue Ice)", 1],
    ('bakiItems', 290): items_dict["Slot Unlock: Salted Peanuts (Ba'kii Items + Green Seed)", 1],
    ('bakiItems', 291): items_dict["Slot Unlock: Cup o' Coffee (Ba'kii Items + Green Seed)", 1],
    ('bakiItems', 331): items_dict["Slot Unlock: Snack Mix (Ba'kii Items + Green Seed)", 1],
    ('bakiWeapons', 118): items_dict["Slot Unlock: Iron Goggles (Ba'kii Weapons)", 1],
    ('bakiWeapons', 113): items_dict["Slot Unlock: Iron Edge (Ba'kii Weapons)", 1],
    ('bakiWeapons', 122): items_dict["Slot Unlock: Iron Mail (Ba'kii Weapons)", 1],
    ('bakiWeapons', 121): items_dict["Slot Unlock: Iron Boots (Ba'kii Weapons)", 1],
    ('bakiWeapons', 204): items_dict["Slot Unlock: Steel Goggles (Ba'kii Weapons)", 1],
    ('bakiWeapons', 205): items_dict["Slot Unlock: Steel Edge (Ba'kii Weapons)", 1],
    ('bakiWeapons', 206): items_dict["Slot Unlock: Steel Mail (Ba'kii Weapons)", 1],
    ('bakiWeapons', 207): items_dict["Slot Unlock: Steel Boots (Ba'kii Weapons)", 1],
    ('basinVendingMachines', 1): items_dict['Slot Unlock: Sandwich (Basin Vending Machine)', 1],
    ('basinVendingMachines', 27): items_dict['Slot Unlock: Hi-Sandwich (Basin Vending Machine)', 1],
    ('basinVendingMachines', 2): items_dict['Slot Unlock: Green Leaf Tea (Basin Vending Machine)', 1],
    ('basinVendingMachines', 366): items_dict['Slot Unlock: Just Water (Basin Vending Machine)', 1],
    ('basinVendingMachines', 64): items_dict['Slot Unlock: Spicy Bun (Basin Vending Machine)', 1],
    ('basinVendingMachines', 70): items_dict['Slot Unlock: Fruit Drink (Basin Vending Machine)', 1],
    ('basinVendingMachines', 73): items_dict['Slot Unlock: Rice Cracker (Basin Vending Machine)', 1],
    ('basinVendingMachines', 67): items_dict['Slot Unlock: Veggie Sticks (Basin Vending Machine)', 1],
    ('basinVendingMachines', 110): items_dict['Slot Unlock: Bergen Ice Cream (Basin Vending Machine)', 1],
    ('basinVendingMachines', 165): items_dict['Slot Unlock: Sweet Lemonjuice (Basin Vending Machine)', 1],
    ('basinVendingMachines', 290): items_dict['Slot Unlock: Salted Peanuts (Basin Vending Machine)', 1],
    ('basinVendingMachines', 291): items_dict["Slot Unlock: Cup o' Coffee (Basin Vending Machine)", 1],
    ('basinVendingMachines', 331): items_dict['Slot Unlock: Snack Mix (Basin Vending Machine)', 1],
    ('basinVendingMachines', 353): items_dict['Slot Unlock: Kebab Roll (Basin Vending Machine)', 1],
    ('basinVendingMachines', 355): items_dict['Slot Unlock: Meaty Risotto (Basin Vending Machine)', 1],
    ('basinItems', 1): items_dict['Slot Unlock: Sandwich (Basin Items)', 1],
    ('basinItems', 27): items_dict['Slot Unlock: Hi-Sandwich (Basin Items)', 1],
    ('basinItems', 2): items_dict['Slot Unlock: Green Leaf Tea (Basin Items)', 1],
    ('basinItems', 366): items_dict['Slot Unlock: Just Water (Basin Items)', 1],
    ('basinItems', 353): items_dict['Slot Unlock: Kebab Roll (Basin Items)', 1],
    ('basinItems', 355): items_dict['Slot Unlock: Meaty Risotto (Basin Items)', 1],
    ('basinItems', 64): items_dict['Slot Unlock: Spicy Bun (Basin Items)', 1],
    ('basinItems', 70): items_dict['Slot Unlock: Fruit Drink (Basin Items)', 1],
    ('basinItems', 73): items_dict['Slot Unlock: Rice Cracker (Basin Items)', 1],
    ('basinItems', 67): items_dict['Slot Unlock: Veggie Sticks (Basin Items)', 1],
    ('basinItems', 110): items_dict['Slot Unlock: Bergen Ice Cream (Basin Items)', 1],
    ('basinItems', 165): items_dict['Slot Unlock: Sweet Lemonjuice (Basin Items)', 1],
    ('basinItems', 290): items_dict['Slot Unlock: Salted Peanuts (Basin Items)', 1],
    ('basinItems', 291): items_dict["Slot Unlock: Cup o' Coffee (Basin Items)", 1],
    ('basinItems', 331): items_dict['Slot Unlock: Snack Mix (Basin Items)', 1],
    ('basinWeapons', 264): items_dict['Slot Unlock: Silver Goggles (Basin Weapons)', 1],
    ('basinWeapons', 266): items_dict['Slot Unlock: Silver Edge (Basin Weapons)', 1],
    ('basinWeapons', 268): items_dict['Slot Unlock: Silver Mail (Basin Weapons)', 1],
    ('basinWeapons', 270): items_dict['Slot Unlock: Silver Boots (Basin Weapons)', 1],
    ('basinWeapons', 265): items_dict['Slot Unlock: Titan Goggles (Basin Weapons)', 1],
    ('basinWeapons', 267): items_dict['Slot Unlock: Titan Edge (Basin Weapons)', 1],
    ('basinWeapons', 269): items_dict['Slot Unlock: Titan Mail (Basin Weapons)', 1],
    ('basinWeapons', 271): items_dict['Slot Unlock: Titan Boots (Basin Weapons)', 1],
    ('basinMushroom', 346): items_dict['Slot Unlock: One Up (Calzone Shop)', 1],
    ('sapphireWeapons', 265): items_dict['Slot Unlock: Titan Goggles (Ridge Weapons)', 1],
    ('sapphireWeapons', 267): items_dict['Slot Unlock: Titan Edge (Ridge Weapons)', 1],
    ('sapphireWeapons', 269): items_dict['Slot Unlock: Titan Mail (Ridge Weapons)', 1],
    ('sapphireWeapons', 271): items_dict['Slot Unlock: Titan Boots (Ridge Weapons)', 1],
    ('sapphireWeapons', 393): items_dict['Slot Unlock: Cobalt Goggles (Ridge Weapons)', 1],
    ('sapphireWeapons', 394): items_dict['Slot Unlock: Cobalt Edge (Ridge Weapons)', 1],
    ('sapphireWeapons', 395): items_dict['Slot Unlock: Cobalt Mail (Ridge Weapons)', 1],
    ('sapphireWeapons', 396): items_dict['Slot Unlock: Cobalt Boots (Ridge Weapons)', 1],
    ('sapphireItems', 1): items_dict['Slot Unlock: Sandwich (Ridge Items)', 1],
    ('sapphireItems', 27): items_dict['Slot Unlock: Hi-Sandwich (Ridge Items)', 1],
    ('sapphireItems', 2): items_dict['Slot Unlock: Green Leaf Tea (Ridge Items)', 1],
    ('sapphireItems', 366): items_dict['Slot Unlock: Just Water (Ridge Items)', 1],
    ('sapphireItems', 353): items_dict['Slot Unlock: Kebab Roll (Ridge Items)', 1],
    ('sapphireItems', 355): items_dict['Slot Unlock: Meaty Risotto (Ridge Items)', 1],
    ('sapphireItems', 64): items_dict['Slot Unlock: Spicy Bun (Ridge Items)', 1],
    ('sapphireItems', 70): items_dict['Slot Unlock: Fruit Drink (Ridge Items)', 1],
    ('sapphireItems', 73): items_dict['Slot Unlock: Rice Cracker (Ridge Items)', 1],
    ('sapphireItems', 67): items_dict['Slot Unlock: Veggie Sticks (Ridge Items)', 1],
    ('sapphireItems', 110): items_dict['Slot Unlock: Bergen Ice Cream (Ridge Items)', 1],
    ('sapphireItems', 165): items_dict['Slot Unlock: Sweet Lemonjuice (Ridge Items)', 1],
    ('sapphireItems', 290): items_dict['Slot Unlock: Salted Peanuts (Ridge Items)', 1],
    ('sapphireItems', 291): items_dict["Slot Unlock: Cup o' Coffee (Ridge Items)", 1],
    ('sapphireItems', 331): items_dict['Slot Unlock: Snack Mix (Ridge Items)', 1],
    ('rhombusWeapons1', 393): items_dict['Slot Unlock: Cobalt Goggles (Rhombus Weapons)', 1],
    ('rhombusWeapons1', 394): items_dict['Slot Unlock: Cobalt Edge (Rhombus Weapons)', 1],
    ('rhombusWeapons1', 395): items_dict['Slot Unlock: Cobalt Mail (Rhombus Weapons)', 1],
    ('rhombusWeapons1', 396): items_dict['Slot Unlock: Cobalt Boots (Rhombus Weapons)', 1],
    ('rhombusWeapons1', 397): items_dict['Slot Unlock: Laser Goggles (Rhombus Weapons)', 1],
    ('rhombusWeapons1', 398): items_dict['Slot Unlock: Laser Edge (Rhombus Weapons)', 1],
    ('rhombusWeapons1', 399): items_dict['Slot Unlock: Laser Mail (Rhombus Weapons)', 1],
    ('rhombusWeapons1', 400): items_dict['Slot Unlock: Laser Boots (Rhombus Weapons)', 1],
    ('rhombusItems1', 1): items_dict['Slot Unlock: Sandwich (Rhombus Items)', 1],
    ('rhombusItems1', 27): items_dict['Slot Unlock: Hi-Sandwich (Rhombus Items)', 1],
    ('rhombusItems1', 2): items_dict['Slot Unlock: Green Leaf Tea (Rhombus Items)', 1],
    ('rhombusItems1', 366): items_dict['Slot Unlock: Just Water (Rhombus Items)', 1],
    ('rhombusItems1', 353): items_dict['Slot Unlock: Kebab Roll (Rhombus Items)', 1],
    ('rhombusItems1', 355): items_dict['Slot Unlock: Meaty Risotto (Rhombus Items)', 1],
    ('rhombusItems1', 64): items_dict['Slot Unlock: Spicy Bun (Rhombus Items)', 1],
    ('rhombusItems1', 70): items_dict['Slot Unlock: Fruit Drink (Rhombus Items)', 1],
    ('rhombusItems1', 73): items_dict['Slot Unlock: Rice Cracker (Rhombus Items)', 1],
    ('rhombusItems1', 67): items_dict['Slot Unlock: Veggie Sticks (Rhombus Items)', 1],
    ('rhombusItems1', 110): items_dict['Slot Unlock: Bergen Ice Cream (Rhombus Items)', 1],
    ('rhombusItems1', 165): items_dict['Slot Unlock: Sweet Lemonjuice (Rhombus Items)', 1],
    ('rhombusItems1', 290): items_dict['Slot Unlock: Salted Peanuts (Rhombus Items)', 1],
    ('rhombusItems1', 291): items_dict["Slot Unlock: Cup o' Coffee (Rhombus Items)", 1],
    ('rhombusItems1', 331): items_dict['Slot Unlock: Snack Mix (Rhombus Items)', 1],
    ('rhombusCurios', 501): items_dict['Slot Unlock: Chest Detector (Rhombus Curios)', 1],
    ('rhombusBacker', 382): items_dict['Slot Unlock: Rising Super Star (Rhombus Backer Items)', 1],
    ('rhombusBacker', 490): items_dict['Slot Unlock: Dk Pepper (Rhombus Backer Items)', 1],
    ('rhombusBacker', 491): items_dict['Slot Unlock: Cheese Spaetzle (Rhombus Backer Items)', 1],
    ('rhombusBacker', 315): items_dict['Slot Unlock: Maultasche (Rhombus Backer Items)', 1],
    ('rhombusBacker', 493): items_dict['Slot Unlock: Durian (Rhombus Backer Items)', 1],
    ('rhombusBacker', 494): items_dict['Slot Unlock: PengoPop (Rhombus Backer Items)', 1],
    ('rhombusBacker', 495): items_dict['Slot Unlock: Spicy Beat-0-Type (Rhombus Backer Items)', 1],
    ('rhombusBacker', 316): items_dict['Slot Unlock: Werewolf Stick (Rhombus Backer Items)', 1],
    ('rhombusBacker', 516): items_dict['Slot Unlock: Mooncake (Rhombus Backer Items)', 1],
    ('rhombusBacker', 496): items_dict['Slot Unlock: Guacamole Toast (Rhombus Backer Items)', 1],
    ('rhombusBacker', 551): items_dict['Slot Unlock: Willis Waldmahl (Rhombus Backer Items)', 1],
    ('rhombusBacker', 637): items_dict['Slot Unlock: Pumpkin Spice Cof. (Rhombus Backer Items)', 1],
    ('aridWeapons', 204): items_dict['Slot Unlock: Steel Goggles (Vermillion Weapons)', 1],
    ('aridWeapons', 205): items_dict['Slot Unlock: Steel Edge (Vermillion Weapons)', 1],
    ('aridWeapons', 206): items_dict['Slot Unlock: Steel Mail (Vermillion Weapons)', 1],
    ('aridWeapons', 207): items_dict['Slot Unlock: Steel Boots (Vermillion Weapons)', 1],
    ('aridWeapons', 264): items_dict['Slot Unlock: Silver Goggles (Vermillion Weapons)', 1],
    ('aridWeapons', 266): items_dict['Slot Unlock: Silver Edge (Vermillion Weapons)', 1],
    ('aridWeapons', 268): items_dict['Slot Unlock: Silver Mail (Vermillion Weapons)', 1],
    ('aridWeapons', 270): items_dict['Slot Unlock: Silver Boots (Vermillion Weapons)', 1],
    ('aridItems', 1): items_dict['Slot Unlock: Sandwich (Vermillion Items)', 1],
    ('aridItems', 27): items_dict['Slot Unlock: Hi-Sandwich (Vermillion Items)', 1],
    ('aridItems', 2): items_dict['Slot Unlock: Green Leaf Tea (Vermillion Items)', 1],
    ('aridItems', 366): items_dict['Slot Unlock: Just Water (Vermillion Items)', 1],
    ('aridItems', 64): items_dict['Slot Unlock: Spicy Bun (Vermillion Items)', 1],
    ('aridItems', 70): items_dict['Slot Unlock: Fruit Drink (Vermillion Items)', 1],
    ('aridItems', 73): items_dict['Slot Unlock: Rice Cracker (Vermillion Items)', 1],
    ('aridItems', 67): items_dict['Slot Unlock: Veggie Sticks (Vermillion Items)', 1],
}