from .rom_addresses import rom_addresses
from .regions import map_ids

music_pointers = {
    "MUSIC_PALLET_TOWN": 47618,
    "MUSIC_CITIES1": 49922,
    "MUSIC_CITIES2": 50946,
    "MUSIC_LAVENDER": 54274,
    "MUSIC_VERMILION": 53250,
    "MUSIC_CELADON": 51714,
    "MUSIC_CINNABAR": 52482,
    "MUSIC_INDIGO_PLATEAU": 64258,
    "MUSIC_ROUTES1": 60162,
    "MUSIC_ROUTES3": 62210,
    "MUSIC_ROUTES4": 63234,
    "MUSIC_ROUTES2": 61186,
    "MUSIC_OAKS_LAB": 52511,
    "MUSIC_POKECENTER": 48386,
    "MUSIC_GYM": 49154,
    "MUSIC_DUNGEON2": 58399,
    "MUSIC_DUNGEON3": 59423,
    "MUSIC_DUNGEON1": 57375,
    "MUSIC_SS_ANNE": 55298,
    "MUSIC_POKEMON_TOWER": 61471,
    "MUSIC_SILPH_CO": 62239,
    "MUSIC_GAME_CORNER": 55583,
    "MUSIC_CINNABAR_MANSION": 60447,
    "MUSIC_SAFARI_ZONE": 58626
}
default_music = {
    "Pallet Town": "MUSIC_PALLET_TOWN",
    "Viridian City": "MUSIC_CITIES1",
    "Pewter City": "MUSIC_CITIES1",
    "Cerulean City": "MUSIC_CITIES2",
    "Lavender Town": "MUSIC_LAVENDER",
    "Vermilion City": "MUSIC_VERMILION",
    "Celadon City": "MUSIC_CELADON",
    "Fuchsia City": "MUSIC_CITIES2",
    "Cinnabar Island": "MUSIC_CINNABAR",
    "Indigo Plateau": "MUSIC_INDIGO_PLATEAU",
    "Saffron City": "MUSIC_CITIES1",
    "Route 1": "MUSIC_ROUTES1",
    "Route 2": "MUSIC_ROUTES1",
    "Route 3": "MUSIC_ROUTES3",
    "Route 4": "MUSIC_ROUTES3",
    "Route 5": "MUSIC_ROUTES3",
    "Route 6": "MUSIC_ROUTES3",
    "Route 7": "MUSIC_ROUTES3",
    "Route 8": "MUSIC_ROUTES3",
    "Route 9": "MUSIC_ROUTES3",
    "Route 10": "MUSIC_ROUTES3",
    "Route 11": "MUSIC_ROUTES4",
    "Route 12": "MUSIC_ROUTES4",
    "Route 13": "MUSIC_ROUTES4",
    "Route 14": "MUSIC_ROUTES4",
    "Route 15": "MUSIC_ROUTES4",
    "Route 16": "MUSIC_ROUTES3",
    "Route 17": "MUSIC_ROUTES3",
    "Route 18": "MUSIC_ROUTES3",
    "Route 19": "MUSIC_ROUTES3",
    "Route 20": "MUSIC_ROUTES3",
    "Route 21": "MUSIC_ROUTES3",
    "Route 22": "MUSIC_ROUTES3",
    "Route 23": "MUSIC_INDIGO_PLATEAU",
    "Route 24": "MUSIC_ROUTES2",
    "Route 25": "MUSIC_ROUTES2",
    "Player's House 1F": "MUSIC_PALLET_TOWN",
    "Player's House 2F": "MUSIC_PALLET_TOWN",
    "Rival's House": "MUSIC_PALLET_TOWN",
    "Oak's Lab": "MUSIC_OAKS_LAB",
    "Viridian Pokemon Center": "MUSIC_POKECENTER",
    "Viridian Pokemart": "MUSIC_POKECENTER",
    "Viridian School House": "MUSIC_CITIES1",
    "Viridian Nickname House": "MUSIC_CITIES1",
    "Viridian Gym": "MUSIC_GYM",
    "Diglett's Cave Route 2": "MUSIC_DUNGEON2",
    "Viridian Forest North Gate": "MUSIC_CITIES1",
    "Route 2 Trade House": "MUSIC_CITIES1",
    "Route 2 Gate": "MUSIC_CITIES1",
    "Viridian Forest South Gate": "MUSIC_CITIES1",
    "Viridian Forest": "MUSIC_DUNGEON2",
    "Pewter Museum 1F": "MUSIC_CITIES1",
    "Pewter Museum 2F": "MUSIC_CITIES1",
    "Pewter Gym": "MUSIC_GYM",
    "Pewter Nidoran House": "MUSIC_CITIES1",
    "Pewter Pokemart": "MUSIC_POKECENTER",
    "Pewter Speech House": "MUSIC_CITIES1",
    "Pewter Pokemon Center": "MUSIC_POKECENTER",
    "Mt Moon 1F": "MUSIC_DUNGEON3",
    "Mt Moon B1F": "MUSIC_DUNGEON3",
    "Mt Moon B2F": "MUSIC_DUNGEON3",
    "Cerulean Trashed House": "MUSIC_CITIES2",
    "Cerulean Trade House": "MUSIC_CITIES2",
    "Cerulean Pokemon Center": "MUSIC_POKECENTER",
    "Cerulean Gym": "MUSIC_GYM",
    "Cerulean Bicycle Shop": "MUSIC_CITIES2",
    "Cerulean Pokemart": "MUSIC_POKECENTER",
    "Route 4 Pokemon Center": "MUSIC_POKECENTER",
    "Route 5 Gate": "MUSIC_CITIES1",
    "Underground Path Route 5": "MUSIC_CITIES1",
    "Daycare": "MUSIC_CITIES1",
    "Route 6 Gate": "MUSIC_CITIES1",
    "Underground Path Route 6": "MUSIC_CITIES1",
    "Route 7 Gate": "MUSIC_CITIES1",
    "Underground Path Route 7": "MUSIC_CITIES1",
    "Route 8 Gate": "MUSIC_CITIES1",
    "Underground Path Route 8": "MUSIC_CITIES1",
    "Rock Tunnel Pokemon Center": "MUSIC_POKECENTER",
    "Rock Tunnel 1F": "MUSIC_DUNGEON3",
    "Power Plant": "MUSIC_DUNGEON1",
    "Route 11 Gate 1F": "MUSIC_VERMILION",
    "Diglett's Cave Route 11": "MUSIC_DUNGEON2",
    "Route 11 Gate 2F": "MUSIC_VERMILION",
    "Route 12 Gate 1F": "MUSIC_CITIES1",
    "Bill's House": "MUSIC_CITIES2",
    "Vermilion Pokemon Center": "MUSIC_POKECENTER",
    "Vermilion Pokemon Fan Club": "MUSIC_VERMILION",
    "Vermilion Pokemart": "MUSIC_POKECENTER",
    "Vermilion Gym": "MUSIC_GYM",
    "Vermilion Pidgey House": "MUSIC_VERMILION",
    "Vermilion Dock": "MUSIC_SS_ANNE",
    "S.S. Anne 1F": "MUSIC_SS_ANNE",
    "S.S. Anne 2F": "MUSIC_SS_ANNE",
    "S.S. Anne 3F": "MUSIC_SS_ANNE",
    "S.S. Anne B1F": "MUSIC_SS_ANNE",
    "S.S. Anne Bow": "MUSIC_SS_ANNE",
    "S.S. Anne Kitchen": "MUSIC_SS_ANNE",
    "S.S. Anne Captain's Room": "MUSIC_SS_ANNE",
    "S.S. Anne 1F Rooms": "MUSIC_SS_ANNE",
    "S.S. Anne 2F Rooms": "MUSIC_SS_ANNE",
    "S.S. Anne B1F Rooms": "MUSIC_SS_ANNE",
    "Victory Road 1F": "MUSIC_DUNGEON3",
    "Indigo Plateau Lance's Room": "MUSIC_INDIGO_PLATEAU",
    "Indigo Plateau Hall of Fame": "MUSIC_PALLET_TOWN",
    "Underground Path North South": "MUSIC_ROUTES1",
    "Indigo Plateau Champion's Room": "MUSIC_INDIGO_PLATEAU",
    "Underground Path West East": "MUSIC_ROUTES1",
    "Celadon Department Store 1F": "MUSIC_POKECENTER",
    "Celadon Department Store 2F": "MUSIC_POKECENTER",
    "Celadon Department Store 3F": "MUSIC_POKECENTER",
    "Celadon Department Store 4F": "MUSIC_POKECENTER",
    "Celadon Department Store Roof": "MUSIC_POKECENTER",
    "Celadon Department Store Elevator": "MUSIC_POKECENTER",
    "Celadon Mansion 1F": "MUSIC_CELADON",
    "Celadon Mansion 2F": "MUSIC_CELADON",
    "Celadon Mansion 3F": "MUSIC_CELADON",
    "Celadon Mansion Roof": "MUSIC_CELADON",
    "Celadon Mansion Roof House": "MUSIC_CELADON",
    "Celadon Pokemon Center": "MUSIC_POKECENTER",
    "Celadon Gym": "MUSIC_GYM",
    "Celadon Game Corner": "MUSIC_GAME_CORNER",
    "Celadon Department Store 5F": "MUSIC_POKECENTER",
    "Celadon Prize Corner": "MUSIC_CELADON",
    "Celadon Diner": "MUSIC_CELADON",
    "Celadon Chief House": "MUSIC_CELADON",
    "Celadon Hotel": "MUSIC_CELADON",
    "Lavender Pokemon Center": "MUSIC_POKECENTER",
    "Pokemon Tower 1F": "MUSIC_POKEMON_TOWER",
    "Pokemon Tower 2F": "MUSIC_POKEMON_TOWER",
    "Pokemon Tower 3F": "MUSIC_POKEMON_TOWER",
    "Pokemon Tower 4F": "MUSIC_POKEMON_TOWER",
    "Pokemon Tower 5F": "MUSIC_POKEMON_TOWER",
    "Pokemon Tower 6F": "MUSIC_POKEMON_TOWER",
    "Pokemon Tower 7F": "MUSIC_POKEMON_TOWER",
    "Lavender Mr. Fuji's House": "MUSIC_LAVENDER",
    "Lavender Pokemart": "MUSIC_POKECENTER",
    "Lavender Cubone House": "MUSIC_LAVENDER",
    "Fuchsia Pokemart": "MUSIC_POKECENTER",
    "Fuchsia Bill's Grandpa's House": "MUSIC_CITIES2",
    "Fuchsia Pokemon Center": "MUSIC_POKECENTER",
    "Fuchsia Warden's House": "MUSIC_CITIES2",
    "Safari Zone Gate": "MUSIC_CITIES2",
    "Fuchsia Gym": "MUSIC_GYM",
    "Fuchsia Meeting Room": "MUSIC_CITIES2",
    "Seafoam Islands B1F": "MUSIC_DUNGEON2",
    "Seafoam Islands B2F": "MUSIC_DUNGEON2",
    "Seafoam Islands B3F": "MUSIC_DUNGEON2",
    "Seafoam Islands B4F": "MUSIC_DUNGEON2",
    "Vermilion Old Rod House": "MUSIC_CITIES2",
    "Fuchsia Good Rod House": "MUSIC_CITIES2",
    "Pokemon Mansion 1F": "MUSIC_CINNABAR_MANSION",
    "Cinnabar Gym": "MUSIC_GYM",
    "Cinnabar Lab": "MUSIC_CINNABAR",
    "Cinnabar Lab Trade Room": "MUSIC_CINNABAR",
    "Cinnabar Lab R&D Room": "MUSIC_CINNABAR",
    "Cinnabar Lab Fossil Room": "MUSIC_CINNABAR",
    "Cinnabar Pokemon Center": "MUSIC_POKECENTER",
    "Cinnabar Pokemart": "MUSIC_POKECENTER",
    "Indigo Plateau Lobby": "MUSIC_INDIGO_PLATEAU",
    "Saffron Copycat's House 1F": "MUSIC_CITIES1",
    "Saffron Copycat's House 2F": "MUSIC_CITIES1",
    "Saffron Fighting Dojo": "MUSIC_CITIES1",
    "Saffron Gym": "MUSIC_GYM",
    "Saffron Pidgey House": "MUSIC_CITIES1",
    "Saffron Pokemart": "MUSIC_POKECENTER",
    "Silph Co 1F": "MUSIC_SILPH_CO",
    "Saffron Pokemon Center": "MUSIC_POKECENTER",
    "Saffron Mr. Psychic's House": "MUSIC_CITIES1",
    "Route 15 Gate 1F": "MUSIC_CITIES1",
    "Route 15 Gate 2F": "MUSIC_CITIES1",
    "Route 16 Gate 1F": "MUSIC_CITIES1",
    "Route 16 Gate 2F": "MUSIC_CITIES1",
    "Route 16 Fly House": "MUSIC_CELADON",
    "Route 12 Super Rod House": "MUSIC_CELADON",
    "Route 18 Gate 1F": "MUSIC_CITIES1",
    "Route 18 Gate 2F": "MUSIC_CITIES1",
    "Seafoam Islands 1F": "MUSIC_DUNGEON2",
    "Route 22 Gate": "MUSIC_DUNGEON2",
    "Victory Road 2F": "MUSIC_DUNGEON3",
    "Route 12 Gate 2F": "MUSIC_CITIES1",
    "Vermilion Trade House": "MUSIC_VERMILION",
    "Diglett's Cave": "MUSIC_DUNGEON2",
    "Victory Road 3F": "MUSIC_DUNGEON3",
    "Rocket Hideout B1F": "MUSIC_DUNGEON1",
    "Rocket Hideout B2F": "MUSIC_DUNGEON1",
    "Rocket Hideout B3F": "MUSIC_DUNGEON1",
    "Rocket Hideout B4F": "MUSIC_DUNGEON1",
    "Rocket Hideout Elevator": "MUSIC_DUNGEON1",
    "Silph Co 2F": "MUSIC_SILPH_CO",
    "Silph Co 3F": "MUSIC_SILPH_CO",
    "Silph Co 4F": "MUSIC_SILPH_CO",
    "Silph Co 5F": "MUSIC_SILPH_CO",
    "Silph Co 6F": "MUSIC_SILPH_CO",
    "Silph Co 7F": "MUSIC_SILPH_CO",
    "Silph Co 8F": "MUSIC_SILPH_CO",
    "Pokemon Mansion 2F": "MUSIC_CINNABAR_MANSION",
    "Pokemon Mansion 3F": "MUSIC_CINNABAR_MANSION",
    "Pokemon Mansion B1F": "MUSIC_CINNABAR_MANSION",
    "Safari Zone East": "MUSIC_SAFARI_ZONE",
    "Safari Zone North": "MUSIC_SAFARI_ZONE",
    "Safari Zone West": "MUSIC_SAFARI_ZONE",
    "Safari Zone Center": "MUSIC_SAFARI_ZONE",
    "Safari Zone Center Rest House": "MUSIC_SAFARI_ZONE",
    "Safari Zone Secret House": "MUSIC_SAFARI_ZONE",
    "Safari Zone West Rest House": "MUSIC_SAFARI_ZONE",
    "Safari Zone East Rest House": "MUSIC_SAFARI_ZONE",
    "Safari Zone North Rest House": "MUSIC_SAFARI_ZONE",
    "Cerulean Cave 2F": "MUSIC_DUNGEON1",
    "Cerulean Cave B1F": "MUSIC_DUNGEON1",
    "Cerulean Cave 1F": "MUSIC_DUNGEON1",
    "Lavender Name Rater's House": "MUSIC_CITIES2",
    "Cerulean Badge House": "MUSIC_CITIES1",
    "Rock Tunnel B1F": "MUSIC_DUNGEON3",
    "Silph Co 9F": "MUSIC_SILPH_CO",
    "Silph Co 10F": "MUSIC_SILPH_CO",
    "Silph Co 11F": "MUSIC_SILPH_CO",
    "Silph Co Elevator": "MUSIC_SILPH_CO",
    "Trade Center": "MUSIC_CELADON",
    "Colosseum": "MUSIC_CELADON",
    "Indigo Plateau Lorelei's Room": "MUSIC_GYM",
    "Indigo Plateau Bruno's Room": "MUSIC_DUNGEON1",
    "Indigo Plateau Agatha's Room": "MUSIC_POKEMON_TOWER"
}


def randomize_map_music(world, write_bytes):
    if world.options.randomize_map_music == "vanilla":
        return
    music_data = bytearray(0x1ee)
    if world.options.randomize_map_music == "shuffle":
        shuffled_music = list(music_pointers.keys())
        world.random.shuffle(shuffled_music)
        music_mapping = {default: shuffled for default, shuffled in zip(music_pointers.keys(), shuffled_music)}
        for music_map, default in default_music.items():
            map_id = map_ids[music_map]
            music_data[map_id * 2:(map_id * 2) + 2] \
                = music_pointers[music_mapping[default]].to_bytes(2, byteorder='big')
    elif world.options.randomize_map_music == "randomize":
        for music_map in default_music.keys():
            map_id = map_ids[music_map]
            music_data[map_id * 2:(map_id * 2) + 2] \
                = world.random.choice(list(music_pointers.values())).to_bytes(2, byteorder='big')
    elif world.options.randomize_map_music == "chaos":
        write_bytes(rom_addresses["Option_Chaos_Music"], [0, 0])
        write_bytes(rom_addresses["Chaos_Music_Quantity"], len(music_pointers))
        for i, music_pointer in enumerate(music_pointers.values()):
            music_data[i * 2:(i * 2) + 2] = music_pointer.to_bytes(2, byteorder='big')
    write_bytes(rom_addresses["Map_Songs"], music_data)
