pokemons = {
    "RHYDON": 0x01,
    "KANGASKHAN": 0x02,
    "NIDORAN_M": 0x03,
    "CLEFAIRY": 0x04,
    "SPEAROW": 0x05,
    "VOLTORB": 0x06,
    "NIDOKING": 0x07,
    "SLOWBRO": 0x08,
    "IVYSAUR": 0x09,
    "EXEGGUTOR": 0x0A,
    "LICKITUNG": 0x0B,
    "EXEGGCUTE": 0x0C,
    "GRIMER": 0x0D,
    "GENGAR": 0x0E,
    "NIDORAN_F": 0x0F,
    "NIDOQUEEN": 0x10,
    "CUBONE": 0x11,
    "RHYHORN": 0x12,
    "LAPRAS": 0x13,
    "ARCANINE": 0x14,
    "MEW": 0x15,
    "GYARADOS": 0x16,
    "SHELLDER": 0x17,
    "TENTACOOL": 0x18,
    "GASTLY": 0x19,
    "SCYTHER": 0x1A,
    "STARYU": 0x1B,
    "BLASTOISE": 0x1C,
    "PINSIR": 0x1D,
    "TANGELA": 0x1E,
    "GROWLITHE": 0x21,
    "ONIX": 0x22,
    "FEAROW": 0x23,
    "PIDGEY": 0x24,
    "SLOWPOKE": 0x25,
    "KADABRA": 0x26,
    "GRAVELER": 0x27,
    "CHANSEY": 0x28,
    "MACHOKE": 0x29,
    "MR_MIME": 0x2A,
    "HITMONLEE": 0x2B,
    "HITMONCHAN": 0x2C,
    "ARBOK": 0x2D,
    "PARASECT": 0x2E,
    "PSYDUCK": 0x2F,
    "DROWZEE": 0x30,
    "GOLEM": 0x31,
    "MAGMAR": 0x33,
    "ELECTABUZZ": 0x35,
    "MAGNETON": 0x36,
    "KOFFING": 0x37,
    "MANKEY": 0x39,
    "SEEL": 0x3A,
    "DIGLETT": 0x3B,
    "TAUROS": 0x3C,
    "FARFETCHD": 0x40,
    "VENONAT": 0x41,
    "DRAGONITE": 0x42,
    "DODUO": 0x46,
    "POLIWAG": 0x47,
    "JYNX": 0x48,
    "MOLTRES": 0x49,
    "ARTICUNO": 0x4A,
    "ZAPDOS": 0x4B,
    "DITTO": 0x4C,
    "MEOWTH": 0x4D,
    "KRABBY": 0x4E,
    "VULPIX": 0x52,
    "NINETALES": 0x53,
    "PIKACHU": 0x54,
    "RAICHU": 0x55,
    "DRATINI": 0x58,
    "DRAGONAIR": 0x59,
    "KABUTO": 0x5A,
    "KABUTOPS": 0x5B,
    "HORSEA": 0x5C,
    "SEADRA": 0x5D,
    "SANDSHREW": 0x60,
    "SANDSLASH": 0x61,
    "OMANYTE": 0x62,
    "OMASTAR": 0x63,
    "JIGGLYPUFF": 0x64,
    "WIGGLYTUFF": 0x65,
    "EEVEE": 0x66,
    "FLAREON": 0x67,
    "JOLTEON": 0x68,
    "VAPOREON": 0x69,
    "MACHOP": 0x6A,
    "ZUBAT": 0x6B,
    "EKANS": 0x6C,
    "PARAS": 0x6D,
    "POLIWHIRL": 0x6E,
    "POLIWRATH": 0x6F,
    "WEEDLE": 0x70,
    "KAKUNA": 0x71,
    "BEEDRILL": 0x72,
    "DODRIO": 0x74,
    "PRIMEAPE": 0x75,
    "DUGTRIO": 0x76,
    "VENOMOTH": 0x77,
    "DEWGONG": 0x78,
    "CATERPIE": 0x7B,
    "METAPOD": 0x7C,
    "BUTTERFREE": 0x7D,
    "MACHAMP": 0x7E,
    "GOLDUCK": 0x80,
    "HYPNO": 0x81,
    "GOLBAT": 0x82,
    "MEWTWO": 0x83,
    "SNORLAX": 0x84,
    "MAGIKARP": 0x85,
    "MUK": 0x88,
    "KINGLER": 0x8A,
    "CLOYSTER": 0x8B,
    "ELECTRODE": 0x8D,
    "CLEFABLE": 0x8E,
    "WEEZING": 0x8F,
    "PERSIAN": 0x90,
    "MAROWAK": 0x91,
    "HAUNTER": 0x93,
    "ABRA": 0x94,
    "ALAKAZAM": 0x95,
    "PIDGEOTTO": 0x96,
    "PIDGEOT": 0x97,
    "STARMIE": 0x98,
    "BULBASAUR": 0x99,
    "VENUSAUR": 0x9A,
    "TENTACRUEL": 0x9B,
    "GOLDEEN": 0x9D,
    "SEAKING": 0x9E,
    "PONYTA": 0xA3,
    "RAPIDASH": 0xA4,
    "RATTATA": 0xA5,
    "RATICATE": 0xA6,
    "NIDORINO": 0xA7,
    "NIDORINA": 0xA8,
    "GEODUDE": 0xA9,
    "PORYGON": 0xAA,
    "AERODACTYL": 0xAB,
    "MAGNEMITE": 0xAD,
    "CHARMANDER": 0xB0,
    "SQUIRTLE": 0xB1,
    "CHARMELEON": 0xB2,
    "WARTORTLE": 0xB3,
    "CHARIZARD": 0xB4,
    # "FOSSIL_KABUTOPS": 0xB6,
    # "FOSSIL_AERODACTYL": 0xB7,
    # "MON_GHOST]": 0xB8,
    "ODDISH": 0xB9,
    "GLOOM": 0xBA,
    "VILEPLUME": 0xBB,
    "BELLSPROUT": 0xBC,
    "WEEPINBELL": 0xBD,
    "VICTREEBEL": 0xBE
}

types = {
    "Normal": 0x0,
    "Fighting": 0x1,
    "Flying": 0x2,
    "Poison": 0x3,
    "Ground": 0x4,
    "Rock": 0x5,
    "Bug": 0x7,
    "Ghost": 0x8,
    "Fire": 0x14,
    "Water": 0x15,
    "Grass": 0x16,
    "Electric": 0x17,
    "Psychic": 0x18,
    "Ice": 0x19,
    "Dragon": 0x1A
}


type_chart = [
    ["Water", "Fire", 20],
    ["Fire", "Grass", 20],
    ["Fire", "Ice", 20],
    ["Grass", "Water", 20],
    ["Electric", "Water", 20],
    ["Water", "Rock", 20],
    ["Ground", "Flying", 0],
    ["Water", "Water", 5],
    ["Fire", "Fire", 5],
    ["Electric", "Electric", 5],
    ["Ice", "Ice", 5],
    ["Grass", "Grass", 5],
    ["Psychic", "Psychic", 5],
    ["Fire", "Water", 5],
    ["Grass", "Fire", 5],
    ["Water", "Grass", 5],
    ["Electric", "Grass", 5],
    ["Normal", "Rock", 5],
    ["Normal", "Ghost", 0],
    ["Ghost", "Ghost", 20],
    ["Fire", "Bug", 20],
    ["Fire", "Rock", 5],
    ["Water", "Ground", 20],
    ["Electric", "Ground", 0],
    ["Electric", "Flying", 20],
    ["Grass", "Ground", 20],
    ["Grass", "Bug", 5],
    ["Grass", "Poison", 5],
    ["Grass", "Rock", 20],
    ["Grass", "Flying", 5],
    ["Ice", "Water", 5],
    ["Ice", "Grass", 20],
    ["Ice", "Ground", 20],
    ["Ice", "Flying", 20],
    ["Fighting", "Normal", 20],
    ["Fighting", "Poison", 5],
    ["Fighting", "Flying", 5],
    ["Fighting", "Psychic", 5],
    ["Fighting", "Bug", 5],
    ["Fighting", "Rock", 20],
    ["Fighting", "Ice", 20],
    ["Fighting", "Ghost", 0],
    ["Poison", "Grass", 20],
    ["Poison", "Poison", 5],
    ["Poison", "Ground", 5],
    ["Poison", "Bug", 20],
    ["Poison", "Rock", 5],
    ["Poison", "Ghost", 5],
    ["Ground", "Fire", 20],
    ["Ground", "Electric", 20],
    ["Ground", "Grass", 5],
    ["Ground", "Bug", 5],
    ["Ground", "Rock", 20],
    ["Ground", "Poison", 20],
    ["Flying", "Electric", 5],
    ["Flying", "Fighting", 20],
    ["Flying", "Bug", 20],
    ["Flying", "Grass", 20],
    ["Flying", "Rock", 5],
    ["Psychic", "Fighting", 20],
    ["Psychic", "Poison", 20],
    ["Bug", "Fire", 5],
    ["Bug", "Grass", 20],
    ["Bug", "Fighting", 5],
    ["Bug", "Flying", 5],
    ["Bug", "Psychic", 20],
    ["Bug", "Ghost", 5],
    ["Bug", "Poison", 20],
    ["Rock", "Fire", 20],
    ["Rock", "Fighting", 5],
    ["Rock", "Ground", 5],
    ["Rock", "Flying", 20],
    ["Rock", "Bug", 20],
    ["Rock", "Ice", 20],
    ["Ghost", "Normal", 0],
    ["Ghost", "Psychic", 0],
    ["Fire", "Dragon", 5],
    ["Water", "Dragon", 5],
    ["Electric", "Dragon", 5],
    ["Grass", "Dragon", 5],
    ["Ice", "Dragon", 20],
    ["Dragon", "Dragon", 20]
]