from BaseClasses import Item
import typing

class ItemPoolLookup():
    level_event_table = [
        ["AtlH 1 Star", "1"],
        ["AtlH 2 Gate", "1"],
        ["AtlH 2 Star", "1"],
        ["AtlH 3 Gate", "1"],
        ["AtlH 3 Star", "1"],
        ["AtlH Boss Gate", "1"],
        ["AtlH Boss Star", "1"],
        ["AtlH Bonus Gate", "1"],
        ["AtlH Bonus Star", "1"],
        ["Atl1 Gate", "1"],
        ["Atl2 Elevator", "1"],
        ["Atl2 Ballswitch Drain", "1"],
        ["Atl2 Gate", "1"],
        ["Atl3 Waterwheel", "1"],
        ["Atl3 Cave Platforms", "1"],
        ["CrnH 1 Star", "1"],
        ["CrnH 2 Gate", "1"],
        ["CrnH 2 Star", "1"],
        ["CrnH 3 Gate", "1"],
        ["CrnH 3 Star", "1"],
        ["CrnH Boss Gate", "1"],
        ["CrnH Boss Star", "1"],
        ["CrnH Bonus Gate", "1"],
        ["CrnH Bonus Star", "1"],
        ["Crn1 Elevator", "1"],
        ["Crn1 Gate", "1"],
        ["Crn1 Door A", "1"],
        ["Crn1 Door B", "1"],
        ["Crn1 Door C", "1"],
        ["Crn1 Rocket 1", "1"],
        ["Crn1 Rocket 2", "1"],
        ["Crn1 Rocket 3", "1"],
        ["Crn2 Drop Garibs", "1"],
        ["Crn2 Fan", "1"],
        ["Crn3 Spin Door", "1"],
        ["Crn3 Hands", "1"],
        ["PrtH 1 Star", "1"],
        ["PrtH 2 Gate", "1"],
        ["PrtH 2 Star", "1"],
        ["PrtH 3 Gate", "1"],
        ["PrtH 3 Star", "1"],
        ["PrtH Boss Gate", "1"],
        ["PrtH Boss Star", "1"],
        ["PrtH Bonus Gate", "1"],
        ["PrtH Bonus Star", "1"],
        ["Prt1 Raise Beach", "1"],
        ["Prt1 Elevator", "1"],
        ["Prt1 Chest", "1"],
        ["Prt1 Sandpile", "1"],
        ["Prt1 Waterspout", "1"],
        ["Prt1 Lighthouse", "1"],
        ["Prt1 Raise Ship", "1"],
        ["Prt1 Bridge", "1"],
        ["Prt2 Lower Water", "1"],
        ["Prt2 Ramp", "1"],
        ["Prt2 Gate", "1"],
        ["Prt3 Platform Spin", "1"],
        ["Prt3 Trampoline", "1"],
        ["Prt3 Stairs", "1"],
        ["Prt3 Elevator", "1"],
        ["PhtH 1 Star", "1"],
        ["PhtH 2 Gate", "1"],
        ["PhtH 2 Star", "1"],
        ["PhtH 3 Gate", "1"],
        ["PhtH 3 Star", "1"],
        ["PhtH Boss Gate", "1"],
        ["PhtH Boss Star", "1"],
        ["PhtH Bonus Gate", "1"],
        ["PhtH Bonus Star", "1"],
        ["Pht1 Life Drop", "1"],
        ["Pht2 Platform 1", "1"],
        ["Pht2 Platform 2", "1"],
        ["Pht2 Lower Ball Switch", "1"],
        ["Pht3 Drop Garibs", "1"],
        ["Pht3 Spin Stones", "1"],
        ["Pht3 Progressive Lower Monolith 1", "1"],
        ["Pht3 Progressive Lower Monolith 2", "1"],
        ["Pht3 Progressive Lower Monolith 3", "1"],
        ["Pht3 Progressive Lower Monolith 4", "1"],
        ["Pht3 Floating Platforms", "1"],
        ["Pht3 Lava Spinning", "1"],
        ["Pht3 Dirt Elevator", "1"],
        ["FoFH 1 Star", "1"],
        ["FoFH 2 Gate", "1"],
        ["FoFH 2 Star", "1"],
        ["FoFH 3 Gate", "1"],
        ["FoFH 3 Star", "1"],
        ["FoFH Boss Gate", "1"],
        ["FoFH Boss Star", "1"],
        ["FoFH Bonus Gate", "1"],
        ["FoFH Bonus Star", "1"],
        ["FoF1 Coffin", "1"],
        ["FoF1 Doorway", "1"],
        ["FoF1 Drawbridge", "1"],
        ["FoF2 Garibs Fall", "1"],
        ["FoF2 Checkpoint Gates", "1"],
        ["FoF2 Mummy Gate", "1"],
        ["FoF3 Gate", "1"],
        ["FoF3 Spikes", "1"],
        ["OtwH 1 Star", "1"],
        ["OtwH 2 Gate", "1"],
        ["OtwH 2 Star", "1"],
        ["OtwH 3 Gate", "1"],
        ["OtwH 3 Star", "1"],
        ["OtwH Boss Gate", "1"],
        ["OtwH Boss Star", "1"],
        ["OtwH Bonus Gate", "1"],
        ["OtwH Bonus Star", "1"],
        ["Otw1 Aliens", "1"],
        ["Otw1 Fans", "1"],
        ["Otw1 Flying Platforms", "1"],
        ["Otw1 Goo Platforms", "1"],
        ["Otw1 UFO", "1"],
        ["Otw1 Missile", "1"],
        ["Otw2 Mashers", "1"],
        ["Otw2 Ramp", "1"],
        ["Otw3 Hazard Gate", "1"],
        ["Otw3 Sign", "1"],
        ["Otw3 Fan", "1"],
        ["Otw3 Bridge", "1"],
        ["Otw3 Glass Gate", "1"],
        ["Hubworld Atlantis Gate", "1"],
        ["Hubworld Carnival Gate", "1"],
        ["Hubworld Pirate's Cove Gate", "1"],
        ["Hubworld Prehistoric Gate", "1"],
        ["Hubworld Fortress of Fear Gate", "1"],
        ["Hubworld Out of This World Gate", "1"],
        ["Training Sandpit", "1"],
        ["Training Lower Target", "1"],
        ["Training Stairs", "1"]
    ]

    checkpoint_table = [
        ["Atl1 Checkpoint 2", "1"],
        ["Atl1 Checkpoint 1", "1"],
        ["Atl2 Checkpoint 2", "1"],
        ["Atl2 Checkpoint 3", "1"],
        ["Atl2 Checkpoint 1", "1"],
        ["Atl3 Checkpoint 2", "1"],
        ["Atl3 Checkpoint 3", "1"],
        ["Atl3 Checkpoint 1", "1"],
        ["Crn1 Checkpoint 2", "1"],
        ["Crn1 Checkpoint 3", "1"],
        ["Crn1 Checkpoint 4", "1"],
        ["Crn1 Checkpoint 1", "1"],
        ["Crn2 Checkpoint 2", "1"],
        ["Crn2 Checkpoint 3", "1"],
        ["Crn2 Checkpoint 4", "1"],
        ["Crn2 Checkpoint 5", "1"],
        ["Crn2 Checkpoint 1", "1"],
        ["Crn3 Checkpoint 2", "1"],
        ["Crn3 Checkpoint 3", "1"],
        ["Crn3 Checkpoint 4", "1"],
        ["Crn3 Checkpoint 1", "1"],
        ["Prt1 Checkpoint 2", "1"],
        ["Prt1 Checkpoint 3", "1"],
        ["Prt1 Checkpoint 1", "1"],
        ["Prt2 Checkpoint 2", "1"],
        ["Prt2 Checkpoint 3", "1"],
        ["Prt2 Checkpoint 1", "1"],
        ["Prt3 Checkpoint 2", "1"],
        ["Prt3 Checkpoint 3", "1"],
        ["Prt3 Checkpoint 4", "1"],
        ["Prt3 Checkpoint 1", "1"],
        ["Pht1 Checkpoint 2", "1"],
        ["Pht1 Checkpoint 3", "1"],
        ["Pht1 Checkpoint 1", "1"],
        ["Pht2 Checkpoint 2", "1"],
        ["Pht2 Checkpoint 3", "1"],
        ["Pht2 Checkpoint 4", "1"],
        ["Pht2 Checkpoint 1", "1"],
        ["Pht3 Checkpoint 2", "1"],
        ["Pht3 Checkpoint 3", "1"],
        ["Pht3 Checkpoint 4", "1"],
        ["Pht3 Checkpoint 1", "1"],
        ["FoF1 Checkpoint 2", "1"],
        ["FoF1 Checkpoint 3", "1"],
        ["FoF1 Checkpoint 1", "1"],
        ["FoF2 Checkpoint 2", "1"],
        ["FoF2 Checkpoint 3", "1"],
        ["FoF2 Checkpoint 1", "1"],
        ["FoF3 Checkpoint 2", "1"],
        ["FoF3 Checkpoint 3", "1"],
        ["FoF3 Checkpoint 4", "1"],
        ["FoF3 Checkpoint 5", "1"],
        ["FoF3 Checkpoint 1", "1"],
        ["Otw1 Checkpoint 2", "1"],
        ["Otw1 Checkpoint 1", "1"],
        ["Otw2 Checkpoint 1", "1"],
        ["Otw3 Checkpoint 2", "1"],
        ["Otw3 Checkpoint 3", "1"],
        ["Otw3 Checkpoint 4", "1"],
        ["Otw3 Checkpoint 1", "1"]
    ]

    garib_table = [
        ["Atl1 1 Garibs", "1"],
        ["Atl1 2 Garibs", "3"],
        ["Atl1 3 Garibs", "1"],
        ["Atl1 4 Garibs", "5"],
        ["Atl1 5 Garibs", "1"],
        ["Atl1 6 Garibs", "1"],
        ["Atl1 9 Garibs", "1"],
        ["Atl2 1 Garibs", "1"],
        ["Atl2 2 Garibs", "2"],
        ["Atl2 3 Garibs", "3"],
        ["Atl2 4 Garibs", "1"],
        ["Atl2 5 Garibs", "5"],
        ["Atl2 7 Garibs", "1"],
        ["Atl2 10 Garibs", "1"],
        ["Atl3 1 Garibs", "2"],
        ["Atl3 2 Garibs", "1"],
        ["Atl3 3 Garibs", "2"],
        ["Atl3 4 Garibs", "4"],
        ["Atl3 5 Garibs", "3"],
        ["Atl3 6 Garibs", "1"],
        ["Atl3 8 Garibs", "3"],
        ["Atl3 9 Garibs", "1"],
        ["Atl? 5 Garibs", "5"],
        ["Crn1 1 Garibs", "1"],
        ["Crn1 4 Garibs", "3"],
        ["Crn1 7 Garibs", "1"],
        ["Crn1 8 Garibs", "3"],
        ["Crn1 10 Garibs", "1"],
        ["Crn1 11 Garibs", "1"],
        ["Crn2 1 Garibs", "3"],
        ["Crn2 2 Garibs", "1"],
        ["Crn2 3 Garibs", "1"],
        ["Crn2 4 Garibs", "4"],
        ["Crn2 6 Garibs", "3"],
        ["Crn2 8 Garibs", "2"],
        ["Crn2 10 Garibs", "1"],
        ["Crn2 12 Garibs", "1"],
        ["Crn3 1 Garibs", "1"],
        ["Crn3 2 Garibs", "1"],
        ["Crn3 3 Garibs", "6"],
        ["Crn3 4 Garibs", "6"],
        ["Crn3 6 Garibs", "1"],
        ["Crn3 8 Garibs", "1"],
        ["Crn3 9 Garibs", "1"],
        ["Crn3 12 Garibs", "1"],
        ["Crn? 8 Garibs", "1"],
        ["Crn? 12 Garibs", "1"],
        ["Prt1 1 Garibs", "4"],
        ["Prt1 4 Garibs", "7"],
        ["Prt1 5 Garibs", "1"],
        ["Prt1 6 Garibs", "3"],
        ["Prt1 7 Garibs", "1"],
        ["Prt1 8 Garibs", "1"],
        ["Prt2 1 Garibs", "6"],
        ["Prt2 2 Garibs", "1"],
        ["Prt2 3 Garibs", "1"],
        ["Prt2 4 Garibs", "5"],
        ["Prt2 8 Garibs", "1"],
        ["Prt2 9 Garibs", "1"],
        ["Prt2 12 Garibs", "1"],
        ["Prt3 1 Garibs", "3"],
        ["Prt3 2 Garibs", "5"],
        ["Prt3 3 Garibs", "3"],
        ["Prt3 4 Garibs", "7"],
        ["Prt3 6 Garibs", "1"],
        ["Prt3 8 Garibs", "1"],
        ["Prt3 16 Garibs", "1"],
        ["Prt? 3 Garibs", "15"],
        ["Prt? 5 Garibs", "1"],
        ["Pht1 1 Garibs", "1"],
        ["Pht1 2 Garibs", "5"],
        ["Pht1 3 Garibs", "6"],
        ["Pht1 4 Garibs", "1"],
        ["Pht1 5 Garibs", "1"],
        ["Pht1 6 Garibs", "1"],
        ["Pht1 8 Garibs", "3"],
        ["Pht1 12 Garibs", "1"],
        ["Pht2 1 Garibs", "6"],
        ["Pht2 2 Garibs", "1"],
        ["Pht2 3 Garibs", "3"],
        ["Pht2 4 Garibs", "6"],
        ["Pht2 5 Garibs", "4"],
        ["Pht2 8 Garibs", "1"],
        ["Pht2 11 Garibs", "1"],
        ["Pht3 1 Garibs", "1"],
        ["Pht3 2 Garibs", "2"],
        ["Pht3 3 Garibs", "2"],
        ["Pht3 5 Garibs", "1"],
        ["Pht3 7 Garibs", "1"],
        ["Pht3 8 Garibs", "2"],
        ["Pht3 10 Garibs", "1"],
        ["Pht3 15 Garibs", "1"],
        ["Pht3 16 Garibs", "1"],
        ["Pht? 10 Garibs", "6"],
        ["FoF1 1 Garibs", "4"],
        ["FoF1 2 Garibs", "1"],
        ["FoF1 3 Garibs", "4"],
        ["FoF1 4 Garibs", "3"],
        ["FoF1 5 Garibs", "2"],
        ["FoF1 6 Garibs", "2"],
        ["FoF1 8 Garibs", "1"],
        ["FoF2 1 Garibs", "1"],
        ["FoF2 2 Garibs", "1"],
        ["FoF2 3 Garibs", "3"],
        ["FoF2 5 Garibs", "5"],
        ["FoF2 6 Garibs", "1"],
        ["FoF2 7 Garibs", "1"],
        ["FoF2 10 Garibs", "1"],
        ["FoF3 1 Garibs", "1"],
        ["FoF3 2 Garibs", "4"],
        ["FoF3 3 Garibs", "4"],
        ["FoF3 4 Garibs", "3"],
        ["FoF3 5 Garibs", "1"],
        ["FoF3 6 Garibs", "1"],
        ["FoF3 8 Garibs", "2"],
        ["FoF3 10 Garibs", "1"],
        ["FoF? 14 Garibs", "4"],
        ["Otw1 1 Garibs", "6"],
        ["Otw1 2 Garibs", "1"],
        ["Otw1 3 Garibs", "4"],
        ["Otw1 4 Garibs", "1"],
        ["Otw1 10 Garibs", "1"],
        ["Otw1 16 Garibs", "1"],
        ["Otw2 2 Garibs", "2"],
        ["Otw2 3 Garibs", "2"],
        ["Otw2 4 Garibs", "3"],
        ["Otw2 5 Garibs", "2"],
        ["Otw2 6 Garibs", "1"],
        ["Otw2 12 Garibs", "1"],
        ["Otw3 3 Garibs", "1"],
        ["Otw3 4 Garibs", "3"],
        ["Otw3 5 Garibs", "2"],
        ["Otw3 6 Garibs", "2"],
        ["Otw3 7 Garibs", "2"],
        ["Otw3 8 Garibs", "1"],
        ["Otw3 9 Garibs", "1"],
        ["Otw3 12 Garibs", "1"],
        ["Otw? 6 Garibs", "3"],
        ["Otw? 8 Garibs", "4"]
        ]

    ability_table = [
        ["Jump", "1"],
        ["Cartwheel", "1"],
        ["Crawl", "1"],
        ["Double Jump", "1"],
        ["Fist Slam", "1"],
        ["Ledge Grab", "1"],
        ["Push", "1"],
        ["Locate Garibs", "1"],
        ["Locate Ball", "1"],
        ["Dribble", "1"],
        ["L Piston", "1"],
        ["Slap", "1"],
        ["Throw", "1"],
        ["Ball Toss", "1"],
        ["Beachball", "1"],
        ["Death Potion", "1"],
        ["Helicopter Potion", "1"],
        ["Frog Potion", "1"],
        ["Boomerang Ball", "1"],
        ["Speed Potion", "1"],
        ["Sticky Potion", "1"],
        ["Hercules Potion", "1"],
        ["Grab", "1"],
        ["Rubber Ball", "1"],
        ["Bowling Ball", "1"],
        ["Ball Bearing", "1"],
        ["Crystal", "1"],
        ["Power Ball", "1"]
    ]