def is_placement_command_code(code):
    return (code < 0xC0)

BATCH_COMMAND_CODE = 0xEB

COMMANDS = {
    0xC0 : ['player move up'],
    0xC1 : ['player move right'],
    0xC2 : ['player move down'],
    0xC3 : ['player move left'],
    0xC4 : ['player face up'],
    0xC5 : ['player face right'],
    0xC6 : ['player face down'],
    0xC7 : ['player face left'],
    0xC8 : ['player invisible'],
    0xC9 : ['player visible'],
    0xCA : ['player wave in'],
    0xCB : ['player wave out'],
    0xCC : ['player bow head'],
    0xCD : ['player lie down'],
    0xCE : ['player toggle turning'],
    0xCF : ['player toggle spinning'],
    0xD0 : ['toggle screen shake'],
    0xD1 : ['screen flash'],
    0xD2 : ['screen blur'],
    0xD3 : ['moon travel'],
    0xD4 : ['fat chocobo'],
    0xD5 : ['open door'],
    0xD6 : ['screen up down'],
    0xD7 : ['toggle run'],
    0xD8 : ['toggle music fade'],
    0xD9 : ['namingway'],
    0xDA : ['toggle screen fade'],
    0xDB : ['toggle status {}', 'status'],
    0xDC : ['inn {}', 'hex'],
    0xDD : ['party leader {}', 'actor'],
    0xDE : ['give hp {}', 'hpmp'],
    0xDF : ['give mp {}', 'hpmp'],
    0xE0 : ['give item {}', 'item'],
    0xE1 : ['take item {}', 'item'],
    0xE2 : ['give spell {} {}', 'spellset', 'spell'],
    0xE3 : ['clear status {}', 'status'],
    0xE4 : ['give status {}', 'status'],
    0xE5 : ['give gp {}', 'gp'],
    0xE6 : ['take gp {}', 'gp'],
    0xE7 : ['give actor {}', 'actor'],
    0xE8 : ['take actor {}', 'actor'],
    0xE9 : ['pause {}', 'decimal'],
    0xEA : ['music {} fade in', 'music'],
    0xEC : ['fight {}', 'formation'],
    0xED : ['shop {}', 'shop'],
    0xEE : ['event message {}', 'decimal'],
    0xEF : ['map message {}', 'decimal'],
    0xF0 : ['message {}', 'message'],
    0xF1 : ['message {}', 'message_high'],
    0xF2 : ['set {}', 'flag'],
    0xF3 : ['clear {}', 'flag'],
    0xF4 : ['activate {}', 'npc'],
    0xF5 : ['deactivate {}', 'npc'],
    0xF6 : ['message {} from bank 3', 'message'],
    0xF7 : ['select item {}', 'item'],
    0xF8 : ['confirm message {}', 'message_high'],
    0xF9 : ['toggle tint {}', 'hex'],
    0xFA : ['music {}', 'music'],
    0xFB : ['sound {}', 'sound'],
    #0xFC : ['crash', 'hex'],
    0xFD : ['vfx {}', 'vfx'],
    0xFE : ['load map {} at {} {} {}', 'map', 'decimal', 'decimal', 'mapflags']
}

PLACEMENT_COMMANDS = {
    0x0 : 'move up',
    0x1 : 'move right',
    0x2 : 'move down',
    0x3 : 'move left',
    0x4 : 'face up',
    0x5 : 'face right',
    0x6 : 'face down',
    0x7 : 'face left',
    0x8 : 'toggle visible',
    0x9 : 'jump sideways',
    0xA : 'spin',
    0xB : 'spin jump',
    0xC : 'wave in',
    0xD : 'wave out',
    0xE : 'bow head',
    0xF : 'lie down'
}

VEHICLES = {
    1 : 'on chocobo',
    2 : 'on black chocobo',
    3 : 'on hovercraft',
    4 : 'on enterprise',
    5 : 'on falcon',
    6 : 'on big whale',
    7 : 'on ship',
    0x1F : 'on ship 2'
}

DEFAULT_EVENT_DESCRIPTIONS = [
    "(no event)",
    "Show first message",
    "Show second message",
    "Show third message",
    "Behemoth battle 51",
    "Behemoth battle 52",
    "Entering Tower of Bab-il",
    "Hummingways",
    "Rydia learning Sylph",
    "Receiving the pan",
    "Do you have the clerics' permission?",
    "Open a door",
    "Locked",
    "Namingway",
    "Rubicant main battle",
    "OUCH!",
    "Opening events",
    "Cid greeting Cecil",
    "Speaking to Kain in Baron",
    "Cecil's maid",
    "Rosa greeting Cecil",
    "Cecil sleeping, Prologue",
    "Item selection - soft",
    "Sealed with unknown power",
    "Finding Odin before Feymarch",
    "Odin battle",
    "Baigan battle",
    "Kainazzo battle, losing twins",
    "Devil's Road is sealed",
    "Attaching hook to Enterprise",
    "Devil's Road to Mysidia",
    "Unlock the Waterway door",
    "Unlock the Weapon/Armor shop",
    "Cecil/Yang fight",
    "Staying at a 50 GP Inn",
    "Bring up Silvera weapon shop",
    "Bring up Baron weapon shop",
    "Bring up Baron armor shop",
    "Bring up Baron item shop",
    "Map message 0",
    "Map message 1",
    "Map message 2",
    "Map message 3",
    "Map message 4",
    "Map message 5",
    "Map message 6",
    "Map message 7",
    "Mist Dragon battle",
    "Mist events",
    "Watery Cave camping",
    "Staying at a 800 GP Inn",
    "Bring up Mist weapon shop",
    "Bring up Mist armor shop",
    "Bring up Kaipo weapon shop",
    "Bring up Kaipo armor shop",
    "Bring up Silvera armor shop",
    "Bring up Silvera item shop",
    "Kaipo Events, Rydia Joining",
    "Curing Rosa",
    "Watery Cave Tellah Joining",
    "Watery Cave Waterfall events",
    "Octomamm battle",
    "The current is too strong for us to get in!",
    "...",
    "Giott: Open the door!",
    "'Terrible bombardments from the airships'",
    "Red Wings bombing Damcyan",
    "Tellah fighting Edward, Edward joining",
    "Fallen soldier in Damcyan's basement",
    "Antlion battle",
    "Rydia melting Mt. Hobs ice, learning Fire",
    "Yang joining, Mombomb battle",
    "Fabul battle",
    "Staying at a 100 GP Inn",
    "Toroia Clerics after Earth Crystal",
    "WA!",
    "We also might have been hypnotized",
    "Open Fat Chocobo screen",
    "Giving a Carrot to a Fat Chocobo",
    "Mist mountains on a chocobo",
    "Touching a White Chocobo",
    "Rosa getting captured",
    "Discussion about rescuing Rosa",
    "Bring up Agart weapon shop",
    "Bring up Agart armor shop",
    "Being poisoned by the bartender in Mysidia",
    "Staying at a 200 GP Inn",
    "Speaking to the White Mage in Mysidia",
    "Winning the Crystal Sword",
    "Winning the Masamune",
    "Bring up Mysidia weapon shop",
    "Bring up Mysidia armor shop",
    "Bring up Mysidia item shop",
    "Being turned into a toad by a Black Mage",
    "Talking with Mysidian Elder, twins joining",
    "Mt. Ordeals fire put out by Palom",
    "Meeting Tellah on Mt. Ordeals",
    "First Milon battle",
    "Cecil's transformation, Tellah remembering",
    "Second Milon battle",
    "Paladin Cecil talking to Mysidian Elder",
    "Devil's Road to Baron",
    "Entering the Tower of Zot first time",
    "Resting for free in Fabul",
    "Resting for free in Castle Baron",
    "Load map 8A at position 07, 06, 00",
    "Load map 8A at position 87, 03, 00",
    "Load map 8A at position 17, 06, 00",
    "Load map 8A at position 97, 03, 00",
    "Bring up Toroia armor shop",
    "Bring up Toroia weapon shop",
    "Bring up Eblan items shop",
    "Staying at a 400 GP Inn",
    "Meeting Edward in Toroia, receiving TwinHarp",
    "Edward in Toroia after defeating the Dark Elf",
    "Dark Elf 'Me Attack You' battle",
    "Obtaining the Earth Crystal",
    "Found Black Chocobo!",
    "Save point message",
    "Using a Tent",
    "Using a Cabin",
    "Magus Sisters battle",
    "Top of Tower of Zot events",
    "Bring up shop 01",
    "Valvalis battle",
    "HP restoring pot",
    "MP restoring pot",
    "Magnus Cave entering message",
    "Dark Elf 'You Fool' battle",
    "Dark Elf 'Fire2' battle",
    "Kain regaining his senses",
    "Depart Fabul, Leviathan Attack",
    "Using Magma Key, opening Underworld",
    "HP/MP/Status restoring pot",
    "Exit spell",
    "Warp spell",
    "Characters 2, 5: Toggle Visibility, Message EF00",
    "Characters 2, 5: Toggle Visibility, Message EF01",
    "Characters 2, 5: Toggle Visibility, Message EF04",
    "Entering the Underworld in the airship events",
    "Meeting Giott, Calbrena battle, rejoining Rydia",
    "Entering the Tower of Zot subsequent times",
    "Exiting the Tower of Zot",
    "Being turned Mini in Baron's Classroom",
    "Staying at a 1600 GP Inn",
    "Dwarf in castle basement opens the door",
    "Authorized dwarves only!",
    "Load Old Waterway map B1F",
    "Dr. Lugae battles",
    "Super Cannon destruction, Yang leaves",
    "Jump from Tower of Bab-il, airship escape",
    "Staying at a 3,200 GP Inn",
    "Bring up Eblan weapon shop",
    "Bring up Eblan armor shop",
    "Edge joining, Rubicant battle",
    "Ninja into Bab-il",
    "Found Black Chocobo!",
    "Returning from the moon to Giant of Bab-il",
    "Big Whale surfacing",
    "'Do you have the Clerics' permission?' when you do",
    "Ninja out of Bab-il",
    "Fighting Edge's parents",
    "Falling to the Underground",
    "Winning the Murasame",
    "Winning the Holy Lance",
    "Finding the Falcon",
    "Obtaining the Luca Key",
    "Cid meeting Edge, adding the heat shield to the Falcon",
    "Opening the Sealed Cave door",
    "Feymarch entrance",
    "Demon Wall battle",
    "Staying at a 6,400 GP Inn",
    "Bring up Tomra weapon shop",
    "Bring up Tomra armor shop",
    "Bring up Kaipo weapon shop",
    "Obtaining the Dark Crystal",
    "Climbing ropes down",
    "Climbing ropes up",
    "Bring up Hummingway shop",
    "Climbing ropes down, jumping sideways/nothing",
    "Climbing ropes up, jumping sideways/nothing",
    "Climbing ropes down, spinning, moving up",
    "Kain stealing the Dark Crystal and leaving",
    "TrapDoor battle 3D",
    "TrapDoor battle 3E",
    "TrapDoor battle 3F",
    "TrapDoor battle 40",
    "TrapDoor battle 41",
    "TrapDoor battle 42",
    "TrapDoor battle 43",
    "TrapDoor battle 44",
    "TrapDoor battle 45",
    "TrapDoor battle 46",
    "TrapDoor battle 47",
    "TrapDoor battle 48",
    "TrapDoor battle 49",
    "TrapDoor battle 4A",
    "Talking to Giott, attaching the airship drill",
    "Drilling to the surface",
    "Bring up Dwarf weapons shop",
    "Bring up Dwarf armor shop",
    "Asura battle",
    "Leviathan battle",
    "Bring up Feymarch weapon shop",
    "Bring up Feymarch armor shop",
    "Staying at a 12,800 GP Inn",
    "Bring up Tomra item shop",
    "Bahamut battle",
    "Meeting FuSoYa and having him join",
    "Baron Dancer's dance",
    "Kaipo Dancer's dance",
    "Fabul Dancer's dance",
    "Agart Dancer's dance",
    "Mysidia Dancer's dance",
    "Baron Dancer's dance after killing Kainazzo",
    "Silvera 3 Dancers' dance",
    "Toroia Dance Troupe's dance",
    "Dwarf Castle Dancer's dance",
    "Characters 2, 5: Toggle Visibility, Message EF07",
    "Reading the magazine?",
    "'Sealed with unknown power'",
    "Entering the Lunar Subterrane",
    "Obtaining the magazine",
    "Obtaining a Grimoire 6C",
    "Obtaining a Grimoire 6D",
    "Obtaining Excalibur",
    "Trading the Rat Tail for Adamant",
    "Trading the Pink Tail for Adamant Armor",
    "Load Big Whale interior",
    "Rydia learning Sylph using the Pan",
    "Giant of Bab-il CPU battle",
    "Zeromus Battle, Ending Events",
    "Load Big Whale interior, activate Baron Black Chocobo",
    "Boarding Big Whale",
    "Travel to/from Moon",
    "Resting for free",
    "TrapDoor battle 68",
    "Element Fiends battle",
    "Giving Adamant and Legend Sword to smithy",
    "Bring up Toroia pass shop",
    "Do you have a pass?",
    "Bring up Smith's shop",
    "Watery Pass - North exiting message",
    "Behemoth battle 50",
    "Load Room of Wishes, play 'Long Way to Go'",
    "Load Room of Wishes, Yang/Cid/Edward, play 'Long Way to Go'",
    "Load Mysidia Crystal Room, play 'The Prelude'",
    "Speaking to Sylph before Yang awakes",
    "Obtaining a Grimoire 91",
    "Trading the Pan for the Spoon",
    "Using the Tower Key",
    "Visual effect 33",
    "Obtaining the Ribbon",
    "Viewing the moon through the telescope",
    "Two explosions at right side of screen",
    "???"
]

