"""
Constants for region names.
"""

class RegionName:
    """Constants for region names."""
    menu = "Menu"
    warp_menu = "Warp Menu"
    lusitania = "Lusitania"
    hermit_garden = "Hermit's Garden"
    jade_corridor_start = "Jade Corridor Start"
    jade_corridor_expansion_area_1 = "Jade Corridor First Expansion Area"
    jade_corridor_expansion_area_2 = "Jade Corridor Second Expansion Area"
    jade_corridor_arseille = "Jade Corridor Airship Arseille"

    day_grancel_south = "Day Grancel South"
    day_grancel_north = "Day Grancel North"
    day_grancel_west = "Day Grancel West"
    day_grancel_east = "Day Grancel East"
    day_grancel_port = "Day Grancel Port"
    night_grancel_south = "Night Grancel South"
    night_grancel_north = "Night Grancel North"
    night_grancel_west = "Night Grancel West"
    night_grancel_east = "Night Grancel East"
    night_grancel_port = "Night Grancel Port"
    grancel_castle = "Grancel Castle"
