from typing import NamedTuple, Optional, Dict

class SongMeta(NamedTuple):
    """Contains difficulty information, Use None for unsupported intsruments"""

    songname: str
    artistname: str
    group: str
    source: str
    guitar5F: Optional[int]
    bass5F: Optional[int]
    drums: Optional[int]
    drumsElite: Optional[int]
    keys5F: Optional[int]
    keysPro: Optional[int]
    vocals: Optional[int]
    harmony2: Optional[int]
    harmony3: Optional[int]
    rhythm5F: Optional[int]

Songs: Dict[int, SongMeta] = {
    1: SongMeta("106", "Frostbitt", "YARG Official Setlist", "yarg", 5, 4, 4, 4, None, None, 2, 2, 2, None),
    2: SongMeta("1nput This 2 Y0ur Spine", "Camellia", "YARG Official Setlist", "yarg", 6, 4, 6, 6, 6, 6, 0, None, None, None),
    3: SongMeta("322", "Creo", "YARG Official Setlist", "yarg", 4, 4, 5, None, 3, 3, 0, None, None, None),
    4: SongMeta("A Visitant (feat. Victor Borba)", "RO1", "YARG Official Setlist", "yarg", 3, 1, 5, None, 6, 6, 4, 4, None, None),
    5: SongMeta("About the Author", "The Sterns", "YARG Official Setlist", "yarg", 3, 2, 2, None, 1, 1, 5, 5, 5, None),
    6: SongMeta("The Afterparty", "Portraits of Tracy", "YARG Official Setlist", "yarg", 3, 1, 2, None, 2, 3, 3, 3, 3, None),
    7: SongMeta("Al Gore Rhythm", "Blight Town", "YARG Official Setlist", "yarg", 5, 4, 5, None, None, None, 5, 5, 5, None),
    8: SongMeta("Alibi", "Vera Kay", "YARG Official Setlist", "yarg", 3, 3, 6, None, 0, 0, 4, 4, 4, None),
    9: SongMeta("All of a Sudden", "Adamic", "YARG Official Setlist", "yarg", 3, 3, 4, None, 2, 3, 1, 1, None, None),
    10: SongMeta("Allure", "Shibito", "YARG Official Setlist", "yarg", 5, 5, 6, None, 0, 0, 2, 2, 2, None),
    11: SongMeta("Avatar the Last Cakebender", "Palette Knife", "YARG Official Setlist", "yarg", 4, 3, 5, None, 4, 4, 4, 4, 4, None),
    12: SongMeta("Avatara", "Heteromorphic Zoo", "YARG Official Setlist", "yarg", 2, 2, 4, 4, 2, 2, 0, 0, None, None),
    13: SongMeta("Bathe in Blood", "Parasiticide", "YARG Official Setlist", "yarg", 6, 2, 6, None, None, None, 0, None, None, None),
    14: SongMeta("Bedroom Community", "Glass Beach", "YARG Official Setlist", "yarg", 3, 3, 3, 3, 5, 5, 3, 3, 3, None),
    15: SongMeta("Better Off Worse (feat. Flower)", "CircusP", "YARG Official Setlist", "yarg", 1, 2, 2, None, 3, 3, 6, 6, 6, None),
    16: SongMeta("Beverly", "Used to Be Valentines", "YARG Official Setlist", "yarg", 2, 2, 2, None, None, None, 2, 2, 2, None),
    17: SongMeta("Blue (feat. Miori Celesta)", "InVerSe", "YARG Official Setlist", "yarg", 3, 5, 4, None, 5, 5, 5, 5, 5, None),
    18: SongMeta("Boom Slayer (feat. Scott Foster Harris)", "Boom Kitty", "YARG Official Setlist", "yarg", 3, 3, 4, None, 2, 2, 3, 3, None, None),
    19: SongMeta("Bottleneck", "Groundlift", "YARG Official Setlist", "yarg", 5, 5, 5, None, None, None, 3, 3, None, None),
    20: SongMeta("Buds", "Troubled Minds", "YARG Official Setlist", "yarg", 2, 1, 2, None, None, None, 2, 2, 2, None),
    21: SongMeta("Butterflies", "Kingseeker", "YARG Official Setlist", "yarg", 3, 3, 4, 4, None, None, 1, 1, 1, None),
    22: SongMeta("Chocolate Rain (Sweet Like Chocolate Remix)", "Tay Zonday", "YARG Official Setlist", "yarg", 2, 2, 2, None, 4, 4, 4, 4, 4, None),
    23: SongMeta("Choked Up", "See You at Rogers", "YARG Official Setlist", "yarg", 3, 1, 2, 2, 3, 4, 4, 4, 4, None),
    24: SongMeta("Circles", "Thousand Thoughts", "YARG Official Setlist", "yarg", 3, 3, 3, None, 0, 0, 3, 3, 3, None),
    25: SongMeta("Cowboy Tanaka", "Atomic Guava", "YARG Official Setlist", "yarg", 4, 3, 5, None, 5, 5, 4, 4, 4, None),
    26: SongMeta("Cruisin'", "raphaelgoulart", "YARG Official Setlist", "yarg", 5, 3, 4, None, 3, 3, None, None, None, None),
    27: SongMeta("Discipline", "Nine Inch Nails", "YARG Official Setlist", "yarg", 3, 2, 2, 2, 2, 2, 3, 3, 3, None),
    28: SongMeta("Do", "Garlagan", "YARG Official Setlist", "yarg", 3, 4, 5, None, 4, 4, 6, 6, None, None),
    29: SongMeta("Don't Look!", "Prismia", "YARG Official Setlist", "yarg", 2, 3, 4, None, 6, 6, 1, 1, 1, None),
    30: SongMeta("Don't Spook the Owl", "Kidd Judo", "YARG Official Setlist", "yarg", 3, 3, 4, None, None, None, 4, 4, 4, None),
    31: SongMeta("Dreamweaver", "Glass Guillotine", "YARG Official Setlist", "yarg", 3, 3, 4, 4, None, None, 0, 0, 0, None),
    32: SongMeta("Duvet Thief", "The Covasettes", "YARG Official Setlist", "yarg", 2, 2, 4, None, 1, 2, 3, 3, 3, None),
    33: SongMeta("Eleven", "Last Dinosaurs", "YARG Official Setlist", "yarg", 2, 2, 3, None, 0, 0, 2, 2, 2, None),
    34: SongMeta("Emperor Rising", "Krilloan", "YARG Official Setlist", "yarg", 5, 5, 6, None, None, None, 4, 4, 4, None),
    35: SongMeta("Empires", "Electric Swing Circus", "YARG Official Setlist", "yarg", 2, 1, 4, None, 4, 4, 4, 4, 4, None),
    36: SongMeta("Everybody Do the Flop", "LilDeuceDeuce", "YARG Official Setlist", "yarg", 4, 3, 5, None, 4, 4, 5, 5, 5, None),
    37: SongMeta("Exeter", "Another One Down!", "YARG Official Setlist", "yarg", 3, 4, 4, None, 0, 0, 2, 2, 2, None),
    38: SongMeta("Fine", "Lemon Demon", "YARG Official Setlist", "yarg", 4, 2, 4, 4, 2, 2, 4, 4, 4, None),
    39: SongMeta("Flight of the Bumblebee", "FamilyJules", "YARG Official Setlist", "yarg", 6, 3, 6, None, None, None, None, None, None, None),
    40: SongMeta("Formless Collective", "A Pretext to Human Suffering", "YARG Official Setlist", "yarg", 6, 5, 8, None, None, None, 0, 0, 0, None),
    41: SongMeta("Frank Scored a Video Game", "Max Boras", "YARG Official Setlist", "yarg", 6, 5, 5, None, None, None, None, None, None, None),
    42: SongMeta("Front Row Seats (To Watching Your World Burn)", "FoundiT", "YARG Official Setlist", "yarg", 2, 2, 5, None, 1, 1, 3, 3, 3, None),
    43: SongMeta("The Game", "RinRin", "YARG Official Setlist", "yarg", 4, 2, 4, 4, 2, 2, 3, 3, 3, None),
    44: SongMeta("God Only Knows (feat. Kasane Teto)", "Bitbreaker", "YARG Official Setlist", "yarg", 5, 5, 5, None, 4, 4, 3, 3, 3, None),
    45: SongMeta("Guess I'll Never Know", "TrackTribe", "YARG Official Setlist", "yarg", 1, 0, 3, None, 0, 0, 2, 2, 2, None),
    46: SongMeta("Half Measures", "Aaron Musslewhite", "YARG Official Setlist", "yarg", 0, 0, 1, None, 0, 1, 6, 6, 6, None),
    47: SongMeta("Human God", "Hadson", "YARG Official Setlist", "yarg", 4, 3, 3, None, None, None, 1, 1, 1, None),
    48: SongMeta("I Don't Wanna Talk", "Carter Vail", "YARG Official Setlist", "yarg", 3, 3, 3, None, 2, 2, 2, 2, 2, None),
    49: SongMeta("I Wish That I Could Fall (feat. GUMI)", "Jamie Paige", "YARG Official Setlist", "yarg", 3, 5, 1, None, 5, 5, 5, 5, 5, None),
    50: SongMeta("I'm a Bug", "Fries on the Side", "YARG Official Setlist", "yarg", 1, 1, 3, None, 5, 5, 2, 2, 2, None),
    51: SongMeta("Igowallah", "Daniel Thrasher", "YARG Official Setlist", "yarg", 0, 2, 5, None, 0, 0, 4, 4, 4, None),
    52: SongMeta("In My Head", "Halfway to Michigan", "YARG Official Setlist", "yarg", 1, 1, 2, None, None, None, 2, 2, 2, None),
    53: SongMeta("Is This What You Wanted", "Scro", "YARG Official Setlist", "yarg", 4, 1, 2, None, 2, 2, 5, 5, 5, None),
    54: SongMeta("It Kills Me", "Roomie", "YARG Official Setlist", "yarg", 2, 2, 4, None, 1, 2, 3, 3, 3, None),
    55: SongMeta("Jenny B", "Bumblefoot", "YARG Official Setlist", "yarg", 7, 4, 2, 2, None, None, 5, None, None, None),
    56: SongMeta("John, Take Me with You", "JW Francis", "YARG Official Setlist", "yarg", 2, 2, 2, None, None, None, 2, 2, 2, None),
    57: SongMeta("Join the Club", "Tilly Louise", "YARG Official Setlist", "yarg", 3, 2, 2, None, 3, 3, 3, 3, 3, None),
    58: SongMeta("Languish", "Our Common Collapse", "YARG Official Setlist", "yarg", 4, 3, 5, 5, 2, 2, 0, 0, 0, None),
    59: SongMeta("Long in the Tooth", "Flying Raccoon Suit", "YARG Official Setlist", "yarg", 5, 3, 5, 5, 3, 3, 2, 2, 2, None),
    60: SongMeta("Luminaire", "insaneintherainmusic", "YARG Official Setlist", "yarg", 3, 3, 7, None, 5, 5, None, None, None, None),
    61: SongMeta("Marlboro Mountain", "Sweet Bike", "YARG Official Setlist", "yarg", 3, 3, 3, None, 0, 0, 3, 3, 3, None),
    62: SongMeta("The Masquerade", "Cantervice", "YARG Official Setlist", "yarg", 4, 4, 4, None, 5, 5, 2, 2, 2, None),
    63: SongMeta("Mass Gap", "Mindiode", "YARG Official Setlist", "yarg", 6, 6, 6, None, 6, 7, None, None, None, None),
    64: SongMeta("Moonlight Sonata 3rd Mvt (Big Band Version)", "The 8-Bit Big Band", "YARG Official Setlist", "yarg", 3, 5, 7, None, 6, 6, None, None, None, None),
    65: SongMeta("Need 2", "Pinegrove", "YARG Official Setlist", "yarg", 3, 0, 0, None, 2, 2, 1, 1, 1, None),
    66: SongMeta("The New World Disorder", "Höwler", "YARG Official Setlist", "yarg", 7, 7, 6, 6, None, None, 3, 3, 3, None),
    67: SongMeta("No Nations", "Jets Overhead", "YARG Official Setlist", "yarg", 0, 1, 0, None, 0, 0, 1, 1, 1, None),
    68: SongMeta("No Remedy", "Levia", "YARG Official Setlist", "yarg", 1, 1, 3, None, 3, 3, 2, 2, 2, None),
    69: SongMeta("Nomu", "Good Kid", "YARG Official Setlist", "yarg", 3, 2, 3, None, None, None, 5, 5, 5, None),
    70: SongMeta("Numb the Mind", "NyxTheShield", "YARG Official Setlist", "yarg", 1, 0, 2, None, 0, 0, 2, None, None, None),
    71: SongMeta("Oh, Krissy Baby!", "WhyLucas", "YARG Official Setlist", "yarg", 3, 2, 2, None, 3, 3, 4, 4, 4, None),
    72: SongMeta("Oopsie Daisy", "JubyPhonic", "YARG Official Setlist", "yarg", 1, 3, 2, None, 2, 2, 3, 3, 3, None),
    73: SongMeta("Over Again", "Alex Sandra", "YARG Official Setlist", "yarg", 2, 1, 2, None, 1, 1, 5, 5, 5, None),
    74: SongMeta("Overdrive", "Vessel", "YARG Official Setlist", "yarg", 3, 2, 3, None, None, None, 3, None, None, None),
    75: SongMeta("Oxygen", "Marta Vega", "YARG Official Setlist", "yarg", 2, 1, 2, None, 2, 2, 2, 2, 2, None),
    76: SongMeta("Participation Trophy Wife", "Thanks! I Hate It", "YARG Official Setlist", "yarg", 4, 3, 3, None, None, None, 3, 3, None, None),
    77: SongMeta("Pixel Galaxy", "Snail's House", "YARG Official Setlist", "yarg", 6, 2, 4, None, 3, 3, None, None, None, None),
    78: SongMeta("Pizza Rolls", "Bottom Bunk", "YARG Official Setlist", "yarg", 5, 1, 2, 2, None, None, 2, 2, 2, None),
    79: SongMeta("Plastic Boogie", "King Gizzard and the Lizard Wizard", "YARG Official Setlist", "yarg", 3, 3, 1, None, 1, 1, 2, 2, 2, None),
    80: SongMeta("Poser", "Luminism", "YARG Official Setlist", "yarg", 4, 3, 3, None, None, None, 4, 4, 4, None),
    81: SongMeta("Positively Clark Street", "Telethon", "YARG Official Setlist", "yarg", 4, 2, 2, None, 2, 2, 4, 4, 4, None),
    82: SongMeta("Queen of the Night", "The Vanished People", "YARG Official Setlist", "yarg", 3, 4, 3, None, 3, 3, 4, 4, 4, None),
    83: SongMeta("Runnin Man", "Stone Deep", "YARG Official Setlist", "yarg", 3, 3, 5, 5, None, None, 0, 0, 0, None),
    84: SongMeta("Sadness (feat. Sapphire Noel)", "Heartsick", "YARG Official Setlist", "yarg", 2, 2, 5, None, 2, 2, 2, 2, None, None),
    85: SongMeta("Salt the Wound", "Surefire", "YARG Official Setlist", "yarg", 3, 3, 6, None, 0, 0, 0, 0, 0, None),
    86: SongMeta("Seasons (feat. Shiki Miyoshino)", "Alohaii", "YARG Official Setlist", "yarg", 2, 1, 0, None, 1, 2, 3, 3, None, None),
    87: SongMeta("Show Ya", "Nana Asteria", "YARG Official Setlist", "yarg", 2, 0, 2, None, 2, 2, 3, 3, 3, None),
    88: SongMeta("Smile for Me", "The Robot's Guide to Living", "YARG Official Setlist", "yarg", 4, 2, 4, None, None, None, 3, 3, 3, None),
    89: SongMeta("Song of November", "Frantic Memories", "YARG Official Setlist", "yarg", 4, 4, 4, None, 1, 1, 3, 3, 3, None),
    90: SongMeta("Spirit", "Practically People", "YARG Official Setlist", "yarg", 2, 1, 1, None, 2, 2, 3, 3, 3, None),
    91: SongMeta("Splinter", "FIG", "YARG Official Setlist", "yarg", 2, 0, 1, None, 2, 3, 3, 3, 3, None),
    92: SongMeta("Stowaway Ants", "Alpha Boötis", "YARG Official Setlist", "yarg", 3, 2, 4, None, 4, 4, 3, 3, 3, None),
    93: SongMeta("Strangers Once Again (feat. Treb and Ofir Tabakov)", "Tanger", "YARG Official Setlist", "yarg", 4, 3, 6, None, 4, 6, 5, 5, 5, None),
    94: SongMeta("Stress", "Jim's Big Ego", "YARG Official Setlist", "yarg", 5, 5, 3, 3, 5, 5, 4, 4, 4, None),
    95: SongMeta("Sweet Victory", "Bob Kulick and David Glen Eisley", "YARG Official Setlist", "yarg", 3, 1, 2, None, 3, 3, 3, 3, 3, None),
    96: SongMeta("Synthespian", "Prototype", "YARG Official Setlist", "yarg", 5, 5, 6, None, None, None, 2, 2, None, None),
    97: SongMeta("They Call", "Auris", "YARG Official Setlist", "yarg", 4, 4, 4, None, None, None, 2, 2, 2, None),
    98: SongMeta("Time", "Vandalheart", "YARG Official Setlist", "yarg", 3, 2, 4, 4, 0, 0, 3, 3, 3, None),
    99: SongMeta("To Let Go", "NateWantsToBattle", "YARG Official Setlist", "yarg", 3, 3, 4, None, 1, 1, 4, 4, 4, None),
    100: SongMeta("Vehemence", "Reo", "YARG Official Setlist", "yarg", 6, 4, 6, None, None, None, None, None, None, None),
    101: SongMeta("Voidwalker", "Inflicted", "YARG Official Setlist", "yarg", 4, 3, 5, None, 0, 0, 0, 0, 0, None),
    102: SongMeta("We All Float Down Here", "Four Year Strong", "YARG Official Setlist", "yarg", 6, 4, 5, None, None, None, 2, 2, None, None),
    103: SongMeta("Burn", "Troubled Minds", "Assorted Rock 1", "yargdlc", 1, 0, 1, None, None, None, 1, 1, 1, None),
    104: SongMeta("Drunken Monday (Freeway Mix)", "Fisher Wagg", "Assorted Rock 1", "yargdlc", 3, 2, 1, 2, None, None, 3, 3, 3, 3),
    105: SongMeta("Middle of the City Road", "Walter Ralts", "Assorted Rock 1", "yargdlc", 3, 3, 2, 2, 1, 1, None, None, None, 1),
    106: SongMeta("Moonlight", "Chill", "Assorted Rock 1", "yargdlc", 2, 0, None, None, 1, 1, 1, None, None, None),
    107: SongMeta("Rock Thing", "Creo", "Assorted Rock 1", "yargdlc", 3, 1, 3, None, 4, 4, None, None, None, None),
    108: SongMeta("Simplicity", "Scott Buckley", "Assorted Rock 1", "yargdlc", 1, 0, 1, None, 2, 2, None, None, None, None),
    109: SongMeta("Turtleneck", "TrackTribe", "Assorted Rock 1", "yargdlc", 3, 1, 3, None, 2, 2, None, None, None, None),
    110: SongMeta("By the Seaside (feat. Kitsui Akira)", "Kirara Magic", "Assorted Electronic 1", "yargdlc", 3, 1, 6, None, 3, 3, 3, 3, None, None),
    111: SongMeta("Feel Good", "Syn Cole", "Assorted Electronic 1", "yargdlc", 2, 1, 1, None, 2, 3, 2, 2, None, None),
    112: SongMeta("Ghost", "Aaron Musslewhite", "Assorted Electronic 1", "yargdlc", 3, 1, 2, None, 2, 2, 4, 4, None, None),
    113: SongMeta("Radioactive", "Waterflame", "Assorted Electronic 1", "yargdlc", 2, 6, 5, 5, 4, 5, 0, None, None, 2),
    114: SongMeta("Rot for Clout (feat. Kasane Teto)", "Jamie Paige", "Assorted Electronic 1", "yargdlc", 3, 4, 4, None, 4, 5, 6, 6, None, 3),
    115: SongMeta("Say It Back", "tv room", "Assorted Electronic 1", "yargdlc", 4, 2, 4, None, 4, 5, 5, 5, None, None),
    116: SongMeta("Space and Time! (feat. Jelly Hoshiumi)", "SO87", "Assorted Electronic 1", "yargdlc", 7, 2, 0, None, 4, 5, 3, 3, 3, None),
    117: SongMeta("Angel in Disguise (feat. Kitsui Akira)", "Alohaii", "SUMMERTIDE", "yargdlc", 2, 2, 2, None, 3, 3, 5, 5, None, None),
    118: SongMeta("Cinnamon (feat. Miori Celesta and Yuuna Nini)", "Alohaii", "SUMMERTIDE", "yargdlc", 2, 1, 3, None, 2, 2, 6, 6, 6, None),
    119: SongMeta("Embrace (feat. Kiyon)", "Alohaii", "SUMMERTIDE", "yargdlc", 5, 3, 2, None, 3, 3, 4, 4, 4, 4),
    120: SongMeta("Heart of Glass (feat. Rachie)", "Alohaii", "SUMMERTIDE", "yargdlc", 2, 3, 4, None, 3, 3, 6, 6, None, None),
    121: SongMeta("Hopeless Romantic (feat. JubyPhonic)", "Alohaii", "SUMMERTIDE", "yargdlc", 0, 0, 2, None, 2, 3, 3, 3, 3, None),
    122: SongMeta("Love Me Not (feat. Tofie)", "Alohaii", "SUMMERTIDE", "yargdlc", 4, 0, 1, None, 2, 2, 4, 4, 4, None),
    123: SongMeta("Magazines (feat. Nia Suzune)", "Alohaii", "SUMMERTIDE", "yargdlc", 3, 2, 2, None, 1, 3, 5, 5, 5, None),
    124: SongMeta("One Step at a Time (feat. Miori Celesta)", "Alohaii", "SUMMERTIDE", "yargdlc", 3, 2, 3, None, 2, 2, 3, 3, 3, 6),
    125: SongMeta("Rose (feat. Ember Amane)", "Alohaii", "SUMMERTIDE", "yargdlc", 2, 1, 1, None, 2, 2, 3, 3, 3, None),
    126: SongMeta("Through the Night (feat. Yuuka Bear)", "Alohaii", "SUMMERTIDE", "yargdlc", 5, 4, 2, None, 2, 2, 4, 4, 4, 4),
    127: SongMeta("Cars", "JW Francis", "WANDERKID", "yargdlc", 3, 1, None, None, None, None, 2, 2, 2, None),
    128: SongMeta("Don't Fall Apart", "JW Francis", "WANDERKID", "yargdlc", 3, 2, 2, None, 0, 0, 2, 2, None, None),
    129: SongMeta("Fake It Till You Make It", "JW Francis", "WANDERKID", "yargdlc", 1, 0, 1, 1, 0, 0, 1, None, None, None),
    130: SongMeta("Holy Mountain", "JW Francis", "WANDERKID", "yargdlc", 3, 4, 4, None, 2, 2, 4, None, None, 4),
    131: SongMeta("I Love You", "JW Francis", "WANDERKID", "yargdlc", 2, 2, 2, None, 1, 2, 2, 2, None, None),
    132: SongMeta("I'm Probably a Ghost", "JW Francis", "WANDERKID", "yargdlc", 3, 2, 4, 4, 0, 0, 2, None, None, None),
    133: SongMeta("Make Another Record", "JW Francis", "WANDERKID", "yargdlc", 3, 2, 4, None, 1, 1, 2, None, None, None),
    134: SongMeta("Maybe", "JW Francis", "WANDERKID", "yargdlc", 1, 3, 4, None, 2, 2, 4, 4, 4, None),
    135: SongMeta("Only with You", "JW Francis", "WANDERKID", "yargdlc", 1, 2, 1, 1, 1, 2, 3, 3, 3, None),
    136: SongMeta("Wanderkid", "JW Francis", "WANDERKID", "yargdlc", 1, 3, 4, None, 0, 0, 4, 4, None, None),
    137: SongMeta("Bridal Chorus", "Richard Wagner", "Classical Keys Pack 1", "yargdlc", None, 3, None, None, 3, 3, None, None, None, None),
    138: SongMeta("Clair de Lune", "Claude Debussy", "Classical Keys Pack 1", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    139: SongMeta("Entrance of the Gladiators", "Julius Fučík", "Classical Keys Pack 1", "yargdlc", None, 4, None, None, 4, 4, None, None, None, None),
    140: SongMeta("Maple Leaf Rag", "Scott Joplin", "Classical Keys Pack 1", "yargdlc", None, 3, None, None, 5, 5, None, None, None, None),
    141: SongMeta("Marche Funèbre", "Frédéric Chopin", "Classical Keys Pack 1", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    142: SongMeta("Scherzo No. 1", "Frédéric Chopin", "Classical Keys Pack 1", "yargdlc", None, 5, None, None, 7, 7, None, None, None, None),
    143: SongMeta("Frère Jacques", "Jean-Philippe Rameau", "Children's Keys Pack 1", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    144: SongMeta("Happy Birthday to You", "Patty and Mildred J. Hill", "Children's Keys Pack 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    145: SongMeta("Mary Had a Little Lamb", "Sarah Josepha Hale", "Children's Keys Pack 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    146: SongMeta("Rock-a-Bye Baby", "Effie I. Canning", "Children's Keys Pack 1", "yargdlc", None, 1, None, None, 1, 1, None, None, None, None),
    147: SongMeta("Row, Row, Row Your Boat", "Eliphalet Oram Lyte", "Children's Keys Pack 1", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    148: SongMeta("Twinkle, Twinkle, Little Star", "Jane Taylor", "Children's Keys Pack 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    149: SongMeta("Dance of the Sugar Plum Fairy", "Pyotr Ilyich Tchaikovsky", "Christmas Keys 1", "yargdlc", None, 4, None, None, 4, 4, None, None, None, None),
    150: SongMeta("Deck the Halls", "Thomas Oliphant", "Christmas Keys 1", "yargdlc", None, 2, None, None, 3, 3, None, None, None, None),
    151: SongMeta("Good King Wenceslas", "John Mason Neale and Thomas Helmore", "Christmas Keys 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    152: SongMeta("Jingle Bells", "James Lord Pierpont", "Christmas Keys 1", "yargdlc", None, 3, None, None, 2, 2, None, None, None, None),
    153: SongMeta("Jolly Old Saint Nicholas", "Emily Huntington Miller and James R. Murray", "Christmas Keys 1", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    154: SongMeta("Joy to the World", "Isaac Watts", "Christmas Keys 1", "yargdlc", None, 1, None, None, 2, 2, None, None, None, None),
    155: SongMeta("Amelioration", "Chaotrope", "YARN Pack 1", "yarn", 6, 4, 6, None, None, None, None, None, None, None),
    156: SongMeta("Burn", "Counterparts", "YARN Pack 1", "yarn", 2, 1, None, None, None, None, None, None, None, 2),
    157: SongMeta("Eviternal", "James Paddock", "YARN Pack 1", "yarn", 5, 4, 6, None, 4, 5, 5, 5, 5, None),
    158: SongMeta("Fearfulness", "Jaden (ft. Various Artists)", "YARN Pack 1", "yarn", 10, None, None, None, None, None, None, None, None, None),
    159: SongMeta("How", "Exyl and Paper Skies", "YARN Pack 1", "yarn", 4, None, None, None, None, None, None, None, None, None),
    160: SongMeta("I'm mindless :3", "Catastrophe", "YARN Pack 1", "yarn", 8, None, None, None, None, None, None, None, None, None),
    161: SongMeta("Reaper (2023 Remaster)", "Chaotrope", "YARN Pack 1", "yarn", 6, 3, 6, None, None, None, None, None, None, None),
    162: SongMeta("Second Wind", "Walter Ralts", "YARN Pack 1", "yarn", 3, 6, 6, 6, 3, 3, None, None, None, None),
    163: SongMeta("Ways of Torment", "Silverhawk", "YARN Pack 1", "yarn", 5, None, None, None, None, None, None, None, None, None),
    164: SongMeta("Whispers (Rose Ver.)", "Asilveras", "YARN Pack 1", "yarn", 2, 1, 2, None, None, None, None, None, None, None),
    165: SongMeta("Abomination", "The Final Event", "Mini-Wave 0", "yarn", 4, None, 6, None, None, None, 1, None, None, None),
    166: SongMeta("Back To School Bitches (Kiraken-G Remix)", "Gabber Cat", "Mini-Wave 0", "yarn", 10, None, None, None, None, None, None, None, None, None),
    167: SongMeta("Brain Implosion Energy Drink (feat. Kasane Teto and Eleanor Forte)", "Flanger Moose", "Mini-Wave 0", "yarn", 2, 1, 3, None, 1, 1, 4, 4, None, None),
    168: SongMeta("Code 75", "FrenchFried", "Mini-Wave 0", "yarn", 4, 2, 4, None, 3, 3, 4, 4, 4, None),
    169: SongMeta("Dance Mr. Funnybones (LOOP)", "PuffballsUnited", "Mini-Wave 0", "yarn", 1, 1, 2, None, None, None, None, None, None, 0),
    170: SongMeta("Hard Licker", "Flalcon", "Mini-Wave 0", "yarn", 4, 4, 5, None, None, None, None, None, None, None),
    171: SongMeta("help, the sillies are after me!1!!!1", "It's Only Connor", "Mini-Wave 0", "yarn", None, 3, 4, 4, 4, 4, None, None, None, None),
    172: SongMeta("Nice Logo", "Exyl & Dalux", "Mini-Wave 0", "yarn", 2, 1, 2, None, 2, 2, 0, None, None, None),
    173: SongMeta("opus_10", "De Dubbelrieters", "Mini-Wave 0", "yarn", None, 5, None, None, 6, 6, None, None, None, None),
    174: SongMeta("Still Got It", "The Coaᴛᴛablers", "Mini-Wave 0", "yarn", 2, 2, 2, None, None, None, None, None, None, None),
    175: SongMeta("Wou Wou Wou", "Yebert", "Mini-Wave 0", "yarn", 6, None, None, None, None, None, 0, None, None, None),
    176: SongMeta("Control", "Thousand Thoughts", "Assorted Metal 1", "yargdlc", 3, 3, 2, None, 3, 3, 3, 3, 3, 3),
    177: SongMeta("Full Body Plutonium", "Frostbitt", "Assorted Metal 1", "yargdlc", 4, 3, 5, 5, None, None, 3, 3, None, 3),
    178: SongMeta("Harbinger of Pestilence", "Silverhawk", "Assorted Metal 1", "yargdlc", 6, 3, 6, 6, None, None, None, None, None, 4),
    179: SongMeta("Hell", "Vandalheart", "Assorted Metal 1", "yargdlc", 4, 2, 5, None, 0, 0, 3, 3, 3, 4),
    180: SongMeta("Simple Folds", "Zephyrianna, Tsyolin and BoffleFloffle", "Assorted Metal 1", "yargdlc", 3, 3, 4, None, 3, 3, 4, 4, 4, 3),
    181: SongMeta("Sleep Cycles", "Heartsick", "Assorted Metal 1", "yargdlc", 3, 3, 4, None, 2, 2, 1, 1, 1, 3),
    182: SongMeta("The Mortal Plane", "Mindiode", "Assorted Metal 1", "yargdlc", 5, 3, 5, None, 5, 5, None, None, None, 4),
    183: SongMeta("What You Really Want", "Garlagan", "Assorted Metal 1", "yargdlc", 5, 4, 3, None, 5, 5, 4, 4, 4, 5),
    184: SongMeta("Chopsticks", "Arthur de Lulli", "Children's Keys Pack 2", "yargdlc", None, 1, None, None, 2, 2, None, None, None, None),
    185: SongMeta("Hey Diddle Diddle", "James William Elliott", "Children's Keys Pack 2", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    186: SongMeta("Old MacDonald Had a Farm", "Thomas d'Urfey", "Children's Keys Pack 2", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    187: SongMeta("Over the River and Through the Woods", "Lydia Maria Child", "Children's Keys Pack 2", "yargdlc", None, 1, None, None, 1, 1, None, None, None, None),
    188: SongMeta("Pop Goes the Weasel", "Eugène Coulon", "Children's Keys Pack 2", "yargdlc", None, 1, None, None, 0, 0, None, None, None, None),
    189: SongMeta("Three Blind Mice", "Thomas Ravenscroft", "Children's Keys Pack 2", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    190: SongMeta("Funiculì, Funiculà", "Luigi Denza", "Classical Keys Pack 2", "yargdlc", None, 3, None, None, 3, 3, None, None, None, None),
    191: SongMeta("Hungarian Rhapsody No. 2", "Franz Liszt", "Classical Keys Pack 2", "yargdlc", None, 6, None, None, 7, 7, None, None, None, None),
    192: SongMeta("Minuet in G Major", "Christian Petzold", "Classical Keys Pack 2", "yargdlc", None, 1, None, None, 1, 1, None, None, None, None),
    193: SongMeta("Piano Sonata No. 16, Mvt. I: Allegro", "Wolfgang Amadeus Mozart", "Classical Keys Pack 2", "yargdlc", None, 5, None, None, 5, 5, None, None, None, None),
    194: SongMeta("The Well-Tempered Clavier Book 1 No. 1: Prelude and Fugue in C Major", "Johann Sebastian Bach", "Classical Keys Pack 2", "yargdlc", None, 0, None, None, 2, 2, None, None, None, None),
    195: SongMeta("Twelfth Street Rag", "Euday L. Bowman", "Classical Keys Pack 2", "yargdlc", None, 3, None, None, 6, 6, None, None, None, None),
    196: SongMeta("Below the Waves", 'Jake "virt" Kaufman', "FX4", "yarn", 4, 4, 5, None, None, None, None, None, None, None),
    197: SongMeta("First Flight", 'Jake "virt" Kaufman', "FX4", "yarn", 5, 6, 6, None, None, None, None, None, None, None),
    198: SongMeta("HBO Feature Presentation", 'Jake "virt" Kaufman', "FX4", "yarn", 2, 0, 2, None, None, None, None, None, None, None),
    199: SongMeta("Incident Zero", 'Jake "virt" Kaufman', "FX4", "yarn", 4, 5, 6, None, None, None, None, None, None, None),
    200: SongMeta("Journey into the Rift", 'Jake "virt" Kaufman', "FX4", "yarn", 5, 4, 7, None, None, None, None, None, None, None),
    201: SongMeta("Reconstruct", 'Jake "virt" Kaufman', "FX4", "yarn", 5, 3, 3, None, None, None, None, None, None, None),
    202: SongMeta("Singularity", 'Jake "virt" Kaufman', "FX4", "yarn", 5, 4, 6, None, None, None, None, None, None, None),
    203: SongMeta("The Time Vampire", 'Jake "virt" Kaufman', "FX4", "yarn", 5, 4, 6, None, None, None, None, None, None, None),
    204: SongMeta("Undone", 'Jake "virt" Kaufman', "FX4", "yarn", 4, 4, 5, None, None, None, None, None, None, None),
    205: SongMeta("Weapon", 'Jake "virt" Kaufman', "FX4", "yarn", 4, 4, 6, None, None, None, None, None, None, None),
    206: SongMeta("Abyss of Time", "James Paddock", "Abyss of Time", "yarn", 3, 2, 3, None, None, None, 3, 3, 3, None),
    207: SongMeta("Aphrodite", "James Paddock", "Abyss of Time", "yarn", 4, 4, 5, None, None, None, 2, 2, None, None),
    208: SongMeta("Bleed Your Hate Out", "James Paddock", "Abyss of Time", "yarn", 4, 4, 5, None, None, None, 3, 3, None, None),
    209: SongMeta("Death Drive", "James Paddock", "Abyss of Time", "yarn", 2, 3, 4, None, None, None, 3, 3, 3, None),
    210: SongMeta("Desert Rose", "James Paddock", "Abyss of Time", "yarn", 3, 2, 3, None, None, None, 2, 2, None, None),
    211: SongMeta("Destroyer of Worlds", "James Paddock", "Abyss of Time", "yarn", 3, 3, 5, None, None, None, 1, 1, 1, None),
    212: SongMeta("Impossible", "James Paddock", "Abyss of Time", "yarn", 4, 4, 4, None, None, None, 3, 3, None, None),
    213: SongMeta("Inertia", "James Paddock", "Abyss of Time", "yarn", 2, 1, 2, None, None, None, 3, 3, None, None),
    214: SongMeta("Mind Like a Minefield", "James Paddock", "Abyss of Time", "yarn", 3, 3, 4, None, None, None, 4, 4, 4, None),
    215: SongMeta("Scorch the Earth", "James Paddock", "Abyss of Time", "yarn", 3, 3, 4, None, None, None, 4, None, None, None),
    216: SongMeta("Summer Rain", "James Paddock", "Abyss of Time", "yarn", 3, 2, 3, None, None, None, 3, None, None, None),
    217: SongMeta("Swallow", "James Paddock", "Abyss of Time", "yarn", 2, 2, 3, None, None, None, 2, 2, 2, None),
    218: SongMeta("The Penalty", "James Paddock", "Abyss of Time", "yarn", 5, 4, 6, None, None, None, 3, 3, None, None),
    219: SongMeta("Unclear Warfare", "James Paddock", "Abyss of Time", "yarn", 3, 2, 3, None, None, None, 4, 4, 4, None),
    220: SongMeta("We've Seen Better Days", "James Paddock", "Abyss of Time", "yarn", 2, 1, 2, None, None, None, 3, 3, 3, None),
    221: SongMeta("200", "Glass Beach", "Plastic Death", "yarn", 1, 1, 4, None, None, None, None, None, None, None),
    222: SongMeta("Abyss Angel", "Glass Beach", "Plastic Death", "yarn", 2, 1, 4, None, None, None, None, None, None, None),
    223: SongMeta("Coelacanth", "Glass Beach", "Plastic Death", "yarn", 3, 2, 3, None, None, None, None, None, None, None),
    224: SongMeta("Commatose", "Glass Beach", "Plastic Death", "yarn", 6, 2, 4, None, None, None, None, None, None, None),
    225: SongMeta("Cul-de-Sac", "Glass Beach", "Plastic Death", "yarn", 3, 1, 3, None, None, None, None, None, None, None),
    226: SongMeta("Guitar Song", "Glass Beach", "Plastic Death", "yarn", 1, 1, 3, None, None, None, None, None, None, None),
    227: SongMeta("Motions", "Glass Beach", "Plastic Death", "yarn", 2, 1, 3, None, None, None, None, None, None, None),
    228: SongMeta("Puppy", "Glass Beach", "Plastic Death", "yarn", 2, 1, 3, None, None, None, None, None, None, None),
    229: SongMeta("Rare Animal", "Glass Beach", "Plastic Death", "yarn", 3, 2, 3, None, None, None, None, None, None, None),
    230: SongMeta("Slip under the Door", "Glass Beach", "Plastic Death", "yarn", 3, 1, 3, None, None, None, None, None, None, None),
    231: SongMeta("The CIA", "Glass Beach", "Plastic Death", "yarn", 5, 1, 5, None, None, None, None, None, None, None),
    232: SongMeta("The Killer", "Glass Beach", "Plastic Death", "yarn", 1, 1, 2, None, None, None, None, None, None, None),
    233: SongMeta("Whalefall", "Glass Beach", "Plastic Death", "yarn", 3, 1, 6, None, None, None, None, None, None, None),
    234: SongMeta("Dance Like an Idiot", "Lemon Demon", "Assorted Rock 2", "yargdlc", 4, 3, 2, 2, 4, 4, 4, 4, 4, 3),
    235: SongMeta("Let Me Dance (feat. Miori Celesta)", "Alohaii", "Assorted Rock 2", "yargdlc", 5, 2, 1, None, 2, 3, 2, 2, 2, None),
    236: SongMeta("Like I Used to Be", "Troubled Minds", "Assorted Rock 2", "yargdlc", 2, 2, 3, None, None, None, 1, 1, 1, None),
    237: SongMeta("North Carolina", "The Broken Spokes", "Assorted Rock 2", "yargdlc", 2, 0, 1, None, None, None, 1, 1, None, None),
    238: SongMeta("Safehouse", "Aviations", "Assorted Rock 2", "yargdlc", 5, 4, 5, None, 6, 6, 5, 5, 5, 4),
    239: SongMeta("Surf Song", "Saturn's Girlfriend", "Assorted Rock 2", "yargdlc", 5, 3, 5, None, None, None, 2, 2, None, None),
    240: SongMeta("Until the Wind Blows Us Away (feat. Leucinjel)", "Clover from the Clouds", "Assorted Rock 2", "yargdlc", 4, 2, 2, None, 0, 1, 2, 2, None, None),
    241: SongMeta("All These Darlings and Now Me", "Sunflo'er", "YARN Pack 2", "yarn", 5, None, None, None, None, None, None, None, None, None),
    242: SongMeta("Alternative Ego", "Mattias", "YARN Pack 2", "yarn", 8, 6, 8, None, None, None, None, None, None, None),
    243: SongMeta("Apple Fritter", "Guttural", "YARN Pack 2", "yarn", 2, 2, 3, None, None, None, None, None, None, None),
    244: SongMeta("BIRDBRAIN (feat. OK Glass and Kasane Teto)", "Jamie Paige", "YARN Pack 2", "yarn", 3, 3, 4, None, None, None, 5, None, None, None),
    245: SongMeta("Country", "Miriam McCombe", "YARN Pack 2", "yarn", 4, 0, 1, None, 2, 3, 3, 3, 3, None),
    246: SongMeta("Desolate Memory", "Benevolence Lost", "YARN Pack 2", "yarn", 4, None, 5, None, None, None, None, None, None, None),
    247: SongMeta("Glass Beach", "Glass Beach", "YARN Pack 2", "yarn", 3, 2, 4, None, None, None, None, None, None, None),
    248: SongMeta("Keep Your Guard Up", "raphaelgoulart", "YARN Pack 2", "yarn", 4, 3, 5, None, 4, 4, None, None, None, None),
    249: SongMeta("Machine Love (feat. Kasane Teto)", "Jamie Paige", "YARN Pack 2", "yarn", 3, 3, 3, None, None, None, 4, None, None, None),
    250: SongMeta("Madtown", "Before After Again", "YARN Pack 2", "yarn", 0, 3, 2, 2, 1, 1, 1, 1, None, 0),
    251: SongMeta("Stranded", "FiniShay", "YARN Pack 2", "yarn", 4, 2, 5, None, None, None, None, None, None, None),
    252: SongMeta("Underground Popstars", "The Dharmites", "YARN Pack 2", "yarn", 3, 2, 2, None, None, None, 2, None, None, None),
    253: SongMeta("999,999 / 1,000,000", "Nine Inch Nails", "The Slip", "yargdlc", 3, 2, 3, 3, 2, 2, 4, 4, 4, 1),
    254: SongMeta("Corona Radiata", "Nine Inch Nails", "The Slip", "yargdlc", 1, 0, 0, 0, 0, 1, None, None, None, 0),
    255: SongMeta("Demon Seed", "Nine Inch Nails", "The Slip", "yargdlc", 2, 1, 4, 4, 2, 2, 3, 3, 3, 1),
    256: SongMeta("Echoplex", "Nine Inch Nails", "The Slip", "yargdlc", 3, 2, 4, 4, 0, 0, 2, 2, 2, 2),
    257: SongMeta("Head Down", "Nine Inch Nails", "The Slip", "yargdlc", 4, 1, 4, 4, 4, 3, 2, 2, None, 3),
    258: SongMeta("Letting You", "Nine Inch Nails", "The Slip", "yargdlc", 4, 2, 6, 6, 1, 1, 2, 2, 2, 4),
    259: SongMeta("Lights in the Sky", "Nine Inch Nails", "The Slip", "yargdlc", 0, 0, None, None, 0, 1, 2, None, None, None),
    260: SongMeta("The Four of Us Are Dying", "Nine Inch Nails", "The Slip", "yargdlc", 2, 2, 3, 3, 2, 2, None, None, None, 3),
    261: SongMeta("Alive (feat. Jeremy Fagan)", "Not For Nothing", "YARN Pack 3", "yarn", 4, 3, 5, None, None, 1, 3, 3, 3, 3),
    262: SongMeta("BUTCHER VANITY (ft. Yi Xi)", "FLAVOR FOLEY", "YARN Pack 3", "yarn", 1, 4, 4, None, None, None, 6, 6, 6, None),
    263: SongMeta("Cascade", "Kubbi", "YARN Pack 3", "yarn", 6, None, None, None, None, None, None, None, None, None),
    264: SongMeta("Don't Touch My Plushies", "Japanese Dream", "YARN Pack 3", "yarn", 3, 3, 3, None, None, None, 3, None, None, None),
    265: SongMeta("Guardian Angel", "Silverhawk", "YARN Pack 3", "yarn", 5, None, None, None, None, None, None, None, None, None),
    266: SongMeta("Kimi no Taion (feat. Eleanor Forte)", "Kuwagata-P (feather268)", "YARN Pack 3", "yarn", 3, 3, 2, None, None, None, 4, None, None, None),
    267: SongMeta("n u l l s t a r _", "[SIGNALER] vs. Catonieca", "YARN Pack 3", "yarn", 5, 0, None, None, 3, 5, None, None, None, None),
    268: SongMeta("phleps", "C418", "YARN Pack 3", "yarn", 2, 1, 0, None, 0, 1, 1, None, None, None),
    269: SongMeta("Retry Now (feat. Hatsune Miku)", "NAKISO", "YARN Pack 3", "yarn", 5, None, None, None, None, None, 6, None, None, None),
    270: SongMeta("Year of the Toad (YOTT)", "YOONIE x NĪKAU", "YARN Pack 3", "yarn", 3, 2, 5, None, None, None, 3, 3, 3, None),
    271: SongMeta("Deep Geyser Tunez", "Walter Ralts", "The Water Cycle", "yarn", None, 6, 6, 6, 3, 3, None, None, None, 5),
    272: SongMeta("Hurricane", "Walter Ralts", "The Water Cycle", "yarn", 5, 4, 3, None, 3, 4, None, None, None, 4),
    273: SongMeta("Liquidic Breakdown", "Walter Ralts", "The Water Cycle", "yarn", 3, 4, 5, None, 5, 4, None, None, None, None),
    274: SongMeta("Rain", "Walter Ralts", "The Water Cycle", "yarn", None, 4, None, None, 4, 5, None, None, None, None),
    275: SongMeta("Surface Wind", "Walter Ralts", "The Water Cycle", "yarn", 3, 3, 3, 3, 5, 4, 0, None, None, None),
    276: SongMeta("Thunderstorm", "Walter Ralts", "The Water Cycle", "yarn", 1, 2, 3, None, 1, 1, None, None, None, None),
    277: SongMeta("Tsunami", "Walter Ralts", "The Water Cycle", "yarn", 3, 3, 6, None, 5, 5, None, None, None, None),
    278: SongMeta("Twilight Ocean", "Walter Ralts", "The Water Cycle", "yarn", 3, 3, 3, None, 5, 4, None, None, None, None),
    279: SongMeta("Water's Under", "Walter Ralts", "The Water Cycle", "yarn", None, 3, 4, None, 4, 4, None, None, None, None),
    280: SongMeta("Born of Dirt", "Senza", "Assorted Metal 2", "yargdlc", 4, 2, 6, None, None, None, 0, None, None, 4),
    281: SongMeta("Deceptive Consequences", "Unrelenting Ferocity", "Assorted Metal 2", "yargdlc", 4, 3, 6, None, None, None, None, None, None, 4),
    282: SongMeta("Event Horizon", "Heartsick", "Assorted Metal 2", "yargdlc", 3, 4, 4, None, 1, 1, 0, 0, 0, 4),
    283: SongMeta("Funeral Waltz", "Talsur", "Assorted Metal 2", "yargdlc", 1, 1, 1, None, 2, 2, 1, 1, 1, 1),
    284: SongMeta("I.E.D. Vanflip", "Funeral Wake", "Assorted Metal 2", "yargdlc", 4, 4, 7, 7, None, None, 0, 0, 0, 0),
    285: SongMeta("Introspective Nightmares", "Narcotic Wasteland", "Assorted Metal 2", "yargdlc", 6, 6, 7, None, 0, 0, 0, 0, 0, 6),
    286: SongMeta("Mr. Jackalope (And His Restless Haunting) / When Days End", "Silverhawk", "Assorted Metal 2", "yargdlc", 6, 2, 4, None, None, None, None, None, None, 4),
    287: SongMeta("The Lonesome Tongues", "Our Common Collapse", "Assorted Metal 2", "yargdlc", 4, 3, 5, None, 0, 1, 0, 0, 0, 3),
    288: SongMeta("Train Wreck", "The HIRS Collective", "Assorted Metal 2", "yargdlc", 2, 1, 7, None, None, None, 0, 0, None, 2),
    289: SongMeta("Angels We Have Heard on High", "James Chadwick and Edward Shippen Barnes", "Christmas Keys 2", "yargdlc", None, 2, None, None, 3, 3, None, None, None, None),
    290: SongMeta("O Come, All Ye Faithful", "John Francis Wade", "Christmas Keys 2", "yargdlc", None, 1, None, None, 2, 2, None, None, None, None),
    291: SongMeta("Shchedryk", "Mykola Leontovych", "Christmas Keys 2", "yargdlc", None, 3, None, None, 3, 3, None, None, None, None),
    292: SongMeta("Silent Night", "Franz Xaver Gruber and Joseph Mohr", "Christmas Keys 2", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    293: SongMeta("The First Noël", "Davies Gilbert", "Christmas Keys 2", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    294: SongMeta("The Twelve Days of Christmas", "Frederic Austin", "Christmas Keys 2", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    295: SongMeta("Atelophobia", "Authko", "Teto Pack", "yarn", 2, 2, 3, None, 1, 1, 3, 3, None, 2),
    296: SongMeta("Classic J Dies and Goes to Hell Part 1 (feat. Kasane Teto)", "Glass Beach (feather268)", "Teto Pack", "yarn", 2, 3, 3, None, 3, 4, 3, 3, 3, 2),
    297: SongMeta("Fever Dream", "MiliSen", "Teto Pack", "yarn", 3, 2, 2, None, 3, 4, 4, 4, 4, None),
    298: SongMeta("Overload", "Kirisame", "Teto Pack", "yarn", 2, 4, 1, None, 2, 2, 3, 3, 3, 2),
    299: SongMeta("POTETO CHIP", "ROMA", "Teto Pack", "yarn", 1, 2, 2, None, 3, 3, 3, 3, 3, None),
    300: SongMeta("Ragebait", "Zynthesiren", "Teto Pack", "yarn", 3, 3, 4, None, 0, 0, 3, 3, 3, None),
    301: SongMeta("REGRET ROCK", "MonochroMenace", "Teto Pack", "yarn", 2, 2, 2, None, 2, 2, 2, 2, 2, None),
    302: SongMeta("TAZTY!", "redseas07", "Teto Pack", "yarn", 2, 2, 4, None, 4, 4, 3, 3, 3, None),
    303: SongMeta("SQUARE UP", "Jamie Paige x peak divide & rachel lake", "UNBEATABLE 01", "yargdlc", 4, 4, 5, None, 4, 4, 5, 5, 5, 3),
    304: SongMeta("WAITING", "peak divide & rachel lake", "UNBEATABLE 01", "yargdlc", 5, 3, 5, None, 3, 3, 4, 4, 4, 4),
    305: SongMeta("WORN OUT TAPES [tally-ho version]", "peak divide & rachel lake", "UNBEATABLE 01", "yargdlc", 5,4, 4, None, 5, 6, 4, 4, 4, 5),

}

#Example on using the Songs Dictionary
#
#for name, data in Songs.items():
#    print("Song Name: " + name)
#    print("5 Fret Guitar Diff: " + str(data.guitar5F))
#    print("5 Fret Bass Diff: " + str(data.bass5F))
#
#If you want to use the Songs Dict in other file add to top of file
#
#from .songinfo import Songs
    
    