"""Generated hub-switch mapping contract.

DO NOT EDIT MANUALLY.
Source: worlds/kirbyam/data/hub_switch_contract.json
Generated by: worlds/kirbyam/tools/generate_hub_switch_contract.py
"""

from __future__ import annotations

from typing import Final


HUB_SWITCH_COMPATIBILITY_AP_BITS_BY_LOCATION_KEY: Final[dict[str, tuple[int, ...]]] = {
    "HUB_SWITCH_RAINBOW_ROUTE_NORTH": (15,),
}
