import collections
from BaseClasses import Region, Location, Entrance


def create_regions(world):

    world.regions = [
        create_region('Light World', 'Light', ['Mushroom', 'Bottle Merchant', 'Flute Spot', 'Sunken Treasure', 'Purple Chest'],
                      ["Blinds Hideout", "Hyrule Castle Secret Entrance Drop", 'Zoras River', 'Kings Grave', 'Dam',
                       'Links House', 'Tavern North', 'Chicken House', 'Aginahs Cave', 'Sahasrahlas Hut', 'Kakariko Well Drop', 'Kakariko Well Cave',
                       'Blacksmiths Hut', 'Bat Cave Drop Ledge', 'Bat Cave Cave', 'Sick Kids House', 'Hobo Bridge', 'Lost Woods Hideout Drop', 'Lost Woods Hideout Stump',
                       'Lumberjack Tree Tree', 'Lumberjack Tree Cave', 'Mini Moldorm Cave', 'Ice Rod Cave', 'Lake Hylia Central Island Pier',
                       'Bonk Rock Cave', 'Library', 'Potion Shop', 'Two Brothers House (East)', 'Desert Palace Stairs', 'Eastern Palace', 'Master Sword Meadow',
                       'Sanctuary', 'Sanctuary Grave', 'Old Man Cave (West)', 'Flute Spot 1', 'Dark Desert Teleporter', 'East Hyrule Teleporter', 'South Hyrule Teleporter', 'Kakariko Teleporter',
                       'Elder House (East)', 'Elder House (West)', 'North Fairy Cave', 'North Fairy Cave Drop', 'Lost Woods Gamble', 'Snitch Lady (East)', 'Snitch Lady (West)', 'Tavern (Front)',
                       'Bush Covered House', 'Light World Bomb Hut', 'Kakariko Shop', 'Long Fairy Cave', 'Good Bee Cave', '20 Rupee Cave', 'Cave Shop (Lake Hylia)', 'Waterfall of Wishing', 'Hyrule Castle Main Gate',
                       'Bonk Fairy (Light)', '50 Rupee Cave', 'Fortune Teller (Light)', 'Lake Hylia Fairy', 'Swamp Fairy', 'Desert Fairy', 'Lumberjack House', 'Lake Hylia Fortune Teller', 'Kakariko Gamble Game', 'Top of Pyramid']),
        create_region('Lake Hylia Central Island', 'Light', None, ['Capacity Upgrade', 'Lake Hylia Central Island Teleporter']),
        create_region('Blinds Hideout', 'Inside', ["Blind\'s Hideout - Top",
                                         "Blind\'s Hideout - Left",
                                         "Blind\'s Hideout - Right",
                                         "Blind\'s Hideout - Far Left",
                                         "Blind\'s Hideout - Far Right"]),
        create_region('Hyrule Castle Secret Entrance', 'Inside', ['Link\'s Uncle', 'Secret Passage'], ['Hyrule Castle Secret Entrance Exit']),
        create_region('Zoras River', 'Light', ['King Zora', 'Zora\'s Ledge']),
        create_region('Waterfall of Wishing', 'Inside', ['Waterfall Fairy - Left', 'Waterfall Fairy - Right']),
        create_region('Kings Grave', 'Inside', ['King\'s Tomb']),
        create_region('North Fairy Cave', 'Inside', None, ['North Fairy Cave Exit']),
        create_region('Dam', 'Inside', ['Floodgate Chest']),
        create_region('Links House', 'Inside', ['Link\'s House'], ['Links House Exit']),
        create_region('Tavern', 'Inside', ['Kakariko Tavern']),
        create_region('Elder House', 'Inside', None, ['Elder House Exit (East)', 'Elder House Exit (West)']),
        create_region('Snitch Lady (East)', 'Inside'),
        create_region('Snitch Lady (West)', 'Inside'),
        create_region('Bush Covered House', 'Inside'),
        create_region('Tavern (Front)', 'Inside'),
        create_region('Light World Bomb Hut', 'Inside'),
        create_region('Kakariko Shop', 'Inside'),
        create_region('Fortune Teller (Light)', 'Inside'),
        create_region('Lumberjack House', 'Inside'),
        create_region('Bonk Fairy', 'Inside'),  # near links house both worlds
        create_region('Healer Fairy', 'Inside'),  # 8 entrances?
        create_region('Chicken House', 'Inside', ['Chicken House']),
        create_region('Aginahs Cave', 'Inside', ['Aginah\'s Cave']),
        create_region('Sahasrahlas Hut', 'Inside', ['Sahasrahla\'s Hut - Left', 'Sahasrahla\'s Hut - Middle', 'Sahasrahla\'s Hut - Right', 'Sahasrahla']),
        create_region('Kakariko Well (top)', 'Inside', ['Kakariko Well - Top', 'Kakariko Well - Left', 'Kakariko Well - Middle',
                                              'Kakariko Well - Right', 'Kakariko Well - Bottom'], ['Kakariko Well (top to bottom)']),
        create_region('Kakariko Well (bottom)', 'Inside', None, ['Kakariko Well Exit']),
        create_region('Blacksmiths Hut', 'Inside', ['Blacksmith']),
        create_region('Bat Cave Drop Ledge', 'Light', None, ['Bat Cave Drop']),
        create_region('Bat Cave (right)', 'Inside', ['Magic Bat'], ['Bat Cave Door']),
        create_region('Bat Cave (left)', 'Inside', None, ['Bat Cave Exit']),
        create_region('Sick Kids House', 'Inside', ['Sick Kid']),
        create_region('Hobo Bridge', 'Light', ['Hobo']),
        create_region('Lost Woods Hideout (top)', 'Inside', ['Lost Woods Hideout'], ['Lost Woods Hideout (top to bottom)']),
        create_region('Lost Woods Hideout (bottom)', 'Inside', None, ['Lost Woods Hideout Exit']),
        create_region('Lumberjack Tree (top)', 'Inside', ['Lumberjack Tree'], ['Lumberjack Tree (top to bottom)']),
        create_region('Lumberjack Tree (bottom)', 'Inside', None, ['Lumberjack Tree Exit']),
        create_region('Cave 45 Ledge', 'Light', None, ['Cave 45']),
        create_region('Cave 45', 'Inside', ['Cave 45']),
        create_region('Graveyard Ledge', 'Light', None, ['Graveyard Cave']),
        create_region('Graveyard Cave', 'Inside', ['Graveyard Cave']),
        create_region('Checkerboard Cave', 'Inside', ['Checkerboard Cave']),
        create_region('Long Fairy Cave', 'Inside'),
        create_region('Mini Moldorm Cave', 'Inside', ['Mini Moldorm Cave - Far Left', 'Mini Moldorm Cave - Left', 'Mini Moldorm Cave - Right',
                                            'Mini Moldorm Cave - Far Right', 'Mini Moldorm Cave - Generous Guy']),
        create_region('Ice Rod Cave', 'Inside', ['Ice Rod Cave']),
        create_region('Good Bee Cave', 'Inside'),
        create_region('20 Rupee Cave', 'Inside'),
        create_region('Cave Shop', 'Inside'),  # two connectors in vanilla
        create_region('Bonk Rock Cave', 'Inside', ['Bonk Rock Cave']),
        create_region('Library', 'Inside', ['Library']),
        create_region('Kakariko Gamble Game', 'Inside'),
        create_region('Potion Shop', 'Inside', ['Potion Shop']),
        create_region('Lake Hylia Island', 'Light', ['Lake Hylia Island']),
        create_region('Capacity Upgrade', 'Inside'),
        create_region('Two Brothers House', 'Inside', None, ['Two Brothers House Exit (East)', 'Two Brothers House Exit (West)']),
        create_region('Maze Race Ledge', 'Light', ['Maze Race'], ['Two Brothers House (West)']),
        create_region('50 Rupee Cave', 'Inside'),
        create_region('Desert Ledge', 'Light', ['Desert Ledge'], ['Desert Palace Entrance (North) Rocks', 'Desert Palace Entrance (West)']),
        create_region('Desert Ledge (Northeast)', 'Light', None, ['Checkerboard Cave']),
        create_region('Desert Palace Stairs', 'Light', None, ['Desert Palace Entrance (South)']),
        create_region('Desert Palace Lone Stairs', 'Light', None, ['Desert Palace Stairs Drop', 'Desert Palace Entrance (East)']),
        create_region('Desert Palace Entrance (North) Spot', 'Light', None, ['Desert Palace Entrance (North)', 'Desert Ledge Return Rocks']),
        create_region('Desert Palace Main', 'Inside', ['Desert Palace - Big Chest', 'Desert Palace - Torch', 'Desert Palace - Map Chest'],
                      ['Desert Palace Exit (South)', 'Desert Palace Exit (West)', 'Desert Palace Exit (East)', 'Desert Palace East Wing']),
        create_region('Desert Palace East', 'Inside', ['Desert Palace - Compass Chest', 'Desert Palace - Big Key Chest']),
        create_region('Desert Palace North', 'Inside', ['Desert Palace - Lanmolas', 'Desert Palace - Prize'], ['Desert Palace Exit (North)']),
        create_region('Eastern Palace', 'Inside', ['Eastern Palace - Compass Chest', 'Eastern Palace - Big Chest', 'Eastern Palace - Cannonball Chest',
                                         'Eastern Palace - Big Key Chest', 'Eastern Palace - Map Chest', 'Eastern Palace - Armos Knights', 'Eastern Palace - Prize'], ['Eastern Palace Exit']),
        create_region('Master Sword Meadow', 'Light', ['Master Sword Pedestal']),
        create_region('Lost Woods Gamble', 'Inside'),
        create_region('Hyrule Castle Courtyard', 'Light', None, ['Hyrule Castle Secret Entrance Stairs', 'Hyrule Castle Entrance (South)']),
        create_region('Hyrule Castle Ledge', 'Light', None, ['Hyrule Castle Entrance (East)', 'Hyrule Castle Entrance (West)', 'Agahnims Tower', 'Hyrule Castle Ledge Courtyard Drop']),
        create_region('Hyrule Castle', 'Inside', ['Hyrule Castle - Boomerang Chest', 'Hyrule Castle - Map Chest', 'Hyrule Castle - Zelda\'s Chest'],
                      ['Hyrule Castle Exit (East)', 'Hyrule Castle Exit (West)', 'Hyrule Castle Exit (South)', 'Throne Room']),
        create_region('Sewer Drop', 'Inside', None, ['Sewer Drop']),  # This exists only to be referenced for access checks
        create_region('Sewers (Dark)', 'Inside', ['Sewers - Dark Cross'], ['Sewers Door']),
        create_region('Sewers', 'Inside', ['Sewers - Secret Room - Left', 'Sewers - Secret Room - Middle',
                                 'Sewers - Secret Room - Right'], ['Sanctuary Push Door', 'Sewers Back Door']),
        create_region('Sanctuary', 'Inside', ['Sanctuary'], ['Sanctuary Exit']),
        create_region('Agahnims Tower', 'Inside', ['Castle Tower - Room 03', 'Castle Tower - Dark Maze'], ['Agahnim 1', 'Agahnims Tower Exit']),
        create_region('Agahnim 1', 'Inside', ['Agahnim 1'], None),
        create_region('Old Man Cave', 'Inside', ['Old Man'], ['Old Man Cave Exit (East)', 'Old Man Cave Exit (West)']),
        create_region('Old Man House', 'Inside', None, ['Old Man House Exit (Bottom)', 'Old Man House Front to Back']),
        create_region('Old Man House Back', 'Inside', None, ['Old Man House Exit (Top)', 'Old Man House Back to Front']),
        create_region('Death Mountain', 'Light', None, ['Old Man Cave (East)', 'Old Man House (Bottom)', 'Old Man House (Top)', 'Death Mountain Return Cave (East)', 'Spectacle Rock Cave', 'Spectacle Rock Cave Peak', 'Spectacle Rock Cave (Bottom)', 'Broken Bridge (West)', 'Death Mountain Teleporter']),
        create_region('Death Mountain Return Cave', 'Inside', None, ['Death Mountain Return Cave Exit (West)', 'Death Mountain Return Cave Exit (East)']),
        create_region('Death Mountain Return Ledge', 'Light', None, ['Death Mountain Return Ledge Drop', 'Death Mountain Return Cave (West)']),
        create_region('Spectacle Rock Cave (Top)', 'Inside', ['Spectacle Rock Cave'], ['Spectacle Rock Cave Drop', 'Spectacle Rock Cave Exit (Top)']),
        create_region('Spectacle Rock Cave (Bottom)', 'Inside', None, ['Spectacle Rock Cave Exit']),
        create_region('Spectacle Rock Cave (Peak)', 'Inside', None, ['Spectacle Rock Cave Peak Drop', 'Spectacle Rock Cave Exit (Peak)']),
        create_region('East Death Mountain (Bottom)', 'Light', None, ['Broken Bridge (East)', 'Paradox Cave (Bottom)', 'Paradox Cave (Middle)', 'East Death Mountain Teleporter', 'Hookshot Fairy', 'Fairy Ascension Rocks', 'Spiral Cave (Bottom)']),
        create_region('Hookshot Fairy', 'Inside'),
        create_region('Paradox Cave Front', 'Inside', None, ['Paradox Cave Push Block Reverse', 'Paradox Cave Exit (Bottom)']),
        create_region('Paradox Cave Chest Area', 'Inside', ['Paradox Cave Lower - Far Left',
                                                  'Paradox Cave Lower - Left',
                                                  'Paradox Cave Lower - Right',
                                                  'Paradox Cave Lower - Far Right',
                                                  'Paradox Cave Lower - Middle',
                                                  'Paradox Cave Upper - Left',
                                                  'Paradox Cave Upper - Right'],
                      ['Paradox Cave Push Block', 'Paradox Cave Bomb Jump']),
        create_region('Paradox Cave', 'Inside', None, ['Paradox Cave Exit (Middle)', 'Paradox Cave Exit (Top)', 'Paradox Cave Drop']),
        create_region('East Death Mountain (Top)', 'Light', None, ['Paradox Cave (Top)', 'Death Mountain (Top)', 'Spiral Cave Ledge Access', 'East Death Mountain Drop', 'Turtle Rock Teleporter', 'Fairy Ascension Ledge']),
        create_region('Spiral Cave Ledge', 'Light', None, ['Spiral Cave', 'Spiral Cave Ledge Drop']),
        create_region('Spiral Cave (Top)', 'Inside', ['Spiral Cave'], ['Spiral Cave (top to bottom)', 'Spiral Cave Exit (Top)']),
        create_region('Spiral Cave (Bottom)', 'Inside', None, ['Spiral Cave Exit']),
        create_region('Fairy Ascension Plateau', 'Light', None, ['Fairy Ascension Drop', 'Fairy Ascension Cave (Bottom)']),
        create_region('Fairy Ascension Cave', 'Inside', None, ['Fairy Ascension Cave Exit (Top)', 'Fairy Ascension Cave Exit (Bottom)']),
        create_region('Fairy Ascension Ledge', 'Light', None, ['Fairy Ascension Ledge Drop', 'Fairy Ascension Cave (Top)']),
        create_region('Death Mountain (Top)', 'Light', ['Ether Tablet'], ['East Death Mountain (Top)', 'Tower of Hera', 'Death Mountain Drop']),
        create_region('Spectacle Rock', 'Light', ['Spectacle Rock'], ['Spectacle Rock Drop']),
        create_region('Tower of Hera (Bottom)', 'Inside', ['Tower of Hera - Basement Cage', 'Tower of Hera - Map Chest'], ['Tower of Hera Small Key Door', 'Tower of Hera Big Key Door', 'Tower of Hera Exit']),
        create_region('Tower of Hera (Basement)', 'Inside', ['Tower of Hera - Big Key Chest']),
        create_region('Tower of Hera (Top)', 'Inside', ['Tower of Hera - Compass Chest', 'Tower of Hera - Big Chest', 'Tower of Hera - Moldorm', 'Tower of Hera - Prize']),

        create_region('East Dark World', 'Dark', ['Pyramid', 'Catfish'], ['Pyramid Fairy', 'South Dark World Bridge', 'West Dark World Gap', 'Palace of Darkness', 'Dark Lake Hylia Drop (East)', 'Dark Lake Hylia Teleporter',
                                                                  'Hyrule Castle Ledge Mirror Spot', 'Dark Lake Hylia Fairy', 'Palace of Darkness Hint', 'East Dark World Hint', 'Dark World Potion Shop', 'Pyramid Hole']),
        create_region('Palace of Darkness Hint', 'Inside'),
        create_region('East Dark World Hint', 'Inside'),
        create_region('South Dark World', 'Dark', ['Stumpy', 'Digging Game', 'Bombos Tablet'], ['Dark Lake Hylia Drop (South)', 'Hype Cave', 'Swamp Palace', 'Village of Outcasts Heavy Rock',
                                                                                        'Maze Race Mirror Spot', 'Cave 45 Mirror Spot', 'East Dark World Bridge', 'Big Bomb Shop', 'Archery Game', 'Bonk Fairy (Dark)', 'Dark Lake Hylia Shop']),
        create_region('Big Bomb Shop', 'Inside'),
        create_region('Archery Game', 'Inside'),
        create_region('Dark Lake Hylia', 'Dark', None, ['Lake Hylia Island Mirror Spot', 'East Dark World Pier', 'Dark Lake Hylia Ledge']),
        create_region('Dark Lake Hylia Central Island', 'Dark', None, ['Ice Palace', 'Lake Hylia Central Island Mirror Spot']),
        create_region('Dark Lake Hylia Ledge', 'Dark', None, ['Dark Lake Hylia Ledge Drop', 'Dark Lake Hylia Ledge Fairy', 'Dark Lake Hylia Ledge Hint', 'Dark Lake Hylia Ledge Spike Cave']),
        create_region('Dark Lake Hylia Ledge Hint', 'Inside'),
        create_region('Dark Lake Hylia Ledge Spike Cave', 'Inside'),
        create_region('Hype Cave', 'Inside', ['Hype Cave - Top', 'Hype Cave - Middle Right', 'Hype Cave - Middle Left',
                                    'Hype Cave - Bottom', 'Hype Cave - Generous Guy']),
        create_region('West Dark World', 'Dark', None, ['Village of Outcasts Drop', 'East Dark World River Pier', 'Brewery', 'C-Shaped House', 'Chest Game', 'Thieves Town', 'Graveyard Ledge Mirror Spot', 'Bumper Cave (Bottom)', 'Skull Woods Forest',
                                                'Bat Cave Drop Ledge Mirror Spot', 'Dark World Hammer Peg Cave', 'Red Shield Shop', 'Dark Sanctuary Hint', 'Fortune Teller (Dark)', 'Dark World Shop', 'Dark World Lumberjack Shop']),
        create_region('Fortune Teller (Dark)', 'Inside'),
        create_region('Dark World Shop', 'Inside'),
        create_region('Dark World Hammer Peg Cave', 'Inside', ['Peg Cave']),
        create_region('Pyramid Fairy', 'Inside', ['Pyramid Fairy - Left', 'Pyramid Fairy - Right']),
        create_region('Brewery', 'Inside', ['Brewery']),
        create_region('C-Shaped House', 'Inside', ['C-Shaped House']),
        create_region('Chest Game', 'Inside', ['Chest Game']),
        create_region('Red Shield Shop', 'Inside'),
        create_region('Dark Sanctuary Hint', 'Inside'),
        create_region('Bumper Cave', 'Inside', None, ['Bumper Cave Exit (Bottom)', 'Bumper Cave Exit (Top)']),
        create_region('Bumper Cave Ledge', 'Dark', ['Bumper Cave Ledge'], ['Bumper Cave Ledge Drop', 'Bumper Cave (Top)', 'Bumper Cave Ledge Mirror Spot']),
        create_region('Skull Woods Forest', 'Dark', None, ['Skull Woods First Section Hole (East)', 'Skull Woods First Section Hole (West)', 'Skull Woods First Section Hole (North)', 'Skull Woods First Section Door',
                                                   'Skull Woods Second Section Door (East)']),
        create_region('Skull Woods Forest (West)', 'Dark', None, ['Skull Woods Second Section Hole', 'Skull Woods Second Section Door (West)', 'Skull Woods Final Section']),
        create_region('Dark Desert', 'Dark', None, ['Misery Mire', 'Mire Shed', 'Desert Ledge (Northeast) Mirror Spot', 'Desert Ledge Mirror Spot', 'Desert Palace Stairs Mirror Spot', 'Desert Palace Entrance (North) Mirror Spot',
                                            'Dark Desert Hint', 'Dark Desert Fairy']),
        create_region('Mire Shed', 'Inside', ['Mire Shed - Left', 'Mire Shed - Right']),
        create_region('Dark Desert Hint', 'Inside'),
        create_region('Dark Death Mountain (West Bottom)', 'Dark', None, ['Spike Cave', 'Spectacle Rock Mirror Spot', 'Dark Death Mountain Fairy']),
        create_region('Dark Death Mountain (Top)', 'Dark', None, ['Dark Death Mountain Drop (East)', 'Dark Death Mountain Drop (West)', 'Ganons Tower', 'Superbunny Cave (Top)', 'Hookshot Cave',
                                                          'East Death Mountain (Top) Mirror Spot', 'Turtle Rock']),
        create_region('Dark Death Mountain Ledge', 'Dark', None, ['Dark Death Mountain Ledge (East)', 'Dark Death Mountain Ledge (West)', 'Mimic Cave Mirror Spot', 'Spiral Cave Mirror Spot']),
        create_region('Dark Death Mountain Isolated Ledge', 'Dark', None, ['Isolated Ledge Mirror Spot', 'Turtle Rock Isolated Ledge Entrance']),
        create_region('Dark Death Mountain (East Bottom)', 'Dark', None, ['Superbunny Cave (Bottom)', 'Cave Shop (Dark Death Mountain)', 'Fairy Ascension Mirror Spot']),
        create_region('Superbunny Cave', 'Inside', ['Superbunny Cave - Top', 'Superbunny Cave - Bottom'],
                      ['Superbunny Cave Exit (Top)', 'Superbunny Cave Exit (Bottom)']),
        create_region('Spike Cave', 'Inside', ['Spike Cave']),
        create_region('Hookshot Cave', 'Inside', ['Hookshot Cave - Top Right', 'Hookshot Cave - Top Left', 'Hookshot Cave - Bottom Right', 'Hookshot Cave - Bottom Left'],
                      ['Hookshot Cave Exit (South)', 'Hookshot Cave Exit (North)']),
        create_region('Death Mountain Floating Island (Dark World)', 'Dark', None, ['Floating Island Drop', 'Hookshot Cave Back Entrance', 'Floating Island Mirror Spot']),
        create_region('Death Mountain Floating Island (Light World)', 'Light', ['Floating Island']),
        create_region('Turtle Rock (Top)', 'Dark', None, ['Turtle Rock Drop']),
        create_region('Mimic Cave Ledge', 'Light', None, ['Mimic Cave']),
        create_region('Mimic Cave', 'Inside', ['Mimic Cave']),

        create_region('Swamp Palace (Entrance)', 'Inside', None, ['Swamp Palace Moat', 'Swamp Palace Exit']),
        create_region('Swamp Palace (First Room)', 'Inside', ['Swamp Palace - Entrance'], ['Swamp Palace Small Key Door']),
        create_region('Swamp Palace (Starting Area)', 'Inside', ['Swamp Palace - Map Chest'], ['Swamp Palace (Center)']),
        create_region('Swamp Palace (Center)', 'Inside', ['Swamp Palace - Big Chest', 'Swamp Palace - Compass Chest',
                                                'Swamp Palace - Big Key Chest', 'Swamp Palace - West Chest'], ['Swamp Palace (North)']),
        create_region('Swamp Palace (North)', 'Inside', ['Swamp Palace - Flooded Room - Left', 'Swamp Palace - Flooded Room - Right',
                                               'Swamp Palace - Waterfall Room', 'Swamp Palace - Arrghus', 'Swamp Palace - Prize']),
        create_region('Thieves Town (Entrance)', 'Inside', ['Thieves\' Town - Big Key Chest',
                                                  'Thieves\' Town - Map Chest',
                                                  'Thieves\' Town - Compass Chest',
                                                  'Thieves\' Town - Ambush Chest'], ['Thieves Town Big Key Door', 'Thieves Town Exit']),
        create_region('Thieves Town (Deep)', 'Inside', ['Thieves\' Town - Attic',
                                              'Thieves\' Town - Big Chest',
                                              'Thieves\' Town - Blind\'s Cell'], ['Blind Fight']),
        create_region('Blind Fight', 'Inside', ['Thieves Town - Blind', 'Thieves Town - Prize']),
        create_region('Skull Woods First Section', 'Inside', ['Skull Woods - Map Chest'], ['Skull Woods First Section Exit', 'Skull Woods First Section Bomb Jump', 'Skull Woods First Section South Door', 'Skull Woods First Section West Door']),
        create_region('Skull Woods First Section (Right)', 'Inside', ['Skull Woods - Pinball Room'], ['Skull Woods First Section (Right) North Door']),
        create_region('Skull Woods First Section (Left)', 'Inside', ['Skull Woods - Compass Chest', 'Skull Woods - Pot Prison'], ['Skull Woods First Section (Left) Door to Exit', 'Skull Woods First Section (Left) Door to Right']),
        create_region('Skull Woods First Section (Top)', 'Inside', ['Skull Woods - Big Chest'], ['Skull Woods First Section (Top) One-Way Path']),
        create_region('Skull Woods Second Section (Drop)', 'Inside', None, ['Skull Woods Second Section (Drop)']),
        create_region('Skull Woods Second Section', 'Inside', ['Skull Woods - Big Key Chest'], ['Skull Woods Second Section Exit (East)', 'Skull Woods Second Section Exit (West)']),
        create_region('Skull Woods Final Section (Entrance)', 'Inside', ['Skull Woods - Bridge Room'], ['Skull Woods Torch Room', 'Skull Woods Final Section Exit']),
        create_region('Skull Woods Final Section (Mothula)', 'Inside', ['Skull Woods - Mothula', 'Skull Woods - Prize']),
        create_region('Ice Palace (Entrance)', 'Inside', None, ['Ice Palace Entrance Room', 'Ice Palace Exit']),
        create_region('Ice Palace (Main)', 'Inside', ['Ice Palace - Compass Chest', 'Ice Palace - Freezor Chest',
                                            'Ice Palace - Big Chest', 'Ice Palace - Iced T Room'], ['Ice Palace (East)', 'Ice Palace (Kholdstare)']),
        create_region('Ice Palace (East)', 'Inside', ['Ice Palace - Spike Room'], ['Ice Palace (East Top)']),
        create_region('Ice Palace (East Top)', 'Inside', ['Ice Palace - Big Key Chest', 'Ice Palace - Map Chest']),
        create_region('Ice Palace (Kholdstare)', 'Inside', ['Ice Palace - Kholdstare', 'Ice Palace - Prize']),
        create_region('Misery Mire (Entrance)', 'Inside', None, ['Misery Mire Entrance Gap', 'Misery Mire Exit']),
        create_region('Misery Mire (Main)', 'Inside', ['Misery Mire - Big Chest', 'Misery Mire - Map Chest', 'Misery Mire - Main Lobby',
                                             'Misery Mire - Bridge Chest', 'Misery Mire - Spike Chest'], ['Misery Mire (West)', 'Misery Mire Big Key Door']),
        create_region('Misery Mire (West)', 'Inside', ['Misery Mire - Compass Chest', 'Misery Mire - Big Key Chest']),
        create_region('Misery Mire (Final Area)', 'Inside', None, ['Misery Mire (Vitreous)']),
        create_region('Misery Mire (Vitreous)', 'Inside', ['Misery Mire - Vitreous', 'Misery Mire - Prize']),
        create_region('Turtle Rock (Entrance)', 'Inside', None, ['Turtle Rock Entrance Gap', 'Turtle Rock Exit (Front)']),
        create_region('Turtle Rock (First Section)', 'Inside', ['Turtle Rock - Compass Chest', 'Turtle Rock - Roller Room - Left',
                                                      'Turtle Rock - Roller Room - Right'], ['Turtle Rock Pokey Room', 'Turtle Rock Entrance Gap Reverse']),
        create_region('Turtle Rock (Chain Chomp Room)', 'Inside', ['Turtle Rock - Chain Chomps'], ['Turtle Rock (Chain Chomp Room) (North)', 'Turtle Rock (Chain Chomp Room) (South)']),
        create_region('Turtle Rock (Second Section)', 'Inside', ['Turtle Rock - Big Key Chest'], ['Turtle Rock Ledge Exit (West)', 'Turtle Rock Chain Chomp Staircase', 'Turtle Rock Big Key Door']),
        create_region('Turtle Rock (Big Chest)', 'Inside', ['Turtle Rock - Big Chest'], ['Turtle Rock (Big Chest) (North)', 'Turtle Rock Ledge Exit (East)']),
        create_region('Turtle Rock (Crystaroller Room)', 'Inside', ['Turtle Rock - Crystaroller Room'], ['Turtle Rock Dark Room Staircase', 'Turtle Rock Big Key Door Reverse']),
        create_region('Turtle Rock (Dark Room)', 'Inside', None, ['Turtle Rock (Dark Room) (North)', 'Turtle Rock (Dark Room) (South)']),
        create_region('Turtle Rock (Eye Bridge)', 'Inside', ['Turtle Rock - Eye Bridge - Bottom Left', 'Turtle Rock - Eye Bridge - Bottom Right',
                                                   'Turtle Rock - Eye Bridge - Top Left', 'Turtle Rock - Eye Bridge - Top Right'],
                      ['Turtle Rock Dark Room (South)', 'Inside', 'Turtle Rock (Trinexx)', 'Turtle Rock Isolated Ledge Exit']),
        create_region('Turtle Rock (Trinexx)', 'Inside', ['Turtle Rock - Trinexx', 'Turtle Rock - Prize']),
        create_region('Palace of Darkness (Entrance)', 'Inside', ['Palace of Darkness - Shooter Room'], ['Palace of Darkness Bridge Room', 'Palace of Darkness Bonk Wall', 'Palace of Darkness Exit']),
        create_region('Palace of Darkness (Center)', 'Inside', ['Palace of Darkness - The Arena - Bridge', 'Palace of Darkness - Stalfos Basement'],
                      ['Palace of Darkness Big Key Chest Staircase', 'Palace of Darkness (North)', 'Palace of Darkness Big Key Door']),
        create_region('Palace of Darkness (Big Key Chest)', 'Inside', ['Palace of Darkness - Big Key Chest']),
        create_region('Palace of Darkness (Bonk Section)', 'Inside', ['Palace of Darkness - The Arena - Ledge', 'Palace of Darkness - Map Chest'], ['Palace of Darkness Hammer Peg Drop']),
        create_region('Palace of Darkness (North)', 'Inside', ['Palace of Darkness - Compass Chest', 'Palace of Darkness - Dark Basement - Left', 'Palace of Darkness - Dark Basement - Right'],
                      ['Palace of Darkness Spike Statue Room Door', 'Palace of Darkness Maze Door']),
        create_region('Palace of Darkness (Maze)', 'Inside', ['Palace of Darkness - Dark Maze - Top', 'Palace of Darkness - Dark Maze - Bottom', 'Palace of Darkness - Big Chest']),
        create_region('Palace of Darkness (Harmless Hellway)', 'Inside', ['Palace of Darkness - Harmless Hellway']),
        create_region('Palace of Darkness (Final Section)', 'Inside', ['Palace of Darkness - Helmasaur', 'Palace of Darkness - Prize']),
        create_region('Ganons Tower (Entrance)', 'Inside', ['Ganons Tower - Bob\'s Torch', 'Ganons Tower - Hope Room - Left', 'Ganons Tower - Hope Room - Right'],
                      ['Ganons Tower (Tile Room)', 'Ganons Tower (Hookshot Room)', 'Ganons Tower Big Key Door', 'Ganons Tower Exit']),
        create_region('Ganons Tower (Tile Room)', 'Inside', ['Ganons Tower - Tile Room'], ['Ganons Tower (Tile Room) Key Door']),
        create_region('Ganons Tower (Compass Room)', 'Inside', ['Ganons Tower - Compass Room - Top Left', 'Ganons Tower - Compass Room - Top Right',
                                                      'Ganons Tower - Compass Room - Bottom Left', 'Ganons Tower - Compass Room - Bottom Right'],
                      ['Ganons Tower (Bottom) (East)']),
        create_region('Ganons Tower (Hookshot Room)', 'Inside', ['Ganons Tower - DMs Room - Top Left', 'Ganons Tower - DMs Room - Top Right',
                                                       'Ganons Tower - DMs Room - Bottom Left', 'Ganons Tower - DMs Room - Bottom Right'],
                      ['Ganons Tower (Map Room)', 'Ganons Tower (Double Switch Room)']),
        create_region('Ganons Tower (Map Room)', 'Inside', ['Ganons Tower - Map Chest']),
        create_region('Ganons Tower (Firesnake Room)', 'Inside', ['Ganons Tower - Firesnake Room'], ['Ganons Tower (Firesnake Room)']),
        create_region('Ganons Tower (Teleport Room)', 'Inside', ['Ganons Tower - Randomizer Room - Top Left', 'Ganons Tower - Randomizer Room - Top Right',
                                                       'Ganons Tower - Randomizer Room - Bottom Left', 'Ganons Tower - Randomizer Room - Bottom Right'],
                      ['Ganons Tower (Bottom) (West)']),
        create_region('Ganons Tower (Bottom)', 'Inside', ['Ganons Tower - Bob\'s Chest', 'Ganons Tower - Big Chest', 'Ganons Tower - Big Key Room - Left',
                                                'Ganons Tower - Big Key Room - Right', 'Ganons Tower - Big Key Chest']),
        create_region('Ganons Tower (Top)', 'Inside', None, ['Ganons Tower Torch Rooms']),
        create_region('Ganons Tower (Before Moldorm)', 'Inside', ['Ganons Tower - Mini Helmasaur Room - Left', 'Ganons Tower - Mini Helmasaur Room - Right',
                                                        'Ganons Tower - Pre-Moldorm Chest'], ['Ganons Tower Moldorm Door']),
        create_region('Ganons Tower (Moldorm)', 'Inside', None, ['Ganons Tower Moldorm Gap']),
        create_region('Agahnim 2', 'Inside', ['Ganons Tower - Validation Chest', 'Agahnim 2'], None),
        create_region('Pyramid', 'Inside', ['Ganon'], ['Ganon Drop']),
        create_region('Bottom of Pyramid', 'Inside', None, ['Pyramid Exit']),
        create_region('Pyramid Ledge', 'Dark', None, ['Pyramid Entrance', 'Pyramid Drop'])
    ]

    world.intialize_regions()


def create_region(name, world='Inside', locations=None, exits=None):
    ret = Region(name)
    if locations is None:
        locations = []
    if exits is None:
        exits = []

    for exit in exits:
        ret.exits.append(Entrance(exit, ret))
    for location in locations:
        address, crystal, hint_text = location_table[location]
        ret.locations.append(Location(location, address, crystal, hint_text, ret))
    return ret


def mark_light_world_regions(world):
    # Note that in "inanity" shuffle this code may mark some dark world locations as being in light world. That is fine because this flag
    # is only used for bunny logic, and you start with a Moon pearl immediately availible in Insanity shuffle.

    # Exclude entrances that represent connections from the light world to the dark world
    excluded_entrances = set(['Top of Pyramid', 'Lake Hylia Central Island Teleporter', 'Dark Desert Teleporter', 'East Hyrule Teleporter', 'South Hyrule Teleporter', 'Kakariko Teleporter', 'Death Mountain Teleporter', 'East Death Mountain Teleporter', 'Turtle Rock Teleporter'])

    starting_regions = ['Links House', 'Cave 45 Ledge', 'Graveyard Ledge', 'Mimic Cave Ledge', 'Death Mountain Floating Island (Light World)', 'Desert Ledge', 'Desert Ledge (Northeast)', 'Lake Hylia Island', 'Spectacle Rock', 'Death Mountain Return Ledge', 'Hyrule Castle Ledge','Maze Race Ledge']
    queue = collections.deque([world.get_region(region) for region in starting_regions])
    seen = set(queue)
    while queue:
        current = queue.popleft()
        current.is_light_world = True
        for exit in current.exits:
            if exit.name in excluded_entrances:
                continue
            if exit.connected_region not in seen:
                seen.add(exit.connected_region)
                queue.append(exit.connected_region)


location_table = {'Mushroom': (0x180013, False, 'in the woods'),
                  'Bottle Merchant': (0x2EB18, False, 'with a merchant'),
                  'Flute Spot': (0x18014A, False, 'underground'),
                  'Sunken Treasure': (0x180145, False, 'underwater'),
                  'Purple Chest': (0x33D68, False, 'from a box'),
                  'Blind\'s Hideout - Top': (0xEB0F, False, 'in a basement'),
                  'Blind\'s Hideout - Left': (0xEB12, False, 'in a basement'),
                  'Blind\'s Hideout - Right': (0xEB15, False, 'in a basement'),
                  'Blind\'s Hideout - Far Left': (0xEB18, False, 'in a basement'),
                  'Blind\'s Hideout - Far Right': (0xEB1B, False, 'in a basement'),
                  'Link\'s Uncle': (0x2DF45, False, 'with your uncle'),
                  'Secret Passage': (0xE971, False, 'near your uncle'),
                  'King Zora': (0xEE1C3, False, 'at a high price'),
                  'Zora\'s Ledge': (0x180149, False, 'near Zora'),
                  'Waterfall Fairy - Left': (0xE9B0, False, 'near a fairy'),
                  'Waterfall Fairy - Right': (0xE9D1, False, 'near a fairy'),
                  'King\'s Tomb': (0xE97A, False, 'alone in a cave'),
                  'Floodgate Chest': (0xE98C, False, 'in the dam'),
                  'Link\'s House': (0xE9BC, False, 'in your home'),
                  'Kakariko Tavern': (0xE9CE, False, 'in the bar'),
                  'Chicken House': (0xE9E9, False, 'near poultry'),
                  'Aginah\'s Cave': (0xE9F2, False, 'with Aginah'),
                  'Sahasrahla\'s Hut - Left': (0xEA82, False, 'near the elder'),
                  'Sahasrahla\'s Hut - Middle': (0xEA85, False, 'near the elder'),
                  'Sahasrahla\'s Hut - Right': (0xEA88, False, 'near the elder'),
                  'Sahasrahla': (0x2F1FC, False, 'with the elder'),
                  'Kakariko Well - Top': (0xEA8E, False, 'in a well'),
                  'Kakariko Well - Left': (0xEA91, False, 'in a well'),
                  'Kakariko Well - Middle': (0xEA94, False, 'in a well'),
                  'Kakariko Well - Right': (0xEA97, False, 'in a well'),
                  'Kakariko Well - Bottom': (0xEA9A, False, 'in a well'),
                  'Blacksmith': (0x18002A, False, 'with the smith'),
                  'Magic Bat': (0x180015, False, 'with the bat'),
                  'Sick Kid': (0x339CF, False, 'with the ill'),
                  'Hobo': (0x33E7D, False, 'with the hobo'),
                  'Lost Woods Hideout': (0x180000, False, 'near a thief'),
                  'Lumberjack Tree': (0x180001, False, 'in a hole'),
                  'Cave 45': (0x180003, False, 'alone in a cave'),
                  'Graveyard Cave': (0x180004, False, 'alone in a cave'),
                  'Checkerboard Cave': (0x180005, False, 'alone in a cave'),
                  'Mini Moldorm Cave - Far Left': (0xEB42, False, 'near Moldorms'),
                  'Mini Moldorm Cave - Left': (0xEB45, False, 'near Moldorms'),
                  'Mini Moldorm Cave - Right': (0xEB48, False, 'near Moldorms'),
                  'Mini Moldorm Cave - Far Right': (0xEB4B, False, 'near Moldorms'),
                  'Mini Moldorm Cave - Generous Guy': (0x180010, False, 'near Moldorms'),
                  'Ice Rod Cave': (0xEB4E, False, 'on ice'),
                  'Bonk Rock Cave': (0xEB3F, False, 'alone in a cave'),
                  'Library': (0x180012, False, 'near books'),
                  'Potion Shop': (0x180014, False, 'near potions'),
                  'Lake Hylia Island': (0x180144, False, 'on an island'),
                  'Maze Race': (0x180142, False, 'at the race'),
                  'Desert Ledge': (0x180143, False, 'in the desert'),
                  'Desert Palace - Big Chest': (0xE98F, False, 'in Desert Palace'),
                  'Desert Palace - Torch': (0x180160, False, 'in Desert Palace'),
                  'Desert Palace - Map Chest': (0xE9B6, False, 'in Desert Palace'),
                  'Desert Palace - Compass Chest': (0xE9CB, False, 'in Desert Palace'),
                  'Desert Palace - Big Key Chest': (0xE9C2, False, 'in Desert Palace'),
                  'Desert Palace - Lanmolas': (0x180151, False, 'with Lanmolas'),
                  'Eastern Palace - Compass Chest': (0xE977, False, 'in Eastern Palace'),
                  'Eastern Palace - Big Chest': (0xE97D, False, 'in Eastern Palace'),
                  'Eastern Palace - Cannonball Chest': (0xE9B3, False, 'in Eastern Palace'),
                  'Eastern Palace - Big Key Chest': (0xE9B9, False, 'in Eastern Palace'),
                  'Eastern Palace - Map Chest': (0xE9F5, False, 'in Eastern Palace'),
                  'Eastern Palace - Armos Knights': (0x180150, False, 'with the Armos'),
                  'Master Sword Pedestal': (0x289B0, False, 'at the pedestal'),
                  'Hyrule Castle - Boomerang Chest': (0xE974, False, 'in Hyrule Castle'),
                  'Hyrule Castle - Map Chest': (0xEB0C, False, 'in Hyrule Castle'),
                  'Hyrule Castle - Zelda\'s Chest': (0xEB09, False, 'in Hyrule Castle'),
                  'Sewers - Dark Cross': (0xE96E, False, 'in the sewers'),
                  'Sewers - Secret Room - Left': (0xEB5D, False, 'in the sewers'),
                  'Sewers - Secret Room - Middle': (0xEB60, False, 'in the sewers'),
                  'Sewers - Secret Room - Right': (0xEB63, False, 'in the sewers'),
                  'Sanctuary': (0xEA79, False, 'in Sanctuary'),
                  'Castle Tower - Room 03': (0xEAB5, False, 'in Hyrule Castle'),
                  'Castle Tower - Dark Maze': (0xEAB2, False, 'in Hyrule Castle'),
                  'Old Man': (0xF69FA, False, 'with the old man'),
                  'Spectacle Rock Cave': (0x180002, False, 'alone in a cave'),
                  'Paradox Cave Lower - Far Left': (0xEB2A, False, 'in paradox cave'),
                  'Paradox Cave Lower - Left': (0xEB2D, False, 'in paradox cave'),
                  'Paradox Cave Lower - Right': (0xEB30, False, 'in paradox cave'),
                  'Paradox Cave Lower - Far Right': (0xEB33, False, 'in paradox cave'),
                  'Paradox Cave Lower - Middle': (0xEB36, False, 'in paradox cave'),
                  'Paradox Cave Upper - Left': (0xEB39, False, 'in paradox cave'),
                  'Paradox Cave Upper - Right': (0xEB3C, False, 'in paradox cave'),
                  'Spiral Cave': (0xE9BF, False, 'in spiral cave'),
                  'Ether Tablet': (0x180016, False, 'at a monument'),
                  'Spectacle Rock': (0x180140, False, 'atop a rock'),
                  'Tower of Hera - Basement Cage': (0x180162, False, 'in Tower of Hera'),
                  'Tower of Hera - Map Chest': (0xE9AD, False, 'in Tower of Hera'),
                  'Tower of Hera - Big Key Chest': (0xE9E6, False, 'in Tower of Hera'),
                  'Tower of Hera - Compass Chest': (0xE9FB, False, 'in Tower of Hera'),
                  'Tower of Hera - Big Chest': (0xE9F8, False, 'in Tower of Hera'),
                  'Tower of Hera - Moldorm': (0x180152, False, 'with Moldorm'),
                  'Pyramid': (0x180147, False, 'on the pyramid'),
                  'Catfish': (0xEE185, False, 'with a fish'),
                  'Stumpy': (0x330C7, False, 'with tree boy'),
                  'Digging Game': (0x180148, False, 'underground'),
                  'Bombos Tablet': (0x180017, False, 'at a monument'),
                  'Hype Cave - Top': (0xEB1E, False, 'near batman'),
                  'Hype Cave - Middle Right': (0xEB21, False, 'near batman'),
                  'Hype Cave - Middle Left': (0xEB24, False, 'near batman'),
                  'Hype Cave - Bottom': (0xEB27, False, 'near batman'),
                  'Hype Cave - Generous Guy': (0x180011, False, 'with batman'),
                  'Peg Cave': (0x180006, False, 'alone in a cave'),
                  'Pyramid Fairy - Left': (0xE980, False, 'near a fairy'),
                  'Pyramid Fairy - Right': (0xE983, False, 'near a fairy'),
                  'Brewery': (0xE9EC, False, 'alone in a home'),
                  'C-Shaped House': (0xE9EF, False, 'alone in a home'),
                  'Chest Game': (0xEDA8, False, 'as a prize'),
                  'Bumper Cave Ledge': (0x180146, False, 'on a ledge'),
                  'Mire Shed - Left': (0xEA73, False, 'near a spark'),
                  'Mire Shed - Right': (0xEA76, False, 'near a spark'),
                  'Superbunny Cave - Top': (0xEA7C, False, 'in a connection'),
                  'Superbunny Cave - Bottom': (0xEA7F, False, 'in a connection'),
                  'Spike Cave': (0xEA8B, False, 'beyond spikes'),
                  'Hookshot Cave - Top Right': (0xEB51, False, 'across pits'),
                  'Hookshot Cave - Top Left': (0xEB54, False, 'across pits'),
                  'Hookshot Cave - Bottom Right': (0xEB5A, False, 'across pits'),
                  'Hookshot Cave - Bottom Left': (0xEB57, False, 'across pits'),
                  'Floating Island': (0x180141, False, 'on an island'),
                  'Mimic Cave': (0xE9C5, False, 'beyond Goriyas'),
                  'Swamp Palace - Entrance': (0xEA9D, False, 'in Swamp Palace'),
                  'Swamp Palace - Map Chest': (0xE986, False, 'in Swamp Palace'),
                  'Swamp Palace - Big Chest': (0xE989, False, 'in Swamp Palace'),
                  'Swamp Palace - Compass Chest': (0xEAA0, False, 'in Swamp Palace'),
                  'Swamp Palace - Big Key Chest': (0xEAA6, False, 'in Swamp Palace'),
                  'Swamp Palace - West Chest': (0xEAA3, False, 'in Swamp Palace'),
                  'Swamp Palace - Flooded Room - Left': (0xEAA9, False, 'in Swamp Palace'),
                  'Swamp Palace - Flooded Room - Right': (0xEAAC, False, 'in Swamp Palace'),
                  'Swamp Palace - Waterfall Room': (0xEAAF, False, 'in Swamp Palace'),
                  'Swamp Palace - Arrghus': (0x180154, False, 'with Arrghus'),
                  'Thieves\' Town - Big Key Chest': (0xEA04, False, 'in Thieves\' Town'),
                  'Thieves\' Town - Map Chest': (0xEA01, False, 'in Thieves\' Town'),
                  'Thieves\' Town - Compass Chest': (0xEA07, False, 'in Thieves\' Town'),
                  'Thieves\' Town - Ambush Chest': (0xEA0A, False, 'in Thieves\' Town'),
                  'Thieves\' Town - Attic': (0xEA0D, False, 'in Thieves\' Town'),
                  'Thieves\' Town - Big Chest': (0xEA10, False, 'in Thieves\' Town'),
                  'Thieves\' Town - Blind\'s Cell': (0xEA13, False, 'in Thieves\' Town'),
                  'Thieves Town - Blind': (0x180156, False, 'with Blind'),
                  'Skull Woods - Compass Chest': (0xE992, False, 'in Skull Woods'),
                  'Skull Woods - Map Chest': (0xE99B, False, 'in Skull Woods'),
                  'Skull Woods - Big Chest': (0xE998, False, 'in Skull Woods'),
                  'Skull Woods - Pot Prison': (0xE9A1, False, 'in Skull Woods'),
                  'Skull Woods - Pinball Room': (0xE9C8, False, 'in Skull Woods'),
                  'Skull Woods - Big Key Chest': (0xE99E, False, 'in Skull Woods'),
                  'Skull Woods - Bridge Room': (0xE9FE, False, 'near Mothula'),
                  'Skull Woods - Mothula': (0x180155, False, 'with Mothula'),
                  'Ice Palace - Compass Chest': (0xE9D4, False, 'in Ice Palace'),
                  'Ice Palace - Freezor Chest': (0xE995, False, 'in Ice Palace'),
                  'Ice Palace - Big Chest': (0xE9AA, False, 'in Ice Palace'),
                  'Ice Palace - Iced T Room': (0xE9E3, False, 'in Ice Palace'),
                  'Ice Palace - Spike Room': (0xE9E0, False, 'in Ice Palace'),
                  'Ice Palace - Big Key Chest': (0xE9A4, False, 'in Ice Palace'),
                  'Ice Palace - Map Chest': (0xE9DD, False, 'in Ice Palace'),
                  'Ice Palace - Kholdstare': (0x180157, False, 'with Kholdstare'),
                  'Misery Mire - Big Chest': (0xEA67, False, 'in Misery Mire'),
                  'Misery Mire - Map Chest': (0xEA6A, False, 'in Misery Mire'),
                  'Misery Mire - Main Lobby': (0xEA5E, False, 'in Misery Mire'),
                  'Misery Mire - Bridge Chest': (0xEA61, False, 'in Misery Mire'),
                  'Misery Mire - Spike Chest': (0xE9DA, False, 'in Misery Mire'),
                  'Misery Mire - Compass Chest': (0xEA64, False, 'in Misery Mire'),
                  'Misery Mire - Big Key Chest': (0xEA6D, False, 'in Misery Mire'),
                  'Misery Mire - Vitreous': (0x180158, False, 'with Vitreous'),
                  'Turtle Rock - Compass Chest': (0xEA22, False, 'in Turtle Rock'),
                  'Turtle Rock - Roller Room - Left': (0xEA1C, False, 'in Turtle Rock'),
                  'Turtle Rock - Roller Room - Right': (0xEA1F, False, 'in Turtle Rock'),
                  'Turtle Rock - Chain Chomps': (0xEA16, False, 'in Turtle Rock'),
                  'Turtle Rock - Big Key Chest': (0xEA25, False, 'in Turtle Rock'),
                  'Turtle Rock - Big Chest': (0xEA19, False, 'in Turtle Rock'),
                  'Turtle Rock - Crystaroller Room': (0xEA34, False, 'in Turtle Rock'),
                  'Turtle Rock - Eye Bridge - Bottom Left': (0xEA31, False, 'in Turtle Rock'),
                  'Turtle Rock - Eye Bridge - Bottom Right': (0xEA2E, False, 'in Turtle Rock'),
                  'Turtle Rock - Eye Bridge - Top Left': (0xEA2B, False, 'in Turtle Rock'),
                  'Turtle Rock - Eye Bridge - Top Right': (0xEA28, False, 'in Turtle Rock'),
                  'Turtle Rock - Trinexx': (0x180159, False, 'with Trinexx'),
                  'Palace of Darkness - Shooter Room': (0xEA5B, False, 'in Palace of Darkness'),
                  'Palace of Darkness - The Arena - Bridge': (0xEA3D, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Stalfos Basement': (0xEA49, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Big Key Chest': (0xEA37, False, 'in Palace of Darkness'),
                  'Palace of Darkness - The Arena - Ledge': (0xEA3A, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Map Chest': (0xEA52, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Compass Chest': (0xEA43, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Dark Basement - Left': (0xEA4C, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Dark Basement - Right': (0xEA4F, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Dark Maze - Top': (0xEA55, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Dark Maze - Bottom': (0xEA58, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Big Chest': (0xEA40, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Harmless Hellway': (0xEA46, False, 'in Palace of Darkness'),
                  'Palace of Darkness - Helmasaur': (0x180153, False, 'with Helmasaur King'),
                  'Ganons Tower - Bob\'s Torch': (0x180161, False, 'on my torch'),
                  'Ganons Tower - Hope Room - Left': (0xEAD9, False, 'in My Tower'),
                  'Ganons Tower - Hope Room - Right': (0xEADC, False, 'in My Tower'),
                  'Ganons Tower - Tile Room': (0xEAE2, False, 'with my tiles'),
                  'Ganons Tower - Compass Room - Top Left': (0xEAE5, False, 'in My Tower'),
                  'Ganons Tower - Compass Room - Top Right': (0xEAE8, False, 'in My Tower'),
                  'Ganons Tower - Compass Room - Bottom Left': (0xEAEB, False, 'in My Tower'),
                  'Ganons Tower - Compass Room - Bottom Right': (0xEAEE, False, 'in My Tower'),
                  'Ganons Tower - DMs Room - Top Left': (0xEAB8, False, 'in My Tower'),
                  'Ganons Tower - DMs Room - Top Right': (0xEABB, False, 'in My Tower'),
                  'Ganons Tower - DMs Room - Bottom Left': (0xEABE, False, 'in My Tower'),
                  'Ganons Tower - DMs Room - Bottom Right': (0xEAC1, False, 'in My Tower'),
                  'Ganons Tower - Map Chest': (0xEAD3, False, 'in My Tower'),
                  'Ganons Tower - Firesnake Room': (0xEAD0, False, 'in My Tower'),
                  'Ganons Tower - Randomizer Room - Top Left': (0xEAC4, False, 'in My Tower'),
                  'Ganons Tower - Randomizer Room - Top Right': (0xEAC7, False, 'in My Tower'),
                  'Ganons Tower - Randomizer Room - Bottom Left': (0xEACA, False, 'in My Tower'),
                  'Ganons Tower - Randomizer Room - Bottom Right': (0xEACD, False, 'in My Tower'),
                  'Ganons Tower - Bob\'s Chest': (0xEADF, False, 'in My Tower'),
                  'Ganons Tower - Big Chest': (0xEAD6, False, 'in my big chest'),
                  'Ganons Tower - Big Key Room - Left': (0xEAF4, False, 'beyond my Armos'),
                  'Ganons Tower - Big Key Room - Right': (0xEAF7, False, 'beyond my Armos'),
                  'Ganons Tower - Big Key Chest': (0xEAF1, False, 'beyond my Armos'),
                  'Ganons Tower - Mini Helmasaur Room - Left': (0xEAFD, False, 'atop My Tower'),
                  'Ganons Tower - Mini Helmasaur Room - Right': (0xEB00, False, 'atop My Tower'),
                  'Ganons Tower - Pre-Moldorm Chest': (0xEB03, False, 'atop My Tower'),
                  'Ganons Tower - Validation Chest': (0xEB06, False, 'atop My Tower'),
                  'Ganon': (None, False, 'from me'),
                  'Agahnim 1': (None, False, 'from my wizardry form'),
                  'Agahnim 2': (None, False, 'from my wizardry form'),
                  'Eastern Palace - Prize': ([0x1209D, 0x53EF8, 0x53EF9, 0x180052, 0x18007C, 0xC6FE], True, 'Eastern Palace'),
                  'Desert Palace - Prize': ([0x1209E, 0x53F1C, 0x53F1D, 0x180053, 0x180078, 0xC6FF], True, 'Desert Palace'),
                  'Tower of Hera - Prize': ([0x120A5, 0x53F0A, 0x53F0B, 0x18005A, 0x18007A, 0xC706], True, 'Tower of Hera'),
                  'Palace of Darkness - Prize': ([0x120A1, 0x53F00, 0x53F01, 0x180056, 0x18007D, 0xC702], True, 'Palace of Darkness'),
                  'Swamp Palace - Prize': ([0x120A0, 0x53F6C, 0x53F6D, 0x180055, 0x180071, 0xC701], True, 'Swamp Palace'),
                  'Thieves Town - Prize': ([0x120A6, 0x53F36, 0x53F37, 0x18005B, 0x180077, 0xC707], True, 'Thieves\' Town'),
                  'Skull Woods - Prize': ([0x120A3, 0x53F12, 0x53F13, 0x180058, 0x18007B, 0xC704], True, 'Skull Woods'),
                  'Ice Palace - Prize': ([0x120A4, 0x53F5A, 0x53F5B, 0x180059, 0x180073, 0xC705], True, 'Ice Palace'),
                  'Misery Mire - Prize': ([0x120A2, 0x53F48, 0x53F49, 0x180057, 0x180075, 0xC703], True, 'Misery Mire'),
                  'Turtle Rock - Prize': ([0x120A7, 0x53F24, 0x53F25, 0x18005C, 0x180079, 0xC708], True, 'Turtle Rock')}
