from BaseClasses import Region, Location, Entrance


def create_regions(world):

    world.regions = [
        create_region('Light World', ['Mushroom', 'Bottle Vendor', 'Haunted Grove', 'Piece of Heart (Dam)', 'Purple Chest'],
                      ["Thiefs Hut", "Hyrule Castle Secret Entrance Drop", "Hyrule Castle Secret Entrance Stairs", 'Zoras River', 'Kings Grave', 'Dam',
                       'Links House', 'Tavern North', 'Chicken House', 'Aginahs Cave', 'Sahasrahlas Hut', 'Kakariko Well Drop', 'Kakariko Well Cave',
                       'Blacksmiths Hut', 'Bat Cave Drop Ledge', 'Bat Cave Cave', 'Sick Kids House', 'Hobo Bridge', 'Thieves Forest Hideout Drop', 'Thieves Forest Hideout Stump',
                       'Lumberjack Tree Tree', 'Lumberjack Tree Cave', 'Mini Moldorm Cave', 'Ice Cave', 'Lake Hylia Central Island Pier',
                       'Bonk Rock Cave', 'Library', 'Witch Hut', 'Two Brothers House (East)', 'Desert Palace Stairs', 'Eastern Palace', 'Master Sword Meadow', 'Hyrule Castle Entrance (South)',
                       'Sanctuary', 'Sanctuary Grave', 'Old Man Cave (West)', 'Flute Spot 1', 'Dark Desert Teleporter', 'East Hyrule Teleporter', 'South Hyrule Teleporter', 'Kakariko Teleporter',
                       'Elder House (East)', 'Elder House (West)', 'North Fairy Cave', 'North Fairy Cave Drop', 'Lost Woods Gamble', 'Snitch Lady (East)', 'Snitch Lady (West)', 'Tavern (Front)',
                       'Bush Covered House', 'Light World Bomb Hut', 'Kakariko Shop', 'Long Fairy Cave', 'Good Bee Cave', '20 Rupee Cave', 'Cave Shop (Lake Hylia)', 'Waterfall of Wishing',
                       'Bonk Fairy (Light)', '50 Rupee Cave', 'Fortune Teller (Light)', 'Lake Hylia Fairy', 'Swamp Fairy', 'Desert Fairy', 'Lumberjack House', 'Lake Hylia Fortune Teller', 'Kakariko Gamble Game', 'Top of Pyramid']),
        create_region('Lake Hylia Central Island', None, ['Capacity Upgrade', 'Lake Hylia Central Island Teleporter']),
        create_region('Thiefs Hut', ["[cave-022-B1] Thiefs hut [top chest]",
                                     "[cave-022-B1] Thiefs hut [top left chest]",
                                     "[cave-022-B1] Thiefs hut [top right chest]",
                                     "[cave-022-B1] Thiefs hut [bottom left chest]",
                                     "[cave-022-B1] Thiefs hut [bottom right chest]"]),
        create_region('Hyrule Castle Secret Entrance', ['Uncle', '[cave-034] Hyrule Castle Secret Entrance'], ['Hyrule Castle Secret Entrance Exit']),
        create_region('Zoras River', ['King Zora', 'Piece of Heart (Zoras River)']),
        create_region('Waterfall of Wishing', ['Waterfall Fairy - Left', 'Waterfall Fairy - Right']),
        create_region('Kings Grave', ['[cave-018] Graveyard - top right grave']),
        create_region('North Fairy Cave', None, ['North Fairy Cave Exit']),
        create_region('Dam', ['[cave-047] Dam']),
        create_region('Links House', ['[cave-040] Links House'], ['Links House Exit']),
        create_region('Tavern', ['[cave-031] Tavern']),
        create_region('Elder House', None, ['Elder House Exit (East)', 'Elder House Exit (West)']),
        create_region('Snitch Lady (East)'),
        create_region('Snitch Lady (West)'),
        create_region('Bush Covered House'),
        create_region('Tavern (Front)'),
        create_region('Light World Bomb Hut'),
        create_region('Kakariko Shop'),
        create_region('Fortune Teller (Light)'),
        create_region('Lumberjack House'),
        create_region('Bonk Fairy'),  # near links house both worlds
        create_region('Healer Fairy'),  # 8 entrances?
        create_region('Chicken House', ['[cave-026] Chicken House']),
        create_region('Aginahs Cave', ['[cave-044] Aginahs Cave']),
        create_region('Sahasrahlas Hut', ['[cave-035] Sahasrahlas Hut [left chest]', '[cave-035] Sahasrahlas Hut [center chest]', '[cave-035] Sahasrahlas Hut [right chest]', 'Sahasrahla']),
        create_region('Kakariko Well (top)', ['[cave-021] Kakariko Well [top chest]', '[cave-021] Kakariko Well [left chest row of 3]', '[cave-021] Kakariko Well [center chest row of 3]',
                                              '[cave-021] Kakariko Well [right chest row of 3]', '[cave-021] Kakariko Well [bottom chest]'], ['Kakariko Well (top to bottom)']),
        create_region('Kakariko Well (bottom)', None, ['Kakariko Well Exit']),
        create_region('Blacksmiths Hut', ['Blacksmiths']),
        create_region('Bat Cave Drop Ledge', None, ['Bat Cave Drop']),
        create_region('Bat Cave (right)', ['Magic Bat'], ['Bat Cave Door']),
        create_region('Bat Cave (left)', None, ['Bat Cave Exit']),
        create_region('Sick Kids House', ['Sick Kid']),
        create_region('Hobo Bridge', ['Hobo']),
        create_region('Thieves Forest Hideout (top)', ['Piece of Heart (Thieves Forest Hideout)'], ['Thieves Forest Hideout (top to bottom)']),
        create_region('Thieves Forest Hideout (bottom)', None, ['Thieves Forest Hideout Exit']),
        create_region('Lumberjack Tree (top)', ['Piece of Heart (Lumberjack Tree)'], ['Lumberjack Tree (top to bottom)']),
        create_region('Lumberjack Tree (bottom)', None, ['Lumberjack Tree Exit']),
        create_region('Cave South of Haunted Grove', ['Piece of Heart (Cave South of Haunted Grove)']),
        create_region('Graveyard Cave', ['Piece of Heart (Graveyard Cave)']),
        create_region('Checkerboard Cave', ['Piece of Heart (Checkerboard Cave)']),
        create_region('Long Fairy Cave'),
        create_region('Mini Moldorm Cave', ['[cave-050] Mini Moldorm Cave [bottom left chest]', '[cave-050] Mini Moldorm Cave [top left chest]', '[cave-050] Mini Moldorm Cave [top right chest]',
                                          '[cave-050] Mini Moldorm Cave [bottom right chest]', '[cave-050] Mini Moldorm Cave [generous guy]']),
        create_region('Ice Cave', ['[cave-051] Ice Cave']),
        create_region('Good Bee Cave'),
        create_region('20 Rupee Cave'),
        create_region('Cave Shop'),  # two connectors in vanilla
        create_region('Bonk Rock Cave', ['[cave-016] Bonk Rock Cave']),
        create_region('Library', ['Library']),
        create_region('Kakariko Gamble Game'),
        create_region('Witch Hut', ['Witch']),
        create_region('Lake Hylia Island', ['Piece of Heart (Lake Hylia)']),
        create_region('Capacity Upgrade'),
        create_region('Two Brothers House', None, ['Two Brothers House Exit (East)', 'Two Brothers House Exit (West)']),
        create_region('Maze Race Ledge', ['Piece of Heart (Maze Race)'], ['Two Brothers House (West)']),
        create_region('50 Rupee Cave'),
        create_region('Desert Ledge', ['Piece of Heart (Desert - west side)'], ['Desert Palace Entrance (North) Rocks', 'Desert Palace Entrance (West)']),
        create_region('Desert Ledge (West)', None, ['Checkerboard Cave']),
        create_region('Desert Palace Stairs', None, ['Desert Palace Entrance (South)']),
        create_region('Desert Palace Lone Stairs', None, ['Desert Palace Stairs Drop', 'Desert Palace Entrance (East)']),
        create_region('Desert Palace Entrance (North) Spot', None, ['Desert Palace Entrance (North)', 'Desert Ledge Return Rocks']),
        create_region('Desert Palace Main', ['[dungeon-L2-B1] Desert Palace - Big Chest', '[dungeon-L2-B1] Desert Palace - Torch', '[dungeon-L2-B1] Desert Palace - Map Room'],
                      ['Desert Palace Exit (South)', 'Desert Palace Exit (West)', 'Desert Palace Exit (East)', 'Desert Palace East Wing']),
        create_region('Desert Palace East', ['[dungeon-L2-B1] Desert Palace - Compass Room', '[dungeon-L2-B1] Desert Palace - Big Key Room']),
        create_region('Desert Palace North', ['Lanmolas - Heart Container', 'Lanmolas - Pendant'], ['Desert Palace Exit (North)']),
        create_region('Eastern Palace', ['[dungeon-L1-1F] Eastern Palace - Compass Room', '[dungeon-L1-1F] Eastern Palace - Big Chest', '[dungeon-L1-1F] Eastern Palace - Big Ball Room',
                                         '[dungeon-L1-1F] Eastern Palace - Big Key Room', '[dungeon-L1-1F] Eastern Palace - Map Room', 'Armos - Heart Container', 'Armos - Pendant'], ['Eastern Palace Exit']),
        create_region('Master Sword Meadow', ['Altar']),
        create_region('Lost Woods Gamble'),
        create_region('Hyrule Castle Ledge', None, ['Hyrule Castle Entrance (East)', 'Hyrule Castle Entrance (West)', 'Agahnims Tower']),
        create_region('Hyrule Castle', ['[dungeon-C-B1] Hyrule Castle - Boomerang Room', '[dungeon-C-B1] Hyrule Castle - Map Room', '[dungeon-C-B1] Hyrule Castle - Next To Zelda'],
                      ['Hyrule Castle Exit (East)', 'Hyrule Castle Exit (West)', 'Hyrule Castle Exit (South)', 'Throne Room']),
        create_region('Sewer Drop', None, ['Sewer Drop']),  # This exists only to be referenced for access checks
        create_region('Sewers (Dark)', ['[dungeon-C-B1] Escape - First B1 Room'], ['Sewers Door']),
        create_region('Sewers', ['[dungeon-C-B1] Escape - Final Basement Room [left chest]', '[dungeon-C-B1] Escape - Final Basement Room [middle chest]',
                                 '[dungeon-C-B1] Escape - Final Basement Room [right chest]'], ['Sanctuary Push Door', 'Sewers Back Door']),
        create_region('Sanctuary', ['[dungeon-C-1F] Sanctuary'], ['Sanctuary Exit']),
        create_region('Agahnims Tower', ['[dungeon-A1-2F] Hyrule Castle Tower - 2 Knife Guys Room', '[dungeon-A1-3F] Hyrule Castle Tower - Maze Room'], ['Agahnim 1', 'Agahnims Tower Exit']),
        create_region('Agahnim 1', ['Agahnim 1'], None),
        create_region('Old Man Cave', ['Old Mountain Man'], ['Old Man Cave Exit (East)', 'Old Man Cave Exit (West)']),
        create_region('Old Man House', None, ['Old Man House Exit (Bottom)', 'Old Man House Front to Back']),
        create_region('Old Man House Back', None, ['Old Man House Exit (Top)', 'Old Man House Back to Front']),
        create_region('Death Mountain', None, ['Old Man Cave (East)', 'Old Man House (Bottom)', 'Old Man House (Top)', 'Death Mountain Return Cave (East)', 'Spectacle Rock Cave', 'Spectacle Rock Cave Peak', 'Spectacle Rock Cave (Bottom)', 'Broken Bridge (West)', 'Death Mountain Teleporter']),
        create_region('Death Mountain Return Cave', None, ['Death Mountain Return Cave Exit (West)', 'Death Mountain Return Cave Exit (East)']),
        create_region('Death Mountain Return Ledge', None, ['Death Mountain Return Ledge Drop', 'Death Mountain Return Cave (West)']),
        create_region('Spectacle Rock Cave (Top)', ['Piece of Heart (Spectacle Rock Cave)'], ['Spectacle Rock Cave Drop', 'Spectacle Rock Cave Exit (Top)']),
        create_region('Spectacle Rock Cave (Bottom)', None, ['Spectacle Rock Cave Exit']),
        create_region('Spectacle Rock Cave (Peak)', None, ['Spectacle Rock Cave Peak Drop', 'Spectacle Rock Cave Exit (Peak)']),
        create_region('East Death Mountain (Bottom)', None, ['Broken Bridge (East)', '7 Chest Cave (Bottom)', '7 Chest Cave (Middle)', 'East Death Mountain Teleporter', 'Hookshot Fairy', 'Fairy Ascension Rocks', 'Spiral Cave (Bottom)']),
        create_region('Hookshot Fairy'),
        create_region('7 Chest Cave Front', None, ['7 Chest Cave Push Block Reverse', '7 Chest Cave Exit (Bottom)']),
        create_region('7 Chest Cave Chest Area', ['[cave-009-1F] Death Mountain - right cave [top left chest]',
                                                               '[cave-009-1F] Death Mountain - right cave [top left middle chest]',
                                                               '[cave-009-1F] Death Mountain - right cave [top right middle chest]',
                                                               '[cave-009-1F] Death Mountain - right cave [top right chest]',
                                                               '[cave-009-1F] Death Mountain - right cave [bottom chest]',
                                                               '[cave-009-B1] Death Mountain - right cave [left chest]',
                                                               '[cave-009-B1] Death Mountain - right cave [right chest]'],
                      ['7 Chest Cave Push Block', '7 Chest Cave Bomb Jump']),
        create_region('7 Chest Cave', None, ['7 Chest Cave Exit (Middle)', '7 Chest Cave Exit (Top)', '7 Chest Cave Drop']),
        create_region('East Death Mountain (Top)', None, ['7 Chest Cave (Top)', 'Death Mountain (Top)', 'Spiral Cave Ledge Access', 'East Death Mountain Drop', 'Turtle Rock Teleporter', 'Fairy Ascension Ledge']),
        create_region('Spiral Cave Ledge', None, ['Spiral Cave', 'Spiral Cave Ledge Drop']),
        create_region('Spiral Cave (Top)', ['[cave-012-1F] Death Mountain - left cave]'], ['Spiral Cave (top to bottom)', 'Spiral Cave Exit (Top)']),
        create_region('Spiral Cave (Bottom)', None, ['Spiral Cave Exit']),
        create_region('Fairy Ascension Plateau', None, ['Fairy Ascension Drop', 'Fairy Ascension Cave (Bottom)']),
        create_region('Fairy Ascension Cave', None, ['Fairy Ascension Cave Exit (Top)', 'Fairy Ascension Cave Exit (Bottom)']),
        create_region('Fairy Ascension Ledge', None, ['Fairy Ascension Ledge Drop', 'Fairy Ascension Cave (Top)']),
        create_region('Death Mountain (Top)', ['Ether Tablet'], ['East Death Mountain (Top)', 'Tower of Hera', 'Death Mountain Drop']),
        create_region('Spectacle Rock', ['Piece of Heart (Spectacle Rock)'], ['Spectacle Rock Drop']),
        create_region('Tower of Hera (Bottom)', ['[dungeon-L3-1F] Tower of Hera - Freestanding Key', '[dungeon-L3-1F] Tower of Hera - Entrance'], ['Tower of Hera Small Key Door', 'Tower of Hera Big Key Door', 'Tower of Hera Exit']),
        create_region('Tower of Hera (Basement)', ['[dungeon-L3-1F] Tower of Hera - Basement']),
        create_region('Tower of Hera (Top)', ['[dungeon-L3-1F] Tower of Hera - 4F [small chest]', '[dungeon-L3-1F] Tower of Hera - Big Chest', 'Moldorm - Heart Container', 'Moldorm - Pendant']),

        create_region('East Dark World', ['Piece of Heart (Pyramid)', 'Catfish'], ['Pyramid Fairy', 'South Dark World Bridge', 'West Dark World Gap', 'Palace of Darkness', 'Dark Lake Hylia Drop (East)', 'Dark Lake Hylia Teleporter',
                                                                                   'Hyrule Castle Ledge Mirror Spot', 'Dark Lake Hylia Fairy', 'Palace of Darkness Hint', 'East Dark World Hint', 'Dark World Potion Shop', 'Pyramid Hole']),
        create_region('Palace of Darkness Hint'),
        create_region('East Dark World Hint'),
        create_region('South Dark World', ['Flute Boy', 'Piece of Heart (Digging Game)', 'Bombos Tablet'], ['Dark Lake Hylia Drop (South)', 'Dark Swamp Cave', 'Swamp Palace', 'Village of Outcasts Heavy Rock',
                                                                                                            'Maze Race Mirror Spot', 'Cave South of Haunted Grove', 'East Dark World Bridge', 'Big Bomb Shop', 'Archery Game', 'Bonk Fairy (Dark)', 'Dark Lake Hylia Shop']),
        create_region('Big Bomb Shop'),
        create_region('Archery Game'),
        create_region('Dark Lake Hylia', None, ['Lake Hylia Island Mirror Spot', 'East Dark World Pier', 'Dark Lake Hylia Ledge']),
        create_region('Dark Lake Hylia Central Island', None, ['Ice Palace', 'Lake Hylia Central Island Mirror Spot']),
        create_region('Dark Lake Hylia Ledge', None, ['Dark Lake Hylia Ledge Drop', 'Dark Lake Hylia Ledge Fairy', 'Dark Lake Hylia Ledge Hint', 'Dark Lake Hylia Ledge Spike Cave']),
        create_region('Dark Lake Hylia Ledge Hint'),
        create_region('Dark Lake Hylia Ledge Spike Cave'),
        create_region('Dark Swamp Cave', ['[cave-073] Cave Northeast of Swamp Palace [top chest]', '[cave-073] Cave Northeast of Swamp Palace [top middle chest]', '[cave-073] Cave Northeast of Swamp Palace [bottom middle chest]',
                                          '[cave-073] Cave Northeast of Swamp Palace [bottom chest]', '[cave-073] Cave Northeast of Swamp Palace [generous guy]']),
        create_region('West Dark World', None, ['Village of Outcasts Drop', 'East Dark World River Pier', 'Doorless Hut', 'C-Shaped House', 'Chest Game', 'Thieves Town', 'Graveyard Cave', 'Bumper Cave (Bottom)', 'Skull Woods Forest',
                                                'Bat Cave Drop Ledge Mirror Spot', 'Dark World Hammer Peg Cave', 'Red Shield Shop', 'Dark Sanctuary Hint', 'Fortune Teller (Dark)', 'Dark World Shop', 'Dark World Lumberjack Shop']),
        create_region('Fortune Teller (Dark)'),
        create_region('Dark World Shop'),
        create_region('Dark World Hammer Peg Cave', ['Piece of Heart (Dark World Blacksmith Pegs)']),
        create_region('Pyramid Fairy', ['Pyramid Fairy [left chest]', 'Pyramid Fairy [right chest]']),
        create_region('Doorless Hut', ['[cave-063] Doorless Hut']),
        create_region('C-Shaped House', ['[cave-062] C-Shaped House']),
        create_region('Chest Game', ['Piece of Heart (Treasure Chest Game)']),
        create_region('Red Shield Shop'),
        create_region('Dark Sanctuary Hint'),
        create_region('Bumper Cave', None, ['Bumper Cave Exit (Bottom)', 'Bumper Cave Exit (Top)']),
        create_region('Bumper Cave Ledge', ['Piece of Heart (Bumper Cave)'], ['Bumper Cave Ledge Drop', 'Bumper Cave (Top)', 'Bumper Cave Ledge Mirror Spot']),
        create_region('Skull Woods Forest', None, ['Skull Woods First Section Hole (East)', 'Skull Woods First Section Hole (West)', 'Skull Woods First Section Hole (North)', 'Skull Woods First Section Door',
                                                   'Skull Woods Second Section Door (East)']),
        create_region('Skull Woods Forest (West)', None, ['Skull Woods Second Section Hole', 'Skull Woods Second Section Door (West)', 'Skull Woods Final Section']),
        create_region('Dark Desert', None, ['Misery Mire', 'Dark Desert Cave', 'Desert Ledge (West) Mirror Spot', 'Desert Ledge Mirror Spot', 'Desert Palace Stairs Mirror Spot', 'Desert Palace Entrance (North) Mirror Spot',
                                            'Dark Desert Hint', 'Dark Desert Fairy']),
        create_region('Dark Desert Cave', ['[cave-071] Misery Mire West Area [left chest]', '[cave-071] Misery Mire West Area [right chest]']),
        create_region('Dark Desert Hint'),
        create_region('Dark Death Mountain (West Bottom)', None, ['Spike Cave', 'Spectacle Rock Mirror Spot', 'Dark Death Mountain Fairy']),
        create_region('Dark Death Mountain (Top)', None, ['Dark Death Mountain Drop (East)', 'Dark Death Mountain Drop (West)', 'Ganons Tower', 'Dark Death Mountain Ascend (Top)', 'Hookshot Cave',
                                                          'East Death Mountain (Top) Mirror Spot', 'Turtle Rock']),
        create_region('Dark Death Mountain Ledge', None, ['Dark Death Mountain Ledge (East)', 'Dark Death Mountain Ledge (West)', 'Mimic Cave Mirror Spot', 'Spiral Cave Mirror Spot']),
        create_region('Dark Death Mountain Isolated Ledge', None, ['Isolated Ledge Mirror Spot', 'Turtle Rock Isolated Ledge Entrance']),
        create_region('Dark Death Mountain (East Bottom)', None, ['Dark Death Mountain Ascend (Bottom)', 'Cave Shop (Dark Death Mountain)', 'Fairy Ascension Mirror Spot']),
        create_region('Dark Death Mountain Ascend', ['[cave-057-1F] Dark World Death Mountain Climb [top chest]', '[cave-057-1F] Dark World Death Mountain Climb [bottom chest]'],
                      ['Dark Death Mountain Ascend Exit (Top)', 'Dark Death Mountain Ascend Exit (Bottom)']),
        create_region('Spike Cave', ['[cave-055] Spike Cave']),
        create_region('Hookshot Cave', ['[cave-056] Hookshot Cave [top right chest]', '[cave-056] Hookshot Cave [top left chest]', '[cave-056] Hookshot Cave [bottom right chest]', '[cave-056] Hookshot Cave [bottom left chest]'],
                      ['Hookshot Cave Exit (South)', 'Hookshot Cave Exit (North)']),
        create_region('Death Mountain Floating Island', ['Piece of Heart (Death Mountain - Floating Island)'], ['Floating Island Drop', 'Hookshot Cave Back Entrance']),
        create_region('Turtle Rock (Top)', None, ['Turtle Rock Drop']),
        create_region('Mimic Cave', ['[cave-013] Mimic Cave']),

        create_region('Swamp Palace (Entrance)', None, ['Swamp Palace Moat', 'Swamp Palace Exit']),
        create_region('Swamp Palace (First Room)', ['[dungeon-D2-1F] Swamp Palace - First Room'], ['Swamp Palace Small Key Door']),
        create_region('Swamp Palace (Starting Area)', ['[dungeon-D2-1F] Swamp Palace - Map Room'], ['Swamp Palace (Center)']),
        create_region('Swamp Palace (Center)', ['[dungeon-D2-B1] Swamp Palace - Big Chest', '[dungeon-D2-B1] Swamp Palace - South of Hookshot Room',
                                                '[dungeon-D2-B1] Swamp Palace - Big Key Chest', '[dungeon-D2-B1] Swamp Palace - Compass Chest'], ['Swamp Palace (North)']),
        create_region('Swamp Palace (North)', ['[dungeon-D2-B2] Swamp Palace - Flooded Room [left chest]', '[dungeon-D2-B2] Swamp Palace - Flooded Room [right chest]',
                                               '[dungeon-D2-B2] Swamp Palace - Waterfall Room', 'Arrghus - Heart Container', 'Arrghus - Crystal']),
        create_region('Thieves Town (Entrance)', ['[dungeon-D4-B1] Thieves Town - Bottom Left of Huge Room [bottom right chest]',
                                                  '[dungeon-D4-B1] Thieves Town - Bottom Left of Huge Room [top left chest]',
                                                  '[dungeon-D4-B1] Thieves Town - Bottom Right of Huge Room',
                                                  '[dungeon-D4-B1] Thieves Town - Top Left of Huge Room'], ['Thieves Town Big Key Door', 'Thieves Town Exit']),
        create_region('Thieves Town (Deep)', ['[dungeon-D4-1F] Thieves Town - Room above Boss',
                                              '[dungeon-D4-B2] Thieves Town - Big Chest',
                                              '[dungeon-D4-B2] Thieves Town - Chest next to Blind'], ['Blind Fight']),
        create_region('Blind Fight', ['Blind - Heart Container', 'Blind - Crystal']),
        create_region('Skull Woods First Section', ['[dungeon-D3-B1] Skull Woods - East of Big Chest'], ['Skull Woods First Section Exit', 'Skull Woods First Section Bomb Jump', 'Skull Woods First Section South Door', 'Skull Woods First Section West Door']),
        create_region('Skull Woods First Section (Right)', ['[dungeon-D3-B1] Skull Woods - South of Big Chest'], ['Skull Woods First Section (Right) North Door']),
        create_region('Skull Woods First Section (Left)', ['[dungeon-D3-B1] Skull Woods - Compass Room', '[dungeon-D3-B1] Skull Woods - Push Statue Room'], ['Skull Woods First Section (Left) Door to Exit', 'Skull Woods First Section (Left) Door to Right']),
        create_region('Skull Woods First Section (Top)', ['[dungeon-D3-B1] Skull Woods - Big Chest'], ['Skull Woods First Section (Top) One-Way Path']),
        create_region('Skull Woods Second Section', ['[dungeon-D3-B1] Skull Woods - Big Key Room'], ['Skull Woods Second Section Exit (East)', 'Skull Woods Second Section Exit (West)']),
        create_region('Skull Woods Final Section (Entrance)', ['[dungeon-D3-B1] Skull Woods - Final Section Entrance'], ['Skull Woods Torch Room', 'Skull Woods Final Section Exit']),
        create_region('Skull Woods Final Section (Mothula)', ['Mothula - Heart Container', 'Mothula - Crystal']),
        create_region('Ice Palace (Entrance)', None, ['Ice Palace Entrance Room', 'Ice Palace Exit']),
        create_region('Ice Palace (Main)', ['[dungeon-D5-B1] Ice Palace - Compass Room', '[dungeon-D5-B4] Ice Palace - Above Big Chest',
                                            '[dungeon-D5-B5] Ice Palace - Big Chest', '[dungeon-D5-B5] Ice Palace - Jellyfish Room'], ['Ice Palace (East)', 'Ice Palace (Kholdstare)']),
        create_region('Ice Palace (East)', ['[dungeon-D5-B3] Ice Palace - Spike Room'], ['Ice Palace (East Top)']),
        create_region('Ice Palace (East Top)', ['[dungeon-D5-B1] Ice Palace - Big Key Room', '[dungeon-D5-B2] Ice Palace - Map Room']),
        create_region('Ice Palace (Kholdstare)', ['Kholdstare - Heart Container', 'Kholdstare - Crystal']),
        create_region('Misery Mire (Entrance)', None, ['Misery Mire Entrance Gap', 'Misery Mire Exit']),
        create_region('Misery Mire (Main)', ['[dungeon-D6-B1] Misery Mire - Big Chest', '[dungeon-D6-B1] Misery Mire - Map Room', '[dungeon-D6-B1] Misery Mire - Hub Room',
                                             '[dungeon-D6-B1] Misery Mire - End of Bridge', '[dungeon-D6-B1] Misery Mire - Spike Room'], ['Misery Mire (West)', 'Misery Mire Big Key Door']),
        create_region('Misery Mire (West)', ['[dungeon-D6-B1] Misery Mire - Compass Room', '[dungeon-D6-B1] Misery Mire - Big Key Room']),
        create_region('Misery Mire (Final Area)', None, ['Misery Mire (Vitreous)']),
        create_region('Misery Mire (Vitreous)', ['Vitreous - Heart Container', 'Vitreous - Crystal']),
        create_region('Turtle Rock (Entrance)', None, ['Turtle Rock Entrance Gap', 'Turtle Rock Exit (Front)']),
        create_region('Turtle Rock (First Section)', ['[dungeon-D7-1F] Turtle Rock - Compass Room', '[dungeon-D7-1F] Turtle Rock - Map Room [left chest]',
                                                      '[dungeon-D7-1F] Turtle Rock - Map Room [right chest]'], ['Turtle Rock Pokey Room', 'Turtle Rock Entrance Gap Reverse']),
        create_region('Turtle Rock (Chain Chomp Room)', ['[dungeon-D7-1F] Turtle Rock - Chain Chomp Room'], ['Turtle Rock (Chain Chomp Room) (North)', 'Turtle Rock (Chain Chomp Room) (South)']),
        create_region('Turtle Rock (Second Section)', ['[dungeon-D7-B1] Turtle Rock - Big Key Room'], ['Turtle Rock Ledge Exit (West)', 'Turtle Rock Chain Chomp Staircase', 'Turtle Rock Big Key Door']),
        create_region('Turtle Rock (Big Chest)', ['[dungeon-D7-B1] Turtle Rock - Big Chest'], ['Turtle Rock (Big Chest) (North)', 'Turtle Rock Ledge Exit (East)']),
        create_region('Turtle Rock (Roller Switch Room)', ['[dungeon-D7-B1] Turtle Rock - Roller Switch Room'], ['Turtle Rock Dark Room Staircase', 'Turtle Rock Big Key Door Reverse']),
        create_region('Turtle Rock (Dark Room)', None, ['Turtle Rock (Dark Room) (North)', 'Turtle Rock (Dark Room) (South)']),
        create_region('Turtle Rock (Eye Bridge)', ['[dungeon-D7-B2] Turtle Rock - Eye Bridge Room [bottom left chest]', '[dungeon-D7-B2] Turtle Rock - Eye Bridge Room [bottom right chest]',
                                                   '[dungeon-D7-B2] Turtle Rock - Eye Bridge Room [top left chest]', '[dungeon-D7-B2] Turtle Rock - Eye Bridge Room [top right chest]'],
                      ['Turtle Rock Dark Room (South)', 'Turtle Rock (Trinexx)', 'Turtle Rock Isolated Ledge Exit']),
        create_region('Turtle Rock (Trinexx)', ['Trinexx - Heart Container', 'Trinexx - Crystal']),
        create_region('Dark Palace (Entrance)', ['[dungeon-D1-B1] Dark Palace - Shooter Room'], ['Dark Palace Bridge Room', 'Dark Palace Bonk Wall', 'Dark Palace Exit']),
        create_region('Dark Palace (Center)', ['[dungeon-D1-1F] Dark Palace - Jump Room [left chest]', '[dungeon-D1-B1] Dark Palace - Turtle Stalfos Room'],
                      ['Dark Palace Big Key Chest Staircase', 'Dark Palace (North)', 'Dark Palace Big Key Door']),
        create_region('Dark Palace (Big Key Chest)', ['[dungeon-D1-1F] Dark Palace - Big Key Room']),
        create_region('Dark Palace (Bonk Section)', ['[dungeon-D1-1F] Dark Palace - Jump Room [right chest]', '[dungeon-D1-1F] Dark Palace - Statue Push Room'], ['Dark Palace Hammer Peg Drop']),
        create_region('Dark Palace (North)', ['[dungeon-D1-1F] Dark Palace - Compass Room', '[dungeon-D1-B1] Dark Palace - Dark Room [left chest]', '[dungeon-D1-B1] Dark Palace - Dark Room [right chest]'],
                      ['Dark Palace Spike Statue Room Door', 'Dark Palace Maze Door']),
        create_region('Dark Palace (Maze)', ['[dungeon-D1-1F] Dark Palace - Maze Room [top chest]', '[dungeon-D1-1F] Dark Palace - Maze Room [bottom chest]', '[dungeon-D1-1F] Dark Palace - Big Chest']),
        create_region('Dark Palace (Spike Statue Room)', ['[dungeon-D1-1F] Dark Palace - Spike Statue Room']),
        create_region('Dark Palace (Final Section)', ['Helmasaur - Heart Container', 'Helmasaur - Crystal']),
        create_region('Ganons Tower (Entrance)', ['[dungeon-A2-1F] Ganons Tower - Torch', '[dungeon-A2-1F] Ganons Tower - Right Staircase [left chest]', '[dungeon-A2-1F] Ganons Tower - Right Staircase [right chest]'],
                      ['Ganons Tower (Tile Room)', 'Ganons Tower (Hookshot Room)', 'Ganons Tower Big Key Door', 'Ganons Tower Exit']),
        create_region('Ganons Tower (Tile Room)', ['[dungeon-A2-1F] Ganons Tower - Tile Room'], ['Ganons Tower (Tile Room) Key Door']),
        create_region('Ganons Tower (Compass Room)', ['[dungeon-A2-1F] Ganons Tower - Compass Room [top left chest]', '[dungeon-A2-1F] Ganons Tower - Compass Room [top right chest]',
                                                      '[dungeon-A2-1F] Ganons Tower - Compass Room [bottom left chest]', '[dungeon-A2-1F] Ganons Tower - Compass Room [bottom right chest]'],
                      ['Ganons Tower (Bottom) (East)']),
        create_region('Ganons Tower (Hookshot Room)', ['[dungeon-A2-1F] Ganons Tower - North of Hookshot Room [top left chest]', '[dungeon-A2-1F] Ganons Tower - North of Hookshot Room [top right chest]',
                                                       '[dungeon-A2-1F] Ganons Tower - North of Hookshot Room [bottom left chest]', '[dungeon-A2-1F] Ganons Tower - North of Hookshot Room [bottom right chest]'],
                      ['Ganons Tower (Map Room)', 'Ganons Tower (Double Switch Room)']),
        create_region('Ganons Tower (Map Room)', ['[dungeon-A2-1F] Ganons Tower - Map Room']),
        create_region('Ganons Tower (Firesnake Room)', ['[dungeon-A2-1F] Ganons Tower - Firesnake Room'], ['Ganons Tower (Firesnake Room)']),
        create_region('Ganons Tower (Teleport Room)', ['[dungeon-A2-1F] Ganons Tower - Teleport Room [top left chest]', '[dungeon-A2-1F] Ganons Tower - Teleport Room [top right chest]',
                                                       '[dungeon-A2-1F] Ganons Tower - Teleport Room [bottom left chest]', '[dungeon-A2-1F] Ganons Tower - Teleport Room [bottom right chest]'],
                      ['Ganons Tower (Bottom) (West)']),
        create_region('Ganons Tower (Bottom)', ['[dungeon-A2-1F] Ganons Tower - above Armos', '[dungeon-A2-1F] Ganons Tower - Big Chest', '[dungeon-A2-B1] Ganons Tower - Armos Room [left chest]',
                                                '[dungeon-A2-B1] Ganons Tower - Armos Room [right chest]', '[dungeon-A2-B1] Ganons Tower - Armos Room [bottom chest]']),
        create_region('Ganons Tower (Top)', None, ['Ganons Tower Torch Rooms']),
        create_region('Ganons Tower (Before Moldorm)', ['[dungeon-A2-6F] Ganons Tower - Mini Helmasaur Room [left chest]', '[dungeon-A2-6F] Ganons Tower - Mini Helmasaur Room [right chest]',
                                                        '[dungeon-A2-6F] Ganons Tower - Room before Moldorm'], ['Ganons Tower Moldorm Door']),
        create_region('Ganons Tower (Moldorm)', None, ['Ganons Tower Moldorm Gap']),
        create_region('Agahnim 2', ['[dungeon-A2-6F] Ganons Tower - Moldorm Room', 'Agahnim 2'], None),
        create_region('Pyramid', ['Ganon'], ['Ganon Drop']),
        create_region('Bottom of Pyramid', None, ['Pyramid Exit']),
        create_region('Pyramid Ledge', None, ['Pyramid Entrance', 'Pyramid Drop'])
        ]
        
    world.intialize_regions()


def create_region(name, locations=None, exits=None):
    ret = Region(name)
    if locations is None:
        locations = []
    if exits is None:
        exits = []

    for exit in exits:
        ret.exits.append(Entrance(exit, ret))
    for location in locations:
        address, crystal, hint_text = location_table[location]
        ret.locations.append(Location(location, address, crystal, hint_text, ret))
    return ret


location_table = {'Mushroom': (0x180013, False, 'in the woods'),
                  'Bottle Vendor': (0x2EB18, False, 'with a merchant'),
                  'Haunted Grove': (0x18014A, False, 'underground'),
                  'Piece of Heart (Dam)': (0x180145, False, 'underwater'),
                  'Purple Chest': (0x33D68, False, 'from a box'),
                  '[cave-022-B1] Thiefs hut [top chest]': (0xEB0F, False, 'in a basement'),
                  '[cave-022-B1] Thiefs hut [top left chest]': (0xEB12, False, 'in a basement'),
                  '[cave-022-B1] Thiefs hut [top right chest]': (0xEB15, False, 'in a basement'),
                  '[cave-022-B1] Thiefs hut [bottom left chest]': (0xEB18, False, 'in a basement'),
                  '[cave-022-B1] Thiefs hut [bottom right chest]': (0xEB1B, False, 'in a basement'),
                  'Uncle': (0x2DF45, False, 'with your uncle'),
                  '[cave-034] Hyrule Castle Secret Entrance': (0xE971, False, 'near your uncle'),
                  'King Zora': (0xEE1C3, False, 'at a high price'),
                  'Piece of Heart (Zoras River)': (0x180149, False, 'near Zora'),
                  'Waterfall Fairy - Left': (0xE9B0, False, 'near a fairy'),
                  'Waterfall Fairy - Right': (0xE9D1, False, 'near a fairy'),
                  '[cave-018] Graveyard - top right grave': (0xE97A, False, 'alone in a cave'),
                  '[cave-047] Dam': (0xE98C, False, 'in the dam'),
                  '[cave-040] Links House': (0xE9BC, False, 'in your home'),
                  '[cave-031] Tavern': (0xE9CE, False, 'in the bar'),
                  '[cave-026] Chicken House': (0xE9E9, False, 'near poultry'),
                  '[cave-044] Aginahs Cave': (0xE9F2, False, 'with Aginah'),
                  '[cave-035] Sahasrahlas Hut [left chest]': (0xEA82, False, 'near the elder'),
                  '[cave-035] Sahasrahlas Hut [center chest]': (0xEA85, False, 'near the elder'),
                  '[cave-035] Sahasrahlas Hut [right chest]': (0xEA88, False, 'near the elder'),
                  'Sahasrahla': (0x2F1FC, False, 'with the elder'),
                  '[cave-021] Kakariko Well [top chest]': (0xEA8E, False, 'in a well'),
                  '[cave-021] Kakariko Well [left chest row of 3]': (0xEA91, False, 'in a well'),
                  '[cave-021] Kakariko Well [center chest row of 3]': (0xEA94, False, 'in a well'),
                  '[cave-021] Kakariko Well [right chest row of 3]': (0xEA97, False, 'in a well'),
                  '[cave-021] Kakariko Well [bottom chest]': (0xEA9A, False, 'in a well'),
                  'Blacksmiths': (0x18002A, False, 'with the smith'),
                  'Magic Bat': (0x180015, False, 'with the bat'),
                  'Sick Kid': (0x339CF, False, 'with the ill'),
                  'Hobo': (0x33E7D, False, 'with the hobo'),
                  'Piece of Heart (Thieves Forest Hideout)': (0x180000, False, 'near a thief'),
                  'Piece of Heart (Lumberjack Tree)': (0x180001, False, 'in a hole'),
                  'Piece of Heart (Cave South of Haunted Grove)': (0x180003, False, 'alone in a cave'),
                  'Piece of Heart (Graveyard Cave)': (0x180004, False, 'alone in a cave'),
                  'Piece of Heart (Checkerboard Cave)': (0x180005, False, 'alone in a cave'),
                  '[cave-050] Mini Moldorm Cave [bottom left chest]': (0xEB42, False, 'near Moldorms'),
                  '[cave-050] Mini Moldorm Cave [top left chest]': (0xEB45, False, 'near Moldorms'),
                  '[cave-050] Mini Moldorm Cave [top right chest]': (0xEB48, False, 'near Moldorms'),
                  '[cave-050] Mini Moldorm Cave [bottom right chest]': (0xEB4B, False, 'near Moldorms'),
                  '[cave-050] Mini Moldorm Cave [generous guy]': (0x180010, False, 'near Moldorms'),
                  '[cave-051] Ice Cave': (0xEB4E, False, 'on ice'),
                  '[cave-016] Bonk Rock Cave': (0xEB3F, False, 'alone in a cave'),
                  'Library': (0x180012, False, 'near books'),
                  'Witch': (0x180014, False, 'near potions'),
                  'Piece of Heart (Lake Hylia)': (0x180144, False, 'on an island'),
                  'Piece of Heart (Maze Race)': (0x180142, False, 'at the race'),
                  'Piece of Heart (Desert - west side)': (0x180143, False, 'in the desert'),
                  '[dungeon-L2-B1] Desert Palace - Big Chest': (0xE98F, False, 'in Desert Palace'),
                  '[dungeon-L2-B1] Desert Palace - Torch': (0x180160, False, 'in Desert Palace'),
                  '[dungeon-L2-B1] Desert Palace - Map Room': (0xE9B6, False, 'in Desert Palace'),
                  '[dungeon-L2-B1] Desert Palace - Compass Room': (0xE9CB, False, 'in Desert Palace'),
                  '[dungeon-L2-B1] Desert Palace - Big Key Room': (0xE9C2, False, 'in Desert Palace'),
                  'Lanmolas - Heart Container': (0x180151, False, 'with Lanmolas'),
                  '[dungeon-L1-1F] Eastern Palace - Compass Room': (0xE977, False, 'in Eastern Palace'),
                  '[dungeon-L1-1F] Eastern Palace - Big Chest': (0xE97D, False, 'in Eastern Palace'),
                  '[dungeon-L1-1F] Eastern Palace - Big Ball Room': (0xE9B3, False, 'in Eastern Palace'),
                  '[dungeon-L1-1F] Eastern Palace - Big Key Room': (0xE9B9, False, 'in Eastern Palace'),
                  '[dungeon-L1-1F] Eastern Palace - Map Room': (0xE9F5, False, 'in Eastern Palace'),
                  'Armos - Heart Container': (0x180150, False, 'with the Armos'),
                  'Altar': (0x289B0, False, 'at the pedestal'),
                  '[dungeon-C-B1] Hyrule Castle - Boomerang Room': (0xE974, False, 'in Hyrule Castle'),
                  '[dungeon-C-B1] Hyrule Castle - Map Room': (0xEB0C, False, 'in Hyrule Castle'),
                  '[dungeon-C-B1] Hyrule Castle - Next To Zelda': (0xEB09, False, 'in Hyrule Castle'),
                  '[dungeon-C-B1] Escape - First B1 Room': (0xE96E, False, 'in the sewers'),
                  '[dungeon-C-B1] Escape - Final Basement Room [left chest]': (0xEB5D, False, 'in the sewers'),
                  '[dungeon-C-B1] Escape - Final Basement Room [middle chest]': (0xEB60, False, 'in the sewers'),
                  '[dungeon-C-B1] Escape - Final Basement Room [right chest]': (0xEB63, False, 'in the sewers'),
                  '[dungeon-C-1F] Sanctuary': (0xEA79, False, 'in Sanctuary'),
                  '[dungeon-A1-2F] Hyrule Castle Tower - 2 Knife Guys Room': (0xEAB5, False, 'in Hyrule Castle'),
                  '[dungeon-A1-3F] Hyrule Castle Tower - Maze Room': (0xEAB2, False, 'in Hyrule Castle'),
                  'Old Mountain Man': (0xF69FA, False, 'with the old man'),
                  'Piece of Heart (Spectacle Rock Cave)': (0x180002, False, 'alone in a cave'),
                  '[cave-009-1F] Death Mountain - right cave [top left chest]': (0xEB2A, False, 'in seven cave'),
                  '[cave-009-1F] Death Mountain - right cave [top left middle chest]': (0xEB2D, False, 'in seven cave'),
                  '[cave-009-1F] Death Mountain - right cave [top right middle chest]': (0xEB30, False, 'in seven cave'),
                  '[cave-009-1F] Death Mountain - right cave [top right chest]': (0xEB33, False, 'in seven cave'),
                  '[cave-009-1F] Death Mountain - right cave [bottom chest]': (0xEB36, False, 'in seven cave'),
                  '[cave-009-B1] Death Mountain - right cave [left chest]': (0xEB39, False, 'in seven cave'),
                  '[cave-009-B1] Death Mountain - right cave [right chest]': (0xEB3C, False, 'in seven cave'),
                  '[cave-012-1F] Death Mountain - left cave]': (0xE9BF, False, 'in spiral cave'),
                  'Ether Tablet': (0x180016, False, 'at a monument'),
                  'Piece of Heart (Spectacle Rock)': (0x180140, False, 'atop a rock'),
                  '[dungeon-L3-1F] Tower of Hera - Freestanding Key': (0x180162, False, 'in Tower of Hera'),
                  '[dungeon-L3-1F] Tower of Hera - Entrance': (0xE9AD, False, 'in Tower of Hera'),
                  '[dungeon-L3-1F] Tower of Hera - Basement': (0xE9E6, False, 'in Tower of Hera'),
                  '[dungeon-L3-1F] Tower of Hera - 4F [small chest]': (0xE9FB, False, 'in Tower of Hera'),
                  '[dungeon-L3-1F] Tower of Hera - Big Chest': (0xE9F8, False, 'in Tower of Hera'),
                  'Moldorm - Heart Container': (0x180152, False, 'with Moldorm'),
                  'Piece of Heart (Pyramid)': (0x180147, False, 'on the pyramid'),
                  'Catfish': (0xEE185, False, 'with a fish'),
                  'Flute Boy': (0x330C7, False, 'with tree boy'),
                  'Piece of Heart (Digging Game)': (0x180148, False, 'underground'),
                  'Bombos Tablet': (0x180017, False, 'at a monument'),
                  '[cave-073] Cave Northeast of Swamp Palace [top chest]': (0xEB1E, False, 'near batman'),
                  '[cave-073] Cave Northeast of Swamp Palace [top middle chest]': (0xEB21, False, 'near batman'),
                  '[cave-073] Cave Northeast of Swamp Palace [bottom middle chest]': (0xEB24, False, 'near batman'),
                  '[cave-073] Cave Northeast of Swamp Palace [bottom chest]': (0xEB27, False, 'near batman'),
                  '[cave-073] Cave Northeast of Swamp Palace [generous guy]': (0x180011, False, 'with batman'),
                  'Piece of Heart (Dark World Blacksmith Pegs)': (0x180006, False, 'alone in a cave'),
                  'Pyramid Fairy [left chest]': (0xE980, False, 'near a fairy'),
                  'Pyramid Fairy [right chest]': (0xE983, False, 'near a fairy'),
                  '[cave-063] Doorless Hut': (0xE9EC, False, 'alone in a home'),
                  '[cave-062] C-Shaped House': (0xE9EF, False, 'alone in a home'),
                  'Piece of Heart (Treasure Chest Game)': (0xEDA8, False, 'as a prize'),
                  'Piece of Heart (Bumper Cave)': (0x180146, False, 'on a ledge'),
                  '[cave-071] Misery Mire West Area [left chest]': (0xEA73, False, 'near a spark'),
                  '[cave-071] Misery Mire West Area [right chest]': (0xEA76, False, 'near a spark'),
                  '[cave-057-1F] Dark World Death Mountain Climb [top chest]': (0xEA7C, False, 'in a connection'),
                  '[cave-057-1F] Dark World Death Mountain Climb [bottom chest]': (0xEA7F, False, 'in a connection'),
                  '[cave-055] Spike Cave': (0xEA8B, False, 'beyond spikes'),
                  '[cave-056] Hookshot Cave [top right chest]': (0xEB51, False, 'across pits'),
                  '[cave-056] Hookshot Cave [top left chest]': (0xEB54, False, 'across pits'),
                  '[cave-056] Hookshot Cave [bottom right chest]': (0xEB5A, False, 'across pits'),
                  '[cave-056] Hookshot Cave [bottom left chest]': (0xEB57, False, 'across pits'),
                  'Piece of Heart (Death Mountain - Floating Island)': (0x180141, False, 'on an island'),
                  '[cave-013] Mimic Cave': (0xE9C5, False, 'beyond Goriyas'),
                  '[dungeon-D2-1F] Swamp Palace - First Room': (0xEA9D, False, 'in Swamp Palace'),
                  '[dungeon-D2-1F] Swamp Palace - Map Room': (0xE986, False, 'in Swamp Palace'),
                  '[dungeon-D2-B1] Swamp Palace - Big Chest': (0xE989, False, 'in Swamp Palace'),
                  '[dungeon-D2-B1] Swamp Palace - South of Hookshot Room': (0xEAA0, False, 'in Swamp Palace'),
                  '[dungeon-D2-B1] Swamp Palace - Big Key Chest': (0xEAA6, False, 'in Swamp Palace'),
                  '[dungeon-D2-B1] Swamp Palace - Compass Chest': (0xEAA3, False, 'in Swamp Palace'),
                  '[dungeon-D2-B2] Swamp Palace - Flooded Room [left chest]': (0xEAA9, False, 'in Swamp Palace'),
                  '[dungeon-D2-B2] Swamp Palace - Flooded Room [right chest]': (0xEAAC, False, 'in Swamp Palace'),
                  '[dungeon-D2-B2] Swamp Palace - Waterfall Room': (0xEAAF, False, 'in Swamp Palace'),
                  'Arrghus - Heart Container': (0x180154, False, 'with Arrghus'),
                  '[dungeon-D4-B1] Thieves Town - Bottom Left of Huge Room [bottom right chest]': (0xEA04, False, 'in Thieves\' Town'),
                  '[dungeon-D4-B1] Thieves Town - Bottom Left of Huge Room [top left chest]': (0xEA01, False, 'in Thieves\' Town'),
                  '[dungeon-D4-B1] Thieves Town - Bottom Right of Huge Room': (0xEA07, False, 'in Thieves\' Town'),
                  '[dungeon-D4-B1] Thieves Town - Top Left of Huge Room': (0xEA0A, False, 'in Thieves\' Town'),
                  '[dungeon-D4-1F] Thieves Town - Room above Boss': (0xEA0D, False, 'in Thieves\' Town'),
                  '[dungeon-D4-B2] Thieves Town - Big Chest': (0xEA10, False, 'in Thieves\' Town'),
                  '[dungeon-D4-B2] Thieves Town - Chest next to Blind': (0xEA13, False, 'in Thieves\' Town'),
                  'Blind - Heart Container': (0x180156, False, 'with Blind'),
                  '[dungeon-D3-B1] Skull Woods - Compass Room': (0xE992, False, 'in Skull Woods'),
                  '[dungeon-D3-B1] Skull Woods - East of Big Chest': (0xE99B, False, 'in Skull Woods'),
                  '[dungeon-D3-B1] Skull Woods - Big Chest': (0xE998, False, 'in Skull Woods'),
                  '[dungeon-D3-B1] Skull Woods - Push Statue Room': (0xE9A1, False, 'in Skull Woods'),
                  '[dungeon-D3-B1] Skull Woods - South of Big Chest': (0xE9C8, False, 'in Skull Woods'),
                  '[dungeon-D3-B1] Skull Woods - Big Key Room': (0xE99E, False, 'in Skull Woods'),
                  '[dungeon-D3-B1] Skull Woods - Final Section Entrance': (0xE9FE, False, 'near Mothula'),
                  'Mothula - Heart Container': (0x180155, False, 'with Mothula'),
                  '[dungeon-D5-B1] Ice Palace - Compass Room': (0xE9D4, False, 'in Ice Palace'),
                  '[dungeon-D5-B4] Ice Palace - Above Big Chest': (0xE995, False, 'in Ice Palace'),
                  '[dungeon-D5-B5] Ice Palace - Big Chest': (0xE9AA, False, 'in Ice Palace'),
                  '[dungeon-D5-B5] Ice Palace - Jellyfish Room': (0xE9E3, False, 'in Ice Palace'),
                  '[dungeon-D5-B3] Ice Palace - Spike Room': (0xE9E0, False, 'in Ice Palace'),
                  '[dungeon-D5-B1] Ice Palace - Big Key Room': (0xE9A4, False, 'in Ice Palace'),
                  '[dungeon-D5-B2] Ice Palace - Map Room': (0xE9DD, False, 'in Ice Palace'),
                  'Kholdstare - Heart Container': (0x180157, False, 'with Kholdstare'),
                  '[dungeon-D6-B1] Misery Mire - Big Chest': (0xEA67, False, 'in Misery Mire'),
                  '[dungeon-D6-B1] Misery Mire - Map Room': (0xEA6A, False, 'in Misery Mire'),
                  '[dungeon-D6-B1] Misery Mire - Hub Room': (0xEA5E, False, 'in Misery Mire'),
                  '[dungeon-D6-B1] Misery Mire - End of Bridge': (0xEA61, False, 'in Misery Mire'),
                  '[dungeon-D6-B1] Misery Mire - Spike Room': (0xE9DA, False, 'in Misery Mire'),
                  '[dungeon-D6-B1] Misery Mire - Compass Room': (0xEA64, False, 'in Misery Mire'),
                  '[dungeon-D6-B1] Misery Mire - Big Key Room': (0xEA6D, False, 'in Misery Mire'),
                  'Vitreous - Heart Container': (0x180158, False, 'with Vitreous'),
                  '[dungeon-D7-1F] Turtle Rock - Compass Room': (0xEA22, False, 'in Turtle Rock'),
                  '[dungeon-D7-1F] Turtle Rock - Map Room [left chest]': (0xEA1C, False, 'in Turtle Rock'),
                  '[dungeon-D7-1F] Turtle Rock - Map Room [right chest]': (0xEA1F, False, 'in Turtle Rock'),
                  '[dungeon-D7-1F] Turtle Rock - Chain Chomp Room': (0xEA16, False, 'in Turtle Rock'),
                  '[dungeon-D7-B1] Turtle Rock - Big Key Room': (0xEA25, False, 'in Turtle Rock'),
                  '[dungeon-D7-B1] Turtle Rock - Big Chest': (0xEA19, False, 'in Turtle Rock'),
                  '[dungeon-D7-B1] Turtle Rock - Roller Switch Room': (0xEA34, False, 'in Turtle Rock'),
                  '[dungeon-D7-B2] Turtle Rock - Eye Bridge Room [bottom left chest]': (0xEA31, False, 'in Turtle Rock'),
                  '[dungeon-D7-B2] Turtle Rock - Eye Bridge Room [bottom right chest]': (0xEA2E, False, 'in Turtle Rock'),
                  '[dungeon-D7-B2] Turtle Rock - Eye Bridge Room [top left chest]': (0xEA2B, False, 'in Turtle Rock'),
                  '[dungeon-D7-B2] Turtle Rock - Eye Bridge Room [top right chest]': (0xEA28, False, 'in Turtle Rock'),
                  'Trinexx - Heart Container': (0x180159, False, 'with Trinexx'),
                  '[dungeon-D1-B1] Dark Palace - Shooter Room': (0xEA5B, False, 'in Palace of Darkness'),
                  '[dungeon-D1-1F] Dark Palace - Jump Room [left chest]': (0xEA3A, False, 'in Palace of Darkness'),
                  '[dungeon-D1-B1] Dark Palace - Turtle Stalfos Room': (0xEA49, False, 'in Palace of Darkness'),
                  '[dungeon-D1-1F] Dark Palace - Big Key Room': (0xEA37, False, 'in Palace of Darkness'),
                  '[dungeon-D1-1F] Dark Palace - Jump Room [right chest]': (0xEA3D, False, 'in Palace of Darkness'),
                  '[dungeon-D1-1F] Dark Palace - Statue Push Room': (0xEA52, False, 'in Palace of Darkness'),
                  '[dungeon-D1-1F] Dark Palace - Compass Room': (0xEA43, False, 'in Palace of Darkness'),
                  '[dungeon-D1-B1] Dark Palace - Dark Room [left chest]': (0xEA4C, False, 'in Palace of Darkness'),
                  '[dungeon-D1-B1] Dark Palace - Dark Room [right chest]': (0xEA4F, False, 'in Palace of Darkness'),
                  '[dungeon-D1-1F] Dark Palace - Maze Room [top chest]': (0xEA55, False, 'in Palace of Darkness'),
                  '[dungeon-D1-1F] Dark Palace - Maze Room [bottom chest]': (0xEA58, False, 'in Palace of Darkness'),
                  '[dungeon-D1-1F] Dark Palace - Big Chest': (0xEA40, False, 'in Palace of Darkness'),
                  '[dungeon-D1-1F] Dark Palace - Spike Statue Room': (0xEA46, False, 'in Palace of Darkness'),
                  'Helmasaur - Heart Container': (0x180153, False, 'with Helmasaur King'),
                  '[dungeon-A2-1F] Ganons Tower - Torch': (0x180161, False, 'on my torch'),
                  '[dungeon-A2-1F] Ganons Tower - Right Staircase [left chest]': (0xEAD9, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Right Staircase [right chest]': (0xEADC, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Tile Room': (0xEAE2, False, 'with my tiles'),
                  '[dungeon-A2-1F] Ganons Tower - Compass Room [top left chest]': (0xEAE5, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Compass Room [top right chest]': (0xEAE8, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Compass Room [bottom left chest]': (0xEAEB, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Compass Room [bottom right chest]': (0xEAEE, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - North of Hookshot Room [top left chest]': (0xEAB8, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - North of Hookshot Room [top right chest]': (0xEABB, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - North of Hookshot Room [bottom left chest]': (0xEABE, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - North of Hookshot Room [bottom right chest]': (0xEAC1, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Map Room': (0xEAD3, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Firesnake Room': (0xEAD0, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Teleport Room [top left chest]': (0xEAC4, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Teleport Room [top right chest]': (0xEAC7, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Teleport Room [bottom left chest]': (0xEACA, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Teleport Room [bottom right chest]': (0xEACD, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - above Armos': (0xEADF, False, 'in My Tower'),
                  '[dungeon-A2-1F] Ganons Tower - Big Chest': (0xEAD6, False, 'in my big chest'),
                  '[dungeon-A2-B1] Ganons Tower - Armos Room [left chest]': (0xEAF4, False, 'beyond my Armos'),
                  '[dungeon-A2-B1] Ganons Tower - Armos Room [right chest]': (0xEAF7, False, 'beyond my Armos'),
                  '[dungeon-A2-B1] Ganons Tower - Armos Room [bottom chest]': (0xEAF1, False, 'beyond my Armos'),
                  '[dungeon-A2-6F] Ganons Tower - Mini Helmasaur Room [left chest]': (0xEAFD, False, 'atop My Tower'),
                  '[dungeon-A2-6F] Ganons Tower - Mini Helmasaur Room [right chest]': (0xEB00, False, 'atop My Tower'),
                  '[dungeon-A2-6F] Ganons Tower - Room before Moldorm': (0xEB03, False, 'atop My Tower'),
                  '[dungeon-A2-6F] Ganons Tower - Moldorm Room': (0xEB06, False, 'atop My Tower'),
                  'Ganon': (None, False, 'from me'),
                  'Agahnim 1': (None, False, 'from my wizardry from'),
                  'Agahnim 2': (None, False, 'from my wizardry from'),
                  'Armos - Pendant': ([0x1209D, 0x53EF8, 0x53EF9, 0x180052, 0x18007C, 0xC6FE], True, 'Eastern Palace'),
                  'Lanmolas - Pendant': ([0x1209E, 0x53F1C, 0x53F1D, 0x180053, 0x180078, 0xC6FF], True, 'Desert Palace'),
                  'Moldorm - Pendant': ([0x120A5, 0x53F0A, 0x53F0B, 0x18005A, 0x18007A, 0xC706], True, 'Tower of Hera'),
                  'Helmasaur - Crystal': ([0x120A1, 0x53F00, 0x53F01, 0x180056, 0x18007D, 0xC702], True, 'Palace of Darkness'),
                  'Arrghus - Crystal': ([0x120A0, 0x53F6C, 0x53F6D, 0x180055, 0x180071, 0xC701], True, 'Swamp Palace'),
                  'Blind - Crystal': ([0x120A6, 0x53F36, 0x53F37, 0x18005B, 0x180077, 0xC707], True, 'Thieves\' Town'),
                  'Mothula - Crystal': ([0x120A3, 0x53F12, 0x53F13, 0x180058, 0x18007B, 0xC704], True, 'Skull Woods'),
                  'Kholdstare - Crystal': ([0x120A4, 0x53F5A, 0x53F5B, 0x180059, 0x180073, 0xC705], True, 'Ice Palace'),
                  'Vitreous - Crystal': ([0x120A2, 0x53F48, 0x53F49, 0x180057, 0x180075, 0xC703], True, 'Misery Mire'),
                  'Trinexx - Crystal': ([0x120A7, 0x53F24, 0x53F25, 0x18005C, 0x180079, 0xC708], True, 'Turtle Rock')}
