line-length = 120
target-version = "py310"

[lint]
select = ["C", "E", "F", "R", "W", "I", "N", "Q", "UP", "RUF", "ISC", "T20"]
ignore = ["C901"]  # Author disagrees with forcing a specific amount of branch complexity in functions
