<ConfettiView>:
    size_hint: None, None
    pos_hint: {"center_x": 0.5, "center_y": 0.5}
    spacing: 0
    padding: 0

<APQuestGrid>:
    cols: 12
    rows: 11
    spacing: 0
    padding: 0
    size_hint: None, None
    pos_hint: {"center_x": 0.5, "center_y": 0.5}

<APQuestGameView>:
    RelativeLayout:
        id: game_container

<VolumeSliderView>:
    BoxLayout:
        orientation: horizontal
