class AnimalProduct:
    any_egg = "Any Egg"
    chicken_egg = "Chicken Egg"
    egg = "Egg"
    brown_egg = "Egg (Brown)"
    large_egg = "Large Egg"
    large_brown_egg = "Large Egg (Brown)"
    milk = "Milk"
    large_milk = "Large Milk"
    cow_milk = "Cow Milk"
    wool = "Wool"
    goat_milk = "Goat Milk"
    large_goat_milk = "Large Goat Milk"
    duck_egg = "Duck Egg"
    duck_feather = "Duck Feather"
    void_egg = "Void Egg"
    truffle = "Truffle"
    rabbit_foot = "Rabbit's Foot"
    roe = "Roe"
    sturgeon_roe = "Sturgeon Roe"
    ostrich_egg = "Ostrich Egg"
    dinosaur_egg = "Dinosaur Egg"
    squid_ink = "Squid Ink"

