class Fish:
    albacore = "Albacore"
    angler = "Angler"
    any = "Any Fish"
    blobfish = "Blobfish"
    blue_discus = "Blue Discus"
    bream = "Bream"
    carp = "Carp"
    catfish = "Catfish"
    crab = "Crab"
    crayfish = "Crayfish"
    crimsonfish = "Crimsonfish"
    dorado = "Dorado"
    eel = "Eel"
    flounder = "Flounder"
    glacierfish = "Glacierfish"
    glacierfish_jr = "Glacierfish Jr."
    largemouth_bass = "Largemouth Bass"
    lava_eel = "Lava Eel"
    legend = "Legend"
    legend_ii = "Legend II"
    lionfish = "Lionfish"
    lobster = "Lobster"
    midnight_carp = "Midnight Carp"
    ms_angler = "Ms. Angler"
    mussel = "Mussel"
    mussel_node = "Mussel Node"
    mutant_carp = "Mutant Carp"
    octopus = "Octopus"
    oyster = "Oyster"
    periwinkle = "Periwinkle"
    pufferfish = "Pufferfish"
    radioactive_carp = "Radioactive Carp"
    rainbow_trout = "Rainbow Trout"
    salmon = "Salmon"
    sardine = "Sardine"
    sea_cucumber = "Sea Cucumber"
    shrimp = "Shrimp"
    smallmouth_bass = "Smallmouth Bass"
    snail = "Snail"
    son_of_crimsonfish = "Son of Crimsonfish"
    spookfish = "Spook Fish"
    squid = "Squid"
    stingray = "Stingray"
    sturgeon = "Sturgeon"
    sunfish = "Sunfish"
    tuna = "Tuna"
    void_salmon = "Void Salmon"


class WaterItem:
    seaweed = "Seaweed"
    green_algae = "Green Algae"
    white_algae = "White Algae"
    clam = "Clam"
    cockle = "Cockle"
    coral = "Coral"
    nautilus_shell = "Nautilus Shell"
    sea_urchin = "Sea Urchin"


class Trash:
    driftwood = "Driftwood"
    trash = "Trash"
    broken_cd = "Broken CD"
    broken_glasses = "Broken Glasses"
    joja_cola = "Joja Cola"
    soggy_newspaper = "Soggy Newspaper"


class WaterChest:
    fishing_chest = "Fishing Chest"
    treasure = "Treasure Chest"


class SVEFish:
    baby_lunaloo = "Baby Lunaloo"
    bonefish = "Bonefish"
    bull_trout = "Bull Trout"
    butterfish = "Butterfish"
    clownfish = "Clownfish"
    daggerfish = "Daggerfish"
    frog = "Frog"
    gemfish = "Gemfish"
    goldenfish = "Goldenfish"
    grass_carp = "Grass Carp"
    king_salmon = "King Salmon"
    kittyfish = "Kittyfish"
    lunaloo = "Lunaloo"
    meteor_carp = "Meteor Carp"
    minnow = "Minnow"
    puppyfish = "Puppyfish"
    radioactive_bass = "Radioactive Bass"
    seahorse = "Seahorse"
    shiny_lunaloo = "Shiny Lunaloo"
    snatcher_worm = "Snatcher Worm"
    starfish = "Starfish"
    torpedo_trout = "Torpedo Trout"
    undeadfish = "Undeadfish"
    void_eel = "Void Eel"
    water_grub = "Water Grub"
    sea_sponge = "Sea Sponge"
    dulse_seaweed = "Dulse Seaweed"




