class Fish:
    albacore = "Albacore"
    angler = "Angler"
    any = "Any Fish"
    blobfish = "Blobfish"
    blue_discus = "Blue Discus"
    bream = "Bream"
    carp = "Carp"
    catfish = "Catfish"
    crab = "Crab"
    crayfish = "Crayfish"
    crimsonfish = "Crimsonfish"
    dorado = "Dorado"
    eel = "Eel"
    glacierfish = "Glacierfish"
    glacierfish_jr = "Glacierfish Jr."
    largemouth_bass = "Largemouth Bass"
    lava_eel = "Lava Eel"
    legend = "Legend"
    legend_ii = "Legend II"
    lionfish = "Lionfish"
    lobster = "Lobster"
    ms_angler = "Ms. Angler"
    mussel = "Mussel"
    mussel_node = "Mussel Node"
    mutant_carp = "Mutant Carp"
    octopus = "Octopus"
    oyster = "Oyster"
    periwinkle = "Periwinkle"
    pufferfish = "Pufferfish"
    radioactive_carp = "Radioactive Carp"
    salmon = "Salmon"
    sardine = "Sardine"
    shrimp = "Shrimp"
    smallmouth_bass = "Smallmouth Bass"
    snail = "Snail"
    son_of_crimsonfish = "Son of Crimsonfish"
    spookfish = "Spook Fish"
    squid = "Squid"
    stingray = "Stingray"
    sturgeon = "Sturgeon"
    sunfish = "Sunfish"
    tuna = "Tuna"
    void_salmon = "Void Salmon"


class WaterItem:
    seaweed = "Seaweed"
    green_algae = "Green Algae"
    white_algae = "White Algae"
    clam = "Clam"
    cockle = "Cockle"
    coral = "Coral"
    nautilus_shell = "Nautilus Shell"
    sea_urchin = "Sea Urchin"


class Trash:
    driftwood = "Driftwood"
    trash = "Trash"
    broken_cd = "Broken CD"
    broken_glasses = "Broken Glasses"
    joja_cola = "Joja Cola"
    soggy_newspaper = "Soggy Newspaper"




