class Goal:
    grandpa_evaluation = "Succeed Grandpa's Evaluation"
    community_center = "Complete Community Center"
    bottom_of_the_mines = "Reach the Bottom of The Mines"
    cryptic_note = "Complete Quest Cryptic Note"
    master_angler = "Catch Every Fish"
    complete_museum = "Complete the Museum Collection"
    full_house = "Full House"
    greatest_walnut_hunter = "Greatest Walnut Hunter"
    protector_of_the_valley = "Protector of the Valley"
    full_shipment = "Full Shipment"
    gourmet_chef = "Gourmet Chef"
    craft_master = "Craft Master"
    legend = "Legend"
    mystery_of_the_stardrops = "Mystery of the Stardrops"
    allsanity = "Allsanity"
    perfection = "Perfection"
