class Machine:
    bee_house = "Bee House"
    cask = "Cask"
    charcoal_kiln = "Charcoal Kiln"
    cheese_press = "Cheese Press"
    furnace = "Furnace"
    geode_crusher = "Geode Crusher"
    keg = "Keg"
    lightning_rod = "Lightning Rod"
    loom = "Loom"
    mayonnaise_machine = "Mayonnaise Machine"
    oil_maker = "Oil Maker"
    preserves_jar = "Preserves Jar"
    recycling_machine = "Recycling Machine"
    seed_maker = "Seed Maker"
    solar_panel = "Solar Panel"
    tapper = "Tapper"
    worm_bin = "Worm Bin"
    coffee_maker = "Coffee Maker"
    crab_pot = "Crab Pot"
    ostrich_incubator = "Ostrich Incubator"

