class Meal:
    blueberry_tart = "Blueberry Tart"
    bread = "Bread"
    fiddlehead_risotto = "Fiddlehead Risotto"
    complete_breakfast = "Complete Breakfast"
    fried_egg = "Fried Egg"
    hashbrowns = "Hashbrowns"
    pancakes = "Pancakes"
    ginger_ale = "Ginger Ale"
    ice_cream = "Ice Cream"
    maki_roll = "Maki Roll"
