class Region:
    menu = "Menu"
    stardew_valley = "Stardew Valley"
    farm_house = "Farmhouse"
    cellar = "Cellar"
    farm = "Farm"
    town = "Town"
    beach = "Beach"
    mountain = "Mountain"
    forest = "Forest"
    bus_stop = "Bus Stop"
    backwoods = "Backwoods"
    bus_tunnel = "Bus Tunnel"
    railroad = "Railroad"
    secret_woods = "Secret Woods"
    community_center = "Community Center"
    pantry = "Pantry"
    crafts_room = "Crafts Room"
    fish_tank = "Fish Tank"
    boiler_room = "Boiler Room"
    vault = "Vault"
    bulletin_board = "Bulletin Board"
    desert = "Desert"
    oasis = "Oasis"
    casino = "Casino"
    mines = "The Mines"
    mines_dwarf_shop = "Mines Dwarf Shop"
    skull_cavern_entrance = "Skull Cavern Entrance"
    skull_cavern = "Skull Cavern"
    sewer = "Sewer"
    mutant_bug_lair = "Mutant Bug Lair"
    witch_swamp = "Witch's Swamp"
    witch_hut = "Witch's Hut"
    island_south = "Island South"
    island_resort = "Island Resort"
    island_south_east = "Island Southeast"
    pirate_cove = "Pirate Cove"
    island_east = "Island East"
    island_north = "Island North"
    island_shrine = "Island Shrine"
    leo_hut = "Leo's Hut"
    leo_treehouse = "Leo's TreeHouse"
    island_farmhouse = "Island Farmhouse"
    dig_site = "Dig Site"
    professor_snail_cave = "Professor Snail Cave"
    field_office = "Field Office"
    volcano = "Volcano Entrance"
    volcano_secret_beach = "Volcano Secret Beach"
    island_trader = "Island Trader"
    volcano_floor_5 = "Volcano - Floor 5"
    volcano_dwarf_shop = "Volcano Dwarf Shop"
    volcano_floor_10 = "Volcano - Floor 10"
    island_west = "Island West"
    gourmand_frog_cave = "Gourmand Frog Cave"
    colored_crystals_cave = "Colored Crystals Cave"
    shipwreck = "Shipwreck"
    qi_walnut_room = "Qi's Walnut Room"
    skull_cavern_25 = "Skull Cavern Floor 25"
    skull_cavern_50 = "Skull Cavern Floor 50"
    skull_cavern_75 = "Skull Cavern Floor 75"
    skull_cavern_100 = "Skull Cavern Floor 100"
    skull_cavern_125 = "Skull Cavern Floor 125"
    skull_cavern_150 = "Skull Cavern Floor 150"
    skull_cavern_175 = "Skull Cavern Floor 175"
    skull_cavern_200 = "Skull Cavern Floor 200"
    hospital = "Hospital"
    carpenter = "Carpenter Shop"
    alex_house = "Alex's House"
    elliott_house = "Elliott's House"
    ranch = "Marnie's Ranch"
    traveling_cart = "Traveling Cart"
    farm_cave = "Farmcave"
    greenhouse = "Greenhouse"
    tunnel_entrance = "Tunnel Entrance"
    leah_house = "Leah's Cottage"
    wizard_tower = "Wizard Tower"
    wizard_basement = "Wizard Basement"
    tent = "Tent"
    maru_room = "Maru's Room"
    sebastian_room = "Sebastian's Room"
    adventurer_guild = "Adventurer's Guild"
    quarry = "Quarry"
    quarry_mine_entrance = "Quarry Mine Entrance"
    quarry_mine = "Quarry Mine"
    witch_warp_cave = "Witch Warp Cave"
    harvey_room = "Harvey's Room"
    pierre_store = "Pierre's General Store"
    sunroom = "Sunroom"
    saloon = "Saloon"
    blacksmith = "Clint's Blacksmith"
    trailer = "Trailer"
    museum = "Museum"
    mayor_house = "Mayor's Manor"
    haley_house = "Haley's House"
    sam_house = "Sam's House"
    jojamart = "JojaMart"
    fish_shop = "Willy's Fish Shop"
    boat_tunnel = "Boat Tunnel"
    tide_pools = "Tide Pools"
    bathhouse_entrance = "Bathhouse Entrance"
    locker_room = "Locker Room"
    public_bath = "Public Bath"
    jotpk_world_1 = "JotPK World 1"
    jotpk_world_2 = "JotPK World 2"
    jotpk_world_3 = "JotPK World 3"
    junimo_kart_1 = "Junimo Kart 1"
    junimo_kart_2 = "Junimo Kart 2"
    junimo_kart_3 = "Junimo Kart 3"
    mines_floor_5 = "The Mines - Floor 5"
    mines_floor_10 = "The Mines - Floor 10"
    mines_floor_15 = "The Mines - Floor 15"
    mines_floor_20 = "The Mines - Floor 20"
    mines_floor_25 = "The Mines - Floor 25"
    mines_floor_30 = "The Mines - Floor 30"
    mines_floor_35 = "The Mines - Floor 35"
    mines_floor_40 = "The Mines - Floor 40"
    mines_floor_45 = "The Mines - Floor 45"
    mines_floor_50 = "The Mines - Floor 50"
    mines_floor_55 = "The Mines - Floor 55"
    mines_floor_60 = "The Mines - Floor 60"
    mines_floor_65 = "The Mines - Floor 65"
    mines_floor_70 = "The Mines - Floor 70"
    mines_floor_75 = "The Mines - Floor 75"
    mines_floor_80 = "The Mines - Floor 80"
    mines_floor_85 = "The Mines - Floor 85"
    mines_floor_90 = "The Mines - Floor 90"
    mines_floor_95 = "The Mines - Floor 95"
    mines_floor_100 = "The Mines - Floor 100"
    mines_floor_105 = "The Mines - Floor 105"
    mines_floor_110 = "The Mines - Floor 110"
    mines_floor_115 = "The Mines - Floor 115"
    mines_floor_120 = "The Mines - Floor 120"


class DeepWoodsRegion:
    main_lichtung = "Entrance to the Deep Woods"
    abandoned_home = "Abandoned Home in Deep Woods"
    woods_obelisk_menu = "Woods Obelisk Menu"
    floor_10 = "The Deep Woods Depth 10"
    floor_20 = "The Deep Woods Depth 20"
    floor_30 = "The Deep Woods Depth 30"
    floor_40 = "The Deep Woods Depth 40"
    floor_50 = "The Deep Woods Depth 50"
    floor_60 = "The Deep Woods Depth 60"
    floor_70 = "The Deep Woods Depth 70"
    floor_80 = "The Deep Woods Depth 80"
    floor_90 = "The Deep Woods Depth 90"
    floor_100 = "The Deep Woods Depth 100"


class EugeneRegion:
    eugene_garden = "Eugene's Garden"
    eugene_bedroom = "Eugene's Bedroom"


class MagicRegion:
    altar = "Magic Altar"


class JasperRegion:
    jasper_bedroom = "Jasper's Bedroom"


class AlecRegion:
    pet_store = "Alec's Pet Shop"
    alec_bedroom = "Alec's Bedroom"


class YobaRegion:
    yoba_clearing = "Yoba's Clearing"


class JunaRegion:
    juna_cave = "Juna's Cave"


class AyeishaRegion:
    mail_van = "Ayeisha's Mail Van"


class RileyRegion:
    riley_house = "Riley's House"
