class Wallet:
    metal_detector = "Traveling Merchant Metal Detector"
    iridium_snake_milk = "Iridium Snake Milk"
    bears_knowledge = "Bear's Knowledge"
    dwarvish_translation_guide = "Dwarvish Translation Guide"
    magnifying_glass = "Magnifying Glass"
    rusty_key = "Rusty Key"
    skull_key = "Skull Key"
    dark_talisman = "Dark Talisman"
    club_card = "Club Card"
    mastery_of_the_five_ways = "Mastery Of The Five Ways"
    key_to_the_town = "Key To The Town"
    magic_ink = "Magic Ink"
    mens_locker_key = "Men's Locker Key"
    womens_locker_key = "Women's Locker Key"
