# APWorld for Heretic
#
# This file is automatically generated by ap_gen_tool version 2.0.
# For more information: https://github.com/ArchipelagoDoom/ap_gen_tool

# Options docstrings may exceed the line length limit.
# ruff: noqa: E501

from dataclasses import dataclass

import Options as BaseOptions
from worlds._id1common import options as id1Options  # noqa: N812


class GoalNumLevels(BaseOptions.Range):
    """
    If 'Complete Some Levels' or 'Complete Random Levels' are chosen as the goal, this is how many levels must be completed.
    """
    display_name = "Goal: Number of Levels"
    range_start = 1
    range_end = 47
    default = 47


class GoalSpecificLevels(BaseOptions.OptionSet):
    """
    If 'Complete Specific Levels' is chosen as the goal, all levels chosen here must be completed.
    """
    display_name = "Goal: Specific Levels"
    valid_keys = (
        "The Docks (E1M1)",
        "The Dungeons (E1M2)",
        "The Gatehouse (E1M3)",
        "The Guard Tower (E1M4)",
        "The Citadel (E1M5)",
        "The Cathedral (E1M6)",
        "The Crypts (E1M7)",
        "Hell's Maw (E1M8)",
        "The Graveyard (E1M9)",
        "The Crater (E2M1)",
        "The Lava Pits (E2M2)",
        "The River of Fire (E2M3)",
        "The Ice Grotto (E2M4)",
        "The Catacombs (E2M5)",
        "The Labyrinth (E2M6)",
        "The Great Hall (E2M7)",
        "The Portals of Chaos (E2M8)",
        "The Glacier (E2M9)",
        "The Storehouse (E3M1)",
        "The Cesspool (E3M2)",
        "The Confluence (E3M3)",
        "The Azure Fortress (E3M4)",
        "The Ophidian Lair (E3M5)",
        "The Halls of Fear (E3M6)",
        "The Chasm (E3M7)",
        "D'Sparil's Keep (E3M8)",
        "The Aquifer (E3M9)",
        "Catafalque (E4M1)",
        "Blockhouse (E4M2)",
        "Ambulatory (E4M3)",
        "Sepulcher (E4M4)",
        "Great Stair (E4M5)",
        "Halls of the Apostate (E4M6)",
        "Ramparts of Perdition (E4M7)",
        "Shattered Bridge (E4M8)",
        "Mausoleum (E4M9)",
        "Ochre Cliffs (E5M1)",
        "Rapids (E5M2)",
        "Quay (E5M3)",
        "Courtyard (E5M4)",
        "Hydratyr (E5M5)",
        "Colonnade (E5M6)",
        "Foetid Manse (E5M7)",
        "Field of Judgement (E5M8)",
        "Skein of D'Sparil (E5M9)",
        "Raven's Lair (E6M1)",
        "The Water Shrine (E6M2)",
    )
    default = frozenset({
        "Hell's Maw (E1M8)",
        "The Portals of Chaos (E2M8)",
        "D'Sparil's Keep (E3M8)",
        "Shattered Bridge (E4M8)",
        "Field of Judgement (E5M8)",
    })


class Episode1(id1Options.DefaultEpisode):
    """
    City of the Damned.

    This episode includes the following levels:

    - The Docks (E1M1)
    - The Dungeons (E1M2)
    - The Gatehouse (E1M3)
    - The Guard Tower (E1M4)
    - The Citadel (E1M5)
    - The Cathedral (E1M6)
    - The Crypts (E1M7)
    - Hell's Maw (E1M8)
    - The Graveyard (E1M9)
    """
    display_name = "Episode 1"


class Episode2(id1Options.DefaultEpisode):
    """
    Hell's Maw.

    This episode includes the following levels:

    - The Crater (E2M1)
    - The Lava Pits (E2M2)
    - The River of Fire (E2M3)
    - The Ice Grotto (E2M4)
    - The Catacombs (E2M5)
    - The Labyrinth (E2M6)
    - The Great Hall (E2M7)
    - The Portals of Chaos (E2M8)
    - The Glacier (E2M9)
    """
    display_name = "Episode 2"


class Episode3(id1Options.DefaultEpisode):
    """
    The Dome of D'Sparil.

    This episode includes the following levels:

    - The Storehouse (E3M1)
    - The Cesspool (E3M2)
    - The Confluence (E3M3)
    - The Azure Fortress (E3M4)
    - The Ophidian Lair (E3M5)
    - The Halls of Fear (E3M6)
    - The Chasm (E3M7)
    - D'Sparil's Keep (E3M8)
    - The Aquifer (E3M9)
    """
    display_name = "Episode 3"


class Episode4(id1Options.Episode):
    """
    The Ossuary.

    This episode includes the following levels:

    - Catafalque (E4M1)
    - Blockhouse (E4M2)
    - Ambulatory (E4M3)
    - Sepulcher (E4M4)
    - Great Stair (E4M5)
    - Halls of the Apostate (E4M6)
    - Ramparts of Perdition (E4M7)
    - Shattered Bridge (E4M8)
    - Mausoleum (E4M9)
    """
    display_name = "Episode 4"


class Episode5(id1Options.Episode):
    """
    The Stagnant Demesne.

    This episode includes the following levels:

    - Ochre Cliffs (E5M1)
    - Rapids (E5M2)
    - Quay (E5M3)
    - Courtyard (E5M4)
    - Hydratyr (E5M5)
    - Colonnade (E5M6)
    - Foetid Manse (E5M7)
    - Field of Judgement (E5M8)
    - Skein of D'Sparil (E5M9)
    """
    display_name = "Episode 5"


class Episode6(id1Options.MinorEpisode):
    """
    Fate's Path.

    This is a minor episode. Another episode must be played alongside this one.
    This episode includes the following levels:

    - Raven's Lair (E6M1)
    - The Water Shrine (E6M2)
    """
    display_name = "Episode 6"


class MaxAmmoWandCrystals(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Wand Crystals.

    Setting this below the default of 100 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Wand Crystals"
    random_start = 100
    range_start = 10
    range_end = 999
    default = 100


class MaxAmmoEtherealArrows(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Ethereal Arrows.

    Setting this below the default of 50 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Ethereal Arrows"
    random_start = 50
    range_start = 5
    range_end = 999
    default = 50


class MaxAmmoClawOrbs(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Claw Orbs.

    Setting this below the default of 200 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Claw Orbs"
    random_start = 200
    range_start = 20
    range_end = 999
    default = 200


class MaxAmmoRunes(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Runes.

    Setting this below the default of 200 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Runes"
    random_start = 200
    range_start = 20
    range_end = 999
    default = 200


class MaxAmmoFlameOrbs(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Flame Orbs.

    Setting this below the default of 20 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Flame Orbs"
    random_start = 20
    range_start = 2
    range_end = 999
    default = 20


class MaxAmmoMaceSpheres(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Mace Spheres.

    Setting this below the default of 150 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Mace Spheres"
    random_start = 150
    range_start = 15
    range_end = 999
    default = 150


class AddedAmmoWandCrystals(BaseOptions.Range):
    """
    Set how much capacity for Wand Crystals will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Wand Crystals"
    range_start = 10
    range_end = 999
    default = 100


class AddedAmmoEtherealArrows(BaseOptions.Range):
    """
    Set how much capacity for Ethereal Arrows will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Ethereal Arrows"
    range_start = 5
    range_end = 999
    default = 50


class AddedAmmoClawOrbs(BaseOptions.Range):
    """
    Set how much capacity for Claw Orbs will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Claw Orbs"
    range_start = 20
    range_end = 999
    default = 200


class AddedAmmoRunes(BaseOptions.Range):
    """
    Set how much capacity for Runes will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Runes"
    range_start = 20
    range_end = 999
    default = 200


class AddedAmmoFlameOrbs(BaseOptions.Range):
    """
    Set how much capacity for Flame Orbs will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Flame Orbs"
    range_start = 2
    range_end = 999
    default = 20


class AddedAmmoMaceSpheres(BaseOptions.Range):
    """
    Set how much capacity for Mace Spheres will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Mace Spheres"
    range_start = 15
    range_end = 999
    default = 150


@dataclass
class HereticOptions(id1Options.id1CommonOptions):
    goal_num_levels: GoalNumLevels  # type: ignore[assignment]
    goal_specific_levels: GoalSpecificLevels  # type: ignore[assignment]
    episode1: Episode1
    episode2: Episode2
    episode3: Episode3
    episode4: Episode4
    episode5: Episode5
    episode6: Episode6
    flip_levels: BaseOptions.Removed  # type: ignore[assignment]
    check_sanity: id1Options.CheckSanity
    difficulty: id1Options.DifficultyHeretic  # type: ignore[assignment]
    start_with_map_scrolls: id1Options.StartWithMapScrolls
    split_bag_of_holding: id1Options.SplitBagOfHolding
    bag_of_holding_count: id1Options.BagOfHoldingCount
    max_ammo_wand_crystals: MaxAmmoWandCrystals
    max_ammo_ethereal_arrows: MaxAmmoEtherealArrows
    max_ammo_claw_orbs: MaxAmmoClawOrbs
    max_ammo_runes: MaxAmmoRunes
    max_ammo_flame_orbs: MaxAmmoFlameOrbs
    max_ammo_mace_spheres: MaxAmmoMaceSpheres
    added_ammo_wand_crystals: AddedAmmoWandCrystals
    added_ammo_ethereal_arrows: AddedAmmoEtherealArrows
    added_ammo_claw_orbs: AddedAmmoClawOrbs
    added_ammo_runes: AddedAmmoRunes
    added_ammo_flame_orbs: AddedAmmoFlameOrbs
    added_ammo_mace_spheres: AddedAmmoMaceSpheres


HereticOptionGroups = [
    BaseOptions.OptionGroup("Episodes to Play", [
        Episode1,
        Episode2,
        Episode3,
        Episode4,
        Episode5,
        Episode6,
    ]),
    BaseOptions.OptionGroup("Goal Options", [
        id1Options.Goal,
        GoalNumLevels,
        GoalSpecificLevels,
    ]),
    BaseOptions.OptionGroup("Difficulty Options", [
        id1Options.DifficultyHeretic,
        id1Options.TrickDifficulty,
        id1Options.AllowDeathLogic,
        id1Options.ResetLevelOnDeath,
        BaseOptions.DeathLink,
    ]),
    BaseOptions.OptionGroup("Randomizer Options", [
        BaseOptions.ProgressionBalancing,
        BaseOptions.Accessibility,
        id1Options.CheckSanity,
        id1Options.RandomMonsters,
        id1Options.RandomPickups,
        id1Options.RandomMusic,
        BaseOptions.Removed,
        id1Options.StartWithMapScrolls,
        id1Options.SplitBagOfHolding,
        id1Options.BagOfHoldingCount,
    ]),
    BaseOptions.OptionGroup("Ammo Capacity", [
        MaxAmmoWandCrystals,
        MaxAmmoEtherealArrows,
        MaxAmmoClawOrbs,
        MaxAmmoRunes,
        MaxAmmoFlameOrbs,
        MaxAmmoMaceSpheres,
        AddedAmmoWandCrystals,
        AddedAmmoEtherealArrows,
        AddedAmmoClawOrbs,
        AddedAmmoRunes,
        AddedAmmoFlameOrbs,
        AddedAmmoMaceSpheres,
    ]),
]

