"""
Annotations to add to item names sent to the in-game message panel
"""
from . import item_names

ITEM_NAME_ANNOTATIONS = {
    item_names.MARINE:           "(Barracks)",
    item_names.MEDIC:            "(Barracks)",
    item_names.FIREBAT:          "(Barracks)",
    item_names.MARAUDER:         "(Barracks)",
    item_names.REAPER:           "(Barracks)",
    item_names.HELLION:          "(Factory)",
    item_names.VULTURE:          "(Factory)",
    item_names.GOLIATH:          "(Factory)",
    item_names.DIAMONDBACK:      "(Factory)",
    item_names.SIEGE_TANK:       "(Factory)",
    item_names.MEDIVAC:          "(Starport)",
    item_names.WRAITH:           "(Starport)",
    item_names.VIKING:           "(Starport)",
    item_names.BANSHEE:          "(Starport)",
    item_names.BATTLECRUISER:    "(Starport)",
    item_names.GHOST:            "(Barracks)",
    item_names.SPECTRE:          "(Barracks)",
    item_names.THOR:             "(Factory)",
    item_names.RAVEN:            "(Starport)",
    item_names.SCIENCE_VESSEL:   "(Starport)",
    item_names.PREDATOR:         "(Factory)",
    item_names.HERCULES:         "(Starport)",

    item_names.HERC:             "(Barracks)",
    item_names.DOMINION_TROOPER: "(Barracks)",
    item_names.WIDOW_MINE:       "(Factory)",
    item_names.CYCLONE:          "(Factory)",
    item_names.WARHOUND:         "(Factory)",
    item_names.LIBERATOR:        "(Starport)",
    item_names.VALKYRIE:         "(Starport)",

    item_names.SON_OF_KORHAL:         "(Elite Barracks)",
    item_names.AEGIS_GUARD:           "(Elite Barracks)",
    item_names.FIELD_RESPONSE_THETA:  "(Elite Barracks)",
    item_names.EMPERORS_SHADOW:       "(Elite Barracks)",
    item_names.BULWARK_COMPANY:       "(Elite Factory)",
    item_names.SHOCK_DIVISION:        "(Elite Factory)",
    item_names.BLACKHAMMER:           "(Elite Factory)",
    item_names.SKY_FURY:              "(Elite Starport)",
    item_names.NIGHT_HAWK:            "(Elite Starport)",
    item_names.NIGHT_WOLF:            "(Elite Starport)",
    item_names.EMPERORS_GUARDIAN:     "(Elite Starport)",
    item_names.PRIDE_OF_AUGUSTRGRAD:  "(Elite Starport)",

    item_names.WAR_PIGS:              "(Terran Mercenary)",
    item_names.DEVIL_DOGS:            "(Terran Mercenary)",
    item_names.HAMMER_SECURITIES:     "(Terran Mercenary)",
    item_names.SPARTAN_COMPANY:       "(Terran Mercenary)",
    item_names.SIEGE_BREAKERS:        "(Terran Mercenary)",
    item_names.HELS_ANGELS:           "(Terran Mercenary)",
    item_names.DUSK_WINGS:            "(Terran Mercenary)",
    item_names.JACKSONS_REVENGE:      "(Terran Mercenary)",
    item_names.SKIBIS_ANGELS:         "(Terran Mercenary)",
    item_names.DEATH_HEADS:           "(Terran Mercenary)",
    item_names.WINGED_NIGHTMARES:     "(Terran Mercenary)",
    item_names.MIDNIGHT_RIDERS:       "(Terran Mercenary)",
    item_names.BRYNHILDS:             "(Terran Mercenary)",
    item_names.JOTUN:                 "(Terran Mercenary)",

    item_names.BUNKER:                "(Terran Building)",
    item_names.MISSILE_TURRET:        "(Terran Building)",
    item_names.SENSOR_TOWER:          "(Terran Building)",
    item_names.PLANETARY_FORTRESS:    "(Terran Building)",
    item_names.PERDITION_TURRET:      "(Terran Building)",
    item_names.DEVASTATOR_TURRET:     "(Terran Building)",
    item_names.PSI_DISRUPTER:         "(Terran Building)",
    item_names.HIVE_MIND_EMULATOR:    "(Terran Building)",

    item_names.ZERGLING:             "(Larva)",
    item_names.SWARM_QUEEN:          "(Hatchery)",
    item_names.ROACH:                "(Larva)",
    item_names.HYDRALISK:            "(Larva)",
    item_names.ABERRATION:           "(Larva)",
    item_names.MUTALISK:             "(Larva)",
    item_names.SWARM_HOST:           "(Larva)",
    item_names.INFESTOR:             "(Larva)",
    item_names.ULTRALISK:            "(Larva)",
    item_names.PYGALISK:             "(Larva)",
    item_names.CORRUPTOR:            "(Larva)",
    item_names.SCOURGE:              "(Larva)",
    item_names.BROOD_QUEEN:          "(Larva)",
    item_names.DEFILER:              "(Larva)",
    item_names.INFESTED_MARINE:      "(Infested Barracks)",
    item_names.INFESTED_SIEGE_TANK:  "(Infested Factory)",
    item_names.INFESTED_DIAMONDBACK: "(Infested Factory)",
    item_names.BULLFROG:             "(Infested Factory)",
    item_names.INFESTED_BANSHEE:     "(Infested Starport)",
    item_names.INFESTED_LIBERATOR:   "(Infested Starport)",

    item_names.ZERGLING_BANELING_ASPECT:             "(Zergling Morph)",
    item_names.HYDRALISK_IMPALER_ASPECT:             "(Hydralisk Morph)",
    item_names.HYDRALISK_LURKER_ASPECT:              "(Hydralisk Morph)",
    item_names.MUTALISK_CORRUPTOR_BROOD_LORD_ASPECT: "(Mutalisk/Corruptor Morph)",
    item_names.MUTALISK_CORRUPTOR_VIPER_ASPECT:      "(Mutalisk/Corruptor Morph)",
    item_names.MUTALISK_CORRUPTOR_GUARDIAN_ASPECT:   "(Mutalisk/Corruptor Morph)",
    item_names.MUTALISK_CORRUPTOR_DEVOURER_ASPECT:   "(Mutalisk/Corruptor Morph)",
    item_names.ROACH_RAVAGER_ASPECT:                 "(Roach Morph)",
    item_names.OVERLORD_OVERSEER_ASPECT:             "(Overlord Morph)",
    item_names.ROACH_PRIMAL_IGNITER_ASPECT:          "(Roach Morph)",
    item_names.ULTRALISK_TYRANNOZOR_ASPECT:          "(Ultralisk Morph)",

    item_names.INFESTED_MEDICS:           "(Zerg Mercenary)",
    item_names.INFESTED_SIEGE_BREAKERS:   "(Zerg Mercenary)",
    item_names.INFESTED_DUSK_WINGS:       "(Zerg Mercenary)",
    item_names.DEVOURING_ONES:            "(Zerg Mercenary)",
    item_names.HUNTER_KILLERS:            "(Zerg Mercenary)",
    item_names.TORRASQUE_MERC:            "(Zerg Mercenary)",
    item_names.HUNTERLING:                "(Zerg Mercenary)",
    item_names.YGGDRASIL:                 "(Zerg Mercenary)",
    item_names.CAUSTIC_HORRORS:           "(Zerg Mercenary)",

    item_names.SPORE_CRAWLER:             "(Zerg Building)",
    item_names.SPINE_CRAWLER:             "(Zerg Building)",
    item_names.BILE_LAUNCHER:             "(Zerg Building)",
    item_names.INFESTED_BUNKER:           "(Zerg Building)",
    item_names.INFESTED_MISSILE_TURRET:   "(Zerg Building)",
    item_names.NYDUS_WORM:                "(Nydus Network)",
    item_names.ECHIDNA_WORM:              "(Nydus Network)",

    item_names.ZEALOT:       "(Gateway, Aiur)",
    item_names.CENTURION:    "(Gateway, Nerazim)",
    item_names.SENTINEL:     "(Gateway, Purifier)",
    item_names.SUPPLICANT:   "(Gateway, Tal'darim)",
    item_names.STALKER:      "(Gateway, Nerazim)",
    item_names.INSTIGATOR:   "(Gateway, Purifier)",
    item_names.SLAYER:       "(Gateway, Tal'darim)",
    item_names.SENTRY:       "(Gateway, Aiur)",
    item_names.ENERGIZER:    "(Gateway, Purifier)",
    item_names.HAVOC:        "(Gateway, Tal'darim)",
    item_names.HIGH_TEMPLAR: "(Gateway, Aiur)",
    item_names.SIGNIFIER:    "(Gateway, Nerazim)",
    item_names.ASCENDANT:    "(Gateway, Tal'darim)",
    item_names.DARK_TEMPLAR: "(Gateway, Nerazim)",
    item_names.AVENGER:      "(Gateway, Aiur)",
    item_names.BLOOD_HUNTER: "(Gateway, Tal'darim)",
    item_names.DRAGOON:      "(Gateway, Aiur)",
    item_names.DARK_ARCHON:  "(Gateway, Nerazim)",
    item_names.ADEPT:        "(Gateway, Purifier)",
    item_names.OBSERVER:     "(Robotics Facility)",
    item_names.WARP_PRISM:   "(Robotics Facility)",
    item_names.IMMORTAL:     "(Robotics Facility, Aiur)",
    item_names.ANNIHILATOR:  "(Robotics Facility, Nerazim)",
    item_names.VANGUARD:     "(Robotics Facility, Tal'darim)",
    item_names.STALWART:     "(Robotics Facility, Purifier)",
    item_names.COLOSSUS:     "(Robotics Facility, Purifier)",
    item_names.WRATHWALKER:  "(Robotics Facility, Tal'darim)",
    item_names.REAVER:       "(Robotics Facility, Aiur)",
    item_names.DISRUPTOR:    "(Robotics Facility, Purifier)",
    item_names.PHOENIX:      "(Stargate, Aiur)",
    item_names.MIRAGE:       "(Stargate, Purifier)",
    item_names.SKIRMISHER:   "(Stargate, Tal'darim)",
    item_names.CORSAIR:      "(Stargate, Nerazim)",
    item_names.VOID_RAY:     "(Stargate, Nerazim)",
    item_names.DESTROYER:    "(Stargate, Tal'darim)",
    item_names.PULSAR:       "(Stargate, Aiur)",
    item_names.DAWNBRINGER:  "(Stargate, Purifier)",
    item_names.SCOUT:        "(Stargate, Aiur)",
    item_names.OPPRESSOR:    "(Stargate, Tal'darim)",
    item_names.CALADRIUS:    "(Stargate, Purifier)",
    item_names.MISTWING:     "(Stargate, Nerazim)",
    item_names.CARRIER:      "(Stargate, Aiur)",
    item_names.SKYLORD:      "(Stargate, Tal'darim)",
    item_names.TRIREME:      "(Stargate, Purifier)",
    item_names.TEMPEST:      "(Stargate, Purifier)",
    item_names.MOTHERSHIP:   "(Stargate, Tal'darim)",
    item_names.ARBITER:      "(Stargate, Aiur)",
    item_names.ORACLE:       "(Stargate, Nerazim)",

    item_names.PHOTON_CANNON:      "(Protoss Building)",
    item_names.KHAYDARIN_MONOLITH: "(Protoss Building)",
    item_names.SHIELD_BATTERY:     "(Protoss Building)",
}