FR_LG_PATCH_EXTENSIONS = ""

FR_LG_POKEMON_SPRITES = []
FR_LG_POKEMON_MAIN_PALETTE_EXTRACTION_PRIORITY = []
FR_LG_POKEMON_SHINY_PALETTE_EXTRACTION_PRIORITY = []
FR_LG_POKEMON_PALETTES = {}

FR_LG_EGG_SPRITES = []
FR_LG_EGG_PALETTES = {}

FR_LG_TRAINER_FOLDERS = []
FR_LG_TRAINER_SPRITES = []
FR_LG_TRAINER_MAIN_PALETTE_EXTRACTION_PRIORITY = []
FR_LG_TRAINER_PALETTES = {}

BLUE_TRAINER_SPRITES = []
BLUE_TRAINER_MAIN_PALETTE_EXTRACTION_PRIORITY = []
BLUE_TRAINER_BATTLE_FRONT_1_PALETTE_EXTRACTION_PRIORITY = []
BLUE_TRAINER_BATTLE_FRONT_2_PALETTE_EXTRACTION_PRIORITY = []
BLUE_TRAINER_BATTLE_FRONT_3_PALETTE_EXTRACTION_PRIORITY = []
BLUE_TRAINER_PALETTES = {}

FR_LG_SIMPLE_TRAINER_FOLDERS = []

FR_LG_FOLDER_OBJECT_INFOS = []

FR_LG_INTERNAL_ID_TO_OBJECT_ADDRESS = {}

FR_LG_OVERWORLD_SPRITE_ADDRESSES = {}

FR_LG_OVERWORLD_PALETTE_IDS = {}

FIRERED_DATA_ADDRESSES_ORIGINAL = {}
FIRERED_REV1_DATA_ADDRESSES_ORIGINAL = {}
LEAFGREEN_DATA_ADDRESSES_ORIGINAL = {}
LEAFGREEN_REV1_DATA_ADDRESSES_ORIGINAL = {}

FR_LG_DATA_ADDRESS_BEGINNING = 0x00
FR_LG_DATA_ADDRESS_END = 0x00

FR_LG_DATA_ADDRESS_INFOS: dict[str, int | dict[str, int]] = {}

FR_LG_VALID_OVERWORLD_SPRITE_SIZES = []

FR_LG_POINTER_REFERENCES = {}

FR_LG_SPRITES_REQUIREMENTS: dict[str, dict[str, bool | int | list[int]]] = {}

FR_LG_SPRITES_REQUIREMENTS_EXCEPTIONS: dict[str, dict[str, dict[str, bool | int | list[int]]]] = {}
