<TrackerView>:
    messages: 1000 # amount of messages stored in client logs.
    cols: 1
    viewclass: 'SelectableLabel'
    scroll_y: 0
    scroll_type: ["content", "bars"]
    bar_width: dp(12)
    effect_cls: "ScrollEffect"
    SelectableRecycleBoxLayout:
        default_size: None, dp(20)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        spacing: dp(3)

<VisualTracker>:
    BoxLayout:
        orientation: "vertical"
        # DropDown
        #     id: map_list
        #     Button:
        #         text: "First Item"
        #     Button:
        #         text: "Second Item"
        ApAsyncImage:
            id: tracker_map
            source: app.source
            fit_mode: "contain"
        Widget:
            id: location_canvas
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            size_hint: '0.01dp', '0.02dp'
            canvas.before:
                PushMatrix:
                Rotate:
                    #make top left 0,0 like poptracker
                    origin: tracker_map.center
                    angle: 180
                    axis: 1, 0, 0
                Translate:
                    #scale location_canvas with tracker_map to match resizing
                    xy: (tracker_map.x + (tracker_map.width - tracker_map.norm_image_size[0])/2, tracker_map.y + (tracker_map.height - tracker_map.norm_image_size[1])/2)
                Scale:
                    #scale coords by original size so we can use coords for full image
                    origin: 0,0
                    x: tracker_map.norm_image_size[0] / tracker_map.texture_size[0] if tracker_map.texture_size[0] > 0 else 1
                    y: tracker_map.norm_image_size[1] / tracker_map.texture_size[1] if tracker_map.texture_size[1] > 0 else 1
            canvas.after:
                #close transformations in after canvas so all objects get transformed
                PopMatrix:

<UTTextColor>:
    in_logic: "20ff20"
    out_of_logic: "cf1010"
    glitched: "ffff20"
    collected: "3F3F3F"
    collected_light: "FFFFFF"
    in_logic_glitched: "afff20"
    out_of_logic_glitched: "ef5500"
    mixed_logic: "ff9f20"
    hinted:"3040ff"
    hinted_in_logic:"20ffff"
    hinted_out_of_logic:"c010ff"
    hinted_glitched:"ff9f20"
    excluded: "CFCFCF"
    unconnected: "89F336"

<ApAsyncImage>:

<ApLocationIcon>:
    id: location_icon
    source: app.iconSource
    size: (0,0)
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    canvas.before:
        PushMatrix:
        Rotate:
            origin: location_icon.center
            angle: 180
            axis: 1, 0, 0
        Translate:
            xy: (-location_icon.norm_image_size[0]/2,location_icon.norm_image_size[1]/2)
    canvas.after:
        #close transformations in after canvas so all objects get transformed
        PopMatrix:

<TrackerTooltip>:
    pos_hint: {}

<ApLocationMixed>:
    text: "Server:"
    size_hint_x: None
    size: (app.loc_size, app.loc_size)
    canvas:
        Color:
            rgb: 0,0,0 
        Rectangle:
            pos: self.x - app.loc_border-self.width/2, self.y - app.loc_border-self.height/2
            size: self.width + (app.loc_border * 2), self.height + (app.loc_border * 2)
        Color:
            rgb: self.color #set by ApLocation.update_color()
        Rectangle:
            pos: self.x-self.width/2, self.y-self.height/2
            size: self.size

<ApLocationSplit>:
    text: "Server:"
    size_hint_x: None
    size: (app.loc_size, app.loc_size)
    color_2: (1, 0, 0)
    color_4: (1, 1, 0)
    color_1: (0, 1, 0)
    color_3: (0, 0, 1)
    canvas:
        Color:
            rgb: 0,0,0 
        Rectangle:
            pos: self.x - app.loc_border-self.width/2, self.y - app.loc_border-self.height/2
            size: self.width + (app.loc_border * 2), self.height + (app.loc_border * 2)
        Color:
            rgb: self.color_1
        Triangle:
            points: self.x, self.y, self.x - (self.width / 2), self.y + (self.height /2), self.x + (self.width / 2), self.y + (self.height /2)
        Color:
            rgb: self.color_3
        Triangle:
            points: self.x, self.y, self.x + (self.width / 2), self.y - (self.height /2), self.x + (self.width / 2), self.y + (self.height /2)
        Color:
            rgb: self.color_2
        Triangle:
            points: self.x, self.y, self.x - (self.width / 2), self.y - (self.height /2), self.x + (self.width / 2), self.y - (self.height /2)
        Color:
            rgb: self.color_4
        Triangle:
            points: self.x, self.y, self.x - (self.width / 2), self.y - (self.height /2), self.x - (self.width / 2), self.y + (self.height /2)
