from typing import Dict, Set, NamedTuple, Optional
from BaseClasses import ItemClassification

class ItemData(NamedTuple):
    category: str
    code: Optional[int]
    classification: ItemClassification
    amount: Optional[int] = 1

#Archipelago does not like it if an item has a code of 0, Crystal project starts its database
#Ids at 0, so we add an offset to the id of each item and remove that offset in the client
job_index_offset = 1
item_index_offset = 101
equipment_index_offset = 1001

item_table: Dict[str, ItemData] = {
    #Jobs
    "Job - Warrior": ItemData("Job", 0 + job_index_offset, ItemClassification.progression),
    "Job - Monk": ItemData("Job", 5 + job_index_offset, ItemClassification.progression),
    "Job - Rogue": ItemData("Job", 2 + job_index_offset, ItemClassification.progression),
    "Job - Cleric": ItemData("Job", 4 + job_index_offset, ItemClassification.progression),
    "Job - Wizard": ItemData("Job", 3 + job_index_offset, ItemClassification.progression),
    "Job - Warlock": ItemData("Job", 14 + job_index_offset, ItemClassification.progression),
    "Job - Fencer": ItemData("Job", 1 + job_index_offset, ItemClassification.progression),
    "Job - Shaman": ItemData("Job", 8 + job_index_offset, ItemClassification.progression),
    "Job - Scholar": ItemData("Job", 13 + job_index_offset, ItemClassification.progression),
    "Job - Aegis": ItemData("Job", 10 + job_index_offset, ItemClassification.progression),
    "Job - Hunter": ItemData("Job", 7 + job_index_offset, ItemClassification.progression),
    "Job - Chemist": ItemData("Job", 17 + job_index_offset, ItemClassification.progression),
    "Job - Reaper": ItemData("Job", 6 + job_index_offset, ItemClassification.progression),
    "Job - Ninja": ItemData("Job", 18 + job_index_offset, ItemClassification.progression),
    "Job - Nomad": ItemData("Job", 12 + job_index_offset, ItemClassification.progression),
    "Job - Dervish": ItemData("Job", 11 + job_index_offset, ItemClassification.progression),
    "Job - Beatsmith": ItemData("Job", 9 + job_index_offset, ItemClassification.progression),
    "Job - Samurai": ItemData("Job", 20 + job_index_offset, ItemClassification.progression),
    "Job - Assassin": ItemData("Job", 19 + job_index_offset, ItemClassification.progression),
    "Job - Valkyrie": ItemData("Job", 15 + job_index_offset, ItemClassification.progression),
    "Job - Summoner": ItemData("Job", 21 + job_index_offset, ItemClassification.progression),
    "Job - Beastmaster": ItemData("Job", 23 + job_index_offset, ItemClassification.progression),
    "Job - Weaver": ItemData("Job", 16 + job_index_offset, ItemClassification.progression),
    "Job - Mimic": ItemData("Job", 22 + job_index_offset, ItemClassification.progression),

    #Consumables
    "Item - Tonic": ItemData("Item", 18 + item_index_offset, ItemClassification.filler, 0),
    "Item - Potion": ItemData("Item", 0 + item_index_offset, ItemClassification.filler, 0),
    "Item - Z-Potion": ItemData("Item", 102 + item_index_offset, ItemClassification.filler, 0),
    "Item - Tincture": ItemData("Item", 47 + item_index_offset, ItemClassification.filler, 0),
    "Item - Ether": ItemData("Item", 1 + item_index_offset, ItemClassification.filler, 0),
    "Item - Zether": ItemData("Item", 142 + item_index_offset, ItemClassification.filler, 0),
    "Item - Fenix Juice": ItemData("Item", 2 + item_index_offset, ItemClassification.filler, 0),
    "Item - Fenix Syrup": ItemData("Item", 145 + item_index_offset, ItemClassification.filler, 0),
    "Item - Nan's Stew'": ItemData("Item", 9 + item_index_offset, ItemClassification.filler, 0),
    "Item - Nan's Cocoa'": ItemData("Item", 8 + item_index_offset, ItemClassification.filler, 0),
    "Item - Nan's Secret Recipe": ItemData("Item", 54 + item_index_offset, ItemClassification.filler, 0),
    "Item - Nuts": ItemData("Item", 14 + item_index_offset, ItemClassification.filler, 0),
    "Item - Milk": ItemData("Item", 20 + item_index_offset, ItemClassification.progression, 0),
    "Item - Shoudu Stew": ItemData("Item", 132 + item_index_offset, ItemClassification.progression, 0),
    "Item - Sweet Pop Candy": ItemData("Item", 34 + item_index_offset, ItemClassification.filler, 0),
    "Item - Sour Pop Candy": ItemData("Item", 35 + item_index_offset, ItemClassification.filler, 0),
    "Item - Bitter Pop Candy": ItemData("Item", 171 + item_index_offset, ItemClassification.filler, 0),
    "Item - Rotten Salmon": ItemData("Item", 11 + item_index_offset, ItemClassification.progression, 0),
    "Item - Decent Cod": ItemData("Item", 38 + item_index_offset, ItemClassification.filler, 0),
    "Item - Fresh Salmon": ItemData("Item", 10 + item_index_offset, ItemClassification.filler, 0),
    "Item - Scroll": ItemData("Item", 263 + item_index_offset, ItemClassification.filler, 0),

    #Bag upgrades
    "Item - Tonic Pouch": ItemData("Item", 133 + item_index_offset, ItemClassification.useful, 21),
    "Item - Potion Pouch": ItemData("Item", 134 + item_index_offset, ItemClassification.useful, 19),
    "Item - Z-Potion Pouch": ItemData("Item", 143 + item_index_offset, ItemClassification.useful, 7),
    "Item - Tincture Pouch": ItemData("Item", 135 + item_index_offset, ItemClassification.useful, 16),
    "Item - Ether Pouch": ItemData("Item", 136 + item_index_offset, ItemClassification.useful, 15),
    "Item - Zether Pouch": ItemData("Item", 144 + item_index_offset, ItemClassification.useful, 7),
    "Item - Fenix Juice Pouch": ItemData("Item", 137 + item_index_offset, ItemClassification.useful, 8),
    "Item - Fenix Syrup Pouch": ItemData("Item", 146 + item_index_offset, ItemClassification.useful, 2),
    "Item - Nuts Sack": ItemData("Item", 184 + item_index_offset, ItemClassification.useful),
    "Item - Milk Bag": ItemData("Item", 138 + item_index_offset, ItemClassification.useful),
    "Item - Decent Cod Bag": ItemData("Item", 185 + item_index_offset, ItemClassification.useful),

    #Fishing
    "Item - Flimsy Rod": ItemData("Item", 55 + item_index_offset, ItemClassification.useful),
    "Item - Tough Rod": ItemData("Item", 150 + item_index_offset, ItemClassification.useful),
    "Item - Super Rod": ItemData("Item", 151 + item_index_offset, ItemClassification.useful),
    "Item - Plug Lure": ItemData("Item", 91 + item_index_offset, ItemClassification.useful),
    "Item - Fly Lure": ItemData("Item", 149 + item_index_offset, ItemClassification.useful),
    "Item - Jigging Lure": ItemData("Item", 97 + item_index_offset, ItemClassification.useful),

    #Ore
    "Item - Silver Ore": ItemData("Item", 3 + item_index_offset, ItemClassification.useful, 18),
    "Item - Silver Ingot": ItemData("Item", 67 + item_index_offset, ItemClassification.useful, 18),
    "Item - Silver Dust": ItemData("Item", 68 + item_index_offset, ItemClassification.useful, 18),
    "Item - Gold Ore": ItemData("Item", 4 + item_index_offset, ItemClassification.useful, 18),
    "Item - Gold Ingot": ItemData("Item", 69 + item_index_offset, ItemClassification.useful, 18),
    "Item - Gold Dust": ItemData("Item", 70 + item_index_offset, ItemClassification.useful, 18),
    "Item - Diamond Ore": ItemData("Item", 5 + item_index_offset, ItemClassification.useful, 18),
    "Item - Diamond Ingot": ItemData("Item", 71 + item_index_offset, ItemClassification.useful, 18),
    "Item - Diamond Dust": ItemData("Item", 72 + item_index_offset, ItemClassification.useful, 18),

    #Passes
    "Item - Quintar Pass": ItemData("Item", 7 + item_index_offset, ItemClassification.progression),
    "Item - Luxury Pass": ItemData("Item", 93 + item_index_offset, ItemClassification.progression),
    "Item - Luxury Pass V2": ItemData("Item", 148 + item_index_offset, ItemClassification.progression),
    "Item - Ferry Pass": ItemData("Item", 37 + item_index_offset, ItemClassification.progression),

    #Key Items
    "Item - Black Squirrel": ItemData("Item", 21 + item_index_offset, ItemClassification.progression, 3),
    "Item - Dog Bone": ItemData("Item", 6 + item_index_offset, ItemClassification.progression, 3),
    #TODO: Check clamshell count
    "Item - Clamshell": ItemData("Item", 16 + item_index_offset, ItemClassification.progression, 17),
    "Item - Digested Head": ItemData("Item", 17 + item_index_offset, ItemClassification.progression, 3),
    "Item - Lost Penguin": ItemData("Item", 24 + item_index_offset, ItemClassification.progression, 12),
    "Item - Elevator Part": ItemData("Item", 224 + item_index_offset, ItemClassification.progression, 17),
    "Item - Undersea Crab": ItemData("Item", 212 + item_index_offset, ItemClassification.progression, 15),
    "Item - West Lookout Token": ItemData("Item", 81 + item_index_offset, ItemClassification.progression),
    "Item - Central Lookout Token": ItemData("Item", 88 + item_index_offset, ItemClassification.progression),
    "Item - North Lookout Token": ItemData("Item", 131 + item_index_offset, ItemClassification.progression),
    "Item - Babel Quintar": ItemData("Item", 167 + item_index_offset, ItemClassification.progression),
    "Item - Quintar Shedding": ItemData("Item", 168 + item_index_offset, ItemClassification.progression, 12),
    "Item - Vermillion Book": ItemData("Item", 172 + item_index_offset, ItemClassification.progression),
    "Item - Viridian Book": ItemData("Item", 173 + item_index_offset, ItemClassification.progression),
    "Item - Cerulean Book": ItemData("Item", 174 + item_index_offset, ItemClassification.progression),
    "Item - Ancient Tablet A": ItemData("Item", 161 + item_index_offset, ItemClassification.filler),
    "Item - Ancient Tablet B": ItemData("Item", 162 + item_index_offset, ItemClassification.filler),
    "Item - Ancient Tablet C": ItemData("Item", 163 + item_index_offset, ItemClassification.filler),

    #Animal summons
    "Item - Quintar Flute": ItemData("Item", 39 + item_index_offset, ItemClassification.progression),
    "Item - Ibek Bell": ItemData("Item", 50 + item_index_offset, ItemClassification.progression),
    "Item - Owl Drum": ItemData("Item", 49 + item_index_offset, ItemClassification.progression),
    "Item - Salmon Violin": ItemData("Item", 48 + item_index_offset, ItemClassification.progression),
    "Item - Salmon Cello": ItemData("Item", 114 + item_index_offset, ItemClassification.progression),

    #Teleport items
    "Item - Home Point Stone": ItemData("Item", 19 + item_index_offset, ItemClassification.progression),
    "Item - Gaea Stone": ItemData("Item", 23 + item_index_offset, ItemClassification.progression),
    "Item - Mercury Stone": ItemData("Item", 13 + item_index_offset, ItemClassification.progression),
    "Item - Poseidon Stone": ItemData("Item", 57 + item_index_offset, ItemClassification.progression),
    "Item - Mars Stone": ItemData("Item", 59 + item_index_offset, ItemClassification.progression),
    "Item - Ganymede Stone": ItemData("Item", 65 + item_index_offset, ItemClassification.progression),
    "Item - Triton Stone": ItemData("Item", 66 + item_index_offset, ItemClassification.progression),
    "Item - Callisto Stone": ItemData("Item", 155 + item_index_offset, ItemClassification.progression),
    "Item - Europa Stone": ItemData("Item", 64 + item_index_offset, ItemClassification.progression),
    "Item - Dione Stone": ItemData("Item", 166 + item_index_offset, ItemClassification.progression),
    "Item - Neptune Stone": ItemData("Item", 208 + item_index_offset, ItemClassification.progression),
    "Item - New World Stone": ItemData("Item", 140 + item_index_offset, ItemClassification.progression),
    "Item - Old World Stone": ItemData("Item", 253 + item_index_offset, ItemClassification.progression),

    #Swords
    "Equipment - Short Sword": ItemData("Equipment", 0 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Iron Sword": ItemData("Equipment", 11 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Contract": ItemData("Equipment", 71 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Help the Prince": ItemData("Equipment", 89 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Craftwork Sword": ItemData("Equipment", 93 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Broadsword": ItemData("Equipment", 12 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Sharp Sword": ItemData("Equipment", 200 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Razor Edge": ItemData("Equipment", 199 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Sword": ItemData("Equipment", 112 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Sword": ItemData("Equipment", 157 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Longsword": ItemData("Equipment", 378 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Boomer Sword": ItemData("Equipment", 177 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Digested Sword": ItemData("Equipment", 227 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Scimitar": ItemData("Equipment", 379 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Cutlass": ItemData("Equipment", 377 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Cold Touch": ItemData("Equipment", 375 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Burning Blade": ItemData("Equipment", 497 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Sword": ItemData("Equipment", 138 + equipment_index_offset, ItemClassification.useful),
    "Equipment - War Sword": ItemData("Equipment", 376 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Bloodbind": ItemData("Equipment", 197 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Temporal Blade": ItemData("Equipment", 525 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Highland Blade": ItemData("Equipment", 370 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Hydra Edge": ItemData("Equipment", 371 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Defender": ItemData("Equipment", 380 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Crystal Sword": ItemData("Equipment", 374 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Conquest": ItemData("Equipment", 372 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Flame Sword": ItemData("Equipment", 381 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Sword": ItemData("Equipment", 248 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Rune Sword": ItemData("Equipment", 382 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Auduril": ItemData("Equipment", 270 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Bigsword": ItemData("Equipment", 249 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Training Sword": ItemData("Equipment", 532 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Life Line": ItemData("Equipment", 302 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Soul Keeper": ItemData("Equipment", 303 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Crabs Claw": ItemData("Equipment", 411 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Kings Guard": ItemData("Equipment", 316 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Sword": ItemData("Equipment", 135 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Balrog": ItemData("Equipment", 369 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Oily Sword": ItemData("Equipment", 279 + equipment_index_offset, ItemClassification.useful),

    #Axes
    "Equipment - Hand Axe": ItemData("Equipment", 55 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Craftwork Axe": ItemData("Equipment", 94 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Cleaver": ItemData("Equipment", 2 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Chopper": ItemData("Equipment", 66 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Hunting Axe": ItemData("Equipment", 187 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Axe": ItemData("Equipment", 104 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Stone Splitter": ItemData("Equipment", 201 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Broadaxe": ItemData("Equipment", 383 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Axe": ItemData("Equipment", 158 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Hatchet": ItemData("Equipment", 386 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Axe of Light": ItemData("Equipment", 387 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Axe": ItemData("Equipment", 139 + equipment_index_offset, ItemClassification.useful),
    "Equipment - War Axe": ItemData("Equipment", 384 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Berserker Axe": ItemData("Equipment", 390 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gaia Axe": ItemData("Equipment", 385 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Axe": ItemData("Equipment", 251 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Ancient Axe": ItemData("Equipment", 391 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Bigaxe": ItemData("Equipment", 250 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Aphotic Edge": ItemData("Equipment", 388 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Axe": ItemData("Equipment", 136 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Decapitator": ItemData("Equipment", 280 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Ragebringer": ItemData("Equipment", 274 + equipment_index_offset, ItemClassification.useful),

    #Daggers
    "Equipment - Dirk": ItemData("Equipment", 3 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Stabbers": ItemData("Equipment", 63 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Fishgutter": ItemData("Equipment", 77 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Poisonkiss": ItemData("Equipment", 40 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Shank": ItemData("Equipment", 60 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Craftwork Dagger": ItemData("Equipment", 95 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Tanto": ItemData("Equipment", 192 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Butterfly": ItemData("Equipment", 203 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Kris": ItemData("Equipment", 202 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Ambush Knife": ItemData("Equipment", 184 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Rondel": ItemData("Equipment", 204 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Dagger": ItemData("Equipment", 113 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Dagger": ItemData("Equipment", 159 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Parry Knife": ItemData("Equipment", 397 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Janbiya": ItemData("Equipment", 392 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Sai": ItemData("Equipment", 396 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Kodachi": ItemData("Equipment", 400 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Butter Cutter": ItemData("Equipment", 198 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Soul Kris": ItemData("Equipment", 3 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gouger": ItemData("Equipment", 61 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Fanged Knife": ItemData("Equipment", 526 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Cinquedea": ItemData("Equipment", 393 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Dagger": ItemData("Equipment", 140 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Kowakizashi": ItemData("Equipment", 398 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Bone Knife": ItemData("Equipment", 395 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Poignard": ItemData("Equipment", 394 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Flamespike": ItemData("Equipment", 72 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Dagger": ItemData("Equipment", 269 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Sange": ItemData("Equipment", 317 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Yasha": ItemData("Equipment", 318 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Legend Spike": ItemData("Equipment", 315 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Mage Masher": ItemData("Equipment", 282 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Mages Pike": ItemData("Equipment", 306 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Dagger": ItemData("Equipment", 137 + equipment_index_offset, ItemClassification.useful),
    
    #Rapiers
    "Equipment - Rapier": ItemData("Equipment", 73 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Stinger": ItemData("Equipment", 1 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Toothpick": ItemData("Equipment", 42 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Craftwork Rapier": ItemData("Equipment", 96 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Estoc": ItemData("Equipment", 207 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Scarlette": ItemData("Equipment", 206 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Fish Skewer": ItemData("Equipment", 175 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Rapier": ItemData("Equipment", 114 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Rapier": ItemData("Equipment", 73 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Dueller": ItemData("Equipment", 10 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Vulture": ItemData("Equipment", 402 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Falcon Dance": ItemData("Equipment", 408 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Fleuret": ItemData("Equipment", 404 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Rapier": ItemData("Equipment", 141 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Epee": ItemData("Equipment", 405 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Windsong": ItemData("Equipment", 407 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Rapier": ItemData("Equipment", 252 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Nightingale": ItemData("Equipment", 401 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Chartreuse": ItemData("Equipment", 403 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Murgleys": ItemData("Equipment", 406 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Rapier": ItemData("Equipment", 142 + equipment_index_offset, ItemClassification.useful),
    
    #Katanas
    "Equipment - Craftwork Katana": ItemData("Equipment", 97 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Craftwork Tachi": ItemData("Equipment", 399 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Katana": ItemData("Equipment", 115 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Katana": ItemData("Equipment", 161 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Nansen": ItemData("Equipment", 363 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Mitsutada": ItemData("Equipment", 22 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Hitofuri": ItemData("Equipment", 364 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Kokaiji": ItemData("Equipment", 23 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Katana": ItemData("Equipment", 143 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Hokuken": ItemData("Equipment", 588 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Tomokirimaru": ItemData("Equipment", 366 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Ichimonji": ItemData("Equipment", 362 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Katana": ItemData("Equipment", 253 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Muramasa": ItemData("Equipment", 367 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Katana": ItemData("Equipment", 144 + equipment_index_offset, ItemClassification.useful),

    #Spears
    "Equipment - Short Spear": ItemData("Equipment", 4 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Craftwork Spear": ItemData("Equipment", 98 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Javelin": ItemData("Equipment", 205 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Skewer": ItemData("Equipment", 190 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Prodder": ItemData("Equipment", 183 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Spear": ItemData("Equipment", 116 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Spear": ItemData("Equipment", 162 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Trident": ItemData("Equipment", 409 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Wind Lance": ItemData("Equipment", 410 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Halberd": ItemData("Equipment", 418 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Spear": ItemData("Equipment", 145 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Voulge": ItemData("Equipment", 419 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Radiance": ItemData("Equipment", 417 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Partizan": ItemData("Equipment", 416 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Spear": ItemData("Equipment", 254 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Incursier": ItemData("Equipment", 563 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Royal Guard": ItemData("Equipment", 275 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gungnir": ItemData("Equipment", 304 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Spear": ItemData("Equipment", 146 + equipment_index_offset, ItemClassification.useful),
    
    #Scythes
    "Equipment - Battle Scythe": ItemData("Equipment", 6 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Craftwork Scythe": ItemData("Equipment", 99 + equipment_index_offset, ItemClassification.useful),
    "Equipment - War Scythe": ItemData("Equipment", 208 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Wind Sickle": ItemData("Equipment", 413 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Scythe": ItemData("Equipment", 117 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Scythe": ItemData("Equipment", 163 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Thresher": ItemData("Equipment", 294 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Grim Scythe": ItemData("Equipment", 293 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Great Thresher": ItemData("Equipment", 295 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Frost Reaper": ItemData("Equipment", 414 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Scythe": ItemData("Equipment", 147 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Ember Scythe": ItemData("Equipment", 589 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gravedigger": ItemData("Equipment", 415 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Wind Thresher": ItemData("Equipment", 590 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Scythe": ItemData("Equipment", 255 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Adjudicator": ItemData("Equipment", 245 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Twilight": ItemData("Equipment", 412 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Arctic Chill": ItemData("Equipment", 556 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Scythe": ItemData("Equipment", 148 + equipment_index_offset, ItemClassification.useful),

    #Bows
    "Equipment - Craftwork Bow": ItemData("Equipment", 105 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Short Bow": ItemData("Equipment", 7 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Hunting Bow": ItemData("Equipment", 181 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Long Bow": ItemData("Equipment", 209 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Bow": ItemData("Equipment", 118 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Bow": ItemData("Equipment", 164 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Battle Bow": ItemData("Equipment", 297 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Composite Bow": ItemData("Equipment", 296 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Habins Bow": ItemData("Equipment", 222 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Razor Bow": ItemData("Equipment", 298 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Elven Bow": ItemData("Equipment", 421 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Bow": ItemData("Equipment", 149 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Spore Shooter": ItemData("Equipment", 180 + equipment_index_offset, ItemClassification.useful),
    "Equipment - War Bow": ItemData("Equipment", 300 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Siege Bow": ItemData("Equipment", 301 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Rune Bow": ItemData("Equipment", 299 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Bow": ItemData("Equipment", 256 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Panakeia": ItemData("Equipment", 530 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artemis": ItemData("Equipment", 281 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Dream Hunter": ItemData("Equipment", 420 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Bow": ItemData("Equipment", 150 + equipment_index_offset, ItemClassification.useful),

    #Staves
    "Equipment - Short Staff": ItemData("Equipment", 5 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Cedar Staff": ItemData("Equipment", 62 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gnarled Root": ItemData("Equipment", 15 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Craftwork Staff": ItemData("Equipment", 100 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Bone Smasher": ItemData("Equipment", 14 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Iron Rod": ItemData("Equipment", 426 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Quarterstaff": ItemData("Equipment", 210 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Walking Stick": ItemData("Equipment", 188 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Maplewood": ItemData("Equipment", 211 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Staff": ItemData("Equipment", 119 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Staff": ItemData("Equipment", 165 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Knockout Stick": ItemData("Equipment", 335 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Skullbasher": ItemData("Equipment", 427 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Future Sight": ItemData("Equipment", 561 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Battle Staff": ItemData("Equipment", 67 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Digested Staff": ItemData("Equipment", 228 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Nature's Gift'": ItemData("Equipment", 423 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Life Jewel": ItemData("Equipment", 422 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Staff": ItemData("Equipment", 151 + equipment_index_offset, ItemClassification.useful),
    "Equipment - War Staff": ItemData("Equipment", 428 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Apprentice": ItemData("Equipment", 424 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Sages Walker": ItemData("Equipment", 425 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Staff": ItemData("Equipment", 257 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Beats Stick": ItemData("Equipment", 289 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Staff of Balance": ItemData("Equipment", 290 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Judgement": ItemData("Equipment", 429 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Staff": ItemData("Equipment", 152 + equipment_index_offset, ItemClassification.useful),

    #Wands
    "Equipment - Ash Wand": ItemData("Equipment", 8 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Cedar Wand": ItemData("Equipment", 13 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Oak Wand": ItemData("Equipment", 16 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Torch": ItemData("Equipment", 64 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Ink Stick": ItemData("Equipment", 80 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Craftwork Wand": ItemData("Equipment", 101 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Soul Wand": ItemData("Equipment", 213 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Static Rod": ItemData("Equipment", 189 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Maple Wand": ItemData("Equipment", 212 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Wand": ItemData("Equipment", 120 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Wand": ItemData("Equipment", 166 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Storm Rod": ItemData("Equipment", 267 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Baton": ItemData("Equipment", 434 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Cursegiver": ItemData("Equipment", 432 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Effigy": ItemData("Equipment", 433 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Wand": ItemData("Equipment", 153 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Rune Wand": ItemData("Equipment", 435 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Sentinel Rod": ItemData("Equipment", 431 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Stardust Wand": ItemData("Equipment", 430 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Wand": ItemData("Equipment", 258 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Aura Focus": ItemData("Equipment", 278 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Paladin Wand": ItemData("Equipment", 276 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Obelisk": ItemData("Equipment", 307 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Flameseeker": ItemData("Equipment", 358 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Wand": ItemData("Equipment", 154 + equipment_index_offset, ItemClassification.useful),

    #Books
    "Equipment - Moby Dick": ItemData("Equipment", 51 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Orylei": ItemData("Equipment", 65 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Craftwork Pages": ItemData("Equipment", 102 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Encyclopedia": ItemData("Equipment", 214 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gospel": ItemData("Equipment", 194 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Paypirbak": ItemData("Equipment", 223 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Art of War": ItemData("Equipment", 224 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Silver Pages": ItemData("Equipment", 121 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Artisan Pages": ItemData("Equipment", 167 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Grimoire": ItemData("Equipment", 438 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Blank Pages": ItemData("Equipment", 437 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Tome of Light": ItemData("Equipment", 439 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Hydrology": ItemData("Equipment", 441 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Gold Pages": ItemData("Equipment", 155 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Dark Gospel": ItemData("Equipment", 440 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Divination": ItemData("Equipment", 442 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Malifice": ItemData("Equipment", 443 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Master Pages": ItemData("Equipment", 259 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Codex": ItemData("Equipment", 436 + equipment_index_offset, ItemClassification.useful),
    "Equipment - Diamond Pages": ItemData("Equipment", 156 + equipment_index_offset, ItemClassification.useful),


    #Currency
    #"Currency": ItemData("Currency", 0 + index_offset, ItemClassification.filler),

}

def get_item_names_per_category() -> Dict[str, Set[str]]:
    categories: Dict[str, Set[str]] = {}

    for name, data in item_table.items():
        if data.category != "Events":
            categories.setdefault(data.category, set()).add(name)

    return categories
