enemy_species = [
    "Cultist",
    "Spook",
    "Frog",
    "Buffalo",
    "Antoid",
    "Mushroom",
    "Fungus",
    "Mobile Sprout",
    "Fire Plug",
    "Record",
    "Power Robot",
    "Reactor Robot",
    "Hieroglyph",
    "Asp Hieroglyph",
    "Swoosh",
    "Menace",
    "Spirit",
    "Elemental",
    "Party Man",
    "Reveler",
    "Local Guy",
    "Hippie",
    "Bear",
    "Bear Seven",
    "Moldyman",
    "Mite",
    "Lady",
    "Ant",
    "Coffee Cup",
    "Dice",
    "Little Pile",
    "Kraken",
    "Robo",
    "Cop",
    "Coil Snake",
    "Batty",
    "Roach",
    "Sign",
    "Shambler",
    "Punk",
    "Skelpion",
    "Starman",
    "Sphere",
    "Royal Guard",
    "General",
    "Zombie",
    "Possessor",
    "Dog",
    "Oak",
    "Octobot",
    "Duck",
    "Clock",
    "Wolf",
    "Musica",
    "Pile of Puke",
    "Kiss of Death",
    "Eel",
    "Tangoo",
    "Arachnid",
    "Demon",
    "Fobby",
    "Foppy",
    "Booka",
    "Mook",
    "Ghost",
    "Slug",
    "Mouse",
    "Bomb",
    "Tom",
    "Sam",
    "Fish",
    "Fish's Brother",
    "Kid",
    "Boy",
    "Art",
    "Shattered Man",
    "Orb",
    "Man Junior",
    "Li'l UFO",
    "UFO",
    "Guy",
    "Taxi",
    "Molecule",
    "Protoplasm",
    "Robot",
    "Psycho",
    "Goat",
    "Mole",
    "Flame",
    "Petunia",
    "Ranboob",
    "Noose",
    "Pump",
    "Crocodile",
    "Fly",
    "Crow",
    "Caterpillar",
    "Eye",
    "Worm",
    "Statue",
    "Rat of Doom",
    "Specter",
    "Chief",
    "Bot",
    "Gangster",
    "Storm",
    "Dino",
    "Painter",
    "Burglar",
    "Tank",
]

enemy_adjectives = [
    "",
    "Insane ",
    "Dept. Store ",
    "Armored ",
    "Bad ",
    "Black ",
    "Red ",
    "Ramblin' ",
    "Struttin' ",
    "Tough ",
    "Enraged ",
    "Mystical ",
    "Atomic ",
    "Nuclear ",
    "Guardian ",
    "Lethal ",
    "Electro ",
    "Conducting ",
    "Evil ",
    "Annoying Old ",
    "Annoying ",
    "Unassuming ",
    "New Age Retro ",
    "Carbon ",
    "Mighty ",
    "Putrid ",
    "Thunder ",
    "Cranky ",
    "Extra Cranky ",
    "Titanic ",
    "Gigantic ",
    "Mondo ",
    "Scalding ",
    "Loaded ",
    "Slimy ",
    "Even Slimier ",
    "Bionic ",
    "Spinning ",
    "Whirling ",
    "Hyper Spinning ",
    "Coil ",
    "Thirsty ",
    "Mr. ",
    "Elder ",
    "Violent ",
    "Filthy Attack ",
    "Crazed ",
    "Wooly ",
    "Wild 'n Wooly ",
    "Skate ",
    "Dread ",
    "Super ",
    "Ghost of ",
    "Smilin' ",
    "Uncontrollable ",
    "Petrified ",
    "Urban ",
    "Zombie ",
    "Crooked ",
    "Over Zealous ",
    "Territorial ",
    "Hostile Elder ",
    "Diamond ",
    "Marauder ",
    "Military ",
    "Mechanical ",
    "Ultimate ",
    "Mad ",
    "Dali's ",
    "Trillionage ",
    "Desert ",
    "Big ",
    "French ",
    "Zap ",
    "Squatter ",
    "Crested ",
    "Great Crested ",
    "Lesser ",
    "Smelly ",
    "Stinky ",
    "Attack ",
    "Pit Bull ",
    "Rowdy ",
    "Deadly ",
    "Care Free ",
    "Electro ",
    "Handsome ",
    "Manly ",
    "Runaway ",
    "Trick or Trick ",
    "Cave ",
    "Abstract ",
    "Shattered ",
    "Fierce ",
    "Ego ",
    "Yes ",
    "Cute ",
    "Beautiful ",
    "Pogo ",
    "Tough ",
    "Worthless ",
    "Sentry ",
    "Heavily Armed ",
    "Psychic ",
    "Major Psychic ",
    "Gruff ",
    "Clumsy ",
    "Soul Consuming ",
    "Demonic ",
    "High-class ",
    "Robo-",
    "Plain ",
    "Strong ",
    "Hard ",
    "No Good ",
    "Mostly Bad ",
    "Spiteful ",
    "Farm ",
    "Criminal ",
    "Master Criminal ",
    "Final ",
    "Plague ",
    "Disingenuous ",
    "Disgusting ",
    "Inadequate ",
    "Dr. ",
    "Electronic ",
    "Jealous ",
    "Bald ",
    "Baked ",
    "Magic ",
    "Polar ",
    "Depressed ",
    "Clean ",
    "Elderly ",
    "Banned ",
    "Grumpy ",
    "Whelmed ",
    "Loud ",
    "Mushy ",
    "Randomized ",
    "Homesick ",
    "Mecha ",
    "Ramblin' Evil ",
    "Master ",
    "Secret ",
    "Platinum ",
    "Armed ",
    "Condemned ",
    "Rad ",
    "Hangry ",
    "Moonsidian ",
    "No. 3 ",
    "Legal ",
    "Copyrighted ",
    "Cyanotic ",
    "Serendipitous ",
    "Disgruntled "
]

battle_sprites = {
    "Antoid": [0x01],
    "Dog": [0x02, 0x42],
    "Frog": [0x03],
    "Sphere": [0x04],
    "Mushroom": [0x05],
    "Bomb": [0x06],
    "Octobot": [0x07],
    "Musica": [0x08],
    "Ranboob": [0x09],
    "Moldyman": [0x0A],
    "Fungus": [0x0B],
    "Booka": [0x0C],
    "Shambler": [0x0D],
    "Dino": [0x0E, 0x41],
    "Art": [0x0F],
    "Crow": [0x10],
    "Fobby": [0x11],
    "Foppy": [0x11],
    "Duck": [0x12],
    "Batty": [0x13],
    "Mouse": [0x14],
    "Kiss of Death": [0x15],
    "Swoosh": [0x16],
    "Petunia": [0x17],
    "Flame": [0x18],
    "Coil Snake": [0x19],
    "Sign": [0x1A],
    "Kid": [0x1B],
    "Sam": [0x1C],
    "Tom": [0x1C],
    "Psycho": [0x1D],
    "Mite": [0x1E],
    "Fish": [0x1F],
    "Fish's Brother": [0x1F],
    "Burglar": [0x20],
    "Painter": [0x21],
    "Party Man": [0x22],
    "Reveler": [0x22],
    "Local Guy": [0x23],
    "Menace": [0x24],
    "Spirit": [0x24],
    "Gangster": [0x25],
    "Guy": [0x26],
    "Storm": [0x27],
    # Carbon
    "Kraken": [0x29],
    # Pokey
    "Li'l UFO": [0x2B],
    "Coffee Cup": [0x2C],
    "Molecule": [0x2D],
    "Record": [0x2E],
    "Slug": [0x2F],
    "Elemental": [0x30],
    "UFO": [0x31],
    "Possessor": [0x32],
    "Cop": [0x33],
    "Robo": [0x34],
    "Ghost": [0x35],
    "Robot": [0x36],
    "Starman": [0x37, 0x6A],
    "Shattered Man": [0x38],
    "Specter": [0x39],
    "Dice": [0x3A],
    "Fire Plug": [0x3B],
    "Protoplasm": [0x3C],
    "Mook": [0x3D],
    "Spook": [0x3D],
    "Pump": [0x3E],
    "Cultist": [0x3F],
    "Man Junior": [0x40],
    "Asp Hieroglyph": [0x43],
    "Eel": [0x44],
    "Chief": [0x45],
    "Hieroglyph": [0x46],
    "Bot": [0x47],
    "Zombie": [0x48],
    "Ant": [0x49],
    "Buffalo": [0x4A],
    "Rat of Doom": [0x4B],
    # iamond Dog
    "Arachnid": [0x4D],
    "Mole": [0x4E],
    "Statue": [0x4F],
    "Roach": [0x50],
    "Noose": [0x51],
    "Tangoo": [0x52],
    # "Digger": [0x53],
    "Crocodile": [0x54],
    "Taxi": [0x55],
    "Demon": [0x56],
    "General": [0x57],
    "Royal Guard": [0x57],
    # Trillionage sprout
    "Fly": [0x59],
    "Mobile Sprout": [0x5A],
    "Little Pile": [0x5B],
    "Skelpion": [0x5C],
    "Clock": [0x5D],
    "Goat": [0x5E],
    "Oak": [0x5F],
    "Punk": [0x60, 0x64],
    "Tank": [0x61],
    "Pile of Puke": [0x62],
    "Lady": [0x63],
    "Boy": [0x65],
    "Orb": [0x66],
    "Wolf": [0x67],
    "Bear": [0x68],
    "Bear Seven": [0x68],
    "Power Robot": [0x69],
    "Reactor Robot": [0x69],
    "Hippie": [0x6B],
    "Worm": [0x6D],
    "Caterpillar": [0x6D],
    "Eye": [0x6E]


}

field_sprites = [
    0x00,
    0x013C,
    0x014A,
    0x0118,
    0x012E,
    0x0123,
    0x0115,
    0x0132,
    0xC3,
    0x0124,
    0x011D,
    0x0123,
    0x0128,
    0x0132,
    0x012A,
    0x012C,
    0x011A,
    0x0116,
    0x011F,
    0x0112,
    0x01A0,
    0x0144,
    0x0114,
    0x0122,
    0x0117,
    0x011B,
    0x0135,
    0x01BC,
    0x011E,
    0x0117,
    0x0144,
    0x0120,
    0x9D,
    0x9F,
    0x0187,
    0x0184,
    0x0144,
    0x99,
    0x0186,
    0x0144,
    0x014A,
    0x0132,
    0x2C,
    0x0130,
    0xC3,
    0x0115,
    0xC3,
    0x013C,
    0x0117,
    0x0130,
    0x0131,
    0x0182,
    0x0132,
    0x011D,
    0x0136,
    0x012F,
    0x0133,
    0x0144,
    0xC3,
    0x0117,
    0xC3,
    0x0132,
    0x0117,
    0x65,
    0x011C,
    0x0138,
    0x016C,
    0x0140,
    0x012D,
    0x0183,
    0x0145,
    0x01A2,
    0x0134,
    0x0139,
    0x0137,
    0x01A0,
    0x014A,
    0x013A,
    0x019F,
    0x0125,
    0x013A,
    0x0143,
    0x0144,
    0x019F,
    0x014C,
    0x0121,
    0x0132,
    0x0142,
    0x013D,
    0x013E,
    0x013D,
    0x013B,
    0x013F,
    0x0146,
    0x0126,
    0x0129,
    0x011C,
    0x0191,
    0x0148,
    0x0188,
    0x011C,
    0x0149,
    0x0147,
    0x014A,
    0x014B,
    0x0132,
    0x0132,
    0x0185,
    0x0132,
    0x01A1,
    0x0132,
]

excluded_enemies = [
    "Dept. Store Spook",
    "Ness's Nightmare",
    "Mr. Carpainter",
    "Carbon Dog",
    "Titanic Ant",
    "Shrooom!",
    "Plague Rat of Doom",
    "Mondo Mole",
    "Guardian Digger",
    "Kraken",
    "Guardian General",
    "Starman Deluxe",
    "Diamond Dog",
    "Trillionage Sprout",
    "Master Belch",
    "Master Barf",
    "Electro Specter",
    "Boogey Tent",
    "Everdred",
    "Thunder and Storm",
    "Frankystein Mark II",
    "Frank",
    "Evil Mani-Mani",
    "Clumsy Robot",
    "Dept. Store Spook (2)",
    "Ness's Nightmare (2)",
    "Mr. Carpainter (2)",
    "Carbon Dog (2)",
    "Chomposaur (2)",
    "Titanic Ant (2)",
    "Gigantic Ant (2)",
    "Shrooom! (2)",
    "Plague Rat of Doom (2)",
    "Mondo Mole (2)",
    "Guardian Digger (2)",
    "Kraken (2)",
    "Starman (2)",
    "Starman Super (2)",
    "Ghost of Starman (2)",
    "Starman Deluxe (2)",
    "Final Starman (2)",
    "Diamond Dog (2)",
    "Trillionage Sprout (2)",
    "Master Belch (2)",
    "Master Barf (2)",
    "Boogey Tent (2)",
    "Everdred (2)",
    "Electro Specter (2)",
    "Thunder and Storm (2)",
    "Frankystein Mark II (2)",
    "Evil Mani-Mani (2)",
    "Clumsy Robot (2)",
    "Robo-pump (2)",
    "Guardian General (2)",
    "Struttin' Evil Mushroom (2)",
    "Runaway Dog (2)",
    "Tiny Li'l Ghost",
    "Starman Junior",
    "Buzz Buzz",
    "Heavily Armed Pokey",
    "Giygas (2)",
    "Giygas (3)",
    "Giygas (4)",
    "Giygas (5)",
    "Mini Barf",
    "Captain Strong",
    "Giygas (6)",
    "Clumsy Robot (3)",
    "Giygas"
]

robots = [
    "Power Robot",
    "Reactor Robot",
    "Robo",
    "Sign",
    "Shambler",
    "Sphere",
    "Octobot",
    "Bomb",
    "Li'l UFO",
    "UFO",
    "Taxi",
    "Bot",
    "Pump",
    "Robot"
]

insects = [
    "Antoid",
    "Ant",
    "Arachnid",
    "Roach",
    "Skelpion",
    "Slug",
    "Fly",
    "Caterpillar",
    "Worm"
]

movement_patterns = {
    0x65: 21,
    0x99: 21,
    0x9D: 21,
    0x9F: 21,
    0xC3: 31,
    0x0112: 25,
    0x01A2: 27,
    0x0114: 27,
    0x0115: 27,
    0x0116: 21,
    0x0117: 27,
    0x0118: 21,
    0x011A: 25,
    0x011B: 20,
    0x011C: 21,
    0x011D: 24,
    0x011E: 24,
    0x011F: 21,
    0x0120: 21,
    0x0121: 30,
    0x0122: 29,
    0x0123: 24,
    0x0124: 21,
    0x0125: 21,
    0x0126: 22,
    0x0128: 20,
    0x0129: 29,
    0x012A: 29,
    0x012C: 27,
    0x012D: 20,
    0x012E: 23,
    0x012F: 26,
    0x0130: 23,
    0x0131: 27,
    0x0132: 23,
    0x0133: 24,
    0x0134: 21,
    0x0135: 28,
    0x0136: 30,
    0x0137: 29,
    0x0138: 29,
    0x0139: 20,
    0x013A: 20,
    0x013B: 20,
    0x013C: 20,
    0x013D: 24,
    0x013E: 23,
    0x013F: 20,
    0x0140: 21,
    0x0142: 28,
    0x0143: 21,
    0x0144: 23,
    0x0145: 21,
    0x0146: 27,
    0x0147: 30,
    0x0148: 29,
    0x0149: 29,
    0x014A: 22,
    0x014B: 29,
    0x014C: 29,
    0x016C: 22,
    0x0182: 21,
    0x0183: 21,
    0x0184: 21,
    0x0185: 21,
    0x0186: 21,
    0x0187: 21,
    0x0188: 21,
    0x0191: 30,
    0x019F: 20,
    0x01A0: 20,
    0x01A1: 27,
    0x01BC: 21,
}

start_texts = [
    0xEF7858,  # attacked
    0xEF7866,  # blocked the way
    0xEF7879,  # came after you
    0xEF788B,  # trapped you
    0xEF789C,  # you encounter
    0xEF78AB,  # you meet
    0xEF78B8,  # you engage
    0xEF78C7,  # you confront
]

death_texts = [
    0xEF6D71,
    0xEF6D83,  # Stopped moving
    0xEF6D96,
    0xEF6DA7,  # disappeared
    0xEF6DB8,  # melted into thin air
    0xEF6DD8,  # broken into pieces
    0xEF6DF0,  # destroyed
    0xEF6E03,  # totally scrapped
    0xEF6E19,  # turned back to normal
    0xEF6E31,  # dust of the earth

]


weakness_table = {
    "Fire": {
             "Frog": 0,
             "Buffalo": 0,
             "Antoid": 0,
             "Mushroom": 0,
             "Fungus": 0,
             "Mobile Sprout": 0,
             "Fire Plug": 3,
             "Record": 0,
             "Power Robot": 3,
             "Reactor Robot": 3,
             "Hieroglyph": 0,
             "Asp Hieroglyph": 2,
             "Swoosh": 2,
             "Elemental": 0,
             "Moldyman": 3,
             "Mite": 0, 
             "Ant": 0,
             "Coffee Cup": 2,
             "Dice": 0,
             "Kraken": 2,
             "Robo": 3,
             "Roach": 0,
             "Sign": 2,
             "Shambler": 2,
             "Skelpion": 0,
             "Sphere": 0,
             "Zombie": 0,
             "Possessor": 3,
             "Dog": 0,
             "Oak": 0,
             "Octobot": 0,
             "Duck": 0,
             "Wolf": 0,
             "Eel": 0,
             "Arachnid": 0,
             "Demon": 0,
             "Fobby": 0,
             "Foppy": 0,
             "Booka": 3,
             "Mook": 0,
             "Ghost": 0, 
             "Slug": 0,
             "Mouse": 0,
             "Bomb": 2,
             "Tom": 0,
             "Sam": 0,
             "Fish": 3,
             "Kid": 0,
             "Boy": 0,
             "Shattered Man": 2,
             "Orb": 2,
             "Li'l UFO": 0,
             "UFO": 2,
             "Taxi": 2,
             "Molecule": 0,
             "Protoplasm": 0,
             "Robot": 2,
             "Psycho": 3,
             "Goat": 0,
             "Flame": 3,
             "Petunia": 0,
             "Ranboob": 0,
             "Noose": 0,
             "Pump": 2,
             "Crocodile": 2,
             "Fly": 0,
             "Crow": 0,
             "Caterpillar": 0,
             "Eye": 3,
             "Worm": 0,
             "Bot": 2,
             "Gangster": 0,
             "Tank": 0
             },

    "Freeze": {
             "Frog": 0,
             "Antoid": 0,
             "Mushroom": 0,
             "Fungus": 2,
             "Mobile Sprout": 0,
             "Fire Plug": 0,
             "Power Robot": 0,
             "Hieroglyph": 2,
             "Asp Hieroglyph": 0,
             "Elemental": 3,
             "Moldyman": 0,
             "Mite": 0,
             "Ant": 0,
             "Coffee Cup": 0,
             "Dice": 0,
             "Robo": 0,
             "Coil Snake": 0,
             "Roach": 0,
             "Skelpion": 0,
             "Sphere": 3,
             "Royal Guard": 2,
             "General": 2,
             "Zombie": 3,
             "Possessor": 0,
             "Dog": 0,
             "Oak": 2,
             "Octobot": 2,
             "Duck": 0,
             "Wolf": 0,
             "Pile of Puke": 2,
             "Arachnid": 0,
             "Demon": 3,
             "Fobby": 0,
             "Foppy": 0,
             "Mook": 3,
             "Ghost": 2,
             "Slug": 0,
             "Mouse": 0,
             "Tom": 2,
             "Sam": 2,
             "Fish's Brother": 3,
             "Kid": 0,
             "Boy": 3,
             "Orb": 0,
             "Li'l UFO": 2,
             "UFO": 2,
             "Taxi": 2,
             "Molecule": 0,
             "Protoplasm": 0,
             "Robot": 2,
             "Goat": 0,
             "Flame": 0,
             "Petunia": 3,
             "Ranboob": 2,
             "Noose": 2,
             "Pump": 2,
             "Fly": 0,
             "Crow": 0,
             "Caterpillar": 0,
             "Eye": 0,
             "Worm": 0,
             "Rat of Doom": 2,
             "Bot": 2,
             "Gangster": 0,
             "Tank": 0
             },
            
    "Flash": {
            "Fire Plug": 3,
            "Record": 3,
            "Power Robot": 2,
            "Reactor Robot": 2,
            "Swoosh": 0,
            "Menace": 3,
            "Spirit": 3,
            "Elemental": 0,
            "Mite": 3,
            "Coffee Cup": 2,
            "Dice": 2,
            "Sign": 3,
            "Starman": 2,
            "Sphere": 3,
            "Zombie": 0,
            "Possessor": 0,
            "Dog": 0,
            "Octobot": 3, 
            "Musica": 2,
            "Kiss of Death": 2,
            "Tangoo": 0,
            "Ghost": 0,
            "Tom": 0,
            "Sam": 0,
            "Fish's Brother": 2,
            "Kid": 0,
            "Orb": 2,
            "Li'l UFO": 2,
            "UFO": 2,
            "Taxi": 2,
            "Molecule": 2,
            "Robot": 3,
            "Mole": 0, 
            "Pump": 2,
            "Crow": 0,
            "Caterpillar": 0,
            "Eye": 3,
            "Worm": 0,
            "Specter": 3,
            "Bot": 2,
            "Storm": 0,
            "Tank": 2
            },

    "Paralysis": {
            "Spook": 2,
            "Buffalo": 0,
            "Antoid": 0,
            "Fungus": 3,
            "Mobile Sprout": 0,
            "Power Robot": 3,
            "Reactor Robot": 3,
            "Asp Hieroglyph": 0,
            "Elemental": 3,
            "Bear": 2,
            "Bear Seven": 2,
            "Moldyman": 2,
            "Dice": 0,
            "Little Pile": 0, 
            "Coil Snake": 0,
            "Batty": 0,
            "Roach": 0,
            "Starman": 2, 
            "Royal Guard": 0,
            "General": 2,
            "Clock": 3,
            "Arachnid": 0,
            "Demon": 3,
            "Fobby": 0,
            "Foppy": 0,
            "Booka": 2,
            "Mook": 2,
            "Ghost": 0,
            "Slug": 0,
            "Fish's Brother": 2,
            "Boy": 3,
            "Art": 0,
            "Shattered Man": 0,
            "Orb": 3,
            "Taxi": 0,
            "Molecule": 0,
            "Protoplasm": 0,
            "Psycho": 2,
            "Mole": 0,
            "Petunia": 3, 
            "Fly": 0,
            "Crow": 0,
            "Caterpillar": 0,
            "Eye": 2,
            "Worm": 0,
            "Statue": 3,
            "Rat of Doom": 2,
            "Specter": 3,
            "Storm": 3,
            "Dino": 2,
            "Tank": 2
            },

    "Hypnosis": {
            "Buffalo": 2,
            "Antoid": 0,
            "Mushroom": 3,
            "Mobile Sprout": 3,
            "Fire Plug": 3,
            "Record": 3,
            "Power Robot": 2,
            "Reactor Robot": 2,
            "Hieroglyph": 0,
            "Asp Hieroglyph": 0,
            "Menace": 2,
            "Spirit": 2,
            "Elemental": 0,
            "Moldyman": 0,
            "Coffee Cup": 2,
            "Dice": 3,
            "Kraken": 2,
            "Coil Snake": 0,
            "Batty": 3,
            "Roach": 3,
            "Sign": 0,
            "Skelpion": 0,
            "Sphere": 0,
            "Dog": 0,
            "Octobot": 2,
            "Duck": 2,
            "Clock": 0, 
            "Pile of Puke": 2,
            "Kiss of Death": 0,
            "Eel": 2,
            "Arachnid": 3,
            "Demon": 2,
            "Fobby": 3,
            "Foppy": 3,
            "Booka": 0,
            "Mook": 0,
            "Ghost": 0,
            "Slug": 3,
            "Mouse": 2,
            "Bomb": 2,
            "Tom": 3,
            "Fish": 2,
            "Fish's Brother": 2,
            "Kid": 0,
            "Boy": 2,
            "Art": 2,
            "Orb": 2,
            "Li'l UFO": 3,
            "UFO": 3,
            "Taxi": 2,
            "Molecule": 3,
            "Protoplasm": 3,
            "Psycho": 3,
            "Goat": 0,
            "Mole": 2,
            "Flame": 2,
            "Petunia": 2, 
            "Noose": 3,
            "Pump": 2,
            "Fly": 3,
            "Caterpillar": 0,
            "Worm": 0,
            "Rat of Doom": 2,
            "Specter": 2,
            "Bot": 2,
            "Tank": 2
            }
}
