from BaseClasses import ItemClassification

items = {
    "Space Zone Progression": ItemClassification.progression,
    "Space Zone Secret": ItemClassification.progression,
    "Tree Zone Progression": ItemClassification.progression,
    "Tree Zone Progression x2": ItemClassification.progression,
    "Tree Zone Secret": ItemClassification.progression,
    "Macro Zone Progression": ItemClassification.progression,
    "Macro Zone Progression x2": ItemClassification.progression,
    "Macro Zone Secret 1": ItemClassification.progression,
    "Macro Zone Secret 2": ItemClassification.progression_skip_balancing,
    "Pumpkin Zone Progression": ItemClassification.progression,
    "Pumpkin Zone Progression x2": ItemClassification.progression,
    "Pumpkin Zone Secret 1": ItemClassification.progression,
    "Pumpkin Zone Secret 2": ItemClassification.progression,
    "Mario Zone Progression": ItemClassification.progression,
    "Mario Zone Progression x2": ItemClassification.progression,
    "Turtle Zone Progression": ItemClassification.progression,
    "Turtle Zone Progression x2": ItemClassification.progression,
    "Turtle Zone Secret": ItemClassification.progression,
    "Tree Coin": ItemClassification.progression_skip_balancing,
    "Space Coin": ItemClassification.progression_skip_balancing,
    "Macro Coin": ItemClassification.progression_skip_balancing,
    "Pumpkin Coin": ItemClassification.progression_skip_balancing,
    "Mario Coin": ItemClassification.progression_skip_balancing,
    "Turtle Coin": ItemClassification.progression_skip_balancing,
    "Mushroom": ItemClassification.progression,
    "Fire Flower": ItemClassification.progression,
    "Carrot": ItemClassification.progression,
    "Space Physics": ItemClassification.progression_skip_balancing,
    "Hippo Bubble": ItemClassification.progression_skip_balancing,
    "Swim": ItemClassification.progression,
    "Pipe Traversal":  ItemClassification.progression,
    "Pipe Traversal - Down":  ItemClassification.progression,
    "Pipe Traversal - Up":  ItemClassification.progression,
    "Pipe Traversal - Right":  ItemClassification.progression,
    "Pipe Traversal - Left":  ItemClassification.progression_skip_balancing,
    "Super Star Duration Increase": ItemClassification.filler,
    "Easy Mode": ItemClassification.useful,
    "Normal Mode": ItemClassification.trap,
    "Auto Scroll": ItemClassification.trap,
    "Mushroom Zone Midway Bell": ItemClassification.filler,
    "Tree Zone 1 - Invincibility! Midway Bell": ItemClassification.filler,
    "Tree Zone 2 - In the Trees Midway Bell": ItemClassification.progression_skip_balancing,
    "Tree Zone 4 - Honeybees Midway Bell": ItemClassification.progression_skip_balancing,
    "Tree Zone 5 - The Big Bird Midway Bell": ItemClassification.filler,
    "Space Zone 1 - Moon Stage Midway Bell": ItemClassification.filler,
    "Space Zone 2 - Star Stage Midway Bell": ItemClassification.progression_skip_balancing,
    "Macro Zone 1 - The Ant Monsters Midway Bell": ItemClassification.progression_skip_balancing,
    "Macro Zone 2 - In the Syrup Sea Midway Bell": ItemClassification.progression_skip_balancing,
    "Macro Zone 3 - Fiery Mario-Special Agent Midway Bell": ItemClassification.progression_skip_balancing,
    "Macro Zone 4 - One Mighty Mouse Midway Bell": ItemClassification.filler,
    "Pumpkin Zone 1 - Bat Course Midway Bell": ItemClassification.progression_skip_balancing,
    "Pumpkin Zone 2 - Cyclops Course Midway Bell": ItemClassification.filler,
    "Pumpkin Zone 3 - Ghost House Midway Bell": ItemClassification.filler,
    "Pumpkin Zone 4 - Witch's Mansion Midway Bell": ItemClassification.filler,
    "Mario Zone 1 - Fiery Blocks Midway Bell": ItemClassification.progression_skip_balancing,
    "Mario Zone 2 - Mario the Circus Star! Midway Bell": ItemClassification.filler,
    "Mario Zone 3 - Beware: Jagged Spikes Midway Bell": ItemClassification.filler,
    "Mario Zone 4 - Three Mean Pigs! Midway Bell": ItemClassification.filler,
    "Turtle Zone 1 - Cheep Cheep Course Midway Bell": ItemClassification.filler,
    "Turtle Zone 2 - Turtle Zone Midway Bell": ItemClassification.progression_skip_balancing,
    "Turtle Zone 3 - Whale Course Midway Bell": ItemClassification.filler,
}