address_to_name = {
    0x9330: "Transfer Station Save",
    0x9bb8: "Transfer Station",
    0x97c2: "Ruined Concourse",
    0x9a32: "Vulnar Caves Map Station",
    0x94b6: "Crumbling Basement",
    0x96ff: "Immersion Pool",
    0x9774: "Hall Of The Elders",
    0xa32f: "Causeway",
    0xa293: "Mezzanine Concourse",
    0x9468: "Eribium Apparatus Access",
    0x9fd5: "East Spore Field",
    0x9504: "Waste Processing",
    0x9b91: "Cellar Access",
    0x979b: "Cistern Access Tunnel",
    0x9b1c: "Cistern",
    0x9294: "Path Of The Warrior",
    0x9f39: "Causeway Overlook",
    0xec19: "Excavation Site",
    0xd7bd: "Transit Concourse",
    0x985e: "Eribium Apparatus Room",
    0x99e4: "Spore Field Supply Cache",
    0x9357: "East Spore Field Access",
    0x948f: "Exhaust Vent",
    0x813a: "Cellar",
    0x926d: "Roosting Cavern",
    0x921f: "Warrior Shrine Access",
    0x80ac: "Crypt Access",
    0x9921: "Arena Save Station",
    0x9b43: "Excavation Site Access",
    0x9eeb: "Construction Site",
    0xdd9d: "East Terminal",
    0xa245: "Transit Tunnel",
    0xbc25: "Grand Chasm",
    0x9e4f: "Summit Landing",
    0x0: "elevator",
    0xa10d: "Spore Collection",
    0x941a: "Subbasement",
    0x98d3: "Trophobiotic Chamber",
    0x974d: "Way Of The Watcher",
    0x8857: "West Spore Field",
    0x9948: "Warrior Shrine",
    0x92e2: "Crypt",
    0x8cb7: "Arena Access",
    0xe797: "Laboratory Workshop",
    0x9f60: "Epiphreatic Crag",
    0xe4c3: "Clifftop Cranny",
    0xd842: "West Terminal",
    0x9d3e: "Frozen Trail",
    0x9d8c: "Antechamber",
    0xe059: "Wrecked Maintenance Deck",
    0xeca5: "Wrecked Machine Room",
    0xbf15: "Wrecked Command Deck",
    0xa0e6: "Spore Generator Access",
    0xa071: "West Spore Field Access",
    0x93cc: "Subbasement Fissure",
    0x96d8: "Vulnar Caves Entrance",
    0x9996: "Path Of Swords",
    0x8065: "Upper Vulnar Power Node",
    0xe47d: "Grand Vault",
    0x98ac: "Watcher Save Station",
    0xa1f7: "Monitoring Station",
    0xa21e: "Archives Access",
    0x9cc9: "Sensor Maintenance",
    0x9ffc: "Great Spore Hall",
    0x93a5: "Sporous Nook",
    0x9af5: "Great Spore Pool",
    0xbbc0: "Arena",
    0xe1b7: "West Corridor",
    0x8dcf: "Isobaric Vent",
    0x89b5: "Cracked Cliffside Cave",
    0x81c7: "West Terminal Access",
    0x9e9d: "Grand Promenade",
    0x95ee: "Cargo Rail Save Station",
    0x9e28: "Icy Flow",
    0xbe04: "Summit Save Station",
    0x8000: "Aurora Unit Wreckage",
    0xbe79: "Wrecked Weapon Control Center",
    0xe013: "Wrecked Observation Deck",
    0xe0e5: "Wrecked Main Engineering",
    0xbeee: "Windswept Rise",
    0x9309: "Spore Field Save Station",
    0xec5f: "Spore Generation Chamber",
    0xa134: "Subbasement Energy Station",
    0xa1a9: "Vulnar Depths Elevator E",
    0xeabb: "Vulnar Caves Access",
    0x963c: "Vulnar Caves Supply Cache",
    0x937e: "Auxiliary Pump Room",
    0xe3f1: "Archives Control Room",
    0x9579: "Hot Spring",
    0x866d: "West Spore Field Item",
    0xe171: "West Corridor Save Station",
    0x8555: "Laboratory Map Station",
    0xb6fe: "Equipment Locker",
    0xe243: "Hydrology Research Access",
    0x84c9: "Hydrodynamic Chamber",
    0x908b: "Loading Dock Security Area",
    0x8fff: "Reliquary",
    0x8d89: "Central Corridor Save Station",
    0x8b59: "Vulnar Canyon",
    0xbb5b: "Impact Crater",
    0xc4d3: "Meeting Hall",
    0x9e01: "Snow Cache",
    0x9dda: "Ice Cave",
    0x9db3: "Glacier's Reach",
    0xbdb6: "Condenser Access",
    0x9d65: "Stair Of Night",
    0xf447: "Wrecked Save Station",
    0xe09f: "Wrecked Map Station",
    0xbec7: "Wrecked Forward Battery",
    0x996f: "Harmonic Growth Enhancer",
    0xa3cb: "Placid Pool",
    0xd549: "Elevator To Vulnar Caves E",
    0xa26c: "Archives",
    0x9ace: "Vulnar Depths Elevator W",
    0xb962: "Hydrology Security Area 1",
    0x89fb: "Main Hydrology Research",
    0x90d1: "Central Corridor",
    0x8e15: "Loading Dock Ammo Station",
    0x8cfd: "Loading Dock Storage Area",
    0xb679: "Loading Dock",
    0x8627: "Reliquary Access",
    0x8acd: "Foyer",
    0x8b9f: "Canyon Passage",
    0xda9b: "Subterranean Burrow",
    0x9441: "Impact Crater Overlook",
    0x93f3: "Free Fall",
    0xc4fa: "Meeting Hall Access",
    0xc98e: "Condenser",
    0xc680: "Preparation Chamber",
    0xc5e4: "Stair Of Dawn",
    0x8a41: "Wrecked Crew Quarters",
    0x9bdf: "Vulnar Depths Elevator N",
    0xf189: "Hive Entrance Save Station",
    0xd597: "Hive Entrance",
    0xcd0f: "Vulnar Caves Elevator W",
    0xb9c7: "Hydrology Security Area 2",
    0xbaf6: "Hydrology Security Area 3",
    0xb783: "Antelier",
    0x8a87: "Restricted Area",
    0x8c2b: "Containment Area",
    0xf1d7: "Mass Driver",
    0x9ec4: "Sanctuary Save Station",
    0xea75: "East Corridor",
    0x8b13: "Foyer Energy Station",
    0x8be5: "Norak Brook",
    0xa37d: "Crater Save Station",
    0xba2c: "Sunken Nest",
    0xa0bf: "Impact Crater Alcove",
    0xc596: "Stair Of Twilight",
    0xc6f5: "Elevator To Intake Pump",
    0xc659: "Anticipation Chamber",
    0xc632: "Sun's Succor",
    0x9aa7: "Odd Chamber",
    0x859b: "Wrecked Crew Quarters Access",
    0xd98d: "Wrecked Weapon Locker",
    0xf273: "Wrecked Aft Battery",
    0xd069: "Elevator To Vulnar Caves N",
    0xd633: "Hive Main Chamber",
    0xccc1: "Verdite Mines Entrance",
    0xede1: "Mines Map Station",
    0xb808: "Weapon Research",
    0xbe2b: "Bygone Course",
    0xc0e9: "Cargo Transfer Port",
    0x8f73: "Brooding Chamber",
    0xc5bd: "Stair Of Dusk",
    0x8483: "Foundry",
    0xcac6: "Norak Escarpment",
    0x896f: "Norak Perimeter",
    0x850f: "Ocean Shore",
    0xc56f: "Armory",
    0xedba: "Elevator To Condenser",
    0x9e76: "Condenser Save Station",
    0x86b3: "Deliberation Chamber",
    0xc4ac: "Sitting Room",
    0xc485: "Drawing Room",
    0xc60b: "Sky Loft",
    0x8299: "Wrecked Air Lock",
    0xd090: "Lava Pool",
    0xd01b: "Hollow Chamber",
    0xd5e5: "Hive Burrow",
    0xd60c: "Infested Passage",
    0xf46e: "Hive Map Station",
    0xcc4c: "Verdite Mines",
    0xbf3c: "Alluring Cenote",
    0xdc3f: "Cargo Bay",
    0x86f9: "Solarium",
    0xcf58: "Overgrown Tunnel",
    0x88e3: "Rocky Ridge Trail",
    0x82df: "Ocean Shallows",
    0xf29a: "Crashed Stern",
    0xc548: "Armory Cache 1",
    0x87cb: "Armory Cache 2",
    0xc521: "Armory Cache 3",
    0xf30f: "Intake Pump",
    0xc6a7: "Condenser Pump",
    0x91f8: "Vulnar Peak Map Station",
    0xba91: "Rocky Ridge",
    0xd0de: "Lava Pool Access",
    0xcff4: "Generator Access Tunnel",
    0xf078: "West Hive Tunnel",
    0x9cf0: "Thermal Reservoir 1",
    0xf051: "Hive Crossways",
    0xf225: "Verdite Mines Save Station",
    0x9246: "Mining Site 1",
    0xd12c: "Mining Site 3",
    0xcbfe: "Burning Trail",
    0xce20: "Mining Site 2",
    0xd153: "Raging Pit Access",
    0xc026: "Orbital Map Station",
    0xbfff: "Docking Port Access 4",
    0xc6ce: "Docking Port Access 3",
    0xde6f: "Lounge",
    0xdc85: "Station Corridor",
    0x873f: "Syzygy Observatorium",
    0x8c71: "Briar Bypass",
    0x8ee7: "Sediment Canyon",
    0xdeb5: "Sea Cave Shaft",
    0x8f2d: "Sediment Tunnel",
    0xa04a: "Oceania Map Station",
    0xcfa6: "Crashed Compartments",
    0xcfcd: "Crashed Metroid Storage",
    0xf162: "Thermal Reservoir 2",
    0x9c54: "Hydraulic Works Map Station",
    0x9c7b: "Frozen Lake Access",
    0xbe52: "Forbidden Room",
    0xd792: "Generator Central Corridor",
    0xe7dd: "Generator Save Station",
    0xdb27: "Crossway Save Station",
    0xd1a1: "Crossway Cache",
    0xf02a: "Sealed Shaft",
    0x836b: "Guard Station",
    0xef8e: "East Hive Tunnel",
    0xf003: "Twisted Tunnel",
    0xee08: "Mining Cache",
    0xcbd7: "Fiery Gallery",
    0xee2f: "Raging Pit",
    0xcb14: "Docking Port 4",
    0xcaed: "Docking Port 3",
    0xcdab: "Gantry",
    0xde29: "Docking Port 1 Access",
    0xdd57: "Fighter Bay Access",
    0xd411: "Docking Port 2 Access",
    0xc7b8: "Briar Access",
    0xc7df: "Briar",
    0x8e5b: "Sediment Floor",
    0x8fb9: "Sandy Gully",
    0x9c06: "Sea Cave Narrows",
    0xa182: "Sandy Burrow",
    0x8325: "Sandy Cache",
    0xa1d0: "Sediment Flow",
    0xf09f: "Crashed Aft",
    0x889d: "Crashed Extract Storage",
    0xf1b0: "Reservoir Maintenance Tunnel",
    0xf13b: "Boiler Bump",
    0x8929: "Frozen Lake Wall",
    0xd042: "Power Distribution Center",
    0xcc9a: "Depressurization Valve",
    0xcdd2: "Security Interlock",
    0xf384: "Sequestered Inferno",
    0x843d: "Guard Station Bridge",
    0x8811: "Path Of Fire",
    0xee7d: "Outer Chamber",
    0xcc73: "Elevator To Turbid Passage",
    0xeecb: "Fiery Crossing",
    0xef67: "Elevator To Magma Lake",
    0xdde3: "Docking Port 1",
    0xcb3b: "Ready Room",
    0xdd11: "Fighter Bay",
    0xd3ea: "Docking Port 2",
    0xc806: "Overgrown Energy Station",
    0x9f12: "Meandering Passage",
    0x9726: "Turbid Passage",
    0x952b: "Karst Aquifer",
    0xa2e1: "Sea Cave Upper Hall",
    0xce47: "Crashed Lower Deck",
    0xf1fe: "Thermal Reservoir 3",
    0xef40: "Conduit Hall",
    0xd0b7: "Security Matrix",
    0xcc25: "Main Boiler",
    0xcce8: "Central Control Room",
    0xeef2: "Fire's Boon Shrine",
    0xf420: "Fire's Bane Shrine Access",
    0xd105: "Fire Temple Courtyard",
    0xf24c: "Magma Forge",
    0xee56: "Slag Heap",
    0x9a80: "Elevator To Fiery Gallery",
    0xef19: "Fiery Crossing Cache",
    0xefb5: "Elevator To Raging Pit",
    0xdccb: "Docking Umbilical 1",
    0xd3c3: "Docking Umbilical 2",
    0xc82d: "Veranda",
    0xa3a4: "Murky Gallery",
    0xa356: "Submarine Alcove",
    0xa308: "Ocean Vent Monitor Access",
    0x94dd: "Eddy Channel",
    0x9fae: "Submarine Nest",
    0xa098: "Sea Caves Lower Hall",
    0xd908: "Crashed Torpedo Bay",
    0xbea0: "Magma Pump",
    0xf3ab: "Central Control Room Access",
    0xf3f9: "Generator Manifold",
    0x8253: "Primary Turbine Shaft",
    0xf336: "Corrupted Hall",
    0xed75: "Ancient Shaft",
    0xeea4: "Magma Furnace",
    0xefdc: "Magma Lake Access",
    0xf0c6: "Magma Lake Cache Access",
    0xeb01: "Air Lock",
    0xd39c: "Stern",
    0xc854: "Shrine Of Fervor",
    0xb8fd: "Hopper Nest",
    0xc9b5: "Chamber Of Life",
    0xc374: "Jungle Map Station Access",
    0x9ca2: "Submarine Crevice",
    0x92bb: "Ocean Vent Save Station",
    0x95a0: "Submarine Nest Save Station",
    0x83b1: "Kraid's Lair",
    0x9c2d: "Dark Hollow",
    0x9552: "Flotation Chamber",
    0x97e9: "Magma Pump Access",
    0x8ea1: "Electromechanical Engine",
    0xda0f: "Corrupted Oblivion Gate",
    0xcdf9: "Gymnasium",
    0xcb62: "Ancient Basin",
    0xed30: "Lost Cache",
    0x85e1: "Fire's Bane Shrine",
    0xd570: "Dark Crevice",
    0xb5f4: "Magma Chamber",
    0xf0ed: "Magma Lake Cache",
    0xdf41: "Crew Quarters Access",
    0x9d17: "Compartments",
    0xebd3: "Metroid Storage",
    0xca03: "Chamber Of Stone",
    0xc71c: "Chamber Of Wind Access",
    0xc9dc: "Jungle Save Station",
    0xc39b: "Jungle Ruins Map Station",
    0xa3f2: "Benthic Shaft",
    0xa2ba: "Ocean Vent Monitor",
    0xea2f: "Shrine Of The Penumbra",
    0x95c7: "Rocky Crevice",
    0x9a59: "Magma Plume",
    0xf114: "Generator Depot",
    0x9837: "Ancient Basin Access",
    0xd4fb: "Dark Crevice Cache",
    0xdae1: "Magma Lake Save Station",
    0xd17a: "Magma Lake Tunnel",
    0xd4d4: "Lake Monitoring Station",
    0xd522: "Magma Lake Bypass",
    0x9810: "Magma Lake Inlet",
    0xeb47: "Crew Quarters",
    0xc76a: "Aft",
    0xe1fd: "Extract Storage",
    0x8d43: "Garden Canal",
    0xca2a: "Water Garden",
    0xca51: "Elevator To Jungle's Heart",
    0x9117: "Chamber Of Wind",
    0x8785: "Benthic Cache Access",
    0x820d: "Ocean Vent",
    0x9045: "Ocean Vent Supply Depot",
    0xa15b: "Submarine Supply Cache",
    0x9f87: "Pile Anchor",
    0x9885: "Scorching Passage",
    0x9615: "Fierce Crevice",
    0x99bd: "Magma Lock",
    0x9663: "Searing Gate",
    0xf526: "Depot Save Station",
    0xcb89: "Collapsed Passage",
    0xdb6d: "Colosseum",
    0x968a: "Blazing Chasm",
    0xeb8d: "GFS Daphne Save Station",
    0xc09b: "GFS Daphne Map Station",
    0xc074: "Weapon Locker",
    0xbcf3: "Lower Deck",
    0xc791: "Wellspring Access",
    0xeceb: "Root Cavern",
    0x9b6a: "Benthic Cache",
    0xa023: "Tram To Suzi Island",
    0xcd5d: "Vulnar's Root Save Station",
    0x98fa: "Scorching Abyss Access",
    0x96b1: "Burning Depths Cache",
    0xcd36: "Elevator To Wellspring",
    0xcd84: "Hypogeum",
    0xe437: "Main Engineering",
    0xdbb3: "Torpedo Bay",
    0xcf7f: "Wellspring",
    0xe12b: "Malodorous Recess",
    0xc326: "Ocean Floor Tram",
    0xdfcd: "Scorching Abyss",
    0xc3c2: "Elevator To Ancient Basin",
    0xdf87: "Command Deck",
    0xc0c2: "Machine Room",
    0xc04d: "Fueling Port Access",
    0xca78: "Aft Battery Access",
    0xc743: "Jungle Supply Cache",
    0xc3e9: "Wellspring Cache",
    0xf4a1: "Crocomire's Lair",
    0xbd41: "Tram To Mainland",
    0x9a0b: "Twisting Conflagration",
    0xd9c9: "Aurora Unit Chamber",
    0x8181: "Bridge",
    0xdbf9: "Fueling Port",
    0xc87b: "Aft Battery",
    0xca9f: "Crocomire's Energy Station",
    0xbd68: "Suzi Island Ruins Entrance",
    0xdefb: "Greater Inferno",
    0xf35d: "Maintenance Deck",
    0xbd8f: "Plaza",
    0xf3d2: "Weapon Control Center",
    0xf2e8: "Observation Deck",
    0xf2c1: "Forward Battery Access",
    0xc45e: "Flooded Atrium",
    0x915d: "Forward Battery",
    0xd5be: "Suzi Ruins Save Station",
    0xc437: "Suzi Ruins Map Station Access",
    0xd2d9: "Sandy Tunnel",
    0xd28b: "Dark Nest",
    0xd4ad: "Watery Walkway",
    0xd6a8: "Data Storage",
    0xd681: "Portico Access",
    0xc2d8: "Nexus",
    0xc410: "Suzi Ruins Map Station",
    0xd2b2: "Sandy Cascade",
    0xd264: "Stilted Hall",
    0xd216: "Rock Garden",
    0xd45f: "Curious Cellar",
    0xd65a: "Portico",
    0xc2ff: "Elevator To Thunder Laboratory",
    0xd23d: "Sand Pits",
    0xd486: "Ancient Arcade",
    0xd1c8: "Suzi Island Energy Station",
    0xd438: "Broken Stair",
    0xd76b: "Moughra Beach",
    0xc34d: "Elevator To Sunken Ruins",
    0xd744: "Echo Climb",
    0xcbb0: "Moughra Lagoon",
    0xbfb1: "Parlor Access",
    0x80f3: "Path Of Alacrity",
    0xd71d: "Shadow Dungeon",
    0xd6cf: "Obscured Vestibule",
    0xbfd8: "Tower Rock",
    0xcf31: "Reef Crevice",
    0xd34e: "Reef Floor Fissure",
    0xbd1a: "Parlor",
    0xd300: "Vesper Point",
    0xbca5: "Reef Save Station",
    0xce6e: "Reef Map Station",
    0xce95: "Tower Rock Lookout",
    0xcebc: "Tide Pool",
    0xcee3: "Spine Reef",
    0xd375: "Saline Cache",
    0xc23c: "Deep Reef Nest",
    0xc263: "Rocky Bore",
    0xbf8a: "Convocation Grounds",
    0xcf0a: "Reef Nook",
    0xd6f6: "Reef Key Cache",
    0xd327: "Castle Rock",
    0xc28a: "Remembrance Hall",
    0xd1ef: "Thunder Laboratory Save Station",
    0xbf63: "Drumming Hall",
    0xbccc: "Enervation Chamber",
    0xda55: "Sanctum",
    0xc2b1: "Reef Floor Key Cache",
    0xbddd: "Thunder Laboratory Supply Station",
    0xc215: "Shrine Of The Animate Spark",
}
