from typing import Dict, NamedTuple, Optional

from BaseClasses import Item, ItemClassification


class KHRECOMItem(Item):
    game: str = "Kingdom Hearts RE Chain of Memories"


class KHRECOMItemData(NamedTuple):
    category: str
    sub: str = "None"
    code: Optional[int] = None
    classification: ItemClassification = ItemClassification.filler
    max_quantity: int = 1
    weight: int = 1


def get_items_by_category(category: str, disclude: list) -> Dict[str, KHRECOMItemData]:
    item_dict: Dict[str, KHRECOMItemData] = {}
    for name, data in item_table.items():
        if data.category == category and all(x not in name for x in disclude):
            item_dict.setdefault(name, data)

    return item_dict


item_table: Dict[str, KHRECOMItemData] = {
    #Victory
    "Victory":                           KHRECOMItemData("Victory",          code = 268_0000, classification = ItemClassification.progression, max_quantity = 1, weight = 10),
    #Battle Cards
    "Card Set Kingdom Key":              KHRECOMItemData("Sets",             code = 268_1001, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Three Wishes":             KHRECOMItemData("Sets",             code = 268_1002, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Crabclaw":                 KHRECOMItemData("Sets",             code = 268_1003, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Pumpkinhead":              KHRECOMItemData("Sets",             code = 268_1004, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Fairy Harp":               KHRECOMItemData("Sets",             code = 268_1005, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Wishing Star":             KHRECOMItemData("Sets",             code = 268_1006, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Spellbinder":              KHRECOMItemData("Sets",             code = 268_1007, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Metal Chocobo":            KHRECOMItemData("Sets",             code = 268_1008, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Olympia":                  KHRECOMItemData("Sets",             code = 268_1009, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Lionheart":                KHRECOMItemData("Sets",             code = 268_1010, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Lady Luck":                KHRECOMItemData("Sets",             code = 268_1011, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Divine Rose":              KHRECOMItemData("Sets",             code = 268_1012, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Oathkeeper":               KHRECOMItemData("Sets",             code = 268_1013, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Oblivion":                 KHRECOMItemData("Sets",             code = 268_1014, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Diamond Dust":             KHRECOMItemData("Sets",             code = 268_1015, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set One Winged Angel":         KHRECOMItemData("Sets",             code = 268_1016, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Ultima Weapon":            KHRECOMItemData("Sets",             code = 268_1017, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Soul Eater":               KHRECOMItemData("Days Sets",        code = 268_1018, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Star Seeker":              KHRECOMItemData("Days Sets",        code = 268_1019, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Total Eclipse":            KHRECOMItemData("Days Sets",        code = 268_1020, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Midnight Roar":            KHRECOMItemData("Days Sets",        code = 268_1021, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Maverick Flare":           KHRECOMItemData("Days Sets",        code = 268_1022, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Two Become One":           KHRECOMItemData("Days Sets",        code = 268_1023, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Bond of Flame":            KHRECOMItemData("Days Sets",        code = 268_1024, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Fire":                     KHRECOMItemData("Sets",             code = 268_1025, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Blizzard":                 KHRECOMItemData("Sets",             code = 268_1026, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Thunder":                  KHRECOMItemData("Sets",             code = 268_1027, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Cure":                     KHRECOMItemData("Sets",             code = 268_1028, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Gravity":                  KHRECOMItemData("Sets",             code = 268_1029, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Stop":                     KHRECOMItemData("Sets",             code = 268_1030, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Aero":                     KHRECOMItemData("Sets",             code = 268_1031, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Simba":                    KHRECOMItemData("Sets",             code = 268_1032, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Genie":                    KHRECOMItemData("Sets",             code = 268_1033, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Bambi":                    KHRECOMItemData("Sets",             code = 268_1034, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Dumbo":                    KHRECOMItemData("Sets",             code = 268_1035, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Tinker Bell":              KHRECOMItemData("Sets",             code = 268_1036, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Mushu":                    KHRECOMItemData("Sets",             code = 268_1037, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Cloud":                    KHRECOMItemData("Sets",             code = 268_1038, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Potion":                   KHRECOMItemData("Sets",             code = 268_1039, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Hi-Potion":                KHRECOMItemData("Sets",             code = 268_1040, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Mega-Potion":              KHRECOMItemData("Sets",             code = 268_1041, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Ether":                    KHRECOMItemData("Sets",             code = 268_1042, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Mega-Ether":               KHRECOMItemData("Sets",             code = 268_1043, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Elixir":                   KHRECOMItemData("Sets",             code = 268_1044, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),
    "Card Set Megalixir":                KHRECOMItemData("Sets",             code = 268_1045, classification = ItemClassification.filler,      max_quantity = 1, weight = 10),

    "Enemy Card Shadow":                 KHRECOMItemData("Enemy Cards",      code = 268_1101, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Soldier":                KHRECOMItemData("Enemy Cards",      code = 268_1102, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Large Body":             KHRECOMItemData("Enemy Cards",      code = 268_1103, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Red Nocturne":           KHRECOMItemData("Enemy Cards",      code = 268_1104, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Blue Rhapsody":          KHRECOMItemData("Enemy Cards",      code = 268_1105, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Yellow Opera":           KHRECOMItemData("Enemy Cards",      code = 268_1106, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Green Requiem":          KHRECOMItemData("Enemy Cards",      code = 268_1107, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Powerwild":              KHRECOMItemData("Enemy Cards",      code = 268_1108, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Bouncywild":             KHRECOMItemData("Enemy Cards",      code = 268_1109, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Air Soldier":            KHRECOMItemData("Enemy Cards",      code = 268_1110, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Bandit":                 KHRECOMItemData("Enemy Cards",      code = 268_1111, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Fat Bandit":             KHRECOMItemData("Enemy Cards",      code = 268_1112, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Barrel Spider":          KHRECOMItemData("Enemy Cards",      code = 268_1113, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Search Ghost":           KHRECOMItemData("Enemy Cards",      code = 268_1114, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Sea Neon":               KHRECOMItemData("Enemy Cards",      code = 268_1115, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Screwdiver":             KHRECOMItemData("Enemy Cards",      code = 268_1116, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Aquatank":               KHRECOMItemData("Enemy Cards",      code = 268_1117, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Wight Knight":           KHRECOMItemData("Enemy Cards",      code = 268_1118, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Gargoyle":               KHRECOMItemData("Enemy Cards",      code = 268_1119, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Pirate":                 KHRECOMItemData("Enemy Cards",      code = 268_1120, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Air Pirate":             KHRECOMItemData("Enemy Cards",      code = 268_1121, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Darkball":               KHRECOMItemData("Enemy Cards",      code = 268_1122, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Defender":               KHRECOMItemData("Enemy Cards",      code = 268_1123, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Wyvern":                 KHRECOMItemData("Enemy Cards",      code = 268_1124, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Neoshadow":              KHRECOMItemData("Enemy Cards",      code = 268_1125, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card White Mushroom":         KHRECOMItemData("Enemy Cards",      code = 268_1126, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Black Fungus":           KHRECOMItemData("Enemy Cards",      code = 268_1127, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Creeper Plant":          KHRECOMItemData("Enemy Cards",      code = 268_1128, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Tornado Step":           KHRECOMItemData("Enemy Cards",      code = 268_1129, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Crescendo":              KHRECOMItemData("Enemy Cards",      code = 268_1130, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Guard Armor":            KHRECOMItemData("Enemy Cards",      code = 268_1131, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Parasite Cage":          KHRECOMItemData("Enemy Cards",      code = 268_1132, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Trickmaster":            KHRECOMItemData("Enemy Cards",      code = 268_1133, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Darkside":               KHRECOMItemData("Enemy Cards",      code = 268_1134, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Card Soldier":           KHRECOMItemData("Enemy Cards",      code = 268_1135, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Hades":                  KHRECOMItemData("Enemy Cards",      code = 268_1137, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Jafar":                  KHRECOMItemData("Enemy Cards",      code = 268_1139, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Oogie Boogie":           KHRECOMItemData("Enemy Cards",      code = 268_1140, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Ursula":                 KHRECOMItemData("Enemy Cards",      code = 268_1141, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Hook":                   KHRECOMItemData("Enemy Cards",      code = 268_1142, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Dragon Maleficent":      KHRECOMItemData("Enemy Cards",      code = 268_1143, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Riku":                   KHRECOMItemData("Enemy Cards",      code = 268_1144, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Axel":                   KHRECOMItemData("Enemy Cards",      code = 268_1145, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Larxene":                KHRECOMItemData("Enemy Cards",      code = 268_1146, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Vexen":                  KHRECOMItemData("Enemy Cards",      code = 268_1147, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Marluxia":               KHRECOMItemData("Enemy Cards",      code = 268_1148, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Lexaeus":                KHRECOMItemData("Enemy Cards",      code = 268_1149, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Ansem":                  KHRECOMItemData("Enemy Cards",      code = 268_1150, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Zexion":                 KHRECOMItemData("Days Enemy Cards", code = 268_1151, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Xemnas":                 KHRECOMItemData("Days Enemy Cards", code = 268_1152, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Xigbar":                 KHRECOMItemData("Days Enemy Cards", code = 268_1153, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Xaldin":                 KHRECOMItemData("Days Enemy Cards", code = 268_1154, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Saix":                   KHRECOMItemData("Days Enemy Cards", code = 268_1155, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Demyx":                  KHRECOMItemData("Days Enemy Cards", code = 268_1156, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Luxord":                 KHRECOMItemData("Days Enemy Cards", code = 268_1157, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),
    "Enemy Card Roxas":                  KHRECOMItemData("Days Enemy Cards", code = 268_1158, classification = ItemClassification.filler,      max_quantity = 1, weight = 3),

    "Sleight Sliding Dash":              KHRECOMItemData("Sleights",         code = 268_2001, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Blitz":                     KHRECOMItemData("Sleights",         code = 268_2002, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Stun Impact":               KHRECOMItemData("Sleights",         code = 268_2003, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Zantetsuken":               KHRECOMItemData("Sleights",         code = 268_2004, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Strike Raid":               KHRECOMItemData("Sleights",         code = 268_2005, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Sonic Blade":               KHRECOMItemData("Sleights",         code = 268_2006, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Ars Arcanum":               KHRECOMItemData("Sleights",         code = 268_2007, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Ragnarok":                  KHRECOMItemData("Sleights",         code = 268_2008, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Trinity Limit":             KHRECOMItemData("Sleights",         code = 268_2009, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Fira":                      KHRECOMItemData("Sleights",         code = 268_2010, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Blizzara":                  KHRECOMItemData("Sleights",         code = 268_2011, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Thundara":                  KHRECOMItemData("Sleights",         code = 268_2012, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Cura":                      KHRECOMItemData("Sleights",         code = 268_2013, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Gravira":                   KHRECOMItemData("Sleights",         code = 268_2014, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Stopra":                    KHRECOMItemData("Sleights",         code = 268_2015, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Aerora":                    KHRECOMItemData("Sleights",         code = 268_2016, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Firaga":                    KHRECOMItemData("Sleights",         code = 268_2017, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Blizzaga":                  KHRECOMItemData("Sleights",         code = 268_2018, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Thundaga":                  KHRECOMItemData("Sleights",         code = 268_2019, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Curaga":                    KHRECOMItemData("Sleights",         code = 268_2020, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Graviga":                   KHRECOMItemData("Sleights",         code = 268_2021, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Stopga":                    KHRECOMItemData("Sleights",         code = 268_2022, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Aeroga":                    KHRECOMItemData("Sleights",         code = 268_2023, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Fire Raid":                 KHRECOMItemData("Sleights",         code = 268_2024, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Blizzard Raid":             KHRECOMItemData("Sleights",         code = 268_2025, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Thunder Raid":              KHRECOMItemData("Sleights",         code = 268_2026, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Reflect Raid":              KHRECOMItemData("Sleights",         code = 268_2027, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Judgement":                 KHRECOMItemData("Sleights",         code = 268_2028, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Firaga Burst":              KHRECOMItemData("Sleights",         code = 268_2029, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Raging Storm":              KHRECOMItemData("Sleights",         code = 268_2030, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Mega Flare":                KHRECOMItemData("Sleights",         code = 268_2031, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Freeze":                    KHRECOMItemData("Sleights",         code = 268_2032, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Homing Blizzara":           KHRECOMItemData("Sleights",         code = 268_2033, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Aqua Splash":               KHRECOMItemData("Sleights",         code = 268_2034, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Magnet Spiral":             KHRECOMItemData("Sleights",         code = 268_2035, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Lethal Frame":              KHRECOMItemData("Sleights",         code = 268_2036, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Shock Impact":              KHRECOMItemData("Sleights",         code = 268_2037, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Tornado":                   KHRECOMItemData("Sleights",         code = 268_2038, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Quake":                     KHRECOMItemData("Sleights",         code = 268_2039, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Warpinator":                KHRECOMItemData("Sleights",         code = 268_2040, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Warp":                      KHRECOMItemData("Sleights",         code = 268_2041, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Bind":                      KHRECOMItemData("Sleights",         code = 268_2042, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Confuse":                   KHRECOMItemData("Sleights",         code = 268_2043, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Terror":                    KHRECOMItemData("Sleights",         code = 268_2044, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Synchro":                   KHRECOMItemData("Sleights",         code = 268_2045, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Gifted Miracle":            KHRECOMItemData("Sleights",         code = 268_2046, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Teleport":                  KHRECOMItemData("Sleights",         code = 268_2047, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Holy":                      KHRECOMItemData("Sleights",         code = 268_2048, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Proud Road LV2":            KHRECOMItemData("Sleights",         code = 268_2049, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Proud Road LV3":            KHRECOMItemData("Sleights",         code = 268_2050, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Splash LV2":                KHRECOMItemData("Sleights",         code = 268_2051, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Splash LV3":                KHRECOMItemData("Sleights",         code = 268_2052, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Paradise LV2":              KHRECOMItemData("Sleights",         code = 268_2053, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Paradise LV3":              KHRECOMItemData("Sleights",         code = 268_2054, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Idyll Romp":                KHRECOMItemData("Sleights",         code = 268_2055, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Flare Breath LV2":          KHRECOMItemData("Sleights",         code = 268_2056, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Flare Breath LV3":          KHRECOMItemData("Sleights",         code = 268_2057, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Showtime LV2":              KHRECOMItemData("Sleights",         code = 268_2058, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Showtime LV3":              KHRECOMItemData("Sleights",         code = 268_2059, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Twinkle LV2":               KHRECOMItemData("Sleights",         code = 268_2060, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Twinkle LV3":               KHRECOMItemData("Sleights",         code = 268_2061, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Cross-slash":               KHRECOMItemData("Sleights",         code = 268_2062, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Omnislash":                 KHRECOMItemData("Sleights",         code = 268_2063, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Cross-slash+":              KHRECOMItemData("Sleights",         code = 268_2064, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Magic LV2":                 KHRECOMItemData("Sleights",         code = 268_2065, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Magic LV3":                 KHRECOMItemData("Sleights",         code = 268_2066, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Stardust Blitz":            KHRECOMItemData("Sleights",         code = 268_2067, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Goofy Tornado LV2":         KHRECOMItemData("Sleights",         code = 268_2068, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Goofy Torando LV3":         KHRECOMItemData("Sleights",         code = 268_2069, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Goofy Smash":               KHRECOMItemData("Sleights",         code = 268_2070, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Wild Crush":                KHRECOMItemData("Sleights",         code = 268_2071, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Sandstorm LV2":             KHRECOMItemData("Sleights",         code = 268_2072, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Sandstorm LV3":             KHRECOMItemData("Sleights",         code = 268_2073, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Surprise! LV2":             KHRECOMItemData("Sleights",         code = 268_2074, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Surprise! LV3":             KHRECOMItemData("Sleights",         code = 268_2075, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Spiral Wave LV2":           KHRECOMItemData("Sleights",         code = 268_2076, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Spiral Wave LV3":           KHRECOMItemData("Sleights",         code = 268_2077, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Hummingbird LV2":           KHRECOMItemData("Sleights",         code = 268_2078, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Hummingbird LV3":           KHRECOMItemData("Sleights",         code = 268_2079, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Furious Volley LV2":        KHRECOMItemData("Sleights",         code = 268_2080, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Furious Volley LV3":        KHRECOMItemData("Sleights",         code = 268_2081, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Lucky Bounty LV2":          KHRECOMItemData("Sleights",         code = 268_2082, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),
    "Sleight Lucky Bounty LV3":          KHRECOMItemData("Sleights",         code = 268_2083, classification = ItemClassification.filler,      max_quantity = 1, weight = 5),

    "World Card Wonderland":             KHRECOMItemData("World Unlocks",    code = 268_3002, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "World Card Olympus Coliseum":       KHRECOMItemData("World Unlocks",    code = 268_3003, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "World Card Monstro":                KHRECOMItemData("World Unlocks",    code = 268_3004, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "World Card Agrabah":                KHRECOMItemData("World Unlocks",    code = 268_3005, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "World Card Halloween Town":         KHRECOMItemData("World Unlocks",    code = 268_3006, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "World Card Atlantica":              KHRECOMItemData("World Unlocks",    code = 268_3007, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "World Card Neverland":              KHRECOMItemData("World Unlocks",    code = 268_3008, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "World Card Hollow Bastion":         KHRECOMItemData("World Unlocks",    code = 268_3009, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "World Card 100 Acre Wood":          KHRECOMItemData("World Unlocks",    code = 268_3010, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "World Card Twilight Town":          KHRECOMItemData("World Unlocks",    code = 268_3011, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "World Card Destiny Islands":        KHRECOMItemData("World Unlocks",    code = 268_3012, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
   #"World Card Castle Oblivion":        KHRECOMItemData("World Unlocks",    code = 268_3013, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Traverse Town":      KHRECOMItemData("Gold Map Cards",   code = 268_3301, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Wonderland":         KHRECOMItemData("Gold Map Cards",   code = 268_3302, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Olympus Coliseum":   KHRECOMItemData("Gold Map Cards",   code = 268_3303, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Monstro":            KHRECOMItemData("Gold Map Cards",   code = 268_3304, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Agrabah":            KHRECOMItemData("Gold Map Cards",   code = 268_3305, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Halloween Town":     KHRECOMItemData("Gold Map Cards",   code = 268_3306, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Atlantica":          KHRECOMItemData("Gold Map Cards",   code = 268_3307, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Neverland":          KHRECOMItemData("Gold Map Cards",   code = 268_3308, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Hollow Bastion":     KHRECOMItemData("Gold Map Cards",   code = 268_3309, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Twilight Town":      KHRECOMItemData("Gold Map Cards",   code = 268_3311, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Destiny Islands":    KHRECOMItemData("Gold Map Cards",   code = 268_3312, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Key to Rewards Castle Oblivion":    KHRECOMItemData("Gold Map Cards",   code = 268_3313, classification = ItemClassification.progression, max_quantity = 1, weight = 1),

    #Friend Cards
    "Friend Card Donald":                KHRECOMItemData("Friend Cards",     code = 268_5001, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Friend Card Goofy":                 KHRECOMItemData("Friend Cards",     code = 268_5002, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Friend Card Aladdin":               KHRECOMItemData("Friend Cards",     code = 268_5003, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Friend Card Ariel":                 KHRECOMItemData("Friend Cards",     code = 268_5004, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Friend Card Beast":                 KHRECOMItemData("Friend Cards",     code = 268_5005, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Friend Card Peter Pan":             KHRECOMItemData("Friend Cards",     code = 268_5006, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Friend Card Jack":                  KHRECOMItemData("Friend Cards",     code = 268_5007, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
    "Friend Card Pluto":                 KHRECOMItemData("Manual Placement", code = 268_5008, classification = ItemClassification.progression, max_quantity = 1, weight = 1),
}

event_item_table: Dict[str, KHRECOMItemData] = {
}
