Ha1 = "Pooh's House"
Ha2 = "Piglet's House"
Ha3 = "Rabbit's House"
Ha4 = "Roo's House"
Ha5 = "Spooky Cave"
Ha6 = "Starry Hill"

SoraLevels = "Sora's Levels"
GoA = "Garden Of Assemblage"
Keyblade = "Weapon Slots"

Valor = "Valor Form"
Wisdom = "Wisdom Form"
Limit = "Limit Form"
Master = "Master Form"
Final = "Final Form"
Summon = "Summons"
# sp
Sp = "Space Paranoids 1"
HostileProgram = "Hostile Program"
Sp2 = "Space Paranoids 2"
Mcp = "Master Control Program"
ASLarxene = "AS Larxene"
DataLarxene = "Data Larxene"

# pr
Pr = "Port Royal 1"
Barbosa = "Barbosa"
Pr2 = "Port Royal 2"
GrimReaper1 = "Grim Reaper 1"
GrimReaper2 = "Grim Reaper 2"
DataLuxord = "Data Luxord"

# tt
Tt = "Twilight Town 1"
Tt2 = "Twilight Town 2"
Tt3 = "Twilight Town 3"
DataAxel = "Data Axel"

# oc
Oc = "Olympus Coliseum 1"
Cerberus = "Cerberus"
OlympusPete = "Olympus Pete"
Hydra = "Hydra"
OcPainAndPanicCup = "Pain and Panic Cup"
OcCerberusCup = "Cerberus Cup"
Oc2 = "Olympus Coliseum 2"
Hades = "Hades"
ASZexion = "AS Zexion"
DataZexion = "Data Zexion"
Oc2TitanCup = "Titan Cup"
Oc2GofCup = "Goddess of Fate Cup"
Oc2Cups = "Olympus Coliseum Cups"
HadesCups = "Olympus Coliseum Hade's Paradox"

# ht
Ht = "Halloween Town 1"
PrisonKeeper = "Prison Keeper"
OogieBoogie = "Oogie Boogie"
Ht2 = "Halloween Town 2"
Experiment = "The Experiment"
ASVexen = "AS Vexen"
DataVexen = "Data Vexen"

# lod
LoD = "Land of Dragons 1"
ShanYu = "Shan Yu"
LoD2 = "Land of Dragons 2"
AnsemRiku = "Ansem Riku"
StormRider = "Storm Rider"
DataXigbar = "Data Xigbar"

# twtnw
Twtnw = "The World That Never Was (Pre Roxas)"
Roxas = "Roxas"
Xigbar = "Xigbar"
Luxord = "Luxord"
Saix = "Saix"
Twtnw2 = "The World That Never Was (Second Visit)"  # Post riku transformation
Xemnas = "Xemnas"
ArmoredXemnas = "Armored Xemnas"
ArmoredXemnas2 = "Armored Xemnas 2"
FinalXemnas = "Final Xemnas"
DataXemnas = "Data Xemnas"

# bc
Bc = "Beast's Castle 1"
Thresholder = "Thresholder"
Beast = "Beast"
DarkThorn = "Dark Thorn"
Bc2 = "Beast's Castle 2"
Xaldin = "Xaldin"
DataXaldin = "Data Xaldin"

# ag
Ag = "Agrabah 1"
TwinLords = "Twin Lords"
Ag2 = "Agrabah 2"
GenieJafar = "Genie Jafar"
ASLexaeus = "AS Lexaeus"
DataLexaeus = "Data Lexaeus"

# pl
Pl = "Pride Lands 1"
Scar = "Scar"
Pl2 = "Pride Lands 2"
GroundShaker = "Groundshaker"
DataSaix = "Data Saix"

# hb
Hb = "Hollow Bastion 1"
Hb2 = "Hollow Bastion 2"
HBDemyx = "Hollow Bastion Demyx"
ThousandHeartless = "Thousand Heartless"
Mushroom13 = "Mushroom 13"
Sephi = "Sephiroth"
DataDemyx = "Data Demyx"

# CoR
CoR = "Cavern of Rememberance"
CorFirstFight = "Cavern of Rememberance:Fight 1"
CorSecondFight = "Cavern of Rememberance:Fight 2"
Transport = "Transport to Rememberance"

# dc
Dc = "Disney Castle"
Tr = "Timeless River"
OldPete = "Old Pete"
FuturePete = "Future Pete"
ASMarluxia = "AS Marluxia"
DataMarluxia = "Data Marluxia"
Terra = "Terra"

# stt
Stt = "Simulated Twilight Town"
TwilightThorn = "Twilight Thorn"
Axel1 = "Axel 1"
Axel2 = "Axel 2"
DataRoxas = "Data Roxas"

AtlanticaSongOne = "Atlantica First Song"
AtlanticaSongTwo = "Atlantica Second Song"
AtlanticaSongThree = "Atlantica Third Song"
AtlanticaSongFour = "Atlantica Fourth Song"

LevelsVS1 = "Levels Region (1 Visit Locking Item)"
LevelsVS3 = "Levels Region (3 Visit Locking Items)"
LevelsVS6 = "Levels Region (6 Visit Locking Items)"
LevelsVS9 = "Levels Region (9 Visit Locking Items)"
LevelsVS12 = "Levels Region (12 Visit Locking Items)"
LevelsVS15 = "Levels Region (15 Visit Locking Items)"
LevelsVS18 = "Levels Region (18 Visit Locking Items)"
LevelsVS21 = "Levels Region (21 Visit Locking Items)"
LevelsVS24 = "Levels Region (24 Visit Locking Items)"
LevelsVS26 = "Levels Region (26 Visit Locking Items)"

PuzzlePieces = "Puzzle Pieces"

Tt1PuzzlePieces = "Twilight Town 1 Puzzle Pieces"
Tt2PuzzlePieces = "Twilight Town 2 Puzzle Pieces"
Tt3PuzzlePieces = "Twilight Town 3 Puzzle Pieces"
Hb1PuzzlePieces = "Hollow Bastion 1 Puzzle Pieces"
Hb2PuzzlePieces = "Hollow Bastion 2 PuzzlePieces"
PostThousandHeartless = "Hollow Bastion Post Thousand Hearts"
CoRFirstFightPuzzlePieces = "Cavern of Rememberance 1 Puzzle Pieces"
CorSecondFightPuzzlePieces = "Cavern of Rememberance 2 Puzzle Pieces"
LoD1PuzzlePieces = "Land of Dragons 1 Puzzle Pieces"
LoD2PuzzlePieces = "Land of Dragons 2 Puzzle Pieces"
PostStormRiderPuzzlePieces = "Land of Dragons 2 Post Storm Rider Puzzle Pieces"
Bc1PuzzlePieces = "Beast's Castle 1 Puzzle Pieces"
Bc2PuzzlePieces = "Beast's Castle 2 Puzzle Pieces"  # post xaldin is the only one
Oc1PuzzlePieces = "Olympus 1 Puzzle Pieces"
DcPuzzlePieces = "Disney Castle Puzzle Pieces"
TrPuzzlePieces = "Timeless River Puzzle Pieces"
Pr1PuzzlePieces = "Port Royal 1 Puzzle Pieces"
BarbosaPuzzlePieces = "Barbosa Puzzle Pieces"
Pr2PuzzlePieces = "Port Royal 2 Puzzle Pieces"
Ag1PuzzlePieces = "Agrabah 1 Puzzle Pieces"
Ag2PuzzlePieces = "Agrabah 2 Puzzle Pieces"  # dont need magic for these
Ht1PuzzlePieces = "Halloween Town 1 Puzzle Pieces"
PrisonKeeperPuzzlePieces = "Prison Keeper Puzzle Pieces"
OogieBoogiePuzzlePieces = "Oogie Boogie Puzzle Pieces"
Pl1PuzzlePieces = "Pride Lands 1 Puzzle Pieces"
Sp1PuzzlePieces = "Space Paranoids 1 Puzzle Pieces"
Sp2PuzzlePieces = "Space Paranoids 2 Puzzle Pieces"
TwtnwPuzzlePostRoxas = "The World that Never Was Post Roxas"
TwtnwPuzzlePostXigbar = "The World that Never Was Post Xigbar"
Twtnw3PuzzlePieces = "The World that Never Was 3 Puzzle Pieces"
PoohsPuzzlePieces = "Poohs house Puzzle Piece"
PigletsPuzzlePieces = "Piglets House Puzzle Piece"
RabbitsPuzzlePieces = "Rabbits House Puzzle Piece"
KangasPuzzlePieces = "Kangas House Puzzle Piece"
SpookyCavePuzzlePieces = "Spooky Cave Puzzle Piece"
StarryHillPuzzlePieces = "Starry Hill Puzzle Piece"
At1PuzzlePieces = "Atlantica Puzzle Pieces"

PuzzleRegion = "Puzzles: Jiminy  Journal"
