from statistics import quantiles
from tokenize import String
import typing

from BaseClasses import Location
from .Names import LocationName

class KH2Location(Location):
    game: str = "Kingdom Hearts 2"

class LocationData(typing.NamedTuple):
    code: typing.Optional[int]
    progression: bool
    locid:int
    yml:str
    charName: str="Sora"


    #sort list from 1-5 to what the location is and what id is there
    #0=the second check of the getbonus
    #1 =treasure chest(trsr yml)
    #2 =1 get Bonus(bons)
    #3 =2 get bons (bons)
    #4 =Level up check 
    #5 = form check

    #if 3 use the id for both
    #if 2 then use one
    #If statement in the for loop

LoD_Checks={
LocationName.BambooGroveDarkShard                   : LocationData(0x13201B,False,245,"Chest"),
LocationName.BambooGroveEther                       : LocationData(0x13201C,False,497,"Chest"),
LocationName.BambooGroveMythrilShard                : LocationData(0x13201D,False,498,"Chest"),
LocationName.EncampmentAreaMap                      : LocationData(0x13201E,False,350,"Chest"),
LocationName.Mission3                               : LocationData(0x13201F,False,417,"Chest"),
LocationName.CheckpointHiPotion                     : LocationData(0x132020,False,21,"Chest"),
LocationName.CheckpointMythrilShard                 : LocationData(0x132021,False,121,"Chest"),
LocationName.MountainTrailLightningShard            : LocationData(0x132022,False,22,"Chest"),
LocationName.MountainTrailRecoveryRecipe            : LocationData(0x132023,False,23,"Chest"),
LocationName.MountainTrailEther                     : LocationData(0x132024,False,122,"Chest"),
LocationName.MountainTrailMythrilShard              : LocationData(0x132025,False,123,"Chest"),
LocationName.VillageCaveAreaMap                     : LocationData(0x132026,False,124,"Chest"),
LocationName.VillageCaveAPBoost                     : LocationData(0x132027,False,125,"Chest"),
LocationName.VillageCaveDarkShard                   : LocationData(0x132028,False,495,"Chest"),
LocationName.VillageCaveBonus                       : LocationData(0x132029,False,43,"Get Bonus"),
LocationName.RidgeFrostShard                        : LocationData(0x13202A,False,24,"Chest"),
LocationName.RidgeAPBoost                           : LocationData(0x13202B,False,126,"Chest"),
LocationName.ShanYu                                 : LocationData(0x13202C,False,9,"Double Get Bonus"),
LocationName.ShanYuGetBonus                         : LocationData(0x13202D,False,9,"Second Get Bonus"),
LocationName.HiddenDragon                           : LocationData(0x13202E,False,357,"Chest"),
}
LoD2_Checks={
LocationName.ThroneRoomTornPages                    : LocationData(0x13202F,False,25,"Chest"),
LocationName.ThroneRoomPalaceMap                    : LocationData(0x132030,False,127,"Chest"),
LocationName.ThroneRoomAPBoost                      : LocationData(0x132031,False,26,"Chest"),
LocationName.ThroneRoomQueenRecipe                  : LocationData(0x132032,False,27,"Chest"),
LocationName.ThroneRoomAPBoost2                     : LocationData(0x132033,False,128,"Chest"),
LocationName.ThroneRoomOgreShield                   : LocationData(0x132034,False,129,"Chest"),
LocationName.ThroneRoomMythrilCrystal               : LocationData(0x132035,False,130,"Chest"),
LocationName.ThroneRoomOrichalcum                   : LocationData(0x132036,False,131,"Chest"),
LocationName.StormRider                             : LocationData(0x132037,False,10,"Get Bonus"),
LocationName.XigbarDataDefenseBoost                 : LocationData(0x132038,False,555,"Chest"),
}                                                                  
AG_Checks={                                                        
LocationName.AgrabahMap                             : LocationData(0x132039,False,353,"Chest"),
LocationName.AgrabahDarkShard                       : LocationData(0x13203A,False,28,"Chest"),
LocationName.AgrabahMythrilShard                    : LocationData(0x13203B,False,29,"Chest"),
LocationName.AgrabahHiPotion                        : LocationData(0x13203C,False,30,"Chest"),
LocationName.AgrabahAPBoost                         : LocationData(0x13203D,False,132,"Chest"),
LocationName.AgrabahMythrilStone                    : LocationData(0x13203E,False,133,"Chest"),
LocationName.AgrabahMythrilShard2                   : LocationData(0x13203F,False,249,"Chest"),
LocationName.AgrabahSerenityShard                   : LocationData(0x132040,False,501,"Chest"),
LocationName.BazaarMythrilGem                       : LocationData(0x132041,False,31,"Chest"),
LocationName.BazaarPowerShard                       : LocationData(0x132042,False,32,"Chest"),
LocationName.BazaarHiPotion                         : LocationData(0x132043,False,33,"Chest"),
LocationName.BazaarAPBoost                          : LocationData(0x132044,False,134,"Chest"),
LocationName.BazaarMythrilShard                     : LocationData(0x132045,False,135,"Chest"),
LocationName.PalaceWallsSkillRing                   : LocationData(0x132046,False,136,"Chest"),
LocationName.PalaceWallsMythrilStone                : LocationData(0x132047,False,520,"Chest"),
LocationName.CaveEntrancePowerStone                 : LocationData(0x132048,False,250,"Chest"),
LocationName.CaveEntranceMythrilShard               : LocationData(0x132049,False,251,"Chest"),
LocationName.ValleyofStoneMythrilStone              : LocationData(0x13204A,False,35,"Chest"),
LocationName.ValleyofStoneAPBoost                   : LocationData(0x13204B,False,36,"Chest"),
LocationName.ValleyofStoneMythrilShard              : LocationData(0x13204C,False,137,"Chest"),
LocationName.ValleyofStoneHiPotion                  : LocationData(0x13204D,False,138,"Chest"),
LocationName.AbuEscort                              : LocationData(0x13204E,False,42,"Get Bonus"),
LocationName.ChasmofChallengesCaveofWondersMap      : LocationData(0x13204F,False,487,"Chest"),
LocationName.ChasmofChallengesAPBoost               : LocationData(0x132050,False,37,"Chest"),
LocationName.TreasureRoom                           : LocationData(0x132051,False,46,"Get Bonus"),
LocationName.TreasureRoomAPBoost                    : LocationData(0x132052,False,502,"Chest"),
LocationName.TreasureRoomSerenityGem                : LocationData(0x132053,False,503,"Chest"),
LocationName.ElementalLords                         : LocationData(0x132054,False,37,"Get Bonus"),
LocationName.LampCharm                              : LocationData(0x132055,False,300,"Chest"),
}                                                                  
AG2_Checks={                                                       
LocationName.RuinedChamberTornPages                 : LocationData(0x132056,False,34,"Chest"),
LocationName.RuinedChamberRuinsMap                  : LocationData(0x132057,False,486,"Chest"),
LocationName.GenieJafar                             : LocationData(0x132058,False,15,"Get Bonus"),
LocationName.WishingLamp                            : LocationData(0x132059,False,303,"Chest"),
LocationName.LexaeusBonus                           : LocationData(0x13205A,False,65,"Get Bonus"),
LocationName.LexaeusASStrengthBeyondStrength        : LocationData(0x13205B,False,545,"Chest"),
LocationName.LexaeusDataLostIllusion                : LocationData(0x13205C,False,550,"Chest"),
}                                                                  
DC_Checks={                                                        
LocationName.DCCourtyardMythrilShard                : LocationData(0x13205D,False,16,"Chest"),
LocationName.DCCourtyardStarRecipe                  : LocationData(0x13205E,False,17,"Chest"),
LocationName.DCCourtyardAPBoost                     : LocationData(0x13205F,False,18,"Chest"),
LocationName.DCCourtyardMythrilStone                : LocationData(0x132060,False,92,"Chest"),
LocationName.DCCourtyardBlazingStone                : LocationData(0x132061,False,93,"Chest"),
LocationName.DCCourtyardBlazingShard                : LocationData(0x132062,False,247,"Chest"),
LocationName.DCCourtyardMythrilShard2               : LocationData(0x132063,False,248,"Chest"),
LocationName.LibraryTornPages                       : LocationData(0x132064,False,91,"Chest"),
LocationName.DisneyCastleMap                        : LocationData(0x132065,False,332,"Chest"),
LocationName.MinnieEscort                           : LocationData(0x132066,False,38,"Double Get Bonus"),
LocationName.MinnieEscortGetBonus                   : LocationData(0x13225E,False,38,"Second Get Bonus"),
}                                                                  
TR_Checks={                                                        
LocationName.CornerstoneHillMap                     : LocationData(0x132067,False,79,"Chest"),
LocationName.CornerstoneHillFrostShard              : LocationData(0x132068,False,12,"Chest"),
LocationName.PierMythrilShard                       : LocationData(0x132069,False,81,"Chest"),
LocationName.PierHiPotion                           : LocationData(0x13206A,False,82,"Chest"),
LocationName.WaterwayMythrilStone                   : LocationData(0x13206B,False,83,"Chest"),
LocationName.WaterwayAPBoost                        : LocationData(0x13206C,False,84,"Chest"),
LocationName.WaterwayFrostStone                     : LocationData(0x13206D,False,85,"Chest"),
LocationName.WindowofTimeMap                        : LocationData(0x13206E,False,368,"Chest"),
LocationName.BoatPete                               : LocationData(0x13206F,False,16,"Get Bonus"),
LocationName.FuturePete                             : LocationData(0x132070,False,17,"Double Get Bonus"),
LocationName.FuturePeteGetBonus                     : LocationData(0x132071,False,17,"Second Get Bonus"),
LocationName.Monochrome                             : LocationData(0x132072,False,261,"Chest"),
LocationName.WisdomForm                             : LocationData(0x132073,False,262,"Chest"),
LocationName.MarluxiaGetBonus                       : LocationData(0x132074,False,67,"Get Bonus"),
LocationName.MarluxiaASEternalBlossom               : LocationData(0x132075,False,584,"Chest"),
LocationName.MarluxiaDataLostIllusion               : LocationData(0x132076,False,553,"Chest"),
LocationName.LingeringWillBonus                     : LocationData(0x132077,False,70,"Get Bonus"),
LocationName.LingeringWillProofofConnection         : LocationData(0x132078,False,587,"Chest"),
LocationName.LingeringWillManifestIllusion          : LocationData(0x132079,False,591,"Chest"),
}                                                                  
HundredAcre1_Checks={                                              
LocationName.PoohsHouse100AcreWoodMap               : LocationData(0x13207A,False,313,"Chest"),
LocationName.PoohsHouseAPBoost                      : LocationData(0x13207B,False,97,"Chest"),
LocationName.PoohsHouseMythrilStone                 : LocationData(0x13207C,False,98,"Chest"),
}                                                                  
HundredAcre2_Checks={                                              
LocationName.PigletsHouseDefenseBoost               : LocationData(0x13207D,False,105,"Chest"),
LocationName.PigletsHouseAPBoost                    : LocationData(0x13207E,False,103,"Chest"),
LocationName.PigletsHouseMythrilGem                 : LocationData(0x13207F,False,104,"Chest"),
}                                                                  
HundredAcre3_Checks={                                              
LocationName.RabbitsHouseDrawRing                   : LocationData(0x132080,False,314,"Chest"),
LocationName.RabbitsHouseMythrilCrystal             : LocationData(0x132081,False,100,"Chest"),
LocationName.RabbitsHouseAPBoost                    : LocationData(0x132082,False,101,"Chest"),
}                                                                  
HundredAcre4_Checks={                                              
LocationName.KangasHouseMagicBoost                  : LocationData(0x132083,False,108,"Chest"),
LocationName.KangasHouseAPBoost                     : LocationData(0x132084,False,106,"Chest"),
LocationName.KangasHouseOrichalcum                  : LocationData(0x132085,False,107,"Chest"),
}                                                                  
HundredAcre5_Checks={                                              
LocationName.SpookyCaveMythrilGem                   : LocationData(0x132086,False,110,"Chest"),
LocationName.SpookyCaveAPBoost                      : LocationData(0x132087,False,111,"Chest"),
LocationName.SpookyCaveOrichalcum                   : LocationData(0x132088,False,112,"Chest"),
LocationName.SpookyCaveGuardRecipe                  : LocationData(0x132089,False,113,"Chest"),
LocationName.SpookyCaveMythrilCrystal               : LocationData(0x13208A,False,115,"Chest"),
LocationName.SpookyCaveAPBoost2                     : LocationData(0x13208B,False,116,"Chest"),
LocationName.SweetMemories                          : LocationData(0x13208C,False,284,"Chest"),
LocationName.SpookyCaveMap                          : LocationData(0x13208D,False,485,"Chest"),
}                                                                  
HundredAcre6_Checks={                                              
LocationName.StarryHillCosmicRing                   : LocationData(0x13208E,False,312,"Chest"),
LocationName.StarryHillStyleRecipe                  : LocationData(0x13208F,False,94,"Chest"),
LocationName.StarryHillCureElement                  : LocationData(0x132090,False,285,"Chest"),
LocationName.StarryHillOrichalcumPlus               : LocationData(0x132091,False,539,"Chest"),
}                                                                  
Oc_Checks={                                                        
LocationName.PassageMythrilShard                    : LocationData(0x132092,False,7,"Chest"),
LocationName.PassageMythrilStone                    : LocationData(0x132093,False,8,"Chest"),
LocationName.PassageEther                           : LocationData(0x132094,False,144,"Chest"),
LocationName.PassageAPBoost                         : LocationData(0x132096,False,145,"Chest"),
LocationName.PassageHiPotion                        : LocationData(0x132097,False,146,"Chest"),
LocationName.InnerChamberUnderworldMap              : LocationData(0x132098,False,2,"Chest"),
LocationName.InnerChamberMythrilShard               : LocationData(0x132099,False,243,"Chest"),
LocationName.Cerberus                               : LocationData(0x13209A,False,5,"Get Bonus"),
LocationName.ColiseumMap                            : LocationData(0x13209B,False,338,"Chest"),
LocationName.Urns                                   : LocationData(0x13209C,False,57,"Get Bonus"),
LocationName.UnderworldEntrancePowerBoost           : LocationData(0x13209D,False,242,"Chest"),
LocationName.CavernsEntranceLucidShard              : LocationData(0x13209E,False,3,"Chest"),
LocationName.CavernsEntranceAPBoost                 : LocationData(0x13209F,False,11,"Chest"),
LocationName.CavernsEntranceMythrilShard            : LocationData(0x1320A0,False,504,"Chest"),
LocationName.TheLostRoadBrightShard                 : LocationData(0x1320A1,False,9,"Chest"),
LocationName.TheLostRoadEther                       : LocationData(0x1320A2,False,10,"Chest"),
LocationName.TheLostRoadMythrilShard                : LocationData(0x1320A3,False,148,"Chest"),
LocationName.TheLostRoadMythrilStone                : LocationData(0x1320A4,False,149,"Chest"),
LocationName.AtriumLucidStone                       : LocationData(0x1320A5,False,150,"Chest"),
LocationName.AtriumAPBoost                          : LocationData(0x1320A6,False,151,"Chest"),
LocationName.DemyxOC                                : LocationData(0x1320A7,False,58,"Get Bonus"),
LocationName.SecretAnsemReport5                     : LocationData(0x1320A8,False,529,"Chest"),
LocationName.OlympusStone                           : LocationData(0x1320A9,False,293,"Chest"),
LocationName.TheLockCavernsMap                      : LocationData(0x1320AA,False,244,"Chest"),
LocationName.TheLockMythrilShard                    : LocationData(0x1320AB,False,5,"Chest"),
LocationName.TheLockAPBoost                         : LocationData(0x1320AC,False,142,"Chest"),
LocationName.PeteOC                                 : LocationData(0x1320AD,False,6,"Get Bonus"),
LocationName.Hydra                                  : LocationData(0x1320AE,False,7,"Double Get Bonus"),
LocationName.HydraGetBonus                          : LocationData(0x1320AF,False,7,"Second Get Bonus"),
LocationName.HerosCrest                             : LocationData(0x1320B0,False,260,"Chest"),
}                                                                  
Oc2_Checks={                                                       
LocationName.AuronsStatue                           : LocationData(0x1320B1,False,295,"Chest"),
LocationName.Hades                                  : LocationData(0x1320B2,False,8,"Double Get Bonus"),
LocationName.HadesGetBonus                          : LocationData(0x1320B3,False,8,"Second Get Bonus"),
LocationName.GuardianSoul                           : LocationData(0x1320B4,False,272,"Chest"),
LocationName.ZexionBonus                            : LocationData(0x1320B5,False,66,"Get Bonus"),
LocationName.ZexionASBookofShadows                  : LocationData(0x1320B6,False,546,"Chest"),
LocationName.ZexionDataLostIllusion                 : LocationData(0x1320B7,False,551,"Chest"),
}                                                                  
Oc2Cups={                                                          
LocationName.ProtectBeltPainandPanicCup             : LocationData(0x1320B8,False,513,"Chest"),
LocationName.SerenityGemPainandPanicCup             : LocationData(0x1320B9,False,540,"Chest"),
LocationName.RisingDragonCerberusCup                : LocationData(0x1320BA,False,515,"Chest"),
LocationName.SerenityCrystalCerberusCup             : LocationData(0x1320BB,False,542,"Chest"),
LocationName.GenjiShieldTitanCup                    : LocationData(0x1320BC,False,514,"Chest"),
LocationName.SkillfulRingTitanCup                   : LocationData(0x1320BD,False,541,"Chest"),
LocationName.FatalCrestGoddessofFateCup             : LocationData(0x1320BE,False,516,"Chest"),
LocationName.OrichalcumPlusGoddessofFateCup         : LocationData(0x1320BF,False,517,"Chest"),
}                                                                  
HadesCups={                                                        
LocationName.HadesCupTrophyParadoxCups              : LocationData(0x1320C0,False,518,"Chest"),
}                                                                  
                                                                   
BC_Checks={                                                        
LocationName.BCCourtyardAPBoost                     : LocationData(0x1320C1,False,39,"Chest"),
LocationName.BCCourtyardHiPotion                    : LocationData(0x1320C2,False,40,"Chest"),
LocationName.BCCourtyardMythrilShard                : LocationData(0x1320C3,False,505,"Chest"),
LocationName.BellesRoomCastleMap                    : LocationData(0x1320C4,False,46,"Chest"),
LocationName.BellesRoomMegaRecipe                   : LocationData(0x1320C5,False,240,"Chest"),
LocationName.TheEastWingMythrilShard                : LocationData(0x1320C6,False,63,"Chest"),
LocationName.TheEastWingTent                        : LocationData(0x1320C7,False,155,"Chest"),
LocationName.TheWestHallHiPotion                    : LocationData(0x1320C8,False,41,"Chest"),
LocationName.TheWestHallPowerShard                  : LocationData(0x1320C9,False,207,"Chest"),
LocationName.TheWestHallAPBoost                     : LocationData(0x1320CA,False,158,"Chest"),
LocationName.TheWestHallBrightStone                 : LocationData(0x1320CB,False,159,"Chest"),
LocationName.TheWestHallMythrilShard                : LocationData(0x1320CC,False,206,"Chest"),
LocationName.Thresholder                            : LocationData(0x1320CD,False,2,"Get Bonus"),
LocationName.DungeonBasementMap                     : LocationData(0x1320CE,False,239,"Chest"),
LocationName.DungeonAPBoost                         : LocationData(0x1320CF,False,43,"Chest"),
LocationName.SecretPassageMythrilShard              : LocationData(0x1320D0,False,44,"Chest"),
LocationName.SecretPassageHiPotion                  : LocationData(0x1320D1,False,168,"Chest"),
LocationName.SecretPassageLucidShard                : LocationData(0x1320D2,False,45,"Chest"),
LocationName.TheWestHallMythrilShardPostDungeon     : LocationData(0x1320D3,False,208,"Chest"),
LocationName.TheWestWingMythrilShard                : LocationData(0x1320D4,False,42,"Chest"),
LocationName.TheWestWingTent                        : LocationData(0x1320D5,False,164,"Chest"),
LocationName.Beast                                  : LocationData(0x1320D6,False,12,"Get Bonus"),
LocationName.TheBeastsRoomBlazingShard              : LocationData(0x1320D7,False,241,"Chest"),
LocationName.DarkThorn                              : LocationData(0x1320D8,False,3,"Double Get Bonus"),
LocationName.DarkThornGetBonus                      : LocationData(0x1320D9,False,3,"Second Get Bonus"),
LocationName.DarkThornCureElement                   : LocationData(0x1320DA,False,299,"Chest"),
}                                                                  
BC2_Checks={                                                       
LocationName.RumblingRose                           : LocationData(0x1320DB,False,270,"Chest"),
LocationName.CastleWallsMap                         : LocationData(0x1320DC,False,325,"Chest"),
LocationName.Xaldin                                 : LocationData(0x1320DD,False,4,"Double Get Bonus"),
LocationName.XaldinGetBonus                         : LocationData(0x1320DE,False,4,"Second Get Bonus"),
LocationName.SecretAnsemReport6                     : LocationData(0x1320DF,False,528,"Chest"),
LocationName.XaldinDataDefenseBoost                 : LocationData(0x1320E0,False,559,"Chest"),
}                                                                  
SP_Checks={                                                        
LocationName.PitCellAreaMap                         : LocationData(0x1320E1,False,316,"Chest"),
LocationName.PitCellMythrilCrystal                  : LocationData(0x1320E2,False,64,"Chest"),
LocationName.CanyonDarkCrystal                      : LocationData(0x1320E3,False,65,"Chest"),
LocationName.CanyonMythrilStone                     : LocationData(0x1320E4,False,171,"Chest"),
LocationName.CanyonMythrilGem                       : LocationData(0x1320E5,False,253,"Chest"),
LocationName.CanyonFrostCrystal                     : LocationData(0x1320E6,False,521,"Chest"),
LocationName.Screens                                : LocationData(0x1320E7,False,45,"Get Bonus"),
LocationName.HallwayPowerCrystal                    : LocationData(0x1320E8,False,49,"Chest"),
LocationName.HallwayAPBoost                         : LocationData(0x1320E9,False,50,"Chest"),
LocationName.CommunicationsRoomIOTowerMap           : LocationData(0x1320EA,False,255,"Chest"),
LocationName.CommunicationsRoomGaiaBelt             : LocationData(0x1320EB,False,499,"Chest"),
LocationName.HostileProgram                         : LocationData(0x1320EC,False,31,"Double Get Bonus"),
LocationName.HostileProgramGetBonus                 : LocationData(0x1320ED,False,31,"Second Get Bonus"),
LocationName.PhotonDebugger                         : LocationData(0x1320EE,False,267,"Chest"),
}                                                                  
SP2_Checks={                                                       
LocationName.SolarSailer                            : LocationData(0x1320EF,False,61,"Get Bonus"),
LocationName.CentralComputerCoreAPBoost             : LocationData(0x1320F0,False,177,"Chest"),
LocationName.CentralComputerCoreOrichalcumPlus      : LocationData(0x1320F1,False,178,"Chest"),
LocationName.CentralComputerCoreCosmicArts          : LocationData(0x1320F2,False,51,"Chest"),
LocationName.CentralComputerCoreMap                 : LocationData(0x1320F3,False,488,"Chest"),
LocationName.MCP                                    : LocationData(0x1320F4,False,32,"Double Get Bonus"),
LocationName.MCPGetBonus                            : LocationData(0x1320F5,False,32,"Second Get Bonus"),
LocationName.LarxeneBonus                           : LocationData(0x1320F6,False,68,"Chest"),
LocationName.LarxeneASCloakedThunder                : LocationData(0x1320F7,False,547,"Chest"),
LocationName.LarxeneDataLostIllusion                : LocationData(0x1320F8,False,552,"Chest"),
}                                                                  
HT_Checks={                                                        
LocationName.GraveyardMythrilShard                  : LocationData(0x1320F9,False,53,"Chest"),
LocationName.GraveyardSerenityGem                   : LocationData(0x1320FA,False,212,"Chest"),
LocationName.FinklesteinsLabHalloweenTownMap        : LocationData(0x1320FB,False,211,"Chest"),
LocationName.TownSquareMythrilStone                 : LocationData(0x1320FC,False,209,"Chest"),
LocationName.TownSquareEnergyShard                  : LocationData(0x1320FD,False,210,"Chest"),
LocationName.HinterlandsLightningShard              : LocationData(0x1320FE,False,54,"Chest"),
LocationName.HinterlandsMythrilStone                : LocationData(0x1320FF,False,213,"Chest"),
LocationName.HinterlandsAPBoost                     : LocationData(0x132100,False,214,"Chest"),
LocationName.CandyCaneLaneMegaPotion                : LocationData(0x132101,False,55,"Chest"),
LocationName.CandyCaneLaneMythrilGem                : LocationData(0x132102,False,56,"Chest"),
LocationName.CandyCaneLaneLightningStone            : LocationData(0x132103,False,216,"Chest"),
LocationName.CandyCaneLaneMythrilStone              : LocationData(0x132104,False,217,"Chest"),
LocationName.SantasHouseChristmasTownMap            : LocationData(0x132105,False,57,"Chest"),
LocationName.SantasHouseAPBoost                     : LocationData(0x132106,False,58,"Chest"),
LocationName.PrisonKeeper                           : LocationData(0x132107,False,18,"Get Bonus"),
LocationName.OogieBoogie                            : LocationData(0x132108,False,19,"Chest"),
LocationName.OogieBoogieMagnetElement               : LocationData(0x132109,False,301,"Chest"),
}                                                                  
HT2_Checks={                                                       
LocationName.Lock                                   : LocationData(0x13210A,False,40,"Chest"),
LocationName.Present                                : LocationData(0x13210B,False,297,"Chest"),
LocationName.DecoyPresents                          : LocationData(0x13210C,False,298,"Chest"),
LocationName.Experiment                             : LocationData(0x13210D,False,20,"Get Bonus"),
LocationName.DecisivePumpkin                        : LocationData(0x13210E,False,275,"Chest"),
LocationName.VexenBonus                             : LocationData(0x13210F,False,64,"Chest"),
LocationName.VexenASRoadtoDiscovery                 : LocationData(0x132110,False,544,"Chest"),
LocationName.VexenDataLostIllusion                  : LocationData(0x132111,False,549,"Chest"),
}                                                                  
PR_Checks={                                                        
LocationName.RampartNavalMap                        : LocationData(0x132112,False,70,"Chest"),
LocationName.RampartMythrilStone                    : LocationData(0x132113,False,219,"Chest"),
LocationName.RampartDarkShard                       : LocationData(0x132114,False,220,"Chest"),
LocationName.TownDarkStone                          : LocationData(0x132115,False,71,"Chest"),
LocationName.TownAPBoost                            : LocationData(0x132116,False,72,"Chest"),
LocationName.TownMythrilShard                       : LocationData(0x132117,False,73,"Chest"),
LocationName.TownMythrilGem                         : LocationData(0x132118,False,221,"Chest"),
LocationName.CaveMouthBrightShard                   : LocationData(0x132119,False,74,"Chest"),
LocationName.CaveMouthMythrilShard                  : LocationData(0x13211A,False,223,"Chest"),
LocationName.IsladeMuertaMap                        : LocationData(0x13211B,False,329,"Chest"),
LocationName.BoatFight                              : LocationData(0x13211C,False,62,"Get Bonus"),
LocationName.InterceptorBarrels                     : LocationData(0x13211D,False,39,"Get Bonus"),
LocationName.PowderStoreAPBoost1                    : LocationData(0x13211E,False,369,"Chest"),
LocationName.PowderStoreAPBoost2                    : LocationData(0x13211F,False,370,"Chest"),
LocationName.MoonlightNookMythrilShard              : LocationData(0x132120,False,75,"Chest"),
LocationName.MoonlightNookSerenityGem               : LocationData(0x132121,False,224,"Chest"),
LocationName.MoonlightNookPowerStone                : LocationData(0x132122,False,371,"Chest"),
LocationName.Barbossa                               : LocationData(0x132123,False,21,"Double Get Bonus"),
LocationName.BarbossaGetBonus                       : LocationData(0x132124,False,21,"Second Get Bonus"),
LocationName.FollowtheWind                          : LocationData(0x132125,False,263,"Chest"),
}                                                                  
PR2_Checks={                                                       
LocationName.GrimReaper1                            : LocationData(0x132126,False,59,"Get Bonus"),
LocationName.InterceptorsHoldFeatherCharm           : LocationData(0x132127,False,252,"Chest"),
LocationName.SeadriftKeepAPBoost                    : LocationData(0x132128,False,76,"Chest"),
LocationName.SeadriftKeepOrichalcum                 : LocationData(0x132129,False,225,"Chest"),
LocationName.SeadriftKeepMeteorStaff                : LocationData(0x13212A,False,372,"Chest"),
LocationName.SeadriftRowSerenityGem                 : LocationData(0x13212B,False,77,"Chest"),
LocationName.SeadriftRowKingRecipe                  : LocationData(0x13212C,False,78,"Chest"),
LocationName.SeadriftRowMythrilCrystal              : LocationData(0x13212D,False,373,"Chest"),
LocationName.SeadriftRowCursedMedallion             : LocationData(0x13212E,False,296,"Chest"),
LocationName.SeadriftRowShipGraveyardMap            : LocationData(0x13212F,False,331,"Chest"),
LocationName.GrimReaper2                            : LocationData(0x132130,False,22,"Get Bonus"),
LocationName.SecretAnsemReport4                     : LocationData(0x132131,False,530,"Chest"),
LocationName.LuxordDataAPBoost                      : LocationData(0x132132,False,557,"Chest"),
}                                                                  
HB_Checks={
LocationName.MarketplaceMap                         : LocationData(0x132133,False,362,"Chest"),
LocationName.BoroughDriveRecovery                   : LocationData(0x132134,False,194,"Chest"),
LocationName.BoroughAPBoost                         : LocationData(0x132135,False,195,"Chest"),
LocationName.BoroughHiPotion                        : LocationData(0x132136,False,196,"Chest"),
LocationName.BoroughMythrilShard                    : LocationData(0x132137,False,305,"Chest"),
LocationName.BoroughDarkShard                       : LocationData(0x132138,False,506,"Chest"),
LocationName.MerlinsHouseMembershipCard             : LocationData(0x132139,False,256,"Chest"),
LocationName.MerlinsHouseBlizzardElement            : LocationData(0x13213A,False,292,"Chest"),
LocationName.Bailey                                 : LocationData(0x13213B,False,47,"Get Bonus"),
LocationName.BaileySecretAnsemReport7               : LocationData(0x13213C,False,531,"Chest"),
LocationName.BaseballCharm                          : LocationData(0x13213D,False,258,"Chest"),
}                                                                  
HB2_Checks={                                                       
LocationName.PosternCastlePerimeterMap              : LocationData(0x13213E,False,310,"Chest"),
LocationName.PosternMythrilGem                      : LocationData(0x13213F,False,189,"Chest"),
LocationName.PosternAPBoost                         : LocationData(0x132140,False,190,"Chest"),
LocationName.CorridorsMythrilStone                  : LocationData(0x132141,False,200,"Chest"),
LocationName.CorridorsMythrilCrystal                : LocationData(0x132142,False,201,"Chest"),
LocationName.CorridorsDarkCrystal                   : LocationData(0x132143,False,202,"Chest"),
LocationName.CorridorsAPBoost                       : LocationData(0x132144,False,307,"Chest"),
LocationName.AnsemsStudyMasterForm                  : LocationData(0x132145,False,184,"Chest"),
LocationName.AnsemsStudySleepingLion                : LocationData(0x132146,False,266,"Chest"),
LocationName.AnsemsStudySkillRecipe                 : LocationData(0x132147,False,276,"Chest"),
LocationName.AnsemsStudyUkuleleCharm                : LocationData(0x132148,False,183,"Chest"),
LocationName.RestorationSiteMoonRecipe              : LocationData(0x132149,False,309,"Chest"),
LocationName.RestorationSiteAPBoost                 : LocationData(0x13214A,False,507,"Chest"),
LocationName.DemyxHB                                : LocationData(0x13214B,False,28,"Double Get Bonus"),
LocationName.DemyxHBGetBonus                        : LocationData(0x13225E,False,28,"Second Get Bonus"),
LocationName.FFFightsCureElement                    : LocationData(0x13214C,False,361,"Chest"),
LocationName.CrystalFissureTornPages                : LocationData(0x13214D,False,179,"Chest"),
LocationName.CrystalFissureTheGreatMawMap           : LocationData(0x13214E,False,489,"Chest"),
LocationName.CrystalFissureEnergyCrystal            : LocationData(0x13214F,False,180,"Chest"),
LocationName.CrystalFissureAPBoost                  : LocationData(0x132150,False,181,"Chest"),
LocationName.ThousandHeartless                      : LocationData(0x132151,False,60,"Get Bonus"),
LocationName.ThousandHeartlessSecretAnsemReport1    : LocationData(0x132152,False,525,"Chest"),
LocationName.ThousandHeartlessIceCream              : LocationData(0x132153,False,269,"Chest"),
LocationName.ThousandHeartlessPicture               : LocationData(0x132154,False,511,"Chest"),
LocationName.PosternGullWing                        : LocationData(0x132155,False,491,"Chest"),
LocationName.HeartlessManufactoryCosmicChain        : LocationData(0x132156,False,311,"Chest"),
LocationName.SephirothBonus                         : LocationData(0x132157,False,35,"Get Bonus"),
LocationName.SephirothFenrir                        : LocationData(0x132158,False,282,"Chest"),
LocationName.WinnersProof                           : LocationData(0x132159,False,560,"Chest"),
LocationName.ProofofPeace                           : LocationData(0x13215A,False,588,"Chest"),
LocationName.DemyxDataAPBoost                       : LocationData(0x13215B,False,589,"Chest"),
}                                                                  
CoR_Checks={                                                       
LocationName.CoRDepthsAPBoost                               : LocationData(0x13215C,False,562,"Chest"),
LocationName.CoRDepthsPowerCrystal                          : LocationData(0x13215D,False,563,"Chest"),
LocationName.CoRDepthsFrostCrystal                          : LocationData(0x13215E,False,564,"Chest"),
LocationName.CoRDepthsManifestIllusion                      : LocationData(0x13215F,False,565,"Chest"),
LocationName.CoRDepthsAPBoost2                              : LocationData(0x132160,False,566,"Chest"),
LocationName.CoRMineshaftLowerLevelDepthsofRemembranceMap   : LocationData(0x132161,False,580,"Chest"),
LocationName.CoRMineshaftLowerLevelAPBoost                  : LocationData(0x132162,False,578,"Chest"),
}
#Need quickrun 2 aerial dodge 2 
FirstHalf_Checks={
LocationName.CoRDepthsUpperLevelRemembranceGem      : LocationData(0x132163,False,567,"Chest"),
LocationName.CoRMiningAreaSerenityGem               : LocationData(0x132164,False,568,"Chest"),
LocationName.CoRMiningAreaAPBoost                   : LocationData(0x132165,False,569,"Chest"),
LocationName.CoRMiningAreaSerenityCrystal           : LocationData(0x132166,False,570,"Chest"),
LocationName.CoRMiningAreaManifestIllusion          : LocationData(0x132167,False,571,"Chest"),
LocationName.CoRMiningAreaSerenityGem2              : LocationData(0x132168,False,572,"Chest"),
LocationName.CoRMiningAreaDarkRemembranceMap        : LocationData(0x132169,False,573,"Chest"),
LocationName.CoRMineshaftMidLevelPowerBoost         : LocationData(0x13216A,False,581,"Chest"),
LocationName.CoREngineChamberSerenityCrystal        : LocationData(0x13216B,False,574,"Chest"),
LocationName.CoREngineChamberRemembranceCrystal     : LocationData(0x13216C,False,575,"Chest"),
LocationName.CoREngineChamberAPBoost                : LocationData(0x13216D,False,576,"Chest"),
LocationName.CoREngineChamberManifestIllusion       : LocationData(0x13216E,False,577,"Chest"),
LocationName.CoRMineshaftUpperLevelMagicBoost       : LocationData(0x13216F,False,582,"Chest"),
}#glide 3 highjump somthem        
 #missed these in putting the hex but it shouldnt cause a issue
SecondHalf_Checks={                                                
LocationName.CoRMineshaftUpperLevelAPBoost          : LocationData(0x13225C,False,570,"Chest"),
LocationName.TransporttoRemembrance                 : LocationData(0x13225D,False,72,"Get Bonus"),
}                                                                  
PL_Checks={                                                        
LocationName.GorgeSavannahMap                       : LocationData(0x132170,False,492,"Chest"),
LocationName.GorgeDarkGem                           : LocationData(0x132171,False,404,"Chest"),
LocationName.GorgeMythrilStone                      : LocationData(0x132172,False,405,"Chest"),
LocationName.ElephantGraveyardFrostGem              : LocationData(0x132173,False,401,"Chest"),
LocationName.ElephantGraveyardMythrilStone          : LocationData(0x132174,False,402,"Chest"),
LocationName.ElephantGraveyardBrightStone           : LocationData(0x132175,False,403,"Chest"),
LocationName.ElephantGraveyardAPBoost               : LocationData(0x132176,False,508,"Chest"),
LocationName.ElephantGraveyardMythrilShard          : LocationData(0x132177,False,509,"Chest"),
LocationName.PrideRockMap                           : LocationData(0x132178,False,418,"Chest"),
LocationName.PrideRockMythrilStone                  : LocationData(0x132179,False,392,"Chest"),
LocationName.PrideRockSerenityCrystal               : LocationData(0x13217A,False,393,"Chest"),
LocationName.WildebeestValleyEnergyStone            : LocationData(0x13217B,False,396,"Chest"),
LocationName.WildebeestValleyAPBoost                : LocationData(0x13217C,False,397,"Chest"),
LocationName.WildebeestValleyMythrilGem             : LocationData(0x13217D,False,398,"Chest"),
LocationName.WildebeestValleyMythrilStone           : LocationData(0x13217E,False,399,"Chest"),
LocationName.WildebeestValleyLucidGem               : LocationData(0x13217F,False,400,"Chest"),
LocationName.WastelandsMythrilShard                 : LocationData(0x132180,False,406,"Chest"),
LocationName.WastelandsSerenityGem                  : LocationData(0x132181,False,407,"Chest"),
LocationName.WastelandsMythrilStone                 : LocationData(0x132182,False,408,"Chest"),
LocationName.JungleSerenityGem                      : LocationData(0x132183,False,409,"Chest"),
LocationName.JungleMythrilStone                     : LocationData(0x132184,False,410,"Chest"),
LocationName.JungleSerenityCrystal                  : LocationData(0x132185,False,411,"Chest"),
LocationName.OasisMap                               : LocationData(0x132186,False,412,"Chest"),
LocationName.OasisTornPages                         : LocationData(0x132187,False,493,"Chest"),
LocationName.OasisAPBoost                           : LocationData(0x132188,False,413,"Chest"),
LocationName.CircleofLife                           : LocationData(0x132189,False,264,"Chest"),
LocationName.Hyenas1                                : LocationData(0x13218A,False,49,"Get Bonus"),
LocationName.Scar                                   : LocationData(0x13218B,False,29,"Chest"),
LocationName.ScarFireElement                        : LocationData(0x13218C,False,302,"Chest"),
}                                                                  
PL2_Checks={                                                       
LocationName.Hyenas2                                : LocationData(0x13218D,False,50,"Get Bonus"),
LocationName.Groundshaker                           : LocationData(0x13218E,False,30,"Double Get Bonus"),
LocationName.GroundshakerGetBonus                   : LocationData(0x13218F,False,30,"Second Get Bonus"),
LocationName.SaixDataDefenseBoost                   : LocationData(0x132190,False,556,"Chest"),
}                                                                  
STT_Checks={                                                       
LocationName.TwilightTownMap                        : LocationData(0x132191,False,319,1,"Roxas"),
LocationName.MunnyPouchOlette                       : LocationData(0x132192,False,288,1,"Roxas"),
LocationName.StationDusks                           : LocationData(0x132193,False,54,"Get Bonus","Roxas"),
LocationName.StationofSerenityPotion                : LocationData(0x132194,False,315,"Chest"),
LocationName.StationofCallingPotion                 : LocationData(0x132195,False,472,"Chest"),
LocationName.TwilightThorn                          : LocationData(0x132196,False,33,"Get Bonus","Roxas"),
LocationName.Axel1                                  : LocationData(0x132197,False,73,"Get Bonus","Roxas"),
LocationName.JunkChampionBelt                       : LocationData(0x132198,False,389,"Chest"),
LocationName.JunkMedal                              : LocationData(0x132199,False,390,"Chest"),
LocationName.TheStruggleTrophy                      : LocationData(0x13219A,False,519,"Chest"),
LocationName.CentralStationPotion1                  : LocationData(0x13219B,False,428,"Chest"),
LocationName.STTCentralStationHiPotion              : LocationData(0x13219C,False,429,"Chest"),
LocationName.CentralStationPotion2                  : LocationData(0x13219D,False,430,"Chest"),
LocationName.SunsetTerraceAbilityRing               : LocationData(0x13219E,False,434,"Chest"),
LocationName.SunsetTerraceHiPotion                  : LocationData(0x13219F,False,435,"Chest"),
LocationName.SunsetTerracePotion1                   : LocationData(0x1321A0,False,436,"Chest"),
LocationName.SunsetTerracePotion2                   : LocationData(0x1321A1,False,437,"Chest"),
LocationName.MansionFoyerHiPotion                   : LocationData(0x1321A2,False,449,"Chest"),
LocationName.MansionFoyerPotion1                    : LocationData(0x1321A3,False,450,"Chest"),
LocationName.MansionFoyerPotion2                    : LocationData(0x1321A4,False,451,"Chest"),
LocationName.MansionDiningRoomElvenBandanna         : LocationData(0x1321A5,False,455,"Chest"),
LocationName.MansionDiningRoomPotion                : LocationData(0x1321A6,False,456,"Chest"),
LocationName.NaminesSketches                        : LocationData(0x1321A7,False,289,"Chest"),
LocationName.MansionMap                             : LocationData(0x1321A8,False,483,"Chest"),
LocationName.MansionLibraryHiPotion                 : LocationData(0x1321A9,False,459,"Chest"),
LocationName.Axel2                                  : LocationData(0x1321AA,False,34,"Get Bonus","Roxas"),
LocationName.MansionBasementCorridorHiPotion        : LocationData(0x1321AB,False,463,"Chest"),
LocationName.RoxasDataMagicBoost                    : LocationData(0x1321AC,False,558,"Chest"),
}                                                                  
TT_Checks={                                                        
LocationName.OldMansionPotion                       : LocationData(0x1321AD,False,447,"Chest"),
LocationName.OldMansionMythrilShard                 : LocationData(0x1321AE,False,448,"Chest"),
LocationName.TheWoodsPotion                         : LocationData(0x1321AF,False,442,"Chest"),
LocationName.TheWoodsMythrilShard                   : LocationData(0x1321B0,False,443,"Chest"),
LocationName.TheWoodsHiPotion                       : LocationData(0x1321B1,False,444,"Chest"),
LocationName.TramCommonHiPotion                     : LocationData(0x1321B2,False,420,"Chest"),
LocationName.TramCommonAPBoost                      : LocationData(0x1321B3,False,421,"Chest"),
LocationName.TramCommonTent                         : LocationData(0x1321B4,False,422,"Chest"),
LocationName.TramCommonMythrilShard1                : LocationData(0x1321B5,False,423,"Chest"),
LocationName.TramCommonPotion1                      : LocationData(0x1321B6,False,424,"Chest"),
LocationName.TramCommonMythrilShard2                : LocationData(0x1321B7,False,425,"Chest"),
LocationName.TramCommonPotion2                      : LocationData(0x1321B8,False,484,"Chest"),
LocationName.StationPlazaSecretAnsemReport2         : LocationData(0x1321B9,False,526,"Chest"),
LocationName.MunnyPouchMickey                       : LocationData(0x1321BA,False,290,"Chest"),
LocationName.CrystalOrb                             : LocationData(0x1321BB,False,291,"Chest"),
LocationName.CentralStationTent                     : LocationData(0x1321BC,False,431,"Chest"),
LocationName.TTCentralStationHiPotion               : LocationData(0x1321BD,False,432,"Chest"),
LocationName.CentralStationMythrilShard             : LocationData(0x1321BE,False,433,"Chest"),
LocationName.TheTowerPotion                         : LocationData(0x1321BF,False,465,"Chest"),
LocationName.TheTowerHiPotion                       : LocationData(0x1321C0,False,466,"Chest"),
LocationName.TheTowerEther                          : LocationData(0x1321C1,False,522,"Chest"),
LocationName.TowerEntrywayEther                     : LocationData(0x1321C2,False,467,"Chest"),
LocationName.TowerEntrywayMythrilShard              : LocationData(0x1321C3,False,468,"Chest"),
LocationName.SorcerersLoftTowerMap                  : LocationData(0x1321C4,False,469,"Chest"),
LocationName.TowerWardrobeMythrilStone              : LocationData(0x1321C5,False,470,"Chest"),
LocationName.StarSeeker                             : LocationData(0x1321C6,False,304,"Chest"),
LocationName.ValorForm                              : LocationData(0x1321C7,False,286,"Chest"),
}                                                                  
TT2_Checks={                                                       
LocationName.SeifersTrophy                          : LocationData(0x1321C8,False,294,"Chest"),
LocationName.Oathkeeper                             : LocationData(0x1321C9,False,265,"Chest"),
LocationName.LimitForm                              : LocationData(0x1321CA,False,543,"Chest"),
}                                                                  
TT3_Checks={                                                       
LocationName.UndergroundConcourseMythrilGem         : LocationData(0x1321CB,False,479,"Chest"),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LocationName.UndergroundConcourseAPBoost            : LocationData(0x1321CC,False,480,"Chest"),
LocationName.UndergroundConcourseOrichalcum         : LocationData(0x1321CD,False,481,"Chest"),
LocationName.UndergroundConcourseMythrilCrystal     : LocationData(0x1321CE,False,482,"Chest"),
LocationName.TunnelwayOrichalcum                    : LocationData(0x1321CF,False,477,"Chest"),
LocationName.TunnelwayMythrilCrystal                : LocationData(0x1321D0,False,478,"Chest"),
LocationName.SunsetTerraceOrichalcumPlus            : LocationData(0x1321D1,False,438,"Chest"),
LocationName.SunsetTerraceMythrilShard              : LocationData(0x1321D2,False,439,"Chest"),
LocationName.SunsetTerraceMythrilCrystal            : LocationData(0x1321D3,False,440,"Chest"),
LocationName.SunsetTerraceAPBoost                   : LocationData(0x1321D4,False,441,"Chest"),
LocationName.MansionNobodies                        : LocationData(0x1321D5,False,56,"Get Bonus"),
LocationName.MansionFoyerMythrilCrystal             : LocationData(0x1321D6,False,452,"Chest"),
LocationName.MansionFoyerMythrilStone               : LocationData(0x1321D7,False,453,"Chest"),
LocationName.MansionFoyerSerenityCrystal            : LocationData(0x1321D8,False,454,"Chest"),
LocationName.MansionDiningRoomMythrilCrystal        : LocationData(0x1321D9,False,457,"Chest"),
LocationName.MansionDiningRoomMythrilStone          : LocationData(0x1321DA,False,458,"Chest"),
LocationName.MansionLibraryOrichalcum               : LocationData(0x1321DB,False,460,"Chest"),
LocationName.BeamSecretAnsemReport10                : LocationData(0x1321DC,False,534,"Chest"),
LocationName.MansionBasementCorridorUltimateRecipe  : LocationData(0x1321DD,False,464,"Chest"),
LocationName.BetwixtandBetween                      : LocationData(0x1321DE,False,63,"Get Bonus"),
LocationName.BetwixtandBetweenBondofFlame           : LocationData(0x1321DF,False,317,"Chest"),
LocationName.AxelDataMagicBoost                     : LocationData(0x1321E0,False,561,"Chest"),
}                                                                  
TWTNW_Checks={                                                     
LocationName.FragmentCrossingMythrilStone           : LocationData(0x1321E1,False,374,"Chest"),
LocationName.FragmentCrossingMythrilCrystal         : LocationData(0x1321E2,False,375,"Chest"),
LocationName.FragmentCrossingAPBoost                : LocationData(0x1321E3,False,376,"Chest"),
LocationName.FragmentCrossingOrichalcum             : LocationData(0x1321E4,False,377,"Chest"),
LocationName.Roxas                                  : LocationData(0x1321E5,False,69,"Double Get Bonus"),
LocationName.RoxasGetBonus                          : LocationData(0x1321E6,False,69,"Second Get Bonus"),
LocationName.RoxasSecretAnsemReport8                : LocationData(0x1321E7,False,532,"Chest"),
LocationName.TwoBecomeOne                           : LocationData(0x1321E8,False,277,"Chest"),
LocationName.MemorysSkyscaperMythrilCrystal         : LocationData(0x1321E9,False,391,"Chest"),
LocationName.MemorysSkyscaperAPBoost                : LocationData(0x1321EA,False,523,"Chest"),
LocationName.MemorysSkyscaperMythrilStone           : LocationData(0x1321EB,False,524,"Chest"),
LocationName.TheBrinkofDespairDarkCityMap           : LocationData(0x1321EC,False,335,"Chest"),
LocationName.TheBrinkofDespairOrichalcumPlus        : LocationData(0x1321ED,False,500,"Chest"),
LocationName.NothingsCallMythrilGem                 : LocationData(0x1321EE,False,378,"Chest"),
LocationName.NothingsCallOrichalcum                 : LocationData(0x1321EF,False,379,"Chest"),
LocationName.TwilightsViewCosmicBelt                : LocationData(0x1321F0,False,336,"Chest"),
}                                                                  
TWTNW2_Checks={                                                    
LocationName.XigbarBonus                            : LocationData(0x1321F1,False,23,"Get Bonus"),
LocationName.XigbarSecretAnsemReport3               : LocationData(0x1321F2,False,527,"Chest"),
LocationName.NaughtsSkywayMythrilGem                : LocationData(0x1321F3,False,380,"Chest"),
LocationName.NaughtsSkywayOrichalcum                : LocationData(0x1321F4,False,381,"Chest"),
LocationName.NaughtsSkywayMythrilCrystal            : LocationData(0x1321F5,False,382,"Chest"),
LocationName.Oblivion                               : LocationData(0x1321F6,False,278,"Chest"),
LocationName.CastleThatNeverWasMap                  : LocationData(0x1321F7,False,496,"Chest"),
LocationName.Luxord                                 : LocationData(0x1321F8,False,24,"Double Get Bonus"),
LocationName.LuxordGetBonus                         : LocationData(0x1321F9,False,24,"Second Get Bonus"),
LocationName.LuxordSecretAnsemReport9               : LocationData(0x1321FA,False,533,"Chest"),
LocationName.SaixBonus                              : LocationData(0x1321FB,False,25,"Get Bonus"),
LocationName.SaixSecretAnsemReport12                : LocationData(0x1321FC,False,536,"Chest"),
LocationName.PreXemnas1SecretAnsemReport11          : LocationData(0x1321FD,False,535,"Chest"),
LocationName.RuinandCreationsPassageMythrilStone    : LocationData(0x1321FE,False,385,"Chest"),
LocationName.RuinandCreationsPassageAPBoost         : LocationData(0x1321FF,False,386,"Chest"),
LocationName.RuinandCreationsPassageMythrilCrystal  : LocationData(0x132200,False,387,"Chest"),
LocationName.RuinandCreationsPassageOrichalcum      : LocationData(0x132201,False,388,"Chest"),
LocationName.Xemnas1                                : LocationData(0x132202,False,26,"Double Get Bonus"),
LocationName.Xemnas1GetBonus                        : LocationData(0x132203,False,26,"Second Get Bonus"),
LocationName.Xemnas1SecretAnsemReport13             : LocationData(0x132204,False,537,"Chest"),
LocationName.FinalXemnas                            : LocationData(0x132205,False,71,"Get Bonus"),
LocationName.XemnasDataPowerBoost                   : LocationData(0x132206,False,554,"Chest"),
}                                                                  
SoraLevels={                                                       
    LocationName.Lvl2                               : LocationData(0x132208,False,2,"Levels"),
    LocationName.Lvl3                               : LocationData(0x132209,False,3,"Levels"),
    LocationName.Lvl4                               : LocationData(0x13220A,False,4,"Levels"),
    LocationName.Lvl5                               : LocationData(0x13220B,False,5,"Levels"),
    LocationName.Lvl6                               : LocationData(0x13220C,False,6,"Levels"),
    LocationName.Lvl7                               : LocationData(0x13220D,False,7,"Levels"),
    LocationName.Lvl8                               : LocationData(0x13220E,False,8,"Levels"),
    LocationName.Lvl9                               : LocationData(0x13220F,False,9,"Levels"),
    LocationName.Lvl10                              : LocationData(0x132210,False,10,"Levels"),
    LocationName.Lvl11                              : LocationData(0x132211,False,11,"Levels"),
    LocationName.Lvl12                              : LocationData(0x132212,False,12,"Levels"),
    LocationName.Lvl13                              : LocationData(0x132213,False,13,"Levels"),
    LocationName.Lvl14                              : LocationData(0x132214,False,14,"Levels"),
    LocationName.Lvl15                              : LocationData(0x132215,False,15,"Levels"),
    LocationName.Lvl16                              : LocationData(0x132216,False,16,"Levels"),
    LocationName.Lvl17                              : LocationData(0x132217,False,17,"Levels"),
    LocationName.Lvl18                              : LocationData(0x132218,False,18,"Levels"),
    LocationName.Lvl19                              : LocationData(0x132219,False,19,"Levels"),
    LocationName.Lvl20                              : LocationData(0x13221A,False,20,"Levels"),
    LocationName.Lvl21                              : LocationData(0x13221B,False,21,"Levels"),
    LocationName.Lvl22                              : LocationData(0x13221C,False,22,"Levels"),
    LocationName.Lvl23                              : LocationData(0x13221D,False,23,"Levels"),
    LocationName.Lvl24                              : LocationData(0x13221E,False,24,"Levels"),
    LocationName.Lvl25                              : LocationData(0x13221F,False,25,"Levels"),
    LocationName.Lvl26                              : LocationData(0x132220,False,26,"Levels"),
    LocationName.Lvl27                              : LocationData(0x132221,False,27,"Levels"),
    LocationName.Lvl28                              : LocationData(0x132222,False,28,"Levels"),
    LocationName.Lvl29                              : LocationData(0x132223,False,29,"Levels"),
    LocationName.Lvl30                              : LocationData(0x132224,False,30,"Levels"),
    LocationName.Lvl31                              : LocationData(0x132225,False,31,"Levels"),
    LocationName.Lvl32                              : LocationData(0x132226,False,32,"Levels"),
    LocationName.Lvl33                              : LocationData(0x132227,False,33,"Levels"),
    LocationName.Lvl34                              : LocationData(0x132228,False,34,"Levels"),
    LocationName.Lvl35                              : LocationData(0x132229,False,35,"Levels"),
    LocationName.Lvl36                              : LocationData(0x13222A,False,36,"Levels"),
    LocationName.Lvl37                              : LocationData(0x13222B,False,37,"Levels"),
    LocationName.Lvl38                              : LocationData(0x13222C,False,38,"Levels"),
    LocationName.Lvl39                              : LocationData(0x13222D,False,39,"Levels"),
    LocationName.Lvl40                              : LocationData(0x13222E,False,40,"Levels"),
    LocationName.Lvl41                              : LocationData(0x13222F,False,41,"Levels"),
    LocationName.Lvl42                              : LocationData(0x132230,False,42,"Levels"),
    LocationName.Lvl43                              : LocationData(0x132231,False,43,"Levels"),
    LocationName.Lvl44                              : LocationData(0x132232,False,44,"Levels"),
    LocationName.Lvl45                              : LocationData(0x132233,False,45,"Levels"),
    LocationName.Lvl46                              : LocationData(0x132234,False,46,"Levels"),
    LocationName.Lvl47                              : LocationData(0x132235,False,47,"Levels"),
    LocationName.Lvl48                              : LocationData(0x132236,False,48,"Levels"),
    LocationName.Lvl49                              : LocationData(0x132237,False,49,"Levels"),
    LocationName.Lvl50                              : LocationData(0x132238,False,50,"Levels"),
    LocationName.Lvl51                              : LocationData(0x132239,False,51,"Levels"),
    LocationName.Lvl52                              : LocationData(0x13223A,False,52,"Levels"),
    LocationName.Lvl53                              : LocationData(0x13223B,False,53,"Levels"),
    LocationName.Lvl54                              : LocationData(0x13223C,False,54,"Levels"),
    LocationName.Lvl55                              : LocationData(0x13223D,False,55,"Levels"),
    LocationName.Lvl56                              : LocationData(0x13223E,False,56,"Levels"),
    LocationName.Lvl57                              : LocationData(0x13223F,False,57,"Levels"),
    LocationName.Lvl58                              : LocationData(0x132240,False,58,"Levels"),
    LocationName.Lvl59                              : LocationData(0x132241,False,59,"Levels"),
    LocationName.Lvl60                              : LocationData(0x132242,False,60,"Levels"),
    LocationName.Lvl61                              : LocationData(0x132243,False,61,"Levels"),
    LocationName.Lvl62                              : LocationData(0x132244,False,62,"Levels"),
    LocationName.Lvl63                              : LocationData(0x132245,False,63,"Levels"),
    LocationName.Lvl64                              : LocationData(0x132246,False,64,"Levels"),
    LocationName.Lvl65                              : LocationData(0x132247,False,65,"Levels"),
    LocationName.Lvl66                              : LocationData(0x132248,False,66,"Levels"),
    LocationName.Lvl67                              : LocationData(0x132249,False,67,"Levels"),
    LocationName.Lvl68                              : LocationData(0x13224A,False,68,"Levels"),
    LocationName.Lvl69                              : LocationData(0x13224B,False,69,"Levels"),
    LocationName.Lvl70                              : LocationData(0x13224C,False,70,"Levels"),
    LocationName.Lvl71                              : LocationData(0x13224D,False,71,"Levels"),
    LocationName.Lvl72                              : LocationData(0x13224E,False,72,"Levels"),
    LocationName.Lvl73                              : LocationData(0x13224F,False,73,"Levels"),
    LocationName.Lvl74                              : LocationData(0x132250,False,74,"Levels"),
    LocationName.Lvl75                              : LocationData(0x132251,False,75,"Levels"),
    LocationName.Lvl76                              : LocationData(0x132252,False,76,"Levels"),
    LocationName.Lvl77                              : LocationData(0x132253,False,77,"Levels"),
    LocationName.Lvl78                              : LocationData(0x132254,False,78,"Levels"),
    LocationName.Lvl79                              : LocationData(0x132255,False,79,"Levels"),
    LocationName.Lvl80                              : LocationData(0x132256,False,80,"Levels"),
    LocationName.Lvl81                              : LocationData(0x132257,False,81,"Levels"),
    LocationName.Lvl82                              : LocationData(0x132258,False,82,"Levels"),
    LocationName.Lvl83                              : LocationData(0x132259,False,83,"Levels"),
    LocationName.Lvl84                              : LocationData(0x13225A,False,84,"Levels"),
    LocationName.Lvl85                              : LocationData(0x13225B,False,85,"Levels"),
    LocationName.Lvl86                              : LocationData(0x13225C,False,86,"Levels"),
    LocationName.Lvl87                              : LocationData(0x13225D,False,87,"Levels"),
    LocationName.Lvl88                              : LocationData(0x13225E,False,88,"Levels"),
    LocationName.Lvl89                              : LocationData(0x13225F,False,89,"Levels"),
    LocationName.Lvl90                              : LocationData(0x132260,False,90,"Levels"),
    LocationName.Lvl91                              : LocationData(0x132261,False,91,"Levels"),
    LocationName.Lvl92                              : LocationData(0x132262,False,92,"Levels"),
    LocationName.Lvl93                              : LocationData(0x132263,False,93,"Levels"),
    LocationName.Lvl94                              : LocationData(0x132264,False,94,"Levels"),
    LocationName.Lvl95                              : LocationData(0x132265,False,95,"Levels"),
    LocationName.Lvl96                              : LocationData(0x132266,False,96,"Levels"),
    LocationName.Lvl97                              : LocationData(0x132267,False,97,"Levels"),
    LocationName.Lvl98                              : LocationData(0x132268,False,98,"Levels"),
    LocationName.Lvl99                              : LocationData(0x132269,False,99,"Levels"),
}                                                                  
Form_Checks={                                                      
    LocationName.Valorlvl2                          : LocationData(0x13226A,False,2,"Forms"),
    LocationName.Valorlvl3                          : LocationData(0x13226B,False,3,"Forms"),
    LocationName.Valorlvl4                          : LocationData(0x13226C,False,4,"Forms"),
    LocationName.Valorlvl5                          : LocationData(0x13226D,False,5,"Forms"),
    LocationName.Valorlvl6                          : LocationData(0x13226E,False,6,"Forms"),
    LocationName.Valorlvl7                          : LocationData(0x13226F,False,7,"Forms"),
    LocationName.Wisdomlvl2                         : LocationData(0x132270,False,2,"Forms"),
    LocationName.Wisdomlvl3                         : LocationData(0x132271,False,3,"Forms"),
    LocationName.Wisdomlvl4                         : LocationData(0x132272,False,4,"Forms"),
    LocationName.Wisdomlvl5                         : LocationData(0x132273,False,5,"Forms"),
    LocationName.Wisdomlvl6                         : LocationData(0x132274,False,6,"Forms"),
    LocationName.Wisdomlvl7                         : LocationData(0x132275,False,7,"Forms"),
    LocationName.Limitlvl2                          : LocationData(0x132276,False,2,"Forms"),
    LocationName.Limitlvl3                          : LocationData(0x132277,False,3,"Forms"),
    LocationName.Limitlvl4                          : LocationData(0x132278,False,4,"Forms"),
    LocationName.Limitlvl5                          : LocationData(0x132279,False,5,"Forms"),
    LocationName.Limitlvl6                          : LocationData(0x13227A,False,6,"Forms"),
    LocationName.Limitlvl7                          : LocationData(0x13227B,False,7,"Forms"),
    LocationName.Masterlvl2                         : LocationData(0x13227C,False,2,"Forms"),
    LocationName.Masterlvl3                         : LocationData(0x13227D,False,3,"Forms"),
    LocationName.Masterlvl4                         : LocationData(0x13227E,False,4,"Forms"),
    LocationName.Masterlvl5                         : LocationData(0x13227F,False,5,"Forms"),
    LocationName.Masterlvl6                         : LocationData(0x132280,False,6,"Forms"),
    LocationName.Masterlvl7                         : LocationData(0x132281,False,7,"Forms"),
    LocationName.Finallvl2                          : LocationData(0x132282,False,2,"Forms"),
    LocationName.Finallvl3                          : LocationData(0x132283,False,3,"Forms"),
    LocationName.Finallvl4                          : LocationData(0x132284,False,4,"Forms"),
    LocationName.Finallvl5                          : LocationData(0x132285,False,5,"Forms"),
    LocationName.Finallvl6                          : LocationData(0x132286,False,6,"Forms"),
    LocationName.Finallvl7                          : LocationData(0x132287,False,7,"Forms"),
}                                                                  
GoA_Checks={                                                       
    LocationName.GardenofAssemblageMap              : LocationData(0x132288,False,585,"Chest"),
    LocationName.GoALostIllusion                    : LocationData(0x132289,False,586,"Chest"),        
    LocationName.ProofofNonexistence                : LocationData(0x13228A,False,590,"Chest"),
    }
#Keyblade_Slots={
#    LocationName.FAKESlot                           :LocationData(0x13228B),
#    LocationName.DetectionSaberSlot                 :LocationData(0x13228C),
#    LocationName.EdgeofUltimaSlot                   :LocationData(0x13228D),
#    LocationName.KingdomKeySlot                     :LocationData(0x13228E),
#    LocationName.OathkeeperSlot                     :LocationData(0x13228F),
#    LocationName.OblivionSlot                       :LocationData(0x13229"Second Get Bonus"),
#    LocationName.StarSeekerSlot                     :LocationData(0x13229"Chest"),
#    LocationName.HiddenDragonSlot                   :LocationData(0x13229"Get Bonus"),
#    LocationName.HerosCrestSlot                     :LocationData(0x13229"Double Get Bonus"),
#    LocationName.MonochromeSlot                     :LocationData(0x13229"Levels"),
#    LocationName.FollowtheWindSlot                  :LocationData(0x13229"Forms"),
#    LocationName.CircleofLifeSlot                   :LocationData(0x132296),
#    LocationName.PhotonDebuggerSlot                 :LocationData(0x132297),
#    LocationName.GullWingSlot                       :LocationData(0x132298),
#    LocationName.RumblingRoseSlot                   :LocationData(0x132299),
#    LocationName.GuardianSoulSlot                   :LocationData(0x13229A),
#    LocationName.WishingLampSlot                    :LocationData(0x13229B),
#    LocationName.DecisivePumpkinSlot                :LocationData(0x13229C),
#    LocationName.SweetMemoriesSlot                  :LocationData(0x13229D),
#    LocationName.MysteriousAbyssSlot                :LocationData(0x13229E),
#    LocationName.SleepingLionSlot                   :LocationData(0x13229F),
#    LocationName.BondofFlameSlot                    :LocationData(0x1322A"Second Get Bonus"),
#    LocationName.TwoBecomeOneSlot                   :LocationData(0x1322A"Chest"),
#    LocationName.FatalCrestSlot                     :LocationData(0x1322A"Get Bonus"),
#    LocationName.FenrirSlot                         :LocationData(0x1322A"Double Get Bonus"),
#    LocationName.UltimaWeaponSlot                   :LocationData(0x1322A"Levels"),
#    LocationName.WinnersProofSlot                   :LocationData(0x1322A"Forms"),
#    }                                                             
exclusion_table = {                                                
    "Datas": {                                                     
        LocationName.XemnasDataPowerBoost,                         
        LocationName.AxelDataMagicBoost,                           
        LocationName.RoxasDataMagicBoost,                          
        LocationName.SaixDataDefenseBoost,
        LocationName.DemyxDataAPBoost ,
        LocationName.LuxordDataAPBoost,
        LocationName.VexenDataLostIllusion,
        LocationName.LarxeneDataLostIllusion,
        LocationName.XaldinDataDefenseBoost,
        LocationName.MarluxiaDataLostIllusion,  
        LocationName.LexaeusDataLostIllusion,
        LocationName.XigbarDataDefenseBoost,
        
    },
    "SuperBosses":{
        LocationName.LingeringWillBonus,            
        LocationName.LingeringWillProofofConnection,
        LocationName.LingeringWillManifestIllusion,
        LocationName.SephirothBonus,
        LocationName.SephirothFenrir,
        },
    
    
    #These levels when level 50 is turned on should have Potion for yml writing reasons
    "Level50":{
        LocationName.Lvl7,
        LocationName.Lvl9,
        LocationName.Lvl12,
        LocationName.Lvl15,
        LocationName.Lvl17,
        LocationName.Lvl20,
        LocationName.Lvl23,
        LocationName.Lvl25,
        LocationName.Lvl28,
        LocationName.Lvl31,
        LocationName.Lvl33,
        LocationName.Lvl36,
        LocationName.Lvl39,
        LocationName.Lvl41,
        LocationName.Lvl44,
        LocationName.Lvl47,
        LocationName.Lvl49,
        LocationName.Lvl51,
        LocationName.Lvl52,
        LocationName.Lvl53,
        LocationName.Lvl54,
        LocationName.Lvl55,
        LocationName.Lvl56,
        LocationName.Lvl57,
        LocationName.Lvl58,
        LocationName.Lvl59,
        LocationName.Lvl60,
        LocationName.Lvl61,
        LocationName.Lvl62,
        LocationName.Lvl63,
        LocationName.Lvl64,
        LocationName.Lvl65,
        LocationName.Lvl66,
        LocationName.Lvl67,
        LocationName.Lvl68,
        LocationName.Lvl69,
        LocationName.Lvl70,
        LocationName.Lvl71,
        LocationName.Lvl72,
        LocationName.Lvl73,
        LocationName.Lvl74,
        LocationName.Lvl75,
        LocationName.Lvl76,
        LocationName.Lvl77,
        LocationName.Lvl78,
        LocationName.Lvl79,
        LocationName.Lvl80,
        LocationName.Lvl81,
        LocationName.Lvl82,
        LocationName.Lvl83,
        LocationName.Lvl84,
        LocationName.Lvl85,
        LocationName.Lvl86,
        LocationName.Lvl87,
        LocationName.Lvl88,
        LocationName.Lvl89,
        LocationName.Lvl90,
        LocationName.Lvl91,
        LocationName.Lvl92,
        LocationName.Lvl93,
        LocationName.Lvl94,
        LocationName.Lvl95,
        LocationName.Lvl96,
        LocationName.Lvl97,
        LocationName.Lvl98,
        LocationName.Lvl99,
        },
}
firstVisits=[
        LocationName.LoD_Region         ,        
        LocationName.Ag_Region          ,
        LocationName.Dc_Region          , 
        LocationName.Pr_Region          ,        
        LocationName.Oc_Region          ,             
        LocationName.Bc_Region          ,         
        LocationName.Sp_Region          ,
        LocationName.Ht_Region          , 
        LocationName.Hb_Region          , 
        LocationName.Pl_Region          ,  
        LocationName.STT_Region         , 
        LocationName.TT_Region          , 
        LocationName.Twtnw_Region       ,
]
corChecks=[
    LocationName.CoRDepthsUpperLevelRemembranceGem ,
    LocationName.CoRMiningAreaSerenityGem          ,
    LocationName.CoRMiningAreaAPBoost              ,
    LocationName.CoRMiningAreaSerenityCrystal      ,
    LocationName.CoRMiningAreaManifestIllusion     ,
    LocationName.CoRMiningAreaSerenityGem2         ,
    LocationName.CoRMiningAreaDarkRemembranceMap   ,
    LocationName.CoRMineshaftMidLevelPowerBoost    ,
    LocationName.CoREngineChamberSerenityCrystal   ,
    LocationName.CoREngineChamberRemembranceCrystal,
    LocationName.CoREngineChamberAPBoost           ,
    LocationName.CoREngineChamberManifestIllusion  ,
    LocationName.CoRMineshaftUpperLevelMagicBoost  ,
    LocationName.CoRMineshaftUpperLevelAPBoost     ,
    LocationName.TransporttoRemembrance            ,
    ]

ag2Checks=[
    LocationName.RuinedChamberTornPages         ,
    LocationName.RuinedChamberRuinsMap          ,
    LocationName.GenieJafar                     ,
    LocationName.WishingLamp                    ,
    LocationName.LexaeusBonus                   ,
    LocationName.LexaeusASStrengthBeyondStrength,
    LocationName.LexaeusDataLostIllusion        ,
    ]
lvl50Checks=[
    LocationName.Lvl2,
    LocationName.Lvl4,
    LocationName.Lvl7,
    LocationName.Lvl9,
    LocationName.Lvl10,
    LocationName.Lvl12,
    LocationName.Lvl14,
    LocationName.Lvl15,
    LocationName.Lvl17,
    LocationName.Lvl20,
    LocationName.Lvl23,
    LocationName.Lvl25,
    LocationName.Lvl28,
    LocationName.Lvl30,
    LocationName.Lvl32,
    LocationName.Lvl34,
    LocationName.Lvl36,
    LocationName.Lvl39,
    LocationName.Lvl41,
    LocationName.Lvl44,
    LocationName.Lvl46,
    LocationName.Lvl48,
    LocationName.Lvl50,
]
formChecks=[
    LocationName.Valorlvl2,
    LocationName.Valorlvl3,
    LocationName.Valorlvl4,
    LocationName.Valorlvl5,
    LocationName.Valorlvl6,
    LocationName.Valorlvl7,
    LocationName.Wisdomlvl2,
    LocationName.Wisdomlvl3,
    LocationName.Wisdomlvl4,
    LocationName.Wisdomlvl5,
    LocationName.Wisdomlvl6,
    LocationName.Wisdomlvl7,
    LocationName.Limitlvl2,
    LocationName.Limitlvl3,
    LocationName.Limitlvl4,
    LocationName.Limitlvl5,
    LocationName.Limitlvl6,
    LocationName.Limitlvl7,
    LocationName.Masterlvl2,
    LocationName.Masterlvl3,
    LocationName.Masterlvl4,
    LocationName.Masterlvl5,
    LocationName.Masterlvl6,
    LocationName.Masterlvl7,
    LocationName.Finallvl2,
    LocationName.Finallvl3,
    LocationName.Finallvl4,
    LocationName.Finallvl5,
    LocationName.Finallvl6,
    LocationName.Finallvl7,
    ]
popupChecks=[
        LocationName.SweetMemories,
        LocationName.SpookyCaveMap,
        LocationName.StarryHillCureElement,
        LocationName.StarryHillOrichalcumPlus,
        LocationName.AgrabahMap,
        LocationName.LampCharm,
        LocationName.WishingLamp,
        LocationName.DarkThornCureElement,
        LocationName.RumblingRose,
        LocationName.CastleWallsMap,
        LocationName.SecretAnsemReport4,
        LocationName.DisneyCastleMap, 
        LocationName.WindowofTimeMap,
        LocationName.Monochrome,
        LocationName.WisdomForm,
        LocationName.LingeringWillProofofConnection,
        LocationName.LingeringWillManifestIllusion, 
        LocationName.OogieBoogieMagnetElement,
        LocationName.Present,
        LocationName.DecoyPresents,
        LocationName.DecisivePumpkin,
        LocationName.MarketplaceMap,
        LocationName.MerlinsHouseMembershipCard,
        LocationName.MerlinsHouseBlizzardElement,
        LocationName.BaseballCharm,
        LocationName.AnsemsStudyMasterForm,  
        LocationName.AnsemsStudySleepingLion,
        LocationName.FFFightsCureElement,
        LocationName.ThousandHeartlessSecretAnsemReport1,
        LocationName.ThousandHeartlessIceCream,
        LocationName.ThousandHeartlessPicture, 
        LocationName.WinnersProof,
        LocationName.ProofofPeace,
        LocationName.SephirothFenrir,
        LocationName.EncampmentAreaMap,
        LocationName.Mission3,
        LocationName.VillageCaveAreaMap,
        LocationName.HiddenDragon,
        LocationName.ColiseumMap,
        LocationName.OlympusStone,
        LocationName.HerosCrest,
        LocationName.AuronsStatue, 
        LocationName.GuardianSoul,
        LocationName.ProtectBeltPainandPanicCup,
        LocationName.SerenityGemPainandPanicCup,
        LocationName.RisingDragonCerberusCup ,
        LocationName.SerenityCrystalCerberusCup,
        LocationName.GenjiShieldTitanCup,
        LocationName.SkillfulRingTitanCup,
        LocationName.FatalCrestGoddessofFateCup,
        LocationName.OrichalcumPlusGoddessofFateCup,
        LocationName.HadesCupTrophyParadoxCups,
        LocationName.IsladeMuertaMap,
        LocationName.FollowtheWind,
        LocationName.SeadriftRowShipGraveyardMap,
        LocationName.SecretAnsemReport6,
        LocationName.CircleofLife,
        LocationName.ScarFireElement,
        LocationName.TwilightTownMap,
        LocationName.MunnyPouchOlette,
        LocationName.JunkChampionBelt,  
        LocationName.JunkMedal,         
        LocationName.TheStruggleTrophy,
        LocationName.NaminesSketches,
        LocationName.MansionMap,
        LocationName.PhotonDebugger,
        LocationName.StationPlazaSecretAnsemReport2,
        LocationName.MunnyPouchMickey,              
        LocationName.CrystalOrb,
        LocationName.StarSeeker,
        LocationName.ValorForm,
        LocationName.SeifersTrophy,
        LocationName.Oathkeeper,   
        LocationName.LimitForm,    
        LocationName.BeamSecretAnsemReport10,
        LocationName.BetwixtandBetweenBondofFlame,
        LocationName.TwoBecomeOne,
        LocationName.RoxasSecretAnsemReport8,
        LocationName.XigbarSecretAnsemReport3,
        LocationName.Oblivion,
        LocationName.CastleThatNeverWasMap,
        LocationName.LuxordSecretAnsemReport9,
        LocationName.SaixSecretAnsemReport12, 
        LocationName.PreXemnas1SecretAnsemReport11,
        LocationName.Xemnas1SecretAnsemReport13,
        LocationName.XemnasDataPowerBoost,
        LocationName.AxelDataMagicBoost,
        LocationName.RoxasDataMagicBoost,
        LocationName.SaixDataDefenseBoost,
        LocationName.DemyxDataAPBoost ,
        LocationName.LuxordDataAPBoost,
        LocationName.VexenDataLostIllusion,
        LocationName.LarxeneDataLostIllusion,
        LocationName.XaldinDataDefenseBoost,
        LocationName.MarluxiaDataLostIllusion,  
        LocationName.LexaeusDataLostIllusion,
        LocationName.XigbarDataDefenseBoost,
        LocationName.VexenASRoadtoDiscovery,
        LocationName.LarxeneASCloakedThunder,
        LocationName.ZexionASBookofShadows,
        LocationName.LexaeusASStrengthBeyondStrength,
        LocationName.MarluxiaASEternalBlossom
    ]
getBonus=[
   "Xemnas 1 Bonus",
   "Thresholder",
   "Dark Thorn Bonus",
   "Xaldin Bonus",
   "Cerberus",
   "Pete (OC)",
   "Hydra",
   "Hades",
   "Shan-Yu",
   "Beast",
   "Storm Rider",
   "Bailey",
   "Boat Pete",
   "Village Cave",
   "Future Pete",
   "Prison Keeper",
   "Oogie Boogie",
   "Experiment",
   "Barbossa",
   "Grim Reaper 2",
   "Xigbar",
   "Luxord",
   "Saix",
   "Demyx (Hollow Bastion)",
   "Scar",
   "Groundshaker",
   "Hostile Program",
   "MCP",
   "Sephiroth Bonus",
   "Elemental Lords",
   "Minnie Escort",
   "Interceptor Barrels",
   "Lock, Shock, and Barrel",
   "Abu Escort",
   "Screens",
   "Treasure Room",
   "Genie Jafar",
   "Hyenas 1",
   "Hyenas 2",
   "Mansion Nobodies",
   "Urns",
   "Demyx OC",
   "Grim Reaper 1",
   "1000 Heartless",
   "Solar Sailer",
   "Boat Fight",
   "Betwixt and Between",
   "Vexen Bonus",
   "Lexaeus Bonus",
   "Zexion Bonus",
   "Marluxia Bonus",
   "Larxene Bonus",
   "Roxas",
   "Lingering Will Bonus",
   "Final Xemnas",
   "Transport to Remembrance", 
   

]

all_locations={
    **TWTNW_Checks,
    **TWTNW2_Checks,
    **TT_Checks,
    **TT2_Checks,
    **TT3_Checks,
    **STT_Checks,
    **PL_Checks,
    **PL2_Checks,
    **CoR_Checks,
    **FirstHalf_Checks,
    **SecondHalf_Checks,
    **HB_Checks,
    **HB2_Checks,
    **HT_Checks,
    **HT2_Checks,
    **PR_Checks,
    **PR2_Checks,
    **PR_Checks,
    **PR2_Checks,
    **SP_Checks,
    **SP2_Checks,
    **BC_Checks,
    **BC2_Checks,
    **Oc_Checks,
    **Oc2_Checks,
    **Oc2Cups,
    **HadesCups,
    **HundredAcre1_Checks,
    **HundredAcre2_Checks,
    **HundredAcre3_Checks,
    **HundredAcre4_Checks,
    **HundredAcre5_Checks,
    **HundredAcre6_Checks,
    **DC_Checks,
    **TR_Checks,
    **AG_Checks,
    **AG2_Checks,
    **LoD_Checks,
    **LoD2_Checks,
    **SoraLevels,
    **Form_Checks,
    **GoA_Checks,
    }

location_table={}

def setup_locations(world,player:int):
    location_table={**TWTNW_Checks,**TWTNW2_Checks,**TT_Checks,**TT2_Checks,**TT3_Checks,**STT_Checks,
                    **PL_Checks,**PL2_Checks,**CoR_Checks,**FirstHalf_Checks,**SecondHalf_Checks,**HB_Checks,**HB2_Checks,
                    **PR_Checks,**PR2_Checks,**PR_Checks,**PR2_Checks,**SP_Checks,**SP2_Checks,**BC_Checks,**BC2_Checks,**HT_Checks,**HT2_Checks,
                    **Oc_Checks,**Oc2_Checks,**HadesCups,**Oc2Cups,
                    **HundredAcre1_Checks,**HundredAcre2_Checks,**HundredAcre3_Checks,**HundredAcre4_Checks,**HundredAcre5_Checks,**HundredAcre6_Checks,
                    **DC_Checks,**TR_Checks,**AG_Checks,**AG2_Checks,**LoD_Checks,**LoD2_Checks,**SoraLevels,**Form_Checks,**GoA_Checks}
    return location_table
lookup_id_to_Location: typing.Dict[int,str] = {data.code: item_name for item_name, data in location_table.items() if data.code}