# Strawberry Locations
strawberry_1  = "First Strawberry"
strawberry_2  = "Floating Blocks Strawberry"
strawberry_3  = "South-East Tower Top Strawberry"
strawberry_4  = "Theo Strawberry"
strawberry_5  = "Fall Through Spike Floor Strawberry"
strawberry_6  = "Troll Strawberry"
strawberry_7  = "Falling Blocks Strawberry"
strawberry_8  = "Traffic Block Strawberry"
strawberry_9  = "South-West Dash Refills Strawberry"
strawberry_10 = "South-East Tower Side Strawberry"
strawberry_11 = "Girders Strawberry"
strawberry_12 = "North-East Tower Bottom Strawberry"
strawberry_13 = "Breakable Blocks Strawberry"
strawberry_14 = "Feather Maze Strawberry"
strawberry_15 = "Feather Chain Strawberry"
strawberry_16 = "Feather Hidden Strawberry"
strawberry_17 = "Double Dash Puzzle Strawberry"
strawberry_18 = "Double Dash Spike Climb Strawberry"
strawberry_19 = "Double Dash Spring Strawberry"
strawberry_20 = "North-East Tower Breakable Bottom Strawberry"
strawberry_21 = "Theo Tower Lower Cassette Strawberry"
strawberry_22 = "Theo Tower Upper Cassette Strawberry"
strawberry_23 = "South End of Bridge Cassette Strawberry"
strawberry_24 = "You Are Ready Cassette Strawberry"
strawberry_25 = "Cassette Hidden in the House Strawberry"
strawberry_26 = "North End of Bridge Cassette Strawberry"
strawberry_27 = "Distant Feather Cassette Strawberry"
strawberry_28 = "Feather Arches Cassette Strawberry"
strawberry_29 = "North-East Tower Cassette Strawberry"
strawberry_30 = "Badeline Cassette Strawberry"

# Friend Locations
granny_1   = "Granny Conversation 1"
granny_2   = "Granny Conversation 2"
granny_3   = "Granny Conversation 3"
theo_1     = "Theo Conversation 1"
theo_2     = "Theo Conversation 2"
theo_3     = "Theo Conversation 3"
badeline_1 = "Badeline Conversation 1"
badeline_2 = "Badeline Conversation 2"
badeline_3 = "Badeline Conversation 3"

# Sign Locations
sign_1 = "Camera Sign"
sign_2 = "Skid Jump Sign"
sign_3 = "Dash Jump Sign"
sign_4 = "Lonely Sign"
sign_5 = "Credits Sign"

# Car Locations
car_1 = "Intro Car"
car_2 = "Secret Car"
