# Level Base Regions
forsaken_city = "Forsaken City"

# Forsaken City Regions
intro_islands        = "Intro Islands"
granny_island        = "Granny Island"
highway_island       = "Freeway Island"
nw_girders_island    = "North-West Girders Island"
ne_feathers_island   = "North-East Feathers Island"
se_house_island      = "South-East House Island"
badeline_tower_lower = "Badeline Tower Lower"
badeline_tower_upper = "Badeline Tower Upper"
badeline_island      = "Badeline Island"

cassette_1  = "Horizontal Traffic Blocks Cassette"
cassette_2  = "Dash Refills Cassette"
cassette_3  = "Coin Puzzle Cassette"
cassette_4  = "Vertical Traffic Blocks Cassette"
cassette_5  = "Double Dash Cassette"
cassette_6  = "Cassette Block Cassette"
cassette_7  = "Falling Coins Cassette"
cassette_8  = "Feathers Cassette"
cassette_9  = "Skid Jump Cassette"
cassette_10 = "Final Challenge Cassette"

cassette_entrance_1  = "Theo Tower Lower Cassette"
cassette_entrance_2  = "Theo Tower Upper Cassette"
cassette_entrance_3  = "South End of Bridge Cassette"
cassette_entrance_4  = "You Are Ready Cassette"
cassette_entrance_5  = "Cassette Hidden in the House"
cassette_entrance_6  = "North End of Bridge Cassette"
cassette_entrance_7  = "Distant Feather Cassette"
cassette_entrance_8  = "Feather Arches Cassette"
cassette_entrance_9  = "Badeline Tower Cassette"
cassette_entrance_10 = "Badeline Island Cassette"
