name: Bug Report
description: File a bug report
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! If this bug occurred during generation check your
        Archipelago install for a log and upload it with this report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What were the expected results?
  - type: dropdown
    id: version
    attributes:
      label: Software
      description: Where did this bug occur?
      options:
        - Website
        - Local generation
        - While playing
    validations:
      required: true