name: Feature Request
description: Request a feature!
title: "Category: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Please replace `Category` in the title with what this feature will be targeting, such as Core generation,
        website, documentation, or a game.
        Note: this is not for requesting new games to be added. If you would like to request a game, the best place to
        ask is about it is in the [discord](https://archipelago.gg/discord).
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?