#############################################################################################################
#                                                                                                           #
#      ▄████▄   ▄▄▄       ██▓▄▄▄█████▓  ██████  ██▓▄▄▄█████▓ ██░ ██    ▄▄▄█████▓ █     █░ ▒█████            #
#     ▒██▀ ▀█  ▒████▄    ▓██▒▓  ██▒ ▓▒▒██    ▒ ▓██▒▓  ██▒ ▓▒▓██░ ██▒   ▓  ██▒ ▓▒▓█░ █ ░█░▒██▒  ██▒          #
#     ▒▓█    ▄ ▒██  ▀█▄  ▒██▒▒ ▓██░ ▒░░ ▓██▄   ▒██▒▒ ▓██░ ▒░▒██▀▀██░   ▒ ▓██░ ▒░▒█░ █ ░█ ▒██░  ██▒          #
#     ▒▓▓▄ ▄██▒░██▄▄▄▄██ ░██░░ ▓██▓ ░   ▒   ██▒░██░░ ▓██▓ ░ ░▓█ ░██    ░ ▓██▓ ░ ░█░ █ ░█ ▒██   ██░          #
#     ▒ ▓███▀ ░ ▓█   ▓██▒░██░  ▒██▒ ░ ▒██████▒▒░██░  ▒██▒ ░ ░▓█▒░██▓     ▒██▒ ░ ░░██▒██▓ ░ ████▓▒░          #
#     ░ ░▒ ▒  ░ ▒▒   ▓▒█░░▓    ▒ ░░   ▒ ▒▓▒ ▒ ░░▓    ▒ ░░    ▒ ░░▒░▒     ▒ ░░   ░ ▓░▒ ▒  ░ ▒░▒░▒░           #
#       ░  ▒     ▒   ▒▒ ░ ▒ ░    ░    ░ ░▒  ░ ░ ▒ ░    ░     ▒ ░▒░ ░       ░      ▒ ░ ░    ░ ▒ ▒░           #
#     ░          ░   ▒    ▒ ░  ░      ░  ░  ░   ▒ ░  ░       ░  ░░ ░     ░        ░   ░  ░ ░ ░ ▒            #
#     ░ ░            ░  ░ ░                 ░   ░            ░  ░  ░                ░        ░ ░            #
#     ░                                                                                                     #
#                                                                                                           #
#                                                                      @                                    #
#                           @@@@@                                   ,@@@@@@                                 #
#                        @@@@&@@@                                    ,@@@&@@@@                              #
#                     %@@@@&&@@@                                       @@@&&&@@@&                           #
#                   @@@@&&&@@@                                          ,@@@&&&@@@@                         #
#                @@@@&&&&&@@@                                             @@@&&&&&@@@@                      #
#              @@@@&&%&&@@@           @@@@@@@@@@@@@@@@@@@@@&               @@@@&&%&&&@@@                    #
#           @@@@&&%%&&&@@@      @@@@@@@@@@################%@@@@@@@@%         @@@&&&%&&&@@@@                 #
#         @@@@&&&%%&&@@@/  (@@@@@@################################&@@@@@@     @@@&&&%%&&&@@@@               #
#       @@@&&&&%%&&&@@@,@@@@@@#########################################%@@@@@  @@@&&&&%&&&&&@@@             #
#     @@@&&&&&%%&&&&@@@@@@@################################################&@@@@@@@&&&&%&&&&&&@@@           #
#   @@@&&&&&&%&&&&&@@@@@&#####################################################%@/.,&&&&&%&&&&&&&@@%         #
#  @@@&&&&&&&&&&&&&@@@###########################################################@#../&&&&&&&&&&&@@.        #
# @@@&&&&&%%%&&&&&&@######*    #####################################################@#...@%&&&&&&@@@        #
# @@@&&&&&&&&&&&&&#########*   /###################.  (####################@##@%*#@@#(#&@/.../@@&@@@        #
#  @@&&&&&&&&&&&###########.    ,###############/      ,##################@@@@**/**/@##&..%@&@/.....*@      #
#  @@@&&&&&&&&%####.                ,/###(/,            #*              .(####@@#****@###&&@/...,//..,      #
#   (@@@&&&&&#####*                                                          ######&@#####&&&&@@@..*,       #
#     @@@&&&######.      /@@@@@@@@@@@@@/                     &@@@@@@@@@@@@%     (##########&@@@@@,          #
#       @@@&######.   ,@@@@@%%%%%%%%%&@@@@@              /@@@@@%%%%%%%%%@@@@@&    .########&@@@.@.@         #
#       @@@#######(      %%((%%%&&%%%%%%# @@%           @@#.%%%%%%&&&%%#(#%,        ########@@@. /@         #
#      @@@@######(        #(((&&&&&&%%%     @          */    *%%%&&&&&(((#.          #######@@@@            #
#      @@@@######        ((/((#/%%/((((*                     ((((##%#/#((((           ######@@@@            #
#      @@@@#####           /((((((((((.                       (((((((((((             #####&@@@@            #
#      @@@@@####                                                                     .#####@@@@             #
#       @@@@&###.                          /@   .@#@&   ,@                           #####@@@@@             #
#        @@@@@###.                              (((((%                              #####@@@@@              #
#         @@@@@####                              (%&.                             #####%@@@@                #
#          %@@@@@%###                                                          .#####@@@@@                  #
#             @@@@@@@####(.                                                .####%@@@@@@                     #
#                @@@@@@@@@&#################/*....         ....,/########%@@@@@@@@@                         #
#                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                               #
#                                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                           #
#                                                                                                           #
#############################################################################################################

description: CaitSith2's ALttP YAML 1 of 1
name: 
#  CaitSith {NUMBER}: 1
#  Yunica Tovah {NUMBER}: 1
#  Adol Christin {NUMBER}: 1
  Untitled Goose {NUMBER}: 1
#  Boco {NUMBER}: 1
#  Popoi {NUMBER}: 1
game:
  A Link to the Past: 1
requires:
  version: 0.2.3
  plando: bosses
# Shared Options supported by all games:
accessibility:
  items: 0
  locations: 50
  none: 0
progression_balancing: 50
A Link to the Past:
  start_hints:
    - Swords
    - Lamp
  start_location_hints:
    - 'Take-Any #1'
    - 'Take-Any #2'
    - 'Take-Any #3'
    - 'Take-Any #4'
    - 'Old Man Sword Cave'
  start_inventory:
    Rupees (300): 33
    Bombs (10): 1
    Arrows (10): 3
    Pegasus Boots: 1
  glitches_required:
    none: 50
    minor_glitches: 0
    overworld_glitches: 0
    hybrid_major_glitches: 0
    no_logic: 0
  dark_room_logic:
    lamp: 0
    torches: 1
    none: 0
  restrict_dungeon_item_on_boss:
    on: 0
    off: 50
  bigkey_shuffle:
    original_dungeon: 0
    own_dungeons: 1
    own_world: 0
    any_world: 0
    different_world: 0
    start_with: 0
  smallkey_shuffle:
    original_dungeon: 0
    own_dungeons: 1
    own_world: 0
    any_world: 0
    different_world: 0
    universal: 0
    start_with: 0
  compass_shuffle:
    original_dungeon: 0
    own_dungeons: 0
    own_world: 0
    any_world: 0
    different_world: 0
    start_with: 1
  map_shuffle:
    original_dungeon: 0
    own_dungeons: 0
    own_world: 0
    any_world: 1
    different_world: 0
    start_with: 0
  key_drop_shuffle:
    on: 1
    off: 0
  dungeon_counters:
    on: 50
    pickup: 0
    default: 0
    off: 0
  progressive:
    on: 50
    off: 0
    grouped_random: 0
  local_items:
    - Swords
    - Moon Pearl
    - Lamp
    - Bottles
    - Flute
    - Magic Mirror
    - Gloves
    - Hammer
    - Hookshot
    - Flippers
    - Magic Powder
    - Cane of Somaria
    - Bombos
    - Fire Rod
    - Ice Rod
    - Book of Mudora
    - Shovel
    - Mushroom
  entrance_shuffle:
    none: 0
    dungeonssimple: 0
    dungeonsfull: 0
    dungeonscrossed: 0
    dungeonscrossed-1000: 1
    simple: 0
    restricted: 0
    full: 0
    crossed: 0
    insanity: 0
    crossed-1000: 0
    crossed-group-myfriends: 0
  goals:
    ganon: 0
    crystals: 0
    bosses: 1
    pedestal: 0
    ganon_pedestal: 0
    triforce_hunt: 0
    local_triforce_hunt: 0
    ganon_triforce_hunt: 0
    local_ganon_triforce_hunt: 0
    ice_rod_hunt: 0
  open_pyramid:
    goal: 50
    auto: 0
    yes: 0
    no: 0
  triforce_pieces_mode:
    extra: 0
    percentage: 0
    available: 50
  triforce_pieces_extra:
    0: 0
    5: 50
    10: 50
    15: 0
    20: 0
  triforce_pieces_percentage:
    100: 0
    150: 50
    200: 0
  triforce_pieces_available:
    25: 0
    30: 0
    40: 1
    60: 0
  triforce_pieces_required:
    15: 0
    20: 0
    30: 1
    40: 0
    60: 0
  crystals_needed_for_gt:
    0: 50
    7: 0
    random: 0
    random-low: 0
    random-middle: 0
    random-high: 0
  crystals_needed_for_ganon:
    0: 0
    3: 0
    4: 0
    5: 50
    6: 50
    7: 50
    random: 0
    random-low: 0
    random-middle: 0
    random-high: 0
  mode:
    standard: 0
    open: 50
    inverted: 0
  retro_bow:
    on: 0
    off: 50
  retro_caves:
    on: 1
    off: 0
  hints:
    'on': 1
    'off': 0
    full: 0
  scams:
    'off': 1
    'king_zora': 0
    'bottle_merchant': 0
    'all': 0
  swordless:
    on: 0
    off: 1
  item_pool:
    easy: 1
    normal: 0
    hard: 0
    expert: 0
  item_functionality:
    easy: 50
    normal: 0
    hard: 0
    expert: 0
  tile_shuffle:
    on: 50
    off: 0
  misery_mire_medallion:
    random: 0
    Ether: 0
    Bombos: 1
    Quake: 0
  turtle_rock_medallion:
    random: 0
    Ether: 0
    Bombos: 1
    Quake: 0
  boss_shuffle:
    none: 0
    basic: 0
    full: 0
    chaos: 0
    
    #I have no desire to fight Trinexx on Ice. The boss that is able to go into all locations is being placed there instead.
    Ganons Tower Bottom-Kholdstare;Trinexx;Kholdstare: 1
    Ganons Tower Bottom-Moldorm;Trinexx;Moldorm: 1
    Ganons Tower Bottom-Mothula;Trinexx;Mothula: 1
    Ganons Tower Bottom-Helmasaur King;Trinexx;Helmasaur King: 1
    Ganons Tower Bottom-Vitreous;Trinexx;Vitreous: 1
    #And the rest of the singularity combinations the exclude trinexx entirely.
    Armos Knights;Moldorm: 1
    Armos Knights;Helmasaur King: 0
    Armos Knights;Mothula: 1
    Armos Knights;Vitreous: 1
    Armos Knights;Kholdstare: 1
    Lanmolas;Moldorm: 1
    Lanmolas;Helmasaur King: 1
    Lanmolas;Mothula: 1
    Lanmolas;Vitreous: 1
    Lanmolas;Kholdstare: 1
    Arrghus;Moldorm: 1
    Arrghus;Helmasaur King: 1
    Arrghus;Mothula: 1
    Arrghus;Vitreous: 1
    Arrghus;Kholdstare: 1
    Blind;Moldorm: 1
    Blind;Helmasaur King: 1
    Blind;Mothula: 1
    Blind;Vitreous: 1
    Blind;Kholdstare: 1
    Moldorm: 1
    Helmasaur King: 1
    Mothula: 1
    Vitreous: 1
    Kholdstare: 1
  enemy_shuffle:
    on: 0
    off: 50
  killable_thieves:
    on: 1
    off: 0
  bush_shuffle:
    on: 0
    off: 50
  enemy_damage:
    default: 50
    shuffled: 0
    chaos: 0
  enemy_health:
    default: 50
    easy: 0
    hard: 0
    expert: 0
  pot_shuffle:
    'on': 0
    'off': 50
  beemizer_total_chance:
    0: 100  
    25: 0  
    50: 0  
    75: 0  
    100: 0 
  beemizer_trap_chance:
    0: 100
    60: 0 
    70: 0  
    80: 0  
    90: 0  
    100: 0 
  shop_item_slots:
    0: 1
    5: 0
    15: 0
    30: 0
    random: 0
  shop_price_modifier:
    0: 0
    400: 0
    random: 0
    random-low: 0
    random-high: 0
    100: 50
  shop_shuffle:
    none: 0
    uw: 50
    g: 0
    f: 0
    i: 0
    p: 0
    w: 0
    ip: 0
    fpu: 0
    uip: 0
  shuffle_prizes:
    none: 0
    g: 50
    b: 0
    bg: 0
  timer:
    none: 50
    timed: 0
    timed_ohko: 0
    ohko: 0
    timed_countdown: 0
    display: 0
  countdown_start_time:
    0: 0
    10: 50
    20: 0
    30: 0
    60: 0
  red_clock_time:
    -2: 50
    1: 0
  blue_clock_time:
    1: 0
    2: 50
  green_clock_time:
    4: 50
    10: 0
    15: 0
  glitch_boots:
    on: 50
    off: 0
  random_sprite_on_event:
    enabled: 
      on: 1
      off: 0
    on_hit: 
      on: 1
      off: 0
    on_enter: 
      on: 1
      off: 1
    on_exit: 
      on: 1
      off: 1
    on_slash: 
      on: 1
      off: 1
    on_item: 
      on: 1
      off: 1
    on_bonk: 
      on: 1
      off: 1
    on_everything: 
      on: 0
      off: 1
    use_weighted_sprite_pool: 
      on: 1
      off: 0
  sprite:
    goose: 1
    boco: 1
    yunica tovah: 1
    adol: 1
    popoi: 1
  music:
    on: 50
    off: 0
  quickswap:
    on: 50
    off: 0
  triforcehud:
    normal: 0
    hide_goal: 0
    hide_required: 0
    hide_both: 1
  reduceflashing:
    on: 50
    off: 0
  menuspeed:
    normal: 0
    instant: 0
    double: 0
    triple: 0
    quadruple: 1
    half: 0
  heartcolor:
    red: 0
    blue: 1
    green: 0
    yellow: 0
    random: 0
  heartbeep:
    double: 0
    normal: 0
    half: 0
    quarter: 1
    off: 0
  ow_palettes:
    default: 50
    good: 0
    blackout: 0
    grayscale: 0
    negative: 0
    classic: 0
    dizzy: 0
    sick: 0
    puke: 0
  uw_palettes:
    default: 50
    good: 0
    blackout: 0
    grayscale: 0
    negative: 0
    classic: 0
    dizzy: 0
    sick: 0
    puke: 0
  hud_palettes:
    default: 50
    good: 0
    blackout: 0
    grayscale: 0
    negative: 0
    classic: 0
    dizzy: 0
    sick: 0
    puke: 0
  sword_palettes:
    default: 50
    good: 0
    blackout: 0
    grayscale: 0
    negative: 0
    classic: 0
    dizzy: 0
    sick: 0
    puke: 0
  shield_palettes:
    default: 50
    good: 0
    blackout: 0
    grayscale: 0
    negative: 0
    classic: 0
    dizzy: 0
    sick: 0
    puke: 0
  legacy_weapons:
    trigger_disabled: 50
    randomized: 0
    assured: 0
    vanilla: 0
    swordless: 0
  death_link:
    false: 50
    true: 0
  allow_collect:
    false: 0
    true: 1
linked_options:
  - name: crosskeys
    options:
      A Link to the Past:
        entrance_shuffle: crossed
        bigkey_shuffle: true
        compass_shuffle: true
        map_shuffle: true
        smallkey_shuffle: true
    percentage: 0
  - name: localcrosskeys
    options:
      A Link to the Past:
        entrance_shuffle: crossed
        bigkey_shuffle: true
        compass_shuffle: true
        map_shuffle: true
        smallkey_shuffle: true
        local_items:
          - "Small Keys"
          - "Big Keys"
    percentage: 0
  - name: enemizer
    options:
      A Link to the Past:
        boss_shuffle:
          basic: 1
          full: 1
          chaos: 1
          singularity: 1
        enemy_damage:
          shuffled: 1
          chaos: 1
        enemy_health:
          easy: 1
          hard: 1
          expert: 1
    percentage: 0
triggers:
  - option_name: legacy_weapons
    option_result: randomized
    option_category: A Link to the Past
    options:
      A Link to the Past:
        swordless: off
  - option_name: legacy_weapons
    option_result: assured
    option_category: A Link to the Past
    options:
      A Link to the Past:
        swordless: off
        start_inventory:
          Progressive Sword: 1
  - option_name: legacy_weapons
    option_result: vanilla
    option_category: A Link to the Past
    options:
      A Link to the Past:
        swordless: off
        plando_items:
          - items:
              Progressive Sword: 4
            locations:
              - Master Sword Pedestal
              - Pyramid Fairy - Left
              - Blacksmith
              - Link's Uncle
          - items:
              Moon Pearl: 1
              Lamp: 1
            locations:
              - early_locations
  - option_name: legacy_weapons
    option_result: swordless
    option_category: A Link to the Past
    options:
      A Link to the Past:
        swordless: on
  - option_name: enemy_damage
    option_category: A Link to the Past
    option_result: shuffled
    percentage: 0
    options:
      A Link to the Past:
        swordless: off
  - option_name: name
    option_result: Yunica Tovah {NUMBER}
    option_category: null
    options:
      A Link to the Past:
        sprite:
          goose: 1
          boco: 1
          yunica tovah: 28
          adol: 1
          popoi: 1
  - option_name: name
    option_result: Adol Christin {NUMBER}
    option_category: null
    options:
      A Link to the Past:
        sprite:
          goose: 1
          boco: 1
          yunica tovah: 1
          adol: 28
          popoi: 1
  - option_name: name
    option_result: Untitled Goose {NUMBER}
    option_category: null
    options:
      A Link to the Past:
        sprite:
          goose: 28
          boco: 1
          yunica tovah: 1
          adol: 1
          popoi: 1
  - option_name: name
    option_result: Boco {NUMBER}
    option_category: null
    options:
      A Link to the Past:
        sprite:
          goose: 1
          boco: 28
          yunica tovah: 1
          adol: 1
          popoi: 1
  - option_name: name
    option_result: Popoi {NUMBER}
    option_category: null
    options:
      A Link to the Past:
        sprite:
          goose: 1
          boco: 1
          yunica tovah: 1
          adol: 1
          popoi: 28

