# Q. What is this file?
# A. This file contains options which allow you to configure your multiworld experience while allowing
#    others to play how they want as well.
#
# Q. How do I use it?
# A. The options in this file are weighted. This means the higher number you assign to a value, the
#    more chances you have for that option to be chosen. For example, an option like this:
#
#    map_shuffle:
#      on: 5
#      off: 15
#
#    Means you have 5 chances for map shuffle to occur, and 15 chances for map shuffle to be turned
#    off.
#
# Q. I've never seen a file like this before. What characters am I allowed to use?
# A. This is a .yaml file. You are allowed to use most characters.
#    To test if your yaml is valid or not, you can use this website:
#        http://www.yamllint.com/
#    You can also verify your Archipelago settings are valid at this site:
#        https://archipelago.gg/check

# Your name in-game. Spaces will be replaced with underscores and there is a 16-character limit.
#     {player} will be replaced with the player's slot number.
#     {PLAYER} will be replaced with the player's slot number, if that slot number is greater than 1.
#     {number} will be replaced with the counter value of the name.
#     {NUMBER} will be replaced with the counter value of the name, if the counter value is greater than 1.
name: DoomedRivers

# Used to describe your yaml. Useful if you have multiple files.
description: Default DOOM 1993 Template

game: DOOM 1993
requires:
  version: 0.4.0 # Version of Archipelago required for this yaml to work as expected.

DOOM 1993:
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0    # equivalent to 0
    normal: 1 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # Locations: ensure everything can be reached and acquired.
    # Items: ensure all logically relevant items can be acquired.
    # Minimal: ensure what is needed to reach your goal can be acquired.
    locations: 0
    items: 50
    minimal: 0

  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_hints:
    # Start with these item's locations prefilled into the !hint command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the !hint command
    []

  exclude_locations:
    # Prevent these locations from having an important item
    []

  priority_locations:
    # Prevent these locations from having an unimportant item
    []

  item_links:
    # Share part of your item pool with other players.
    []

  difficulty:
    # Choose the difficulty option. Those match DOOM's difficulty options.
    # baby (I'm too young to die.) double ammos, half damage, less monsters or strength.
    # easy (Hey, not too rough.) less monsters or strength.
    # medium (Hurt me plenty.) Default.
    # hard (Ultra-Violence.) More monsters or strength.
    # nightmare (Nightmare!) Monsters attack more rapidly and respawn.
    baby: 0
    easy: 0
    medium: 1
    hard: 0
    nightmare: 0

  random_monsters:
    # Choose how monsters are randomized.
    # vanilla: No randomization
    # shuffle: Monsters are shuffled within the level
    # random_balanced: Monsters are completely randomized, but balanced based on existing ratio in the level. (Small monsters vs medium vs big)
    vanilla: 0
    shuffle: 0
    random_balanced: 1

  random_items:
    # Choose how items are randomized.
    # vanilla: No randomization
    # shuffle: Items are shuffled within the level
    # random_balanced: Items are completely randomized, but balanced based on existing ratio in the level. (Small item vs Big)
    vanilla: 0
    shuffle: 0
    random_balanced: 1

  allow_death_logic:
    # Some locations require a timed puzzle that can only be tried once.
    # After which if the player failed to get it, the location cannot be checked anymore.
    # No progression items are placed in those are. There is a way, hovewer, to still get them:
    # Get killed in the current map. The map will reset, you can now attempt the puzzle again.
    false: 50
    true: 0

  death_link:
    # When you die, everyone dies. Of course the reverse is true too.
    false: 50
    true: 0

  episode1:
    # Knee-Deep in the Dead
    false: 0
    true: 50

  episode2:
    # The Shores of Hell
    false: 0
    true: 1

  episode3:
    # Inferno
    false: 1
    true: 0
  
  start_with_computer_area_maps:
    # Give the player all Computer Area Map items from the start.
    false: 0
    true: 1

---

Muse Dash:
  progression_balancing: 0
  accessibility: items
  available_trap_types: all
  # Activates deathlink... you know you want to.
  # Default: off
  death_link: off

  # How many songs you can start out with.
  # Note: Starting songs are first in line to get 2 items under additional_item_percentage
  # Range 3-10. Default: 5
  starting_song_count: 3

  # How many extra songs that are added in between the starting songs and ending songs.
  # Note: This value will be lower if other options limit songs too much.
  # Range 15-500. Default: 30
  additional_song_count: 50

  # Whether or not songs that come with the DLC 'Just As Planned' are included.
  # Default: false
  allow_just_as_planned_dlc_songs: 'true'

  # Whether or not the songs chosen are available in Streamer Mode. Recommended to only switch this on, if you want to stream Muse Dash.
  # Default: false
  streamer_mode_enabled: 'false'

  # The number of music sheets placed in the multiworld
  # Range 5-35. Default: 20
  music_sheet_count_percentage: 20

  # The number of music sheets required to win
  # Range 50-100. Default: 80
  music_sheet_win_count_percentage: 70

  # The percentage of songs that get a second reward
  # Range 50-100. Default: 80
  additional_item_percentage: 80

  # The number of traps placed in the multiworld
  # Range 0-35. Default: 15
  trap_count_percentage: 35

  # Sets the grade needed to get rewards.
  # Accepts the following: 'any'/0, 'c'/1, 'b'/2, 'a'/3, 'pinks'/4, 'silvers'/5.
  # Default: 'any'
  grade_needed: 'any'

  # Limits the range of songs chosen, such that at least 1 difficulty is within the chosen range. (Does not include secret difficulties)
  # Supports the following:
  #  'any' / 0 : Difficulty 1-11
  #  'easy' / 1 : Difficulty 1-3
  #  'medium' / 2 : Difficulty 4-5
  #  'hard' / 3 : Difficulty 6-7
  #  'expert' / 4 : Difficulty 8-9
  #  'master' / 5 : Difficulty 10-11
  #  'manual' / 6 : Allows song_difficulty_min and song_difficulty_max
  # Default: 'any'
  song_difficulty_mode: 'manual'

  # The following Options are only available under 'manual'" Must be between 1 and 11. Should not be randomised.
  song_difficulty_min: 6
  song_difficulty_max: 8

  # Any Traps or Songs you would want when starting the game. Any songs here will be considered as part of Starting Song Count.
  start_inventory:
    Bad Apple!! feat. Nomico: 1
  # Bad Apple Trap: 10
  # "Bad Apple!! feat. Nomico": 1

  # Any songs you would want included within the randomiser. Will count as a song for additional_song_count.
  # You will need to use the full name of the song. (i.e. "Bad Apple!! feat. Nomico") You can find this in song select at the bottom right while playing a seed.
  # Songs here will not be starting songs. Use start_inventory for that.
  include_songs:
    - Night of Nights
    - Cirno's Perfect Math Class
    - Brain Power
    - Nyan Cat
    - Glimmer
    - Magic Spell
    - Bang!!
    - Bit-alize
    - PeroPero in the Universe
    - I don't care about Christmas though
    - Dandelion's Daydream
    - Give Me 5
    - Sand Maze
    - Fireflies
    - Tenri Kaku Jou
  # - "Bad Apple!! feat. Nomico"

  # Any songs you would want excluded within the randomiser.
  # You will need to use the full name of the song. (i.e. "Bad Apple!! feat. Nomico") You can find this in song select at the bottom right while playing a seed.
  exclude_songs:
    - PUPA
    - sheep in the light
    - -+
    - Marry me, Nightmare
    - ManiFesto
  
  bad_apple_mode:
    on: 0
    off: 20
  
#  non_local_items:
#    - Music Sheet
#    - Bad Apple Trap
#    - Random Wave Trap
#    - Background Freeze Trap
#    - Pixelate Trap
#    - Gray Scale Trap
#    - Chromatic Aberration Trap
#    - Shadow Edge Trap
triggers: 
  - option_name: bad_apple_mode
    option_result: on
    option_category: Muse Dash
    options:
      Muse Dash:
        start_inventory:
          Bad Apple Trap: 150
          Bad Apple!! feat. Nomico: 1

description: 'Generated by https://archipelago.gg/'
game: Muse Dash
name: Rivers Dash
