services:
  web:
    build:
      context: ..
    entrypoint: >
      sh -c "python WebHost.py --config_override selflaunch.yaml & gunicorn -c gunicorn.conf.py"
    volumes:
      - static_volume:/app/WebHostLib
      - output_volume:/app/output
      - sprites_alttpr_volume:/app/sprites/alttpr
      - sprites_custom_volume:/app/sprites/custom
      - ./example_config.yaml:/app/config.yaml
      - ./example_selflaunch.yaml:/app/selflaunch.yaml
      - ./example_gunicorn.conf.py:/app/gunicorn.conf.py
    environment:
      #Bind gunicorn to 0.0.0.0:8000
      - PORT=8000
    network_mode: host

  nginx:
    image: nginx:stable-alpine
    volumes:
      - static_volume:/app/WebHostLib
      - ./example_nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  static_volume:
  output_volume:
  sprites_alttpr_volume:
  sprites_custom_volume:
