from typing import List

regions: List[str] = [
    "Opening Street",
    "Grassland 1",
    "Grassland 2",
    "Grassland 3",
    "Grassland 4",
    "Grassland 5",
    "Grassland 6",
    "Grassland 7",
    "Lake",
    "Hill Country 1",
    "Hill Country 2",
    "Hill Country 3",
    "Forest 1",
    "Forest 2",
    "Cavern 1",
    "Cavern 2",
    "Cavern 3",
    "Castle Gate",
    "Castle",
    "Seaside 1",
    "Seaside 2",
    "Seaside 3",
    "Seaside 4",
    "Mist Grove 1",
    "Mist Grove 2",
    "Mist Grove 3",
    "???",
    "Submarine 1",
    "Submarine 2",
    "Submarine 3",
    "Submarine 4",
    "Submarine Shrine",
    "Desert 1",
    "Desert 2",
    "Desert 3",
    "Desert 4",
    "Desert 5",
    "Oasis",
    "Desert 6",
    "Desert 7",
    "Desert 8",
    "Beach 1",
    "Beach 2",
    "Beach 3",
    "Pyramid",
    "Cavern 4",
    "Cavern 5",
    "Cavern 6",
    "Snowfield 1",
    "Snowfield 2",
    "Snowfield 3",
    "Snowfield 4",
    "Snowfield 5",
    "Snowfield 6",
    "Snowfield 7",
    "Snowfield 8",
    "Mountain 1",
    "Mountain 2",
    "Mountaintop",
    "Frozen Lake",
    "Ice Castle",
    "Snowfield 9",
    "!!!",
    "Beach 4",
    "Forest 3",
    "Forest 4",
    "Forest 5",
    "Forest 6",
    "Hell 1",
    "Hell 2",
    "Hell 3",
    "Hell 4",
    "Hell 5",
    "Hell 6",
    "Cavern 7",
    "Cavern 8",
    "Hell 7",
    "Hell 8",
    "Hell Gate",
    "Hell Castle",
    "Inferno 1",
    "Inferno 2",
    "Inferno 3",
    "Blood Lake",
    "Volcano",
]