# TODO - Generate these from the list file
# TODO - This file should be autogenerated

static_item_data_location = 0xe88
static_item_element_size = 9
item_position_table = 0x400
items_ram_start = 0xa1

# in case I need to place a rom address in the rom
rom_address_space_start = 0xf000

