map_generation_params = {
  "FluidsSpawnPrimaryColors": True,
  "FluidsSpawnSecondaryColors": False,
  "FluidsSpawnTertiaryColors": False,
  "FluidPatchLikelinessPercent": 40,
  "FluidPatchBaseSize": 2,
  "FluidPatchSizeGrowPercentPerChunk": 70,
  "FluidPatchMaxSize": 4,
  "ShapePatchLikelinessPercent": 100,
  "ShapePatchBaseSize": 2,
  "ShapePatchSizeGrowPercentPerChunk": 70,
  "ShapePatchMaxSize": 7,
  "ShapePatchShapeColorfulnessPercent": 50,
  "ShapePatchRareShapeLikelinessPercent": 30,
  "ShapePatchVeryRareShapeLikelinessPercent": 10,
  "ShapePatchGenerationLikeliness": [
    {"GenerationType": "TertiaryColorFullShapePure","MinimumDistanceToOrigin": 40,"LikelinessPerMille": 5},
    {"GenerationType": "TertiaryColorFullShape","MinimumDistanceToOrigin": 32,"LikelinessPerMille": 7},
    {"GenerationType": "TertiaryColorAlmostFullShape","MinimumDistanceToOrigin": 28,"LikelinessPerMille": 10},
    {"GenerationType": "TertiaryColorHalfShape","MinimumDistanceToOrigin": 24,"LikelinessPerMille": 10},
    {"GenerationType": "SecondaryColorFullShapePure","MinimumDistanceToOrigin": 20,"LikelinessPerMille": 15},
    {"GenerationType": "SecondaryColorFullShape","MinimumDistanceToOrigin": 16,"LikelinessPerMille": 20},
    {"GenerationType": "SecondaryColorAlmostFullShape","MinimumDistanceToOrigin": 12,"LikelinessPerMille": 25},
    {"GenerationType": "SecondaryColorHalfShape","MinimumDistanceToOrigin": 10,"LikelinessPerMille": 30},
    {"GenerationType": "PrimaryColorFullShapePure","MinimumDistanceToOrigin": 8,"LikelinessPerMille": 35},
    {"GenerationType": "PrimaryColorFullShape","MinimumDistanceToOrigin": 6,"LikelinessPerMille": 40},
    {"GenerationType": "PrimaryColorAlmostFullShape","MinimumDistanceToOrigin": 4,"LikelinessPerMille": 45},
    {"GenerationType": "PrimaryColorHalfShape","MinimumDistanceToOrigin": 3,"LikelinessPerMille": 50},
    {"GenerationType": "UncoloredFullShapePure","MinimumDistanceToOrigin": 2,"LikelinessPerMille": 100},
    {"GenerationType": "UncoloredFullShape","MinimumDistanceToOrigin": 1,"LikelinessPerMille": 300},
    {"GenerationType": "UncoloredAlmostFullShape","MinimumDistanceToOrigin": 1,"LikelinessPerMille": 500},
    {"GenerationType": "UncoloredHalfShape","MinimumDistanceToOrigin": 0,"LikelinessPerMille": 1000}
  ]
}
