<CampaignScroll>
    scroll_type: ["content", "bars"]
    bar_width: dp(12)
    effect_cls: "ScrollEffect"

<MultiCampaignLayout>
    cols: 1
    size_hint_y: None
    height: self.minimum_height + 15
    padding: [5,0,dp(12),0]

<CampaignLayout>:
    cols: 1

<MissionLayout>:
    rows: 1

<MissionCategory>:
    cols: 1
    spacing: [0,5]

<MissionButton>:
    text_size: self.size
    markup: True
    halign: 'center'
    valign: 'middle'
    padding: [5,0,5,0]
    outline_width: 1
