# autogenerated from Hamsandwich/tools/archipelago_data_scripts
from BaseClasses import ItemClassification
from worlds.generic.Rules import CollectionRule, add_rule
from worlds.loonyland.entrances import LLEntrance
from worlds.loonyland.flags import LLFlags
from worlds.loonyland.items import LLItem, LLItemCat
from worlds.loonyland.locations import LLLocation, LLLocCat
from worlds.loonyland.regions import LLRegion
from worlds.loonyland.rules import (
    can_cleanse_crypts,
    can_do_collection,
    can_kill_werewolves,
    can_reach_bats,
    can_reach_frog,
    can_reach_ghost,
    can_reach_mummy,
    can_reach_skeleton,
    can_reach_swampdog,
    can_reach_vampire,
    can_reach_wolves,
    have_39_badges,
    have_all_weapons,
    have_bombs,
    have_light_source,
    have_many_bombs,
    have_special_weapon_bullet,
    have_special_weapon_damage,
    hundred_percent,
    power_level,
)

ll_base_id: int = 2876900
VAR_HEART = 0
VAR_LIGHTNING = 20
VAR_ARROW = 30
VAR_PANTS = 40
VAR_QUESTASSIGN = 50
VAR_QUESTDONE = 70
VAR_MUSHROOM = 90
VAR_MYSORB = 100
VAR_WEAPON = 104
VAR_WBOMBS = 104
VAR_WLIGHTNING = 105
VAR_WICE = 106
VAR_WCACTUS = 107
VAR_WBOOMERANG = 108
VAR_WWHOOPEE = 109
VAR_WHOTPANTS = 110
VAR_KEY = 111
VAR_SKULLKEY = 111
VAR_BATKEY = 112
VAR_PUMPKINKEY = 113
VAR_BOOTS = 114
VAR_STICK = 115
VAR_TORCH = 116
VAR_FERTILIZER = 117
VAR_SILVER = 118
VAR_DAISY = 119
VAR_POTION = 120
VAR_VAMPBUST = 121
VAR_CAT = 129
VAR_GEM = 130
VAR_ORBSTAND = 150
VAR_BOOTSALES = 154
VAR_WITCHTALK = 155
VAR_BRIDGEOPEN = 156
VAR_ZOMBIE = 157
VAR_ZOMBIEREWARD = 160
VAR_TRIPLEFIRE = 161
VAR_TALISMAN = 162
VAR_VAMPYWALL = 163
VAR_BATSTATUE = 164
VAR_BATSTAND = 168
VAR_VAMPSTAND = 172
VAR_KNOWWOLVES = 180
VAR_DOLL = 181
VAR_BATDOLL = 181
VAR_SKELDOLL = 182
VAR_FROGDOLL = 183
VAR_GHOSTDOLL = 184
VAR_MUMMYDOLL = 185
VAR_SWAMPDOLL = 186
VAR_VAMPDOLL = 187
VAR_WOLFDOLL = 188
VAR_REFLECT = 189
VAR_DOLLGIVEN = 190
VAR_TOWNOPEN = 198
VAR_LEFTBOMB = 199
VAR_HELPERBAT = 200
VAR_TALKBAT = 201
VAR_TALKBRIDGE = 202
VAR_PAIDBRIDGE = 203
VAR_PORTALOPEN = 204
VAR_GAVEDAISY = 205
VAR_DEADELDER = 206
VAR_GATEOUT = 210
VAR_DEADBONK = 211
VAR_SEERTALK = 212
VAR_MINERTALK = 213
VAR_HPSALES = 214
VAR_DEALERTALK = 215
VAR_HIPUZZLE = 216
VAR_WITCHREWARD = 217
VAR_LANTERN = 218
VAR_TREEREWARD = 219
VAR_SILVERSLING = 220
VAR_LARRYREWARD = 221
VAR_CROPSREWARD = 222
VAR_ZOMBIEGEM = 223
ITM_NONE = 0
ITM_TINYHEART = 1
ITM_BIGHEART = 2
ITM_SUPERHEART = 3
ITM_LITTLEGEM = 4
ITM_BIGGEM = 5
ITM_SUPERGEM = 6
ITM_FIREPOWERUP = 7
ITM_RANGEUP = 8
ITM_FIRERATEUP = 9
ITM_KEY = 10
ITM_KEY2 = 11
ITM_KEY3 = 12
ITM_KEY4 = 13
ITM_WBOMB = 14
ITM_WLIGHTNING = 15
ITM_WICE = 16
ITM_WCACTUS = 17
ITM_WBOOMERANG = 18
ITM_WWHOOPEE = 19
ITM_WHOTPANTS = 20
ITM_POTION = 21
ITM_DOOR = 22
ITM_SKULLDOOR = 23
ITM_BATDOOR = 24
ITM_PUMPKINDOOR = 25
ITM_DOOR2 = 26
ITM_SKULLDOOR2 = 27
ITM_BATDOOR2 = 28
ITM_PUMPKINDOOR2 = 29
ITM_TREE1 = 30
ITM_TREE2 = 31
ITM_LAKECAVE = 32
ITM_TABLE = 33
ITM_STOOL = 34
ITM_CHAIR = 35
ITM_CHAIR2 = 36
ITM_CHAIR3 = 37
ITM_CHAIR4 = 38
ITM_CHAIR5 = 39
ITM_BIGCHAIR = 40
ITM_BIGCHAIR2 = 41
ITM_BIGCHAIR3 = 42
ITM_BIGCHAIR4 = 43
ITM_MYSORB = 44
ITM_ORBSTAND = 45
ITM_ORBSTAND2 = 46
ITM_SAVEGEM = 47
ITM_BOTTLE = 48
ITM_BOTTLE2 = 49
ITM_BOTTLE3 = 50
ITM_BOTTLE4 = 51
ITM_BOTTLE5 = 52
ITM_BOTTLE6 = 53
ITM_BOTTLE7 = 54
ITM_BOTTLE8 = 55
ITM_BOTTLE9 = 56
ITM_BOTTLE10 = 57
ITM_BOTTLE11 = 58
ITM_SIGN = 59
ITM_SIGN2 = 60
ITM_SIGN3 = 61
ITM_KNIGHT = 62
ITM_KNIGHT2 = 63
ITM_CLOCK = 64
ITM_CANDLE = 65
ITM_BOOKCASE = 66
ITM_BED = 67
ITM_LOG = 68
ITM_LOG2 = 69
ITM_LOG3 = 70
ITM_TWIG = 71
ITM_ROCK = 72
ITM_ROCKPILE = 73
ITM_BARREL = 74
ITM_BARREL2 = 75
ITM_TREE3 = 76
ITM_TREE4 = 77
ITM_TREE5 = 78
ITM_TREE6 = 79
ITM_TREE7 = 80
ITM_SHROOM = 81
ITM_DAISY = 82
ITM_SILVER = 83
ITM_MAGICPLANT = 84
ITM_WALKPLANT = 85
ITM_SWITCH1ON = 86
ITM_SWITCH1OFF = 87
ITM_SWITCH2 = 88
ITM_GRASS = 89
ITM_GRASS2 = 90
ITM_GRASS3 = 91
ITM_CATTAIL = 92
ITM_LILROCK = 93
ITM_BIGROCK = 94
ITM_BOOMROCK = 95
ITM_TORCH = 96
ITM_GASHOLE = 97
ITM_GASPIPELR = 98
ITM_GASPIPEUD = 99
ITM_GASPIPEDR = 100
ITM_GASPIPEDL = 101
ITM_GASPIPEUR = 102
ITM_GASPIPEUL = 103
ITM_GASSPARK = 104
ITM_GRAVE = 105
ITM_GRAVE2 = 106
ITM_TABLE2 = 107
ITM_AUTODOOR = 108
ITM_AUTODOOR2 = 109
ITM_TALISMAN = 110
ITM_TRIPLEFIRE = 111
ITM_BUSTSTAND = 112
ITM_BUST = 113
ITM_BUSTONSTAND = 114
ITM_BATSTAND = 115
ITM_BAT = 116
ITM_BATONSTAND = 117
ITM_BATDOLL = 118
ITM_SKELDOLL = 119
ITM_FROGDOLL = 120
ITM_GHOSTDOLL = 121
ITM_MUMMYDOLL = 122
ITM_SWAMPDOLL = 123
ITM_VAMPDOLL = 124
ITM_WOLFDOLL = 125
ITM_PORTAL = 126
ITM_BADGE = 127
ITM_CAT = 128
ITM_ZOMBGEM = 129
ITM_BOOTS = 130
ITM_FERTILIZER = 131
ITM_GHOSTPOTION = 132
ITM_LANTERN = 133
ITM_REFLECTGEM = 134
ITM_SILVERSLING = 135
ITM_STICK = 136
ITM_ARCHIPELAGO = 137
BADGE_EVILIZER = 0
BADGE_BOWLING = 1
BADGE_GRAVES = 2
BADGE_GEMS = 3
BADGE_MONSTERPTS = 4
BADGE_MONSTERPTS2 = 5
BADGE_POLTERGUY = 6
BADGE_DARKNESS = 7
BADGE_BESTRANK = 8
BADGE_LOONYBALL = 9
BADGE_BOSSBASH = 10
BADGE_BONKULA = 11
BADGE_SNEAK = 12
BADGE_WITCH = 13
BADGE_WOLFDEN = 14
BADGE_ANNOY = 15
BADGE_RESCUE = 16
BADGE_WINGAME = 17
BADGE_COMBO = 18
BADGE_ROCKS = 19
BADGE_HIDDEN = 20
BADGE_TERRORSRV = 21
BADGE_KILLALL = 22
BADGE_HUNDREDPCT = 23
BADGE_SURVIVAL = 24
BADGE_LARRY = 25
BADGE_TERROR = 26
BADGE_FRANKENJ = 27
BADGE_SURVCOMBO = 28
BADGE_CATTAILS = 29
BADGE_REMIX = 30
BADGE_WITCHCRAFT = 31
BADGE_THIEF = 32
BADGE_SURV100 = 33
BADGE_RIOT = 34
BADGE_SWAMPDOG = 35
BADGE_SCORE = 36
BADGE_BRAWL = 37
BADGE_HIDDEN2 = 38
BADGE_MASTER = 39
CH_LIGHT = 0
CH_DISCO = 1
CH_TERROR = 2
CH_SURPRISE = 3
CH_QUICK = 4
CH_GEMS = 5
CH_SIDEKICK = 6
CH_HOMING = 7
CH_MAXPOWER = 8
CH_VINTAGE = 9
CH_BONKULA = 10
CH_TOAD = 11
CH_CRYSTAL = 12
CH_RADAR = 13
CH_HEAVYHIT = 14
CH_RAPIDFIRE = 15
CH_DEATH = 16
CH_ALLACCESS = 17
CH_SWAMPDOG = 18
CH_HARDCORE = 19
CH_SAVEANY = 20
CH_GUIDED = 21
CH_SLOMO = 22
CH_CORPSE = 23
CH_FROGWPN = 24
CH_WITCH = 25
CH_WEREWOLF = 26
CH_RESPAWN = 27
CH_KICKCAT = 28
CH_RNDSURVIVAL = 29
CH_SUMMON = 30
CH_THIEF = 31
CH_WALLWALK = 32
CH_SUPERSURV = 33
CH_BEND = 34
CH_STINKY = 35
CH_ULTRAWEAPON = 36
CH_THORNS = 37
CH_REGEN = 38
CH_NOFARLEY = 39
AP_BADGEMOD = 1000
AP_MODEMOD = 2000
AP_FILLERMOD = 3000
MODE_SURVIVAL = 0
MODE_BOSSBASH = 1
MODE_LOONYBALL = 2
MODE_BOWLING = 3
MODE_BADGES = 4
MODE_REMIX = 5
loony_item_table: dict[str, LLItem] = {
    "Heart": LLItem(ll_base_id + VAR_HEART, LLItemCat.ITEM, ItemClassification.useful, 20, flags=LLFlags.PWR),
    "Lightning": LLItem(ll_base_id + VAR_LIGHTNING, LLItemCat.ITEM, ItemClassification.useful, 10, flags=LLFlags.PWR),
    "Arrow": LLItem(ll_base_id + VAR_ARROW, LLItemCat.ITEM, ItemClassification.useful, 10, flags=LLFlags.PWR),
    "Pants": LLItem(ll_base_id + VAR_PANTS, LLItemCat.ITEM, ItemClassification.useful, 10, flags=LLFlags.PWR),
    "Mushroom": LLItem(ll_base_id + VAR_MUSHROOM, LLItemCat.ITEM, ItemClassification.progression, 10),
    "Orb": LLItem(ll_base_id + VAR_MYSORB, LLItemCat.ITEM, ItemClassification.progression, 4),
    "Bombs": LLItem(ll_base_id + VAR_WBOMBS, LLItemCat.ITEM, ItemClassification.progression),
    "Shock Wand": LLItem(ll_base_id + VAR_WLIGHTNING, LLItemCat.ITEM, ItemClassification.progression),
    "Ice Spear": LLItem(ll_base_id + VAR_WICE, LLItemCat.ITEM, ItemClassification.progression),
    "Cactus": LLItem(ll_base_id + VAR_WCACTUS, LLItemCat.ITEM, ItemClassification.progression),
    "Boomerang": LLItem(ll_base_id + VAR_WBOOMERANG, LLItemCat.ITEM, ItemClassification.progression),
    "Whoopee": LLItem(ll_base_id + VAR_WWHOOPEE, LLItemCat.ITEM, ItemClassification.progression),
    "Hot Pants": LLItem(ll_base_id + VAR_WHOTPANTS, LLItemCat.ITEM, ItemClassification.progression),
    "Skull Key": LLItem(ll_base_id + VAR_SKULLKEY, LLItemCat.ITEM, ItemClassification.progression),
    "Bat Key": LLItem(ll_base_id + VAR_BATKEY, LLItemCat.ITEM, ItemClassification.progression),
    "Pumpkin Key": LLItem(ll_base_id + VAR_PUMPKINKEY, LLItemCat.ITEM, ItemClassification.progression),
    "Boots": LLItem(ll_base_id + VAR_BOOTS, LLItemCat.ITEM, ItemClassification.progression),
    "Stick": LLItem(ll_base_id + VAR_STICK, LLItemCat.ITEM, ItemClassification.progression),
    "Fertilizer": LLItem(ll_base_id + VAR_FERTILIZER, LLItemCat.ITEM, ItemClassification.progression),
    "Silver": LLItem(ll_base_id + VAR_SILVER, LLItemCat.ITEM, ItemClassification.progression),
    "Doom Daisy": LLItem(ll_base_id + VAR_DAISY, LLItemCat.ITEM, ItemClassification.progression),
    "Ghost Potion": LLItem(ll_base_id + VAR_POTION, LLItemCat.ITEM, ItemClassification.progression),
    "Vampire Bust": LLItem(ll_base_id + VAR_VAMPBUST, LLItemCat.ITEM, ItemClassification.progression, 8),
    "Cat": LLItem(ll_base_id + VAR_CAT, LLItemCat.ITEM, ItemClassification.progression),
    "Big Gem": LLItem(ll_base_id + VAR_GEM, LLItemCat.ITEM, ItemClassification.progression, 6),
    "100 Gems": LLItem(ll_base_id + VAR_ZOMBIEGEM, LLItemCat.ITEM, ItemClassification.filler),
    "Triple Fire Gem": LLItem(ll_base_id + VAR_TRIPLEFIRE, LLItemCat.ITEM, ItemClassification.useful, flags=LLFlags.PWR_BIG),
    "Happy Stick": LLItem(ll_base_id + VAR_TALISMAN, LLItemCat.ITEM, ItemClassification.progression),
    "Bat Statue": LLItem(ll_base_id + VAR_BATSTATUE, LLItemCat.ITEM, ItemClassification.progression, 4),
    "Lantern": LLItem(ll_base_id + VAR_LANTERN, LLItemCat.ITEM, ItemClassification.progression),
    "Reflect Gem": LLItem(ll_base_id + VAR_REFLECT, LLItemCat.ITEM, ItemClassification.useful, flags=LLFlags.PWR_BIG),
    "Silver Sling": LLItem(ll_base_id + VAR_SILVERSLING, LLItemCat.ITEM, ItemClassification.progression),
    "20/20 Vision": LLItem(ll_base_id + CH_LIGHT + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression),
    "Disco Mode": LLItem(ll_base_id + CH_DISCO + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler),
    "Terror Mode": LLItem(ll_base_id + CH_TERROR + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression),
    "Surprise Mode": LLItem(ll_base_id + CH_SURPRISE + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler),
    "Quick Mode": LLItem(ll_base_id + CH_QUICK + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful, flags=LLFlags.PWR),
    "Infinite Gems": LLItem(ll_base_id + CH_GEMS + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression, flags=LLFlags.LONG),
    "Sidekick": LLItem(ll_base_id + CH_SIDEKICK + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful),
    "Homing Shots": LLItem(ll_base_id + CH_HOMING + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful, flags=LLFlags.PWR),
    "Ultimate Firepower": LLItem(ll_base_id + CH_MAXPOWER + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler, flags=LLFlags.MULTISAVE),
    "Vintage Mode": LLItem(ll_base_id + CH_VINTAGE + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful),
    "Play As Bonkula": LLItem(ll_base_id + CH_BONKULA + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler, flags=LLFlags.MULTISAVE),
    "Play As Toad": LLItem(ll_base_id + CH_TOAD + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler, flags=LLFlags.MULTISAVE),
    "Crystal Ball": LLItem(ll_base_id + CH_CRYSTAL + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful),
    "Radar": LLItem(ll_base_id + CH_RADAR + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression),
    "Heavy Hitter": LLItem(ll_base_id + CH_HEAVYHIT + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful, flags=LLFlags.PWR_BIG),
    "Rapid Fire": LLItem(ll_base_id + CH_RAPIDFIRE + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler, flags=LLFlags.PWR),
    "Touch Of Death": LLItem(ll_base_id + CH_DEATH + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression, flags=LLFlags.PWR_MAX | LLFlags.OP),
    "All Access Pass": LLItem(ll_base_id + CH_ALLACCESS + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression, flags=LLFlags.MULTISAVE),
    "Play As Swampdog": LLItem(ll_base_id + CH_SWAMPDOG + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful, flags=LLFlags.MULTISAVE | LLFlags.LONG),
    "Hardcore Mode": LLItem(ll_base_id + CH_HARDCORE + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler, flags=LLFlags.MULTISAVE),
    "Save Anywhere": LLItem(ll_base_id + CH_SAVEANY + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful),
    "Guided Shots": LLItem(ll_base_id + CH_GUIDED + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful, flags=LLFlags.PWR),
    "Slo-Mo": LLItem(ll_base_id + CH_SLOMO + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful, flags=LLFlags.PWR_BIG),
    "Combo-Bombo": LLItem(ll_base_id + CH_CORPSE + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful, flags=LLFlags.PWR),
    "Frog-o-rama": LLItem(ll_base_id + CH_FROGWPN + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler),
    "Play As Witch": LLItem(ll_base_id + CH_WITCH + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful, flags=LLFlags.MULTISAVE | LLFlags.LONG),
    "Play As Werewolf": LLItem(ll_base_id + CH_WEREWOLF + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression, flags=LLFlags.MULTISAVE),
    "Enemy Overload": LLItem(ll_base_id + CH_RESPAWN + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful),
    "Kick The Cat!": LLItem(ll_base_id + CH_KICKCAT + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler),
    "Infinite Survival": LLItem(ll_base_id + CH_RNDSURVIVAL + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression),
    "Play As Summony": LLItem(ll_base_id + CH_SUMMON + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful, flags=LLFlags.MULTISAVE),
    "Play As Ninja Girl": LLItem(ll_base_id + CH_THIEF + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression, flags=LLFlags.MULTISAVE),
    "Molecular Dispersion": LLItem(ll_base_id + CH_WALLWALK + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression, flags=LLFlags.OP),
    "Guaranteed Survival": LLItem(ll_base_id + CH_SUPERSURV + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression, flags=LLFlags.PWR_MAX | LLFlags.OP),
    "Bend It Like Bouapha": LLItem(ll_base_id + CH_BEND + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful),
    "Stinky Farley": LLItem(ll_base_id + CH_STINKY + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful),
    "Ultra Weapons Are Go!": LLItem(ll_base_id + CH_ULTRAWEAPON + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.progression),
    "Thorns Aura": LLItem(ll_base_id + CH_THORNS + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.useful),
    "Monster Regeneration": LLItem(ll_base_id + CH_REGEN + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler),
    "Farley Free Zone": LLItem(ll_base_id + CH_NOFARLEY + AP_BADGEMOD, LLItemCat.CHEAT, ItemClassification.filler),
    "Bowling Access": LLItem(ll_base_id + MODE_BOWLING + AP_MODEMOD, LLItemCat.ACCESS, ItemClassification.progression),
    "Survival Access": LLItem(ll_base_id + MODE_SURVIVAL + AP_MODEMOD, LLItemCat.ACCESS, ItemClassification.progression),
    "Boss Bash Access": LLItem(ll_base_id + MODE_BOSSBASH + AP_MODEMOD, LLItemCat.ACCESS, ItemClassification.progression),
    "Loony Ball Access": LLItem(ll_base_id + MODE_LOONYBALL + AP_MODEMOD, LLItemCat.ACCESS, ItemClassification.progression),
    "Remix Access": LLItem(ll_base_id + MODE_REMIX + AP_MODEMOD, LLItemCat.ACCESS, ItemClassification.progression, flags=LLFlags.REMIX),
    "Bat Doll": LLItem(ll_base_id + VAR_BATDOLL, LLItemCat.DOLL, ItemClassification.progression),
    "Skeleton Doll": LLItem(ll_base_id + VAR_SKELDOLL, LLItemCat.DOLL, ItemClassification.progression),
    "Frog Doll": LLItem(ll_base_id + VAR_FROGDOLL, LLItemCat.DOLL, ItemClassification.progression),
    "Ghost Doll": LLItem(ll_base_id + VAR_GHOSTDOLL, LLItemCat.DOLL, ItemClassification.progression),
    "Mummy Doll": LLItem(ll_base_id + VAR_MUMMYDOLL, LLItemCat.DOLL, ItemClassification.progression),
    "Swampdog Doll": LLItem(ll_base_id + VAR_SWAMPDOLL, LLItemCat.DOLL, ItemClassification.progression),
    "Vampire Doll": LLItem(ll_base_id + VAR_VAMPDOLL, LLItemCat.DOLL, ItemClassification.progression),
    "Wolfman Doll": LLItem(ll_base_id + VAR_WOLFDOLL, LLItemCat.DOLL, ItemClassification.progression),
    "Torch": LLItem(ll_base_id + VAR_TORCH, LLItemCat.ITEM, ItemClassification.progression, flags=LLFlags.TORCH),
}
loonyland_region_table: dict[str, LLRegion] = {
    "Menu": LLRegion(False),
    "Halloween Hill": LLRegion(True, map_id=0),
    "Slurpy Swamp Mud": LLRegion(False, "Halloween Hill", map_id=0),
    "Slurpy Swamp Mud North Warp": LLRegion(False, "Halloween Hill", map_id=0),
    "Slurpy Swamp Mud East Warp": LLRegion(False, "Halloween Hill", map_id=0),
    "Zombiton": LLRegion(False, "Halloween Hill", map_id=0),
    "Rocky Cliffs": LLRegion(False, "Halloween Hill", map_id=0),
    "Vampy Land": LLRegion(False, "Halloween Hill", map_id=0),
    "A Cabin Trees": LLRegion(True, "A Cabin", map_id=1),
    "The Witch's Cabin": LLRegion(True, map_id=2),
    "The Witch's Cabin Back": LLRegion(False, "The Witch's Cabin", map_id=2),
    "Bonita's Cabin": LLRegion(True, map_id=3),
    "The Bog Pit": LLRegion(True, map_id=4),
    "Underground Tunnel": LLRegion(True, map_id=5),
    "Underground Tunnel Mud": LLRegion(False, "Underground Tunnel", map_id=5),
    "Underground Tunnel Zombie": LLRegion(False, "Underground Tunnel", map_id=5),
    "Swamp Gas Cavern": LLRegion(True, map_id=6),
    "Swamp Gas Cavern Back": LLRegion(False, "Swamp Gas Cavern", map_id=6),
    "A Tiny Cabin": LLRegion(True, map_id=7),
    "A Cabin Seer": LLRegion(True, map_id=8),
    "Benny's Cocktails": LLRegion(True, map_id=9),
    "Dusty Crypt": LLRegion(True, map_id=10),
    "Dusty Crypt Entrance": LLRegion(False, "Dusty Crypt", map_id=10),
    "Musty Crypt": LLRegion(True, map_id=11),
    "Musty Crypt Entrance": LLRegion(False, "Musty Crypt", map_id=11),
    "Rusty Crypt": LLRegion(True, map_id=12),
    "Rusty Crypt Entrance": LLRegion(False, "Rusty Crypt", map_id=12),
    "A Messy Cabin": LLRegion(True, map_id=13),
    "Under The Lake": LLRegion(True, map_id=14),
    "Under The Lake Entrance": LLRegion(False, "Under The Lake", map_id=14),
    "Under The Lake Exit": LLRegion(False, "Under The Lake", map_id=14),
    "Deeper Under The Lake": LLRegion(True, map_id=15),
    "Frankenjulie's Laboratory": LLRegion(True, map_id=16),
    "Haunted Tower": LLRegion(True, map_id=17),
    "Haunted Tower Entrance": LLRegion(False, map_id=17),
    "Haunted Tower Stairs Up": LLRegion(False, map_id=17),
    "Haunted Tower Stairs Down": LLRegion(False, map_id=17),
    "Haunted Tower Floor 2": LLRegion(True, map_id=18),
    "Haunted Tower Floor 2 Entrance": LLRegion(False, map_id=18),
    "Haunted Tower Floor 2 Exit": LLRegion(False, map_id=18),
    "Haunted Tower Floor 3 Entrance": LLRegion(False, map_id=19),
    "Haunted Tower Floor 3 Exit": LLRegion(False, map_id=19),
    "Haunted Tower Floor 3": LLRegion(True, map_id=19),
    "Haunted Tower Roof": LLRegion(True, map_id=20),
    "Haunted Basement": LLRegion(True, map_id=21),
    "Haunted Basement Entrance": LLRegion(False, "Haunted Basement", map_id=21),
    "Abandoned Mines": LLRegion(True, map_id=22),
    "Abandoned Mines Entrance": LLRegion(False, "Abandoned Mines", map_id=22),
    "The Shrine Of Bombulus": LLRegion(True, map_id=23),
    "A Gloomy Cavern": LLRegion(True, map_id=24),
    "A Gloomy Cavern Entrance": LLRegion(False, "A Gloomy Cavern", map_id=24),
    "Happy Stick Woods": LLRegion(True, map_id=25),
    "The Wolf Den": LLRegion(True, map_id=26),
    "The Wolf Den Entrance": LLRegion(False, "The Wolf Den", map_id=26),
    "The Wolf Den Exit": LLRegion(False, "The Wolf Den", map_id=26),
    "A Cabin Larry": LLRegion(True, map_id=27),
    "Upper Creepy Caverns": LLRegion(True, map_id=28),
    "Upper Creepy Caverns Left Warp": LLRegion(False, "Upper Creepy Caverns", map_id=28),
    "Upper Creepy Caverns Middle Warp": LLRegion(False, "Upper Creepy Caverns", map_id=28),
    "Upper Creepy Caverns Right Warp": LLRegion(False, "Upper Creepy Caverns", map_id=28),
    "Under The Ravine": LLRegion(True, map_id=29),
    "Creepy Caverns Left": LLRegion(False, "Creepy Caverns", map_id=30),
    "Creepy Caverns Left Bottom Warp": LLRegion(False, "Creepy Caverns", map_id=30),
    "Creepy Caverns Left Top Warp": LLRegion(False, "Creepy Caverns", map_id=30),
    "Creepy Caverns Middle": LLRegion(False, "Creepy Caverns", map_id=30),
    "Creepy Caverns Middle Top Warp": LLRegion(False, "Creepy Caverns", map_id=30),
    "Creepy Caverns Middle Right Warp": LLRegion(False, "Creepy Caverns", map_id=30),
    "Creepy Caverns Right": LLRegion(False, "Creepy Caverns", map_id=30),
    "Creepy Caverns Right Left Warp": LLRegion(False, "Creepy Caverns", map_id=30),
    "Creepy Caverns Right Bottom Warp": LLRegion(False, "Creepy Caverns", map_id=30),
    "Castle Vampy": LLRegion(True, map_id=31),
    "Castle Vampy NW": LLRegion(False, "Castle Vampy", map_id=31),
    "Castle Vampy NE": LLRegion(False, "Castle Vampy", map_id=31),
    "Castle Vampy SW": LLRegion(False, "Castle Vampy", map_id=31),
    "Castle Vampy SE": LLRegion(False, "Castle Vampy", map_id=31),
    "Castle Vampy Skull Jail": LLRegion(False, "Castle Vampy", map_id=31),
    "Castle Vampy II": LLRegion(True, map_id=32),
    "Castle Vampy II NW": LLRegion(False, "Castle Vampy II", map_id=32),
    "Castle Vampy II NE": LLRegion(False, "Castle Vampy II", map_id=32),
    "Castle Vampy II SW": LLRegion(False, "Castle Vampy II", map_id=32),
    "Castle Vampy II SE": LLRegion(False, "Castle Vampy II", map_id=32),
    "Castle Vampy II Bat Jail": LLRegion(False, "Castle Vampy II", map_id=32),
    "Cabin In The Woods": LLRegion(True, map_id=33),
    "Castle Vampy III": LLRegion(True, map_id=34),
    "Castle Vampy III NW": LLRegion(False, "Castle Vampy III", map_id=34),
    "Castle Vampy III NE": LLRegion(False, "Castle Vampy III", map_id=34),
    "Castle Vampy III SW": LLRegion(False, "Castle Vampy III", map_id=34),
    "Castle Vampy III SE": LLRegion(False, "Castle Vampy III", map_id=34),
    "Castle Vampy III Pumpkin Jail": LLRegion(False, "Castle Vampy III", map_id=34),
    "Castle Vampy IV": LLRegion(True, map_id=35),
    "Castle Vampy IV NW": LLRegion(False, "Castle Vampy IV", map_id=35),
    "Castle Vampy IV NE": LLRegion(False, "Castle Vampy IV", map_id=35),
    "Castle Vampy IV SW": LLRegion(False, "Castle Vampy IV", map_id=35),
    "Castle Vampy IV SE": LLRegion(False, "Castle Vampy IV", map_id=35),
    "A Cabin Collector": LLRegion(True, map_id=36),
    "Castle Vampy Roof NE": LLRegion(True, "Castle Vampy Roof", map_id=37),
    "Castle Vampy Roof SE": LLRegion(True, "Castle Vampy Roof", map_id=38),
    "Castle Vampy Roof SW": LLRegion(True, "Castle Vampy Roof", map_id=39),
    "Castle Vampy Roof NW": LLRegion(True, "Castle Vampy Roof", map_id=40),
    "The Evilizer": LLRegion(True, map_id=41),
    "The Heart Of Terror": LLRegion(True, map_id=42),
    "The Heart Of Terror Entrance": LLRegion(False, "The Heart Of Terror", map_id=42),
    "A Hidey-Hole": LLRegion(True, map_id=43),
    "Empty Rooftop": LLRegion(True, map_id=44),
    "Swampdog Lair": LLRegion(True, map_id=45),
    "Swampdog Lair Entrance": LLRegion(False, "Swampdog Lair", map_id=45),
    "Larry's Lair": LLRegion(True, map_id=46),
    "Bowling": LLRegion(False, flags=LLFlags.MODE),
    "Survival": LLRegion(False, flags=LLFlags.MODE),
    "Boss Bash": LLRegion(False, flags=LLFlags.MODE),
    "Loony Ball": LLRegion(False, flags=LLFlags.MODE),
    "Remix": LLRegion(False, flags=LLFlags.MODE | LLFlags.REMIX),
}
loonyland_location_table: dict[str, LLLocation] = {
    "Swamp: Mud Path": LLLocation(0, LLLocCat.PICKUP, 0, "Slurpy Swamp Mud"),
    "Swamp: Bog Beast": LLLocation(1, LLLocCat.PICKUP, 0, "Halloween Hill"),
    "Rocky Cliffs: Upper Ledge": LLLocation(2, LLLocCat.PICKUP, 0, "Rocky Cliffs"),
    "Swamp: Sapling Shrine": LLLocation(3, LLLocCat.PICKUP, 0, "Slurpy Swamp Mud"),
    "Terror Glade: South Trees": LLLocation(4, LLLocCat.PICKUP, 0, "Halloween Hill"),
    "Rocky Cliffs: Vine": LLLocation(5, LLLocCat.PICKUP, 0, "Rocky Cliffs"),
    "Rocky Cliffs: Grand Pharoh": LLLocation(6, LLLocCat.PICKUP, 0, "Rocky Cliffs"),
    "Rocky Cliffs: Rock Corner": LLLocation(7, LLLocCat.PICKUP, 0, "Rocky Cliffs"),
    "Swamp: Outside Luniton": LLLocation(8, LLLocCat.PICKUP, 0, "Halloween Hill"),
    "Swamp: East 1": LLLocation(9, LLLocCat.PICKUP, 0, "Halloween Hill"),
    "Swamp: Top Left dry": LLLocation(10, LLLocCat.PICKUP, 0, "Halloween Hill"),
    "Swamp: East 2": LLLocation(11, LLLocCat.PICKUP, 0, "Halloween Hill"),
    "Woods: Above Castle": LLLocation(12, LLLocCat.PICKUP, 0, "Halloween Hill"),
    "Rocky Cliffs: Entrance Ledge": LLLocation(13, LLLocCat.PICKUP, 0, "Rocky Cliffs"),
    "Rocky Cliffs: Peak": LLLocation(14, LLLocCat.PICKUP, 0, "Rocky Cliffs"),
    "Woods: SW of Cabin": LLLocation(15, LLLocCat.PICKUP, 0, "Halloween Hill"),
    "Witch's Cabin: Bedroom": LLLocation(16, LLLocCat.PICKUP, 2, "The Witch's Cabin"),
    "Witch's Cabin: Backroom": LLLocation(17, LLLocCat.PICKUP, 2, "The Witch's Cabin Back"),
    "Bonita's Cabin: Barrel Maze": LLLocation(18, LLLocCat.PICKUP, 3, "Bonita's Cabin"),
    "Bog Pit: Top Door": LLLocation(19, LLLocCat.PICKUP, 4, "The Bog Pit"),
    "Bog Pit: Posts Room": LLLocation(20, LLLocCat.PICKUP, 4, "The Bog Pit"),
    "Bog Pit: Drippy Window": LLLocation(21, LLLocCat.PICKUP, 4, "The Bog Pit"),
    "Bog Pit: Green room": LLLocation(22, LLLocCat.PICKUP, 4, "The Bog Pit"),
    "Bog Pit: Arena": LLLocation(23, LLLocCat.PICKUP, 4, "The Bog Pit"),
    "Bog Pit: Sw Switch": LLLocation(24, LLLocCat.PICKUP, 4, "The Bog Pit"),
    "Tunnel: Swampdog Pumpkin Door": LLLocation(25, LLLocCat.PICKUP, 5, "Underground Tunnel"),
    "Tunnel: Scratch Wall": LLLocation(26, LLLocCat.PICKUP, 5, "Underground Tunnel"),
    "Tunnel: Narrow Passage": LLLocation(27, LLLocCat.PICKUP, 5, "Underground Tunnel"),
    "Tunnel: Top Frogs": LLLocation(28, LLLocCat.PICKUP, 5, "Underground Tunnel"),
    "Tunnel: Torch Island": LLLocation(29, LLLocCat.PICKUP, 5, "Underground Tunnel Mud"),
    "Tunnel: Small Room": LLLocation(30, LLLocCat.PICKUP, 5, "Underground Tunnel"),
    "Swamp Gas: Scratch Wall": LLLocation(31, LLLocCat.PICKUP, 6, "Swamp Gas Cavern"),
    "Swamp Gas: Bat Door": LLLocation(32, LLLocCat.PICKUP, 6, "Swamp Gas Cavern"),
    "Swamp Gas: Stair room": LLLocation(33, LLLocCat.PICKUP, 6, "Swamp Gas Cavern Back"),
    "Swamp Gas: Rock Prison": LLLocation(34, LLLocCat.PICKUP, 6, "Swamp Gas Cavern"),
    "A Tiny Cabin": LLLocation(35, LLLocCat.PICKUP, 7, "A Tiny Cabin"),
    "Seer: Bedside": LLLocation(36, LLLocCat.PICKUP, 8, "A Cabin Seer"),
    "Dusty Crypt: Pumpkin Door": LLLocation(37, LLLocCat.PICKUP, 10, "Dusty Crypt"),
    "Dusty Crypt: Maze": LLLocation(38, LLLocCat.PICKUP, 10, "Dusty Crypt"),
    "Musty Crypt: Maze Room": LLLocation(39, LLLocCat.PICKUP, 11, "Musty Crypt"),
    "Rusty Crypt: Vine": LLLocation(40, LLLocCat.PICKUP, 12, "Rusty Crypt"),
    "Rusty Crypt: Boulders": LLLocation(41, LLLocCat.PICKUP, 12, "Rusty Crypt"),
    "A Messy Cabin": LLLocation(42, LLLocCat.PICKUP, 13, "A Messy Cabin"),
    "Under The Lake: Behind Lightning Rod": LLLocation(43, LLLocCat.PICKUP, 14, "Under The Lake"),
    "Under The Lake: Bat Door": LLLocation(44, LLLocCat.PICKUP, 14, "Under The Lake"),
    "Deeper Lake: Corner": LLLocation(45, LLLocCat.PICKUP, 15, "Deeper Under The Lake"),
    "Deeper Lake: Rhombus": LLLocation(46, LLLocCat.PICKUP, 15, "Deeper Under The Lake"),
    "Frankenjulie's Reward": LLLocation(47, LLLocCat.PICKUP, 16, "Frankenjulie's Laboratory"),
    "Tower: Barracks": LLLocation(48, LLLocCat.PICKUP, 17, "Haunted Tower"),
    "Tower F2: Skull Puzzle": LLLocation(49, LLLocCat.PICKUP, 18, "Haunted Tower Floor 2"),
    "PolterGuy's Reward": LLLocation(50, LLLocCat.PICKUP, 20, "Haunted Tower Roof"),
    "Tower Basement: DoorDoorDoorDoorDoorDoor": LLLocation(51, LLLocCat.PICKUP, 21, "Haunted Basement"),
    "Abandoned Mine: Shaft": LLLocation(52, LLLocCat.PICKUP, 22, "Abandoned Mines"),
    "Shrine Of Bombulus: Prize": LLLocation(53, LLLocCat.PICKUP, 23, "The Shrine Of Bombulus"),
    "Gloomy Cavern: Lockpick": LLLocation(54, LLLocCat.PICKUP, 24, "A Gloomy Cavern"),
    "Happy Stick: Hidden": LLLocation(55, LLLocCat.PICKUP, 25, "Happy Stick Woods"),
    "Happy Stick: Reward": LLLocation(56, LLLocCat.PICKUP, 25, "Happy Stick Woods"),
    "Wolf Den: Top Left": LLLocation(57, LLLocCat.PICKUP, 26, "The Wolf Den"),
    "Wolf Den: Pumpkin Door": LLLocation(58, LLLocCat.PICKUP, 26, "The Wolf Den"),
    "Wolf Den: Vine": LLLocation(59, LLLocCat.PICKUP, 26, "The Wolf Den"),
    "Upper Cavern: Three Gold Skeletons": LLLocation(60, LLLocCat.PICKUP, 28, "Upper Creepy Caverns"),
    "Under The Ravine: Left Vine": LLLocation(61, LLLocCat.PICKUP, 29, "Under The Ravine"),
    "Under The Ravine: Right Vine": LLLocation(62, LLLocCat.PICKUP, 29, "Under The Ravine"),
    "Creepy Caverns M: Pharaoh Bat Door": LLLocation(63, LLLocCat.PICKUP, 30, "Creepy Caverns Middle"),
    "Creepy Caverns R: Top Pharaohs": LLLocation(64, LLLocCat.PICKUP, 30, "Creepy Caverns Right"),
    "Creepy Caverns M: Gargoyles": LLLocation(65, LLLocCat.PICKUP, 30, "Creepy Caverns Middle"),
    "Castle Vampy: Top Room": LLLocation(66, LLLocCat.PICKUP, 31, "Castle Vampy"),
    "Castle Vampy: Maze": LLLocation(67, LLLocCat.PICKUP, 31, "Castle Vampy"),
    "Castle Vampy: Gauntlet": LLLocation(68, LLLocCat.PICKUP, 31, "Castle Vampy"),
    "Castle Vampy: Bat Closet": LLLocation(69, LLLocCat.PICKUP, 31, "Castle Vampy"),
    "Castle Vampy II: Candle Room": LLLocation(70, LLLocCat.PICKUP, 32, "Castle Vampy II"),
    "Castle Vampy II: Bloodsucker Room": LLLocation(71, LLLocCat.PICKUP, 32, "Castle Vampy II"),
    "Castle Vampy II: Vampire Lord": LLLocation(72, LLLocCat.PICKUP, 32, "Castle Vampy II"),
    "Castle Vampy II: Bat Room": LLLocation(73, LLLocCat.PICKUP, 32, "Castle Vampy II"),
    "Cabin in the Woods: Gold Skull": LLLocation(74, LLLocCat.PICKUP, 33, "Cabin In The Woods"),
    "Castle Vampy III: Center": LLLocation(75, LLLocCat.PICKUP, 34, "Castle Vampy III"),
    "Castle Vampy III: Behind the Pews": LLLocation(76, LLLocCat.PICKUP, 34, "Castle Vampy III"),
    "Castle Vampy III: AMBUSH!": LLLocation(77, LLLocCat.PICKUP, 34, "Castle Vampy III"),
    "Castle Vampy III: Halloween": LLLocation(78, LLLocCat.PICKUP, 34, "Castle Vampy III"),
    "Castle Vampy III: Bat room": LLLocation(79, LLLocCat.PICKUP, 34, "Castle Vampy III"),
    "Castle Vampy IV: Right Path": LLLocation(80, LLLocCat.PICKUP, 35, "Castle Vampy IV"),
    "Castle Vampy IV: Left Path": LLLocation(81, LLLocCat.PICKUP, 35, "Castle Vampy IV"),
    "Castle Vampy IV: Ballroom Right": LLLocation(82, LLLocCat.PICKUP, 35, "Castle Vampy IV"),
    "Castle Vampy IV: Right Secret Wall": LLLocation(83, LLLocCat.PICKUP, 35, "Castle Vampy IV"),
    "Castle Vampy IV: Ballroom Left": LLLocation(84, LLLocCat.PICKUP, 35, "Castle Vampy IV"),
    "Roof NW: Gutsy the Elder": LLLocation(85, LLLocCat.PICKUP, 37, "Castle Vampy Roof NW"),
    "Roof NE: Stoney the Elder": LLLocation(86, LLLocCat.PICKUP, 38, "Castle Vampy Roof NE"),
    "Roof SW: Drippy the Elder": LLLocation(87, LLLocCat.PICKUP, 39, "Castle Vampy Roof SW"),
    "Roof SE: Toasty the Elder": LLLocation(88, LLLocCat.PICKUP, 40, "Castle Vampy Roof SE"),
    "Bonkula Item": LLLocation(89, LLLocCat.PICKUP, 42, "The Heart Of Terror"),
    "Hidey-Hole: Bat Door": LLLocation(90, LLLocCat.PICKUP, 43, "A Hidey-Hole"),
    "Hidey-Hole: Pebbles": LLLocation(91, LLLocCat.PICKUP, 43, "A Hidey-Hole"),
    "Swampdog Lair: Entrance": LLLocation(92, LLLocCat.PICKUP, 45, "Swampdog Lair"),
    "Swampdog Lair: End": LLLocation(93, LLLocCat.PICKUP, 45, "Swampdog Lair"),
    "Q: Save Halloween Hill": LLLocation(94, LLLocCat.QUEST, 0, "The Evilizer"),
    "Q: Tree Trimming": LLLocation(95, LLLocCat.QUEST, 1, "Halloween Hill"),
    "Q: Scaredy Cat": LLLocation(96, LLLocCat.QUEST, 2, "Halloween Hill"),
    "Q: Sticky Shoes": LLLocation(97, LLLocCat.QUEST, 3, "Halloween Hill"),
    "Q: Mushroom Hunt": LLLocation(98, LLLocCat.QUEST, 4, "The Witch's Cabin"),
    "Q: Picking Daisies": LLLocation(99, LLLocCat.QUEST, 5, "Menu"),
    "Q: Curse The Darkness": LLLocation(100, LLLocCat.QUEST, 6, "Swamp Gas Cavern"),
    "Q: Zombie Stomp": LLLocation(101, LLLocCat.QUEST, 7, "Zombiton"),
    "Q: Smashing Pumpkins": LLLocation(102, LLLocCat.QUEST, 8, "Halloween Hill"),
    "Q: Mystery Lake": LLLocation(103, LLLocCat.QUEST, 9, "Halloween Hill"),
    "Q: Beneath The Lake": LLLocation(104, LLLocCat.QUEST, 10, "Frankenjulie's Laboratory"),
    "Q: Happy Stick?!?": LLLocation(105, LLLocCat.QUEST, 11, "Happy Stick Woods"),
    "Q: A True Hero": LLLocation(106, LLLocCat.QUEST, 12, "Under The Ravine"),
    "Q: Silver Bullet": LLLocation(107, LLLocCat.QUEST, 13, "Zombiton"),
    "Q: Hairy Larry": LLLocation(108, LLLocCat.QUEST, 14, "The Wolf Den"),
    "Q: Ghostbusting": LLLocation(109, LLLocCat.QUEST, 15, "The Witch's Cabin"),
    "Q: The Haunted Tower": LLLocation(110, LLLocCat.QUEST, 16, "Haunted Tower Roof"),
    "Q: The Last Gate": LLLocation(111, LLLocCat.QUEST, 17, "Castle Vampy IV"),
    "Q: The Rescue": LLLocation(112, LLLocCat.QUEST, 18, "A Gloomy Cavern"),
    "Q: The Collection": LLLocation(113, LLLocCat.QUEST, 19, "A Cabin Collector", flags=LLFlags.DOLL),
    "Evil Smashin'": LLLocation(114, LLLocCat.BADGE, 0, "The Evilizer", flags=LLFlags.POSTGAME, base_item="Quick Mode"),
    "Bowlin'": LLLocation(115, LLLocCat.BADGE, 1, "Bowling", base_item="Disco Mode"),
    "Vandalizin'": LLLocation(116, LLLocCat.BADGE, 2, "Zombiton", base_item="Vintage Mode"),
    "Greed": LLLocation(117, LLLocCat.BADGE, 3, "Menu", flags=LLFlags.LONG, base_item="Infinite Gems"),
    "Monster Slayin'": LLLocation(118, LLLocCat.BADGE, 4, "Menu", flags=LLFlags.LONG, base_item="Sidekick"),
    "Monster Poundin'": LLLocation(119, LLLocCat.BADGE, 5, "Menu", base_item="Hardcore Mode"),
    "Ghostbustin'": LLLocation(120, LLLocCat.BADGE, 6, "Haunted Tower Roof", base_item="Homing Shots"),
    "Lookin'": LLLocation(121, LLLocCat.BADGE, 7, "The Witch's Cabin", base_item="20/20 Vision"),
    "Ultimate Victory": LLLocation(122, LLLocCat.BADGE, 8, "The Evilizer", flags=LLFlags.POSTGAME, base_item="Ultimate Firepower"),
    "Kickin'": LLLocation(123, LLLocCat.BADGE, 9, "Loony Ball", base_item="Surprise Mode"),
    "Boss Bashin'": LLLocation(124, LLLocCat.BADGE, 10, "Boss Bash", base_item="Combo-Bombo"),
    "Vampire Slayin'": LLLocation(125, LLLocCat.BADGE, 11, "The Heart Of Terror", base_item="Play As Bonkula"),
    "Sneakin'": LLLocation(126, LLLocCat.BADGE, 12, "Haunted Tower", base_item="Play As Swampdog"),
    "Witch Hunt": LLLocation(127, LLLocCat.BADGE, 13, "Happy Stick Woods", base_item="Play As Witch"),
    "Animal Control": LLLocation(128, LLLocCat.BADGE, 14, "The Wolf Den", base_item="Play As Werewolf"),
    "Annoyance": LLLocation(129, LLLocCat.BADGE, 15, "The Witch's Cabin", base_item="Play As Toad"),
    "Civic Duty": LLLocation(130, LLLocCat.BADGE, 16, "A Gloomy Cavern", base_item="Enemy Overload"),
    "Winnin'": LLLocation(131, LLLocCat.BADGE, 17, "The Evilizer", flags=LLFlags.POSTGAME, base_item="Crystal Ball"),
    "Combo Plate": LLLocation(132, LLLocCat.BADGE, 18, "Menu", base_item="Radar"),
    "Cleanin' Up": LLLocation(133, LLLocCat.BADGE, 19, "Rocky Cliffs", base_item="Heavy Hitter"),
    "Findin'": LLLocation(134, LLLocCat.BADGE, 20, "The Wolf Den", base_item="Rapid Fire"),
    "Extreme Survivin'": LLLocation(135, LLLocCat.BADGE, 21, "Survival", flags=LLFlags.LONG_VANILLA_BADGES | LLFlags.VANILLA_POSTGAME, base_item="Touch Of Death"),
    "Huntin'": LLLocation(136, LLLocCat.BADGE, 22, "Halloween Hill", base_item="All Access Pass"),
    "Advanced Winnin'": LLLocation(137, LLLocCat.BADGE, 23, "Menu", flags=LLFlags.LONG | LLFlags.POSTGAME, base_item="Terror Mode"),
    "Survivin'": LLLocation(138, LLLocCat.BADGE, 24, "Survival", base_item="Save Anywhere"),
    "Puppy Poundin'": LLLocation(139, LLLocCat.BADGE, 25, "Larry's Lair", base_item="Guided Shots"),
    "Mad Skeelz": LLLocation(140, LLLocCat.BADGE, 26, "The Evilizer", flags=LLFlags.LONG_VANILLA_BADGES | LLFlags.MULTISAVE | LLFlags.POSTGAME, base_item="Kick The Cat!"),
    "Frankenfryin'": LLLocation(141, LLLocCat.BADGE, 27, "Frankenjulie's Laboratory", base_item="Slo-Mo"),
    "Combo Magic": LLLocation(142, LLLocCat.BADGE, 28, "Survival", base_item="Infinite Survival"),
    "Hedge Clippin'": LLLocation(143, LLLocCat.BADGE, 29, "Slurpy Swamp Mud", base_item="Frog-o-rama"),
    "R-R-R-Remix!": LLLocation(144, LLLocCat.BADGE, 30, "Menu", flags=LLFlags.REMIX | LLFlags.LONG | LLFlags.POSTGAME, base_item="Play As Summony"),
    "Witchcraft": LLLocation(145, LLLocCat.BADGE, 31, "Menu", flags=LLFlags.LONG | LLFlags.MULTISAVE, base_item="Play As Ninja Girl"),
    "Ninjitsu": LLLocation(146, LLLocCat.BADGE, 32, "Menu", flags=LLFlags.LONG_VANILLA_BADGES | LLFlags.MULTISAVE, base_item="Molecular Dispersion"),
    "Stayin' Alive": LLLocation(147, LLLocCat.BADGE, 33, "Survival", flags=LLFlags.LONG, base_item="Guaranteed Survival"),
    "Hooliganin'": LLLocation(148, LLLocCat.BADGE, 34, "Loony Ball", base_item="Bend It Like Bouapha"),
    "Swampdoggin'": LLLocation(149, LLLocCat.BADGE, 35, "Menu", flags=LLFlags.LONG | LLFlags.MULTISAVE, base_item="Stinky Farley"),
    "Scorin'": LLLocation(150, LLLocCat.BADGE, 36, "The Evilizer", flags=LLFlags.LONG, base_item="Ultra Weapons Are Go!"),
    "Brawlin'": LLLocation(151, LLLocCat.BADGE, 37, "Benny's Cocktails", flags=LLFlags.LONG_VANILLA_BADGES | LLFlags.OP | LLFlags.VANILLA_POSTGAME, base_item="Thorns Aura"),
    "Minin' For Treasure": LLLocation(152, LLLocCat.BADGE, 38, "Menu", flags=LLFlags.REMIX, base_item="Monster Regeneration"),
    "Digitally Masterin'": LLLocation(153, LLLocCat.BADGE, 39, "Menu", flags=LLFlags.LONG | LLFlags.REMIX | LLFlags.MULTISAVE | LLFlags.POSTGAME | LLFlags.LONG_VANILLA_BADGES, base_item="Farley Free Zone"),
    "Tree Trimming Reward": LLLocation(154, LLLocCat.REWARD, VAR_TREEREWARD, "A Cabin Trees"),
    "Larry's Wife Reward": LLLocation(155, LLLocCat.REWARD, VAR_LARRYREWARD, "A Cabin Larry"),
    "Farmer Reward": LLLocation(156, LLLocCat.REWARD, VAR_CROPSREWARD, "Halloween Hill"),
    "Witch Mushroom Reward": LLLocation(157, LLLocCat.REWARD, VAR_WITCHREWARD, "The Witch's Cabin"),
    "Mayor Reward": LLLocation(158, LLLocCat.REWARD, VAR_ZOMBIEREWARD, "Zombiton"),
    "Bat Drop": LLLocation(159, LLLocCat.DOLL, 0, "Menu", base_item="Bat Doll"),
    "Skeleton Drop": LLLocation(160, LLLocCat.DOLL, 1, "Menu", base_item="Skeleton Doll"),
    "Frog Drop": LLLocation(161, LLLocCat.DOLL, 2, "Menu", base_item="Frog Doll"),
    "Ghost Drop": LLLocation(162, LLLocCat.DOLL, 3, "Menu", base_item="Ghost Doll"),
    "Mummy Drop": LLLocation(163, LLLocCat.DOLL, 4, "Menu", base_item="Mummy Doll"),
    "Swampdog Drop": LLLocation(164, LLLocCat.DOLL, 5, "Menu", base_item="Swampdog Doll"),
    "Vampire Drop": LLLocation(165, LLLocCat.DOLL, 6, "Menu", base_item="Vampire Doll"),
    "Wolf Drop": LLLocation(166, LLLocCat.DOLL, 7, "Menu", base_item="Wolfman Doll"),
}


def set_rules(world):
    player = world.player
    access_rules: dict[str, CollectionRule] = {
        "Rocky Cliffs: Vine": lambda state: state.has("Fertilizer", player),
        "Rocky Cliffs: Rock Corner": lambda state: have_bombs(state, player),
        "Witch's Cabin: Bedroom": lambda state: have_light_source(state, player),
        "Bog Pit: Top Door": lambda state: state.has("Skull Key", player),
        "Tunnel: Swampdog Pumpkin Door": lambda state: state.has("Pumpkin Key", player),
        "Tunnel: Scratch Wall": lambda state: have_special_weapon_bullet(state, player),
        "Swamp Gas: Scratch Wall": lambda state: have_special_weapon_bullet(state, player),
        "Swamp Gas: Bat Door": lambda state: state.has("Bat Key", player),
        "Swamp Gas: Rock Prison": lambda state: state.has("Bombs", player) or state.has("Play As Werewolf", player),
        "Dusty Crypt: Pumpkin Door": lambda state: state.has("Pumpkin Key", player),
        "Musty Crypt: Maze Room": lambda state: have_special_weapon_bullet(state, player),
        "Rusty Crypt: Vine": lambda state: state.has("Fertilizer", player),
        "Under The Lake: Bat Door": lambda state: state.has("Bat Key", player),
        "Frankenjulie's Reward": lambda state: power_level(state, player, 10),
        "Tower: Barracks": lambda state: state.has("Bat Key", player),
        "PolterGuy's Reward": lambda state: power_level(state, player, 10),
        "Tower Basement: DoorDoorDoorDoorDoorDoor": lambda state: state.has("Bat Key", player) and state.has("Skull Key", player) and state.has("Pumpkin Key", player),
        "Happy Stick: Reward": lambda state: power_level(state, player, 40),
        "Wolf Den: Pumpkin Door": lambda state: state.has("Pumpkin Key", player),
        "Wolf Den: Vine": lambda state: state.has("Fertilizer", player),
        "Under The Ravine: Left Vine": lambda state: state.has("Fertilizer", player),
        "Under The Ravine: Right Vine": lambda state: state.has("Fertilizer", player) and state.has("Skull Key", player),
        "Creepy Caverns M: Pharaoh Bat Door": lambda state: state.has("Bat Key", player),
        "Castle Vampy IV: Ballroom Right": lambda state: state.has("Ghost Potion", player) and can_kill_werewolves(state, player),
        "Castle Vampy IV: Ballroom Left": lambda state: state.has("Ghost Potion", player) and can_kill_werewolves(state, player),
        "Roof NW: Gutsy the Elder": lambda state: have_special_weapon_damage(state, player) and power_level(state, player, 20),
        "Roof NE: Stoney the Elder": lambda state: power_level(state, player, 20),
        "Roof SW: Drippy the Elder": lambda state: power_level(state, player, 20),
        "Roof SE: Toasty the Elder": lambda state: power_level(state, player, 20),
        "Hidey-Hole: Bat Door": lambda state: state.has("Bat Key", player),
        "Hidey-Hole: Pebbles": lambda state: power_level(state, player, 5),
        "Swampdog Lair: End": lambda state: have_light_source(state, player) and state.has("Fertilizer", player),
        "Q: Save Halloween Hill": lambda state: power_level(state, player, 30),
        "Q: Scaredy Cat": lambda state: state.has("Cat", player),
        "Q: Mushroom Hunt": lambda state: state.has("Mushroom", player, 10),
        "Q: Picking Daisies": lambda state: state.has("Doom Daisy", player),
        "Q: Curse The Darkness": lambda state: state.has("Stick", player),
        "Q: Zombie Stomp": lambda state: can_cleanse_crypts(state, player),
        "Q: Smashing Pumpkins": lambda state: can_cleanse_crypts(state, player),
        "Q: Mystery Lake": lambda state: state.has("Orb", player, 4),
        "Q: Beneath The Lake": lambda state: power_level(state, player, 10),
        "Q: Happy Stick?!?": lambda state: power_level(state, player, 40),
        "Q: A True Hero": lambda state: state.has("Fertilizer", player) and have_bombs(state, player),
        "Q: Silver Bullet": lambda state: can_cleanse_crypts(state, player) and state.has("Silver", player),
        "Q: Hairy Larry": lambda state: state.can_reach_region("Larry's Lair", player) and power_level(state, player, 10),
        "Q: Ghostbusting": lambda state: state.has("Doom Daisy", player) and state.has("Mushroom", player, 10),
        "Q: The Haunted Tower": lambda state: power_level(state, player, 10),
        "Q: The Last Gate": lambda state: state.has("Vampire Bust", player, 8),
        "Q: The Collection": lambda state: can_do_collection(state, player),
        "Greed": lambda state: state.can_reach_region("Castle Vampy IV", player) and power_level(state, player, 10),
        "Monster Slayin'": lambda state: state.can_reach_region("Castle Vampy IV", player) and power_level(state, player, 10),
        "Monster Poundin'": lambda state: state.can_reach_region("Castle Vampy IV", player) and power_level(state, player, 10),
        "Animal Control": lambda state: can_kill_werewolves(state, player),
        "Cleanin' Up": lambda state: have_many_bombs(state, player),
        "Extreme Survivin'": lambda state: state.has("Terror Mode", player) and power_level(state, player, 30),
        "Huntin'": lambda state: state.can_reach_region("Rocky Cliffs", player) and state.can_reach_region("Zombiton", player) and state.can_reach_region("Slurpy Swamp Mud", player) and can_kill_werewolves(state, player),
        "Advanced Winnin'": lambda state: hundred_percent(state, player),
        "Mad Skeelz": lambda state: state.has("Terror Mode", player) and power_level(state, player, 30),
        "Hedge Clippin'": lambda state: state.can_reach_region("Vampy Land", player),
        "R-R-R-Remix!": lambda state: hundred_percent(state, player) and state.has("Remix Access", player),
        "Witchcraft": lambda state: state.has("Play As Witch", player) and have_all_weapons(state, player) and state.can_reach_region("Castle Vampy IV", player),
        "Ninjitsu": lambda state: state.has("Play As Ninja Girl", player) and have_all_weapons(state, player) and state.has("Infinite Gems", player),
        "Stayin' Alive": lambda state: state.has("Infinite Survival", player),
        "Swampdoggin'": lambda state: state.has("Play As Swampdog", player) and state.can_reach_region("Castle Vampy IV", player),
        "Scorin'": lambda state: state.has("Boss Bash Access", player) and power_level(state, player, 30),
        "Brawlin'": lambda state: state.has("Touch Of Death", player),
        "Minin' For Treasure": lambda state: state.can_reach_region("Abandoned Mines", player) and state.has("Remix Access", player),
        "Digitally Masterin'": lambda state: have_39_badges(state, player),
        "Larry's Wife Reward": lambda state: state.can_reach_region("Larry's Lair", player) and can_cleanse_crypts(state, player),
        "Farmer Reward": lambda state: can_cleanse_crypts(state, player),
        "Witch Mushroom Reward": lambda state: state.has("Mushroom", player, 10),
        "Mayor Reward": lambda state: can_cleanse_crypts(state, player),
        "Bat Drop": lambda state: can_reach_bats(state, player),
        "Skeleton Drop": lambda state: can_reach_skeleton(state, player),
        "Frog Drop": lambda state: can_reach_frog(state, player),
        "Ghost Drop": lambda state: can_reach_ghost(state, player) and state.has("Ghost Potion", player),
        "Mummy Drop": lambda state: can_reach_mummy(state, player),
        "Swampdog Drop": lambda state: can_reach_swampdog(state, player),
        "Vampire Drop": lambda state: can_reach_vampire(state, player),
        "Wolf Drop": lambda state: can_reach_wolves(state, player) and can_kill_werewolves(state, player),
    }
    for loc in world.multiworld.get_locations(world.player):
        if loc.name in access_rules:
            add_rule(loc, access_rules[loc.name])


def setup_entrances(world):
    player = world.player
    return [
        LLEntrance("Menu New Game", "Menu", "Halloween Hill"),
        LLEntrance("Menu Bowling", "Menu", "Bowling", lambda state: state.has("Bowling Access", player), flags=LLFlags.MODE),
        LLEntrance("Menu Survival", "Menu", "Survival", lambda state: state.has("Survival Access", player), flags=LLFlags.MODE),
        LLEntrance("Menu Boss Bash", "Menu", "Boss Bash", lambda state: state.has("Boss Bash Access", player), flags=LLFlags.MODE),
        LLEntrance("Menu Loony Ball", "Menu", "Loony Ball", lambda state: state.has("Loony Ball Access", player), flags=LLFlags.MODE),
        LLEntrance("Menu Remix", "Menu", "Remix", lambda state: state.has("Remix Access", player), flags=LLFlags.MODE | LLFlags.REMIX),
        LLEntrance("Luniton SW House", "Halloween Hill", "Tree Guy's Cabin Door", id=1),
        LLEntrance("Luniton NE House", "Halloween Hill", "Witch's Cabin Door", id=2),
        LLEntrance("Luniton SE House", "Halloween Hill", "Bonita's Cabin Door", id=3),
        LLEntrance("Slurpy Swamp Hay Stairs", "Halloween Hill", "Underground Tunnel North Stairs", id=4),
        LLEntrance("Slurpy Swamp Dirt Stairs", "Halloween Hill", "The Bog Pit Door", id=5),
        LLEntrance("", "Slurpy Swamp Mud", "Slurpy Swamp Mud East Warp"),
        LLEntrance("Slurpy Swamp Lillypad Stairs", "Slurpy Swamp Mud East Warp", "Swamp Gas Cavern East Stairs", id=6),
        LLEntrance("", "Slurpy Swamp Mud", "Slurpy Swamp Mud North Warp"),
        LLEntrance("Slurpy Swamp Mud Stairs", "Slurpy Swamp Mud North Warp", "Swamp Gas Cavern North Stairs", id=7),
        LLEntrance("Luniton NW House", "Halloween Hill", "Tiny Cabin Door", lambda state: state.has("Skull Key", player), id=8),
        LLEntrance("Luniton NE House Backdoor", "Halloween Hill", "Witch's Cabin Backdoor", id=9),
        LLEntrance("Zombiton Paired House East", "Zombiton", "Seer Cabin Door", id=10),
        LLEntrance("Zombiton Big House", "Zombiton", "Bar West Door", id=11),
        LLEntrance("Graveyard West Crypt", "Halloween Hill", "Dusty Crypt Door", id=12),
        LLEntrance("Zombiton Crypt", "Zombiton", "Musty Crypt Door", id=13),
        LLEntrance("Zombiton Paired House West", "Zombiton", "Messy Cabin Door", id=14),
        LLEntrance("Graveyard East Crypt", "Halloween Hill", "Rusty Crypt Door", id=15),
        LLEntrance("Pointless Plains Lake", "Halloween Hill", "Under The Lake South Door", lambda state: state.has("Orb", player, 4), id=16),
        LLEntrance("Wicked Woods Castle", "Halloween Hill", "Haunted Tower South Door", id=17),
        LLEntrance("Rocky Cliffs West Cave", "Rocky Cliffs", "Abadoned Mines Exit", id=18),
        LLEntrance("Rocky Cliffs Peak Cave", "Rocky Cliffs", "Bombulus Exit", id=19),
        LLEntrance("Rocky Cliffs South Cave", "Rocky Cliffs", "Gloomy Cavern Exit", lambda state: have_light_source(state, player), id=20),
        LLEntrance("Wicked Woods Happy Stick", "Halloween Hill", "Happy Stick Woods Exit", lambda state: state.has("Happy Stick", player), id=21),
        LLEntrance("Zombiton SE House", "Zombiton", "Larry's Cabin Door", id=22),
        LLEntrance("Pointless Plains Cave", "Halloween Hill", "Wolf Den South Exit", id=23),
        LLEntrance("Rocky Cliffs Rock Blocked Cave", "Rocky Cliffs", "Upper Creepy Caverns West Exit", lambda state: state.has("Bombs", player), id=24),
        LLEntrance("Vampy Land Cave", "Vampy Land", "Creepy Caverns Right Bottom Exit", id=25),
        LLEntrance("Vampy Land Castle", "Vampy Land", "Castle Vampy South Exit", id=26),
        LLEntrance("Wicked Woods Cabin", "Halloween Hill", "Cabin In The Woods Exit", id=27),
        LLEntrance("Luniton Center House", "Halloween Hill", "Collector's Cabin Exit", id=28),
        LLEntrance("Wicked Woods Tree Cluster", "Halloween Hill", "A Hidey-Hole Exit", id=29),
        LLEntrance("Rocky Cliffs SE Cave", "Rocky Cliffs", "Creepy Caverns Left Bottom Exit", lambda state: have_light_source(state, player), id=30),
        LLEntrance("Slurpy Swamp SE Cave", "Halloween Hill", "Swampdog Lair Exit", id=31),
        LLEntrance("Tree Guy's Cabin Door", "A Cabin Trees", "Luniton SW House", id=32),
        LLEntrance("Witch's Cabin Door", "The Witch's Cabin", "Luniton NE House", id=33),
        LLEntrance("Witch's Cabin Backdoor", "The Witch's Cabin Back", "Luniton NE House Backdoor", id=34),
        LLEntrance("Bonita's Cabin Door", "Bonita's Cabin", "Luniton SE House", id=35),
        LLEntrance("The Bog Pit Door", "The Bog Pit", "Slurpy Swamp Dirt Stairs", id=36),
        LLEntrance("Underground Tunnel North Stairs", "Underground Tunnel", "Slurpy Swamp Hay Stairs", id=37),
        LLEntrance("Underground Tunnel South Stairs", "Underground Tunnel Zombie", "Bar East Stairs", id=38),
        LLEntrance("Swamp Gas Cavern East Stairs", "Swamp Gas Cavern", "Slurpy Swamp Lillypad Stairs", id=39),
        LLEntrance("Swamp Gas Cavern North Stairs", "Swamp Gas Cavern Back", "Slurpy Swamp Mud Stairs", id=40),
        LLEntrance("Tiny Cabin Door", "A Tiny Cabin", "Luniton NW House", id=41),
        LLEntrance("Seer Cabin Door", "A Cabin Seer", "Zombiton Paired House East", id=42),
        LLEntrance("Bar West Door", "Benny's Cocktails", "Zombiton Big House", id=43),
        LLEntrance("Bar East Stairs", "Benny's Cocktails", "Underground Tunnel South Stairs", id=44),
        LLEntrance("", "Dusty Crypt Entrance", "Dusty Crypt", lambda state: have_light_source(state, player)),
        LLEntrance("Dusty Crypt Door", "Dusty Crypt Entrance", "Graveyard West Crypt", id=45),
        LLEntrance("", "Dusty Crypt", "Dusty Crypt Entrance"),
        LLEntrance("", "Musty Crypt Entrance", "Musty Crypt", lambda state: have_light_source(state, player)),
        LLEntrance("Musty Crypt Door", "Musty Crypt Entrance", "Zombiton Crypt", id=46),
        LLEntrance("", "Musty Crypt", "Musty Crypt Entrance"),
        LLEntrance("", "Rusty Crypt Entrance", "Rusty Crypt", lambda state: have_light_source(state, player)),
        LLEntrance("Rusty Crypt Door", "Rusty Crypt Entrance", "Graveyard East Crypt", id=47),
        LLEntrance("", "Rusty Crypt", "Rusty Crypt Entrance"),
        LLEntrance("Messy Cabin Door", "A Messy Cabin", "Zombiton Paired House West", id=48),
        LLEntrance("", "Under The Lake Entrance", "Under The Lake", lambda state: have_light_source(state, player)),
        LLEntrance("Under The Lake South Door", "Under The Lake Entrance", "Pointless Plains Lake", id=49),
        LLEntrance("", "Under The Lake", "Under The Lake Entrance"),
        LLEntrance("", "Under The Lake", "Under The Lake Exit"),
        LLEntrance("Under The Lake North Door", "Under The Lake Exit", "Deeper Under The Lake South Door", id=50),
        LLEntrance("", "Under The Lake Exit", "Under The Lake"),
        LLEntrance("Deeper Under The Lake South Door", "Deeper Under The Lake", "Under The Lake North Door", id=51),
        LLEntrance("Deeper Under The Lake Central Door", "Deeper Under The Lake", "Frankenjulie's Laboratory South Door", id=52),
        LLEntrance("Frankenjulie's Laboratory South Door", "Frankenjulie's Laboratory", "Deeper Under The Lake Central Door", id=53),
        LLEntrance("Frankenjulie's Laboratory North Exit", "Frankenjulie's Laboratory", "Halloween Hill"),
        LLEntrance("Haunted Tower South Door", "Haunted Tower Entrance", "Wicked Woods Castle", id=54),
        LLEntrance("", "Haunted Tower Entrance", "Haunted Tower"),
        LLEntrance("", "Haunted Tower", "Haunted Tower Stairs Up"),
        LLEntrance("", "Haunted Tower", "Haunted Tower Stairs Down", lambda state: state.has("Bat Key", player) and state.has("Pumpkin Key", player) and state.has("Skull Key", player)),
        LLEntrance("Haunted Tower Stairs Up", "Haunted Tower Stairs Up", "Haunted Tower Floor 2 Stairs Down", id=55),
        LLEntrance("", "Haunted Tower Stairs Up", "Haunted Tower"),
        LLEntrance("", "Haunted Tower Stairs Down", "Haunted Tower", lambda state: state.has("Bat Key", player) and state.has("Pumpkin Key", player) and state.has("Skull Key", player)),
        LLEntrance("Haunted Tower Stairs Down", "Haunted Tower Stairs Down", "Haunted Tower Basement Stairs Up", lambda state: have_light_source(state, player), id=56),
        LLEntrance("Haunted Tower Floor 2 Stairs Down", "Haunted Tower Floor 2 Entrance", "Haunted Tower Stairs Up", id=57),
        LLEntrance("", "Haunted Tower Floor 2 Entrance", "Haunted Tower Floor 2", lambda state: state.has("Ghost Potion", player)),
        LLEntrance("", "Haunted Tower Floor 2", "Haunted Tower Floor 2 Entrance"),
        LLEntrance("", "Haunted Tower Floor 2", "Haunted Tower Floor 2 Exit"),
        LLEntrance("", "Haunted Tower Floor 2 Exit", "Haunted Tower Floor 2", lambda state: state.has("Ghost Potion", player)),
        LLEntrance("Haunted Tower Floor 2 Stairs Up", "Haunted Tower Floor 2 Exit", "Haunted Tower Floor 3 Stairs Down", id=58),
        LLEntrance("Haunted Tower Floor 3 Stairs Down", "Haunted Tower Floor 3 Entrance", "Haunted Tower Floor 2 Stairs Up", id=59),
        LLEntrance("", "Haunted Tower Floor 3 Entrance", "Haunted Tower Floor 3", lambda state: state.has("Ghost Potion", player)),
        LLEntrance("", "Haunted Tower Floor 3", "Haunted Tower Floor 3 Entrance"),
        LLEntrance("", "Haunted Tower Floor 3", "Haunted Tower Floor 3 Exit"),
        LLEntrance("", "Haunted Tower Floor 3 Exit", "Haunted Tower Floor 3", lambda state: state.has("Ghost Potion", player)),
        LLEntrance("Haunted Tower Floor 3 Stairs Up", "Haunted Tower Floor 3 Exit", "Haunted Tower Roof Stairs Down", id=60),
        LLEntrance("", "Haunted Tower Roof", "Halloween Hill"),
        LLEntrance("Haunted Tower Roof Stairs Down", "Haunted Tower Roof", "Haunted Tower Floor 3 Stairs Up", id=61),
        LLEntrance("Haunted Tower Basement Stairs Up", "Haunted Basement Entrance", "Haunted Tower Stairs Down", id=62),
        LLEntrance("", "Haunted Basement Entrance", "Haunted Basement", lambda state: have_light_source(state, player)),
        LLEntrance("", "Haunted Basement", "Haunted Basement Entrance"),
        LLEntrance("", "Abandoned Mines Entrance", "Abandoned Mines", lambda state: have_light_source(state, player)),
        LLEntrance("Abadoned Mines Exit", "Abandoned Mines Entrance", "Rocky Cliffs West Cave", id=63),
        LLEntrance("", "Abandoned Mines", "Abandoned Mines Entrance"),
        LLEntrance("Bombulus Exit", "The Shrine Of Bombulus", "Rocky Cliffs Peak Cave", id=64),
        LLEntrance("", "A Gloomy Cavern Entrance", "A Gloomy Cavern", lambda state: have_light_source(state, player)),
        LLEntrance("Gloomy Cavern Exit", "A Gloomy Cavern Entrance", "Rocky Cliffs South Cave", id=65),
        LLEntrance("", "A Gloomy Cavern", "A Gloomy Cavern Entrance"),
        LLEntrance("Happy Stick Woods Exit", "Happy Stick Woods", "Wicked Woods Happy Stick", id=66),
        LLEntrance("", "The Wolf Den Entrance", "The Wolf Den", lambda state: can_kill_werewolves(state, player) and have_light_source(state, player)),
        LLEntrance("Wolf Den South Exit", "The Wolf Den Entrance", "Pointless Plains Cave", id=67),
        LLEntrance("", "The Wolf Den", "The Wolf Den Entrance"),
        LLEntrance("", "The Wolf Den", "The Wolf Den Exit"),
        LLEntrance("", "The Wolf Den Exit", "Larry's Lair"),
        LLEntrance("", "The Wolf Den Exit", "The Wolf Den", lambda state: can_kill_werewolves(state, player) and have_light_source(state, player)),
        LLEntrance("Larry's Cabin Door", "A Cabin Larry", "Zombiton SE House", id=68),
        LLEntrance("Upper Creepy Caverns West Exit", "Upper Creepy Caverns Left Warp", "Rocky Cliffs Rock Blocked Cave", lambda state: state.has("Bombs", player), id=69),
        LLEntrance("", "Upper Creepy Caverns Left Warp", "Upper Creepy Caverns", lambda state: have_light_source(state, player)),
        LLEntrance("", "Upper Creepy Caverns", "Upper Creepy Caverns Left Warp"),
        LLEntrance("Upper Creepy Caverns Center Stairs", "Upper Creepy Caverns Middle Warp", "Creepy Caverns Left Top Stairs", lambda state: have_light_source(state, player), id=70),
        LLEntrance("", "Upper Creepy Caverns Middle Warp", "Upper Creepy Caverns", lambda state: have_light_source(state, player)),
        LLEntrance("", "Upper Creepy Caverns", "Upper Creepy Caverns Middle Warp"),
        LLEntrance("Upper Creepy Caverns East Stairs", "Upper Creepy Caverns Right Warp", "Creepy Caverns Middle Top Stairs", lambda state: have_light_source(state, player), id=71),
        LLEntrance("", "Upper Creepy Caverns Right Warp", "Upper Creepy Caverns", lambda state: have_light_source(state, player)),
        LLEntrance("", "Upper Creepy Caverns", "Upper Creepy Caverns Right Warp"),
        LLEntrance("Under The Ravine West Exit", "Under The Ravine", "Creepy Caverns Middle Right Stairs", lambda state: have_light_source(state, player), id=72),
        LLEntrance("Under The Ravine East Exit", "Under The Ravine", "Creepy Caverns Right Left Stairs", lambda state: have_light_source(state, player), id=73),
        LLEntrance("Creepy Caverns Left Bottom Exit", "Creepy Caverns Left Bottom Warp", "Rocky Cliffs SE Cave", id=74),
        LLEntrance("", "Creepy Caverns Left Bottom Warp", "Creepy Caverns Left", lambda state: have_light_source(state, player)),
        LLEntrance("", "Creepy Caverns Left", "Creepy Caverns Left Bottom Warp"),
        LLEntrance("", "Creepy Caverns Left", "Creepy Caverns Left Top Warp"),
        LLEntrance("", "Creepy Caverns Left Top Warp", "Creepy Caverns Left", lambda state: have_light_source(state, player)),
        LLEntrance("Creepy Caverns Left Top Stairs", "Creepy Caverns Left Top Warp", "Upper Creepy Caverns Center Stairs", id=75),
        LLEntrance("Creepy Caverns Middle Top Stairs", "Creepy Caverns Middle Top Warp", "Upper Creepy Caverns East Stairs", id=76),
        LLEntrance("", "Creepy Caverns Middle Top Warp", "Creepy Caverns Middle", lambda state: have_light_source(state, player)),
        LLEntrance("", "Creepy Caverns Middle", "Creepy Caverns Middle Top Warp"),
        LLEntrance("", "Creepy Caverns Middle", "Creepy Caverns Middle Right Warp"),
        LLEntrance("Creepy Caverns Middle Right Stairs", "Creepy Caverns Middle Right Warp", "Under The Ravine West Exit", lambda state: power_level(state, player, 20), id=77),
        LLEntrance("", "Creepy Caverns Middle Right Warp", "Creepy Caverns Middle", lambda state: have_light_source(state, player)),
        LLEntrance("Creepy Caverns Right Left Stairs", "Creepy Caverns Right Left Warp", "Under The Ravine East Exit", lambda state: power_level(state, player, 20), id=78),
        LLEntrance("", "Creepy Caverns Right Left Warp", "Creepy Caverns Right", lambda state: have_light_source(state, player)),
        LLEntrance("", "Creepy Caverns Right", "Creepy Caverns Right Left Warp"),
        LLEntrance("", "Creepy Caverns Right", "Creepy Caverns Right Bottom Warp"),
        LLEntrance("", "Creepy Caverns Right Bottom Warp", "Creepy Caverns Right", lambda state: have_light_source(state, player)),
        LLEntrance("Creepy Caverns Right Bottom Exit", "Creepy Caverns Right Bottom Warp", "Vampy Land Cave", id=79),
        LLEntrance("Castle Vampy South Exit", "Castle Vampy", "Vampy Land Castle", id=80),
        LLEntrance("", "Castle Vampy", "Castle Vampy NW", lambda state: state.has("Bat Statue", player, 4)),
        LLEntrance("", "Castle Vampy", "Castle Vampy SW", lambda state: state.has("Bat Statue", player, 4)),
        LLEntrance("", "Castle Vampy", "Castle Vampy SE", lambda state: state.has("Bat Statue", player, 4)),
        LLEntrance("", "Castle Vampy", "Castle Vampy NE", lambda state: state.has("Bat Statue", player, 4)),
        LLEntrance("", "Castle Vampy", "Castle Vampy Skull Jail", lambda state: state.has("Skull Key", player)),
        LLEntrance("", "Castle Vampy Skull Jail", "Castle Vampy", lambda state: state.has("Skull Key", player)),
        LLEntrance("Castle Vampy Center Stairs Up", "Castle Vampy Skull Jail", "Castle Vampy II Center Stairs Down", id=81),
        LLEntrance("Castle Vampy NW Stairs Up", "Castle Vampy NW", "Castle Vampy II NW Stairs Down", id=82),
        LLEntrance("Castle Vampy SW Stairs Up", "Castle Vampy SW", "Castle Vampy II SW Stairs Down", id=83),
        LLEntrance("Castle Vampy SE Stairs Up", "Castle Vampy SE", "Castle Vampy II SE Stairs Down", id=84),
        LLEntrance("Castle Vampy NE Stairs Up", "Castle Vampy NE", "Castle Vampy II NE Stairs Down", id=85),
        LLEntrance("Castle Vampy II Center Stairs Down", "Castle Vampy II", "Castle Vampy Center Stairs Up", id=86),
        LLEntrance("", "Castle Vampy II", "Castle Vampy II Bat Jail", lambda state: state.has("Bat Key", player)),
        LLEntrance("", "Castle Vampy II Bat Jail", "Castle Vampy II", lambda state: state.has("Bat Key", player)),
        LLEntrance("Castle Vampy II Center Stairs Up", "Castle Vampy II Bat Jail", "Castle Vampy III Center Stairs Down", id=87),
        LLEntrance("Castle Vampy II NW Stairs Down", "Castle Vampy II NW", "Castle Vampy NW Stairs Up", id=88),
        LLEntrance("Castle Vampy II NW Stairs Up", "Castle Vampy II NW", "Castle Vampy III NW Stairs Down", id=89),
        LLEntrance("Castle Vampy II SW Stairs Down", "Castle Vampy II SW", "Castle Vampy SW Stairs Up", id=90),
        LLEntrance("Castle Vampy II SW Stairs Up", "Castle Vampy II SW", "Castle Vampy III SW Stairs Down", id=91),
        LLEntrance("Castle Vampy II SE Stairs Down", "Castle Vampy II SE", "Castle Vampy SE Stairs Up", id=92),
        LLEntrance("Castle Vampy II SE Stairs Up", "Castle Vampy II SE", "Castle Vampy III SE Stairs Down", id=93),
        LLEntrance("Castle Vampy II NE Stairs Down", "Castle Vampy II NE", "Castle Vampy NE Stairs Up", id=94),
        LLEntrance("Castle Vampy II NE Stairs Up", "Castle Vampy II NE", "Castle Vampy III NE Stairs Down", id=95),
        LLEntrance("Cabin In The Woods Exit", "Cabin In The Woods", "Wicked Woods Cabin", id=96),
        LLEntrance("Castle Vampy III Center Stairs Down", "Castle Vampy III", "Castle Vampy II Center Stairs Up", id=97),
        LLEntrance("", "Castle Vampy III", "Castle Vampy III Pumpkin Jail", lambda state: state.has("Pumpkin Key", player)),
        LLEntrance("", "Castle Vampy III Pumpkin Jail", "Castle Vampy III", lambda state: state.has("Pumpkin Key", player)),
        LLEntrance("Castle Vampy III Center Stairs Up", "Castle Vampy III Pumpkin Jail", "Castle Vampy IV Center Stairs Down", id=98),
        LLEntrance("Castle Vampy III NW Stairs Down", "Castle Vampy III NW", "Castle Vampy II NW Stairs Up", id=99),
        LLEntrance("Castle Vampy III NW Stairs Up", "Castle Vampy III NW", "Castle Vampy IV NW Stairs Down", id=100),
        LLEntrance("Castle Vampy III SW Stairs Down", "Castle Vampy III SW", "Castle Vampy II SW Stairs Up", id=101),
        LLEntrance("Castle Vampy III SW Stairs Up", "Castle Vampy III SW", "Castle Vampy IV SW Stairs Down", id=102),
        LLEntrance("Castle Vampy III SE Stairs Down", "Castle Vampy III SE", "Castle Vampy II SE Stairs Up", id=103),
        LLEntrance("Castle Vampy III SE Stairs Up", "Castle Vampy III SE", "Castle Vampy IV SE Stairs Down", id=104),
        LLEntrance("Castle Vampy III NE Stairs Down", "Castle Vampy III NE", "Castle Vampy II NE Stairs Up", id=105),
        LLEntrance("Castle Vampy III NE Stairs Up", "Castle Vampy III NE", "Castle Vampy IV NE Stairs Down", id=106),
        LLEntrance("Castle Vampy IV Center Stairs Down", "Castle Vampy IV", "Castle Vampy III Center Stairs Up", id=107),
        LLEntrance("", "Castle Vampy IV", "The Heart Of Terror Entrance", lambda state: state.has("Vampire Bust", player, 8)),
        LLEntrance("Castle Vampy IV NW Stairs Down", "Castle Vampy IV NW", "Castle Vampy III NW Stairs Up", id=108),
        LLEntrance("Castle Vampy IV NW Stairs Up", "Castle Vampy IV NW", "Castle Vampy Roof NW Stairs Down", id=109),
        LLEntrance("Castle Vampy IV SW Stairs Down", "Castle Vampy IV SW", "Castle Vampy III SW Stairs Up", id=110),
        LLEntrance("Castle Vampy IV SW Stairs Up", "Castle Vampy IV SW", "Castle Vampy Roof SW Stairs Down", id=111),
        LLEntrance("Castle Vampy IV SE Stairs Down", "Castle Vampy IV SE", "Castle Vampy III SE Stairs Up", id=112),
        LLEntrance("Castle Vampy IV SE Stairs Up", "Castle Vampy IV SE", "Castle Vampy Roof SE Stairs Down", id=113),
        LLEntrance("Castle Vampy IV NE Stairs Down", "Castle Vampy IV NE", "Castle Vampy III NE Stairs Up", id=114),
        LLEntrance("Castle Vampy IV NE Stairs Up", "Castle Vampy IV NE", "Castle Vampy Roof NE Stairs Down", id=115),
        LLEntrance("Collector's Cabin Exit", "A Cabin Collector", "Luniton Center House", id=116),
        LLEntrance("Castle Vampy Roof NW Stairs Down", "Castle Vampy Roof NW", "Castle Vampy IV NW Stairs Up", id=117),
        LLEntrance("Castle Vampy Roof SW Stairs Down", "Castle Vampy Roof SW", "Castle Vampy IV SW Stairs Up", id=118),
        LLEntrance("Castle Vampy Roof SE Stairs Down", "Castle Vampy Roof SE", "Castle Vampy IV SE Stairs Up", id=119),
        LLEntrance("Castle Vampy Roof NE Stairs Down", "Castle Vampy Roof NE", "Castle Vampy IV NE Stairs Up", id=120),
        LLEntrance("", "The Evilizer", "Halloween Hill"),
        LLEntrance("", "The Heart Of Terror Entrance", "The Heart Of Terror", lambda state: have_light_source(state, player)),
        LLEntrance("", "The Heart Of Terror", "The Evilizer"),
        LLEntrance("", "The Heart Of Terror", "Empty Rooftop"),
        LLEntrance("A Hidey-Hole Exit", "A Hidey-Hole", "Wicked Woods Tree Cluster", id=121),
        LLEntrance("", "Empty Rooftop", "Halloween Hill"),
        LLEntrance("", "Swampdog Lair Entrance", "Swampdog Lair", lambda state: state.has("Boots", player)),
        LLEntrance("Swampdog Lair Exit", "Swampdog Lair Entrance", "Slurpy Swamp SE Cave", id=122),
        LLEntrance("", "Swampdog Lair", "Swampdog Lair Entrance"),
        LLEntrance("", "Larry's Lair", "Halloween Hill"),
        LLEntrance("", "Halloween Hill", "Slurpy Swamp Mud", lambda state: state.has("Boots", player)),
        LLEntrance("", "Slurpy Swamp Mud", "Halloween Hill", lambda state: state.has("Boots", player)),
        LLEntrance("", "Slurpy Swamp Mud North Warp", "Slurpy Swamp Mud", lambda state: state.has("Boots", player)),
        LLEntrance("", "Slurpy Swamp Mud East Warp", "Slurpy Swamp Mud", lambda state: state.has("Boots", player)),
        LLEntrance("", "Zombiton", "Halloween Hill"),
        LLEntrance("", "Halloween Hill", "Zombiton", lambda state: state.has("All Access Pass", player)),
        LLEntrance("", "Halloween Hill", "Rocky Cliffs", lambda state: state.has("Big Gem", player) or state.has("All Access Pass", player)),
        LLEntrance("", "Rocky Cliffs", "Halloween Hill", lambda state: state.has("Big Gem", player) or state.has("All Access Pass", player)),
        LLEntrance("", "Vampy Land", "Halloween Hill", lambda state: state.has("All Access Pass", player)),
        LLEntrance("", "Halloween Hill", "Vampy Land", lambda state: state.has("All Access Pass", player)),
        LLEntrance("", "Underground Tunnel", "Underground Tunnel Mud", lambda state: state.has("Boots", player)),
        LLEntrance("", "Underground Tunnel Mud", "Underground Tunnel", lambda state: state.has("Boots", player)),
        LLEntrance("", "Underground Tunnel Mud", "Underground Tunnel Zombie", lambda state: state.has("Boots", player)),
        LLEntrance("", "Underground Tunnel Zombie", "Underground Tunnel Mud", lambda state: state.has("Boots", player) and state.has("All Access Pass", player)),
        LLEntrance("", "Swamp Gas Cavern", "Swamp Gas Cavern Back", lambda state: state.has("Boots", player)),
        LLEntrance("", "Swamp Gas Cavern Back", "Swamp Gas Cavern", lambda state: state.has("All Access Pass", player)),
    ]
