from BaseClasses import ItemClassification
from typing import TypedDict, List, Dict, Set
from enum import Enum


class UKType(Enum):
    Weapon = 1
    WeaponAlt = 2
    Arm = 3
    Ability = 4
    Skull = 5
    Level = 6
    Layer = 7
    Points = 8
    Powerup = 9
    Trap = 10
    Soap = 11
    Fire2 = 12


class ItemDict(TypedDict):
    name: str
    #count: int
    classification: ItemClassification
    type: UKType


base_id = 2009000


item_table: List[ItemDict] = [
    # Weapons
    {'name': "Revolver - Piercer", #rev0 (blue)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},
    {'name': "Revolver - Marksman", #rev2 (green)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},
    {'name': "Revolver - Sharpshooter", #rev1 (red)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},
    {'name': "Revolver - Alternate", #revalt
        'classification': ItemClassification.progression,
        'type': UKType.WeaponAlt},

    {'name': "Shotgun - Core Eject", #sho0 (blue)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},
    {'name': "Shotgun - Pump Charge", #sho1 (green)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},

    {'name': "Nailgun - Attractor", #nai0 (blue)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},
    {'name': "Nailgun - Overheat", #nai1 (green)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},
    {'name': "Nailgun - Alternate", #naialt
        'classification': ItemClassification.useful,
        'type': UKType.WeaponAlt},

    {'name': "Railcannon - Electric", #rai0 (blue)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},
    {'name': "Railcannon - Screwdriver", #rai1 (green)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},
    {'name': "Railcannon - Malicious", #rai2 (red)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},

    {'name': "Rocket Launcher - Freezeframe", #rock0 (blue)
        'classification': ItemClassification.progression,
        'type': UKType.Weapon},
    {'name': "Rocket Launcher - S.R.S. Cannon", #rock1 (green)
        'classification': ItemClassification.progression, # ?
        'type': UKType.Weapon},

    {'name': "Secondary Fire - Piercer",
        'classification': ItemClassification.progression,
        'type': UKType.Fire2},
    {'name': "Secondary Fire - Marksman",
        'classification': ItemClassification.progression,
        'type': UKType.Fire2},
    {'name': "Secondary Fire - Sharpshooter",
        'classification': ItemClassification.progression,
        'type': UKType.Fire2},
    {'name': "Secondary Fire - Core Eject",
        'classification': ItemClassification.progression,
        'type': UKType.Fire2},
    {'name': "Secondary Fire - Pump Charge",
        'classification': ItemClassification.progression,
        'type': UKType.Fire2},
    {'name': "Secondary Fire - Attractor",
        'classification': ItemClassification.progression,
        'type': UKType.Fire2},
    {'name': "Secondary Fire - Overheat",
        'classification': ItemClassification.progression,
        'type': UKType.Fire2},
    {'name': "Secondary Fire - Freezeframe",
        'classification': ItemClassification.progression,
        'type': UKType.Fire2},
    {'name': "Secondary Fire - S.R.S. Cannon",
        'classification': ItemClassification.progression,
        'type': UKType.Fire2},

    {'name': "Feedbacker", #arm0
        'classification': ItemClassification.progression, # ?
        'type': UKType.Arm},
    {'name': "Knuckleblaster", #arm1
        'classification': ItemClassification.progression,
        'type': UKType.Arm},
    {'name': "Whiplash", #arm2
        'classification': ItemClassification.progression,
        'type': UKType.Arm},

    # Abilities
    {'name': "Stamina Bar",
        'classification': ItemClassification.progression,
        'type': UKType.Ability},
    {'name': "Wall Jump",
        'classification': ItemClassification.progression,
        'type': UKType.Ability},
    {'name': "Slide",
        'classification': ItemClassification.progression,
        'type': UKType.Ability},
    {'name': "Slam",
        'classification': ItemClassification.progression,
        'type': UKType.Ability},

    # Skulls
    {'name': "Blue Skull (0-2)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (0-S)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Red Skull (0-S)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Red Skull (1-1)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (1-1)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (1-2)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Red Skull (1-2)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (1-3)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Red Skull (1-3)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (1-4)", # 4 of them
        'classification': ItemClassification.filler,
        'type': UKType.Skull},
    {'name': "Blue Skull (2-3)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Red Skull (2-3)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (2-4)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Red Skull (2-4)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (4-2)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Red Skull (4-2)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (4-3)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (4-4)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (5-1)", # 3 of them
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (5-2)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Red Skull (5-2)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Blue Skull (5-3)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Red Skull (5-3)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},
    {'name': "Red Skull (6-1)",
        'classification': ItemClassification.progression,
        'type': UKType.Skull},

    # Levels
    {'name': "0-2: THE MEATGRINDER",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "0-3: DOUBLE DOWN",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "0-4: A ONE-MACHINE ARMY",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "0-5: CERBERUS",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "1-1: HEART OF THE SUNRISE",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "1-2: THE BURNING WORLD",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "1-3: HALLS OF SACRED REMAINS",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "1-4: CLAIR DE LUNE",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "2-1: BRIDGEBURNER",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "2-2: DEATH AT 20,000 VOLTS",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "2-3: SHEER HEART ATTACK",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "2-4: COURT OF THE CORPSE KING",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "3-1: BELLY OF THE BEAST",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "3-2: IN THE FLESH",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "4-1: SLAVES TO POWER",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "4-2: GOD DAMN THE SUN",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "4-3: A SHOT IN THE DARK",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "4-4: CLAIR DE SOLEIL",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "5-1: IN THE WAKE OF POSEIDON",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "5-2: WAVES OF THE STARLESS SEA",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "5-3: SHIP OF FOOLS",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "5-4: LEVIATHAN",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "6-1: CRY FOR THE WEEPER",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "6-2: AESTHETICS OF HATE",
        'classification': ItemClassification.progression,
        'type': UKType.Level},
    {'name': "P-1: SOUL SURVIVOR",
        'classification': ItemClassification.filler,
        'type': UKType.Level},
    {'name': "P-2: WAIT OF THE WORLD",
        'classification': ItemClassification.filler,
        'type': UKType.Level},

    # Layers
    {'name': "OVERTURE: THE MOUTH OF HELL",
        'classification': ItemClassification.progression,
        'type': UKType.Layer},
    {'name': "LAYER 1: LIMBO",
        'classification': ItemClassification.progression,
        'type': UKType.Layer},
    {'name': "LAYER 2: LUST",
        'classification': ItemClassification.progression,
        'type': UKType.Layer},
    {'name': "LAYER 3: GLUTTONY",
        'classification': ItemClassification.progression,
        'type': UKType.Layer},
    {'name': "LAYER 4: GREED",
        'classification': ItemClassification.progression,
        'type': UKType.Layer},
    {'name': "LAYER 5: WRATH",
        'classification': ItemClassification.progression,
        'type': UKType.Layer},
    {'name': "LAYER 6: HERESY",
        'classification': ItemClassification.progression,
        'type': UKType.Layer},

    # Points
    {'name': "+10,000P",
        'classification': ItemClassification.filler,
        'type': UKType.Points},

    # Powerups
    {'name': "Overheal",
        'classification': ItemClassification.filler,
        'type': UKType.Powerup},
    {'name': "Dual Wield",
        'classification': ItemClassification.filler,
        'type': UKType.Powerup},
    {'name': "Infinite Stamina",
        'classification': ItemClassification.filler,
        'type': UKType.Powerup},
    {'name': "Air Jump",
        'classification': ItemClassification.filler,
        'type': UKType.Powerup},
    {'name': "Soap",
        'classification': ItemClassification.filler,
        'type': UKType.Soap},

    # Traps
    {'name': "Hard Damage",
        'classification': ItemClassification.trap,
        'type': UKType.Trap},
    {'name': "Stamina Limiter",
        'classification': ItemClassification.trap,
        'type': UKType.Trap},
    {'name': "Wall Jump Limiter",
        'classification': ItemClassification.trap,
        'type': UKType.Trap},
    {'name': "Empty Ammunition",
        'classification': ItemClassification.trap,
        'type': UKType.Trap},
    {'name': "Radiant Aura",
        'classification': ItemClassification.trap,
        'type': UKType.Trap},
]

group_table: Dict[str, Set[str]] = {
    "revolver": ["Revolver - Piercer",
                 "Revolver - Marksman",
                 "Revolver - Sharpshooter"],
    "pistol": ["Revolver - Piercer",
               "Revolver - Marksman",
               "Revolver - Sharpshooter"],
    "shotgun": ["Shotgun - Core Eject",
                "Shotgun - Pump Charge"],
    "nailgun": ["Nailgun - Attractor",
                "Nailgun - Overheat"],
    "railcannon": ["Railcannon - Electric",
                   "Railcannon - Screwdriver",
                   "Railcannon - Malicious"],
    "railgun": ["Railcannon - Electric",
                "Railcannon - Screwdriver",
                "Railcannon - Malicious"],
    "rocket": ["Rocket Launcher - Freezeframe",
               "Rocket Launcher - S.R.S. Cannon"],
    "rocket launcher": ["Rocket Launcher - Freezeframe",
                        "Rocket Launcher - S.R.S. Cannon"],
    "rpg": ["Rocket Launcher - Freezeframe",
            "Rocket Launcher - S.R.S. Cannon"],
    "junk": ["+10,000P",
             "Overheal",
             "Dual Wield",
             "Infinite Stamina",
             "Air Jump",
             "Soap",
             "Hard Damage",
             "Stamina Limiter",
             "Wall Jump Limiter",
             "Empty Ammunition",
             "Radiant Aura"],
    "filler": ["+10,000P",
               "Overheal",
               "Dual Wield",
               "Infinite Stamina",
               "Air Jump",
               "Soap"],
    "trap": ["Hard Damage",
             "Stamina Limiter",
             "Wall Jump Limiter",
             "Empty Ammunition",
             "Radiant Aura"],
    "dash": ["Stamina Bar"],
    "walljump": ["Wall Jump"],
    "levels": ["0-2: THE MEATGRINDER",
               "0-3: DOUBLE DOWN",
               "0-4: A ONE-MACHINE ARMY",
               "0-5: CERBERUS",
               "1-1: HEART OF THE SUNRISE",
               "1-2: THE BURNING WORLD",
               "1-3: HALLS OF SACRED REMAINS",
               "1-4: CLAIR DE LUNE",
               "2-1: BRIDGEBURNER",
               "2-2: DEATH AT 20,000 VOLTS",
               "2-3: SHEER HEART ATTACK",
               "2-4: COURT OF THE CORPSE KING",
               "3-1: BELLY OF THE BEAST",
               "3-2: IN THE FLESH",
               "4-1: SLAVES TO POWER",
               "4-2: GOD DAMN THE SUN",
               "4-3: A SHOT IN THE DARK",
               "4-4: CLAIR DE SOLEIL",
               "5-1: IN THE WAKE OF POSEIDON",
               "5-2: WAVES OF THE STARLESS SEA",
               "5-3: SHIP OF FOOLS",
               "5-4: LEVIATHAN",
               "6-1: CRY FOR THE WEEPER",
               "6-2: AESTHETICS OF HATE"],
    "layers": ["OVERTURE: THE MOUTH OF HELL",
               "LAYER 1: LIMBO",
               "LAYER 2: LUST",
               "LAYER 3: GLUTTONY",
               "LAYER 4: GREED",
               "LAYER 5: WRATH",
               "LAYER 6: HERESY"],
    "start_weapons": ["Revolver - Piercer",
                      "Revolver - Marksman",
                      "Revolver - Sharpshooter",
                      "Shotgun - Core Eject",
                      "Shotgun - Pump Charge",
                      "Nailgun - Attractor",
                      "Nailgun - Overheat",
                      "Railcannon - Electric",
                      "Railcannon - Screwdriver",
                      "Railcannon - Malicious",
                      "Rocket Launcher - Freezeframe",
                      "Rocket Launcher - S.R.S. Cannon",
                      "Feedbacker",
                      "Knuckleblaster"],
    "0-2": ["0-2: THE MEATGRINDER"],
    "0-3": ["0-3: DOUBLE DOWN"],
    "0-4": ["0-4: A ONE-MACHINE ARMY"],
    "0-5": ["0-5: CERBERUS"],
    "1-1": ["1-1: HEART OF THE SUNRISE"],
    "1-2": ["1-2: THE BURNING WORLD"],
    "1-3": ["1-3: HALLS OF SACRED REMAINS"],
    "1-4": ["1-4: CLAIR DE LUNE"],
    "2-1": ["2-1: BRIDGEBURNER"],
    "2-2": ["2-2: DEATH AT 20,000 VOLTS"],
    "2-3": ["2-3: SHEER HEART ATTACK"],
    "2-4": ["2-4: COURT OF THE CORPSE KING"],
    "3-1": ["3-1: BELLY OF THE BEAST"],
    "3-2": ["3-2: IN THE FLESH"],
    "4-1": ["4-1: SLAVES TO POWER"],
    "4-2": ["4-2: GOD DAMN THE SUN"],
    "4-3": ["4-3: A SHOT IN THE DARK"],
    "4-4": ["4-4: CLAIR DE SOLEIL"],
    "5-1": ["5-1: IN THE WAKE OF POSEIDON"],
    "5-2": ["5-2: WAVES OF THE STARLESS SEA"],
    "5-3": ["5-3: SHIP OF FOOLS"],
    "5-4": ["5-4: LEVIATHAN"],
    "6-1": ["6-1: CRY FOR THE WEEPER"],
    "6-2": ["6-2: AESTHETICS OF HATE"],
    "P-1": ["P-1: SOUL SURVIVOR"],
    "P-2": ["P-2: WAIT OF THE WORLD"],
    "overture": ["OVERTURE: THE MOUTH OF HELL"],
    "prologue": ["OVERTURE: THE MOUTH OF HELL"],
    "prelude": ["OVERTURE: THE MOUTH OF HELL"],
    "layer 1": ["LAYER 1: LIMBO"],
    "limbo": ["LAYER 1: LIMBO"],
    "layer 2": ["LAYER 2: LUST"],
    "lust": ["LAYER 2: LUST"],
    "layer 3": ["LAYER 3: GLUTTONY"],
    "gluttony": ["LAYER 3: GLUTTONY"],
    "layer 4": ["LAYER 4: GREED"],
    "greed": ["LAYER 4: GREED"],
    "layer 5": ["LAYER 5: WRATH"],
    "wrath": ["LAYER 5: WRATH"],
    "layer 6": ["LAYER 6: HERESY"],
    "heresy": ["LAYER 6: HERESY"],
}