from typing import TypedDict, List, Set


class LocationDict(TypedDict):
    name: str
    region: str
    game_id: str


location_table: List[LocationDict] = [
    # 0-1: INTO THE FIRE
    {'name': "0-1: Weapon",
        'region': "0-1",
        'game_id': "1_w1"},
    {'name': "0-1: Secret #1",
        'region': "0-1",
        'game_id': "1_s1"},
    {'name': "0-1: Secret #2",
        'region': "0-1",
        'game_id': "1_s2"},
    {'name': "0-1: Secret #3",
        'region': "0-1",
        'game_id': "1_s3"},
    {'name': "0-1: Secret #4",
        'region': "0-1",
        'game_id': "1_s4"},
    {'name': "0-1: Secret #5",
        'region': "0-1",
        'game_id': "1_s5"},
    {'name': "0-1: Get 5 kills with a single glass panel",
        'region': "0-1",
        'game_id': "1_c"},
    {'name': "0-1: Perfect Rank",
        'region': "0-1",
        'game_id': "1_p"},

    # 0-2: THE MEATGRINDER
    {'name': "0-2: Secret #1",
        'region': "0-2",
        'game_id': "2_s1"},
    {'name': "0-2: Secret #2",
        'region': "0-2",
        'game_id': "2_s2"},
    {'name': "0-2: Secret #3",
        'region': "0-2",
        'game_id': "2_s3"},
    {'name': "0-2: Secret #4",
        'region': "0-2",
        'game_id': "2_s4"},
    {'name': "0-2: Secret #5",
        'region': "0-2",
        'game_id': "2_s5"},
    {'name': "0-2: Beat the secret encounter",
        'region': "0-2",
        'game_id': "2_c"},
    {'name': "0-2: Perfect Rank",
        'region': "0-2",
        'game_id': "2_p"},

    # 0-3: DOUBLE DOWN
    {'name': "0-3: Weapon",
        'region': "0-3",
        'game_id': "3_w1"},
    {'name': "0-3: Secret #1",
        'region': "0-3",
        'game_id': "3_s1"},
    {'name': "0-3: Secret #2",
        'region': "0-3",
        'game_id': "3_s2"},
    {'name': "0-3: Secret #3",
        'region': "0-3",
        'game_id': "3_s3"},
    {'name': "0-3: Kill only 1 enemy",
        'region': "0-3",
        'game_id': "3_c"},
    {'name': "0-3: Perfect Rank",
        'region': "0-3",
        'game_id': "3_p"},

    # 0-4: A ONE-MACHINE ARMY
    {'name': "0-4: Secret #1",
        'region': "0-4",
        'game_id': "4_s1"},
    {'name': "0-4: Secret #2",
        'region': "0-4",
        'game_id': "4_s2"},
    {'name': "0-4: Secret #3",
        'region': "0-4",
        'game_id': "4_s3"},
    {'name': "0-4: Slide uninterrupted for 17 seconds",
        'region': "0-4",
        'game_id': "4_c"},
    {'name': "0-4: Perfect Rank",
        'region': "0-4",
        'game_id': "4_p"},

    # 0-5: CERBERUS
    {'name': "0-5: Defeat the Cerberi",
        'region': "0-5",
        'game_id': "5_b"},
    {'name': "0-5: Don't inflict fatal damage to any enemy",
        'region': "0-5",
        'game_id': "5_c"},
    {'name': "0-5: Perfect Rank",
        'region': "0-5",
        'game_id': "5_p"},
    
    # 1-1: HEART OF THE SUNRISE
    {'name': "1-1: Weapon",
        'region': "1-1",
        'game_id': "6_w1"},
    {'name': "1-1: Secret #1",
        'region': "1-1",
        'game_id': "6_s1"},
    {'name': "1-1: Secret #2",
        'region': "1-1",
        'game_id': "6_s2"},
    {'name': "1-1: Secret #3",
        'region': "1-1",
        'game_id': "6_s3"},
    {'name': "1-1: Secret #4",
        'region': "1-1",
        'game_id': "6_s4"},
    {'name': "1-1: Secret #5",
        'region': "1-1",
        'game_id': "6_s5"},
    {'name': "1-1: Complete the level in under 10 seconds",
        'region': "1-1",
        'game_id': "6_c"},
    {'name': "1-1: Perfect Rank",
        'region': "1-1",
        'game_id': "6_p"},

    # 1-2: THE BURNING WORLD
    {'name': "1-2: Secret #1",
        'region': "1-2",
        'game_id': "7_s1"},
    {'name': "1-2: Secret #2",
        'region': "1-2",
        'game_id': "7_s2"},
    {'name': "1-2: Secret #3",
        'region': "1-2",
        'game_id': "7_s3"},
    {'name': "1-2: Secret #4",
        'region': "1-2",
        'game_id': "7_s4"},
    {'name': "1-2: Secret #5",
        'region': "1-2",
        'game_id': "7_s5"},
    {'name': "1-2: Defeat the Very Cancerous Rodent",
        'region': "1-2",
        'game_id': "7_b"},
    {'name': "1-2: Do not pick up any skulls",
        'region': "1-2",
        'game_id': "7_c"},
    {'name': "1-2: Perfect Rank",
        'region': "1-2",
        'game_id': "7_p"},
    
    # 1-3: HALLS OF SACRED REMAINS
    {'name': "1-3: Secret #1",
        'region': "1-3",
        'game_id': "8_s1"},
    {'name': "1-3: Secret #2",
        'region': "1-3",
        'game_id': "8_s2"},
    {'name': "1-3: Secret #3",
        'region': "1-3",
        'game_id': "8_s3"},
    {'name': "1-3: Secret #4",
        'region': "1-3",
        'game_id': "8_s4"},
    {'name': "1-3: Secret #5",
        'region': "1-3",
        'game_id': "8_s5"},
    {'name': "1-3: Beat the secret encounter",
        'region': "1-3",
        'game_id': "8_c"},
    {'name': "1-3: Perfect Rank",
        'region': "1-3",
        'game_id': "8_p"},

    # 1-4: CLAIR DE LUNE
    {'name': "1-4: V2's Arm",
        'region': "1-4",
        'game_id': "9_w1"},
    {'name': "1-4: Secret Weapon",
        'region': "1-4",
        'game_id': "9_w2"},
    {'name': "1-4: Defeat V2",
        'region': "1-4",
        'game_id': "9_b"},
    {'name': "1-4: Do not pick up any skulls",
        'region': "1-4",
        'game_id': "9_c"},
    {'name': "1-4: Perfect Rank",
        'region': "1-4",
        'game_id': "9_p"},

    # 2-1: BRIDGEBURNER
    {'name': "2-1: Secret #1",
        'region': "2-1",
        'game_id': "10_s1"},
    {'name': "2-1: Secret #2",
        'region': "2-1",
        'game_id': "10_s2"},
    {'name': "2-1: Secret #3",
        'region': "2-1",
        'game_id': "10_s3"},
    {'name': "2-1: Secret #4",
        'region': "2-1",
        'game_id': "10_s4"},
    {'name': "2-1: Secret #5",
        'region': "2-1",
        'game_id': "10_s5"},
    {'name': "2-1: Don't open any normal doors",
        'region': "2-1",
        'game_id': "10_c"},
    {'name': "2-1: Perfect Rank",
        'region': "2-1",
        'game_id': "10_p"},

    # 2-2: DEATH AT 20,000 VOLTS
    {'name': "2-2: Weapon",
        'region': "2-2",
        'game_id': "11_w1"},
    {'name': "2-2: Secret #1",
        'region': "2-2",
        'game_id': "11_s1"},
    {'name': "2-2: Secret #2",
        'region': "2-2",
        'game_id': "11_s2"},
    {'name': "2-2: Secret #3",
        'region': "2-2",
        'game_id': "11_s3"},
    {'name': "2-2: Secret #4",
        'region': "2-2",
        'game_id': "11_s4"},
    {'name': "2-2: Secret #5",
        'region': "2-2",
        'game_id': "11_s5"},
    {'name': "2-2: Beat the level in under 60 seconds",
        'region': "2-2",
        'game_id': "11_c"},
    {'name': "2-2: Perfect Rank",
        'region': "2-2",
        'game_id': "11_p"},
    
    # 2-3: SHEER HEART ATTACK
    {'name': "2-3: Secret #1",
        'region': "2-3",
        'game_id': "12_s1"},
    {'name': "2-3: Secret #2",
        'region': "2-3",
        'game_id': "12_s2"},
    {'name': "2-3: Secret #3",
        'region': "2-3",
        'game_id': "12_s3"},
    {'name': "2-3: Secret #4",
        'region': "2-3",
        'game_id': "12_s4"},
    {'name': "2-3: Secret #5",
        'region': "2-3",
        'game_id': "12_s5"},
    {'name': "2-3: Don't touch any water",
        'region': "2-3",
        'game_id': "12_c"},
    {'name': "2-3: Perfect Rank",
        'region': "2-3",
        'game_id': "12_p"},

    # 2-4: COURT OF THE CORPSE KING
    {'name': "2-4: Defeat the Corpse of King Minos",
        'region': "2-4",
        'game_id': "13_b"},
    {'name': "2-4: Parry a punch",
        'region': "2-4",
        'game_id': "13_c"},
    {'name': "2-4: Perfect Rank",
        'region': "2-4",
        'game_id': "13_p"},

    # 3-1: BELLY OF THE BEAST
    {'name': "3-1: Secret #1",
        'region': "3-1",
        'game_id': "14_s1"},
    {'name': "3-1: Secret #2",
        'region': "3-1",
        'game_id': "14_s2"},
    {'name': "3-1: Secret #3",
        'region': "3-1",
        'game_id': "14_s3"},
    {'name': "3-1: Secret #4",
        'region': "3-1",
        'game_id': "14_s4"},
    {'name': "3-1: Secret #5",
        'region': "3-1",
        'game_id': "14_s5"},
    {'name': "3-1: Kill a Mindflayer with acid",
        'region': "3-1",
        'game_id': "14_c"},
    {'name': "3-1: Perfect Rank",
        'region': "3-1",
        'game_id': "14_p"},

    # 3-2: IN THE FLESH
    {'name': "3-2: Defeat Gabriel",
        'region': "3-2",
        'game_id': "15_b"},
    {'name': "3-2: Drop Gabriel in a pit",
        'region': "3-2",
        'game_id': "15_c"},
    {'name': "3-2: Perfect Rank",
        'region': "3-2",
        'game_id': "15_p"},

    # 4-1: SLAVES TO POWER
    {'name': "4-1: Secret #1",
        'region': "4-1",
        'game_id': "16_s1"},
    {'name': "4-1: Secret #2",
        'region': "4-1",
        'game_id': "16_s2"},
    {'name': "4-1: Secret #3",
        'region': "4-1",
        'game_id': "16_s3"},
    {'name': "4-1: Secret #4",
        'region': "4-1",
        'game_id': "16_s4"},
    {'name': "4-1: Secret #5",
        'region': "4-1",
        'game_id': "16_s5"},
    {'name': "4-1: Don't activate any enemies",
        'region': "4-1",
        'game_id': "16_c"},
    {'name': "4-1: Perfect Rank",
        'region': "4-1",
        'game_id': "16_p"},

    # 4-2: GOD DAMN THE SUN
    {'name': "4-2: Secret #1",
        'region': "4-2",
        'game_id': "17_s1"},
    {'name': "4-2: Secret #2",
        'region': "4-2",
        'game_id': "17_s2"},
    {'name': "4-2: Secret #3",
        'region': "4-2",
        'game_id': "17_s3"},
    {'name': "4-2: Secret #4",
        'region': "4-2",
        'game_id': "17_s4"},
    {'name': "4-2: Secret #5",
        'region': "4-2",
        'game_id': "17_s5"},
    {'name': "4-2: Kill the Insurrectionist in under 10 seconds",
        'region': "4-2",
        'game_id': "17_c"},
    {'name': "4-2: Perfect Rank",
        'region': "4-2",
        'game_id': "17_p"},

    # 4-3: A SHOT IN THE DARK
    {'name': "4-3: Secret #1",
        'region': "4-3",
        'game_id': "18_s1"},
    {'name': "4-3: Secret #2",
        'region': "4-3",
        'game_id': "18_s2"},
    {'name': "4-3: Secret #3",
        'region': "4-3",
        'game_id': "18_s3"},
    {'name': "4-3: Secret #4",
        'region': "4-3",
        'game_id': "18_s4"},
    {'name': "4-3: Secret #5",
        'region': "4-3",
        'game_id': "18_s5"},
    {'name': "4-3: Defeat the Mysterious Druid Knight (& Owl)",
        'region': "4-3",
        'game_id': "18_b"},
    {'name': "4-3: Don't pick up the torch",
        'region': "4-3",
        'game_id': "18_c"},
    {'name': "4-3: Perfect Rank",
        'region': "4-3",
        'game_id': "18_p"},

    # 4-4: CLAIR DE SOLEIL
    {'name': "4-4: V2's Other Arm",
        'region': "4-4",
        'game_id': "19_w1"},
    {'name': "4-4: Secret Weapon",
        'region': "4-4",
        'game_id': "19_w2"},
    {'name': "4-4: Defeat V2",
        'region': "4-4",
        'game_id': "19_b"},
    {'name': "4-4: Reach the boss room in 18 seconds",
        'region': "4-4",
        'game_id': "19_c"},
    {'name': "4-4: Perfect Rank",
        'region': "4-4",
        'game_id': "19_p"},

    # 5-1: IN THE WAKE OF POSEIDON
    {'name': "5-1: Secret #1",
        'region': "5-1",
        'game_id': "20_s1"},
    {'name': "5-1: Secret #2",
        'region': "5-1",
        'game_id': "20_s2"},
    {'name': "5-1: Secret #3",
        'region': "5-1",
        'game_id': "20_s3"},
    {'name': "5-1: Secret #4",
        'region': "5-1",
        'game_id': "20_s4"},
    {'name': "5-1: Secret #5",
        'region': "5-1",
        'game_id': "20_s5"},
    {'name': "5-1: Don't touch any water",
        'region': "5-1",
        'game_id': "20_c"},
    {'name': "5-1: Perfect Rank",
        'region': "5-1",
        'game_id': "20_p"},

    # 5-S: I ONLY SAY MORNING
    {'name': "Funny Stupid Fish (Friend)",
        'region': "5-S",
        'game_id': "fish0"},
    {'name': "PITR Fish",
        'region': "5-S",
        'game_id': "fish1"},
    {'name': "Trout",
        'region': "5-S",
        'game_id': "fish2"},
    {'name': "Metal Fish",
        'region': "5-S",
        'game_id': "fish3"},
    {'name': "Chomper",
        'region': "5-S",
        'game_id': "fish4"},
    {'name': "Bomb Fish",
        'region': "5-S",
        'game_id': "fish5"},
    {'name': "Eyeball",
        'region': "5-S",
        'game_id': "fish6"},
    {'name': "Frog (?)",
        'region': "5-S",
        'game_id': "fish7"},
    {'name': "Dope Fish",
        'region': "5-S",
        'game_id': "fish8"},
    {'name': "Stickfish",
        'region': "5-S",
        'game_id': "fish9"},
    {'name': "Cooked Fish",
        'region': "5-S",
        'game_id': "fish10"},
    {'name': "Shark",
        'region': "5-S",
        'game_id': "fish11"},

    # 5-2: WAVES OF THE STARLESS SEA
    {'name': "5-2: Secret #1",
        'region': "5-2",
        'game_id': "21_s1"},
    {'name': "5-2: Secret #2",
        'region': "5-2",
        'game_id': "21_s2"},
    {'name': "5-2: Secret #3",
        'region': "5-2",
        'game_id': "21_s3"},
    {'name': "5-2: Secret #4",
        'region': "5-2",
        'game_id': "21_s4"},
    {'name': "5-2: Secret #5",
        'region': "5-2",
        'game_id': "21_s5"},
    {'name': "5-2: Don't fight the ferryman",
        'region': "5-2",
        'game_id': "21_c"},
    {'name': "5-2: Perfect Rank",
        'region': "5-2",
        'game_id': "21_p"},

    # 5-3: SHIP OF FOOLS
    {'name': "5-3: Weapon",
        'region': "5-3",
        'game_id': "22_w1"},
    {'name': "5-3: Secret #1",
        'region': "5-3",
        'game_id': "22_s1"},
    {'name': "5-3: Secret #2",
        'region': "5-3",
        'game_id': "22_s2"},
    {'name': "5-3: Secret #3",
        'region': "5-3",
        'game_id': "22_s3"},
    {'name': "5-3: Secret #4",
        'region': "5-3",
        'game_id': "22_s4"},
    {'name': "5-3: Secret #5",
        'region': "5-3",
        'game_id': "22_s5"},
    {'name': "5-3: Don't touch any water",
        'region': "5-3",
        'game_id': "22_c"},
    {'name': "5-3: Perfect Rank",
        'region': "5-3",
        'game_id': "22_p"},

    # 5-4: LEVIATHAN
    {'name': "5-4: Defeat the Leviathan",
        'region': "5-4",
        'game_id': "23_b"},
    {'name': "5-4: Reach the surface in under 10 seconds",
        'region': "5-4",
        'game_id': "23_c"},
    {'name': "5-4: Perfect Rank",
        'region': "5-4",
        'game_id': "23_p"},
    
    # 6-1: CRY FOR THE WEEPER
    {'name': "6-1: Secret #1",
        'region': "6-1",
        'game_id': "24_s1"},
    {'name': "6-1: Secret #2",
        'region': "6-1",
        'game_id': "24_s2"},
    {'name': "6-1: Secret #3",
        'region': "6-1",
        'game_id': "24_s3"},
    {'name': "6-1: Secret #4",
        'region': "6-1",
        'game_id': "24_s4"},
    {'name': "6-1: Secret #5",
        'region': "6-1",
        'game_id': "24_s5"},
    {'name': "6-1: Beat the secret encounter",
        'region': "6-1",
        'game_id': "24_c"},
    {'name': "6-1: Perfect Rank",
        'region': "6-1",
        'game_id': "24_p"},

    # 6-2: AESTHETICS OF HATE
    {'name': "6-2: Defeat Gabriel",
        'region': "6-2",
        'game_id': "25_b"},
    {'name': "6-2: Hit Gabriel into the ceiling",
        'region': "6-2",
        'game_id': "25_c"},
    {'name': "6-2: Perfect Rank",
        'region': "6-2",
        'game_id': "25_p"},

    # Shop
    {'name': "Shop: Buy Revolver Variant 1",
        'region': "shop",
        'game_id': "shop_rev2"},
    {'name': "Shop: Buy Revolver Variant 2",
        'region': "shop",
        'game_id': "shop_rev1"},
    {'name': "Shop: Buy Shotgun Variant",
        'region': "shop",
        'game_id': "shop_sho1"},
    {'name': "Shop: Buy Nailgun Variant",
        'region': "shop",
        'game_id': "shop_nai1"},
    {'name': "Shop: Buy Railcannon Variant 1",
        'region': "shop",
        'game_id': "shop_rai1"},
    {'name': "Shop: Buy Railcannon Variant 2",
        'region': "shop",
        'game_id': "shop_rai2"},
    {'name': "Shop: Buy Rocket Launcher Variant",
        'region': "shop",
        'game_id': "shop_rock1"},
]


event_table: List[LocationDict] = [
    {'name': "Cleared 0-1",
        'region': "0-1"},
    {'name': "Cleared 0-2",
        'region': "0-2"},
    {'name': "Cleared 0-3",
        'region': "0-3"},
    {'name': "Cleared 0-4",
        'region': "0-4"},
    {'name': "Cleared 0-5",
        'region': "0-5"},
    {'name': "Cleared 0-S",
        'region': "0-S"},
    {'name': "Cleared 1-1",
        'region': "1-1"},
    {'name': "Cleared 1-2",
        'region': "1-2"},
    {'name': "Cleared 1-3",
        'region': "1-3"},
    {'name': "Cleared 1-4",
        'region': "1-4"},
    {'name': "Cleared 1-S",
        'region': "1-S"},
    {'name': "Cleared 2-1",
        'region': "2-1"},
    {'name': "Cleared 2-2",
        'region': "2-2"},
    {'name': "Cleared 2-3",
        'region': "2-3"},
    {'name': "Cleared 2-4",
        'region': "2-4"},
    {'name': "Cleared 2-S",
        'region': "2-S"},
    {'name': "Cleared 3-1",
        'region': "3-1"},
    {'name': "Cleared 3-2",
        'region': "3-2"},
    {'name': "Cleared 4-1",
        'region': "4-1"},
    {'name': "Cleared 4-2",
        'region': "4-2"},
    {'name': "Cleared 4-3",
        'region': "4-3"},
    {'name': "Cleared 4-4",
        'region': "4-4"},
    {'name': "Cleared 4-S",
        'region': "4-S"},
    {'name': "Cleared 5-1",
        'region': "5-1"},
    {'name': "Cleared 5-2",
        'region': "5-2"},
    {'name': "Cleared 5-3",
        'region': "5-3"},
    {'name': "Cleared 5-4",
        'region': "5-4"},
    {'name': "Cleared 5-S",
        'region': "5-S"},
    {'name': "Cleared 6-1",
        'region': "6-1"},
    {'name': "Cleared 6-2",
        'region': "6-2"},
    {'name': "Cleared P-1",
        'region': "P-1"},
    {'name': "Cleared P-2",
        'region': "P-2"},
]


ext_bosses: Set[str] = [
    "1-2: Defeat the Very Cancerous Rodent",
    "4-3: Defeat the Mysterious Druid Knight (& Owl)"
]