from BaseClasses import ItemClassification
from typing import TypedDict, Dict, List, Set


class ItemDict(TypedDict):
    name: str
    count: int
    classification: ItemClassification
    game_id: List[str]


item_table: List[ItemDict] = [
    # Rosary Beads
    {'name': "Dove Skull",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB01"]},
    {'name': "Ember of the Holy Cremation",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB02"]},
    {'name': "Silver Grape",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB03"]},
    {'name': "Uvula of Proclamation",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB04"]},
    {'name': "Hollow Pearl",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB05"]},
    {'name': "Knot of Hair",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB06"]},
    {'name': "Painted Wood Bead",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB07"]},
    {'name': "Piece of a Golden Mask",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB08"]},
    {'name': "Moss Preserved in Glass",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB09"]},
    {'name': "Frozen Olive",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB10"]},
    {'name': "Quirce's Scorched Bead",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB11"]},
    {'name': "Wicker Knot",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB12"]},
    {'name': "Perpetva's Protection",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB13"]},
    {'name': "Thorned Symbol",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB14"]},
    {'name': "Piece of a Tombstone",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB15"]},
    {'name': "Sphere of the Sacred Smoke",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB16"]},
    {'name': "Bead of Red Wax",
        'count': 3,
        'classification': ItemClassification.progression,
        'game_id': ["RB17", "RB18", "RB19"]},
    {'name': "Little Toe made of Limestone",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RB20"]},
    {'name': "Big Toe made of Limestone",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RB21"]},
    {'name': "Fourth Toe made of Limestone",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RB22"]},
    {'name': "Bead of Blue Wax",
        'count': 3,
        'classification': ItemClassification.progression,
        'game_id': ["RB24", "RB25", "RB26"]},
    {'name': "Pelican Effigy",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB28"]},
    {'name': "Drop of Coagulated Ink",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB30"]},
    {'name': "Amber Eye",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB31"]},
    {'name': "Muted Bell",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB32"]},
    {'name': "Consecrated Amethyst",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB33"]},
    {'name': "Embers of a Broken Star",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB34"]},
    {'name': "Scaly Coin",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB35"]},
    {'name': "Seashell of the Inverted Spiral",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB36"]},
    {'name': "Calcified Eye of Erudition",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB37"]},
    {'name': "Weight of True Guilt", #RB38-41
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RB41"]},
    {'name': "Reliquary of the Fervent Heart",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB101"]},
    {'name': "Reliquary of the Suffering Heart",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB102"]},
    {'name': "Reliquary of the Sorrowful Heart",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB103"]},
    {'name': "Token of Appreciation",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB104"]},
    {'name': "Cloistered Ruby",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RB105"]},
    {'name': "Bead of Gold Thread",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB106"]},
    {'name': "Cloistered Sapphire",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB107"]},
    {'name': "Fire Enclosed in Enamel",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB108"]},
    {'name': "Light of the Lady of the Lamp",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB201"]},
    {'name': "Scale of Burnished Alabaster",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB202"]},
    {'name': "The Young Mason's Wheel",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RB203"]},
    {'name': "Crown of Gnawed Iron",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB204"]},
    {'name': "Crimson Heart of a Miura",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RB205"]},

    # Prayers
    {'name': "Seguiriya to your Eyes like Stars",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["PR01"]},
    {'name': "Debla of the Lights",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["PR03"]},
    {'name': "Saeta Dolorosa",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["PR04"]},
    {'name': "Campanillero to the Sons of the Aurora",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["PR05"]},
    {'name': "Lorquiana",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["PR07"]},
    {'name': "Zarabanda of the Safe Haven",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["PR08"]},
    {'name': "Taranto to my Sister",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["PR09"]},
    {'name': "Solea of Excommunication",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["PR10"]},
    {'name': "Tiento to your Thorned Hairs",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["PR11"]},
    {'name': "Cante Jondo of the Three Sisters",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["PR13"]},
    {'name': "Verdiales of the Forsaken Hamlet",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["PR14"]},
    {'name': "Romance to the Crimson Mist",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["PR15"]},
    {'name': "Zambra to the Resplendent Crown",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["PR16"]},
    {'name': "Aubade of the Nameless Guardian",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["PR101"]},
    {'name': "Cantina of the Blue Rose",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["PR201"]},
    {'name': "Mirabras of the Return to Port",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["PR202"]},
    {'name': "Tirana of the Celestial Bastion",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["PR203"]},

    # Relics
    {'name': "Blood Perpetuated in Sand",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RE01"]},
    {'name': "Incorrupt Hand of the Fraternal Master",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["RE02"]},
    {'name': "Nail Uprooted from Dirt",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RE03"]},
    {'name': "Shroud of Dreamt Sins",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RE04"]},
    {'name': "Linen of Golden Thread",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RE05"]},
    {'name': "Silvered Lung of Dolphos",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RE07"]},
    {'name': "Three Gnarled Tongues",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["RE10"]},

    # Mea Culpa Hearts
    {'name': "Smoking Heart of Incense",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["HE01"]},
    {'name': "Heart of the Virtuous Pain",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["HE02"]},
    {'name': "Heart of Saltpeter Blood",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["HE03"]},
    {'name': "Heart of Oils",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["HE04"]},
    {'name': "Heart of Cerulean Incense",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["HE05"]},
    {'name': "Heart of the Holy Purge",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["HE06"]},
    {'name': "Molten Heart of Boiling Blood",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["HE07"]},
    {'name': "Heart of the Single Tone",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["HE10"]},
    {'name': "Heart of the Unnamed Minstrel",
        'count': 1,
        'classification': ItemClassification.useful,
        'game_id': ["HE11"]},
    {'name': "Brilliant Heart of Dawn",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["HE101"]},
    {'name': "Apodictic Heart of Mea Culpa",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["HE201"]},

    # Quest Items
    {'name': "Cord of the True Burying",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI01"]},
    {'name': "Mark of the First Refuge",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI02"]},
    {'name': "Mark of the Second Refuge",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI03"]},
    {'name': "Mark of the Third Refuge",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI04"]},
    {'name': "Tentudia's Carnal Remains",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI06"]},
    {'name': "Remains of Tentudia's Hair",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI07"]},
    {'name': "Tentudia's Skeletal Remains",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI08"]},
    {'name': "Melted Golden Coins",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI10"]},
    {'name': "Torn Bridal Ribbon",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI11"]},
    {'name': "Black Grieving Veil",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI12"]},
    {'name': "Egg of Deformity",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI13"]},
    {'name': "Hatched Egg of Deformity",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI14"]},
    {'name': "Bouquet of Rosemary",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI19"]},
    {'name': "Incense Garlic",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI20"]},
    {'name': "Thorn", #QI31-35, QI79-81
        'count': 8,
        'classification': ItemClassification.progression,
        'game_id': ["QI31", "QI32", "QI33", "QI34", "QI35", "QI79", "QI80", "QI81"]},
    {'name': "Olive Seeds",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI37"]},
    {'name': "Holy Wound of Attrition",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI38"]},
    {'name': "Holy Wound of Contrition",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI39"]},
    {'name': "Holy Wound of Compunction",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI40"]},
    {'name': "Empty Bile Vessel", #QI41, QI45-51
        'count': 8,
        'classification': ItemClassification.progression,
        'game_id': ["QI41", "QI45", "QI46", "QI47", "QI48", "QI49", "QI50", "QI51"]},
    {'name': "Knot of Rosary Rope", #QI44, QI52-56
        'count': 6,
        'classification': ItemClassification.progression,
        'game_id': ["QI44", "QI52", "QI53", "QI54", "QI55", "QI56"]},
    {'name': "Golden Thimble Filled with Burning Oil",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI57"]},
    {'name': "Key to the Chamber of the Eldest Brother",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI58"]},
    {'name': "Empty Golden Thimble",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI59"]},
    {'name': "Deformed Mask of Orestes",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI60"]},
    {'name': "Mirrored Mask of Dolphos",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI61"]},
    {'name': "Embossed Mask of Crescente",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI62"]},
    {'name': "Dried Clove",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI63"]},
    {'name': "Sooty Garlic",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI64"]},
    {'name': "Bouquet of Thyme",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI65"]},
    {'name': "Linen Cloth",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI66"]},
    {'name': "Severed Hand",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI67"]},
    {'name': "Dried Flowers bathed in Tears",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI68"]},
    {'name': "Key of the Secular",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI69"]},
    {'name': "Key of the Scribe",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI70"]},
    {'name': "Key of the Inquisitor",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI71"]},
    {'name': "Key of the High Peaks",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI72"]},
    {'name': "Chalice of Inverted Verses",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI75"]},
    {'name': "Quicksilver", #QI101-105
        'count': 5,
        'classification': ItemClassification.useful,
        'game_id': ["QI101", "QI102", "QI103", "QI104", "QI105"]},
    {'name': "Petrified Bell",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI106"]},
    {'name': "Verses Spun from Gold", #QI107-110
        'count': 4,
        'classification': ItemClassification.progression,
        'game_id': ["QI107", "QI108", "QI109", "QI110"]},
    {'name': "Severed Right Eye of the Traitor",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI201"]},
    {'name': "Broken Left Eye of the Traitor",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI202"]},
    {'name': "Incomplete Scapular",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI203"]},
    {'name': "Key Grown from Twisted Wood",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI204"]},
    {'name': "Holy Wound of Abnegation",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["QI301"]},

    # Collectibles
    {'name': "Parietal Bone of Lasser, the Inquisitor",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO01"]},
    {'name': "Jaw of Ashgan, the Inquisitor",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO02"]},
    {'name': "Cervical vertebra of Zicher, the Brewmaster",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO03"]},
    {'name': "Clavicle of Dalhuisen, the Schoolchild",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO04"]},
    {'name': "Sternum of Vitas, the Performer",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO05"]},
    {'name': "Ribs of Sabnock, the Guardian",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO06"]},
    {'name': "Vertebra of John, the Gambler",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO07"]},
    {'name': "Scapula of Carlos, the Executioner",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO08"]},
    {'name': "Humerus of McMittens, the Nurse",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO09"]},
    {'name': "Ulna of Koke, the Troubadour",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO10"]},
    {'name': "Radius of Helzer, the Poet",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO11"]},
    {'name': "Frontal of Martinus, the Ropemaker",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO12"]},
    {'name': "Metacarpus of Hodges, the Blacksmith",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO13"]},
    {'name': "Phalanx of Arthur, the Sailor",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO14"]},
    {'name': "Phalanx of Miriam, the Consellor",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO15"]},
    {'name': "Phalanx of Brannon, the Gravedigger",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO16"]},
    {'name': "Coxal of June, the Prostitute",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO17"]},
    {'name': "Sacrum of the Dark Warlock",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO18"]},
    {'name': "Coccyx of Daniel, the Possessed",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO19"]},
    {'name': "Femur of Karpow, the Bounty Hunter",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO20"]},
    {'name': "Kneecap of Sebastien, the Puppeteer",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO21"]},
    {'name': "Tibia of Alsahli, the Mystic",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO22"]},
    {'name': "Fibula of Rysp, the Ranger",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO23"]},
    {'name': "Temporal of Joel, the Thief",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO24"]},
    {'name': "Metatarsus of Rikusyo, the Traveller",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO25"]},
    {'name': "Phalanx of Zeth, the Prisoner",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO26"]},
    {'name': "Phalanx of William, the Sceptic",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO27"]},
    {'name': "Phalanx of Aralcarim, the Archivist",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO28"]},
    {'name': "Occipital of Tequila, the Metalsmith",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO29"]},
    {'name': "Maxilla of Tarradax, the Cleric",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO30"]},
    {'name': "Nasal bone of Charles, the Artist",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO31"]},
    {'name': "Hyoid bone of Senex, the Beggar",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO32"]},
    {'name': "Vertebra of Lindquist, the Forger",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO33"]},
    {'name': "Trapezium of Jeremiah, the Hangman",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO34"]},
    {'name': "Trapezoid of Yeager, the Jeweller",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO35"]},
    {'name': "Capitate of Barock, the Herald",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO36"]},
    {'name': "Hamate of Vukelich, the Copyist",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO37"]},
    {'name': "Pisiform of Hernandez, the Explorer",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO38"]},
    {'name': "Triquetral of Luca, the Tailor",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO39"]},
    {'name': "Lunate of Keiya, the Butcher",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO40"]},
    {'name': "Scaphoid of Fiece, the Leper",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO41"]},
    {'name': "Anklebone of Weston, the Pilgrim",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO42"]},
    {'name': "Calcaneum of Persian, the Bandit",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO43"]},
    {'name': "Navicular of Kahnnyhoo, the Murderer",
        'count': 1,
        'classification': ItemClassification.progression,
        'game_id': ["CO44"]},

    # Other
    {'name': "Child of Moonlight",
        'count': 38,
        'classification': ItemClassification.progression,
        'game_id': ["CH"]},
    {'name': "Life Upgrade",
        'count': 6,
        'classification': ItemClassification.progression,
        'game_id': ["LU"]},
    {'name': "Fervour Upgrade",
        'count': 6,
        'classification': ItemClassification.progression,
        'game_id': ["FU"]},
    {'name': "Mea Culpa Upgrade",
        'count': 7,
        'classification': ItemClassification.progression,
        'game_id': ["SU"]},
    {'name': "Tears of Atonement (250)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[250]"]},
    {'name': "Tears of Atonement (300)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[300]"]},
    {'name': "Tears of Atonement (500)",
        'count': 3,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[500]"]},
    {'name': "Tears of Atonement (625)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[625]"]},
    {'name': "Tears of Atonement (750)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[750]"]},
    {'name': "Tears of Atonement (1000)",
        'count': 4,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[1000]"]},
    {'name': "Tears of Atonement (1250)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[1250]"]},
    {'name': "Tears of Atonement (1500)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[1500]"]},
    {'name': "Tears of Atonement (1750)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[1750]"]},
    {'name': "Tears of Atonement (2000)",
        'count': 2,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[2000]"]},
    {'name': "Tears of Atonement (2100)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[2100]"]},
    {'name': "Tears of Atonement (2500)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[2500]"]},
    {'name': "Tears of Atonement (2600)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[2600]"]},
    {'name': "Tears of Atonement (3000)",
        'count': 2,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[3000]"]},
    {'name': "Tears of Atonement (4300)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[4300]"]},
    {'name': "Tears of Atonement (5000)",
        'count': 4,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[5000]"]},
    {'name': "Tears of Atonement (5500)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[5500]"]},
    {'name': "Tears of Atonement (9000)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[9000]"]},
    {'name': "Tears of Atonement (10000)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[10000]"]},
    {'name': "Tears of Atonement (11250)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[11250]"]},
    {'name': "Tears of Atonement (18000)",
        'count': 5,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[18000]"]},
    {'name': "Tears of Atonement (30000)",
        'count': 1,
        'classification': ItemClassification.filler,
        'game_id': ["Tears[30000]"]},
]

group_table: Dict[str, Set[str]] = {
    "wounds"  : ["Holy Wound of Attrition",
                 "Holy Wound of Contrition",
                 "Holy Wound of Compunction"],

    "masks"   : ["Deformed Mask of Orestes",
                 "Mirrored Mask of Dolphos",
                 "Embossed Mask of Crescente"],

    "tirso"   : ["Bouquet of Rosemary",
                 "Incense Garlic",
                 "Olive Seeds",
                 "Dried Clove",
                 "Sooty Garlic",
                 "Bouquet of Thyme"],

    "tentudia": ["Tentudia's Carnal Remains",
                 "Remains of Tentudia's Hair",
                 "Tentudia's Skeletal Remains"],

    "egg"     : ["Melted Golden Coins",
                 "Torn Bridal Ribbon",
                 "Black Grieving Veil"],

    "bones"   : ["Parietal Bone of Lasser, the Inquisitor",
                 "Jaw of Ashgan, the Inquisitor",
                 "Cervical vertebra of Zicher, the Brewmaster",
                 "Clavicle of Dalhuisen, the Schoolchild",
                 "Sternum of Vitas, the Performer",
                 "Ribs of Sabnock, the Guardian",
                 "Vertebra of John, the Gambler",
                 "Scapula of Carlos, the Executioner",
                 "Humerus of McMittens, the Nurse",
                 "Ulna of Koke, the Troubadour",
                 "Radius of Helzer, the Poet",
                 "Frontal of Martinus, the Ropemaker",
                 "Metacarpus of Hodges, the Blacksmith",
                 "Phalanx of Arthur, the Sailor",
                 "Phalanx of Miriam, the Consellor",
                 "Phalanx of Brannon, the Gravedigger",
                 "Coxal of June, the Prostitute",
                 "Sacrum of the Dark Warlock",
                 "Coccyx of Daniel, the Possessed",
                 "Femur of Karpow, the Bounty Hunter",
                 "Kneecap of Sebastien, the Puppeteer",
                 "Tibia of Alsahli, the Mystic",
                 "Fibula of Rysp, the Ranger",
                 "Temporal of Joel, the Thief",
                 "Metatarsus of Rikusyo, the Traveller",
                 "Phalanx of Zeth, the Prisoner", 
                 "Phalanx of William, the Sceptic",
                 "Phalanx of Aralcarim, the Archivist",
                 "Occipital of Tequila, the Metalsmith",
                 "Maxilla of Tarradax, the Cleric",
                 "Nasal bone of Charles, the Artist",
                 "Hyoid bone of Senex, the Beggar",
                 "Vertebra of Lindquist, the Forger",
                 "Trapezium of Jeremiah, the Hangman",
                 "Trapezoid of Yeager, the Jeweller",
                 "Capitate of Barock, the Herald",
                 "Hamate of Vukelich, the Copyist",
                 "Pisiform of Hernandez, the Explorer",
                 "Triquetral of Luca, the Tailor",
                 "Lunate of Keiya, the Butcher",
                 "Scaphoid of Fiece, the Leper",
                 "Anklebone of Weston, the Pilgrim",
                 "Calcaneum of Persian, the Bandit",
                 "Navicular of Kahnnyhoo, the Murderer"],
    
    "power"   : ["Life Upgrade",
                 "Fervour Upgrade",
                 "Mea Culpa Upgrade",
                 "Empty Bile Vessel",
                 "Quicksilver"]
}

tears_set: Set[str] = [
    "Tears of Atonement (250)",
    "Tears of Atonement (300)",
    "Tears of Atonement (500)",
    "Tears of Atonement (625)",
    "Tears of Atonement (750)",
    "Tears of Atonement (1000)",
    "Tears of Atonement (1250)",
    "Tears of Atonement (1500)",
    "Tears of Atonement (1750)",
    "Tears of Atonement (2000)",
    "Tears of Atonement (2100)",
    "Tears of Atonement (2500)",
    "Tears of Atonement (2600)",
    "Tears of Atonement (3000)",
    "Tears of Atonement (4300)",
    "Tears of Atonement (5000)",
    "Tears of Atonement (5500)",
    "Tears of Atonement (9000)",
    "Tears of Atonement (10000)",
    "Tears of Atonement (11250)",
    "Tears of Atonement (18000)",
    "Tears of Atonement (30000)"
]