from typing import Dict, TypedDict


class LocationDict(TypedDict):
    name: str
    region: str


location_table: Dict[int, LocationDict] = {
    # Albero (35)
    1909000: {'name': "Albero: Sick house",
              'region': "albero"},
    1909001: {'name': "Albero: Outside ossuary",
              'region': "albero"},
    1909002: {'name': "Albero: Graveyard",
              'region': "albero"},
    1909003: {'name': "Albero: Warp room",
              'region': "albero"},
    1909004: {'name': "Albero: Elevator cherub",
              'region': "albero"},
    1909005: {'name': "Lake of Silent Pilgrims: Bless cloth",
              'region': "albero"},
    1909006: {'name': "Lake of Silent Pilgrims: Bless egg",
              'region': "albero"},
    1909007: {'name': "Lake of Silent Pilgrims: Bless hand",
              'region': "albero"},
    1909008: {'name': "Albero: Cleofas gift initial",
              'region': "albero"},
    1909009: {'name': "Albero: Cleofas gift final",
              'region': "albero"},
    1909010: {'name': "Albero: Tirso reward 1",
              'region': "albero"},
    1909011: {'name': "Albero: Tirso reward 2",
              'region': "albero"},
    1909012: {'name': "Albero: Tirso reward 3",
              'region': "albero"},
    1909013: {'name': "Albero: Tirso reward 4",
              'region': "albero"},
    1909014: {'name': "Albero: Tirso reward 5",
              'region': "albero"},
    1909015: {'name': "Albero: Tirso reward 6",
              'region': "albero"},
    1909016: {'name': "Albero: Tirso reward final",
              'region': "albero"},
    1909017: {'name': "Albero: Tentudia reward 1",
              'region': "albero"},
    1909019: {'name': "Albero: Tentudia reward 2",
              'region': "albero"},
    1909020: {'name': "Albero: Tentudia reward 3",
              'region': "albero"},
    1909021: {'name': "Ossuary: Isidora reward main",
              'region': "albero"},
    1909022: {'name': "Albero: Sword room",
              'region': "albero"},
    1909023: {'name': "Albero: Church donation 1",
              'region': "albero"},
    1909024: {'name': "Albero: Church donation 2",
              'region': "albero"},
    1909025: {'name': "Ossuary: Reward 1",
              'region': "albero"},
    1909026: {'name': "Ossuary: Reward 2",
              'region': "albero"},
    1909027: {'name': "Ossuary: Reward 3",
              'region': "albero"},
    1909028: {'name': "Ossuary: Reward 4",
              'region': "albero"},
    1909029: {'name': "Ossuary: Reward 5",
              'region': "albero"},
    1909030: {'name': "Ossuary: Reward 6",
              'region': "albero"},
    1909031: {'name': "Ossuary: Reward 7",
              'region': "albero"},
    1909032: {'name': "Ossuary: Reward 8",
              'region': "albero"},
    1909033: {'name': "Ossuary: Reward 9",
              'region': "albero"},
    1909034: {'name': "Ossuary: Reward 10",
              'region': "albero"},
    1909035: {'name': "Ossuary: Reward 11",
              'region': "albero"},
    
    # All the Tears of the Sea (1)
    1909036: {'name': "AtTotS: Miriam gift",
              'region': "attots"},

    # Archcathedral Rooftops (11)
    1909037: {'name': "AR: Bridge fight 1",
              'region': "ar"},
    1909038: {'name': "AR: Bridge fight 2",
              'region': "ar"},
    1909039: {'name': "AR: Bridge fight 3",
              'region': "ar"},
    1909040: {'name': "AR: Western shaft ledge",
              'region': "ar"},
    1909041: {'name': "AR: Western shaft cherub",
              'region': "ar"},
    1909042: {'name': "AR: Western shaft chest",
              'region': "ar"},
    1909043: {'name': "AR: MoM east entrance",
              'region': "ar"},
    1909044: {'name': "AR: Lady room",
              'region': "ar"},
    1909045: {'name': "AR: Second checkpoint ledge",
              'region': "ar"},
    1909046: {'name': "AR: Sword room",
              'region': "ar"},
    1909047: {'name': "AR: Crisanta",
              'region': "ar"},

    # Bridge of the Three Cavalries (3)
    1909048: {'name': "BotTC: Esdras",
              'region': "bottc"},
    1909049: {'name': "BotTC: Esdras gift initial",
              'region': "bottc"},
    1909050: {'name': "BotTC: Amanecida core",
              'region': "bottc"},

    # Brotherhood of the Silent Sorrow (11)
    1909051: {'name': "BotSS: Beginning gift",
              'region': "botss"},
    1909052: {'name': "BotSS: Initial room cherub",
              'region': "botss"},
    1909053: {'name': "BotSS: Initial room ledge",
              'region': "botss"},
    1909054: {'name': "BotSS: Elder Brother's room",
              'region': "botss"},
    1909055: {'name': "BotSS: Sword room",
              'region': "botss"},
    1909056: {'name': "BotSS: Spike gauntlet exit",
              'region': "botss"},
    1909057: {'name': "BotSS: Blue candle",
              'region': "botss"},
    1909058: {'name': "BotSS: Church entrance",
              'region': "botss"},
    1909059: {'name': "BotSS: Esdras gift final",
              'region': "botss"},
    1909060: {'name': "BotSS: Crisanta gift",
              'region': "botss"},
    1909061: {'name': "BotSS: Warden of the Silent Sorrow",
              'region': "botss"},
    
    # Convent of Our Lady of the Charred Visage (13)
    1909062: {'name': "CoOLotCV: Blood platform ledge",
              'region': "coolotcv"},
    1909063: {'name': "CoOLotCV: Ghost death room",
              'region': "coolotcv"},
    1909064: {'name': "CoOLotCV: Central lung room",
              'region': "coolotcv"},
    1909065: {'name': "CoOLotCV: Southwest lung room",
              'region': "coolotcv"},
    1909066: {'name': "CoOLotCV: Lady room",
              'region': "coolotcv"},
    1909067: {'name': "CoOLotCV: Sword room",
              'region': "coolotcv"},
    1909068: {'name': "CoOLotCV: Red candle",
              'region': "coolotcv"},
    1909069: {'name': "CoOLotCV: Blue candle",
              'region': "coolotcv"},
    1909070: {'name': "CoOLotCV: Outside area",
              'region': "coolotcv"},
    1909071: {'name': "CoOLotCV: Burning oil fountain",
              'region': "coolotcv"},
    1909072: {'name': "CoOLotCV: Our Lady of the Charred Visage",
              'region': "coolotcv"},
    1909073: {'name': "CoOLotCV: Holy Visage gift",
              'region': "coolotcv"},
    1909074: {'name': "CoOLotCV: Mask room",
              'region': "coolotcv"},

    # Deambulatory of His Holiness (3)
    1909075: {'name': "DoHH: Complete Penitence 1",
              'region': "dohh"},
    1909076: {'name': "DoHH: Complete Penitence 2",
              'region': "dohh"},
    1909077: {'name': "DoHH: Complete Penitence 3",
              'region': "dohh"},

    # Desecrated Cistern (20)
    1909078: {'name': "DC: MeD lady room",
              'region': "dc"},
    1909079: {'name': "DC: MeD entrance",
              'region': "dc"},
    1909080: {'name': "DC: Water room cherub",
              'region': "dc"},
    1909081: {'name': "DC: Eastern lower tunnel chest",
              'region': "dc"},
    1909082: {'name': "DC: Eastern upper tunnel chest",
              'region': "dc"},
    1909083: {'name': "DC: Eastern upper tunnel cherub",
              'region': "dc"},
    1909084: {'name': "DC: Hidden hand room",
              'region': "dc"},
    1909085: {'name': "DC: WaBC entrance",
              'region': "dc"},
    1909086: {'name': "DC: Oil room",
              'region': "dc"},
    1909087: {'name': "DC: Veil room cherub",
              'region': "dc"},
    1909088: {'name': "DC: Veil room ledge",
              'region': "dc"},
    1909089: {'name': "DC: Lung tunnel cherub",
              'region': "dc"},
    1909090: {'name': "DC: Lung tunnel ledge",
              'region': "dc"},
    1909091: {'name': "DC: Shroud puzzle",
              'region': "dc"},
    1909092: {'name': "DC: Chalice room",
              'region': "dc"},
    1909093: {'name': "DC: Sword room",
              'region': "dc"},
    1909094: {'name': "DC: GrA lady room",
              'region': "dc"},
    1909095: {'name': "DC: Elevator exit cherub",
              'region': "dc"},
    1909096: {'name': "DC: Elevator shaft cherub",
              'region': "dc"},
    1909097: {'name': "DC: Elevator shaft ledge",
              'region': "dc"},

    # Echoes of Salt (2)
    1909098: {'name': "EoS: MoED entrance",
              'region': "eos"},
    1909099: {'name': "EoS: Near elevator shaft",
              'region': "eos"},
    
    # Graveyard of the Peaks (21)
    1909100: {'name': "GotP: Shop cave cherub",
              'region': "gotp"},
    1909101: {'name': "GotP: Shop cave hole",
              'region': "gotp"},
    1909102: {'name': "GotP: Shop left",
              'region': "gotp"},
    1909103: {'name': "GotP: Shop middle",
              'region': "gotp"},
    1909104: {'name': "GotP: Shop right",
              'region': "gotp"},
    1909105: {'name': "GotP: Guilt room",
              'region': "gotp"},
    1909106: {'name': "GotP: Elevator shaft cherub",
              'region': "gotp"},
    1909107: {'name': "GotP: Elevator shaft ledge",
              'region': "gotp"},
    1909108: {'name': "GotP: Lady room",
              'region': "gotp"},
    1909109: {'name': "GotP: Bleed room",
              'region': "gotp"},
    1909110: {'name': "GotP: Eastern shaft lower",
              'region': "gotp"},
    1909111: {'name': "GotP: Eastern shaft middle",
              'region': "gotp"},
    1909112: {'name': "GotP: Eastern shaft upper",
              'region': "gotp"},
    1909113: {'name': "GotP: Amanecida ledge",
              'region': "gotp"},
    1909114: {'name': "GotP: Western shaft cherub",
              'region': "gotp"},
    1909115: {'name': "GotP: Western shaft lower",
              'region': "gotp"},
    1909116: {'name': "GotP: Western shaft middle",
              'region': "gotp"},
    1909117: {'name': "GotP: Western shaft upper",
              'region': "gotp"},
    1909118: {'name': "GotP: Center shaft cherub",
              'region': "gotp"},
    1909119: {'name': "GotP: Center shaft ledge",
              'region': "gotp"},
    1909120: {'name': "GotP: Oil room",
              'region': "gotp"},
    1909121: {'name': "GotP: Bow Amanecida",
              'region': "gotp"},
    
    # Grievance Ascends (12)
    1909122: {'name': "GA: Western lung ledge",
              'region': "ga"},
    1909123: {'name': "GA: Lung room upper",
              'region': "ga"},
    1909124: {'name': "GA: Lung room cherub",
              'region': "ga"},
    1909125: {'name': "GA: Lung room lower",
              'region': "ga"},
    1909126: {'name': "GA: Oil room",
              'region': "ga"},
    1909127: {'name': "GA: Blood tunnel ledge",
              'region': "ga"},
    1909128: {'name': "GA: Blood tunnel cherub",
              'region': "ga"},
    1909129: {'name': "GA: Altasgracias cherub",
              'region': "ga"},
    1909130: {'name': "GA: Altasgracias gift",
              'region': "ga"},
    1909131: {'name': "GA: Altasgracias cocoon",
              'region': "ga"},
    1909132: {'name': "GA: Tres Angustias",
              'region': "ga"},
    1909133: {'name': "GA: Holy Visage gift",
              'region': "ga"},
    
    # Hall of the Dawning (2)
    1909134: {'name': "HotD: Mirror room",
              'region': "hotd"},
    1909135: {'name': "HotD: Laudes",
              'region': "hotd"},
    
    # Jondo (13)
    1909136: {'name': "Jondo: Eastern entrance ledge",
              'region': "jondo"},
    1909137: {'name': "Jondo: Eastern entrance chest",
              'region': "jondo"},
    1909138: {'name': "Jondo: Eastern shaft bell chargers",
              'region': "jondo"},
    1909139: {'name': "Jondo: Eastern shaft bell trap",
              'region': "jondo"},
    1909140: {'name': "Jondo: Eastern shaft cherub",
              'region': "jondo"},
    1909141: {'name': "Jondo: Spike tunnel cherub",
              'region': "jondo"},
    1909142: {'name': "Jondo: Spike tunnel ledge",
              'region': "jondo"},
    1909143: {'name': "Jondo: EcS entrance",
              'region': "jondo"},
    1909144: {'name': "Jondo: Western shaft lower slide",
              'region': "jondo"},
    1909145: {'name': "Jondo: Western shaft bell trap",
              'region': "jondo"},
    1909146: {'name': "Jondo: Western shaft bell puzzle",
              'region': "jondo"},
    1909147: {'name': "Jondo: Western shaft root puzzle",
              'region': "jondo"},
    1909148: {'name': "Jondo: Western shaft cherub",
              'region': "jondo"},
    
    # Knot of the Three Words (1)
    1909149: {'name': "KotTW: Fourth Visage gift",
              'region': "kottw"},
    
    # Library of the Negated Words (18)
    1909150: {'name': "LotNW: Platform room cherub",
              'region': "lotnw"},
    1909151: {'name': "LotNW: Platform room ledge",
              'region': "lotnw"},
    1909152: {'name': "LotNW: Upper cathedral ledge",
              'region': "lotnw"},
    1909153: {'name': "LotNW: Hidden floor",
              'region': "lotnw"},
    1909154: {'name': "LotNW: Lung ambush chest",
              'region': "lotnw"},
    1909155: {'name': "LotNW: Lady room",
              'region': "lotnw"},
    1909156: {'name': "LotNW: Bone puzzle",
              'region': "lotnw"},
    1909157: {'name': "LotNW: Diosdado ledge",
              'region': "lotnw"},
    1909158: {'name': "LotNW: Platform puzzle chest",
              'region': "lotnw"},
    1909159: {'name': "LotNW: Final shaft ledge",
              'region': "lotnw"},
    1909160: {'name': "LotNW: Final shaft cherub",
              'region': "lotnw"},
    1909161: {'name': "LotNW: Oil room",
              'region': "lotnw"},
    1909162: {'name': "LotNW: Elevator cherub",
              'region': "lotnw"},
    1909163: {'name': "LotNW: Mask room",
              'region': "lotnw"},
    1909164: {'name': "LotNW: Sword room",
              'region': "lotnw"},
    1909165: {'name': "LotNW: Red candle",
              'region': "lotnw"},
    1909166: {'name': "LotNW: Diosdado gift",
              'region': "lotnw"},
    1909167: {'name': "LotNW: Fourth Visage hidden wall",
              'region': "lotnw"},

    # Mercy Dreams (15)
    1909168: {'name': "MD: First section hidden wall",
              'region': "md"},
    1909169: {'name': "MD: Second section ghost ambush",
              'region': "md"},
    1909170: {'name': "MD: Second section ledge",
              'region': "md"},
    1909171: {'name': "MD: Second section cherub",
              'region': "md"},
    1909172: {'name': "MD: Red candle",
              'region': "md"},
    1909173: {'name': "MD: Shop left",
              'region': "md"},
    1909174: {'name': "MD: Shop middle",
              'region': "md"},
    1909175: {'name': "MD: Shop right",
              'region': "md"},
    1909176: {'name': "MD: Third section hidden wall",
              'region': "md"},
    1909177: {'name': "MD: Third section lower corridor",
              'region': "md"},
    1909178: {'name': "MD: Ten Piedad",
              'region': "md"},
    1909179: {'name': "MD: Holy Visage gift",
              'region': "md"},
    1909180: {'name': "MD: Blue candle",
              'region': "md"},
    1909181: {'name': "MD: SlC entrance cherub",
              'region': "md"},
    1909182: {'name': "MD: SlC entrance ledge",
              'region': "md"},

    # Mother of Mothers (14)
    1909183: {'name': "MoM: Oil room",
              'region': "mom"},
    1909184: {'name': "MoM: Eastern room upper",
              'region': "mom"},
    1909185: {'name': "MoM: Eastern room lower",
              'region': "mom"},
    1909186: {'name': "MoM: Western room cherub",
              'region': "mom"},
    1909187: {'name': "MoM: Western room ledge",
              'region': "mom"},
    1909188: {'name': "MoM: Redento prayer room",
              'region': "mom"},
    1909189: {'name': "MoM: Redento corpse",
              'region': "mom"},
    1909190: {'name': "MoM: Blood incense shaft",
              'region': "mom"},
    1909191: {'name': "MoM: Outside Cleofas room",
              'region': "mom"},
    1909192: {'name': "MoM: Center room ledge",
              'region': "mom"},
    1909193: {'name': "MoM: Center room cherub",
              'region': "mom"},
    1909194: {'name': "MoM: Sword room",
              'region': "mom"},
    1909195: {'name': "MoM: Melquiades",
              'region': "mom"},
    1909196: {'name': "MoM: Mask room",
              'region': "mom"},

    # Mountains of the Endless Dusk (8)
    1909197: {'name': "MotED: DeC entrance",
              'region': "moted"},
    1909198: {'name': "MotED: Petpetua gift",
              'region': "moted"},
    1909199: {'name': "MotED: Bell gap cherub",
              'region': "moted"},
    1909200: {'name': "MotED: Bell gap ledge",
              'region': "moted"},
    1909201: {'name': "MotED: Redento meeting 1",
              'region': "moted"},
    1909202: {'name': "MotED: Blood platform",
              'region': "moted"},
    1909203: {'name': "MotED: Egg hatching",
              'region': "moted"},
    1909204: {'name': "MotED: Axe Amanecida",
              'region': "moted"},

    # Mourning and Havoc (4)
    1909205: {'name': "MaH: Western chest",
              'region': "mah"},
    1909206: {'name': "MaH: Eastern chest",
              'region': "mah"},
    1909207: {'name': "MaH: Sierpes reward",
              'region': "mah"},
    1909208: {'name': "MaH: Sierpes",
              'region': "mah"},
    
    # Patio of the Silent Steps (9)
    1909209: {'name': "PotSS: Garden 1 cherub",
              'region': "potss"},
    1909210: {'name': "PotSS: Garden 1 ledge",
              'region': "potss"},
    1909211: {'name': "PotSS: Garden 2 ledge",
              'region': "potss"},
    1909212: {'name': "PotSS: Garden 3 cherub",
              'region': "potss"},
    1909213: {'name': "PotSS: Garden 3 lower ledge",
              'region': "potss"},
    1909214: {'name': "PotSS: Garden 3 upper ledge",
              'region': "potss"},
    1909215: {'name': "PotSS: Northern shaft",
              'region': "potss"},
    1909216: {'name': "PotSS: Redento meeting 4",
              'region': "potss"},
    1909217: {'name': "PotSS: Falcata Amanecida",
              'region': "potss"},

    # Petrous (1)
    1909218: {'name': "Petrous: Entrance room",
              'region': "petrous"},

    # The Resting Place of the Sister (1)
    1909219: {'name': "TRPotS: Perpetua shrine",
              'region': "trpots"},
    
    # The Sleeping Canvases (10)
    1909220: {'name': "TSC: Herb shaft",
              'region': "tsc"},
    1909221: {'name': "TSC: Wax bleed puzzle",
              'region': "tsc"},
    1909222: {'name': "TSC: Shop left",
              'region': "tsc"},
    1909223: {'name': "TSC: Shop middle",
              'region': "tsc"},
    1909224: {'name': "TSC: Shop right",
              'region': "tsc"},
    1909225: {'name': "TSC: Low tunnel blade trap",
              'region': "tsc"},
    1909226: {'name': "TSC: Exposito",
              'region': "tsc"},
    1909227: {'name': "TSC: Linen drop room",
              'region': "tsc"},
    1909228: {'name': "TSC: Jocinero gift initial",
              'region': "tsc"},
    1909229: {'name': "TSC: Jocinero gift final",
              'region': "tsc"},

    # The Holy Line (6)
    1909230: {'name': "THL: Deosgracias gift",
              'region': "thl"},
    1909231: {'name': "THL: Mud ledge lower",
              'region': "thl"},
    1909232: {'name': "THL: Mud ledge upper",
              'region': "thl"},
    1909233: {'name': "THL: Mud cherub",
              'region': "thl"},
    1909234: {'name': "THL: Cave ledge",
              'region': "thl"},
    1909235: {'name': "THL: Cave chest",
              'region': "thl"},

    # Wall of the Holy Prohibitions (19)
    1909236: {'name': "WotHP: Q1 lift puzzle",
              'region': "wothp"},
    1909237: {'name': "WotHP: Q1 drop room upper",
              'region': "wothp"},
    1909238: {'name': "WotHP: Q1 drop room lower",
              'region': "wothp"},
    1909239: {'name': "WotHP: Q1 upper bronze door",
              'region': "wothp"},
    1909240: {'name': "WotHP: Q1 upper silver door",
              'region': "wothp"},
    1909241: {'name': "WotHP: Q1 middle gold door",
              'region': "wothp"},
    1909242: {'name': "WotHP: Q2 middle gold door",
              'region': "wothp"},
    1909243: {'name': "WotHP: Q3 lower gold door",
              'region': "wothp"},
    1909244: {'name': "WotHP: Q3 upper silver door",
              'region': "wothp"},
    1909245: {'name': "WotHP: Q3 upper ledge",
              'region': "wothp"},
    1909246: {'name': "WotHP: Q4 hidden ledge",
              'region': "wothp"},
    1909247: {'name': "WotHP: Q4 lower silver door",
              'region': "wothp"},
    1909248: {'name': "WotHP: Q4 upper bronze door",
              'region': "wothp"},
    1909249: {'name': "WotHP: Q4 upper silver door",
              'region': "wothp"},
    1909250: {'name': "WotHP: CoLCV entrance",
              'region': "wothp"},
    1909251: {'name': "WotHP: Oil room",
              'region': "wothp"},
    1909252: {'name': "WotHP: Quirce",
              'region': "wothp"},
    1909253: {'name': "WotHP: Quirce room",
              'region': "wothp"},
    1909254: {'name': "WotHP: Lance Amanecida",
              'region': "wothp"},

    # Wasteland of the Buried Churches (8)
    1909255: {'name': "WotBC: Lower tree path",
              'region': "wotbc"},
    1909256: {'name': "WotBC: Building slide",
              'region': "wotbc"},
    1909257: {'name': "WotBC: Exterior ledge",
              'region': "wotbc"},
    1909258: {'name': "WotBC: Exterior cherub",
              'region': "wotbc"},
    1909259: {'name': "WotBC: Underneath MeD bridge",
              'region': "wotbc"},
    1909260: {'name': "WotBC: Cliffside ledge",
              'region': "wotbc"},
    1909261: {'name': "WotBC: Cliffside cherub",
              'region': "wotbc"},
    1909262: {'name': "WotBC: Redento meeting 3",
              'region': "wotbc"},
    
    # Where Olive Trees Wither (11)
    1909263: {'name': "WOTW: WaBC entrance",
              'region': "wotw"},
    1909264: {'name': "WOTW: Healing cave",
              'region': "wotw"},
    1909265: {'name': "WOTW: White lady flower",
              'region': "wotw"},
    1909266: {'name': "WOTW: White lady tomb",
              'region': "wotw"},
    1909267: {'name': "WOTW: White lady cave cherub",
              'region': "wotw"},
    1909268: {'name': "WOTW: White lady cave ledge",
              'region': "wotw"},
    1909269: {'name': "WOTW: Eastern root cherub",
              'region': "wotw"},
    1909270: {'name': "WOTW: Eastern root ledge",
              'region': "wotw"},
    1909271: {'name': "WOTW: Death run",
              'region': "wotw"},
    1909272: {'name': "WOTW: Gemino gift initial",
              'region': "wotw"},
    1909273: {'name': "WOTW: Gemino gift final",
              'region': "wotw"},

    # Various (20)
    1909274: {'name': "Guilt arena 1 extra",
              'region': "dungeon"},
    1909275: {'name': "Guilt arena 1 main",
              'region': "dungeon"},
    1909276: {'name': "Guilt arena 2 extra",
              'region': "dungeon"},
    1909277: {'name': "Guilt arena 2 main",
              'region': "dungeon"},
    1909278: {'name': "Guilt arena 3 extra",
              'region': "dungeon"},
    1909279: {'name': "Guilt arena 3 main",
              'region': "dungeon"},
    1909280: {'name': "Guilt arena 4 extra",
              'region': "dungeon"},
    1909281: {'name': "Guilt arena 4 main",
              'region': "dungeon"},
    1909282: {'name': "Guilt arena 5 extra",
              'region': "dungeon"},
    1909283: {'name': "Guilt arena 5 main",
              'region': "dungeon"},
    1909284: {'name': "Guilt arena 6 extra",
              'region': "dungeon"},
    1909285: {'name': "Guilt arena 6 main",
              'region': "dungeon"},
    1909286: {'name': "Guilt arena 7 extra",
              'region': "dungeon"},
    1909287: {'name': "Guilt arena 7 main",
              'region': "dungeon"},
    1909288: {'name': "Viridiana gift",
              'region': "ar"},
    1909289: {'name': "Amanecida 1",
              'region': "dungeon"},
    1909290: {'name': "Amanecida 2",
              'region': "dungeon"},
    1909291: {'name': "Amanecida 3",
              'region': "dungeon"},
    1909292: {'name': "Amanecida 4",
              'region': "dungeon"},
    1909293: {'name': "All amanecidas reward",
              'region': "dungeon"},
}