from typing import List, TypedDict


class LocationDict(TypedDict):
    name: str
    region: str
    game_id: str
    room: str


location_table: List[LocationDict] = [
    # Albero (35)
    {'name': "Albero: Sick house",
        'region': "albero",
        'game_id': "RB01",
        'room': ""},
    {'name': "Albero: Outside ossuary",
        'region': "albero",
        'game_id': "CO43",
        'room': ""},
    {'name': "Albero: Graveyard",
        'region': "albero",
        'game_id': "CO16",
        'room': ""},
    {'name': "Albero: Warp room",
        'region': "albero",
        'game_id': "QI65",
        'room': ""},
    {'name': "Albero: Elevator cherub",
        'region': "albero",
        'game_id': "RESCUED_CHERUB_08",
        'room': ""},
    {'name': "Albero: Bless cloth",
        'region': "albero",
        'game_id': "RE04",
        'room': ""},
    {'name': "Albero: Bless egg",
        'region': "albero",
        'game_id': "RE10",
        'room': ""},
    {'name': "Albero: Bless hand",
        'region': "albero",
        'game_id': "RE02",
        'room': ""},
    {'name': "Albero: Cleofas gift initial",
        'region': "albero",
        'game_id': "QI01",
        'room': ""},
    {'name': "Albero: Cleofas gift final",
        'region': "albero",
        'game_id': "PR11",
        'room': ""},
    {'name': "Albero: Tirso reward 1",
        'region': "albero",
        'game_id': "QI66",
        'room': ""},
    {'name': "Albero: Tirso reward 2",
        'region': "albero",
        'game_id': "Tirso[500]",
        'room': ""},
    {'name': "Albero: Tirso reward 3",
        'region': "albero",
        'game_id': "Tirso[1000]",
        'room': ""},
    {'name': "Albero: Tirso reward 4",
        'region': "albero",
        'game_id': "Tirso[2000]",
        'room': ""},
    {'name': "Albero: Tirso reward 5",
        'region': "albero",
        'game_id': "Tirso[5000]",
        'room': ""},
    {'name': "Albero: Tirso reward 6",
        'region': "albero",
        'game_id': "Tirso[10000]",
        'room': ""},
    {'name': "Albero: Tirso reward final",
        'region': "albero",
        'game_id': "QI56",
        'room': ""},
    {'name': "Albero: Tentudia reward 1",
        'region': "albero",
        'game_id': "Lvdovico[500]",
        'room': ""},
    {'name': "Albero: Tentudia reward 2",
        'region': "albero",
        'game_id': "Lvdovico[1000]",
        'room': ""},
    {'name': "Albero: Tentudia reward 3",
        'region': "albero",
        'game_id': "PR03",
        'room': ""},
    {'name': "Ossuary: Isidora reward main",
        'region': "albero",
        'game_id': "QI201",
        'room': ""},
    {'name': "Albero: Sword room",
        'region': "albero",
        'game_id': "Sword[D01Z02S06]",
        'room': ""},
    {'name': "Albero: Church donation 1",
        'region': "albero",
        'game_id': "RB104",
        'room': ""},
    {'name': "Albero: Church donation 2",
        'region': "albero",
        'game_id': "RB105",
        'room': ""},
    {'name': "Ossuary: Reward 1",
        'region': "albero",
        'game_id': "Undertaker[250]",
        'room': ""},
    {'name': "Ossuary: Reward 2",
        'region': "albero",
        'game_id': "Undertaker[500]",
        'room': ""},
    {'name': "Ossuary: Reward 3",
        'region': "albero",
        'game_id': "Undertaker[750]",
        'room': ""},
    {'name': "Ossuary: Reward 4",
        'region': "albero",
        'game_id': "Undertaker[1000]",
        'room': ""},
    {'name': "Ossuary: Reward 5",
        'region': "albero",
        'game_id': "Undertaker[1250]",
        'room': ""},
    {'name': "Ossuary: Reward 6",
        'region': "albero",
        'game_id': "Undertaker[1500]",
        'room': ""},
    {'name': "Ossuary: Reward 7",
        'region': "albero",
        'game_id': "Undertaker[1750]",
        'room': ""},
    {'name': "Ossuary: Reward 8",
        'region': "albero",
        'game_id': "Undertaker[2000]",
        'room': ""},
    {'name': "Ossuary: Reward 9",
        'region': "albero",
        'game_id': "Undertaker[2500]",
        'room': ""},
    {'name': "Ossuary: Reward 10",
        'region': "albero",
        'game_id': "Undertaker[3000]",
        'room': ""},
    {'name': "Ossuary: Reward 11",
        'region': "albero",
        'game_id': "Undertaker[5000]",
        'room': ""},
    
    # All the Tears of the Sea (1)
    {'name': "AtTotS: Miriam gift",
        'region': "attots",
        'game_id': "PR201",
        'room': ""},

    # Archcathedral Rooftops (11)
    {'name': "AR: Bridge fight 1",
        'region': "ar",
        'game_id': "QI02",
        'room': ""},
    {'name': "AR: Bridge fight 2",
        'region': "ar",
        'game_id': "QI03",
        'room': ""},
    {'name': "AR: Bridge fight 3",
        'region': "ar",
        'game_id': "QI04",
        'room': ""},
    {'name': "AR: Western shaft ledge",
        'region': "ar",
        'game_id': "CO06",
        'room': ""},
    {'name': "AR: Western shaft cherub",
        'region': "ar",
        'game_id': "RESCUED_CHERUB_36",
        'room': ""},
    {'name': "AR: Western shaft chest",
        'region': "ar",
        'game_id': "PR12",
        'room': ""},
    {'name': "AR: MoM east entrance",
        'region': "ar",
        'game_id': "HE04",
        'room': ""},
    {'name': "AR: Lady room",
        'region': "ar",
        'game_id': "Lady[D06Z01S24]",
        'room': ""},
    {'name': "AR: Second checkpoint ledge",
        'region': "ar",
        'game_id': "CO40",
        'room': ""},
    {'name': "AR: Sword room",
        'region': "ar",
        'game_id': "Sword[D06Z01S11]",
        'room': ""},
    {'name': "AR: Crisanta",
        'region': "ar",
        'game_id': "BS16",
        'room': ""},

    # Bridge of the Three Cavalries (3)
    {'name': "BotTC: Esdras",
        'region': "bottc",
        'game_id': "BS12",
        'room': ""},
    {'name': "BotTC: Esdras gift initial",
        'region': "bottc",
        'game_id': "PR09",
        'room': ""},
    {'name': "BotTC: Amanecida core",
        'region': "bottc",
        'game_id': "HE101",
        'room': ""},

    # Brotherhood of the Silent Sorrow (11)
    {'name': "BotSS: Beginning gift",
        'region': "botss",
        'game_id': "QI106",
        'room': ""},
    {'name': "BotSS: Initial room cherub",
        'region': "botss",
        'game_id': "RESCUED_CHERUB_06",
        'room': ""},
    {'name': "BotSS: Initial room ledge",
        'region': "botss",
        'game_id': "RB204",
        'room': ""},
    {'name': "BotSS: Elder Brother's room",
        'region': "botss",
        'game_id': "RE01",
        'room': ""},
    {'name': "BotSS: Sword room",
        'region': "botss",
        'game_id': "Sword[D17Z01S08]",
        'room': ""},
    {'name': "BotSS: Spike gauntlet exit",
        'region': "botss",
        'game_id': "CO25",
        'room': ""},
    {'name': "BotSS: Blue candle",
        'region': "botss",
        'game_id': "RB25",
        'room': ""},
    {'name': "BotSS: Church entrance",
        'region': "botss",
        'game_id': "PR203",
        'room': ""},
    {'name': "BotSS: Esdras gift final",
        'region': "botss",
        'game_id': "QI204",
        'room': ""},
    {'name': "BotSS: Crisanta gift",
        'region': "botss",
        'game_id': "QI301",
        'room': ""},
    {'name': "BotSS: Warden of the Silent Sorrow",
        'region': "botss",
        'game_id': "BS13",
        'room': ""},
    
    # Convent of Our Lady of the Charred Visage (13)
    {'name': "CoOLotCV: Blood platform ledge",
        'region': "coolotcv",
        'game_id': "CO05",
        'room': ""},
    {'name': "CoOLotCV: Ghost death room",
        'region': "coolotcv",
        'game_id': "CO15",
        'room': ""},
    {'name': "CoOLotCV: Central lung room",
        'region': "coolotcv",
        'game_id': "RB08",
        'room': ""},
    {'name': "CoOLotCV: Southwest lung room",
        'region': "coolotcv",
        'game_id': "HE03",
        'room': ""},
    {'name': "CoOLotCV: Lady room",
        'region': "coolotcv",
        'game_id': "Lady[D02Z03S15]",
        'room': ""},
    {'name': "CoOLotCV: Sword room",
        'region': "coolotcv",
        'game_id': "Sword[D02Z03S13]",
        'room': ""},
    {'name': "CoOLotCV: Red candle",
        'region': "coolotcv",
        'game_id': "RB18",
        'room': ""},
    {'name': "CoOLotCV: Blue candle",
        'region': "coolotcv",
        'game_id': "RB24",
        'room': ""},
    {'name': "CoOLotCV: Outside area",
        'region': "coolotcv",
        'game_id': "RB107",
        'room': ""},
    {'name': "CoOLotCV: Burning oil fountain",
        'region': "coolotcv",
        'game_id': "QI57",
        'room': ""},
    {'name': "CoOLotCV: Our Lady of the Charred Visage",
        'region': "coolotcv",
        'game_id': "BS03",
        'room': ""},
    {'name': "CoOLotCV: Holy Visage gift",
        'region': "coolotcv",
        'game_id': "QI40",
        'room': ""},
    {'name': "CoOLotCV: Mask room",
        'region': "coolotcv",
        'game_id': "QI61",
        'room': ""},

    # Deambulatory of His Holiness (3)
    {'name': "DoHH: Complete Penitence 1",
        'region': "dohh",
        'game_id': "RB101",
        'room': ""},
    {'name': "DoHH: Complete Penitence 2",
        'region': "dohh",
        'game_id': "RB102",
        'room': ""},
    {'name': "DoHH: Complete Penitence 3",
        'region': "dohh",
        'game_id': "RB103",
        'room': ""},

    # Desecrated Cistern (20)
    {'name': "DC: MeD lady room",
        'region': "dc",
        'game_id': "Lady[D01Z05S22]",
        'room': ""},
    {'name': "DC: MeD entrance",
        'region': "dc",
        'game_id': "CO41",
        'room': ""},
    {'name': "DC: Water room cherub",
        'region': "dc",
        'game_id': "RESCUED_CHERUB_11",
        'room': ""},
    {'name': "DC: Eastern lower tunnel chest",
        'region': "dc",
        'game_id': "QI45",
        'room': ""},
    {'name': "DC: Eastern upper tunnel chest",
        'region': "dc",
        'game_id': "PR16",
        'room': ""},
    {'name': "DC: Eastern upper tunnel cherub",
        'region': "dc",
        'game_id': "RESCUED_CHERUB_13",
        'room': ""},
    {'name': "DC: Hidden hand room",
        'region': "dc",
        'game_id': "QI67",
        'room': ""},
    {'name': "DC: WaBC entrance",
        'region': "dc",
        'game_id': "CO09",
        'room': ""},
    {'name': "DC: Oil room",
        'region': "dc",
        'game_id': "Oil[D01Z05S07]",
        'room': ""},
    {'name': "DC: Veil room cherub",
        'region': "dc",
        'game_id': "RESCUED_CHERUB_14",
        'room': ""},
    {'name': "DC: Veil room ledge",
        'region': "dc",
        'game_id': "QI12",
        'room': ""},
    {'name': "DC: Lung tunnel cherub",
        'region': "dc",
        'game_id': "RESCUED_CHERUB_12",
        'room': ""},
    {'name': "DC: Lung tunnel ledge",
        'region': "dc",
        'game_id': "CO32",
        'room': ""},
    {'name': "DC: Shroud puzzle",
        'region': "dc",
        'game_id': "RB03",
        'room': ""},
    {'name': "DC: Chalice room",
        'region': "dc",
        'game_id': "QI75",
        'room': ""},
    {'name': "DC: Sword room",
        'region': "dc",
        'game_id': "Sword[D01Z05S24]",
        'room': ""},
    {'name': "DC: GrA lady room",
        'region': "dc",
        'game_id': "Lady[D01Z05S26]",
        'room': ""},
    {'name': "DC: Elevator exit cherub",
        'region': "dc",
        'game_id': "RESCUED_CHERUB_15",
        'room': ""},
    {'name': "DC: Elevator shaft cherub",
        'region': "dc",
        'game_id': "RESCUED_CHERUB_22",
        'room': ""},
    {'name': "DC: Elevator shaft ledge",
        'region': "dc",
        'game_id': "CO44",
        'room': ""},

    # Echoes of Salt (2)
    {'name': "EoS: MoED entrance",
        'region': "eos",
        'game_id': "RB108",
        'room': ""},
    {'name': "EoS: Near elevator shaft",
        'region': "eos",
        'game_id': "RB202",
        'room': ""},
    
    # Graveyard of the Peaks (21)
    {'name': "GotP: Shop cave cherub",
        'region': "gotp",
        'game_id': "RESCUED_CHERUB_31",
        'room': ""},
    {'name': "GotP: Shop cave hole",
        'region': "gotp",
        'game_id': "CO42",
        'room': ""},
    {'name': "GotP: Shop left",
        'region': "gotp",
        'game_id': "QI11",
        'room': ""},
    {'name': "GotP: Shop middle",
        'region': "gotp",
        'game_id': "RB37",
        'room': ""},
    {'name': "GotP: Shop right",
        'region': "gotp",
        'game_id': "RB02",
        'room': ""},
    {'name': "GotP: Guilt room",
        'region': "gotp",
        'game_id': "RB38",
        'room': ""},
    {'name': "GotP: Elevator shaft cherub",
        'region': "gotp",
        'game_id': "RESCUED_CHERUB_26",
        'room': ""},
    {'name': "GotP: Elevator shaft ledge",
        'region': "gotp",
        'game_id': "QI53",
        'room': ""},
    {'name': "GotP: Lady room",
        'region': "gotp",
        'game_id': "Lady[D02Z02S12]",
        'room': ""},
    {'name': "GotP: Bleed room",
        'region': "gotp",
        'game_id': "HE11",
        'room': ""},
    {'name': "GotP: Eastern shaft lower",
        'region': "gotp",
        'game_id': "QI46",
        'room': ""},
    {'name': "GotP: Eastern shaft middle",
        'region': "gotp",
        'game_id': "CO29",
        'room': ""},
    {'name': "GotP: Eastern shaft upper",
        'region': "gotp",
        'game_id': "QI08",
        'room': ""},
    {'name': "GotP: Amanecida ledge",
        'region': "gotp",
        'game_id': "RB106",
        'room': ""},
    {'name': "GotP: Western shaft cherub",
        'region': "gotp",
        'game_id': "RESCUED_CHERUB_25",
        'room': ""},
    {'name': "GotP: Western shaft lower",
        'region': "gotp",
        'game_id': "RB32",
        'room': ""},
    {'name': "GotP: Western shaft upper",
        'region': "gotp",
        'game_id': "CO01",
        'room': ""},
    {'name': "GotP: Center shaft cherub",
        'region': "gotp",
        'game_id': "RESCUED_CHERUB_24",
        'room': ""},
    {'name': "GotP: Center shaft ledge",
        'region': "gotp",
        'game_id': "RB15",
        'room': ""},
    {'name': "GotP: Oil room",
        'region': "gotp",
        'game_id': "Oil[D02Z02S10]",
        'room': ""},
    {'name': "GotP: Bow Amanecida",
        'region': "gotp",
        'game_id': "D02Z02S14[18000]",
        'room': ""},
    
    # Grievance Ascends (12)
    {'name': "GA: Western lung ledge",
        'region': "ga",
        'game_id': "QI44",
        'room': ""},
    {'name': "GA: Lung room upper",
        'region': "ga",
        'game_id': "RE07",
        'room': ""},
    {'name': "GA: Lung room cherub",
        'region': "ga",
        'game_id': "RESCUED_CHERUB_19",
        'room': ""},
    {'name': "GA: Lung room lower",
        'region': "ga",
        'game_id': "CO12",
        'room': ""},
    {'name': "GA: Oil room",
        'region': "ga",
        'game_id': "Oil[D03Z03S13]",
        'room': ""},
    {'name': "GA: Blood tunnel ledge",
        'region': "ga",
        'game_id': "QI10",
        'room': ""},
    {'name': "GA: Blood tunnel cherub",
        'region': "ga",
        'game_id': "RESCUED_CHERUB_21",
        'room': ""},
    {'name': "GA: Altasgracias cherub",
        'region': "ga",
        'game_id': "RESCUED_CHERUB_20",
        'room': ""},
    {'name': "GA: Altasgracias gift",
        'region': "ga",
        'game_id': "QI13",
        'room': ""},
    {'name': "GA: Altasgracias cacoon",
        'region': "ga",
        'game_id': "RB06",
        'room': ""},
    {'name': "GA: Tres Angustias",
        'region': "ga",
        'game_id': "BS04",
        'room': ""},
    {'name': "GA: Holy Visage gift",
        'region': "ga",
        'game_id': "QI39",
        'room': ""},
    
    # Hall of the Dawning (2)
    {'name': "HotD: Mirror room",
        'region': "hotd",
        'game_id': "QI105",
        'room': ""},
    {'name': "HotD: Laudes",
        'region': "hotd",
        'game_id': "LaudesBossTrigger[30000]",
        'room': ""},
    
    # Jondo (13)
    {'name': "Jondo: Eastern entrance ledge",
        'region': "jondo",
        'game_id': "CO08",
        'room': ""},
    {'name': "Jondo: Eastern entrance chest",
        'region': "jondo",
        'game_id': "PR10",
        'room': ""},
    {'name': "Jondo: Eastern shaft bell chargers",
        'region': "jondo",
        'game_id': "CO33",
        'room': ""},
    {'name': "Jondo: Eastern shaft bell trap",
        'region': "jondo",
        'game_id': "QI19",
        'room': ""},
    {'name': "Jondo: Eastern shaft cherub",
        'region': "jondo",
        'game_id': "RESCUED_CHERUB_18",
        'room': ""},
    {'name': "Jondo: Spike tunnel cherub",
        'region': "jondo",
        'game_id': "RESCUED_CHERUB_37",
        'room': ""},
    {'name': "Jondo: Spike tunnel ledge",
        'region': "jondo",
        'game_id': "HE06",
        'room': ""},
    {'name': "Jondo: EcS entrance",
        'region': "jondo",
        'game_id': "QI103",
        'room': ""},
    {'name': "Jondo: Western shaft lower slide",
        'region': "jondo",
        'game_id': "CO47",
        'room': ""},
    {'name': "Jondo: Western shaft bell trap",
        'region': "jondo",
        'game_id': "QI41",
        'room': ""},
    {'name': "Jondo: Western shaft bell puzzle",
        'region': "jondo",
        'game_id': "QI52",
        'room': ""},
    {'name': "Jondo: Western shaft root puzzle",
        'region': "jondo",
        'game_id': "RB28",
        'room': ""},
    {'name': "Jondo: Western shaft cherub",
        'region': "jondo",
        'game_id': "RESCUED_CHERUB_17",
        'room': ""},
    
    # Knot of the Three Words (1)
    {'name': "KotTW: Fourth Visage gift",
        'region': "kottw",
        'game_id': "HE201",
        'room': ""},
    
    # Library of the Negated Words (18)
    {'name': "LotNW: Platform room cherub",
        'region': "lotnw",
        'game_id': "RESCUED_CHERUB_01",
        'room': ""},
    {'name': "LotNW: Platform room ledge",
        'region': "lotnw",
        'game_id': "CO18",
        'room': ""},
    {'name': "LotNW: Upper cathedral ledge",
        'region': "lotnw",
        'game_id': "CO22",
        'room': ""},
    {'name': "LotNW: Hidden floor",
        'region': "lotnw",
        'game_id': "QI50",
        'room': ""},
    {'name': "LotNW: Lung ambush chest",
        'region': "lotnw",
        'game_id': "RB31",
        'room': ""},
    {'name': "LotNW: Lady room",
        'region': "lotnw",
        'game_id': "Lady[D05Z01S14]",
        'room': ""},
    {'name': "LotNW: Bone puzzle",
        'region': "lotnw",
        'game_id': "PR15",
        'room': ""},
    {'name': "LotNW: Diosdado ledge",
        'region': "lotnw",
        'game_id': "CO28",
        'room': ""},
    {'name': "LotNW: Platform puzzle chest",
        'region': "lotnw",
        'game_id': "PR07",
        'room': ""},
    {'name': "LotNW: Final shaft ledge",
        'region': "lotnw",
        'game_id': "RB30",
        'room': ""},
    {'name': "LotNW: Final shaft cherub",
        'region': "lotnw",
        'game_id': "RESCUED_CHERUB_02",
        'room': ""},
    {'name': "LotNW: Oil room",
        'region': "lotnw",
        'game_id': "Oil[D05Z01S19]",
        'room': ""},
    {'name': "LotNW: Elevator cherub",
        'region': "lotnw",
        'game_id': "RESCUED_CHERUB_32",
        'room': ""},
    {'name': "LotNW: Mask room",
        'region': "lotnw",
        'game_id': "QI62",
        'room': ""},
    {'name': "LotNW: Sword room",
        'region': "lotnw",
        'game_id': "Sword[D05Z01S13]",
        'room': ""},
    {'name': "LotNW: Red candle",
        'region': "lotnw",
        'game_id': "RB19",
        'room': ""},
    {'name': "LotNW: Diosdado gift",
        'region': "lotnw",
        'game_id': "RB203",
        'room': ""},
    {'name': "LotNW: Fourth Visage hidden wall",
        'region': "lotnw",
        'game_id': "RB301",
        'room': ""},

    # Mercy Dreams (15)
    {'name': "MD: First section hidden wall",
        'region': "md",
        'game_id': "CO30",
        'room': ""},
    {'name': "MD: Second section ghost ambush",
        'region': "md",
        'game_id': "PR01",
        'room': ""},
    {'name': "MD: Second section ledge",
        'region': "md",
        'game_id': "CO03",
        'room': ""},
    {'name': "MD: Second section cherub",
        'region': "md",
        'game_id': "RESCUED_CHERUB_09",
        'room': ""},
    {'name': "MD: Red candle",
        'region': "md",
        'game_id': "RB17",
        'room': ""},
    {'name': "MD: Shop left",
        'region': "md",
        'game_id': "QI58",
        'room': ""},
    {'name': "MD: Shop middle",
        'region': "md",
        'game_id': "RB05",
        'room': ""},
    {'name': "MD: Shop right",
        'region': "md",
        'game_id': "RB09",
        'room': ""},
    {'name': "MD: Third section hidden wall",
        'region': "md",
        'game_id': "QI48",
        'room': ""},
    {'name': "MD: Third section lower corridor",
        'region': "md",
        'game_id': "CO38",
        'room': ""},
    {'name': "MD: Ten Piedad",
        'region': "md",
        'game_id': "BS01",
        'room': ""},
    {'name': "MD: Holy Visage gift",
        'region': "md",
        'game_id': "QI38",
        'room': ""},
    {'name': "MD: Blue candle",
        'region': "md",
        'game_id': "RB26",
        'room': ""},
    {'name': "MD: SlC entrance cherub",
        'region': "md",
        'game_id': "RESCUED_CHERUB_33",
        'room': ""},
    {'name': "MD: SlC entrance ledge",
        'region': "md",
        'game_id': "CO03",
        'room': ""},

    # Mother of Mothers (14)
    {'name': "MoM: Oil room",
        'region': "mom",
        'game_id': "Oil[D04Z02S14]",
        'room': ""},
    {'name': "MoM: Eastern room upper",
        'region': "mom",
        'game_id': "RB33",
        'room': ""},
    {'name': "MoM: Eastern room lower",
        'region': "mom",
        'game_id': "CO35",
        'room': ""},
    {'name': "MoM: Western room cherub",
        'region': "mom",
        'game_id': "RESCUED_CHERUB_30",
        'room': ""},
    {'name': "MoM: Western room ledge",
        'region': "mom",
        'game_id': "CO17",
        'room': ""},
    {'name': "MoM: Redento prayer room",
        'region': "mom",
        'game_id': "RE03",
        'room': ""},
    {'name': "MoM: Redento corpse",
        'region': "mom",
        'game_id': "QI54",
        'room': ""},
    {'name': "MoM: Blood incense shaft",
        'region': "mom",
        'game_id': "HE01",
        'room': ""},
    {'name': "MoM: Outside Cleofas room",
        'region': "mom",
        'game_id': "CO34",
        'room': ""},
    {'name': "MoM: Center room ledge",
        'region': "mom",
        'game_id': "CO20",
        'room': ""},
    {'name': "MoM: Center room cherub",
        'region': "mom",
        'game_id': "RESCUED_CHERUB_29",
        'room': ""},
    {'name': "MoM: Sword room",
        'region': "mom",
        'game_id': "Sword[D04Z02S12]",
        'room': ""},
    {'name': "MoM: Melquiades",
        'region': "mom",
        'game_id': "BS05",
        'room': ""},
    {'name': "MoM: Mask room",
        'region': "mom",
        'game_id': "QI60",
        'room': ""},

    # Mountains of the Endless Dusk (8)
    {'name': "MotED: DeC entrance",
        'region': "moted",
        'game_id': "CO13",
        'room': ""},
    {'name': "MotED: Petpetua gift",
        'region': "moted",
        'game_id': "RB13",
        'room': ""},
    {'name': "MotED: Bell gap cherub",
        'region': "moted",
        'game_id': "RESCUED_CHERUB_16",
        'room': ""},
    {'name': "MotED: Bell gap ledge",
        'region': "moted",
        'game_id': "QI47",
        'room': ""},
    {'name': "MotED: Redento meeting 1",
        'region': "moted",
        'game_id': "RB22",
        'room': ""},
    {'name': "MotED: Blood platform",
        'region': "moted",
        'game_id': "QI63",
        'room': ""},
    {'name': "MotED: Egg hatching",
        'region': "moted",
        'game_id': "QI14",
        'room': ""},
    {'name': "MotED: Axe Amanecida",
        'region': "moted",
        'game_id': "D03Z01S03[18000]",
        'room': ""},

    # Mourning and Havoc (4)
    {'name': "MaH: Western chest",
        'region': "mah",
        'game_id': "PR202",
        'room': ""},
    {'name': "MaH: Eastern chest",
        'region': "mah",
        'game_id': "RB201",
        'room': ""},
    {'name': "MaH: Sierpes reward",
        'region': "mah",
        'game_id': "QI202",
        'room': ""},
    {'name': "MaH: Sierpes",
        'region': "mah",
        'game_id': "BossTrigger[5000]",
        'room': ""},
    
    # Patio of the Silent Steps (9)
    {'name': "PotSS: Garden 1 cherub",
        'region': "potss",
        'game_id': "RESCUED_CHERUB_35",
        'room': ""},
    {'name': "PotSS: Garden 1 ledge",
        'region': "potss",
        'game_id': "CO23",
        'room': ""},
    {'name': "PotSS: Garden 2 ledge",
        'region': "potss",
        'game_id': "RB14",
        'room': ""},
    {'name': "PotSS: Garden 3 cherub",
        'region': "potss",
        'game_id': "RESCUED_CHERUB_28",
        'room': ""},
    {'name': "PotSS: Garden 3 lower ledge",
        'region': "potss",
        'game_id': "QI37",
        'room': ""},
    {'name': "PotSS: Garden 3 upper ledge",
        'region': "potss",
        'game_id': "CO39",
        'room': ""},
    {'name': "PotSS: Northern shaft",
        'region': "potss",
        'game_id': "QI102",
        'room': ""},
    {'name': "PotSS: Redento meeting 4",
        'region': "potss",
        'game_id': "RB21",
        'room': ""},
    {'name': "PotSS: Falcata Amanecida",
        'region': "potss",
        'game_id': "D04Z01S04[18000]",
        'room': ""},

    # Petrous (1)
    {'name': "Petrous: Entrance room",
        'region': "petrous",
        'game_id': "QI101",
        'room': ""},

    # The Resting Place of the Sister (1)
    {'name': "TRPotS: Perpetua shrine",
        'region': "trpots",
        'game_id': "QI203",
        'room': ""},
    
    # The Sleeping Canvases (10)
    {'name': "TSC: Herb shaft",
        'region': "tsc",
        'game_id': "QI64",
        'room': ""},
    {'name': "TSC: Wax bleed puzzle",
        'region': "tsc",
        'game_id': "HE07",
        'room': ""},
    {'name': "TSC: Shop left",
        'region': "tsc",
        'game_id': "RB12",
        'room': ""},
    {'name': "TSC: Shop middle",
        'region': "tsc",
        'game_id': "QI49",
        'room': ""},
    {'name': "TSC: Shop right",
        'region': "tsc",
        'game_id': "QI71",
        'room': ""},
    {'name': "TSC: Low tunnel blade trap",
        'region': "tsc",
        'game_id': "QI104",
        'room': ""},
    {'name': "TSC: Expositio",
        'region': "tsc",
        'game_id': "BS06",
        'room': ""},
    {'name': "TSC: Linen drop room",
        'region': "tsc",
        'game_id': "CO31",
        'room': ""},
    {'name': "TSC: Jocinero gift initial",
        'region': "tsc",
        'game_id': "RE05",
        'room': ""},
    {'name': "TSC: Jocinero gift final",
        'region': "tsc",
        'game_id': "PR05",
        'room': ""},

    # The Holy Line (6)
    {'name': "THL: Deosgracias gift",
        'region': "thl",
        'game_id': "QI31",
        'room': ""},
    {'name': "THL: Mud ledge lower",
        'region': "thl",
        'game_id': "PR14",
        'room': ""},
    {'name': "THL: Mud ledge upper",
        'region': "thl",
        'game_id': "RB07",
        'room': ""},
    {'name': "THL: Mud cherub",
        'region': "thl",
        'game_id': "RESCUED_CHERUB_07",
        'room': ""},
    {'name': "THL: Cave ledge",
        'region': "thl",
        'game_id': "CO04",
        'room': ""},
    {'name': "THL: Cave chest",
        'region': "thl",
        'game_id': "QI55",
        'room': ""},

    # Wall of the Holy Prohibitions (19)
    {'name': "WotHP: Q1 lift puzzle",
        'region': "wothp",
        'game_id': "RB11",
        'room': ""},
    {'name': "WotHP: Q1 drop room upper",
        'region': "wothp",
        'game_id': "CO10",
        'room': ""},
    {'name': "WotHP: Q1 drop room lower",
        'region': "wothp",
        'game_id': "QI69",
        'room': ""},
    {'name': "WotHP: Q1 upper bronze door",
        'region': "wothp",
        'game_id': "RESCUED_CHERUB_03",
        'room': ""},
    {'name': "WotHP: Q1 upper silver door",
        'region': "wothp",
        'game_id': "CO24",
        'room': ""},
    {'name': "WotHP: Q1 middle gold door",
        'region': "wothp",
        'game_id': "QI51",
        'room': ""},
    {'name': "WotHP: Q2 middle gold door",
        'region': "wothp",
        'game_id': "CO26",
        'room': ""},
    {'name': "WotHP: Q3 lower gold door",
        'region': "wothp",
        'game_id': "CO02",
        'room': ""},
    {'name': "WotHP: Q3 upper silver door",
        'region': "wothp",
        'game_id': "RESCUED_CHERUB_34",
        'room': ""},
    {'name': "WotHP: Q3 upper ledge",
        'region': "wothp",
        'game_id': "RB16",
        'room': ""},
    {'name': "WotHP: Q4 hidden ledge",
        'region': "wothp",
        'game_id': "CO27",
        'room': ""},
    {'name': "WotHP: Q4 lower silver door",
        'region': "wothp",
        'game_id': "RESCUED_CHERUB_04",
        'room': ""},
    {'name': "WotHP: Q4 upper bronze door",
        'region': "wothp",
        'game_id': "QI70",
        'room': ""},
    {'name': "WotHP: Q4 upper silver door",
        'region': "wothp",
        'game_id': "CO37",
        'room': ""},
    {'name': "WotHP: CoLCV entrance",
        'region': "wothp",
        'game_id': "RESCUED_CHERUB_05",
        'room': ""},
    {'name': "WotHP: Oil room",
        'region': "wothp",
        'game_id': "Oil[D09Z01S12]",
        'room': ""},
    {'name': "WotHP: Quirce",
        'region': "wothp",
        'game_id': "BS14",
        'room': ""},
    {'name': "WotHP: Quirce room",
        'region': "wothp",
        'game_id': "QI72",
        'room': ""},
    {'name': "WotHP: Lance Amanecida",
        'region': "wothp",
        'game_id': "D09Z01S01[18000]",
        'room': ""},

    # Wasteland of the Buried Churches (8)
    {'name': "WotBC: Lower tree path",
        'region': "wotbc",
        'game_id': "RB04",
        'room': ""},
    {'name': "WotBC: Building slide",
        'region': "wotbc",
        'game_id': "CO14",
        'room': ""},
    {'name': "WotBC: Exterior ledge",
        'region': "wotbc",
        'game_id': "CO36",
        'room': ""},
    {'name': "WotBC: Exterior cherub",
        'region': "wotbc",
        'game_id': "RESCUED_CHERUB_10",
        'room': ""},
    {'name': "WotBC: Underneath MeD bridge",
        'region': "wotbc",
        'game_id': "QI06",
        'room': ""},
    {'name': "WotBC: Cliffside ledge",
        'region': "wotbc",
        'game_id': "HE02",
        'room': ""},
    {'name': "WotBC: Cliffside cherub",
        'region': "wotbc",
        'game_id': "RESCUED_CHERUB_38",
        'room': ""},
    {'name': "WotBC: Redento meeting 3",
        'region': "wotbc",
        'game_id': "RB20",
        'room': ""},
    
    # Where Olive Trees Wither (11)
    {'name': "WOTW: WaBC entrance",
        'region': "wotw",
        'game_id': "CO11",
        'room': ""},
    {'name': "WOTW: Healing cave",
        'region': "wotw",
        'game_id': "QI20",
        'room': ""},
    {'name': "WOTW: White lady flower",
        'region': "wotw",
        'game_id': "QI68",
        'room': ""},
    {'name': "WOTW: White lady tomb",
        'region': "wotw",
        'game_id': "PR04",
        'room': ""},
    {'name': "WOTW: White lady cave cherub",
        'region': "wotw",
        'game_id': "RESCUED_CHERUB_17",
        'room': ""},
    {'name': "WOTW: White lady cave ledge",
        'region': "wotw",
        'game_id': "CO19",
        'room': ""},
    {'name': "WOTW: Eastern root cherub",
        'region': "wotw",
        'game_id': "RESCUED_CHERUB_23",
        'room': ""},
    {'name': "WOTW: Eastern root ledge",
        'region': "wotw",
        'game_id': "HE05",
        'room': ""},
    {'name': "WOTW: Death run",
        'region': "wotw",
        'game_id': "QI07",
        'room': ""},
    {'name': "WOTW: Gemino gift initial",
        'region': "wotw",
        'game_id': "QI59",
        'room': ""},
    {'name': "WOTW: Gemino gift final",
        'region': "wotw",
        'game_id': "RB10",
        'room': ""},

    # Various (20)
    {'name': "Guilt arena 1 extra",
        'region': "dungeon",
        'game_id': "Arena_NailManager[1000]",
        'room': ""},
    {'name': "Guilt arena 1 main",
        'region': "dungeon",
        'game_id': "QI32",
        'room': ""},
    {'name': "Guilt arena 2 extra",
        'region': "dungeon",
        'game_id': "HE10",
        'room': ""},
    {'name': "Guilt arena 2 main",
        'region': "dungeon",
        'game_id': "QI33",
        'room': ""},
    {'name': "Guilt arena 3 extra",
        'region': "dungeon",
        'game_id': "Arena_NailManager[3000]",
        'room': ""},
    {'name': "Guilt arena 3 main",
        'region': "dungeon",
        'game_id': "QI34",
        'room': ""},
    {'name': "Guilt arena 4 extra",
        'region': "dungeon",
        'game_id': "RB34",
        'room': ""},
    {'name': "Guilt arena 4 main",
        'region': "dungeon",
        'game_id': "QI35",
        'room': ""},
    {'name': "Guilt arena 5 extra",
        'region': "dungeon",
        'game_id': "Arena_NailManager[5000]",
        'room': ""},
    {'name': "Guilt arena 5 main",
        'region': "dungeon",
        'game_id': "QI79",
        'room': ""},
    {'name': "Guilt arena 6 extra",
        'region': "dungeon",
        'game_id': "RB35",
        'room': ""},
    {'name': "Guilt arena 6 main",
        'region': "dungeon",
        'game_id': "QI80",
        'room': ""},
    {'name': "Guilt arena 7 extra",
        'region': "dungeon",
        'game_id': "RB36",
        'room': ""},
    {'name': "Guilt arena 7 main",
        'region': "dungeon",
        'game_id': "QI81",
        'room': ""},
    {'name': "Viridiana gift",
        'region': "ar",
        'game_id': "PR08",
        'room': ""},
    {'name': "Amanecida 1",
        'region': "dungeon",
        'game_id': "QI107",
        'room': ""},
    {'name': "Amanecida 2",
        'region': "dungeon",
        'game_id': "QI108",
        'room': ""},
    {'name': "Amanecida 3",
        'region': "dungeon",
        'game_id': "QI109",
        'room': ""},
    {'name': "Amanecida 4",
        'region': "dungeon",
        'game_id': "QI110",
        'room': ""},
    {'name': "All amanecidas reward",
        'region': "dungeon",
        'game_id': "PR101",
        'room': ""}
]