from typing import Dict, List, Set

REGIONS: Dict[str, List[str]] = {
    "Menu": [],
    "Tower HQ": [],
    "The Shop": [],
    "The Craftsman's Corner": [],
    "Tower of Time": [],
    "Ninja Village": ["Ninja Village - Candle", "Ninja Village - Astral Seed"],
    "Autumn Hills": ["Autumn Hills - Climbing Claws", "Autumn Hills - Key of Hope", "Autumn Hills - Leaf Golem"],
    "Forlorn Temple": ["Forlorn Temple - Demon King"],
    "Catacombs": ["Catacombs - Necro", "Catacombs - Ruxxtin's Amulet", "Catacombs - Ruxxtin"],
    "Bamboo Creek": ["Bamboo Creek - Claustro"],
    "Howling Grotto": ["Howling Grotto - Wingsuit", "Howling Grotto - Emerald Golem"],
    "Quillshroom Marsh": ["Quillshroom Marsh - Seashell", "Quillshroom Marsh - Queen of Quills"],
    "Searing Crags": ["Searing Crags - Rope Dart"],
    "Searing Crags Upper": ["Searing Crags - Power Thistle", "Searing Crags - Key of Strength",
                            "Searing Crags - Astral Tea Leaves"],
    "Glacial Peak": [],
    "Cloud Ruins": [],
    "Cloud Ruins Right": ["Cloud Ruins - Acro"],
    "Underworld": ["Searing Crags - Pyro", "Underworld - Key of Chaos"],
    "Dark Cave": [],
    "Riviere Turquoise Entrance": [],
    "Riviere Turquoise": ["Riviere Turquoise - Butterfly Matriarch"],
    "Sunken Shrine": ["Sunken Shrine - Lightfoot Tabi", "Sunken Shrine - Sun Crest", "Sunken Shrine - Moon Crest",
                      "Sunken Shrine - Key of Love"],
    "Elemental Skylands": ["Elemental Skylands - Key of Symbiosis"],
    "Corrupted Future": ["Corrupted Future - Key of Courage"],
    "Music Box": ["Rescue Phantom"],
}

SEALS: Dict[str, List[str]] = {
    "Ninja Village": ["Ninja Village Seal - Tree House"],
    "Autumn Hills": ["Autumn Hills Seal - Trip Saws", "Autumn Hills Seal - Double Swing Saws",
                     "Autumn Hills Seal - Spike Ball Swing", "Autumn Hills Seal - Spike Ball Darts"],
    "Catacombs": ["Catacombs Seal - Triple Spike Crushers", "Catacombs Seal - Crusher Gauntlet",
                  "Catacombs Seal - Dirty Pond"],
    "Bamboo Creek": ["Bamboo Creek Seal - Spike Crushers and Doors", "Bamboo Creek Seal - Spike Ball Pits",
                     "Bamboo Creek Seal - Spike Crushers and Doors v2"],
    "Howling Grotto": ["Howling Grotto Seal - Windy Saws and Balls", "Howling Grotto Seal - Crushing Pits",
                       "Howling Grotto Seal - Breezy Crushers"],
    "Quillshroom Marsh": ["Quillshroom Marsh Seal - Spikey Window", "Quillshroom Marsh Seal - Sand Trap",
                          "Quillshroom Marsh Seal - Do the Spike Wave"],
    "Searing Crags": ["Searing Crags Seal - Triple Ball Spinner"],
    "Searing Crags Upper": ["Searing Crags Seal - Raining Rocks", "Searing Crags Seal - Rhythm Rocks"],
    "Glacial Peak": ["Glacial Peak Seal - Ice Climbers", "Glacial Peak Seal - Projectile Spike Pit",
                     "Glacial Peak Seal - Glacial Air Swag"],
    "Tower of Time": ["Tower of Time Seal - Time Waster", "Tower of Time Seal - Lantern Climb",
                      "Tower of Time Seal - Arcane Orbs"],
    "Cloud Ruins Right": ["Cloud Ruins Seal - Ghost Pit", "Cloud Ruins Seal - Toothbrush Alley",
                          "Cloud Ruins Seal - Saw Pit", "Cloud Ruins Seal - Money Farm Room"],
    "Underworld": ["Underworld Seal - Sharp and Windy Climb", "Underworld Seal - Spike Wall",
                   "Underworld Seal - Fireball Wave", "Underworld Seal - Rising Fanta"],
    "Forlorn Temple": ["Forlorn Temple Seal - Rocket Maze", "Forlorn Temple Seal - Rocket Sunset"],
    "Sunken Shrine": ["Sunken Shrine Seal - Ultra Lifeguard", "Sunken Shrine Seal - Waterfall Paradise",
                      "Sunken Shrine Seal - Tabi Gauntlet"],
    "Riviere Turquoise Entrance": ["Riviere Turquoise Seal - Bounces and Balls"],
    "Riviere Turquoise": ["Riviere Turquoise Seal - Launch of Faith", "Riviere Turquoise Seal - Flower Power"],
    "Elemental Skylands": ["Elemental Skylands Seal - Air", "Elemental Skylands Seal - Water",
                           "Elemental Skylands Seal - Fire"]
}

MEGA_SHARDS: Dict[str, List[str]] = {
    "Autumn Hills": ["Autumn Hills Mega Piece", "Hidden Entrance Mega Piece"],
    "Catacombs": ["Catacombs Mega Piece"],
    "Bamboo Creek": ["Above Entrance Mega Piece", "Abandoned Mega Piece", "Time Loop Mega Piece"],
    "Howling Grotto": ["Bottom Left Mega Piece", "Near Portal Mega Piece", "Pie in the Sky Mega Piece"],
    "Quillshroom Marsh": ["Quillshroom Marsh Mega Piece"],
    "Searing Crags Upper": ["Searing Crags Mega Piece"],
    "Glacial Peak": ["Glacial Peak Mega Piece"],
    "Cloud Ruins": ["Cloud Entrance Mega Piece", "Time Warp Mega Piece"],
    "Cloud Ruins Right": ["Money Farm Room Mega Piece 1", "Money Farm Room Mega Piece 2"],
    "Underworld": ["Under Entrance Mega Piece", "Hot Tub Mega Piece", "Projectile Pit Mega Piece"],
    "Forlorn Temple": ["Sunny Day Mega Piece", "Down Under Mega Piece"],
    "Sunken Shrine": ["Mega Piece of the Moon", "Beginner's Mega Piece", "Mega Piece of the Stars", "Mega Piece of the Sun"],
    "Riviere Turquoise Entrance": ["Waterfall Mega Piece"],
    "Riviere Turquoise": ["Quick Restock Mega Piece 1", "Quick Restock Mega Piece 2"],
    "Elemental Skylands": ["Earth Mega Piece", "Water Mega Piece"],
}


REGION_CONNECTIONS: Dict[str, Set[str]] = {
    "Menu": {"Tower HQ"},
    "Tower HQ": {"Autumn Hills", "Howling Grotto", "Searing Crags", "Glacial Peak", "Tower of Time",
                 "Riviere Turquoise Entrance", "Sunken Shrine", "Corrupted Future", "The Shop",
                 "The Craftsman's Corner", "Music Box"},
    "Autumn Hills": {"Ninja Village", "Forlorn Temple", "Catacombs"},
    "Forlorn Temple": {"Catacombs", "Bamboo Creek"},
    "Catacombs": {"Autumn Hills", "Bamboo Creek", "Dark Cave"},
    "Bamboo Creek": {"Catacombs", "Howling Grotto"},
    "Howling Grotto": {"Bamboo Creek", "Quillshroom Marsh", "Sunken Shrine"},
    "Quillshroom Marsh": {"Howling Grotto", "Searing Crags"},
    "Searing Crags": {"Searing Crags Upper", "Quillshroom Marsh", "Underworld"},
    "Searing Crags Upper": {"Searing Crags", "Glacial Peak"},
    "Glacial Peak": {"Searing Crags Upper", "Tower HQ", "Cloud Ruins", "Elemental Skylands"},
    "Cloud Ruins": {"Cloud Ruins Right"},
    "Cloud Ruins Right": {"Underworld"},
    "Dark Cave": {"Catacombs", "Riviere Turquoise Entrance"},
    "Riviere Turquoise Entrance": {"Riviere Turquoise"},
    "Sunken Shrine": {"Howling Grotto"},
}
"""Vanilla layout mapping with all Tower HQ portals open. from -> to"""
