from typing import Dict, List, Set, Union

REGIONS: Dict[str, List[str]] = {
    "Menu": [],
    "Tower HQ": [],
    "The Shop": [],
    "The Craftsman's Corner": [],
    "Tower of Time": [],
    "Ninja Village": ["Ninja Village - Candle", "Ninja Village - Astral Seed"],
    "Ninja Village - Right": [],
    "Autumn Hills": ["Autumn Hills - Climbing Claws", "Autumn Hills - Key of Hope", "Autumn Hills - Leaf Golem"],
    "Forlorn Temple": ["Forlorn Temple - Demon King"],
    "Forlorn Temple Outside Shop": [],
    "Catacombs": ["Catacombs - Necro", "Catacombs - Ruxxtin's Amulet", "Catacombs - Ruxxtin"],
    "Bamboo Creek": ["Bamboo Creek - Claustro"],
    "Howling Grotto": ["Howling Grotto - Wingsuit", "Howling Grotto - Emerald Golem"],
    "Quillshroom Marsh": ["Quillshroom Marsh - Seashell", "Quillshroom Marsh - Queen of Quills"],
    "Searing Crags": ["Searing Crags - Rope Dart"],
    "Searing Crags Upper": ["Searing Crags - Power Thistle", "Searing Crags - Key of Strength",
                            "Searing Crags - Astral Tea Leaves"],
    "Glacial Peak": [],
    "Cloud Ruins": [],
    "Cloud Ruins Right": ["Cloud Ruins - Acro"],
    "Underworld": ["Searing Crags - Pyro", "Underworld - Key of Chaos"],
    "Dark Cave": [],
    "Riviere Turquoise Entrance": [],
    "Riviere Turquoise": ["Riviere Turquoise - Butterfly Matriarch"],
    "Sunken Shrine": ["Sunken Shrine - Lightfoot Tabi", "Sunken Shrine - Sun Crest", "Sunken Shrine - Moon Crest",
                      "Sunken Shrine - Key of Love"],
    "Elemental Skylands": ["Elemental Skylands - Key of Symbiosis"],
    "Corrupted Future": ["Corrupted Future - Key of Courage"],
    "Music Box": ["Rescue Phantom"],
}


SUB_REGIONS: Dict[str, List[str]] = {
    "Ninja Village": [
        "Right",
    ],
    "Autumn Hills": [
        "Left",
        "Right",
        "Bottom",
        "Portal",
        "Climbing Claws Shop",
        "Hope Path Shop",
        "Dimension Climb Shop",
        "Leaf Golem Shop",
        "Hope Path Checkpoint",
        "Key of Hope Checkpoint",
        "Lakeside Checkpoint",
        "Double Swing Checkpoint",
        "Spike Ball Swing Checkpoint",
    ],
    "Forlorn Temple": [
        "Left",
        "Right",
        "Bottom",
        "Outside Shop",
        "Entrance Shop",
        "Climb Shop",
        "Rocket Sunset Shop",
        "Descent Shop",
        "Final Fall Shop",
        "Demon King Shop",
        "Sunny Day Checkpoint",
        "Rocket Maze Checkpoint",
    ],
    "Catacombs": [
        "Top Left",
        "Bottom Left",
        "Bottom",
        "Right",
        "Triple Spike Crushers Shop",
        "Ruxxtin Shop",
        "Death Trap Checkpoint",
        "Crusher Gauntlet Checkpoint",
        "Dirty Pond Checkpoint",
    ],
    "Bamboo Creek": [
        "Bottom Left",
        "Top Left",
        "Right",
        "Spike Crushers Shop",
        "Abandoned Shop",
        "Time Loop Shop",
        "Spike Ball Pits Checkpoint",
        "Spike Doors Checkpoint",
    ],
    "Howling Grotto": [
        "Left",
        "Top",
        "Right",
        "Bottom",
        "Portal",
        "Wingsuit Shop",
        "Crushing Pits Shop",
        "Emerald Golem Shop",
        "Lost Woods Checkpoint",
        "Breezy Crushers Checkpoint",
    ],
    "Quillshroom Marsh": [
        "Top Left",
        "Bottom Left",
        "Top Right",
        "Bottom Right",
        "Spikey Window Shop",
        "Sand Trap Shop",
        "Queen of Quills Shop",
        "Seashell Checkpoint",
        "Quicksand Checkpoint",
        "Spike Wave Checkpoint",
    ],
    "Searing Crags": [
        "Left",
        "Top",
        "Bottom",
        "Right",
        "Portal",
        "Rope Dart Shop",
        "Triple Ball Spinner Shop",
        "Searing Mega Shard Shop",
        "Before Final Climb Shop",
        "Colossuses Shop",
        "Key of Strength Shop",
        "Triple Ball Spinner Checkpoint",
        "Raining Rocks Checkpoint",
    ],
    "Glacial Peak": [
        "Bottom",
        "Top",
        "Portal",
        "Ice Climbers' Shop",
        "Glacial Mega Shard Shop",
        "Tower Entrance Shop",
        "Projectile Spike Pit Checkpoint",
        "Air Swag Checkpoint",
        "Free Climbing Checkpoint",
    ],
    "Tower of Time": [
        "Left",
        "Entrance Shop",
        "Arcane Golem Shop",
        "First Checkpoint",
        "Second Checkpoint",
        "Third Checkpoint",
        "Fourth Checkpoint",
        "Fifth Checkpoint",
        "Sixth Checkpoint",
    ],
    "Cloud Ruins": [
        "Left",
        "Entrance Shop",
        "First Gap Shop",
        "Shop",
        "Shop",
        "Shop",
        "Shop",
        "Shop",
        "Checkpoint",
        "Checkpoint",
        "Checkpoint",
        "Checkpoint",
    ],
    "Underworld": [
        "Left",
        "Shop",
        "Shop",
        "Shop",
        "Shop",
        "Shop",
        "Checkpoint",
        "Checkpoint",
        "Checkpoint",
    ],
    "Riviere Turquoise": [
        "Right",
        "Portal",
        "Shop",
        "Shop",
        "Shop",
        "Shop",
        "Shop",
        "Shop",
        "Checkpoint",
    ],
    "Sunken Shrine": [
        "Left",
        "Portal",
        "Shop",
        "Shop",
        "Shop",
        "Shop",
        "Shop",
        "Checkpoint",
        "Checkpoint",
        "Checkpoint",
        "Checkpoint",
    ]
}


SEALS: Dict[str, List[str]] = {
    "Ninja Village": ["Ninja Village Seal - Tree House"],
    "Autumn Hills": ["Autumn Hills Seal - Trip Saws", "Autumn Hills Seal - Double Swing Saws",
                     "Autumn Hills Seal - Spike Ball Swing", "Autumn Hills Seal - Spike Ball Darts"],
    "Catacombs": ["Catacombs Seal - Triple Spike Crushers", "Catacombs Seal - Crusher Gauntlet",
                  "Catacombs Seal - Dirty Pond"],
    "Bamboo Creek": ["Bamboo Creek Seal - Spike Crushers and Doors", "Bamboo Creek Seal - Spike Ball Pits",
                     "Bamboo Creek Seal - Spike Crushers and Doors v2"],
    "Howling Grotto": ["Howling Grotto Seal - Windy Saws and Balls", "Howling Grotto Seal - Crushing Pits",
                       "Howling Grotto Seal - Breezy Crushers"],
    "Quillshroom Marsh": ["Quillshroom Marsh Seal - Spikey Window", "Quillshroom Marsh Seal - Sand Trap",
                          "Quillshroom Marsh Seal - Do the Spike Wave"],
    "Searing Crags": ["Searing Crags Seal - Triple Ball Spinner"],
    "Searing Crags Upper": ["Searing Crags Seal - Raining Rocks", "Searing Crags Seal - Rhythm Rocks"],
    "Glacial Peak": ["Glacial Peak Seal - Ice Climbers", "Glacial Peak Seal - Projectile Spike Pit",
                     "Glacial Peak Seal - Glacial Air Swag"],
    "Tower of Time": ["Tower of Time Seal - Time Waster", "Tower of Time Seal - Lantern Climb",
                      "Tower of Time Seal - Arcane Orbs"],
    "Cloud Ruins Right": ["Cloud Ruins Seal - Ghost Pit", "Cloud Ruins Seal - Toothbrush Alley",
                          "Cloud Ruins Seal - Saw Pit", "Cloud Ruins Seal - Money Farm Room"],
    "Underworld": ["Underworld Seal - Sharp and Windy Climb", "Underworld Seal - Spike Wall",
                   "Underworld Seal - Fireball Wave", "Underworld Seal - Rising Fanta"],
    "Forlorn Temple": ["Forlorn Temple Seal - Rocket Maze", "Forlorn Temple Seal - Rocket Sunset"],
    "Sunken Shrine": ["Sunken Shrine Seal - Ultra Lifeguard", "Sunken Shrine Seal - Waterfall Paradise",
                      "Sunken Shrine Seal - Tabi Gauntlet"],
    "Riviere Turquoise Entrance": ["Riviere Turquoise Seal - Bounces and Balls"],
    "Riviere Turquoise": ["Riviere Turquoise Seal - Launch of Faith", "Riviere Turquoise Seal - Flower Power"],
    "Elemental Skylands": ["Elemental Skylands Seal - Air", "Elemental Skylands Seal - Water",
                           "Elemental Skylands Seal - Fire"]
}

MEGA_SHARDS: Dict[str, List[str]] = {
    "Autumn Hills": ["Autumn Hills Mega Shard", "Hidden Entrance Mega Shard"],
    "Catacombs": ["Catacombs Mega Shard"],
    "Bamboo Creek": ["Above Entrance Mega Shard", "Abandoned Mega Shard", "Time Loop Mega Shard"],
    "Howling Grotto": ["Bottom Left Mega Shard", "Near Portal Mega Shard", "Pie in the Sky Mega Shard"],
    "Quillshroom Marsh": ["Quillshroom Marsh Mega Shard"],
    "Searing Crags Upper": ["Searing Crags Mega Shard"],
    "Glacial Peak": ["Glacial Peak Mega Shard"],
    "Cloud Ruins": ["Cloud Entrance Mega Shard", "Time Warp Mega Shard"],
    "Cloud Ruins Right": ["Money Farm Room Mega Shard 1", "Money Farm Room Mega Shard 2"],
    "Underworld": ["Under Entrance Mega Shard", "Hot Tub Mega Shard", "Projectile Pit Mega Shard"],
    "Forlorn Temple": ["Sunny Day Mega Shard", "Down Under Mega Shard"],
    "Sunken Shrine": ["Mega Shard of the Moon", "Beginner's Mega Shard", "Mega Shard of the Stars", "Mega Shard of the Sun"],
    "Riviere Turquoise Entrance": ["Waterfall Mega Shard"],
    "Riviere Turquoise": ["Quick Restock Mega Shard 1", "Quick Restock Mega Shard 2"],
    "Elemental Skylands": ["Earth Mega Shard", "Water Mega Shard"],
}


REGION_CONNECTIONS: Dict[str, Union[Dict[str, str], str]] = {
    "Menu": {"Start Game": "Tower HQ"},
    "Tower HQ": {
        "ToTHQ Autumn Hills Portal": "Autumn Hills Portal",
        "ToTHQ Howling Grotto Portal": "Howling Grotto Portal",
        "ToTHQ Searing Crags Portal": "Searing Crags Portal",
        "ToTHQ Glacial Peak Portal": "Glacial Peak Portal",
        "ToTHQ -> Tower of Time": "Tower of Time - Left",
        "ToTHQ Riviere Turquoise Portal": "Riviere Turquoise Portal",
        "ToTHQ Sunken Shrine Portal": "Sunken Shrine Portal",
        "Artificer's Portal": "Corrupted Future",
        "Home": "The Shop",
        "Money Sink": "The Craftsman's Corner",
        "Shrink Down": "Music Box",
    },
    "Ninja Village - Right": "Autumn Hills",
    "Autumn Hills - Left": "Ninja Village",
    "Autumn Hills - Right": "Forlorn Temple",
    "Autumn Hills - Bottom": "Catacombs",
    "Autumn Hills Portal": "Tower HQ",
    "Forlorn Temple - Left": "Autumn Hills",
    "Forlorn Temple - Bottom": "Catacombs",
    "Forlorn Temple - Right": "Bamboo Creek",
    "Catacombs - Top Left": "Forlorn Temple",
    "Catacombs - Bottom Left": "Autumn Hills",
    "Catacombs - Bottom": "Dark Cave",
    "Catacombs - Right": "Bamboo Creek",
    "Dark Cave": {
        "Dark Cave - Right": "Catacombs - Bottom",
        "Dark Cave - Left": "Riviere Turquoise - Right",
    },
    "Bamboo Creek - Bottom Left": "Catacombs - Right",
    "Bamboo Creek - Top Left": "Forlorn Temple - Right",
    "Bamboo Creek - Right": "Howling Grotto - Top",
    "Howling Grotto - Left": "Bamboo Creek - Right",
    "Howling Grotto - Top": "Quillshroom Marsh - Bottom Left",
    "Howling Grotto - Right": "Quillshroom Marsh - Top Left",
    "Howling Grotto - Bottom": "Sunken Shrine",
    "Howling Grotto Portal": "Tower HQ",
    "Quillshroom Marsh - Top Left": "Howling Grotto - Right",
    "Quillshroom Marsh - Bottom Left": "Howling Grotto - Top",
    "Quillshroom Marsh - Top Right": "Searing Crags - Left",
    "Quillshroom Marsh - Bottom Right": "Searing Crags - Bottom",
    "Searing Crags - Left": "Quillshroom Marsh - Top Right",
    "Searing Crags - Top": "Glacial Peak - Bottom",
    "Searing Crags - Bottom": "Quillshroom Marsh - Bottom Right",
    "Searing Crags - Right": "Underworld - Left",
    "Searing Crags Portal": "Tower HQ",
    "Glacial Peak - Bottom": "Searing Crags - Top",
    "Glacial Peak - Top": "Cloud Ruins - Left",
    "Glacial Peak Portal": "Tower HQ",
    "Cloud Ruins - Left": "Glacial Peak - Top",
    "Underworld - Top Left": "Searing Crags - Right",
    "Sunken Shrine - Left": "Howling Grotto - Bottom",
    "Sunken Shrine Portal": "Tower HQ",
    "Riviere Turquoise Portal": "Tower HQ",
}
"""Vanilla layout mapping with all Tower HQ portals open. format is source[entrance_name][exit_region] or source[exit_region]"""


IN_AREA_REGION_CONNECTIONS: Dict[str, Dict[str, str]] = {
    
}
"""Vanilla layout mapping of sub region connections within the larger regions."""
