from worlds.rac3.constants.box_theme import RAC3BOXTHEME


class RAC3BOXCOLOR:
    DEFAULT_BACKGROUND = 0x800E5092
    DEFAULT_BOX = 0x802299DE
    DEFAULT_TEXT = 0x8066CCFF
    DEATHLINK_TEXT = 0x805555FF
    DEATHLINK_BOX = 0x806666EE
    DEATHLINK_BACKGROUND = 0x80222277

THEME_ID_TO_THEME_COLORS = {
    RAC3BOXTHEME.DEFAULT: {
        'background': RAC3BOXCOLOR.DEFAULT_BACKGROUND,
        'box': RAC3BOXCOLOR.DEFAULT_BOX,
        'text': RAC3BOXCOLOR.DEFAULT_TEXT,
    },
    RAC3BOXTHEME.DEATHLINK: {
        'background': RAC3BOXCOLOR.DEATHLINK_BACKGROUND,
        'box': RAC3BOXCOLOR.DEATHLINK_BOX,
        'text': RAC3BOXCOLOR.DEATHLINK_TEXT,
    }
}