class RAC3ITEM:
    AGENTS_OF_DOOM = "Agents of Doom"
    AGENTS_OF_DOOM_V2 = "Agents of Doom V2"
    AGENTS_OF_DOOM_V3 = "Agents of Doom V3"
    AGENTS_OF_DOOM_V4 = "Agents of Doom V4"
    AGENTS_OF_DREAD = "Agents of Dread"
    AGENTS_OF_DREAD_V6 = "Agents of Dread V6"
    AGENTS_OF_DREAD_V7 = "Agents of Dread V7"
    AGENTS_OF_DREAD_V8 = "Agents of Dread V8"
    ANNIHILATOR = "Annihilator"
    ANNIHILATOR_V2 = "Annihilator V2"
    ANNIHILATOR_V3 = "Annihilator V3"
    ANNIHILATOR_V4 = "Annihilator V4"
    DECIMATOR = "Decimator"
    DECIMATOR_V6 = "Decimator V6"
    DECIMATOR_V7 = "Decimator V7"
    DECIMATOR_V8 = "Decimator V8"
    BOLT_GRABBER = "Bolt Grabber V2"
    BOMB_GLOVE = "Bomb Glove"
    BOUNCER = "Bouncer"
    BOUNCER_V2 = "Bouncer V2"
    BOUNCER_V3 = "Bouncer V3"
    BOUNCER_V4 = "Bouncer V4"
    HEAVY_BOUNCER = "Heavy Bouncer"
    HEAVY_BOUNCER_V6 = "Heavy Bouncer V6"
    HEAVY_BOUNCER_V7 = "Heavy Bouncer V7"
    HEAVY_BOUNCER_V8 = "Heavy Bouncer V8"
    BOX_BREAKER = "Box Breaker"
    CHARGE_BOOTS = "Charge Boots"
    COMMANDO_SUIT = "Commando Suit"
    DISC_BLADE = "Disc Blade Gun"
    DISC_BLADE_V2 = "Disc Blade Gun V2"
    DISC_BLADE_V3 = "Disc Blade Gun V3"
    DISC_BLADE_V4 = "Disc Blade Gun V4"
    MULTI_DISC = "Multi-Disc Gun"
    MULTI_DISC_V6 = "Multi-Disc Gun V6"
    MULTI_DISC_V7 = "Multi-Disc Gun V7"
    MULTI_DISC_V8 = "Multi-Disc Gun V8"
    FIRST_PERSON = "First Person"
    FLUX_RIFLE = "Flux Rifle"
    FLUX_RIFLE_V2 = "Flux Rifle V2"
    FLUX_RIFLE_V3 = "Flux Rifle V3"
    FLUX_RIFLE_V4 = "Flux Rifle V4"
    SPLITTER_RIFLE = "Splitter Rifle"
    SPLITTER_RIFLE_V6 = "Splitter Rifle V6"
    SPLITTER_RIFLE_V7 = "Splitter Rifle V7"
    SPLITTER_RIFLE_V8 = "Splitter Rifle V8"
    GLIDER = "Glider"
    GRAV_BOOTS = "Gravity Boots"
    GRIND_BOOTS = "Grind Boots"
    HACKER = "The Hacker"
    HASH = "Hash"
    HELI_PACK = "Heli-Pack"
    HELMET = "Helmet"
    HOLO_SHIELD = "Holo Shield Glove"
    HOLO_SHIELD_V2 = "Holo Shield Glove V2"
    HOLO_SHIELD_V3 = "Holo Shield Glove V3"
    HOLO_SHIELD_V4 = "Holo Shield Glove V4"
    ULTRA_SHIELD = "Ultrashield Launcher"
    ULTRA_SHIELD_V6 = "Ultrashield Launcher V6"
    ULTRA_SHIELD_V7 = "Ultrashield Launcher V7"
    ULTRA_SHIELD_V8 = "Ultrashield Launcher V8"
    HYDRO_PACK = "Hydro Pack"
    HYPERSHOT = "Hypershot"
    INFECTOR = "Infector"
    INFECTOR_V2 = "Infector V2"
    INFECTOR_V3 = "Infector V3"
    INFECTOR_V4 = "Infector V4"
    INFECTO_BOMB = "Infecto-Bomb"
    INFECTO_BOMB_V6 = "Infecto-Bomb V6"
    INFECTO_BOMB_V7 = "Infecto-Bomb V7"
    INFECTO_BOMB_V8 = "Infecto-Bomb V8"
    LAVA_GUN = "Lava Gun"
    LAVA_GUN_V2 = "Lava Gun V2"
    LAVA_GUN_V3 = "Lava Gun V3"
    LAVA_GUN_V4 = "Lava Gun V4"
    LIQUID_NITROGEN = "Liquid Nitrogen Gun"
    LIQUID_NITROGEN_V6 = "Liquid Nitrogen Gun V6"
    LIQUID_NITROGEN_V7 = "Liquid Nitrogen Gun V7"
    LIQUID_NITROGEN_V8 = "Liquid Nitrogen Gun V8"
    LEVITATOR = "Levitator"
    LOCK_STRAFE = "Lock Strafe"
    MAP_O_MATIC = "Map-O-Matic"
    MASTER_PLAN = "Master Plan"
    MINI_TURRET = "Miniturret Glove"
    MINI_TURRET_V2 = "Miniturret Glove V2"
    MINI_TURRET_V3 = "Miniturret Glove V3"
    MINI_TURRET_V4 = "Miniturret Glove V4"
    MEGA_TURRET = "Megaturret Glove"
    MEGA_TURRET_V6 = "Megaturret Glove V6"
    MEGA_TURRET_V7 = "Megaturret Glove V7"
    MEGA_TURRET_V8 = "Megaturret Glove V8"
    MORPH_O_RAY = "Morph-O-Ray"
    N60_STORM = "N60 Storm"
    N60_STORM_V2 = "N60 Storm V2"
    N60_STORM_V3 = "N60 Storm V3"
    N60_STORM_V4 = "N60 Storm V4"
    N90_HURRICANE = "N90 Hurricane"
    N90_HURRICANE_V6 = "N90 Hurricane V6"
    N90_HURRICANE_V7 = "N90 Hurricane V7"
    N90_HURRICANE_V8 = "N90 Hurricane V8"
    NANO_PAK = "Nano-pak"
    NITRO_LAUNCHER = "Nitro Launcher"
    NITRO_LAUNCHER_V2 = "Nitro Launcher V2"
    NITRO_LAUNCHER_V3 = "Nitro Launcher V3"
    NITRO_LAUNCHER_V4 = "Nitro Launcher V4"
    NITRO_ERUPTOR = "Nitro Eruptor"
    NITRO_ERUPTOR_V6 = "Nitro Eruptor V6"
    NITRO_ERUPTOR_V7 = "Nitro Eruptor V7"
    NITRO_ERUPTOR_V8 = "Nitro Eruptor V8"
    PDA = "PDA"
    PLASMA_COIL = "Plasma Coil"
    PLASMA_COIL_V2 = "Plasma Coil V2"
    PLASMA_COIL_V3 = "Plasma Coil V3"
    PLASMA_COIL_V4 = "Plasma Coil V4"
    PLASMA_STORM = "Plasma Storm"
    PLASMA_STORM_V6 = "Plasma Storm V6"
    PLASMA_STORM_V7 = "Plasma Storm V7"
    PLASMA_STORM_V8 = "Plasma Storm V8"
    PLASMA_WHIP = "Plasma Whip"
    PLASMA_WHIP_V2 = "Plasma Whip V2"
    PLASMA_WHIP_V3 = "Plasma Whip V3"
    PLASMA_WHIP_V4 = "Plasma Whip V4"
    QUANTUM_WHIP = "Quantum Whip"
    QUANTUM_WHIP_V6 = "Quantum Whip V6"
    QUANTUM_WHIP_V7 = "Quantum Whip V7"
    QUANTUM_WHIP_V8 = "Quantum Whip V8"
    QWACK_O_RAY = "Qwack-O-Ray"
    QWACK_O_RAY_V2 = "Qwack-O-Ray V2"
    QWACK_O_RAY_V3 = "Qwack-O-Ray V3"
    QWACK_O_RAY_V4 = "Qwack-O-Ray V4"
    QWACK_O_BLITZER = "Qwack-O-Blitzer"
    QWACK_O_BLITZER_V6 = "Qwack-O-Blitzer V6"
    QWACK_O_BLITZER_V7 = "Qwack-O-Blitzer V7"
    QWACK_O_BLITZER_V8 = "Qwack-O-Blitzer V8"
    REFRACTOR = "Refractor"
    RIFT_INDUCER = "Rift Inducer"
    RIFT_INDUCER_V2 = "Rift Inducer V2"
    RIFT_INDUCER_V3 = "Rift Inducer v3"
    RIFT_INDUCER_V4 = "Rift Inducer v4"
    RIFT_RIPPER = "Rift Ripper"
    RIFT_RIPPER_V6 = "Rift Ripper V6"
    RIFT_RIPPER_V7 = "Rift Ripper V7"
    RIFT_RIPPER_V8 = "Rift Ripper V8"
    RY3N0 = "RY3N0"
    RY3NO_V2 = "RY3NO V2"
    RY3NO_V3 = "RY3NO V3"
    RY3NO_V4 = "RY3NO V4"
    RYNOCIRATOR = "RYNOCIRATOR"
    SHIELD_CHARGER = "Shield Charger"
    SHIELD_CHARGER_V2 = "Shield Charger V2"
    SHIELD_CHARGER_V3 = "Shield Charger V3"
    SHIELD_CHARGER_V4 = "Shield Charger V4"
    TESLA_BARRIER = "Tesla Barrier"
    TESLA_BARRIER_V6 = "Tesla Barrier V6"
    TESLA_BARRIER_V7 = "Tesla Barrier V7"
    TESLA_BARRIER_V8 = "Tesla Barrier V8"
    SHOCK_BLASTER = "Shock Blaster"
    SHOCK_BLASTER_V2 = "Shock Blaster V2"
    SHOCK_BLASTER_V3 = "Shock Blaster V3"
    SHOCK_BLASTER_V4 = "Shock Blaster V4"
    SHOCK_CANNON = "Shock Cannon"
    SHOCK_CANNON_V6 = "Shock Cannon V6"
    SHOCK_CANNON_V7 = "Shock Cannon V7"
    SHOCK_CANNON_V8 = "Shock Cannon V8"
    SPITTING_HYDRA = "Spitting Hydra"
    SPITTING_HYDRA_V2 = "Spitting Hydra V2"
    SPITTING_HYDRA_V3 = "Spitting Hydra V3"
    SPITTING_HYDRA_V4 = "Spitting Hydra V4"
    TEMPEST = "Tempest"
    TEMPEST_V6 = "Tempest V6"
    TEMPEST_V7 = "Tempest V7"
    TEMPEST_V8 = "Tempest V8"
    STAR_MAP = "Star Map"
    SUCK_CANNON = "Suck Cannon"
    SUCK_CANNON_V2 = "Suck Cannon V2"
    SUCK_CANNON_V3 = "Suck Cannon V3"
    SUCK_CANNON_V4 = "Suck Cannon V4"
    VORTEX_CANNON = "Vortex Cannon"
    VORTEX_CANNON_V6 = "Vortex Cannon V6"
    VORTEX_CANNON_V7 = "Vortex Cannon V7"
    VORTEX_CANNON_V8 = "Vortex Cannon V8"
    THIRD_PERSON = "Third Person"
    THRUSTER_PACK = "Thruster-Pack"
    TYHRRA_GUISE = "Tyhrra-Guise"
    VIDCOMIC1 = "Qwark VidComic 1"
    VIDCOMIC2 = "Qwark VidComic 2"
    VIDCOMIC3 = "Qwark VidComic 3"
    VIDCOMIC4 = "Qwark VidComic 4"
    VIDCOMIC5 = "Qwark VidComic 5"
    WARP_PAD = "Warp Pad"
    WRENCH = "OmniWrench"
    WRENCH_V2 = "OmniWrench V2"
    WRENCH_V3 = "OmniWrench V3"
    WRENCH_V4 = "OmniWrench V4"
    WRENCH_V5 = "OmniWrench V5"
    WRENCH_V6 = "OmniWrench V6"
    WRENCH_V7 = "OmniWrench V7"
    WRENCH_V8 = "OmniWrench V8"
    GRIND_BOOTS_2 = "Grind Boots 2"
    MAGNAPLATE = "Magnaplate armor"
    ADAMANTINE = "Adamantine armor"
    AEGIS = "Aegis Mark V armor"
    INFERNOX = "Infernox armor"

    PROGRESSIVE_SHOCK_BLASTER = "Progressive Shock Blaster"
    PROGRESSIVE_NITRO_LAUNCHER = "Progressive Nitro Launcher"
    PROGRESSIVE_N60_STORM = "Progressive N60 Storm"
    PROGRESSIVE_PLASMA_WHIP = "Progressive Plasma Whip"
    PROGRESSIVE_INFECTOR = "Progressive Infector"
    PROGRESSIVE_SUCK_CANNON = "Progressive Suck Cannon"
    PROGRESSIVE_SPITTING_HYDRA = "Progressive Spitting Hydra"
    PROGRESSIVE_AGENTS_OF_DOOM = "Progressive Agents of Doom"
    PROGRESSIVE_FLUX_RIFLE = "Progressive Flux Rifle"
    PROGRESSIVE_ANNIHILATOR = "Progressive Annihilator"
    PROGRESSIVE_HOLO_SHIELD = "Progressive Holo Shield Glove"
    PROGRESSIVE_DISC_BLADE = "Progressive Disc Blade Gun"
    PROGRESSIVE_RIFT_INDUCER = "Progressive Rift Inducer"
    PROGRESSIVE_QWACK_O_RAY = "Progressive Qwack-O-Ray"
    PROGRESSIVE_RY3N0 = "Progressive RY3N0"
    PROGRESSIVE_MINI_TURRET = "Progressive Miniturret Glove"
    PROGRESSIVE_LAVA_GUN = "Progressive Lava Gun"
    PROGRESSIVE_SHIELD_CHARGER = "Progressive Shield Charger"
    PROGRESSIVE_BOUNCER = "Progressive Bouncer"
    PROGRESSIVE_PLASMA_COIL = "Progressive Plasma Coil"
    PROGRESSIVE_VIDCOMIC = "Progressive VidComic"
    PROGRESSIVE_ARMOR = "Progressive Armor"

    VELDIN = "Infobot: Veldin"
    FLORANA = "Infobot: Florana"
    STARSHIP_PHOENIX = "Infobot: Starship Phoenix"
    MARCADIA = "Infobot: Marcadia"
    ANNIHILATION_NATION = "Infobot: Annihilation Nation"
    AQUATOS = "Infobot: Aquatos"
    TYHRRANOSIS = "Infobot: Tyhrranosis"
    DAXX = "Infobot: Daxx"
    OBANI_GEMINI = "Infobot: Obani Gemini"
    BLACKWATER_CITY = "Infobot: Blackwater City"
    HOLOSTAR_STUDIOS = "Infobot: Holostar Studios"
    OBANI_DRACO = "Infobot: Obani Draco"
    ZELDRIN_STARPORT = "Infobot: Zeldrin Starport"
    METROPOLIS = "Infobot: Metropolis"
    CRASH_SITE = "Infobot: Crash Site"
    ARIDIA = "Infobot: Aridia"
    QWARKS_HIDEOUT = "Infobot: Qwarks Hideout"
    KOROS = "Infobot: Koros"
    COMMAND_CENTER = "Infobot: Command Center"
    MUSEUM = "Infobot: Insomniac Museum"

    TITANIUM_BOLT = "Titanium Bolt"
    WEAPON_XP = "Weapon Level-Up"
    PLAYER_XP = "Player EXP"
    BOLTS = "Bolts"
    INFERNO_MODE = "Inferno Mode"
    JACKPOT = "Jackpot"

    MIRROR_TRAP = "Mirror Trap"
    OHKO_TRAP = "1-Hit KO Trap"
    LOCK_TRAP = "Item Lock Trap"
    WRENCH_TRAP = "Wrench Trap"
    PANCAKE_TRAP = "Pancake Trap"
    LAVA_TRAP = "Lava Trap"
    NO_AMMO_TRAP = "No Ammo Trap"
    BLACK_SCREEN_TRAP = "Black Screen Trap"
    NO_CLANK_TRAP = "No Clank Trap"

    QUICK_SELECT_0 = "Quick Select 0"
    QUICK_SELECT_1 = "Quick Select 1"
    QUICK_SELECT_2 = "Quick Select 2"
    QUICK_SELECT_3 = "Quick Select 3"
    QUICK_SELECT_4 = "Quick Select 4"
    QUICK_SELECT_5 = "Quick Select 5"
    QUICK_SELECT_6 = "Quick Select 6"
    QUICK_SELECT_7 = "Quick Select 7"
    QUICK_SELECT_8 = "Quick Select 8"
    QUICK_SELECT_9 = "Quick Select 9"
    QUICK_SELECT_A = "Quick Select A"
    QUICK_SELECT_B = "Quick Select B"
    QUICK_SELECT_C = "Quick Select C"
    QUICK_SELECT_D = "Quick Select D"
    QUICK_SELECT_E = "Quick Select E"
    QUICK_SELECT_F = "Quick Select F"

    VICTORY = "Biobliterator Defeated!"


UPGRADE_DICT: dict[str, list[int]] = {
    RAC3ITEM.SHOCK_BLASTER: [0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E],
    RAC3ITEM.NITRO_LAUNCHER: [0x77, 0x78, 0x79, 0x7A, 0x7B, 0x7C, 0x7D, 0x7E],
    RAC3ITEM.N60_STORM: [0x2F, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36],
    RAC3ITEM.PLASMA_WHIP: [0x7F, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86],
    RAC3ITEM.INFECTOR: [0x37, 0x38, 0x39, 0x3A, 0x3B, 0x3C, 0x3D, 0x3E],
    RAC3ITEM.SUCK_CANNON: [0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E],
    RAC3ITEM.SPITTING_HYDRA: [0x47, 0x48, 0x49, 0x4A, 0x4B, 0x4C, 0x4D, 0x4E],
    RAC3ITEM.AGENTS_OF_DOOM: [0x57, 0x58, 0x59, 0x5A, 0x5B, 0x5C, 0x5D, 0x5E],
    RAC3ITEM.FLUX_RIFLE: [0x6F, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76],
    RAC3ITEM.ANNIHILATOR: [0x3F, 0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46],
    RAC3ITEM.HOLO_SHIELD: [0x67, 0x68, 0x69, 0x6A, 0x6B, 0x6C, 0x6D, 0x6E],
    RAC3ITEM.DISC_BLADE: [0x4F, 0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56],
    RAC3ITEM.RIFT_INDUCER: [0x5F, 0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66],
    RAC3ITEM.QWACK_O_RAY: [0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96],
    RAC3ITEM.RY3N0: [0x97, 0x98, 0x99, 0x9A, 0x9B],
    RAC3ITEM.MINI_TURRET: [0x15, 0xA2, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD],
    RAC3ITEM.LAVA_GUN: [0x11, 0xA1, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3],
    RAC3ITEM.SHIELD_CHARGER: [0x16, 0xA7, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5],
    RAC3ITEM.BOUNCER: [0x13, 0xA6, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9],
    RAC3ITEM.PLASMA_COIL: [0x10, 0xA0, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF],
    RAC3ITEM.WRENCH: [0x09, 0xA4, 0xA5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA],
}
QUICK_SELECT_LIST: list[str] = [
    RAC3ITEM.QUICK_SELECT_0,
    RAC3ITEM.QUICK_SELECT_1,
    RAC3ITEM.QUICK_SELECT_2,
    RAC3ITEM.QUICK_SELECT_3,
    RAC3ITEM.QUICK_SELECT_4,
    RAC3ITEM.QUICK_SELECT_5,
    RAC3ITEM.QUICK_SELECT_6,
    RAC3ITEM.QUICK_SELECT_7,
    RAC3ITEM.QUICK_SELECT_8,
    RAC3ITEM.QUICK_SELECT_9,
    RAC3ITEM.QUICK_SELECT_A,
    RAC3ITEM.QUICK_SELECT_B,
    RAC3ITEM.QUICK_SELECT_C,
    RAC3ITEM.QUICK_SELECT_D,
    RAC3ITEM.QUICK_SELECT_E,
    RAC3ITEM.QUICK_SELECT_F,
]
