""" Constants for Ratchet & Clank 3 player action states. States without a character name defaults to Ratchet."""

class RAC3PLAYERACTION:
    IDLE = 0x00
    WRENCH_FIRST_PERSON = 0x01
    WALKING = 0x02
    SKIDDING = 0x03
    CROUCHING = 0x04
    QUICK_TURN = 0x05
    FALLING = 0x06
    JUMP_FEET_APART = 0x07
    GLIDING = 0x08
    JUMP_FEET_TOGETHER = 0x09
    HELI_LONG_JUMP = 0x0A
    JUMP_FLIP = 0x0B
    JUMP_JINK = 0x0C
    THRUSTER_HIGH_JUMP = 0x0D
    DOUBLE_JUMP = 0x0E
    HELI_HIGH_JUMP = 0x0F
    THRUSTER_LONG_JUMP = 0x10
    WALL_JUMP = 0x11
    JUMP_OUT_OF_WATER = 0x12
    MELEE_SWING = 0x13
    HYPER_STRIKE = 0x14
    MELEE_THROW = 0x15
    HURT = 0x16
    LEDGE_GRAB = 0x17
    LEDGE_HANG = 0x18
    LEDGE_TRAVERSAL_LEFT = 0x19
    LEDGE_TRAVERSAL_RIGHT = 0x1A
    LEDGE_JUMP = 0x1B
    VISIBOMB = 0x1C
    WEAPON_FIRST_PERSON = 0x1D
    GUN_WAITING = 0x1E
    WALLOPER_ATTACK = 0x1F
    ATTACK_BOUNCE = 0x20
    THRUSTER_GROUND_POUND = 0x21
    GLOVE_THROW = 0x22
    HYPERSHOT_EXTEND = 0x23
    HYPERSHOT_PULL = 0x24
    HYPERSHOT_PULL_VEHICLE = 0x25
    SUCK_CANNON = 0x26
    GRIND = 0x27
    GRIND_JUMP = 0x28
    GRIND_SWITCH_JUMP = 0x29
    GRIND_ATTACK = 0x2A
    HYPERSHOT_SWING = 0x2B
    HYPERSHOT_LAUNCH = 0x2C
    RECOIL = 0x2D
    ICE_SKATING = 0x2E
    DEVASTATOR = 0x2F
    SLIDING = 0x30
    EATEN = 0x31
    UNDERWATER_SWIM = 0x32
    UNDERWATER_IDLE = 0x33
    HYDRO_PACK = 0x34
    SURFACE_SWIM = 0x35
    WATER_SURFACE_IDLE = 0x36
    WRENCH_CRANK = 0x37
    LAVA_ELECTRIC_BOUNCE = 0x38
    DEATH = 0x39
    BOARDING = 0x3A
    GRAVITY_WALK = 0x3B
    GRIND_HIT = 0x3C
    GRIND_JUMP_TURN = 0x3D
    CLANK_IDLE = 0x3F
    CLANK_WALK = 0x40
    CLANK_HURT = 0x42
    CLANK_DIE = 0x43
    CLANK_JUMP = 0x45
    CLANK_GLIDE = 0x4B
    CLANK_PUNCH = 0x4D
    CLANK_FROZEN = 0x50
    TYHRRANOID_IDLE = 0x51
    TYHRRANOID_WALK = 0x52
    TYHRRANOID_FALLING = 0x53
    TYHRRANOID_JUMP = 0x54
    TYHRRANOID_HURT = 0x55
    TYHRRANOID_DEATH = 0x56
    TYHRRANOID_MINIGAME = 0x58
    TYHRRANOID_WAVE = 0x59
    GIANT_CLANK_IDLE = 0x5B
    GIANT_CLANK_WALK = 0x5C
    GIANT_CLANK_HURT = 0x5D
    GIANT_CLANK_JUMP = 0x5F
    GIANT_CLANK_PUNCH = 0x61
    GIANT_CLANK_BOMB = 0x62
    GIANT_CLANK_DIE = 0x63
    IN_CUTSCENE = 0x65
    PATHING = 0x66
    HACKER = 0x68
    AREA_LOAD_SEWERS = 0x69
    UNDERWATER_DEATH = 0x6C
    GRAVITY_BOOTS_JUMP = 0x73
    SQUASHED = 0x74
    SHALLOW_WATER = 0x75
    ZIPLINE = 0x76
    UNDERWATER_DAMAGE = 0x78
    FALLING_DEATH = 0x79
    WALL_BONK = 0x7C
    DROWNING_IN_LAVA_MUD_INSTANT = 0x7D
    DROWNING_IN_LAVA_BOUNCE = 0x7E
    CHARGE_BOOTS = 0x80
    FROZEN_ICECUBE = 0x81
    PANCAKED = 0x91
    QWARK_IDLE = 0x9A
    QWARK_WALK = 0x9B
    QWARK_WALL_SLIDE = 0x9C
    QWARK_PUNCH = 0x9D
    QWARK_HURT = 0x9E
    QWARK_DEATH = 0x9F
    QWARK_JUMP = 0xA2
    QWARK_CROUCH = 0xA3
    QWARK_WALL_JUMP = 0xA7
    QWARK_LEDGE_GRAB = 0xA9
    HALO_DIVE = 0xB0

PERMITTED_DEATHLINK_SHIP_TELEPORT_ACTIONS = [
    RAC3PLAYERACTION.IDLE,
    RAC3PLAYERACTION.WRENCH_FIRST_PERSON,
    RAC3PLAYERACTION.WALKING,
    RAC3PLAYERACTION.SKIDDING,
    RAC3PLAYERACTION.CROUCHING,
    RAC3PLAYERACTION.MELEE_SWING,
    RAC3PLAYERACTION.WEAPON_FIRST_PERSON,
    RAC3PLAYERACTION.ICE_SKATING,
    RAC3PLAYERACTION.UNDERWATER_SWIM,
    RAC3PLAYERACTION.UNDERWATER_IDLE,
    RAC3PLAYERACTION.HYDRO_PACK,
    RAC3PLAYERACTION.WRENCH_CRANK,
    RAC3PLAYERACTION.CLANK_IDLE,
    RAC3PLAYERACTION.CLANK_WALK,
    RAC3PLAYERACTION.CLANK_PUNCH,
    RAC3PLAYERACTION.TYHRRANOID_IDLE,
    RAC3PLAYERACTION.TYHRRANOID_WALK,
    RAC3PLAYERACTION.TYHRRANOID_WAVE,
    RAC3PLAYERACTION.GIANT_CLANK_IDLE,
    RAC3PLAYERACTION.GIANT_CLANK_WALK,
    RAC3PLAYERACTION.GIANT_CLANK_PUNCH,
    RAC3PLAYERACTION.GIANT_CLANK_BOMB,
    RAC3PLAYERACTION.SHALLOW_WATER,
    RAC3PLAYERACTION.ZIPLINE,
    RAC3PLAYERACTION.WALL_BONK,
    RAC3PLAYERACTION.CHARGE_BOOTS,
    RAC3PLAYERACTION.QWARK_IDLE,
    RAC3PLAYERACTION.QWARK_WALK,
    RAC3PLAYERACTION.QWARK_PUNCH,
    RAC3PLAYERACTION.QWARK_CROUCH,
]
