class RAC3ITEMTAG:
    ARMOR = "Armor"
    EQUIPABLE = "Equipable"
    FILLER = "Filler"
    GADGET = "Gadget"
    GOAL = "Goal"
    INFOBOT = "Infobot"
    NGPLUS = "NG+"
    NON_PROG_WEAPON = "Non-Progressive Weapon"
    PROG_WEAPON = "Progressive Weapon"
    PROGRESSIVE = "Progressive"
    TRAP = "Trap"
    UNUSED = "Unused"
    VIDCOMIC = "VidComic"
    WEAPON = "Weapon"
    WEAPON_UPGRADE = "Weapon Upgrade"
