"""
This file was auto generated by LogicCSVToPython.py
"""
from BaseClasses import ItemClassification
from ..Items import ItemRow

item_rows = [
	ItemRow('Area: Lumbridge', 1, ItemClassification.progression),
	ItemRow('Area: Lumbridge Swamp', 1, ItemClassification.progression),
	ItemRow('Area: HAM Hideout', 1, ItemClassification.progression),
	ItemRow('Area: Lumbridge Farms', 1, ItemClassification.progression),
	ItemRow('Area: South of Varrock', 1, ItemClassification.progression),
	ItemRow('Area: East Varrock', 1, ItemClassification.progression),
	ItemRow('Area: Central Varrock', 1, ItemClassification.progression),
	ItemRow('Area: Varrock Palace', 1, ItemClassification.progression),
	ItemRow('Area: West Varrock', 1, ItemClassification.progression),
	ItemRow('Area: Edgeville', 1, ItemClassification.progression),
	ItemRow('Area: Barbarian Village', 1, ItemClassification.progression),
	ItemRow('Area: Draynor Manor', 1, ItemClassification.progression),
	ItemRow('Area: Falador', 1, ItemClassification.progression),
	ItemRow('Area: Dwarven Mines', 1, ItemClassification.progression),
	ItemRow('Area: Ice Mountain', 1, ItemClassification.progression),
	ItemRow('Area: Monastery', 1, ItemClassification.progression),
	ItemRow('Area: Falador Farms', 1, ItemClassification.progression),
	ItemRow('Area: Port Sarim', 1, ItemClassification.progression),
	ItemRow('Area: Mudskipper Point', 1, ItemClassification.progression),
	ItemRow('Area: Karamja', 1, ItemClassification.progression),
	ItemRow('Area: Crandor', 1, ItemClassification.progression),
	ItemRow('Area: Rimmington', 1, ItemClassification.progression),
	ItemRow('Area: Crafting Guild', 1, ItemClassification.progression),
	ItemRow('Area: Draynor Village', 1, ItemClassification.progression),
	ItemRow('Area: Wizard Tower', 1, ItemClassification.progression),
	ItemRow('Area: Corsair Cove', 1, ItemClassification.progression),
	ItemRow('Area: Al Kharid', 1, ItemClassification.progression),
	ItemRow('Area: Citharede Abbey', 1, ItemClassification.progression),
	ItemRow('Area: Wilderness', 1, ItemClassification.progression),
	ItemRow('Progressive Armor', 6, ItemClassification.progression),
	ItemRow('Progressive Weapons', 6, ItemClassification.progression),
	ItemRow('Progressive Tools', 6, ItemClassification.useful),
	ItemRow('Progressive Ranged Weapons', 3, ItemClassification.useful),
	ItemRow('Progressive Ranged Armor', 3, ItemClassification.useful),
	ItemRow('Progressive Magic', 2, ItemClassification.useful),
]
