from statistics import quantiles
from tokenize import String
import typing

from BaseClasses import Location
from .Names import LocationName

class KH2Location(Location):
    game: str = "Kingdom Hearts 2"

class LocationData(typing.NamedTuple):
    code: typing.Optional[int]
    progression: bool
    locid:int
    yml:int
    dummy14: bool=False
    charName: str="Sora"


    #sort list from 1-5 to what the location is and what id is there
    #0=the second check of the getbonus
    #1 =treasure chest(trsr yml)
    #2 =1 get Bonus(bons)
    #3 =2 get bons (bons)
    #4 =Level up check 
    #5 = form check

    #if 3 use the id for both
    #if 2 then use one
    #If statement in the for loop

LoD_Checks={
LocationName.BambooGroveDarkShard                   : LocationData(0x13201B,False,245,1),
LocationName.BambooGroveEther                       : LocationData(0x13201C,False,497,1),
LocationName.BambooGroveMythrilShard                : LocationData(0x13201D,False,498,1),
LocationName.EncampmentAreaMap                      : LocationData(0x13201E,False,350,1),
LocationName.Mission3                               : LocationData(0x13201F,False,417,1),
LocationName.CheckpointHiPotion                     : LocationData(0x132020,False,21,1),
LocationName.CheckpointMythrilShard                 : LocationData(0x132021,False,121,1),
LocationName.MountainTrailLightningShard            : LocationData(0x132022,False,22,1),
LocationName.MountainTrailRecoveryRecipe            : LocationData(0x132023,False,23,1),
LocationName.MountainTrailEther                     : LocationData(0x132024,False,122,1),
LocationName.MountainTrailMythrilShard              : LocationData(0x132025,False,123,1),
LocationName.VillageCaveAreaMap                     : LocationData(0x132026,False,124,1),
LocationName.VillageCaveAPBoost                     : LocationData(0x132027,False,125,1),
LocationName.VillageCaveDarkShard                   : LocationData(0x132028,False,495,1),
LocationName.VillageCaveBonus                       : LocationData(0x132029,False,43,2),
LocationName.RidgeFrostShard                        : LocationData(0x13202A,False,24,1),
LocationName.RidgeAPBoost                           : LocationData(0x13202B,False,126,1),
LocationName.ShanYu                                 : LocationData(0x13202C,False,9,3),
LocationName.ShanYuGetBonus                         : LocationData(0x13202D,False,9,0),
LocationName.HiddenDragon                           : LocationData(0x13202E,False,357,1),
}
LoD2_Checks={
LocationName.ThroneRoomTornPages                    : LocationData(0x13202F,False,25,1),
LocationName.ThroneRoomPalaceMap                    : LocationData(0x132030,False,127,1),
LocationName.ThroneRoomAPBoost                      : LocationData(0x132031,False,26,1),
LocationName.ThroneRoomQueenRecipe                  : LocationData(0x132032,False,27,1),
LocationName.ThroneRoomAPBoost2                     : LocationData(0x132033,False,128,1),
LocationName.ThroneRoomOgreShield                   : LocationData(0x132034,False,129,1),
LocationName.ThroneRoomMythrilCrystal               : LocationData(0x132035,False,130,1),
LocationName.ThroneRoomOrichalcum                   : LocationData(0x132036,False,131,1),
LocationName.StormRider                             : LocationData(0x132037,False,10,2),
LocationName.XigbarDataDefenseBoost                 : LocationData(0x132038,False,555,1),
}                                                                  
AG_Checks={                                                        
LocationName.AgrabahMap                             : LocationData(0x132039,False,353,1),
LocationName.AgrabahDarkShard                       : LocationData(0x13203A,False,28,1),
LocationName.AgrabahMythrilShard                    : LocationData(0x13203B,False,29,1),
LocationName.AgrabahHiPotion                        : LocationData(0x13203C,False,30,1),
LocationName.AgrabahAPBoost                         : LocationData(0x13203D,False,132,1),
LocationName.AgrabahMythrilStone                    : LocationData(0x13203E,False,133,1),
LocationName.AgrabahMythrilShard2                   : LocationData(0x13203F,False,249,1),
LocationName.AgrabahSerenityShard                   : LocationData(0x132040,False,501,1),
LocationName.BazaarMythrilGem                       : LocationData(0x132041,False,31,1),
LocationName.BazaarPowerShard                       : LocationData(0x132042,False,32,1),
LocationName.BazaarHiPotion                         : LocationData(0x132043,False,33,1),
LocationName.BazaarAPBoost                          : LocationData(0x132044,False,134,1),
LocationName.BazaarMythrilShard                     : LocationData(0x132045,False,135,1),
LocationName.PalaceWallsSkillRing                   : LocationData(0x132046,False,136,1),
LocationName.PalaceWallsMythrilStone                : LocationData(0x132047,False,520,1),
LocationName.CaveEntrancePowerStone                 : LocationData(0x132048,False,250,1),
LocationName.CaveEntranceMythrilShard               : LocationData(0x132049,False,251,1),
LocationName.ValleyofStoneMythrilStone              : LocationData(0x13204A,False,35,1),
LocationName.ValleyofStoneAPBoost                   : LocationData(0x13204B,False,36,1),
LocationName.ValleyofStoneMythrilShard              : LocationData(0x13204C,False,137,1),
LocationName.ValleyofStoneHiPotion                  : LocationData(0x13204D,False,138,1),
LocationName.AbuEscort                              : LocationData(0x13204E,False,42,2),
LocationName.ChasmofChallengesCaveofWondersMap      : LocationData(0x13204F,False,487,1),
LocationName.ChasmofChallengesAPBoost               : LocationData(0x132050,False,37,1),
LocationName.TreasureRoom                           : LocationData(0x132051,False,46,2),
LocationName.TreasureRoomAPBoost                    : LocationData(0x132052,False,502,1),
LocationName.TreasureRoomSerenityGem                : LocationData(0x132053,False,503,1),
LocationName.ElementalLords                         : LocationData(0x132054,False,37,2),
LocationName.LampCharm                              : LocationData(0x132055,False,300,1),
}                                                                  
AG2_Checks={                                                       
LocationName.RuinedChamberTornPages                 : LocationData(0x132056,False,34,1),
LocationName.RuinedChamberRuinsMap                  : LocationData(0x132057,False,486,1),
LocationName.GenieJafar                             : LocationData(0x132058,False,15,2),
LocationName.WishingLamp                            : LocationData(0x132059,False,303,1),
LocationName.LexaeusBonus                           : LocationData(0x13205A,False,65,2),
LocationName.LexaeusASStrengthBeyondStrength        : LocationData(0x13205B,False,545,1),
LocationName.LexaeusDataLostIllusion                : LocationData(0x13205C,False,550,1),
}                                                                  
DC_Checks={                                                        
LocationName.DCCourtyardMythrilShard                : LocationData(0x13205D,False,16,1),
LocationName.DCCourtyardStarRecipe                  : LocationData(0x13205E,False,17,1),
LocationName.DCCourtyardAPBoost                     : LocationData(0x13205F,False,18,1),
LocationName.DCCourtyardMythrilStone                : LocationData(0x132060,False,92,1),
LocationName.DCCourtyardBlazingStone                : LocationData(0x132061,False,93,1),
LocationName.DCCourtyardBlazingShard                : LocationData(0x132062,False,247,1),
LocationName.DCCourtyardMythrilShard2               : LocationData(0x132063,False,248,1),
LocationName.LibraryTornPages                       : LocationData(0x132064,False,91,1),
LocationName.DisneyCastleMap                        : LocationData(0x132065,False,332,1),
LocationName.MinnieEscort                           : LocationData(0x132066,False,38,3),
LocationName.MinnieEscortGetBonus                   : LocationData(0x13225E,False,38,0),
}                                                                  
TR_Checks={                                                        
LocationName.CornerstoneHillMap                     : LocationData(0x132067,False,79,1),
LocationName.CornerstoneHillFrostShard              : LocationData(0x132068,False,12,1),
LocationName.PierMythrilShard                       : LocationData(0x132069,False,81,1),
LocationName.PierHiPotion                           : LocationData(0x13206A,False,82,1),
LocationName.WaterwayMythrilStone                   : LocationData(0x13206B,False,83,1),
LocationName.WaterwayAPBoost                        : LocationData(0x13206C,False,84,1),
LocationName.WaterwayFrostStone                     : LocationData(0x13206D,False,85,1),
LocationName.WindowofTimeMap                        : LocationData(0x13206E,False,368,1),
LocationName.BoatPete                               : LocationData(0x13206F,False,16,2),
LocationName.FuturePete                             : LocationData(0x132070,False,17,3),
LocationName.FuturePeteGetBonus                     : LocationData(0x132071,False,17,0),
LocationName.Monochrome                             : LocationData(0x132072,False,261,1),
LocationName.WisdomForm                             : LocationData(0x132073,False,262,1),
LocationName.MarluxiaGetBonus                       : LocationData(0x132074,False,67,2),
LocationName.MarluxiaASEternalBlossom               : LocationData(0x132075,False,584,1),
LocationName.MarluxiaDataLostIllusion               : LocationData(0x132076,False,553,1),
LocationName.LingeringWillBonus                     : LocationData(0x132077,False,70,2),
LocationName.LingeringWillProofofConnection         : LocationData(0x132078,False,587,1),
LocationName.LingeringWillManifestIllusion          : LocationData(0x132079,False,591,1),
}                                                                  
HundredAcre1_Checks={                                              
LocationName.PoohsHouse100AcreWoodMap               : LocationData(0x13207A,False,313,1),
LocationName.PoohsHouseAPBoost                      : LocationData(0x13207B,False,97,1),
LocationName.PoohsHouseMythrilStone                 : LocationData(0x13207C,False,98,1),
}                                                                  
HundredAcre2_Checks={                                              
LocationName.PigletsHouseDefenseBoost               : LocationData(0x13207D,False,105,1),
LocationName.PigletsHouseAPBoost                    : LocationData(0x13207E,False,103,1),
LocationName.PigletsHouseMythrilGem                 : LocationData(0x13207F,False,104,1),
}                                                                  
HundredAcre3_Checks={                                              
LocationName.RabbitsHouseDrawRing                   : LocationData(0x132080,False,314,1),
LocationName.RabbitsHouseMythrilCrystal             : LocationData(0x132081,False,100,1),
LocationName.RabbitsHouseAPBoost                    : LocationData(0x132082,False,101,1),
}                                                                  
HundredAcre4_Checks={                                              
LocationName.KangasHouseMagicBoost                  : LocationData(0x132083,False,108,1),
LocationName.KangasHouseAPBoost                     : LocationData(0x132084,False,106,1),
LocationName.KangasHouseOrichalcum                  : LocationData(0x132085,False,107,1),
}                                                                  
HundredAcre5_Checks={                                              
LocationName.SpookyCaveMythrilGem                   : LocationData(0x132086,False,110,1),
LocationName.SpookyCaveAPBoost                      : LocationData(0x132087,False,111,1),
LocationName.SpookyCaveOrichalcum                   : LocationData(0x132088,False,112,1),
LocationName.SpookyCaveGuardRecipe                  : LocationData(0x132089,False,113,1),
LocationName.SpookyCaveMythrilCrystal               : LocationData(0x13208A,False,115,1),
LocationName.SpookyCaveAPBoost2                     : LocationData(0x13208B,False,116,1),
LocationName.SweetMemories                          : LocationData(0x13208C,False,284,1),
LocationName.SpookyCaveMap                          : LocationData(0x13208D,False,485,1),
}                                                                  
HundredAcre6_Checks={                                              
LocationName.StarryHillCosmicRing                   : LocationData(0x13208E,False,312,1),
LocationName.StarryHillStyleRecipe                  : LocationData(0x13208F,False,94,1),
LocationName.StarryHillCureElement                  : LocationData(0x132090,False,285,1),
LocationName.StarryHillOrichalcumPlus               : LocationData(0x132091,False,539,1),
}                                                                  
Oc_Checks={                                                        
LocationName.PassageMythrilShard                    : LocationData(0x132092,False,7,1),
LocationName.PassageMythrilStone                    : LocationData(0x132093,False,8,1),
LocationName.PassageEther                           : LocationData(0x132094,False,144,1),
LocationName.PassageAPBoost                         : LocationData(0x132096,False,145,1),
LocationName.PassageHiPotion                        : LocationData(0x132097,False,146,1),
LocationName.InnerChamberUnderworldMap              : LocationData(0x132098,False,2,1),
LocationName.InnerChamberMythrilShard               : LocationData(0x132099,False,243,1),
LocationName.Cerberus                               : LocationData(0x13209A,False,5,2),
LocationName.ColiseumMap                            : LocationData(0x13209B,False,338,1),
LocationName.Urns                                   : LocationData(0x13209C,False,57,2),
LocationName.UnderworldEntrancePowerBoost           : LocationData(0x13209D,False,242,1),
LocationName.CavernsEntranceLucidShard              : LocationData(0x13209E,False,3,1),
LocationName.CavernsEntranceAPBoost                 : LocationData(0x13209F,False,11,1),
LocationName.CavernsEntranceMythrilShard            : LocationData(0x1320A0,False,504,1),
LocationName.TheLostRoadBrightShard                 : LocationData(0x1320A1,False,9,1),
LocationName.TheLostRoadEther                       : LocationData(0x1320A2,False,10,1),
LocationName.TheLostRoadMythrilShard                : LocationData(0x1320A3,False,148,1),
LocationName.TheLostRoadMythrilStone                : LocationData(0x1320A4,False,149,1),
LocationName.AtriumLucidStone                       : LocationData(0x1320A5,False,150,1),
LocationName.AtriumAPBoost                          : LocationData(0x1320A6,False,151,1),
LocationName.DemyxOC                                : LocationData(0x1320A7,False,58,2),
LocationName.SecretAnsemReport5                     : LocationData(0x1320A8,False,529,1),
LocationName.OlympusStone                           : LocationData(0x1320A9,False,293,1),
LocationName.TheLockCavernsMap                      : LocationData(0x1320AA,False,244,1),
LocationName.TheLockMythrilShard                    : LocationData(0x1320AB,False,5,1),
LocationName.TheLockAPBoost                         : LocationData(0x1320AC,False,142,1),
LocationName.PeteOC                                 : LocationData(0x1320AD,False,6,2),
LocationName.Hydra                                  : LocationData(0x1320AE,False,7,3),
LocationName.HydraGetBonus                          : LocationData(0x1320AF,False,7,0),
LocationName.HerosCrest                             : LocationData(0x1320B0,False,260,1),
}                                                                  
Oc2_Checks={                                                       
LocationName.AuronsStatue                           : LocationData(0x1320B1,False,295,1),
LocationName.Hades                                  : LocationData(0x1320B2,False,8,3),
LocationName.HadesGetBonus                          : LocationData(0x1320B3,False,8,0),
LocationName.GuardianSoul                           : LocationData(0x1320B4,False,272,1),
LocationName.ZexionBonus                            : LocationData(0x1320B5,False,66,2),
LocationName.ZexionASBookofShadows                  : LocationData(0x1320B6,False,546,1),
LocationName.ZexionDataLostIllusion                 : LocationData(0x1320B7,False,551,1),
}                                                                  
Oc2Cups={                                                          
LocationName.ProtectBeltPainandPanicCup             : LocationData(0x1320B8,False,513,1),
LocationName.SerenityGemPainandPanicCup             : LocationData(0x1320B9,False,540,1),
LocationName.RisingDragonCerberusCup                : LocationData(0x1320BA,False,515,1),
LocationName.SerenityCrystalCerberusCup             : LocationData(0x1320BB,False,542,1),
LocationName.GenjiShieldTitanCup                    : LocationData(0x1320BC,False,514,1),
LocationName.SkillfulRingTitanCup                   : LocationData(0x1320BD,False,541,1),
LocationName.FatalCrestGoddessofFateCup             : LocationData(0x1320BE,False,516,1),
LocationName.OrichalcumPlusGoddessofFateCup         : LocationData(0x1320BF,False,517,1),
}                                                                  
HadesCups={                                                        
LocationName.HadesCupTrophyParadoxCups              : LocationData(0x1320C0,False,518,1),
}                                                                  
                                                                   
BC_Checks={                                                        
LocationName.BCCourtyardAPBoost                     : LocationData(0x1320C1,False,39,1),
LocationName.BCCourtyardHiPotion                    : LocationData(0x1320C2,False,40,1),
LocationName.BCCourtyardMythrilShard                : LocationData(0x1320C3,False,505,1),
LocationName.BellesRoomCastleMap                    : LocationData(0x1320C4,False,46,1),
LocationName.BellesRoomMegaRecipe                   : LocationData(0x1320C5,False,240,1),
LocationName.TheEastWingMythrilShard                : LocationData(0x1320C6,False,63,1),
LocationName.TheEastWingTent                        : LocationData(0x1320C7,False,155,1),
LocationName.TheWestHallHiPotion                    : LocationData(0x1320C8,False,41,1),
LocationName.TheWestHallPowerShard                  : LocationData(0x1320C9,False,207,1),
LocationName.TheWestHallAPBoost                     : LocationData(0x1320CA,False,158,1),
LocationName.TheWestHallBrightStone                 : LocationData(0x1320CB,False,159,1),
LocationName.TheWestHallMythrilShard                : LocationData(0x1320CC,False,206,1),
LocationName.Thresholder                            : LocationData(0x1320CD,False,2,2),
LocationName.DungeonBasementMap                     : LocationData(0x1320CE,False,239,1),
LocationName.DungeonAPBoost                         : LocationData(0x1320CF,False,43,1),
LocationName.SecretPassageMythrilShard              : LocationData(0x1320D0,False,44,1),
LocationName.SecretPassageHiPotion                  : LocationData(0x1320D1,False,168,1),
LocationName.SecretPassageLucidShard                : LocationData(0x1320D2,False,45,1),
LocationName.TheWestHallMythrilShardPostDungeon     : LocationData(0x1320D3,False,208,1),
LocationName.TheWestWingMythrilShard                : LocationData(0x1320D4,False,42,1),
LocationName.TheWestWingTent                        : LocationData(0x1320D5,False,164,1),
LocationName.Beast                                  : LocationData(0x1320D6,False,12,2),
LocationName.TheBeastsRoomBlazingShard              : LocationData(0x1320D7,False,241,1),
LocationName.DarkThorn                              : LocationData(0x1320D8,False,3,3),
LocationName.DarkThornGetBonus                      : LocationData(0x1320D9,False,3,0),
LocationName.DarkThornCureElement                   : LocationData(0x1320DA,False,299,1),
}                                                                  
BC2_Checks={                                                       
LocationName.RumblingRose                           : LocationData(0x1320DB,False,270,1),
LocationName.CastleWallsMap                         : LocationData(0x1320DC,False,325,1),
LocationName.Xaldin                                 : LocationData(0x1320DD,False,4,3),
LocationName.XaldinGetBonus                         : LocationData(0x1320DE,False,4,0),
LocationName.SecretAnsemReport6                     : LocationData(0x1320DF,False,528,1),
LocationName.XaldinDataDefenseBoost                 : LocationData(0x1320E0,False,559,1),
}                                                                  
SP_Checks={                                                        
LocationName.PitCellAreaMap                         : LocationData(0x1320E1,False,316,1),
LocationName.PitCellMythrilCrystal                  : LocationData(0x1320E2,False,64,1),
LocationName.CanyonDarkCrystal                      : LocationData(0x1320E3,False,65,1),
LocationName.CanyonMythrilStone                     : LocationData(0x1320E4,False,171,1),
LocationName.CanyonMythrilGem                       : LocationData(0x1320E5,False,253,1),
LocationName.CanyonFrostCrystal                     : LocationData(0x1320E6,False,521,1),
LocationName.Screens                                : LocationData(0x1320E7,False,45,2),
LocationName.HallwayPowerCrystal                    : LocationData(0x1320E8,False,49,1),
LocationName.HallwayAPBoost                         : LocationData(0x1320E9,False,50,1),
LocationName.CommunicationsRoomIOTowerMap           : LocationData(0x1320EA,False,255,1),
LocationName.CommunicationsRoomGaiaBelt             : LocationData(0x1320EB,False,499,1),
LocationName.HostileProgram                         : LocationData(0x1320EC,False,31,3),
LocationName.HostileProgramGetBonus                 : LocationData(0x1320ED,False,31,0),
LocationName.PhotonDebugger                         : LocationData(0x1320EE,False,267,1),
}                                                                  
SP2_Checks={                                                       
LocationName.SolarSailer                            : LocationData(0x1320EF,False,61,2),
LocationName.CentralComputerCoreAPBoost             : LocationData(0x1320F0,False,177,1),
LocationName.CentralComputerCoreOrichalcumPlus      : LocationData(0x1320F1,False,178,1),
LocationName.CentralComputerCoreCosmicArts          : LocationData(0x1320F2,False,51,1),
LocationName.CentralComputerCoreMap                 : LocationData(0x1320F3,False,488,1),
LocationName.MCP                                    : LocationData(0x1320F4,False,32,3),
LocationName.MCPGetBonus                            : LocationData(0x1320F5,False,32,0),
LocationName.LarxeneBonus                           : LocationData(0x1320F6,False,68,1),
LocationName.LarxeneASCloakedThunder                : LocationData(0x1320F7,False,547,1),
LocationName.LarxeneDataLostIllusion                : LocationData(0x1320F8,False,552,1),
}                                                                  
HT_Checks={                                                        
LocationName.GraveyardMythrilShard                  : LocationData(0x1320F9,False,53,1),
LocationName.GraveyardSerenityGem                   : LocationData(0x1320FA,False,212,1),
LocationName.FinklesteinsLabHalloweenTownMap        : LocationData(0x1320FB,False,211,1),
LocationName.TownSquareMythrilStone                 : LocationData(0x1320FC,False,209,1),
LocationName.TownSquareEnergyShard                  : LocationData(0x1320FD,False,210,1),
LocationName.HinterlandsLightningShard              : LocationData(0x1320FE,False,54,1),
LocationName.HinterlandsMythrilStone                : LocationData(0x1320FF,False,213,1),
LocationName.HinterlandsAPBoost                     : LocationData(0x132100,False,214,1),
LocationName.CandyCaneLaneMegaPotion                : LocationData(0x132101,False,55,1),
LocationName.CandyCaneLaneMythrilGem                : LocationData(0x132102,False,56,1),
LocationName.CandyCaneLaneLightningStone            : LocationData(0x132103,False,216,1),
LocationName.CandyCaneLaneMythrilStone              : LocationData(0x132104,False,217,1),
LocationName.SantasHouseChristmasTownMap            : LocationData(0x132105,False,57,1),
LocationName.SantasHouseAPBoost                     : LocationData(0x132106,False,58,1),
LocationName.PrisonKeeper                           : LocationData(0x132107,False,18,2),
LocationName.OogieBoogie                            : LocationData(0x132108,False,19,1),
LocationName.OogieBoogieMagnetElement               : LocationData(0x132109,False,301,1),
}                                                                  
HT2_Checks={                                                       
LocationName.Lock                                   : LocationData(0x13210A,False,40,1),
LocationName.Present                                : LocationData(0x13210B,False,297,1),
LocationName.DecoyPresents                          : LocationData(0x13210C,False,298,1),
LocationName.Experiment                             : LocationData(0x13210D,False,20,2),
LocationName.DecisivePumpkin                        : LocationData(0x13210E,False,275,1),
LocationName.VexenBonus                             : LocationData(0x13210F,False,64,1),
LocationName.VexenASRoadtoDiscovery                 : LocationData(0x132110,False,544,1),
LocationName.VexenDataLostIllusion                  : LocationData(0x132111,False,549,1),
}                                                                  
PR_Checks={                                                        
LocationName.RampartNavalMap                        : LocationData(0x132112,False,70,1),
LocationName.RampartMythrilStone                    : LocationData(0x132113,False,219,1),
LocationName.RampartDarkShard                       : LocationData(0x132114,False,220,1),
LocationName.TownDarkStone                          : LocationData(0x132115,False,71,1),
LocationName.TownAPBoost                            : LocationData(0x132116,False,72,1),
LocationName.TownMythrilShard                       : LocationData(0x132117,False,73,1),
LocationName.TownMythrilGem                         : LocationData(0x132118,False,221,1),
LocationName.CaveMouthBrightShard                   : LocationData(0x132119,False,74,1),
LocationName.CaveMouthMythrilShard                  : LocationData(0x13211A,False,223,1),
LocationName.IsladeMuertaMap                        : LocationData(0x13211B,False,329,1),
LocationName.BoatFight                              : LocationData(0x13211C,False,62,2),
LocationName.InterceptorBarrels                     : LocationData(0x13211D,False,39,2),
LocationName.PowderStoreAPBoost1                    : LocationData(0x13211E,False,369,1),
LocationName.PowderStoreAPBoost2                    : LocationData(0x13211F,False,370,1),
LocationName.MoonlightNookMythrilShard              : LocationData(0x132120,False,75,1),
LocationName.MoonlightNookSerenityGem               : LocationData(0x132121,False,224,1),
LocationName.MoonlightNookPowerStone                : LocationData(0x132122,False,371,1),
LocationName.Barbossa                               : LocationData(0x132123,False,21,3),
LocationName.BarbossaGetBonus                       : LocationData(0x132124,False,21,0),
LocationName.FollowtheWind                          : LocationData(0x132125,False,263,1),
}                                                                  
PR2_Checks={                                                       
LocationName.GrimReaper1                            : LocationData(0x132126,False,59,2),
LocationName.InterceptorsHoldFeatherCharm           : LocationData(0x132127,False,252,1),
LocationName.SeadriftKeepAPBoost                    : LocationData(0x132128,False,76,1),
LocationName.SeadriftKeepOrichalcum                 : LocationData(0x132129,False,225,1),
LocationName.SeadriftKeepMeteorStaff                : LocationData(0x13212A,False,372,1),
LocationName.SeadriftRowSerenityGem                 : LocationData(0x13212B,False,77,1),
LocationName.SeadriftRowKingRecipe                  : LocationData(0x13212C,False,78,1),
LocationName.SeadriftRowMythrilCrystal              : LocationData(0x13212D,False,373,1),
LocationName.SeadriftRowCursedMedallion             : LocationData(0x13212E,False,296,1),
LocationName.SeadriftRowShipGraveyardMap            : LocationData(0x13212F,False,331,1),
LocationName.GrimReaper2                            : LocationData(0x132130,False,22,2),
LocationName.SecretAnsemReport4                     : LocationData(0x132131,False,530,1),
LocationName.LuxordDataAPBoost                      : LocationData(0x132132,False,557,1),
}                                                                  
HB_Checks={
LocationName.MarketplaceMap                         : LocationData(0x132133,False,362,1),
LocationName.BoroughDriveRecovery                   : LocationData(0x132134,False,194,1),
LocationName.BoroughAPBoost                         : LocationData(0x132135,False,195,1),
LocationName.BoroughHiPotion                        : LocationData(0x132136,False,196,1),
LocationName.BoroughMythrilShard                    : LocationData(0x132137,False,305,1),
LocationName.BoroughDarkShard                       : LocationData(0x132138,False,506,1),
LocationName.MerlinsHouseMembershipCard             : LocationData(0x132139,False,256,1),
LocationName.MerlinsHouseBlizzardElement            : LocationData(0x13213A,False,292,1),
LocationName.Bailey                                 : LocationData(0x13213B,False,47,2),
LocationName.BaileySecretAnsemReport7               : LocationData(0x13213C,False,531,1),
LocationName.BaseballCharm                          : LocationData(0x13213D,False,258,1),
}                                                                  
HB2_Checks={                                                       
LocationName.PosternCastlePerimeterMap              : LocationData(0x13213E,False,310,1),
LocationName.PosternMythrilGem                      : LocationData(0x13213F,False,189,1),
LocationName.PosternAPBoost                         : LocationData(0x132140,False,190,1),
LocationName.CorridorsMythrilStone                  : LocationData(0x132141,False,200,1),
LocationName.CorridorsMythrilCrystal                : LocationData(0x132142,False,201,1),
LocationName.CorridorsDarkCrystal                   : LocationData(0x132143,False,202,1),
LocationName.CorridorsAPBoost                       : LocationData(0x132144,False,307,1),
LocationName.AnsemsStudyMasterForm                  : LocationData(0x132145,False,184,1),
LocationName.AnsemsStudySleepingLion                : LocationData(0x132146,False,266,1),
LocationName.AnsemsStudySkillRecipe                 : LocationData(0x132147,False,276,1),
LocationName.AnsemsStudyUkuleleCharm                : LocationData(0x132148,False,183,1),
LocationName.RestorationSiteMoonRecipe              : LocationData(0x132149,False,309,1),
LocationName.RestorationSiteAPBoost                 : LocationData(0x13214A,False,507,1),
LocationName.DemyxHB                                : LocationData(0x13214B,False,28,3),
LocationName.DemyxHBGetBonus                        : LocationData(0x13225E,False,28,0),
LocationName.FFFightsCureElement                    : LocationData(0x13214C,False,361,1),
LocationName.CrystalFissureTornPages                : LocationData(0x13214D,False,179,1),
LocationName.CrystalFissureTheGreatMawMap           : LocationData(0x13214E,False,489,1),
LocationName.CrystalFissureEnergyCrystal            : LocationData(0x13214F,False,180,1),
LocationName.CrystalFissureAPBoost                  : LocationData(0x132150,False,181,1),
LocationName.ThousandHeartless                      : LocationData(0x132151,False,60,2),
LocationName.ThousandHeartlessSecretAnsemReport1    : LocationData(0x132152,False,525,1),
LocationName.ThousandHeartlessIceCream              : LocationData(0x132153,False,269,1),
LocationName.ThousandHeartlessPicture               : LocationData(0x132154,False,511,1),
LocationName.PosternGullWing                        : LocationData(0x132155,False,491,1),
LocationName.HeartlessManufactoryCosmicChain        : LocationData(0x132156,False,311,1),
LocationName.SephirothBonus                         : LocationData(0x132157,False,35,2),
LocationName.SephirothFenrir                        : LocationData(0x132158,False,282,1),
LocationName.WinnersProof                           : LocationData(0x132159,False,560,1),
LocationName.ProofofPeace                           : LocationData(0x13215A,False,588,1),
LocationName.DemyxDataAPBoost                       : LocationData(0x13215B,False,589,1),
}                                                                  
CoR_Checks={                                                       
LocationName.CoRDepthsAPBoost                               : LocationData(0x13215C,False,562,1),
LocationName.CoRDepthsPowerCrystal                          : LocationData(0x13215D,False,563,1),
LocationName.CoRDepthsFrostCrystal                          : LocationData(0x13215E,False,564,1),
LocationName.CoRDepthsManifestIllusion                      : LocationData(0x13215F,False,565,1),
LocationName.CoRDepthsAPBoost2                              : LocationData(0x132160,False,566,1),
LocationName.CoRMineshaftLowerLevelDepthsofRemembranceMap   : LocationData(0x132161,False,580,1),
LocationName.CoRMineshaftLowerLevelAPBoost                  : LocationData(0x132162,False,578,1),
}
#Need quickrun 2 aerial dodge 2 
FirstHalf_Checks={
LocationName.CoRDepthsUpperLevelRemembranceGem      : LocationData(0x132163,False,567,1),
LocationName.CoRMiningAreaSerenityGem               : LocationData(0x132164,False,568,1),
LocationName.CoRMiningAreaAPBoost                   : LocationData(0x132165,False,569,1),
LocationName.CoRMiningAreaSerenityCrystal           : LocationData(0x132166,False,570,1),
LocationName.CoRMiningAreaManifestIllusion          : LocationData(0x132167,False,571,1),
LocationName.CoRMiningAreaSerenityGem2              : LocationData(0x132168,False,572,1),
LocationName.CoRMiningAreaDarkRemembranceMap        : LocationData(0x132169,False,573,1),
LocationName.CoRMineshaftMidLevelPowerBoost         : LocationData(0x13216A,False,581,1),
LocationName.CoREngineChamberSerenityCrystal        : LocationData(0x13216B,False,574,1),
LocationName.CoREngineChamberRemembranceCrystal     : LocationData(0x13216C,False,575,1),
LocationName.CoREngineChamberAPBoost                : LocationData(0x13216D,False,576,1),
LocationName.CoREngineChamberManifestIllusion       : LocationData(0x13216E,False,577,1),
LocationName.CoRMineshaftUpperLevelMagicBoost       : LocationData(0x13216F,False,582,1),
}#glide 3 highjump somthem        
 #missed these in putting the hex but it shouldnt cause a issue
SecondHalf_Checks={                                                
LocationName.CoRMineshaftUpperLevelAPBoost          : LocationData(0x13225C,False,570,1),
LocationName.TransporttoRemembrance                 : LocationData(0x13225D,False,72,2),
}                                                                  
PL_Checks={                                                        
LocationName.GorgeSavannahMap                       : LocationData(0x132170,False,492,1),
LocationName.GorgeDarkGem                           : LocationData(0x132171,False,404,1),
LocationName.GorgeMythrilStone                      : LocationData(0x132172,False,405,1),
LocationName.ElephantGraveyardFrostGem              : LocationData(0x132173,False,401,1),
LocationName.ElephantGraveyardMythrilStone          : LocationData(0x132174,False,402,1),
LocationName.ElephantGraveyardBrightStone           : LocationData(0x132175,False,403,1),
LocationName.ElephantGraveyardAPBoost               : LocationData(0x132176,False,508,1),
LocationName.ElephantGraveyardMythrilShard          : LocationData(0x132177,False,509,1),
LocationName.PrideRockMap                           : LocationData(0x132178,False,418,1),
LocationName.PrideRockMythrilStone                  : LocationData(0x132179,False,392,1),
LocationName.PrideRockSerenityCrystal               : LocationData(0x13217A,False,393,1),
LocationName.WildebeestValleyEnergyStone            : LocationData(0x13217B,False,396,1),
LocationName.WildebeestValleyAPBoost                : LocationData(0x13217C,False,397,1),
LocationName.WildebeestValleyMythrilGem             : LocationData(0x13217D,False,398,1),
LocationName.WildebeestValleyMythrilStone           : LocationData(0x13217E,False,399,1),
LocationName.WildebeestValleyLucidGem               : LocationData(0x13217F,False,400,1),
LocationName.WastelandsMythrilShard                 : LocationData(0x132180,False,406,1),
LocationName.WastelandsSerenityGem                  : LocationData(0x132181,False,407,1),
LocationName.WastelandsMythrilStone                 : LocationData(0x132182,False,408,1),
LocationName.JungleSerenityGem                      : LocationData(0x132183,False,409,1),
LocationName.JungleMythrilStone                     : LocationData(0x132184,False,410,1),
LocationName.JungleSerenityCrystal                  : LocationData(0x132185,False,411,1),
LocationName.OasisMap                               : LocationData(0x132186,False,412,1),
LocationName.OasisTornPages                         : LocationData(0x132187,False,493,1),
LocationName.OasisAPBoost                           : LocationData(0x132188,False,413,1),
LocationName.CircleofLife                           : LocationData(0x132189,False,264,1),
LocationName.Hyenas1                                : LocationData(0x13218A,False,49,2),
LocationName.Scar                                   : LocationData(0x13218B,False,29,1),
LocationName.ScarFireElement                        : LocationData(0x13218C,False,302,1),
}                                                                  
PL2_Checks={                                                       
LocationName.Hyenas2                                : LocationData(0x13218D,False,50,2),
LocationName.Groundshaker                           : LocationData(0x13218E,False,30,3),
LocationName.GroundshakerGetBonus                   : LocationData(0x13218F,False,30,0),
LocationName.SaixDataDefenseBoost                   : LocationData(0x132190,False,556,1),
}                                                                  
STT_Checks={                                                       
LocationName.TwilightTownMap                        : LocationData(0x132191,False,319,1,"Roxas"),
LocationName.MunnyPouchOlette                       : LocationData(0x132192,False,288,1,"Roxas"),
LocationName.StationDusks                           : LocationData(0x132193,False,54,2),
LocationName.StationofSerenityPotion                : LocationData(0x132194,False,315,1),
LocationName.StationofCallingPotion                 : LocationData(0x132195,False,472,1),
LocationName.TwilightThorn                          : LocationData(0x132196,False,33,2),
LocationName.Axel1                                  : LocationData(0x132197,False,73,2),
LocationName.JunkChampionBelt                       : LocationData(0x132198,False,389,1),
LocationName.JunkMedal                              : LocationData(0x132199,False,390,1),
LocationName.TheStruggleTrophy                      : LocationData(0x13219A,False,519,1),
LocationName.CentralStationPotion1                  : LocationData(0x13219B,False,428,1),
LocationName.STTCentralStationHiPotion              : LocationData(0x13219C,False,429,1),
LocationName.CentralStationPotion2                  : LocationData(0x13219D,False,430,1),
LocationName.SunsetTerraceAbilityRing               : LocationData(0x13219E,False,434,1),
LocationName.SunsetTerraceHiPotion                  : LocationData(0x13219F,False,435,1),
LocationName.SunsetTerracePotion1                   : LocationData(0x1321A0,False,436,1),
LocationName.SunsetTerracePotion2                   : LocationData(0x1321A1,False,437,1),
LocationName.MansionFoyerHiPotion                   : LocationData(0x1321A2,False,449,1),
LocationName.MansionFoyerPotion1                    : LocationData(0x1321A3,False,450,1),
LocationName.MansionFoyerPotion2                    : LocationData(0x1321A4,False,451,1),
LocationName.MansionDiningRoomElvenBandanna         : LocationData(0x1321A5,False,455,1),
LocationName.MansionDiningRoomPotion                : LocationData(0x1321A6,False,456,1),
LocationName.NaminesSketches                        : LocationData(0x1321A7,False,289,1),
LocationName.MansionMap                             : LocationData(0x1321A8,False,483,1),
LocationName.MansionLibraryHiPotion                 : LocationData(0x1321A9,False,459,1),
LocationName.Axel2                                  : LocationData(0x1321AA,False,34,2),
LocationName.MansionBasementCorridorHiPotion        : LocationData(0x1321AB,False,463,1),
LocationName.RoxasDataMagicBoost                    : LocationData(0x1321AC,False,558,1),
}                                                                  
TT_Checks={                                                        
LocationName.OldMansionPotion                       : LocationData(0x1321AD,False,447,1),
LocationName.OldMansionMythrilShard                 : LocationData(0x1321AE,False,448,1),
LocationName.TheWoodsPotion                         : LocationData(0x1321AF,False,442,1),
LocationName.TheWoodsMythrilShard                   : LocationData(0x1321B0,False,443,1),
LocationName.TheWoodsHiPotion                       : LocationData(0x1321B1,False,444,1),
LocationName.TramCommonHiPotion                     : LocationData(0x1321B2,False,420,1),
LocationName.TramCommonAPBoost                      : LocationData(0x1321B3,False,421,1),
LocationName.TramCommonTent                         : LocationData(0x1321B4,False,422,1),
LocationName.TramCommonMythrilShard1                : LocationData(0x1321B5,False,423,1),
LocationName.TramCommonPotion1                      : LocationData(0x1321B6,False,424,1),
LocationName.TramCommonMythrilShard2                : LocationData(0x1321B7,False,425,1),
LocationName.TramCommonPotion2                      : LocationData(0x1321B8,False,484,1),
LocationName.StationPlazaSecretAnsemReport2         : LocationData(0x1321B9,False,526,1),
LocationName.MunnyPouchMickey                       : LocationData(0x1321BA,False,290,1),
LocationName.CrystalOrb                             : LocationData(0x1321BB,False,291,1),
LocationName.CentralStationTent                     : LocationData(0x1321BC,False,431,1),
LocationName.TTCentralStationHiPotion               : LocationData(0x1321BD,False,432,1),
LocationName.CentralStationMythrilShard             : LocationData(0x1321BE,False,433,1),
LocationName.TheTowerPotion                         : LocationData(0x1321BF,False,465,1),
LocationName.TheTowerHiPotion                       : LocationData(0x1321C0,False,466,1),
LocationName.TheTowerEther                          : LocationData(0x1321C1,False,522,1),
LocationName.TowerEntrywayEther                     : LocationData(0x1321C2,False,467,1),
LocationName.TowerEntrywayMythrilShard              : LocationData(0x1321C3,False,468,1),
LocationName.SorcerersLoftTowerMap                  : LocationData(0x1321C4,False,469,1),
LocationName.TowerWardrobeMythrilStone              : LocationData(0x1321C5,False,470,1),
LocationName.StarSeeker                             : LocationData(0x1321C6,False,304,1),
LocationName.ValorForm                              : LocationData(0x1321C7,False,286,1),
}                                                                  
TT2_Checks={                                                       
LocationName.SeifersTrophy                          : LocationData(0x1321C8,False,294,1),
LocationName.Oathkeeper                             : LocationData(0x1321C9,False,265,1),
LocationName.LimitForm                              : LocationData(0x1321CA,False,543,1),
}                                                                  
TT3_Checks={                                                       
LocationName.UndergroundConcourseMythrilGem         : LocationData(0x1321CB,False,479,1),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
LocationName.UndergroundConcourseAPBoost            : LocationData(0x1321CC,False,480,1),
LocationName.UndergroundConcourseOrichalcum         : LocationData(0x1321CD,False,481,1),
LocationName.UndergroundConcourseMythrilCrystal     : LocationData(0x1321CE,False,482,1),
LocationName.TunnelwayOrichalcum                    : LocationData(0x1321CF,False,477,1),
LocationName.TunnelwayMythrilCrystal                : LocationData(0x1321D0,False,478,1),
LocationName.SunsetTerraceOrichalcumPlus            : LocationData(0x1321D1,False,438,1),
LocationName.SunsetTerraceMythrilShard              : LocationData(0x1321D2,False,439,1),
LocationName.SunsetTerraceMythrilCrystal            : LocationData(0x1321D3,False,440,1),
LocationName.SunsetTerraceAPBoost                   : LocationData(0x1321D4,False,441,1),
LocationName.MansionNobodies                        : LocationData(0x1321D5,False,56,2),
LocationName.MansionFoyerMythrilCrystal             : LocationData(0x1321D6,False,452,1),
LocationName.MansionFoyerMythrilStone               : LocationData(0x1321D7,False,453,1),
LocationName.MansionFoyerSerenityCrystal            : LocationData(0x1321D8,False,454,1),
LocationName.MansionDiningRoomMythrilCrystal        : LocationData(0x1321D9,False,457,1),
LocationName.MansionDiningRoomMythrilStone          : LocationData(0x1321DA,False,458,1),
LocationName.MansionLibraryOrichalcum               : LocationData(0x1321DB,False,460,1),
LocationName.BeamSecretAnsemReport10                : LocationData(0x1321DC,False,534,1),
LocationName.MansionBasementCorridorUltimateRecipe  : LocationData(0x1321DD,False,464,1),
LocationName.BetwixtandBetween                      : LocationData(0x1321DE,False,63,2),
LocationName.BetwixtandBetweenBondofFlame           : LocationData(0x1321DF,False,317,1),
LocationName.AxelDataMagicBoost                     : LocationData(0x1321E0,False,561,1),
}                                                                  
TWTNW_Checks={                                                     
LocationName.FragmentCrossingMythrilStone           : LocationData(0x1321E1,False,374,1),
LocationName.FragmentCrossingMythrilCrystal         : LocationData(0x1321E2,False,375,1),
LocationName.FragmentCrossingAPBoost                : LocationData(0x1321E3,False,376,1),
LocationName.FragmentCrossingOrichalcum             : LocationData(0x1321E4,False,377,1),
LocationName.Roxas                                  : LocationData(0x1321E5,False,69,3),
LocationName.RoxasGetBonus                          : LocationData(0x1321E6,False,69,0),
LocationName.RoxasSecretAnsemReport8                : LocationData(0x1321E7,False,532,1),
LocationName.TwoBecomeOne                           : LocationData(0x1321E8,False,277,1),
LocationName.MemorysSkyscaperMythrilCrystal         : LocationData(0x1321E9,False,391,1),
LocationName.MemorysSkyscaperAPBoost                : LocationData(0x1321EA,False,523,1),
LocationName.MemorysSkyscaperMythrilStone           : LocationData(0x1321EB,False,524,1),
LocationName.TheBrinkofDespairDarkCityMap           : LocationData(0x1321EC,False,335,1),
LocationName.TheBrinkofDespairOrichalcumPlus        : LocationData(0x1321ED,False,500,1),
LocationName.NothingsCallMythrilGem                 : LocationData(0x1321EE,False,378,1),
LocationName.NothingsCallOrichalcum                 : LocationData(0x1321EF,False,379,1),
LocationName.TwilightsViewCosmicBelt                : LocationData(0x1321F0,False,336,1),
}                                                                  
TWTNW2_Checks={                                                    
LocationName.XigbarBonus                            : LocationData(0x1321F1,False,23,2),
LocationName.XigbarSecretAnsemReport3               : LocationData(0x1321F2,False,527,1),
LocationName.NaughtsSkywayMythrilGem                : LocationData(0x1321F3,False,380,1),
LocationName.NaughtsSkywayOrichalcum                : LocationData(0x1321F4,False,381,1),
LocationName.NaughtsSkywayMythrilCrystal            : LocationData(0x1321F5,False,382,1),
LocationName.Oblivion                               : LocationData(0x1321F6,False,278,1),
LocationName.CastleThatNeverWasMap                  : LocationData(0x1321F7,False,496,1),
LocationName.Luxord                                 : LocationData(0x1321F8,False,24,3),
LocationName.LuxordGetBonus                         : LocationData(0x1321F9,False,24,0),
LocationName.LuxordSecretAnsemReport9               : LocationData(0x1321FA,False,533,1),
LocationName.SaixBonus                              : LocationData(0x1321FB,False,25,2),
LocationName.SaixSecretAnsemReport12                : LocationData(0x1321FC,False,536,1),
LocationName.PreXemnas1SecretAnsemReport11          : LocationData(0x1321FD,False,535,1),
LocationName.RuinandCreationsPassageMythrilStone    : LocationData(0x1321FE,False,385,1),
LocationName.RuinandCreationsPassageAPBoost         : LocationData(0x1321FF,False,386,1),
LocationName.RuinandCreationsPassageMythrilCrystal  : LocationData(0x132200,False,387,1),
LocationName.RuinandCreationsPassageOrichalcum      : LocationData(0x132201,False,388,1),
LocationName.Xemnas1                                : LocationData(0x132202,False,26,3),
LocationName.Xemnas1GetBonus                        : LocationData(0x132203,False,26,0),
LocationName.Xemnas1SecretAnsemReport13             : LocationData(0x132204,False,537,1),
LocationName.FinalXemnas                            : LocationData(0x132205,False,71,2),
LocationName.XemnasDataPowerBoost                   : LocationData(0x132206,False,554,1),
}                                                                  
SoraLevels={                                                       
    LocationName.Lvl2                               : LocationData(0x132208,False,2,4),
    LocationName.Lvl3                               : LocationData(0x132209,False,3,4),
    LocationName.Lvl4                               : LocationData(0x13220A,False,4,4),
    LocationName.Lvl5                               : LocationData(0x13220B,False,5,4),
    LocationName.Lvl6                               : LocationData(0x13220C,False,6,4),
    LocationName.Lvl7                               : LocationData(0x13220D,False,7,4),
    LocationName.Lvl8                               : LocationData(0x13220E,False,8,4),
    LocationName.Lvl9                               : LocationData(0x13220F,False,9,4),
    LocationName.Lvl10                              : LocationData(0x132210,False,10,4),
    LocationName.Lvl11                              : LocationData(0x132211,False,11,4),
    LocationName.Lvl12                              : LocationData(0x132212,False,12,4),
    LocationName.Lvl13                              : LocationData(0x132213,False,13,4),
    LocationName.Lvl14                              : LocationData(0x132214,False,14,4),
    LocationName.Lvl15                              : LocationData(0x132215,False,15,4),
    LocationName.Lvl16                              : LocationData(0x132216,False,16,4),
    LocationName.Lvl17                              : LocationData(0x132217,False,17,4),
    LocationName.Lvl18                              : LocationData(0x132218,False,18,4),
    LocationName.Lvl19                              : LocationData(0x132219,False,19,4),
    LocationName.Lvl20                              : LocationData(0x13221A,False,20,4),
    LocationName.Lvl21                              : LocationData(0x13221B,False,21,4),
    LocationName.Lvl22                              : LocationData(0x13221C,False,22,4),
    LocationName.Lvl23                              : LocationData(0x13221D,False,23,4),
    LocationName.Lvl24                              : LocationData(0x13221E,False,24,4),
    LocationName.Lvl25                              : LocationData(0x13221F,False,25,4),
    LocationName.Lvl26                              : LocationData(0x132220,False,26,4),
    LocationName.Lvl27                              : LocationData(0x132221,False,27,4),
    LocationName.Lvl28                              : LocationData(0x132222,False,28,4),
    LocationName.Lvl29                              : LocationData(0x132223,False,29,4),
    LocationName.Lvl30                              : LocationData(0x132224,False,30,4),
    LocationName.Lvl31                              : LocationData(0x132225,False,31,4),
    LocationName.Lvl32                              : LocationData(0x132226,False,32,4),
    LocationName.Lvl33                              : LocationData(0x132227,False,33,4),
    LocationName.Lvl34                              : LocationData(0x132228,False,34,4),
    LocationName.Lvl35                              : LocationData(0x132229,False,35,4),
    LocationName.Lvl36                              : LocationData(0x13222A,False,36,4),
    LocationName.Lvl37                              : LocationData(0x13222B,False,37,4),
    LocationName.Lvl38                              : LocationData(0x13222C,False,38,4),
    LocationName.Lvl39                              : LocationData(0x13222D,False,39,4),
    LocationName.Lvl40                              : LocationData(0x13222E,False,40,4),
    LocationName.Lvl41                              : LocationData(0x13222F,False,41,4),
    LocationName.Lvl42                              : LocationData(0x132230,False,42,4),
    LocationName.Lvl43                              : LocationData(0x132231,False,43,4),
    LocationName.Lvl44                              : LocationData(0x132232,False,44,4),
    LocationName.Lvl45                              : LocationData(0x132233,False,45,4),
    LocationName.Lvl46                              : LocationData(0x132234,False,46,4),
    LocationName.Lvl47                              : LocationData(0x132235,False,47,4),
    LocationName.Lvl48                              : LocationData(0x132236,False,48,4),
    LocationName.Lvl49                              : LocationData(0x132237,False,49,4),
    LocationName.Lvl50                              : LocationData(0x132238,False,50,4),
    LocationName.Lvl51                              : LocationData(0x132239,False,51,4),
    LocationName.Lvl52                              : LocationData(0x13223A,False,52,4),
    LocationName.Lvl53                              : LocationData(0x13223B,False,53,4),
    LocationName.Lvl54                              : LocationData(0x13223C,False,54,4),
    LocationName.Lvl55                              : LocationData(0x13223D,False,55,4),
    LocationName.Lvl56                              : LocationData(0x13223E,False,56,4),
    LocationName.Lvl57                              : LocationData(0x13223F,False,57,4),
    LocationName.Lvl58                              : LocationData(0x132240,False,58,4),
    LocationName.Lvl59                              : LocationData(0x132241,False,59,4),
    LocationName.Lvl60                              : LocationData(0x132242,False,60,4),
    LocationName.Lvl61                              : LocationData(0x132243,False,61,4),
    LocationName.Lvl62                              : LocationData(0x132244,False,62,4),
    LocationName.Lvl63                              : LocationData(0x132245,False,63,4),
    LocationName.Lvl64                              : LocationData(0x132246,False,64,4),
    LocationName.Lvl65                              : LocationData(0x132247,False,65,4),
    LocationName.Lvl66                              : LocationData(0x132248,False,66,4),
    LocationName.Lvl67                              : LocationData(0x132249,False,67,4),
    LocationName.Lvl68                              : LocationData(0x13224A,False,68,4),
    LocationName.Lvl69                              : LocationData(0x13224B,False,69,4),
    LocationName.Lvl70                              : LocationData(0x13224C,False,70,4),
    LocationName.Lvl71                              : LocationData(0x13224D,False,71,4),
    LocationName.Lvl72                              : LocationData(0x13224E,False,72,4),
    LocationName.Lvl73                              : LocationData(0x13224F,False,73,4),
    LocationName.Lvl74                              : LocationData(0x132250,False,74,4),
    LocationName.Lvl75                              : LocationData(0x132251,False,75,4),
    LocationName.Lvl76                              : LocationData(0x132252,False,76,4),
    LocationName.Lvl77                              : LocationData(0x132253,False,77,4),
    LocationName.Lvl78                              : LocationData(0x132254,False,78,4),
    LocationName.Lvl79                              : LocationData(0x132255,False,79,4),
    LocationName.Lvl80                              : LocationData(0x132256,False,80,4),
    LocationName.Lvl81                              : LocationData(0x132257,False,81,4),
    LocationName.Lvl82                              : LocationData(0x132258,False,82,4),
    LocationName.Lvl83                              : LocationData(0x132259,False,83,4),
    LocationName.Lvl84                              : LocationData(0x13225A,False,84,4),
    LocationName.Lvl85                              : LocationData(0x13225B,False,85,4),
    LocationName.Lvl86                              : LocationData(0x13225C,False,86,4),
    LocationName.Lvl87                              : LocationData(0x13225D,False,87,4),
    LocationName.Lvl88                              : LocationData(0x13225E,False,88,4),
    LocationName.Lvl89                              : LocationData(0x13225F,False,89,4),
    LocationName.Lvl90                              : LocationData(0x132260,False,90,4),
    LocationName.Lvl91                              : LocationData(0x132261,False,91,4),
    LocationName.Lvl92                              : LocationData(0x132262,False,92,4),
    LocationName.Lvl93                              : LocationData(0x132263,False,93,4),
    LocationName.Lvl94                              : LocationData(0x132264,False,94,4),
    LocationName.Lvl95                              : LocationData(0x132265,False,95,4),
    LocationName.Lvl96                              : LocationData(0x132266,False,96,4),
    LocationName.Lvl97                              : LocationData(0x132267,False,97,4),
    LocationName.Lvl98                              : LocationData(0x132268,False,98,4),
    LocationName.Lvl99                              : LocationData(0x132269,False,99,4),
}                                                                  
Form_Checks={                                                      
    LocationName.Valorlvl2                          : LocationData(0x13226A,False,2,5),
    LocationName.Valorlvl3                          : LocationData(0x13226B,False,3,5),
    LocationName.Valorlvl4                          : LocationData(0x13226C,False,4,5),
    LocationName.Valorlvl5                          : LocationData(0x13226D,False,5,5),
    LocationName.Valorlvl6                          : LocationData(0x13226E,False,6,5),
    LocationName.Valorlvl7                          : LocationData(0x13226F,False,7,5),
    LocationName.Wisdomlvl2                         : LocationData(0x132270,False,2,5),
    LocationName.Wisdomlvl3                         : LocationData(0x132271,False,3,5),
    LocationName.Wisdomlvl4                         : LocationData(0x132272,False,4,5),
    LocationName.Wisdomlvl5                         : LocationData(0x132273,False,5,5),
    LocationName.Wisdomlvl6                         : LocationData(0x132274,False,6,5),
    LocationName.Wisdomlvl7                         : LocationData(0x132275,False,7,5),
    LocationName.Limitlvl2                          : LocationData(0x132276,False,2,5),
    LocationName.Limitlvl3                          : LocationData(0x132277,False,3,5),
    LocationName.Limitlvl4                          : LocationData(0x132278,False,4,5),
    LocationName.Limitlvl5                          : LocationData(0x132279,False,5,5),
    LocationName.Limitlvl6                          : LocationData(0x13227A,False,6,5),
    LocationName.Limitlvl7                          : LocationData(0x13227B,False,7,5),
    LocationName.Masterlvl2                         : LocationData(0x13227C,False,2,5),
    LocationName.Masterlvl3                         : LocationData(0x13227D,False,3,5),
    LocationName.Masterlvl4                         : LocationData(0x13227E,False,4,5),
    LocationName.Masterlvl5                         : LocationData(0x13227F,False,5,5),
    LocationName.Masterlvl6                         : LocationData(0x132280,False,6,5),
    LocationName.Masterlvl7                         : LocationData(0x132281,False,7,5),
    LocationName.Finallvl2                          : LocationData(0x132282,False,2,5),
    LocationName.Finallvl3                          : LocationData(0x132283,False,3,5),
    LocationName.Finallvl4                          : LocationData(0x132284,False,4,5),
    LocationName.Finallvl5                          : LocationData(0x132285,False,5,5),
    LocationName.Finallvl6                          : LocationData(0x132286,False,6,5),
    LocationName.Finallvl7                          : LocationData(0x132287,False,7,5),
}                                                                  
GoA_Checks={                                                       
    LocationName.GardenofAssemblageMap              : LocationData(0x132288,False,585,1),
    LocationName.GoALostIllusion                    : LocationData(0x132289,False,586,1),        
    LocationName.ProofofNonexistence                : LocationData(0x13228A,False,590,1),
    }
#Keyblade_Slots={
#    LocationName.FAKESlot                           :LocationData(0x13228B),
#    LocationName.DetectionSaberSlot                 :LocationData(0x13228C),
#    LocationName.EdgeofUltimaSlot                   :LocationData(0x13228D),
#    LocationName.KingdomKeySlot                     :LocationData(0x13228E),
#    LocationName.OathkeeperSlot                     :LocationData(0x13228F),
#    LocationName.OblivionSlot                       :LocationData(0x132290),
#    LocationName.StarSeekerSlot                     :LocationData(0x132291),
#    LocationName.HiddenDragonSlot                   :LocationData(0x132292),
#    LocationName.HerosCrestSlot                     :LocationData(0x132293),
#    LocationName.MonochromeSlot                     :LocationData(0x132294),
#    LocationName.FollowtheWindSlot                  :LocationData(0x132295),
#    LocationName.CircleofLifeSlot                   :LocationData(0x132296),
#    LocationName.PhotonDebuggerSlot                 :LocationData(0x132297),
#    LocationName.GullWingSlot                       :LocationData(0x132298),
#    LocationName.RumblingRoseSlot                   :LocationData(0x132299),
#    LocationName.GuardianSoulSlot                   :LocationData(0x13229A),
#    LocationName.WishingLampSlot                    :LocationData(0x13229B),
#    LocationName.DecisivePumpkinSlot                :LocationData(0x13229C),
#    LocationName.SweetMemoriesSlot                  :LocationData(0x13229D),
#    LocationName.MysteriousAbyssSlot                :LocationData(0x13229E),
#    LocationName.SleepingLionSlot                   :LocationData(0x13229F),
#    LocationName.BondofFlameSlot                    :LocationData(0x1322A0),
#    LocationName.TwoBecomeOneSlot                   :LocationData(0x1322A1),
#    LocationName.FatalCrestSlot                     :LocationData(0x1322A2),
#    LocationName.FenrirSlot                         :LocationData(0x1322A3),
#    LocationName.UltimaWeaponSlot                   :LocationData(0x1322A4),
#    LocationName.WinnersProofSlot                   :LocationData(0x1322A5),
#    }
                                                          
exclusion_table = {                                                
    "Datas": {                                                     
        LocationName.XemnasDataPowerBoost,                         
        LocationName.AxelDataMagicBoost,                           
        LocationName.RoxasDataMagicBoost,                          
        LocationName.SaixDataDefenseBoost,
        LocationName.DemyxDataAPBoost ,
        LocationName.LuxordDataAPBoost,
        LocationName.VexenDataLostIllusion,
        LocationName.LarxeneDataLostIllusion,
        LocationName.XaldinDataDefenseBoost,
        LocationName.MarluxiaDataLostIllusion,  
        LocationName.LexaeusDataLostIllusion,
        LocationName.XigbarDataDefenseBoost,
        
    },
    "SuperBosses":{
        LocationName.LingeringWillBonus,            
        LocationName.LingeringWillProofofConnection,
        LocationName.LingeringWillManifestIllusion,
        LocationName.SephirothBonus,
        LocationName.SephirothFenrir,
        },
    
    
    #These levels when level 50 is turned on should have Nothing
    "Level50":{
        LocationName.Lvl7,
        LocationName.Lvl9,
        LocationName.Lvl12,
        LocationName.Lvl15,
        LocationName.Lvl17,
        LocationName.Lvl20,
        LocationName.Lvl23,
        LocationName.Lvl25,
        LocationName.Lvl28,
        LocationName.Lvl31,
        LocationName.Lvl33,
        LocationName.Lvl36,
        LocationName.Lvl39,
        LocationName.Lvl41,
        LocationName.Lvl44,
        LocationName.Lvl47,
        LocationName.Lvl49,
        LocationName.Lvl51,
        LocationName.Lvl52,
        LocationName.Lvl53,
        LocationName.Lvl54,
        LocationName.Lvl55,
        LocationName.Lvl56,
        LocationName.Lvl57,
        LocationName.Lvl58,
        LocationName.Lvl59,
        LocationName.Lvl60,
        LocationName.Lvl61,
        LocationName.Lvl62,
        LocationName.Lvl63,
        LocationName.Lvl64,
        LocationName.Lvl65,
        LocationName.Lvl66,
        LocationName.Lvl67,
        LocationName.Lvl68,
        LocationName.Lvl69,
        LocationName.Lvl70,
        LocationName.Lvl71,
        LocationName.Lvl72,
        LocationName.Lvl73,
        LocationName.Lvl74,
        LocationName.Lvl75,
        LocationName.Lvl76,
        LocationName.Lvl77,
        LocationName.Lvl78,
        LocationName.Lvl79,
        LocationName.Lvl80,
        LocationName.Lvl81,
        LocationName.Lvl82,
        LocationName.Lvl83,
        LocationName.Lvl84,
        LocationName.Lvl85,
        LocationName.Lvl86,
        LocationName.Lvl87,
        LocationName.Lvl88,
        LocationName.Lvl89,
        LocationName.Lvl90,
        LocationName.Lvl91,
        LocationName.Lvl92,
        LocationName.Lvl93,
        LocationName.Lvl94,
        LocationName.Lvl95,
        LocationName.Lvl96,
        LocationName.Lvl97,
        LocationName.Lvl98,
        LocationName.Lvl99,
        },
}
firstVisits=[
        LocationName.LoD_Region         ,        
        LocationName.Ag_Region          ,
        LocationName.Dc_Region          , 
        LocationName.Pr_Region          ,        
        LocationName.Oc_Region          ,             
        LocationName.Bc_Region          ,         
        LocationName.Sp_Region          ,
        LocationName.Ht_Region          , 
        LocationName.Hb_Region          , 
        LocationName.Pl_Region          ,  
        LocationName.STT_Region         , 
        LocationName.TT_Region          , 
        LocationName.Twtnw_Region       ,
]
corChecks=[
    LocationName.CoRDepthsUpperLevelRemembranceGem ,
    LocationName.CoRMiningAreaSerenityGem          ,
    LocationName.CoRMiningAreaAPBoost              ,
    LocationName.CoRMiningAreaSerenityCrystal      ,
    LocationName.CoRMiningAreaManifestIllusion     ,
    LocationName.CoRMiningAreaSerenityGem2         ,
    LocationName.CoRMiningAreaDarkRemembranceMap   ,
    LocationName.CoRMineshaftMidLevelPowerBoost    ,
    LocationName.CoREngineChamberSerenityCrystal   ,
    LocationName.CoREngineChamberRemembranceCrystal,
    LocationName.CoREngineChamberAPBoost           ,
    LocationName.CoREngineChamberManifestIllusion  ,
    LocationName.CoRMineshaftUpperLevelMagicBoost  ,
    LocationName.CoRMineshaftUpperLevelAPBoost     ,
    LocationName.TransporttoRemembrance            ,
    ]

ag2Checks=[
    LocationName.RuinedChamberTornPages         ,
    LocationName.RuinedChamberRuinsMap          ,
    LocationName.GenieJafar                     ,
    LocationName.WishingLamp                    ,
    LocationName.LexaeusBonus                   ,
    LocationName.LexaeusASStrengthBeyondStrength,
    LocationName.LexaeusDataLostIllusion        ,
    ]
lvl50Checks=[
    LocationName.Lvl2,
    LocationName.Lvl4,
    LocationName.Lvl7,
    LocationName.Lvl9,
    LocationName.Lvl10,
    LocationName.Lvl12,
    LocationName.Lvl14,
    LocationName.Lvl15,
    LocationName.Lvl17,
    LocationName.Lvl20,
    LocationName.Lvl23,
    LocationName.Lvl25,
    LocationName.Lvl28,
    LocationName.Lvl30,
    LocationName.Lvl32,
    LocationName.Lvl34,
    LocationName.Lvl36,
    LocationName.Lvl39,
    LocationName.Lvl41,
    LocationName.Lvl44,
    LocationName.Lvl46,
    LocationName.Lvl48,
    LocationName.Lvl50,
]
formChecks=[
    LocationName.Valorlvl2,
    LocationName.Valorlvl3,
    LocationName.Valorlvl4,
    LocationName.Valorlvl5,
    LocationName.Valorlvl6,
    LocationName.Valorlvl7,
    LocationName.Wisdomlvl2,
    LocationName.Wisdomlvl3,
    LocationName.Wisdomlvl4,
    LocationName.Wisdomlvl5,
    LocationName.Wisdomlvl6,
    LocationName.Wisdomlvl7,
    LocationName.Limitlvl2,
    LocationName.Limitlvl3,
    LocationName.Limitlvl4,
    LocationName.Limitlvl5,
    LocationName.Limitlvl6,
    LocationName.Limitlvl7,
    LocationName.Masterlvl2,
    LocationName.Masterlvl3,
    LocationName.Masterlvl4,
    LocationName.Masterlvl5,
    LocationName.Masterlvl6,
    LocationName.Masterlvl7,
    LocationName.Finallvl2,
    LocationName.Finallvl3,
    LocationName.Finallvl4,
    LocationName.Finallvl5,
    LocationName.Finallvl6,
    LocationName.Finallvl7,
    ]
popupChecks=[
        LocationName.SweetMemories,
        LocationName.SpookyCaveMap,
        LocationName.StarryHillCureElement,
        LocationName.StarryHillOrichalcumPlus,
        LocationName.AgrabahMap,
        LocationName.LampCharm,
        LocationName.WishingLamp,
        LocationName.DarkThornCureElement,
        LocationName.RumblingRose,
        LocationName.CastleWallsMap,
        LocationName.SecretAnsemReport4,
        LocationName.DisneyCastleMap, 
        LocationName.WindowofTimeMap,
        LocationName.Monochrome,
        LocationName.WisdomForm,
        LocationName.LingeringWillProofofConnection,
        LocationName.LingeringWillManifestIllusion, 
        LocationName.OogieBoogieMagnetElement,
        LocationName.Present,
        LocationName.DecoyPresents,
        LocationName.DecisivePumpkin,
        LocationName.MarketplaceMap,
        LocationName.MerlinsHouseMembershipCard,
        LocationName.MerlinsHouseBlizzardElement,
        LocationName.BaseballCharm,
        LocationName.AnsemsStudyMasterForm,  
        LocationName.AnsemsStudySleepingLion,
        LocationName.FFFightsCureElement,
        LocationName.ThousandHeartlessSecretAnsemReport1,
        LocationName.ThousandHeartlessIceCream,
        LocationName.ThousandHeartlessPicture, 
        LocationName.WinnersProof,
        LocationName.ProofofPeace,
        LocationName.SephirothFenrir,
        LocationName.EncampmentAreaMap,
        LocationName.Mission3,
        LocationName.VillageCaveAreaMap,
        LocationName.HiddenDragon,
        LocationName.ColiseumMap,
        LocationName.OlympusStone,
        LocationName.HerosCrest,
        LocationName.AuronsStatue, 
        LocationName.GuardianSoul,
        LocationName.ProtectBeltPainandPanicCup,
        LocationName.SerenityGemPainandPanicCup,
        LocationName.RisingDragonCerberusCup ,
        LocationName.SerenityCrystalCerberusCup,
        LocationName.GenjiShieldTitanCup,
        LocationName.SkillfulRingTitanCup,
        LocationName.FatalCrestGoddessofFateCup,
        LocationName.OrichalcumPlusGoddessofFateCup,
        LocationName.HadesCupTrophyParadoxCups,
        LocationName.IsladeMuertaMap,
        LocationName.FollowtheWind,
        LocationName.SeadriftRowShipGraveyardMap,
        LocationName.SecretAnsemReport6,
        LocationName.CircleofLife,
        LocationName.ScarFireElement,
        LocationName.TwilightTownMap,
        LocationName.MunnyPouchOlette,
        LocationName.JunkChampionBelt,  
        LocationName.JunkMedal,         
        LocationName.TheStruggleTrophy,
        LocationName.NaminesSketches,
        LocationName.MansionMap,
        LocationName.PhotonDebugger,
        LocationName.StationPlazaSecretAnsemReport2,
        LocationName.MunnyPouchMickey,              
        LocationName.CrystalOrb,
        LocationName.StarSeeker,
        LocationName.ValorForm,
        LocationName.SeifersTrophy,
        LocationName.Oathkeeper,   
        LocationName.LimitForm,    
        LocationName.BeamSecretAnsemReport10,
        LocationName.BetwixtandBetweenBondofFlame,
        LocationName.TwoBecomeOne,
        LocationName.RoxasSecretAnsemReport8,
        LocationName.XigbarSecretAnsemReport3,
        LocationName.Oblivion,
        LocationName.CastleThatNeverWasMap,
        LocationName.LuxordSecretAnsemReport9,
        LocationName.SaixSecretAnsemReport12, 
        LocationName.PreXemnas1SecretAnsemReport11,
        LocationName.Xemnas1SecretAnsemReport13,
        LocationName.XemnasDataPowerBoost,
        LocationName.AxelDataMagicBoost,
        LocationName.RoxasDataMagicBoost,
        LocationName.SaixDataDefenseBoost,
        LocationName.DemyxDataAPBoost ,
        LocationName.LuxordDataAPBoost,
        LocationName.VexenDataLostIllusion,
        LocationName.LarxeneDataLostIllusion,
        LocationName.XaldinDataDefenseBoost,
        LocationName.MarluxiaDataLostIllusion,  
        LocationName.LexaeusDataLostIllusion,
        LocationName.XigbarDataDefenseBoost,
        LocationName.VexenASRoadtoDiscovery,
        LocationName.LarxeneASCloakedThunder,
        LocationName.ZexionASBookofShadows,
        LocationName.LexaeusASStrengthBeyondStrength,
        LocationName.MarluxiaASEternalBlossom
    ]
getBonus=[
   "Xemnas 1 Bonus",
   "Thresholder",
   "Dark Thorn Bonus",
   "Xaldin Bonus",
   "Cerberus",
   "Pete (OC)",
   "Hydra",
   "Hades",
   "Shan-Yu",
   "Beast",
   "Storm Rider",
   "Bailey",
   "Boat Pete",
   "Village Cave",
   "Future Pete",
   "Prison Keeper",
   "Oogie Boogie",
   "Experiment",
   "Barbossa",
   "Grim Reaper 2",
   "Xigbar",
   "Luxord",
   "Saix",
   "Demyx (Hollow Bastion)",
   "Scar",
   "Groundshaker",
   "Hostile Program",
   "MCP",
   "Sephiroth Bonus",
   "Elemental Lords",
   "Minnie Escort",
   "Interceptor Barrels",
   "Lock, Shock, and Barrel",
   "Abu Escort",
   "Screens",
   "Treasure Room",
   "Genie Jafar",
   "Hyenas 1",
   "Hyenas 2",
   "Mansion Nobodies",
   "Urns",
   "Demyx OC",
   "Grim Reaper 1",
   "1000 Heartless",
   "Solar Sailer",
   "Boat Fight",
   "Betwixt and Between",
   "Vexen Bonus",
   "Lexaeus Bonus",
   "Zexion Bonus",
   "Marluxia Bonus",
   "Larxene Bonus",
   "Roxas",
   "Lingering Will Bonus",
   "Final Xemnas",
   "Transport to Remembrance", 
   

]

all_locations={
    **TWTNW_Checks,
    **TWTNW2_Checks,
    **TT_Checks,
    **TT2_Checks,
    **TT3_Checks,
    **STT_Checks,
    **PL_Checks,
    **PL2_Checks,
    **CoR_Checks,
    **FirstHalf_Checks,
    **SecondHalf_Checks,
    **HB_Checks,
    **HB2_Checks,
    **HT_Checks,
    **HT2_Checks,
    **PR_Checks,
    **PR2_Checks,
    **PR_Checks,
    **PR2_Checks,
    **SP_Checks,
    **SP2_Checks,
    **BC_Checks,
    **BC2_Checks,
    **Oc_Checks,
    **Oc2_Checks,
    **Oc2Cups,
    **HadesCups,
    **HundredAcre1_Checks,
    **HundredAcre2_Checks,
    **HundredAcre3_Checks,
    **HundredAcre4_Checks,
    **HundredAcre5_Checks,
    **HundredAcre6_Checks,
    **DC_Checks,
    **TR_Checks,
    **AG_Checks,
    **AG2_Checks,
    **LoD_Checks,
    **LoD2_Checks,
    **SoraLevels,
    **Form_Checks,
    **GoA_Checks,
    }

location_table={}

def setup_locations(world,player:int):
    location_table={**TWTNW_Checks,**TWTNW2_Checks,**TT_Checks,**TT2_Checks,**TT3_Checks,**STT_Checks,
                    **PL_Checks,**PL2_Checks,**CoR_Checks,**FirstHalf_Checks,**SecondHalf_Checks,**HB_Checks,**HB2_Checks,
                    **PR_Checks,**PR2_Checks,**PR_Checks,**PR2_Checks,**SP_Checks,**SP2_Checks,**BC_Checks,**BC2_Checks,**HT_Checks,**HT2_Checks,
                    **Oc_Checks,**Oc2_Checks,**HadesCups,**Oc2Cups,
                    **HundredAcre1_Checks,**HundredAcre2_Checks,**HundredAcre3_Checks,**HundredAcre4_Checks,**HundredAcre5_Checks,**HundredAcre6_Checks,
                    **DC_Checks,**TR_Checks,**AG_Checks,**AG2_Checks,**LoD_Checks,**LoD2_Checks,**SoraLevels,**Form_Checks,**GoA_Checks}
    return location_table
lookup_id_to_Location: typing.Dict[int,str] = {data.code: item_name for item_name, data in location_table.items() if data.code}