# APWorld for DOOM II
#
# This file is automatically generated by ap_gen_tool version 2.0.
# For more information: https://github.com/ArchipelagoDoom/ap_gen_tool

# Options docstrings may exceed the line length limit.
# ruff: noqa: E501

from dataclasses import dataclass

import Options as BaseOptions
from worlds._id1common import options as id1Options  # noqa: N812


class GoalNumLevels(BaseOptions.Range):
    """
    If 'Complete Some Levels' or 'Complete Random Levels' are chosen as the goal, this is how many levels must be completed.
    """
    display_name = "Goal: Number of Levels"
    range_start = 1
    range_end = 32
    default = 32


class GoalSpecificLevels(BaseOptions.OptionSet):
    """
    If 'Complete Specific Levels' is chosen as the goal, all levels chosen here must be completed.
    """
    display_name = "Goal: Specific Levels"
    valid_keys = (
        "Entryway (MAP01)",
        "Underhalls (MAP02)",
        "The Gantlet (MAP03)",
        "The Focus (MAP04)",
        "The Waste Tunnels (MAP05)",
        "The Crusher (MAP06)",
        "Dead Simple (MAP07)",
        "Tricks and Traps (MAP08)",
        "The Pit (MAP09)",
        "Refueling Base (MAP10)",
        "Circle of Death (MAP11)",
        "The Factory (MAP12)",
        "Downtown (MAP13)",
        "The Inmost Dens (MAP14)",
        "Industrial Zone (MAP15)",
        "Suburbs (MAP16)",
        "Tenements (MAP17)",
        "The Courtyard (MAP18)",
        "The Citadel (MAP19)",
        "Gotcha! (MAP20)",
        "Nirvana (MAP21)",
        "The Catacombs (MAP22)",
        "Barrels o' Fun (MAP23)",
        "The Chasm (MAP24)",
        "Bloodfalls (MAP25)",
        "The Abandoned Mines (MAP26)",
        "Monster Condo (MAP27)",
        "The Spirit World (MAP28)",
        "The Living End (MAP29)",
        "Icon of Sin (MAP30)",
        "Wolfenstein (MAP31)",
        "Grosse (MAP32)",
    )
    default = frozenset({
        "Circle of Death (MAP11)",
        "Gotcha! (MAP20)",
        "Icon of Sin (MAP30)",
    })


class Episode1(id1Options.DefaultEpisode):
    """
    Subterranean Outpost.

    This episode includes the following levels:

    - Entryway (MAP01)
    - Underhalls (MAP02)
    - The Gantlet (MAP03)
    - The Focus (MAP04)
    - The Waste Tunnels (MAP05)
    - The Crusher (MAP06)
    - Dead Simple (MAP07)
    - Tricks and Traps (MAP08)
    - The Pit (MAP09)
    - Refueling Base (MAP10)
    - Circle of Death (MAP11)
    """
    display_name = "Episode 1"


class Episode2(id1Options.DefaultEpisode):
    """
    The City.

    This episode includes the following levels:

    - The Factory (MAP12)
    - Downtown (MAP13)
    - The Inmost Dens (MAP14)
    - Industrial Zone (MAP15)
    - Suburbs (MAP16)
    - Tenements (MAP17)
    - The Courtyard (MAP18)
    - The Citadel (MAP19)
    - Gotcha! (MAP20)
    """
    display_name = "Episode 2"


class Episode3(id1Options.DefaultEpisode):
    """
    Hell.

    This episode includes the following levels:

    - Nirvana (MAP21)
    - The Catacombs (MAP22)
    - Barrels o' Fun (MAP23)
    - The Chasm (MAP24)
    - Bloodfalls (MAP25)
    - The Abandoned Mines (MAP26)
    - Monster Condo (MAP27)
    - The Spirit World (MAP28)
    - The Living End (MAP29)
    - Icon of Sin (MAP30)
    """
    display_name = "Episode 3"


class Episode4(id1Options.MinorEpisode):
    """
    Secret Levels.

    This is a minor episode. Another episode must be played alongside this one.
    This episode includes the following levels:

    - Wolfenstein (MAP31)
    - Grosse (MAP32)
    """
    display_name = "Episode 4"


class MaxAmmoBullets(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Bullets.

    Setting this below the default of 200 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Bullets"
    random_start = 200
    range_start = 20
    range_end = 999
    default = 200


class MaxAmmoShells(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Shells.

    Setting this below the default of 50 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Shells"
    random_start = 50
    range_start = 5
    range_end = 999
    default = 50


class MaxAmmoEnergyCells(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Energy Cells.

    Setting this below the default of 300 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Energy Cells"
    random_start = 300
    range_start = 30
    range_end = 999
    default = 300


class MaxAmmoRockets(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Rockets.

    Setting this below the default of 50 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Rockets"
    random_start = 50
    range_start = 5
    range_end = 999
    default = 50


class AddedAmmoBullets(BaseOptions.Range):
    """
    Set how much capacity for Bullets will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Bullets"
    range_start = 20
    range_end = 999
    default = 200


class AddedAmmoShells(BaseOptions.Range):
    """
    Set how much capacity for Shells will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Shells"
    range_start = 5
    range_end = 999
    default = 50


class AddedAmmoEnergyCells(BaseOptions.Range):
    """
    Set how much capacity for Energy Cells will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Energy Cells"
    range_start = 30
    range_end = 999
    default = 300


class AddedAmmoRockets(BaseOptions.Range):
    """
    Set how much capacity for Rockets will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Rockets"
    range_start = 5
    range_end = 999
    default = 50


@dataclass
class DOOM2Options(id1Options.id1CommonOptions):
    goal_num_levels: GoalNumLevels  # type: ignore[assignment]
    goal_specific_levels: GoalSpecificLevels  # type: ignore[assignment]
    episode1: Episode1
    episode2: Episode2
    episode3: Episode3
    episode4: Episode4
    difficulty: id1Options.DifficultyDoom  # type: ignore[assignment]
    start_with_computer_area_maps: id1Options.StartWithComputerAreaMaps
    partial_invisibility_as_trap: id1Options.PartialInvisibilityAsTrap
    split_backpack: id1Options.SplitBackpack
    backpack_count: id1Options.BackpackCount
    max_ammo_bullets: MaxAmmoBullets
    max_ammo_shells: MaxAmmoShells
    max_ammo_energy_cells: MaxAmmoEnergyCells
    max_ammo_rockets: MaxAmmoRockets
    added_ammo_bullets: AddedAmmoBullets
    added_ammo_shells: AddedAmmoShells
    added_ammo_energy_cells: AddedAmmoEnergyCells
    added_ammo_rockets: AddedAmmoRockets


DOOM2OptionGroups = [
    BaseOptions.OptionGroup("Episodes to Play", [
        Episode1,
        Episode2,
        Episode3,
        Episode4,
    ]),
    BaseOptions.OptionGroup("Goal Options", [
        id1Options.Goal,
        GoalNumLevels,
        GoalSpecificLevels,
    ]),
    BaseOptions.OptionGroup("Difficulty Options", [
        id1Options.DifficultyDoom,
        id1Options.TrickDifficulty,
        id1Options.AllowDeathLogic,
        id1Options.ResetLevelOnDeath,
        BaseOptions.DeathLink,
    ]),
    BaseOptions.OptionGroup("Randomizer Options", [
        BaseOptions.ProgressionBalancing,
        BaseOptions.Accessibility,
        id1Options.RandomMonsters,
        id1Options.RandomPickups,
        id1Options.RandomMusic,
        id1Options.FlipLevels,
        id1Options.StartWithComputerAreaMaps,
        id1Options.PartialInvisibilityAsTrap,
        id1Options.SplitBackpack,
        id1Options.BackpackCount,
    ]),
    BaseOptions.OptionGroup("Ammo Capacity", [
        MaxAmmoBullets,
        MaxAmmoShells,
        MaxAmmoEnergyCells,
        MaxAmmoRockets,
        AddedAmmoBullets,
        AddedAmmoShells,
        AddedAmmoEnergyCells,
        AddedAmmoRockets,
    ]),
]

