# APWorld for DOOM 1993
#
# This file is automatically generated by ap_gen_tool version 2.0.
# For more information: https://github.com/ArchipelagoDoom/ap_gen_tool

# Options docstrings may exceed the line length limit.
# ruff: noqa: E501

from dataclasses import dataclass

import Options as BaseOptions
from worlds._id1common import options as id1Options  # noqa: N812


class GoalNumLevels(BaseOptions.Range):
    """
    If 'Complete Some Levels' or 'Complete Random Levels' are chosen as the goal, this is how many levels must be completed.
    """
    display_name = "Goal: Number of Levels"
    range_start = 1
    range_end = 36
    default = 36


class GoalSpecificLevels(BaseOptions.OptionSet):
    """
    If 'Complete Specific Levels' is chosen as the goal, all levels chosen here must be completed.
    """
    display_name = "Goal: Specific Levels"
    valid_keys = (
        "Hangar (E1M1)",
        "Nuclear Plant (E1M2)",
        "Toxin Refinery (E1M3)",
        "Command Control (E1M4)",
        "Phobos Lab (E1M5)",
        "Central Processing (E1M6)",
        "Computer Station (E1M7)",
        "Phobos Anomaly (E1M8)",
        "Military Base (E1M9)",
        "Deimos Anomaly (E2M1)",
        "Containment Area (E2M2)",
        "Refinery (E2M3)",
        "Deimos Lab (E2M4)",
        "Command Center (E2M5)",
        "Halls of the Damned (E2M6)",
        "Spawning Vats (E2M7)",
        "Tower of Babel (E2M8)",
        "Fortress of Mystery (E2M9)",
        "Hell Keep (E3M1)",
        "Slough of Despair (E3M2)",
        "Pandemonium (E3M3)",
        "House of Pain (E3M4)",
        "Unholy Cathedral (E3M5)",
        "Mt. Erebus (E3M6)",
        "Limbo (E3M7)",
        "Dis (E3M8)",
        "Warrens (E3M9)",
        "Hell Beneath (E4M1)",
        "Perfect Hatred (E4M2)",
        "Sever the Wicked (E4M3)",
        "Unruly Evil (E4M4)",
        "They Will Repent (E4M5)",
        "Against Thee Wickedly (E4M6)",
        "And Hell Followed (E4M7)",
        "Unto the Cruel (E4M8)",
        "Fear (E4M9)",
    )
    default = frozenset({
        "Phobos Anomaly (E1M8)",
        "Tower of Babel (E2M8)",
        "Dis (E3M8)",
        "Unto the Cruel (E4M8)",
    })


class Episode1(id1Options.DefaultEpisode):
    """
    Knee-Deep in the Dead.

    This episode includes the following levels:

    - Hangar (E1M1)
    - Nuclear Plant (E1M2)
    - Toxin Refinery (E1M3)
    - Command Control (E1M4)
    - Phobos Lab (E1M5)
    - Central Processing (E1M6)
    - Computer Station (E1M7)
    - Phobos Anomaly (E1M8)
    - Military Base (E1M9)
    """
    display_name = "Episode 1"


class Episode2(id1Options.DefaultEpisode):
    """
    The Shores of Hell.

    This episode includes the following levels:

    - Deimos Anomaly (E2M1)
    - Containment Area (E2M2)
    - Refinery (E2M3)
    - Deimos Lab (E2M4)
    - Command Center (E2M5)
    - Halls of the Damned (E2M6)
    - Spawning Vats (E2M7)
    - Tower of Babel (E2M8)
    - Fortress of Mystery (E2M9)
    """
    display_name = "Episode 2"


class Episode3(id1Options.DefaultEpisode):
    """
    Inferno.

    This episode includes the following levels:

    - Hell Keep (E3M1)
    - Slough of Despair (E3M2)
    - Pandemonium (E3M3)
    - House of Pain (E3M4)
    - Unholy Cathedral (E3M5)
    - Mt. Erebus (E3M6)
    - Limbo (E3M7)
    - Dis (E3M8)
    - Warrens (E3M9)
    """
    display_name = "Episode 3"


class Episode4(id1Options.Episode):
    """
    Thy Flesh Consumed.

    This episode includes the following levels:

    - Hell Beneath (E4M1)
    - Perfect Hatred (E4M2)
    - Sever the Wicked (E4M3)
    - Unruly Evil (E4M4)
    - They Will Repent (E4M5)
    - Against Thee Wickedly (E4M6)
    - And Hell Followed (E4M7)
    - Unto the Cruel (E4M8)
    - Fear (E4M9)
    """
    display_name = "Episode 4"


class MaxAmmoBullets(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Bullets.

    Setting this below the default of 200 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Bullets"
    random_start = 200
    range_start = 20
    range_end = 999
    default = 200


class MaxAmmoShells(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Shells.

    Setting this below the default of 50 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Shells"
    random_start = 50
    range_start = 5
    range_end = 999
    default = 50


class MaxAmmoEnergyCells(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Energy Cells.

    Setting this below the default of 300 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Energy Cells"
    random_start = 300
    range_start = 30
    range_end = 999
    default = 300


class MaxAmmoRockets(id1Options.BoundedRandomRange):
    """
    Set the starting capacity for Rockets.

    Setting this below the default of 50 is allowed, but may be logically unsafe.
    """
    display_name = "Max Ammo - Rockets"
    random_start = 50
    range_start = 5
    range_end = 999
    default = 50


class AddedAmmoBullets(BaseOptions.Range):
    """
    Set how much capacity for Bullets will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Bullets"
    range_start = 20
    range_end = 999
    default = 200


class AddedAmmoShells(BaseOptions.Range):
    """
    Set how much capacity for Shells will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Shells"
    range_start = 5
    range_end = 999
    default = 50


class AddedAmmoEnergyCells(BaseOptions.Range):
    """
    Set how much capacity for Energy Cells will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Energy Cells"
    range_start = 30
    range_end = 999
    default = 300


class AddedAmmoRockets(BaseOptions.Range):
    """
    Set how much capacity for Rockets will be added when a capacity upgrade is obtained.
    """
    display_name = "Added Ammo - Rockets"
    range_start = 5
    range_end = 999
    default = 50


@dataclass
class DOOM1993Options(id1Options.id1CommonOptions):
    goal_num_levels: GoalNumLevels  # type: ignore[assignment]
    goal_specific_levels: GoalSpecificLevels  # type: ignore[assignment]
    episode1: Episode1
    episode2: Episode2
    episode3: Episode3
    episode4: Episode4
    difficulty: id1Options.DifficultyDoom  # type: ignore[assignment]
    start_with_computer_area_maps: id1Options.StartWithComputerAreaMaps
    partial_invisibility_as_trap: id1Options.PartialInvisibilityAsTrap
    split_backpack: id1Options.SplitBackpack
    backpack_count: id1Options.BackpackCount
    max_ammo_bullets: MaxAmmoBullets
    max_ammo_shells: MaxAmmoShells
    max_ammo_energy_cells: MaxAmmoEnergyCells
    max_ammo_rockets: MaxAmmoRockets
    added_ammo_bullets: AddedAmmoBullets
    added_ammo_shells: AddedAmmoShells
    added_ammo_energy_cells: AddedAmmoEnergyCells
    added_ammo_rockets: AddedAmmoRockets


DOOM1993OptionGroups = [
    BaseOptions.OptionGroup("Episodes to Play", [
        Episode1,
        Episode2,
        Episode3,
        Episode4,
    ]),
    BaseOptions.OptionGroup("Goal Options", [
        id1Options.Goal,
        GoalNumLevels,
        GoalSpecificLevels,
    ]),
    BaseOptions.OptionGroup("Difficulty Options", [
        id1Options.DifficultyDoom,
        id1Options.TrickDifficulty,
        id1Options.AllowDeathLogic,
        id1Options.ResetLevelOnDeath,
        BaseOptions.DeathLink,
    ]),
    BaseOptions.OptionGroup("Randomizer Options", [
        BaseOptions.ProgressionBalancing,
        BaseOptions.Accessibility,
        id1Options.RandomMonsters,
        id1Options.RandomPickups,
        id1Options.RandomMusic,
        id1Options.FlipLevels,
        id1Options.StartWithComputerAreaMaps,
        id1Options.PartialInvisibilityAsTrap,
        id1Options.SplitBackpack,
        id1Options.BackpackCount,
    ]),
    BaseOptions.OptionGroup("Ammo Capacity", [
        MaxAmmoBullets,
        MaxAmmoShells,
        MaxAmmoEnergyCells,
        MaxAmmoRockets,
        AddedAmmoBullets,
        AddedAmmoShells,
        AddedAmmoEnergyCells,
        AddedAmmoRockets,
    ]),
]

