from . import LingoTestBase


class TestProgressiveOrangeTower(LingoTestBase):
    options = {
        "shuffle_doors": "complex",
        "progressive_orange_tower": "true"
    }

    def test_from_welcome_back(self) -> None:
        assert not self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect_by_name("Welcome Back Area - Shortcut to Starting Room")
        self.collect_by_name("Orange Tower Fifth Floor - Welcome Back")
        assert not self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        progressive_tower = self.get_items_by_name("Progressive Orange Tower")

        self.collect(progressive_tower[0])
        assert not self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect(progressive_tower[1])
        assert not self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect(progressive_tower[2])
        assert not self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect(progressive_tower[3])
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect(progressive_tower[4])
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect(progressive_tower[5])
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

    def test_from_hub_room(self) -> None:
        assert not self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect_by_name("Starting Room - Main Door")
        self.collect_by_name("Second Room - Exit Door")
        assert not self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect_by_name("Orange Tower First Floor - Shortcut to Hub Room")
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        progressive_tower = self.get_items_by_name("Progressive Orange Tower")

        self.collect(progressive_tower[0])
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.remove(self.get_item_by_name("Orange Tower First Floor - Shortcut to Hub Room"))
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect(progressive_tower[1])
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect(progressive_tower[2])
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect(progressive_tower[3])
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect(progressive_tower[4])
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert not self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)

        self.collect(progressive_tower[5])
        assert self.multiworld.state.can_reach("Orange Tower First Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Second Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Third Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fourth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Fifth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Sixth Floor", "Region", self.player)
        assert self.multiworld.state.can_reach("Orange Tower Seventh Floor", "Region", self.player)
