from enum import Enum

from worlds.pokepark import BERRIES, FRIENDSHIP_ITEMS, POWERS, UNLOCK_ITEMS


class MinigameLocationIds(Enum):
    # Bulbasaur's Daring Dash
    PIKACHU_DASH = BERRIES["100 Berries"] + 1
    TURTWIG_DASH = BERRIES["100 Berries"] + 2
    MUNCHLAX_DASH = BERRIES["100 Berries"] + 3
    CHIMCHAR_DASH = BERRIES["100 Berries"] + 4
    TREECKO_DASH = BERRIES["100 Berries"] + 5
    BIBAREL_DASH = BERRIES["100 Berries"] + 6
    BULBASAUR_DASH = BERRIES["100 Berries"] + 7
    BIDOOF_DASH = BERRIES["100 Berries"] + 8
    ODDISH_DASH = BERRIES["100 Berries"] + 9
    SHROOMISH_DASH = BERRIES["100 Berries"] + 10
    BONSLY_DASH = BERRIES["100 Berries"] + 11
    LOTAD_DASH = BERRIES["100 Berries"] + 12
    WEEDLE_DASH = BERRIES["100 Berries"] + 13
    CATERPIE_DASH = BERRIES["100 Berries"] + 14
    MAGIKARP_DASH = BERRIES["100 Berries"] + 15
    JOLTEON_DASH = BERRIES["100 Berries"] + 16  # Not implemented
    ARCANINE_DASH = BERRIES["100 Berries"] + 17  # Not implemented
    LEAFEON_DASH = BERRIES["100 Berries"] + 18
    SCYTHER_DASH = BERRIES["100 Berries"] + 19
    PONYTA_DASH = BERRIES["100 Berries"] + 20  # Not implemented
    SHINX_DASH = BERRIES["100 Berries"] + 21
    EEVEE_DASH = BERRIES["100 Berries"] + 22  # Not implemented
    PACHIRISU_DASH = BERRIES["100 Berries"] + 23
    BUNEARY_DASH = BERRIES["100 Berries"] + 24
    CROAGUNK_DASH = BERRIES["100 Berries"] + 25

    # Venusaur's Vine Swing
    PIKACHU_VINE_SWING = BERRIES["100 Berries"] + 26
    MUNCHLAX_VINE_SWING = BERRIES["100 Berries"] + 27
    MAGIKARP_VINE_SWING = BERRIES["100 Berries"] + 28
    BLAZIKEN_VINE_SWING = BERRIES["100 Berries"] + 29  # Not implemented
    INFERNAPE_VINE_SWING = BERRIES["100 Berries"] + 30  # Not implemented
    LUCARIO_VINE_SWING = BERRIES["100 Berries"] + 31  # Not implemented
    PRIMEAPE_VINE_SWING = BERRIES["100 Berries"] + 32  # Not implemented
    TANGROWTH_VINE_SWING = BERRIES["100 Berries"] + 33  # Not implemented
    AMBIPOM_VINE_SWING = BERRIES["100 Berries"] + 34
    CROAGUNK_VINE_SWING = BERRIES["100 Berries"] + 35
    MANKEY_VINE_SWING = BERRIES["100 Berries"] + 36
    AIPOM_VINE_SWING = BERRIES["100 Berries"] + 37
    CHIMCHAR_VINE_SWING = BERRIES["100 Berries"] + 38
    TREECKO_VINE_SWING = BERRIES["100 Berries"] + 39
    PACHIRISU_VINE_SWING = BERRIES["100 Berries"] + 40

    # Pelipper's Circle Circuit
    PIKACHU_CIRCLE = BERRIES["100 Berries"] + 41
    STARAPTOR_CIRCLE = BERRIES["100 Berries"] + 42  # Not implemented
    TOGEKISS_CIRCLE = BERRIES["100 Berries"] + 43  # Not implemented
    HONCHKROW_CIRCLE = BERRIES["100 Berries"] + 44  # Not implemented
    GLISCOR_CIRCLE = BERRIES["100 Berries"] + 45  # Not implemented
    PELIPPER_CIRCLE = BERRIES["100 Berries"] + 46
    STARAVIA_CIRCLE = BERRIES["100 Berries"] + 47
    PIDGEOTTO_CIRCLE = BERRIES["100 Berries"] + 48
    BUTTERFREE_CIRCLE = BERRIES["100 Berries"] + 49
    TROPIUS_CIRCLE = BERRIES["100 Berries"] + 50
    MURKROW_CIRCLE = BERRIES["100 Berries"] + 51  # Not implemented
    TAILLOW_CIRCLE = BERRIES["100 Berries"] + 52
    SPEAROW_CIRCLE = BERRIES["100 Berries"] + 53
    STARLY_CIRCLE = BERRIES["100 Berries"] + 54
    WINGULL_CIRCLE = BERRIES["100 Berries"] + 55

    # Gyarados' Aqua Dash
    PIKACHU_AQUA = BERRIES["100 Berries"] + 56
    PSYDUCK_AQUA = BERRIES["100 Berries"] + 57
    AZURILL_AQUA = BERRIES["100 Berries"] + 58
    SLOWPOKE_AQUA = BERRIES["100 Berries"] + 59
    EMPOLEON_AQUA = BERRIES["100 Berries"] + 60  # Not implemented
    FLOATZEL_AQUA = BERRIES["100 Berries"] + 61
    FERALIGATR_AQUA = BERRIES["100 Berries"] + 62
    GOLDUCK_AQUA = BERRIES["100 Berries"] + 63
    VAPOREON_AQUA = BERRIES["100 Berries"] + 64
    PRINPLUP_AQUA = BERRIES["100 Berries"] + 65  # Not implemented
    BIBAREL_AQUA = BERRIES["100 Berries"] + 66
    BUIZEL_AQUA = BERRIES["100 Berries"] + 67
    CORSOLA_AQUA = BERRIES["100 Berries"] + 68
    PIPLUP_AQUA = BERRIES["100 Berries"] + 69
    LOTAD_AQUA = BERRIES["100 Berries"] + 70

    #Empoleon's Snow Slide
    PIKACHU_SLIDE = BERRIES["100 Berries"]+71
    TEDDIURSA_SLIDE = BERRIES["100 Berries"]+72
    MAGIKARP_SLIDE = BERRIES["100 Berries"]+73
    EMPOLEON_SLIDE = BERRIES["100 Berries"]+74
    GLACEON_SLIDE = BERRIES["100 Berries"]+ 75
    BLASTOISE_SLIDE = BERRIES["100 Berries"]+ 76
    GLALIE_SLIDE = BERRIES["100 Berries"]+77
    LAPRAS_SLIDE = BERRIES["100 Berries"]+78
    DELIBIRD_SLIDE = BERRIES["100 Berries"] + 79
    PILOSWINE_SLIDE = BERRIES["100 Berries"]+ 80
    PRINPLUP_SLIDE = BERRIES["100 Berries"]+ 81
    SQUIRTLE_SLIDE = BERRIES["100 Berries"]+ 82
    PIPLUP_SLIDE = BERRIES["100 Berries"]+ 83
    QUAGSIRE_SLIDE = BERRIES["100 Berries"]+ 84
    SPHEAL_SLIDE = BERRIES["100 Berries"]+ 85

    # Bastiodon's Panel Crush
    PIKACHU_PANEL = BERRIES["100 Berries"]+ 86
    SABLEYE_PANEL = BERRIES["100 Berries"]+ 87
    MEOWTH_PANEL = BERRIES["100 Berries"]+ 88
    TORCHIC_PANEL = BERRIES["100 Berries"]+ 89
    ELECTIVIRE_PANEL = BERRIES["100 Berries"]+ 90
    MAGMORTAR_PANEL = BERRIES["100 Berries"]+ 91
    HITMONLEE_PANEL = BERRIES["100 Berries"]+ 92
    URSARING_PANEL = BERRIES["100 Berries"]+ 93
    MRMIME_PANEL = BERRIES["100 Berries"]+ 94
    RAICHU_PANEL = BERRIES["100 Berries"]+ 95
    SUDOWOODO_PANEL = BERRIES["100 Berries"]+ 96
    CHARMANDER_PANEL = BERRIES["100 Berries"]+97
    GIBLE_PANEL = BERRIES["100 Berries"]+98
    CHIMCHAR_PANEL = BERRIES["100 Berries"]+99
    MAGBY_PANEL = BERRIES["100 Berries"]+100

    # Rhyperior's Bumper Burn
    PIKACHU_BUMPER = BERRIES["100 Berries"]+101
    MAGNEMITE_BUMPER = BERRIES["100 Berries"]+102
    RHYPERIOR_BUMPER = BERRIES["100 Berries"]+103
    TYRANITAR_BUMPER = BERRIES["100 Berries"]+104
    HITMONTOP_BUMPER = BERRIES["100 Berries"]+105
    FLAREON_BUMPER = BERRIES["100 Berries"]+106
    VENUSAUR_BUMPER =BERRIES["100 Berries"]+107
    SNORLAX_BUMPER =BERRIES["100 Berries"]+108
    TORTERRA_BUMPER =BERRIES["100 Berries"]+109
    MAGNEZONE_BUMPER =BERRIES["100 Berries"]+110
    CLAYDOL_BUMPER =BERRIES["100 Berries"]+111
    QUILAVA_BUMPER = BERRIES["100 Berries"]+112
    TORKOAL_BUMPER = BERRIES["100 Berries"] +113
    BALTOY_BUMPER = BERRIES["100 Berries"]+114
    BONSLY_BUMPER = BERRIES["100 Berries"]+115

    # Blaziken's Boulder Bash
    PIKACHU_BOULDER = BERRIES["100 Berries"] + 116
    GEODUDE_BOULDER = BERRIES["100 Berries"] + 117
    PHANPY_BOULDER = BERRIES["100 Berries"] + 118
    BLAZIKEN_BOULDER = BERRIES["100 Berries"] + 119
    GARCHOMP_BOULDER = BERRIES["100 Berries"] + 120
    SCIZOR_BOULDER = BERRIES["100 Berries"] + 121
    MAGMORTAR_BOULDER = BERRIES["100 Berries"] + 122
    HITMONCHAN_BOULDER = BERRIES["100 Berries"] + 123
    MACHAMP_BOULDER = BERRIES["100 Berries"] + 124
    MAROWAK_BOULDER = BERRIES["100 Berries"] + 125
    FARFETCHD_BOULDER = BERRIES["100 Berries"] + 126
    CRANIDOS_BOULDER = BERRIES["100 Berries"] + 127
    CAMERUPT_BOULDER = BERRIES["100 Berries"] + 128
    BASTIODON_BOULDER = BERRIES["100 Berries"] + 129
    MAWILE_BOULDER = BERRIES["100 Berries"] + 130

    # Tangrowth's Swing-Along
    PIKACHU_SWING = BERRIES["100 Berries"] + 131
    MEOWTH_SWING = BERRIES["100 Berries"] + 132
    PICHU_SWING = BERRIES["100 Berries"] + 133
    LUCARIO_SWING = BERRIES["100 Berries"] + 134
    INFERNAPE_SWING = BERRIES["100 Berries"] + 135
    BLAZIKEN_SWING = BERRIES["100 Berries"] + 136
    RIOLU_SWING = BERRIES["100 Berries"] + 137
    SNEASEL_SWING = BERRIES["100 Berries"] + 138
    RAICHU_SWING = BERRIES["100 Berries"] + 139
    AMBIPOM_SWING = BERRIES["100 Berries"] + 140
    PRIMEAPE_SWING = BERRIES["100 Berries"] + 141
    AIPOM_SWING = BERRIES["100 Berries"] + 142
    ELECTABUZZ_SWING = BERRIES["100 Berries"] + 143
    CHIMCHAR_SWING = BERRIES["100 Berries"] + 144
    CROAGUNK_SWING = BERRIES["100 Berries"] + 145

    # Dusknoir's Speed Slam
    PIKACHU_SLAM = BERRIES["100 Berries"] + 146
    STUNKY_SLAM = BERRIES["100 Berries"] + 147
    GENGAR_SLAM = BERRIES["100 Berries"] + 148
    MISMAGIUS_SLAM = BERRIES["100 Berries"] + 149
    SCIZOR_SLAM = BERRIES["100 Berries"] + 150
    ESPEON_SLAM = BERRIES["100 Berries"] + 151
    DUSKNOIR_SLAM = BERRIES["100 Berries"] + 152
    UMBREON_SLAM = BERRIES["100 Berries"] + 153
    CRANIDOS_SLAM = BERRIES["100 Berries"] + 154
    SKUNTANK_SLAM = BERRIES["100 Berries"] + 155
    ELECTRODE_SLAM = BERRIES["100 Berries"] + 156
    GASTLY_SLAM = BERRIES["100 Berries"] + 157
    DUSKULL_SLAM = BERRIES["100 Berries"] + 158
    MISDREAVUS_SLAM = BERRIES["100 Berries"] + 159
    KRABBY_SLAM = BERRIES["100 Berries"] + 160

    #Rotom's Spooky Shoot-'em-Up
    PIKACHU_SHOOT = BERRIES["100 Berries"] + 161
    MAGNEMITE_SHOOT = BERRIES["100 Berries"] + 162
    PORYGONZ_SHOOT = BERRIES["100 Berries"] + 163
    MAGNEZONE_SHOOT = BERRIES["100 Berries"] + 164
    GENGAR_SHOOT = BERRIES["100 Berries"] + 165
    MAGMORTAR_SHOOT = BERRIES["100 Berries"] + 166
    ELECTIVIRE_SHOOT = BERRIES["100 Berries"] + 167
    MISMAGIUS_SHOOT = BERRIES["100 Berries"] + 168
    CLAYDOL_SHOOT = BERRIES["100 Berries"] + 169
    ELECTABUZZ_SHOOT = BERRIES["100 Berries"] + 170
    HAUNTER_SHOOT = BERRIES["100 Berries"] + 171
    ABRA_SHOOT = BERRIES["100 Berries"] + 172
    ELEKID_SHOOT = BERRIES["100 Berries"] + 173
    MRMIME_SHOOT = BERRIES["100 Berries"] + 174
    BALTOY_SHOOT = BERRIES["100 Berries"] + 175

class OverworldPokemonLocationIds(Enum):
    STARLY_BEACH = FRIENDSHIP_ITEMS["Starly"] +1000
    KRABBY_ICE = FRIENDSHIP_ITEMS["Krabby"] +1000
    CORPHISH_ICE = FRIENDSHIP_ITEMS["Corphish"] +1000
    MUDKIP_ICE = FRIENDSHIP_ITEMS["Mudkip"] +1000
    TAILLOW_ICE = FRIENDSHIP_ITEMS["Taillow"] +1000
    STARAVIA_ICE = FRIENDSHIP_ITEMS["Staravia"] +1000
    STARLY_ICE = FRIENDSHIP_ITEMS["Starly"] +2000
    WINGULL_ICE = FRIENDSHIP_ITEMS["Wingull"]+1000
    TEDDIURSA_CAVERN = FRIENDSHIP_ITEMS["Teddiursa"] + 1000
    BONSLY_CAVERN = FRIENDSHIP_ITEMS["Bonsly"] + 1000
    BONSLY_MAGMA = FRIENDSHIP_ITEMS["Bonsly"]+2000
    CHIMCHAR_CAVERN = FRIENDSHIP_ITEMS["Chimchar"] + 1000
    CHIMCHAR_MAGMA = FRIENDSHIP_ITEMS["Chimchar"]+2000
    SUDOWOODO_CAVERN = FRIENDSHIP_ITEMS["Sudowoodo"] + 1000
    MACHAMP_CAVERN_BATTLE = FRIENDSHIP_ITEMS["Machamp"] + 1000
    MAGNEMITE_CAVERN_2 = FRIENDSHIP_ITEMS["Magnemite"] + 1000
    MAGNEMITE_CAVERN_3 = FRIENDSHIP_ITEMS["Magnemite"] + 2000
    ARON_MAGMA = FRIENDSHIP_ITEMS["Aron"] +1000
    TORCHIC_MAGMA = FRIENDSHIP_ITEMS["Torchic"] +1000
    GEODUDE_MAGMA = FRIENDSHIP_ITEMS["Geodude"] + 1000
    MAGBY_MAGMA_BATTLE = FRIENDSHIP_ITEMS["Magby"] + 1000
    RAICHU_HAUNTED = FRIENDSHIP_ITEMS["Raichu"]+1000
    MEOWTH_HAUNTED = FRIENDSHIP_ITEMS["Meowth"] +1000
    AIPOM_HAUNTED = FRIENDSHIP_ITEMS["Aipom"] +1000
    AMBIPOM_HAUNTED = FRIENDSHIP_ITEMS["Ambipom"] +1000

class UnlockLocationIds(Enum):
    SUDOWOODO_CAVERN = UNLOCK_ITEMS["Sudowoodo Unlock"] + 1
    AMBIPOM_HAUNTED = UNLOCK_ITEMS["Ambipom Unlock"] +1

class QuestLocationIds(Enum):
    MEADOW_BIDOOF_HOUSING1 = BERRIES["10 Berries"] + 1
    MEADOW_BIDOOF_HOUSING2 = BERRIES["10 Berries"] + 2
    MEADOW_BIDOOF_HOUSING3 = BERRIES["10 Berries"] + 3
    MEADOW_BIDOOF_HOUSING4 = BERRIES["10 Berries"] + 4

    BEACH_BOTTLE1 = BERRIES["10 Berries"] + 5
    BEACH_BOTTLE2 = BERRIES["10 Berries"] + 6
    BEACH_BOTTLE3 = BERRIES["10 Berries"] + 7
    BEACH_BOTTLE4 = BERRIES["10 Berries"] + 8
    BEACH_BOTTLE5 = BERRIES["10 Berries"] + 9
    BEACH_BOTTLE6 = BERRIES["10 Berries"] + 10

    IGLOO_QUEST1 = BERRIES["10 Berries"] + 11
    IGLOO_QUEST2 = BERRIES["10 Berries"] + 12
    IGLOO_QUEST3 = BERRIES["10 Berries"] + 13

    CHRISTMAS_TREE1 = BERRIES["10 Berries"] + 14
    CHRISTMAS_TREE2 = BERRIES["10 Berries"] + 15
    CHRISTMAS_TREE3 = BERRIES["10 Berries"] + 16
    CHRISTMAS_TREE4 = BERRIES["10 Berries"] + 17

    MEDITITE_QUIZ = BERRIES["10 Berries"] + 18
    RHYPERIOR_DISC = BERRIES["10 Berries"] + 19


    THUNDERBOLT_POWERUP1 = POWERS["Progressive Thunderbolt"] + 1
    THUNDERBOLT_POWERUP2 = POWERS["Progressive Thunderbolt"] + 2
    THUNDERBOLT_POWERUP3 = POWERS["Progressive Thunderbolt"] + 3

    DASH_POWERUP1 = POWERS["Progressive Dash"] + 1
    DASH_POWERUP2 = POWERS["Progressive Dash"] + 2
    DASH_POWERUP3 = POWERS["Progressive Dash"] + 3

    HEALTH_POWERUP1 = POWERS["Progressive Health"] + 1
    HEALTH_POWERUP2 = POWERS["Progressive Health"] + 2
    HEALTH_POWERUP3 = POWERS["Progressive Health"] + 3

    IRON_TAIL_POWERUP1 = POWERS["Progressive Iron Tail"] +1
    IRON_TAIL_POWERUP2 = POWERS["Progressive Iron Tail"] +2
    IRON_TAIL_POWERUP3 = POWERS["Progressive Iron Tail"] +3

