"""Logic file for Gorgeous Music Castle."""

from .mn64_logic_classes import MN64DoorType, MN64HintRegion, MN64Items, MN64Levels, MN64LocationLogic, MN64Region, MN64TransitionFront

LogicRegions = {
    "GorgeousMusicCastleEntrance": MN64Region(
        name="Gorgeous Music Castle Entrance",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleFlameHallwayLower",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleSuddenImpactRoomLower",
                lambda l: l.has_gold_key(),
                type=MN64DoorType.DOOR,
                consumes_key="gold",
            ),
            MN64TransitionFront("UgoStoneCircle", lambda l: l.all_miracle_items, type=MN64DoorType.DOOR),
        ],
        room_id=0x0A8,
        room_default_definitions=[
            0x05D,
            0x3BC,
            0x191,
            0x152,
            0x02B,
            0x1F9,
            0x15C,
            0x1A4,
            0x024,
            0x1CC,
        ],
        enemies={0x06: 0x13F, 0x07: 0x13F, 0x08: 0x13F, 0x09: 0x13F},
    ),
    "GorgeousMusicCastleSuddenImpactRoomLower": MN64Region(
        name="Gorgeous Music Castle Sudden Impact Room (Lower)",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleEntrance", lambda l: True, type=MN64DoorType.DOOR),
            MN64TransitionFront(
                "GorgeousMusicCastleClosingFanRoom",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0AE,
        room_default_definitions=[
            0x05D,
            0x3C2,
            0x191,
            0x152,
            0x1D8,
            0x15D,
            0x31C,
            0x17F,
            0x02B,
            0x1F9,
            0x15C,
            0x020,
            0x19D,
            0x038,
            0x02C,
            0x01E,
            0x1FD,
            0x156,
            0x1A3,
            0x1A6,
            0x01A,
            0x193,
        ],
        enemies={0x07: 0x12C, 0x08: 0x12C, 0x09: 0x12C},
    ),
    "GorgeousMusicCastleClosingFanRoom": MN64Region(
        name="Gorgeous Music Castle Closing Fan Room",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Silver Fortune Doll",
                lambda l: True,
                MN64Items.SILVER_FORTUNE_DOLL,
                flag_id=0x00D6,
                instance_id=0x0E,
            ),
        ],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleSuddenImpactRoomLower",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleFakeWaterConnector",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleChangingRoom",
                lambda l: l.has_gold_key(),
                type=MN64DoorType.DOOR,
                consumes_key="gold",
            ),
        ],
        room_id=0x0B0,
        room_default_definitions=[
            0x05D,
            0x3C4,
            0x191,
            0x152,
            0x02B,
            0x1F9,
            0x15C,
            0x1A4,
            0x320,
            0x15F,
            0x038,
            0x01E,
            0x2CA,
            0x16F,
            0x028,
            0x1D7,
            0x15D,
            0x01A,
        ],
    ),
    "GorgeousMusicCastleChangingRoom": MN64Region(
        name="Gorgeous Music Castle Changing Room",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Silver Fortune Doll",
                lambda l: True,
                MN64Items.SILVER_FORTUNE_DOLL,
                flag_id=0x00D7,
                instance_id=0x12,
            ),
        ],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleGoldWaterKey", lambda l: l.mini_ebisumaru and l.ebisumaru),
            MN64TransitionFront(
                "GorgeousMusicCastleClosingFanRoom",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleHammerThrowingRoom",
                lambda l: l.has_gold_key(),
                type=MN64DoorType.DOOR,
                consumes_key="gold",
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleWaveRoom",
                lambda l: l.has_diamond_key(),
                type=MN64DoorType.DOOR,
                consumes_key="diamond",
            ),
        ],
        room_id=0x0B2,
        room_default_definitions=[
            0x05D,
            0x07A,
            0x3C6,
            0x191,
            0x152,
            0x02B,
            0x1F9,
            0x15C,
            0x1A4,
            0x020,
            0x197,
            0x159,
            0x1F4,
            0x15D,
            0x01E,
            0x2CA,
            0x16F,
            0x032,
            0x1AD,
            0x01A,
        ],
    ),
    "GorgeousMusicCastleWaveRoom": MN64Region(
        name="Gorgeous Music Castle Wave Room",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleChangingRoom",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront("GorgeousMusicCastleWaterRoom", lambda l: True, type=MN64DoorType.DOOR),
        ],
        room_id=0x0B5,
        room_default_definitions=[
            0x05D,
            0x3C9,
            0x191,
            0x152,
            0x15D,
            0x31F,
            0x17F,
            0x330,
            0x1D5,
            0x15D,
            0x331,
            0x1F4,
            0x02C,
            0x1AA,
            0x02B,
            0x1F9,
            0x15C,
            0x038,
            0x1A3,
        ],
    ),
    "GorgeousMusicCastleWaterRoom": MN64Region(
        name="Gorgeous Music Castle Water Room",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Silver Fortune Doll",
                lambda l: l.jetpack and l.sasuke,
                MN64Items.SILVER_FORTUNE_DOLL,
                flag_id=0x00D8,
                instance_id=0x14,
            ),
            MN64LocationLogic(
                "Surprise Pack",
                lambda l: l.mermaid and l.yae,
                MN64Items.SURPRISE_PACK,
                flag_id=0x00FB,
                instance_id=0x12,
            ),
            MN64LocationLogic(
                "Golden Health",
                lambda l: l.mermaid and l.yae,
                MN64Items.GOLDEN_HEALTH,
                flag_id=0x1844,
                instance_id=0x15,
            ),
            MN64LocationLogic(
                "Mr Arrow",
                lambda l: True,
                MN64Items.MR_ARROW_GORGEOUS_MUSIC_CASTLE,
                flag_id=0x0108,
                instance_id=0x13,
            ),
        ],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleWaveRoom", lambda l: True, type=MN64DoorType.DOOR),
            MN64TransitionFront("GorgeousMusicCastleGarden", lambda l: True, type=MN64DoorType.DOOR),
        ],
        room_id=0x0B6,
        room_default_definitions=[
            0x05D,
            0x3CA,
            0x191,
            0x152,
            0x02B,
            0x1A4,
            0x1F9,
            0x15C,
            0x1F4,
            0x15D,
            0x227,
            0x161,
            0x027,
            0x1BE,
            0x032,
            0x1AD,
            0x01E,
            0x038,
            0x2BF,
            0x01A,
            0x196,
            0x194,
            0x192,
            0x01C,
            0x1A2,
        ],
        enemies={0x05: 0x12E, 0x06: 0x12E, 0x07: 0x12E, 0x08: 0x12E},
    ),
    "GorgeousMusicCastleGarden": MN64Region(
        name="Gorgeous Music Castle Garden",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Strength Upgrade 2",
                lambda l: True,
                MN64Items.STRENGTH_UPGRADE_2,
                flag_id=0x01A,
            ),
        ],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleWaterRoom", lambda l: True, type=MN64DoorType.DOOR),
            MN64TransitionFront(
                "GorgeousMusicCastleDancingLegs",
                lambda l: l.strength_upgrade_2,
                type=MN64DoorType.DOOR,
            ),
        ],
        npcs=[
            "General Store (Food)",
            "Inn",
            "General Store (Armor)",
            "Resturant",
        ],
        room_id=0x0B7,
        room_default_definitions=[
            0x05D,
            0x191,
            0x152,
            0x02B,
            0x1F9,
            0x15C,
            0x251,
            0x15D,
            0x021,
            0x199,
            0x159,
            0x19C,
            0x025,
            0x1CB,
            0x026,
            0x3CB,
        ],
        enemies={
            0x10: 0x10A,
            0x11: 0x10A,
            0x12: 0x13E,
            0x13: 0x13E,
            0x14: 0x13E,
            0x15: 0x13E,
            0x16: 0x13E,
            0x17: 0x13E,
            0x18: 0x13E,
            0x19: 0x13E,
        },
    ),
    "GorgeousMusicCastleDancingLegs": MN64Region(
        name="Gorgeous Music Castle Dancing Legs",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleGarden",
                lambda l: l.strength_upgrade_2,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront("GorgeousMusicCastleDancinWarp", lambda l: True),
            MN64TransitionFront(
                "GorgeousMusicCastleSlidingPlatforms",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleGlassHallway",
                lambda l: l.has_diamond_key(),
                type=MN64DoorType.DOOR,
                consumes_key="diamond",
            ),
        ],
        room_id=0x0B8,
        room_default_definitions=[
            0x05D,
            0x3CC,
            0x191,
            0x152,
            0x02B,
            0x1A4,
            0x1F9,
            0x15C,
            0x1DA,
            0x15D,
            0x023,
            0x1B9,
        ],
        enemies={0x0B: 0x104, 0x0C: 0x104, 0x0D: 0x104, 0x0E: 0x104},
    ),
    "GorgeousMusicCastleDancinWarp": MN64Region(
        name="Gorgeous Music Castle Dancin Warp",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Gold Fortune Doll",
                lambda l: True,
                MN64Items.GOLD_FORTUNE_DOLL,
                flag_id=0x00F4,
                instance_id=0x0B,
            ),
        ],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleDancingLegs", lambda l: True),
        ],
        room_id=0x0BC,
        room_default_definitions=[
            0x05D,
            0x3D0,
            0x191,
            0x152,
            0x020,
            0x197,
            0x159,
            0x19A,
            0x02B,
            0x1F9,
            0x15C,
            0x1DA,
            0x15D,
            0x026,
            0x01A,
            0x01C,
            0x1A2,
            0x01E,
            0x2BF,
        ],
        enemies={0x07: 0x108, 0x08: 0x108, 0x09: 0x10B, 0x0A: 0x10B},
    ),
    "GorgeousMusicCastleSlidingPlatforms": MN64Region(
        name="Gorgeous Music Castle Sliding Platforms",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleDancingLegs", lambda l: True, type=MN64DoorType.DOOR),
            MN64TransitionFront(
                "GorgeousMusicCastleConveyorBeltRoom",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0B9,
        room_default_definitions=[
            0x3CD,
            0x191,
            0x152,
            0x1F4,
            0x15D,
            0x02B,
            0x1F9,
            0x15C,
            0x01E,
            0x2CA,
            0x16F,
            0x02C,
            0x2BF,
        ],
    ),
    "GorgeousMusicCastleConveyorBeltRoom": MN64Region(
        name="Gorgeous Music Castle Conveyor Belt Room",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Golden Health",
                lambda l: l.chain_pipe and l.goemon,
                MN64Items.GOLDEN_HEALTH,
                flag_id=0x1843,
                instance_id=0x11,
            ),
        ],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleSlidingPlatforms",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleLavaRoom",
                lambda l: l.chain_pipe and l.goemon,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0BA,
        room_default_definitions=[
            0x3CE,
            0x191,
            0x152,
            0x1F4,
            0x15D,
            0x2AF,
            0x02B,
            0x1F9,
            0x15C,
            0x02C,
            0x1DB,
            0x032,
            0x1AD,
            0x01E,
            0x1A6,
            0x2BF,
            0x01A,
            0x192,
            0x01C,
            0x1A2,
        ],
    ),
    "GorgeousMusicCastleLavaRoom": MN64Region(
        name="Gorgeous Music Castle Lava Room",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleConveyorBeltRoom",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleWindowHallway",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0BB,
        room_default_definitions=[
            0x3CF,
            0x191,
            0x152,
            0x1F4,
            0x15D,
            0x01E,
            0x1FD,
            0x156,
            0x320,
            0x15F,
            0x2AF,
            0x02B,
            0x1F9,
            0x15C,
            0x038,
            0x2BF,
            0x027,
            0x032,
            0x1AD,
        ],
        enemies={0x0C: 0x3FC, 0x0D: 0x3FC, 0x0E: 0x3FC},
    ),
    "GorgeousMusicCastleWindowHallway": MN64Region(
        name="Gorgeous Music Castle Window Hallway",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleLavaRoom", lambda l: True, type=MN64DoorType.DOOR),
            MN64TransitionFront(
                "GorgeousMusicCastleRaisingPlatform",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0BC,
        room_default_definitions=[
            0x05D,
            0x3D0,
            0x191,
            0x152,
            0x020,
            0x197,
            0x159,
            0x19A,
            0x02B,
            0x1F9,
            0x15C,
            0x1DA,
            0x15D,
            0x026,
            0x01A,
            0x01C,
            0x1A2,
            0x01E,
            0x2BF,
        ],
        enemies={0x07: 0x108, 0x08: 0x108, 0x09: 0x10B, 0x0A: 0x10B},
    ),
    "GorgeousMusicCastleRaisingPlatform": MN64Region(
        name="Gorgeous Music Castle Raising Platform",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Diamond Key",
                lambda l: True,
                MN64Items.DIAMOND_KEY,
                flag_id=0x0193,
                instance_id=0x10,
            ),
        ],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleWindowHallway",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleSlideRoomUpper",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0BD,
        room_default_definitions=[
            0x05D,
            0x3D1,
            0x483,
            0x191,
            0x152,
            0x1F4,
            0x15D,
            0x020,
            0x198,
            0x159,
            0x021,
            0x19B,
            0x2AF,
            0x02B,
            0x1F9,
            0x15C,
            0x026,
            0x032,
            0x1AD,
            0x01E,
            0x2CB,
            0x1A3,
        ],
        enemies={0x06: 0x109, 0x07: 0x109},
    ),
    "GorgeousMusicCastleSlideRoomUpper": MN64Region(
        name="Gorgeous Music Castle Slide Room (Upper)",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Golden Health",
                lambda l: True,
                MN64Items.GOLDEN_HEALTH,
                flag_id=0x1842,
                instance_id=0x06,
            ),
        ],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleRaisingPlatform",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront("GorgeousMusicCastleSlideRoomLower", lambda l: True),
        ],
        room_id=0x0BE,
        room_default_definitions=[
            0x3D2,
            0x191,
            0x152,
            0x02B,
            0x1F9,
            0x15C,
            0x01E,
            0x2BF,
            0x01A,
            0x192,
            0x025,
            0x1CB,
            0x01C,
            0x1A2,
        ],
        enemies={0x07: 0x13E, 0x08: 0x13E},
    ),
    "GorgeousMusicCastleSlideRoomLower": MN64Region(
        name="Gorgeous Music Castle Slide Room (Lower)",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleRotatingBlocks",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0BE,
        room_default_definitions=[
            0x3D2,
            0x191,
            0x152,
            0x02B,
            0x1F9,
            0x15C,
            0x01E,
            0x2BF,
            0x01A,
            0x192,
            0x025,
            0x1CB,
            0x01C,
            0x1A2,
        ],
        enemies={0x07: 0x13E, 0x08: 0x13E},
    ),
    "GorgeousMusicCastleRotatingBlocks": MN64Region(
        name="Gorgeous Music Castle Rotating Blocks",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleSlideRoomLower",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront("GorgeousMusicCastleDancingLegs", lambda l: True, type=MN64DoorType.DOOR),
        ],
        room_id=0x0B9,
        room_default_definitions=[
            0x3CD,
            0x191,
            0x152,
            0x1F4,
            0x15D,
            0x02B,
            0x1F9,
            0x15C,
            0x01E,
            0x2CA,
            0x16F,
            0x02C,
            0x2BF,
        ],
    ),
    "GorgeousMusicCastleGlassHallway": MN64Region(
        name="Gorgeous Music Castle Glass Hallway",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleDancingLegs", lambda l: True, type=MN64DoorType.DOOR),
            MN64TransitionFront("GorgeousMusicCastleDungeon", lambda l: True, type=MN64DoorType.DOOR),
        ],
        room_id=0x0B9,
        room_default_definitions=[
            0x3CD,
            0x191,
            0x152,
            0x1F4,
            0x15D,
            0x02B,
            0x1F9,
            0x15C,
            0x01E,
            0x2CA,
            0x16F,
            0x02C,
            0x2BF,
        ],
    ),
    "GorgeousMusicCastleDungeon": MN64Region(
        name="Gorgeous Music Castle Dungeon",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Silver Fortune Doll",
                lambda l: True,
                MN64Items.SILVER_FORTUNE_DOLL,
                flag_id=0x00D9,
                instance_id=0x05,
            ),
        ],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleGlassHallway",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleSpinningRoom",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0BF,
        room_default_definitions=[
            0x05D,
            0x3D3,
            0x191,
            0x152,
            0x020,
            0x198,
            0x159,
            0x021,
            0x19B,
            0x02B,
            0x1F9,
            0x15C,
            0x01A,
            0x026,
            0x025,
            0x1CB,
        ],
        enemies={
            0x06: 0x109,
            0x07: 0x109,
            0x08: 0x109,
            0x09: 0x13E,
            0x0A: 0x13E,
            0x0B: 0x13E,
        },
    ),
    "GorgeousMusicCastleSpinningRoom": MN64Region(
        name="Gorgeous Music Castle Spinning Room",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleDungeon", lambda l: True, type=MN64DoorType.DOOR),
            MN64TransitionFront("GorgeousMusicCastleBossRoom", lambda l: True, type=MN64DoorType.DOOR),
        ],
        room_id=0x0C0,
        room_default_definitions=[
            0x4BA,
            0x05D,
            0x05F,
            0x3D4,
            0x191,
            0x152,
            0x02B,
            0x1F9,
            0x15C,
            0x195,
            0x01E,
            0x2C9,
            0x16F,
            0x2D0,
            0x177,
            0x020,
            0x1B6,
        ],
        enemies={0x09: 0x0FA, 0x0A: 0x0FA, 0x0B: 0x0FA, 0x0C: 0x0FA},
    ),
    "GorgeousMusicCastleBossRoom": MN64Region(
        name="Gorgeous Music Castle Boss Room",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            # We don't need a room ID for the collection event, we handle that in the client
            MN64LocationLogic(
                "Beat Game Die Hard Fans",
                lambda l: True,
                MN64Items.BEAT_GAME_DIE_HARD_FANS,
            ),
        ],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleSpinningRoom",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0C1,
        room_default_definitions=[
            0x05F,
            0x078,
            0x065,
            0x327,
            0x32E,
            0x2B9,
            0x3D5,
            0x48C,
            0x191,
            0x152,
            0x17C,
            0x17D,
            0x02B,
            0x1F9,
            0x15C,
            0x04A,
            0x04B,
        ],
    ),
    "GorgeousMusicCastleGoldWaterKey": MN64Region(
        name="Gorgeous Music Castle Gold Water Key",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Gold Key",
                lambda l: True,
                MN64Items.GOLD_KEY,
                flag_id=0x018F,
                instance_id=0x0C,
            ),
        ],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleChangingRoom", lambda l: l.mini_ebisumaru and l.ebisumaru),
        ],
        # TODO: Technically you can access this room from the wave room and softlock
        room_id=0x0B5,
        room_default_definitions=[
            0x05D,
            0x3C9,
            0x191,
            0x152,
            0x15D,
            0x31F,
            0x17F,
            0x330,
            0x1D5,
            0x15D,
            0x331,
            0x1F4,
            0x02C,
            0x1AA,
            0x02B,
            0x1F9,
            0x15C,
            0x038,
            0x1A3,
        ],
    ),
    "GorgeousMusicCastleHammerThrowingRoom": MN64Region(
        name="Gorgeous Music Castle Hammer Throwing Room",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleChangingRoom",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleMovingBoxClimb",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0B3,
        room_default_definitions=[
            0x3C7,
            0x191,
            0x152,
            0x229,
            0x161,
            0x02B,
            0x1F9,
            0x15C,
            0x024,
            0x1CC,
            0x038,
        ],
        enemies={0x05: 0x13F, 0x06: 0x13F, 0x07: 0x13F, 0x08: 0x13F, 0x09: 0x13F},
    ),
    "GorgeousMusicCastleMovingBoxClimb": MN64Region(
        name="Gorgeous Music Castle Moving Box Climb",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Diamond Key",
                lambda l: True,
                MN64Items.DIAMOND_KEY,
                flag_id=0x0191,
                instance_id=0x03,
            ),
        ],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleHammerThrowingRoom",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0B4,
        room_default_definitions=[
            0x05D,
            0x3C8,
            0x191,
            0x152,
            0x01E,
            0x02B,
            0x1F9,
            0x15C,
            0x1F4,
            0x15D,
            0x1A3,
            0x02C,
        ],
    ),
    "GorgeousMusicCastleFakeWaterConnector": MN64Region(
        name="Gorgeous Music Castle Fake Water Connector",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleClosingFanRoom",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleFakeWaterandDrum",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0B1,
        room_default_definitions=[
            0x3C5,
            0x191,
            0x152,
            0x31E,
            0x17F,
            0x02B,
            0x1F9,
            0x15C,
            0x038,
            0x020,
            0x19D,
        ],
        enemies={0x06: 0x12C, 0x07: 0x12C, 0x08: 0x12C, 0x09: 0x12C},
    ),
    "GorgeousMusicCastleFakeWaterandDrum": MN64Region(
        name="Gorgeous Music Castle Fake Water and Drum",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleFakeWaterConnector",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleSuddenImpactRoomUpper",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0AF,
        room_default_definitions=[
            0x3C3,
            0x191,
            0x152,
            0x31D,
            0x17F,
            0x02B,
            0x1F9,
            0x15C,
            0x038,
            0x02C,
            0x1D9,
            0x15D,
            0x020,
            0x19D,
        ],
        enemies={0x09: 0x12C, 0x0A: 0x12C},
    ),
    "GorgeousMusicCastleSuddenImpactRoomUpper": MN64Region(
        name="Gorgeous Music Castle Sudden Impact Room (Upper)",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Mr Ellyfant",
                lambda l: True,
                MN64Items.MR_ELLY_FANT_GORGEOUS_MUSIC_CASTLE,
                flag_id=0x0103,
                instance_id=0x10,
            ),
            MN64LocationLogic(
                "Gold Key",
                lambda l: l.chain_pipe and l.sudden_impact and l.goemon,
                MN64Items.GOLD_KEY,
                flag_id=0x018C,
                instance_id=0x0E,
            ),
        ],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleSuddenImpactRoomLower",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleFakeWaterandDrum",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0AE,
        room_default_definitions=[
            0x05D,
            0x3C2,
            0x191,
            0x152,
            0x1D8,
            0x15D,
            0x31C,
            0x17F,
            0x02B,
            0x1F9,
            0x15C,
            0x020,
            0x19D,
            0x038,
            0x02C,
            0x01E,
            0x1FD,
            0x156,
            0x1A3,
            0x1A6,
            0x01A,
            0x193,
        ],
        enemies={0x07: 0x12C, 0x08: 0x12C, 0x09: 0x12C},
    ),
    "GorgeousMusicCastleFlameHallwayLower": MN64Region(
        name="Gorgeous Music Castle Flame Hallway (Lower)",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Golden Health",
                lambda l: True,
                MN64Items.GOLDEN_HEALTH,
                flag_id=0x1841,
                instance_id=0x0B,
            ),
        ],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleEntrance", lambda l: True, type=MN64DoorType.DOOR),
            MN64TransitionFront(
                "GorgeousMusicCastleScaffoldingClimbUpper",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0A9,
        room_default_definitions=[
            0x3BD,
            0x191,
            0x152,
            0x020,
            0x198,
            0x159,
            0x021,
            0x19B,
            0x02B,
            0x1F9,
            0x15C,
            0x01A,
            0x192,
            0x025,
            0x1CD,
        ],
        enemies={0x0D: 0x140},
    ),
    "GorgeousMusicCastleScaffoldingClimbUpper": MN64Region(
        name="Gorgeous Music Castle Scaffolding Climb (Upper)",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Golden Health",
                lambda l: True,
                MN64Items.GOLDEN_HEALTH,
                flag_id=0x1840,
                instance_id=0x0B,
            ),
            MN64LocationLogic(
                "Silver Key",
                lambda l: l.jetpack and l.sasuke,
                MN64Items.SILVER_KEY,
                flag_id=0x018B,
                instance_id=0x08,
            ),
        ],
        exits=[
            MN64TransitionFront("GorgeousMusicCastleFlameHallwayLower", lambda l: True),
            MN64TransitionFront(
                "GorgeousMusicCastleScaffoldingClimbLower",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleFanJump",
                lambda l: l.has_silver_key(),
                type=MN64DoorType.DOOR,
                consumes_key="silver",
            ),
        ],
        room_id=0x0AA,
        room_default_definitions=[
            0x05D,
            0x3BE,
            0x191,
            0x152,
            0x02B,
            0x1F9,
            0x15C,
            0x1A4,
            0x228,
            0x161,
            0x038,
            0x1A3,
            0x01C,
            0x1A2,
            0x01A,
            0x192,
            0x020,
            0x19D,
        ],
        enemies={0x0C: 0x12C, 0x0D: 0x12C, 0x0E: 0x12C, 0x0F: 0x12C, 0x10: 0x12C},
    ),
    "GorgeousMusicCastleScaffoldingClimbLower": MN64Region(
        name="Gorgeous Music Castle Scaffolding Climb (Lower)",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleSlidingKnives",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0AA,
        room_default_definitions=[
            0x05D,
            0x3BE,
            0x191,
            0x152,
            0x02B,
            0x1F9,
            0x15C,
            0x1A4,
            0x228,
            0x161,
            0x038,
            0x1A3,
            0x01C,
            0x1A2,
            0x01A,
            0x192,
            0x020,
            0x19D,
        ],
        enemies={0x0C: 0x12C, 0x0D: 0x12C, 0x0E: 0x12C, 0x0F: 0x12C, 0x10: 0x12C},
    ),
    "GorgeousMusicCastleSlidingKnives": MN64Region(
        name="Gorgeous Music Castle Sliding Knives",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleScaffoldingClimbLower",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleKnifeHallway",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0AB,
        room_default_definitions=[
            0x3BF,
            0x191,
            0x152,
            0x01E,
            0x1D6,
            0x180,
            0x02B,
            0x1F9,
            0x15C,
        ],
    ),
    "GorgeousMusicCastleKnifeHallway": MN64Region(
        name="Gorgeous Music Castle Knife Hallway",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleSlidingKnives",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront(
                "GorgeousMusicCastleFlameHallwayUpper",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0AC,
        room_default_definitions=[
            0x3C0,
            0x191,
            0x152,
            0x01E,
            0x1D6,
            0x180,
            0x02B,
            0x1F9,
            0x15C,
        ],
    ),
    "GorgeousMusicCastleFlameHallwayUpper": MN64Region(
        name="Gorgeous Music Castle Flame Hallway (Upper)",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleKnifeHallway",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
            MN64TransitionFront("GorgeousMusicCastleFlameHallwayLower", lambda l: True),
        ],
        room_id=0x0A9,
        room_default_definitions=[
            0x3BD,
            0x191,
            0x152,
            0x020,
            0x198,
            0x159,
            0x021,
            0x19B,
            0x02B,
            0x1F9,
            0x15C,
            0x01A,
            0x192,
            0x025,
            0x1CD,
        ],
        enemies={0x0D: 0x140},
    ),
    "GorgeousMusicCastleFanJump": MN64Region(
        name="Gorgeous Music Castle Fan Jump",
        hint_name=MN64HintRegion.GORGEOUS_MUSIC_CASTLE,
        level=MN64Levels.GORGEOUS_MUSIC_CASTLE,
        locations=[
            MN64LocationLogic(
                "Golden Health 1",
                lambda l: True,
                MN64Items.GOLDEN_HEALTH,
                flag_id=0x183F,
                instance_id=0x05,
            ),
            MN64LocationLogic(
                "Golden Health 2",
                lambda l: True,
                MN64Items.GOLDEN_HEALTH,
                flag_id=0x183E,
                instance_id=0x06,
            ),
            MN64LocationLogic(
                "Gold Key",
                lambda l: True,
                MN64Items.GOLD_KEY,
                flag_id=0x0189,
                instance_id=0x07,
            ),
        ],
        exits=[
            MN64TransitionFront(
                "GorgeousMusicCastleScaffoldingClimbUpper",
                lambda l: True,
                type=MN64DoorType.DOOR,
            ),
        ],
        room_id=0x0AD,
        room_default_definitions=[
            0x05D,
            0x3C1,
            0x191,
            0x152,
            0x320,
            0x15F,
            0x028,
            0x1D7,
            0x15D,
            0x02B,
            0x1F9,
            0x15C,
            0x01E,
            0x2CA,
            0x16F,
            0x038,
            0x01A,
            0x192,
            0x1A3,
        ],
    ),
}
