from typing import List, TypedDict
from BaseClasses import Location


base_id = 147000


class InscryptionLocation(Location):
    game: str = "Inscryption"


class LocDict(TypedDict):
    name: str
    region: str


location_table: List[LocDict] = [
    {'name': "Act 1 - Boss Prospector",
     'region': "Act 1"},
    {'name': "Act 1 - Boss Angler",
     'region': "Act 1"},
    {'name': "Act 1 - Boss Trapper",
     'region': "Act 1"},
    {'name': "Act 1 - Boss Leshy",
     'region': "Act 1"},
    {'name': "Act 1 - Safe",
     'region': "Act 1"},
    {'name': "Act 1 - Clock Main Compartment",
     'region': "Act 1"},
    {'name': "Act 1 - Clock Upper Compartment",
     'region': "Act 1"},
    {'name': "Act 1 - Dagger",
     'region': "Act 1"},
    {'name': "Act 1 - Wardrobe Drawer 1",
     'region': "Act 1"},
    {'name': "Act 1 - Wardrobe Drawer 2",
     'region': "Act 1"},
    {'name': "Act 1 - Wardrobe Drawer 3",
     'region': "Act 1"},
    {'name': "Act 1 - Wardrobe Drawer 4",
     'region': "Act 1"},
    {'name': "Act 1 - Magnificus Eye",
     'region': "Act 1"},
    {'name': "Act 1 - Painting 1",
     'region': "Act 1"},
    {'name': "Act 1 - Painting 2",
     'region': "Act 1"},
    {'name': "Act 1 - Painting 3",
     'region': "Act 1"},
    {'name': "Act 1 - Greater Smoke",
     'region': "Act 1"},
    {'name': "Act 2 - Boss Leshy",
     'region': "Act 2"},
    {'name': "Act 2 - Boss Magnificus",
     'region': "Act 2"},
    {'name': "Act 2 - Boss Grimora",
     'region': "Act 2"},
    {'name': "Act 2 - Boss P03",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Prospector",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Angler",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Trapper",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Sawyer",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Royal",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Kaycee",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Goobert",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Pike Mage",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Lonely Wizard",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Inspector",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Melter",
     'region': "Act 2"},
    {'name': "Act 2 - Battle Dredger",
     'region': "Act 2"},
    {'name': "Act 2 - Dock Chest",
     'region': "Act 2"},
    {'name': "Act 2 - Forest Cabin Chest",
     'region': "Act 2"},
    {'name': "Act 2 - Forest Meadow Chest",
     'region': "Act 2"},
    {'name': "Act 2 - Cabin Wardrobe Drawer",
     'region': "Act 2"},
    {'name': "Act 2 - Cabin Safe",
     'region': "Act 2"},
    {'name': "Act 2 - Crypt Casket 1",
     'region': "Act 2"},
    {'name': "Act 2 - Crypt Casket 2",
     'region': "Act 2"},
    {'name': "Act 2 - Crypt Well",
     'region': "Act 2"},
    {'name': "Act 2 - Tower Chest 1",
     'region': "Act 2"},
    {'name': "Act 2 - Tower Chest 2",
     'region': "Act 2"},
    {'name': "Act 2 - Tower Chest 3",
     'region': "Act 2"},
    {'name': "Act 2 - Tentacle",
     'region': "Act 2"},
    {'name': "Act 2 - Factory Trash Can",
     'region': "Act 2"},
    {'name': "Act 2 - Factory Drawer 1",
     'region': "Act 2"},
    {'name': "Act 2 - Factory Drawer 2",
     'region': "Act 2"},
    {'name': "Act 2 - Factory Chest 1",
     'region': "Act 2"},
    {'name': "Act 2 - Factory Chest 2",
     'region': "Act 2"},
    {'name': "Act 2 - Factory Chest 3",
     'region': "Act 2"},
    {'name': "Act 2 - Factory Chest 4",
     'region': "Act 2"},
    {'name': "Act 2 - Ancient Obol",
     'region': "Act 2"},
    {'name': "Act 2 - Bone Lord Femur",
     'region': "Act 2"},
    {'name': "Act 2 - Bone Lord Horn",
     'region': "Act 2"},
    {'name': "Act 2 - Bone Lord Holo Key",
     'region': "Act 2"},
    {'name': "Act 2 - Mycologists Holo Key",
     'region': "Act 2"},
    {'name': "Act 2 - Camera Replica",
     'region': "Act 2"},
    {'name': "Act 2 - Clover",
     'region': "Act 2"},
    {'name': "Act 2 - Monocle",
     'region': "Act 2"},
    {'name': "Act 2 - Epitaph Piece 1",
     'region': "Act 2"},
    {'name': "Act 2 - Epitaph Piece 2",
     'region': "Act 2"},
    {'name': "Act 2 - Epitaph Piece 3",
     'region': "Act 2"},
    {'name': "Act 2 - Epitaph Piece 4",
     'region': "Act 2"},
    {'name': "Act 2 - Epitaph Piece 5",
     'region': "Act 2"},
    {'name': "Act 2 - Epitaph Piece 6",
     'region': "Act 2"},
    {'name': "Act 2 - Epitaph Piece 7",
     'region': "Act 2"},
    {'name': "Act 2 - Epitaph Piece 8",
     'region': "Act 2"},
    {'name': "Act 2 - Epitaph Piece 9",
     'region': "Act 2"},
    {'name': "Act 3 - Boss Photographer",
     'region': "Act 3"},
    {'name': "Act 3 - Boss Archivist",
     'region': "Act 3"},
    {'name': "Act 3 - Boss Unfinished",
     'region': "Act 3"},
    {'name': "Act 3 - Boss G0lly",
     'region': "Act 3"},
    {'name': "Act 3 - Boss Mycologists",
     'region': "Act 3"},
    {'name': "Act 3 - Bone Lord Room",
     'region': "Act 3"},
    {'name': "Act 3 - Shop Holo Pelt",
     'region': "Act 3"},
    {'name': "Act 3 - Middle Holo Pelt",
     'region': "Act 3"},
    {'name': "Act 3 - Forest Holo Pelt",
     'region': "Act 3"},
    {'name': "Act 3 - Crypt Holo Pelt",
     'region': "Act 3"},
    {'name': "Act 3 - Tower Holo Pelt",
     'region': "Act 3"},
    {'name': "Act 3 - Trader 1",
     'region': "Act 3"},
    {'name': "Act 3 - Trader 2",
     'region': "Act 3"},
    {'name': "Act 3 - Trader 3",
     'region': "Act 3"},
    {'name': "Act 3 - Trader 4",
     'region': "Act 3"},
    {'name': "Act 3 - Trader 5",
     'region': "Act 3"},
    {'name': "Act 3 - Drawer 1",
     'region': "Act 3"},
    {'name': "Act 3 - Drawer 2",
     'region': "Act 3"},
    {'name': "Act 3 - Clock",
     'region': "Act 3"},
    {'name': "Act 3 - Extra Battery",
     'region': "Act 3"},
    {'name': "Act 3 - Nano Armor Generator",
     'region': "Act 3"},
    {'name': "Act 3 - Chest",
     'region': "Act 3"},
    {'name': "Act 3 - Goobert's Painting",
     'region': "Act 3"},
    {'name': "Act 3 - Luke's File Entry 1",
     'region': "Act 3"},
    {'name': "Act 3 - Luke's File Entry 2",
     'region': "Act 3"},
    {'name': "Act 3 - Luke's File Entry 3",
     'region': "Act 3"},
    {'name': "Act 3 - Luke's File Entry 4",
     'region': "Act 3"},
    {'name': "Act 3 - Inspectometer Battery",
     'region': "Act 3"},
    {'name': "Act 3 - Gems Drone",
     'region': "Act 3"},
    {'name': "Act 3 - The Great Transcendence",
     'region': "Act 3"},
    {'name': "Act 3 - Well",
     'region': "Act 3"},
]
