from .ap_regions import *

#Beginner
#Spawning Meadows
HOMEPOINT_AP_SPAWN_NAME = "Home Point - AP Spawn Point"
HOMEPOINT_AP_SPAWN_AP_REGION = SPAWNING_MEADOWS_AP_REGION
HOMEPOINT_OLD_NANS_WATERING_HOLE_NAME = "Home Point - Old Nan's Watering Hole"
HOMEPOINT_OLD_NANS_WATERING_HOLE_AP_REGION = SPAWNING_MEADOWS_AP_REGION
#Delende
HOMEPOINT_FISH_HATCHERY_NAME = "Home Point - Fish Hatchery"
HOMEPOINT_FISH_HATCHERY_AP_REGION = DELENDE_PLAINS_AP_REGION
HOMEPOINT_SOILED_DEN_NAME = "Home Point - Soiled Den"
HOMEPOINT_SOILED_DEN_AP_REGION = DELENDE_PLAINS_AP_REGION
HOMEPOINT_THE_PALE_GROTTO_ENTRANCE_NAME = "Home Point - The Pale Grotto Entrance"
HOMEPOINT_THE_PALE_GROTTO_ENTRANCE_AP_REGION = DELENDE_PLAINS_AP_REGION
HOMEPOINT_DELENDE_FALLS_NAME = "Home Point - Delende Falls"
HOMEPOINT_DELENDE_FALLS_AP_REGION = DELENDE_HIGH_BRIDGES_AP_REGION
HOMEPOINT_DELENDE_PEAK_NAME = "Home Point - Delende Peak"
HOMEPOINT_DELENDE_PEAK_AP_REGION = DELENDE_PEAK_AP_REGION
HOMEPOINT_CABIN_ON_THE_CLIFF_NAME = "Home Point - Cabin On The Cliff"
HOMEPOINT_CABIN_ON_THE_CLIFF_AP_REGION = DELENDE_HIGH_BRIDGES_AP_REGION
#Mercury Shrine
HOMEPOINT_MERCURY_SHRINE_NAME = "Home Point - Mercury Shrine"
HOMEPOINT_MERCURY_SHRINE_AP_REGION = MERCURY_SHRINE_AP_REGION
#The Pale Grotto
HOMEPOINT_THE_PALE_GROTTO_RUINS_NAME = "Home Point - The Pale Grotto Ruins"
HOMEPOINT_THE_PALE_GROTTO_RUINS_AP_REGION = THE_PALE_GROTTO_AP_REGION
#Seaside Cliffs
HOMEPOINT_SEASIDE_CLIFFS_CAMP_NAME = "Home Point - Seaside Cliffs Camp"
HOMEPOINT_SEASIDE_CLIFFS_AP_REGION = SEASIDE_CLIFFS_AP_REGION
#Yamagawa M.A.
HOMEPOINT_YAMAGAWA_MA_SUMMIT_NAME = "Home Point - Yamagawa M.A. Summit"
HOMEPOINT_YAMAGAWA_MA_SUMMIT_AP_REGION = YAMAGAWA_MA_AP_REGION
#Proving Meadows
HOMEPOINT_PROVING_MEADOWS_CAMP_NAME = "Home Point - Proving Meadows Camp"
HOMEPOINT_PROVING_MEADOWS_CAMP_AP_REGION = PROVING_MEADOWS_AP_REGION
#Skumparadise
HOMEPOINT_SKUMPARADISE_ENTRANCE_NAME = "Home Point - Skumparadise Entrance"
HOMEPOINT_SKUMPARADISE_ENTRANCE_AP_REGION = SKUMPARADISE_AP_REGION
HOMEPOINT_SKUMPARADISE_DEPTHS_NAME = "Home Point - Skumparadise Depths"
HOMEPOINT_SKUMPARADISE_DEPTHS_AP_REGION = SKUMPARADISE_AP_REGION

#Advanced
#Capital Sequoia
HOMEPOINT_SKUMPARADISE_EXIT_NAME = "Home Point - Skumparadise Exit"
HOMEPOINT_SKUMPARADISE_EXIT_AP_REGION = CAPITAL_SEQUOIA_AP_REGION
HOMEPOINT_WEST_MARKET_DISTRICT_NAME = "Home Point - West Market District"
HOMEPOINT_WEST_MARKET_DISTRICT_AP_REGION = CAPITAL_SEQUOIA_AP_REGION
HOMEPOINT_KNOW_IT_ALL_DUCKS_HOUSE_NAME = "Home Point - Know-It-All Ducks' House"
HOMEPOINT_KNOW_IT_ALL_DUCKS_HOUSE_AP_REGION = CAPITAL_SEQUOIA_AP_REGION
HOMEPOINT_EAST_MARKET_DISTRICT_NAME = "Home Point - East Market District"
HOMEPOINT_EAST_MARKET_DISTRICT_AP_REGION = CAPITAL_SEQUOIA_AP_REGION
HOMEPOINT_TRAINING_GROUNDS_NAME = "Home Point - Training Grounds"
HOMEPOINT_TRAINING_GROUNDS_AP_REGION = CAPITAL_SEQUOIA_AP_REGION
HOMEPOINT_BULLETIN_SQUARE_NAME = "Home Point - Bulletin Square"
HOMEPOINT_BULLETIN_SQUARE_AP_REGION = CAPITAL_SEQUOIA_AP_REGION
HOMEPOINT_GAEA_SHRINE_NAME = "Home Point - Gaea Shrine"
HOMEPOINT_GAEA_SHRINE_AP_REGION = CAPITAL_SEQUOIA_AP_REGION
#Boomer Society
HOMEPOINT_BOOMER_SOCIETY_NAME = "Home Point - Boomer Society"
HOMEPOINT_BOOMER_SOCIETY_AP_REGION = BOOMER_SOCIETY_AP_REGION
#Rolling Quintar Fields
HOMEPOINT_RENT_A_QUINTAR_NAME = "Home Point - Rent-A-Quintar"
HOMEPOINT_RENT_A_QUINTAR_AP_REGION = ROLLING_QUINTAR_FIELDS_AP_REGION
HOMEPOINT_QUINTAR_ENTHUSIASTS_HOUSE_NAME = "Home Point - Quintar Enthusiast's House"
HOMEPOINT_QUINTAR_ENTHUSIASTS_HOUSE_AP_REGION = ROLLING_QUINTAR_FIELDS_AP_REGION
HOMEPOINT_QUINTAR_SANCTUM_NAME = "Home Point - Quintar Sanctum"
HOMEPOINT_QUINTAR_SANCTUM_AP_REGION = SANCTUM_ENTRANCE_AP_REGION
#Quintar Sanctum
HOMEPOINT_QUINTAR_NAMEKO_NAME = "Home Point - Quintar Nameko"
HOMEPOINT_QUINTAR_NAMEKO_AP_REGION = QUINTAR_SANCTUM_AP_REGION
#Capital Jail
HOMEPOINT_CAPITAL_JAIL_ENTRANCE_NAME = "Home Point - Capital Jail Entrance"
HOMEPOINT_CAPITAL_JAIL_ENTRANCE_AP_REGION = CAPITAL_JAIL_AP_REGION
HOMEPOINT_CAPITAL_JAIL_DARK_WING_NAME = "Home Point - Capital Jail Dark Wing"
HOMEPOINT_CAPITAL_JAIL_DARK_WING_AP_REGION = JAIL_DARK_WING_AP_REGION
#Capital Pipeline
HOMEPOINT_CAPITAL_PIPELINE_NAME = "Home Point - Capital Pipeline"
HOMEPOINT_CAPITAL_PIPELINE_AP_REGION = PIPELINE_NORTH_AP_REGION
HOMEPOINT_EAST_CAPITAL_PIPELINE_NAME = "Home Point - East Capital Pipeline"
HOMEPOINT_EAST_CAPITAL_PIPELINE_AP_REGION = PIPELINE_SOUTH_AP_REGION
#Okimoto N.S.
HOMEPOINT_OKIMOTO_N_S_BASE_NAME = "Home Point - Okimoto N.S. Base"
HOMEPOINT_OKIMOTO_N_S_BASE_AP_REGION = OKIMOTO_NS_AP_REGION
HOMEPOINT_NINJA_YASHIKI_NAME = "Home Point - Ninja Yashiki"
HOMEPOINT_NINJA_YASHIKI_AP_REGION = OKIMOTO_NS_AP_REGION
#Salmon Pass
HOMEPOINT_SALMON_PASS_ENTRANCE_NAME = "Home Point - Salmon Pass Entrance"
HOMEPOINT_SALMON_PASS_ENTRANCE_AP_REGION = SALMON_PASS_EAST_AP_REGION
#Salmon River
HOMEPOINT_SALMON_SHACK_NAME = "Home Point - Salmon Shack"
HOMEPOINT_SALMON_SHACK_AP_REGION = SALMON_RIVER_AP_REGION
#Poko Poko Desert
HOMEPOINT_LABYRINTH_ENCAMPMENT_NAME = "Home Point - Labyrinth Encampment"
HOMEPOINT_LABYRINTH_ENCAMPMENT_AP_REGION = TOWER_OF_ZOT_CAMP_AP_REGION
#Sara Sara Bazaar
HOMEPOINT_SARA_SARA_BAZAAR_PORT_NAME = "Home Point - Sara Sara Bazaar Port"
HOMEPOINT_SARA_SARA_BAZAAR_PORT_AP_REGION = SARA_SARA_BAZAAR_AP_REGION
HOMEPOINT_POKO_POKO_WEST_GATE_NAME = "Home Point - Poko Poko West Gate"
HOMEPOINT_POKO_POKO_WEST_GATE_AP_REGION = SARA_SARA_BAZAAR_AP_REGION
HOMEPOINT_POKO_POKO_EAST_GATE_NAME = "Home Point - Poko Poko East Gate"
HOMEPOINT_POKO_POKO_EAST_GATE_AP_REGION = SARA_SARA_BAZAAR_AP_REGION
#Sara Sara Beach
HOMEPOINT_IBEKS_CAVE_NAME = "Home Point - Ibek's Cave"
HOMEPOINT_IBEKS_CAVE_AP_REGION = IBEK_CAVE_MOUTH_AP_REGION
HOMEPOINT_BEACH_BIRDS_NEST_NAME = "Home Point - Beach Bird's Nest"
HOMEPOINT_BEACH_BIRDS_NEST_AP_REGION = BEACH_BIRDS_NEST_AP_REGION
#Ancient Reservoir
HOMEPOINT_ANCIENT_RESERVOIR_ENTRANCE_NAME = "Home Point - Ancient Reservoir Entrance"
HOMEPOINT_ANCIENT_RESERVOIR_ENTRANCE_AP_REGION = ANCIENT_RESERVOIR_AP_REGION
HOMEPOINT_MAIN_RESERVOIR_CHAMBER_NAME = "Home Point - Main Reservoir Chamber"
HOMEPOINT_MAIN_RESERVOIR_CHAMBER_AP_REGION = ANCIENT_RESERVOIR_AP_REGION

#Expert
#The Open Sea
HOMEPOINT_SAILORS_RAFT_NAME = "Home Point - Sailor's Raft"
HOMEPOINT_SAILORS_RAFT_AP_REGION = THE_OPEN_SEA_AP_REGION
#Shoudu Province
HOMEPOINT_SHOUDU_PORT_NAME = "Home Point - Shoudu Port"
HOMEPOINT_SHOUDU_PORT_AP_REGION = SHOUDU_DOCKSIDE_AP_REGION
HOMEPOINT_SHANTY_INN_NAME = "Home Point - Shanty Inn"
HOMEPOINT_SHANTY_INN_AP_REGION = SHOUDU_DOCKSIDE_AP_REGION
HOMEPOINT_SHOUDU_MARKET_NAME = "Home Point - Shoudu Market"
HOMEPOINT_SHOUDU_MARKET_AP_REGION = SHOUDU_PROVINCE_PROPER_AP_REGION
HOMEPOINT_PRIZE_COUNTER_NAME = "Home Point - Prize Counter"
HOMEPOINT_PRIZE_COUNTER_AP_REGION = SHOUDU_PROVINCE_PROPER_AP_REGION
HOMEPOINT_SHOUDU_ELEVATOR_NAME = "Home Point - Shoudu Elevator"
HOMEPOINT_SHOUDU_ELEVATOR_AP_REGION = SHOUDU_ELEVATOR_BASE_AP_REGION
HOMEPOINT_SHOUDU_FIELDS_NAME = "Home Point - Shoudu Fields"
HOMEPOINT_SHOUDU_FIELDS_AP_REGION = SHOUDU_FIELDS_WEST_SCAFFOLDING_AP_REGION
HOMEPOINT_SKY_ARENA_NAME = "Home Point - Sky Arena"
HOMEPOINT_SKY_ARENA_AP_REGION = SKY_ARENA_AP_REGION
#The Undercity
HOMEPOINT_THE_UNDERCITY_NAME = "Home Point - The Undercity"
HOMEPOINT_THE_UNDERCITY_AP_REGION = THE_UNDERCITY_HOMEPOINT_AND_BLADE_MASTER_AP_REGION
#Ganymede Shrine
HOMEPOINT_GANYMEDE_SHRINE_NAME = "Home Point - Ganymede Shrine"
HOMEPOINT_GANYMEDE_SHRINE_AP_REGION = GANYMEDE_SHRINE_AP_REGION
#Beaurior Volcano
HOMEPOINT_BEAURIOR_ROCK_NAME = "Home Point - Beaurior Rock"
HOMEPOINT_BEAURIOR_ROCK_AP_REGION = BEAURIOR_BOARDWALK_AP_REGION
HOMEPOINT_BEAURIOR_VOLCANO_PEAK_NAME = "Home Point - Beaurior Volcano Peak"
HOMEPOINT_BEAURIOR_VOLCANO_PEAK_AP_REGION = VOLCANO_PEAK_AP_REGION
#Beaurior Rock
HOMEPOINT_BOSS_ROOM_NAME = "Home Point - Boss Room"
HOMEPOINT_BOSS_ROOM_AP_REGION = BEAURIOR_BOSS_ANTECHAMBER_AP_REGION
#Quintar Reserve
HOMEPOINT_DIONE_SHRINE_NAME = "Home Point - Dione Shrine"
HOMEPOINT_DIONE_SHRINE_AP_REGION = QUINTAR_RESERVE_AP_REGION
#Dione Shrine
HOMEPOINT_FLYERS_LOOKOUT_NAME = "Home Point - Flyer's Lookout"
HOMEPOINT_FLYERS_LOOKOUT_AP_REGION = DIONE_SHRINE_AP_REGION
#Tall, Tall Heights
HOMEPOINT_TALL_TALL_HEIGHTS_NAME = "Home Point - Tall, Tall Heights"
HOMEPOINT_TALL_TALL_HEIGHTS_AP_REGION = TALL_TALL_SAVE_POINT_AP_REGION
HOMEPOINT_ICE_FISHERS_HUT_NAME = "Home Point - Ice Fisher's Hut"
HOMEPOINT_ICE_FISHERS_HUT_AP_REGION = LOWER_ICE_LAKES_AP_REGION
HOMEPOINT_ICE_PASS_NAME = "Home Point - Ice Pass"
HOMEPOINT_ICE_PASS_AP_REGION = LOWER_ICE_LAKES_AP_REGION
HOMEPOINT_LANDS_END_COTTAGE_NAME = "Home Point - Land's End Cottage"
HOMEPOINT_LANDS_END_COTTAGE_AP_REGION = LOWER_ICE_LAKES_AP_REGION
HOMEPOINT_TRITON_SHRINE_NAME = "Home Point - Triton Shrine"
HOMEPOINT_TRITON_SHRINE_AP_REGION = UPPER_ICE_LAKES_AP_REGION
HOMEPOINT_SLIP_GLIDE_RIDE_EXIT_NAME = "Home Point - Slip Glide Ride Exit"
HOMEPOINT_SLIP_GLIDE_RIDE_EXIT_AP_REGION = SLIP_GLIDE_RIDE_EXIT_AP_REGION
HOMEPOINT_TALL_TALL_SOUVENIR_SHOP_NAME = "Home Point - Tall, Tall Souvenir Shop"
HOMEPOINT_TALL_TALL_SOUVENIR_SHOP_AP_REGION = SOUVENIR_SHOP_AP_REGION
HOMEPOINT_SEQUOIA_ATHENAEUM_NAME = "Home Point - Sequoia Athenaeum"
HOMEPOINT_SEQUOIA_ATHENAEUM_AP_REGION = SEQUOIA_ATHENAEUM_ENTRANCE_AP_REGION
#Land's End
HOMEPOINT_SUMMIT_SHRINE_NAME = "Home Point - Summit Shrine"
HOMEPOINT_SUMMIT_SHRINE_AP_REGION = LANDS_END_AP_REGION
#Slip Glide Ride
HOMEPOINT_SLIP_GLIDE_RIDE_ENTRANCE_NAME = "Home Point - Slip Glide Ride Entrance"
HOMEPOINT_SLIP_GLIDE_RIDE_ENTRANCE_AP_REGION = SLIP_GLIDE_RIDE_ENTRANCE_AP_REGION
#Castle Ramparts
HOMEPOINT_WEST_RAMPARTS_NAME = "Home Point - West Ramparts"
HOMEPOINT_WEST_RAMPARTS_AP_REGION = PEAK_RAMPARTS_AP_REGION
HOMEPOINT_EAST_RAMPARTS_NAME = "Home Point - East Ramparts"
HOMEPOINT_EAST_RAMPARTS_AP_REGION = PEAK_RAMPARTS_AP_REGION
#The Chalice of Tar
HOMEPOINT_THE_CHALICE_OF_TAR_NAME = "Home Point - The Chalice of Tar"
HOMEPOINT_THE_CHALICE_OF_TAR_AP_REGION = CHALICE_FOOT_AP_REGION
#Jidamba Tangle
HOMEPOINT_EUROPA_SHRINE_NAME = "Home Point - Europa Shrine"
HOMEPOINT_EUROPA_SHRINE_AP_REGION = EUROPA_SHRINE_AP_REGION
#Jidamba Eaclaneya
HOMEPOINT_EACLANEYA_ENTRANCE_NAME = "Home Point - Eaclaneya Entrance"
HOMEPOINT_EACLANEYA_ENTRANCE_AP_REGION = EACLANEYA_ENTRANCE_AP_REGION
HOMEPOINT_SALMON_ROOM_NAME = "Home Point - Salmon Room"
HOMEPOINT_SALMON_ROOM_AP_REGION = SALMON_ROOM_AP_REGION
#Neptune Shrine
HOMEPOINT_NEPTUNE_SHRINE_NAME = "Home Point - Neptune Shrine"
HOMEPOINT_NEPTUNE_SHRINE_AP_REGION = NEPTUNE_SHRINE_AP_REGION
#Continental Tram
HOMEPOINT_PLATFORM_A_NAME = "Home Point - Platform A"
HOMEPOINT_PLATFORM_A_AP_REGION = CONTINENTAL_TRAM_AP_REGION

#End-Game
#Ancient Labyrinth
HOMEPOINT_ANCIENT_LABYRINTH_CORE_NAME = "Home Point - Ancient Labyrinth Core"
HOMEPOINT_ANCIENT_LABYRINTH_CORE_AP_REGION = LABYRINTH_CORE_AP_REGION
#The Sequoia
HOMEPOINT_TOP_OF_THE_SEQUOIA_NAME = "Home Point - Top Of The Sequoia"
HOMEPOINT_TOP_OF_THE_SEQUOIA_AP_REGION = THE_SEQUOIA_AP_REGION
#Castle Sequoia
HOMEPOINT_CASTLE_SEQUOIA_FOYER_NAME = "Home Point - Castle Sequoia Foyer"
HOMEPOINT_CASTLE_SEQUOIA_FOYER_AP_REGION = CASTLE_SEQUOIA_AP_REGION
#The New World
HOMEPOINT_ASTLEYS_SHRINE_NAME = "Home Point - Astley's Shrine"
HOMEPOINT_ASTLEYS_SHRINE_AP_REGION = THE_NEW_WORLD_AP_REGION
HOMEPOINT_DISCIPLINE_HOLLOW_NAME = "Home Point - Discipline Hollow"
HOMEPOINT_DISCIPLINE_HOLLOW_AP_REGION = DISCIPLINE_HOLLOW_AP_REGION
HOMEPOINT_ASTLEYS_KEEP_NAME = "Home Point - Astley's Keep"
HOMEPOINT_ASTLEYS_KEEP_AP_REGION = THE_NEW_WORLD_AP_REGION