from . import Levels, Weapons
from .ObjectTypes import ObjectType, SETObject
from .Names import REGION_INDICES, REGION_RESTRICTION_TYPES, Characters, WEAPONS

DESIRABLE_OBJECTS_THE_DOOM = [

    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 397, "Heal Server 1"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 396, "Heal Server 2"),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_THE_DOOM, 258, "Special Weapons Box 1",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE),
    SETObject(ObjectType.KEY_DOOR, Levels.STAGE_THE_DOOM, 178, "Secret Door",
              region=REGION_INDICES.THE_DOOM_KEY_DOOR),
    SETObject(ObjectType.STANDARD_PULLEY, Levels.STAGE_THE_DOOM, 189, "Pulley To Secret Door"),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_THE_DOOM, 109, "Special Weapons Box 2",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.HEAVY_MACHINE_GUN),

    SETObject(ObjectType.BOMB_SERVER, Levels.STAGE_THE_DOOM, 214, "Bomb Server 1"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 398, "Heal Server 2"),
    SETObject(ObjectType.BOMB_SERVER, Levels.STAGE_THE_DOOM, 285, "Bomb Server 2"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 403, "Heal Server 3"),
    SETObject(ObjectType.STANDARD_PULLEY, Levels.STAGE_THE_DOOM, 194, "Pulley (Key 4)"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 400, "Heal Server 4"),

    SETObject(ObjectType.BOMB_SERVER, Levels.STAGE_THE_DOOM, 222, "Bomb Server 3"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 399, "Heal Server 5"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 401, "Heal Server 6"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 402, "Heal Server 7"),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_THE_DOOM, 265, "Special Weapons Box 3",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX, weapon=WEAPONS.RPG),

    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 408, "Doom Researcher 1",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 412, "Doom Researcher 2",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 409, "Doom Researcher 3",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 407, "Doom Researcher 4",
              region=REGION_INDICES.THE_DOOM_BOMBS, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 413, "Doom Researcher 5",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 410, "Doom Researcher 6",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 483, "Doom Researcher 7",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 411, "Doom Researcher 8",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 405, "Doom Researcher 9",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 406, "Doom Researcher 10",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, restrictionType=REGION_RESTRICTION_TYPES.Heal),

    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 135, "1",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="0"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 114, "2",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="1"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 122, "3",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="2"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 123, "4",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.PISTOL, old_name="3"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 213, "5",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, old_name="4"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 187, "6",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="5"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 188, "7",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, old_name="6"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 186, "8",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, old_name="7"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 140, "9",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="8"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 86, "10",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="9"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 87, "11",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.PISTOL, old_name="10"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 141, "12",
              region=REGION_INDICES.THE_DOOM_BOMBS, weapon=WEAPONS.PISTOL, old_name="11"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 139, "13",
              region=REGION_INDICES.THE_DOOM_BOMBS, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="12"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 127, "14",
              region=REGION_INDICES.THE_DOOM_BOMBS, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="13"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 116, "15",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="14"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 142, "16",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO, weapon=WEAPONS.PISTOL, old_name="15"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 143, "17",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO, weapon=WEAPONS.PISTOL, old_name="17"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 144, "18",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO, weapon=WEAPONS.PISTOL, old_name="18"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 145, "19",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="19"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 161, "20",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="21"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 162, "21",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="22"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 163, "22",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="23"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 166, "23",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="24"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 167, "24",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="25"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 217, "25",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="26"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 219, "26",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, old_name="27"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 224, "27",
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH, weapon=WEAPONS.EIGHT_SHOT_RPG, old_name="28"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 226, "28",
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="29"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 195, "29",
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="30"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 259, "30",
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="31"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 196, "31",
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH, weapon=WEAPONS.GRENADE_LAUNCHER, old_name="32"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 228, "32",
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="33"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 233, "33",
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH, old_name="34"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 231, "34",
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH, old_name="35"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 229, "35",
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="45.5"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 237, "36",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="36"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 235, "37",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="37"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 236, "38",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="38"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 239, "39",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="39"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 238, "40",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="40"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 206, "41",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="41"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 230, "42",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="42"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 260, "43",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="43"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 240, "44",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FOUR, weapon=WEAPONS.SURVIVAL_KNIFE, old_name="45"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 242, "45",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FIVE, old_name="44"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 244, "46",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FIVE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="46"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 245, "47",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FIVE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="47"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 243, "48",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FIVE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="48"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 246, "49",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FIVE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="49"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 247, "50",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FIVE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="50"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 119, "51",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_FIVE, old_name="54.5"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 249, "52",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX, weapon=WEAPONS.HEAVY_MACHINE_GUN,
              old_name="45.51"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 210, "53",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="51"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 250, "54",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="52"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 252, "55",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX, weapon=WEAPONS.EIGHT_SHOT_RPG, old_name="53"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_THE_DOOM, 251, "56",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX, weapon=WEAPONS.EIGHT_SHOT_RPG, old_name="54"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 254, "57",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="56"),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 253, "58",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="57"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 255, "59",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="55"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 256, "60",
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE, old_name="58"),


    SETObject(ObjectType.GOLD_BEETLE, Levels.STAGE_THE_DOOM, 363, 'Gold Beetle',
              region=REGION_INDICES.THE_DOOM_GOLD_BEETLE),

    SETObject(ObjectType.KEY, Levels.STAGE_THE_DOOM, 107, 'Key 1', region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE),
    SETObject(ObjectType.KEY, Levels.STAGE_THE_DOOM, 108, 'Key 2', region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE),
    SETObject(ObjectType.KEY, Levels.STAGE_THE_DOOM, 112, 'Key 3', region=REGION_INDICES.THE_DOOM_BOMBS),
    SETObject(ObjectType.KEY, Levels.STAGE_THE_DOOM, 110, 'Key 4', region=REGION_INDICES.THE_DOOM_PULLEY_2),
    SETObject(ObjectType.KEY, Levels.STAGE_THE_DOOM, 154, 'Key 5', region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE),

    SETObject(ObjectType.GOAL_RING, Levels.STAGE_THE_DOOM, 414, 'Goal Ring', region=REGION_INDICES.THE_DOOM_CHECKPOINT_SIX),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_THE_DOOM, 131, 'Start',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 185, 'By Key 1',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_THE_DOOM, 191, 'Door Room A',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_THE_DOOM, 137, 'Door Room B',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 115, 'By Key 2',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_THE_DOOM, 388, 'After Bomb A',
              region=REGION_INDICES.THE_DOOM_BOMBS),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_THE_DOOM, 389, 'After Bomb B',
              region=REGION_INDICES.THE_DOOM_BOMBS),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_THE_DOOM, 386, 'After Bomb C',
              region=REGION_INDICES.THE_DOOM_BOMBS),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_THE_DOOM, 387, 'After Bomb D',
              region=REGION_INDICES.THE_DOOM_BOMBS),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_THE_DOOM, 391, 'After Bomb E',
              region=REGION_INDICES.THE_DOOM_BOMBS),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 184, 'Up Bomb Lift A',
              region=REGION_INDICES.THE_DOOM_BOMBS),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 95, 'Near Key 4',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_THE_DOOM, 133, 'Nearer Key 4',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 193, 'Right Next to Key 4',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 197, 'Fan Room Item A',
              region=REGION_INDICES.THE_DOOM_FAN_ROOM),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 198, 'Fan Room Item B',
              region=REGION_INDICES.THE_DOOM_FAN_ROOM),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 199, 'Fan Room Item C',
              region=REGION_INDICES.THE_DOOM_FAN_ROOM),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 203, 'Lift Cross A',
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 350, 'Lift Cross B',
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 351, 'Lift Cross C',
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 352, 'Lift Cross D',
              region=REGION_INDICES.THE_DOOM_DOOR_1_SWITCH),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 284, 'Blast Room A',
              region=REGION_INDICES.THE_DOOM_WALL_ROOM),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 283, 'Blast Room B',
              region=REGION_INDICES.THE_DOOM_WALL_ROOM),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 281, 'Blast Room C',
              region=REGION_INDICES.THE_DOOM_WALL_ROOM),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_THE_DOOM, 282, 'Blast Room D',
              region=REGION_INDICES.THE_DOOM_WALL_ROOM),

    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_THE_DOOM, 0, '1', count=1),
    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_THE_DOOM, 1, '2', count=2),
    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_THE_DOOM, 4, '3', count=3),
    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_THE_DOOM, 12, '4', count=4),
    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_THE_DOOM, 79, '5', count=5),
    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_THE_DOOM, 14, '6', count=6),

    SETObject(ObjectType.PARTNER, Levels.STAGE_THE_DOOM, 417, 'Maria', character=Characters.Maria,
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE),
    SETObject(ObjectType.PARTNER, Levels.STAGE_THE_DOOM, 445, 'Dooms Eye', character=Characters.Doom,
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE),


    #SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 120, '120',
    #          region=REGION_INDICES.X, weapon=WEAPONS.RPG),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 121, '121',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.PISTOL),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 129, '129',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.PISTOL),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 158, '158',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, weapon=WEAPONS.SUB_MACHINE_GUN),
    #SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 164, '164',
    #          region=REGION_INDICES.X, weapon=WEAPONS.RPG),
    #SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 165, '165',
    #          region=REGION_INDICES.X, weapon=WEAPONS.RPG),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 176, '176',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.HEAVY_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 177, '177',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO, weapon=WEAPONS.GRENADE_LAUNCHER),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 179, '179',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 180, '180',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 220, '220',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_THREE, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 375, '375',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 376, '376',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 379, '379',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 380, '380',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.HEAVY_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 381, '381',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_ONE, weapon=WEAPONS.HEAVY_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 382, '382',
              region=REGION_INDICES.THE_DOOM_BOMBS, weapon=WEAPONS.GRENADE_LAUNCHER),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 383, '383',
              region=REGION_INDICES.THE_DOOM_BOMBS, weapon=WEAPONS.GRENADE_LAUNCHER),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 384, '384',
              region=REGION_INDICES.THE_DOOM_BOMBS, weapon=WEAPONS.GRENADE_LAUNCHER),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 385, '385',
              region=REGION_INDICES.THE_DOOM_BOMBS, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_THE_DOOM, 390, '390',
              region=REGION_INDICES.THE_DOOM_CHECKPOINT_TWO, weapon=WEAPONS.SUB_MACHINE_GUN),



]