from . import Levels, Weapons
from .ObjectTypes import ObjectType, SETObject, ObjectTypeVehicles
from .Names import REGION_INDICES, Characters, WEAPONS

DESIRABLE_OBJECTS_LETHAL_HIGHWAY  = [

    SETObject(ObjectType.HEAL_UNIT, Levels.STAGE_LETHAL_HIGHWAY, 395, "Heal Unit 1"),
    SETObject(ObjectType.HEAL_UNIT, Levels.STAGE_LETHAL_HIGHWAY, 376, "Heal Unit 2"),
    SETObject(ObjectType.HEAL_UNIT, Levels.STAGE_LETHAL_HIGHWAY, 541, "Heal Unit 3"),
    SETObject(ObjectType.HEAL_UNIT, Levels.STAGE_LETHAL_HIGHWAY, 542, "Heal Unit 4"),

    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_LETHAL_HIGHWAY, 320, "Special Weapons Box 1",
              region=REGION_INDICES.LETHAL_HIGHWAY_TWO_FALL, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE),
    SETObject(ObjectType.KEY_DOOR, Levels.STAGE_LETHAL_HIGHWAY, 25, "Secret Door",
              region=REGION_INDICES.LETHAL_HIGHWAY_KEY_DOOR),
    SETObject(ObjectType.ROCKET, Levels.STAGE_LETHAL_HIGHWAY, 399, "Rocket 1"),

    SETObject(ObjectType.VEHICLE, Levels.STAGE_LETHAL_HIGHWAY, 154, "Motorbike 1",
              vehicle=ObjectTypeVehicles.GUN_MOTORCYCLE,
              region=REGION_INDICES.LETHAL_HIGHWAY_ROCKET),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LETHAL_HIGHWAY, 342, "Convertible 1",
              vehicle=ObjectTypeVehicles.CONVERTIBLE,
              region=REGION_INDICES.LETHAL_HIGHWAY_ROCKET),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_LETHAL_HIGHWAY, 518, "Special Weapons Box 2",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, weapon=WEAPONS.FLASH_SHOT),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_LETHAL_HIGHWAY, 141, "Special Weapons Box 3",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE),

    SETObject(ObjectType.ENERGY_CORE, Levels.STAGE_LETHAL_HIGHWAY, 458, "Dark Energy Core",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_LETHAL_HIGHWAY, 324, "Special Weapons Box 4",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL_2, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE),
    SETObject(ObjectType.STANDARD_PULLEY, Levels.STAGE_LETHAL_HIGHWAY, 53, "Pulley"),

    SETObject(ObjectType.VEHICLE, Levels.STAGE_LETHAL_HIGHWAY, 230, "Motorbike 2",
              vehicle=ObjectTypeVehicles.GUN_MOTORCYCLE,
              region=REGION_INDICES.LETHAL_HIGHWAY_ROCKET),
    SETObject(ObjectType.HEAL_UNIT, Levels.STAGE_LETHAL_HIGHWAY, 377, "Heal Unit 5"),
    SETObject(ObjectType.ROCKET, Levels.STAGE_LETHAL_HIGHWAY, 381, "Rocket 2"),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_LETHAL_HIGHWAY, 519, "Special Weapon Box 5",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LETHAL_HIGHWAY, 343, "Convertible 2",
              vehicle=ObjectTypeVehicles.CONVERTIBLE,
              region=REGION_INDICES.LETHAL_HIGHWAY_ROCKET),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LETHAL_HIGHWAY, 297, "Motorbike 3",
              vehicle=ObjectTypeVehicles.GUN_MOTORCYCLE,
              region=REGION_INDICES.LETHAL_HIGHWAY_ROCKET),

    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 87, "1",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO, weapon=WEAPONS.PISTOL, old_name="0"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 94, "2",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO, old_name="1"),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 85, "3",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO, old_name="2", is_hard=True),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 86, "4",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO, old_name="3", is_hard=True),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 89, "5",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO, weapon=WEAPONS.SUB_MACHINE_GUN,
              old_name="4"),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 96, "6",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO, old_name="5", is_hard=True),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 98, "7",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO, weapon=WEAPONS.LIGHT_SHOT, old_name="6"),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 105, "8",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ONE, old_name="7", count=4),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 104, "9",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ONE, old_name="8", count=4),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 108, "10",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ONE, old_name="10", count=3),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 111, "11",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ONE, old_name="11"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 109, "12",
              region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="12"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 110, "13",
              region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="13"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 117, "14",
              region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="14"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 118, "15",
              region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="15"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LETHAL_HIGHWAY, 127, "16",
              region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, weapon=WEAPONS.SUB_MACHINE_GUN,
              old_name="16"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 126, "17",
              region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, old_name="17"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 131, "18",
              region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="18"),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 134, "19",
              region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, old_name="19", count=4),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 132, "20",
              region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, old_name="20", count=3),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 139, "21",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_TWO, old_name="21", count=8),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 143, "22",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_TWO, weapon=WEAPONS.PISTOL, old_name="22"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 144, "23",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_TWO, weapon=WEAPONS.PISTOL, old_name="23"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 145, "24",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_TWO, weapon=WEAPONS.FLASH_SHOT, old_name="24"),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 167, "25",
              region=REGION_INDICES.LETHAL_HIGHWAY_TWO_FALL, old_name="25", count=4),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 168, "26",
              region=REGION_INDICES.LETHAL_HIGHWAY_TWO_FALL, old_name="26"),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 166, "27",
              region=REGION_INDICES.LETHAL_HIGHWAY_TWO_FALL, old_name="27", count=5),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 172, "28",
              region=REGION_INDICES.LETHAL_HIGHWAY_TWO_FALL, weapon=WEAPONS.FLASH_SHOT, old_name="28"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 323, "29",
              region=REGION_INDICES.LETHAL_HIGHWAY_TWO_FALL, weapon=WEAPONS.FLASH_SHOT, old_name="29"),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 536, "30",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, old_name="30", count=5),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 535, "31",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, old_name="31", count=2),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 538, "32",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, old_name="32", count=4),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 537, "33",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, old_name="33", count=3),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 369, "34",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, old_name="34", count=6),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 192, "35",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, old_name="35", count=4),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 203, "36",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, weapon=WEAPONS.SUB_MACHINE_GUN,
              old_name="36"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 209, "37",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, weapon=WEAPONS.FLASH_SHOT, old_name="37"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 208, "38",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, weapon=WEAPONS.FLASH_SHOT, old_name="38"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 210, "39",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, weapon=WEAPONS.FLASH_SHOT, old_name="39"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 52, "40",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL, weapon=WEAPONS.LIGHT_SHOT, old_name="40"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 51, "41",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL, weapon=WEAPONS.LIGHT_SHOT, old_name="41"),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 50, "42",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL, old_name="42"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 240, "43",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL, weapon=WEAPONS.PISTOL, old_name="43"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 241, "44",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL, weapon=WEAPONS.PISTOL, old_name="44"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 219, "45",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL_2, weapon=WEAPONS.FLASH_SHOT, old_name="45"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 220, "46",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL_2, weapon=WEAPONS.FLASH_SHOT, old_name="46"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 221, "47",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL_2, weapon=WEAPONS.FLASH_SHOT, old_name="47"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 223, "48",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL_2, weapon=WEAPONS.FLASH_SHOT, old_name="48"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 229, "49",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL_2, weapon=WEAPONS.FLASH_SHOT, old_name="49"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LETHAL_HIGHWAY, 384, "50",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL_2, old_name="50"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LETHAL_HIGHWAY, 383, "51",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL_2, old_name="51"),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 385, "52",
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL_2, old_name="52"),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 259, "53",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, old_name="53", is_hard=True),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 260, "54",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, old_name="54", is_hard=True),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 269, "55",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, weapon=WEAPONS.SUB_MACHINE_GUN,
              old_name="55"),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 267, "56",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, old_name="56", count=6),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 266, "57",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, old_name="57", count=4),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 268, "58",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, weapon=WEAPONS.FLASH_SHOT, old_name="58"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 270, "59",
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, weapon=WEAPONS.FLASH_SHOT, old_name="59"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 282, "60",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_BOMB, weapon=WEAPONS.PISTOL, old_name="61"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 284, "61",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_BOMB, weapon=WEAPONS.FLASH_SHOT, old_name="62"),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 281, "62",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_BOMB, old_name="63", is_hard=True),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 289, "63",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_BOMB, old_name="64"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 290, "64",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_BOMB, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="66"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LETHAL_HIGHWAY, 288, "65",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_BOMB, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="67"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LETHAL_HIGHWAY, 291, "66",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_BOMB, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="68"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 292, "67",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_BOMB, weapon=WEAPONS.LIGHT_SHOT, old_name="83.1"),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 251, "68",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_BOMB, old_name="83.99", count=4),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LETHAL_HIGHWAY, 390, "69",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, old_name="69"),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LETHAL_HIGHWAY, 389, "70",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.SUB_MACHINE_GUN,
              old_name="70"),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 298, "71",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.LIGHT_SHOT, old_name="71"),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 296, "72",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, old_name="72", is_hard=True),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 340, "73",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="73"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 304, "74",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE,
              old_name="74"),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 302, "75",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, old_name="75", count=8),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 303, "76",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, old_name="76", count=8),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 75, "77",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.PISTOL, old_name="77"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 334, "78",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.PISTOL, old_name="78"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 66, "79",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.PISTOL, old_name="79"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 67, "80",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.PISTOL, old_name="80"),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LETHAL_HIGHWAY, 70, "81",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.SUB_MACHINE_GUN, old_name="81"),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 68, "82",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, old_name="82"),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 64, "83",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, old_name="83"),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_LETHAL_HIGHWAY, 253, "84",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, old_name="83.0", is_hard=True),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_LETHAL_HIGHWAY, 366, "85",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, old_name="83.2"),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 356, "86",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, old_name="83.3", count=5),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_LETHAL_HIGHWAY, 357, "87",
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, old_name="83.4", count=6),

    SETObject(ObjectType.GOLD_BEETLE, Levels.STAGE_LETHAL_HIGHWAY, 374, 'Gold Beetle',
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR),

    SETObject(ObjectType.KEY, Levels.STAGE_LETHAL_HIGHWAY, 337, 'Key 1',
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ONE),
    SETObject(ObjectType.KEY, Levels.STAGE_LETHAL_HIGHWAY, 157, 'Key 2',
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_TWO),
    SETObject(ObjectType.KEY, Levels.STAGE_LETHAL_HIGHWAY, 152, 'Key 3',
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_TWO),
    SETObject(ObjectType.KEY, Levels.STAGE_LETHAL_HIGHWAY, 227, 'Key 4',
              region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL_2),
    SETObject(ObjectType.KEY, Levels.STAGE_LETHAL_HIGHWAY, 352, 'Key 5',
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET),
    SETObject(ObjectType.GOAL_RING, Levels.STAGE_LETHAL_HIGHWAY, 81, 'Goal Ring',
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET),


    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_LETHAL_HIGHWAY, 100, 'Rotating Item Box 1',
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ONE),
    SETObject(ObjectType.ITEM_IN_BOX, Levels.STAGE_LETHAL_HIGHWAY, 128, '5 Rings in Box',
              region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_LETHAL_HIGHWAY, 171, 'Highway Down',
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LETHAL_HIGHWAY, 255, 'Life Behind Blast Area',
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FIVE),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_LETHAL_HIGHWAY, 367, 'Cage Under End Pass',
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET),

    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_LETHAL_HIGHWAY, 112, '1', count=1),
    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_LETHAL_HIGHWAY, 136, '2', count=2),
    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_LETHAL_HIGHWAY, 153, '3', count=3),
    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_LETHAL_HIGHWAY, 235, '4', count=4),
    SETObject(ObjectType.CHECKPOINT, Levels.STAGE_LETHAL_HIGHWAY, 250, '5', count=5),

    SETObject(ObjectType.PARTNER, Levels.STAGE_LETHAL_HIGHWAY, 462, 'Dooms Eye 1', character=Characters.Doom,
          region=REGION_INDICES.LETHAL_HIGHWAY_TWO_FALL),
    SETObject(ObjectType.PARTNER, Levels.STAGE_LETHAL_HIGHWAY, 463, 'Sonic 1', character=Characters.Sonic,
              region=REGION_INDICES.LETHAL_HIGHWAY_ROCKET),
    SETObject(ObjectType.PARTNER, Levels.STAGE_LETHAL_HIGHWAY, 464, 'Sonic 2', character=Characters.Sonic,
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FIVE),
    SETObject(ObjectType.PARTNER, Levels.STAGE_LETHAL_HIGHWAY, 465, 'Dooms Eye 2', character=Characters.Doom,
              region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET),
    SETObject(ObjectType.PARTNER, Levels.STAGE_LETHAL_HIGHWAY, 466, 'Dooms Eye 3', character=Characters.Doom,
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO),
    SETObject(ObjectType.PARTNER, Levels.STAGE_LETHAL_HIGHWAY, 477, 'Sonic 3', character=Characters.Sonic,
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO),
    SETObject(ObjectType.PARTNER, Levels.STAGE_LETHAL_HIGHWAY, 539, 'Sonic 4', character=Characters.Sonic,
              region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_TWO),    
    
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 124, '124', 
        region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 125, '125', 
        region=REGION_INDICES.LETHAL_HIGHWAY_ONE_FALL, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 155, '155', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ONE, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 173, '173', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 174, '174', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 201, '201', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 236, '236', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 277, '277', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FIVE, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.FLOOR_WEAPON, Levels.STAGE_LETHAL_HIGHWAY, 321, '321', 
        region=REGION_INDICES.LETHAL_HIGHWAY_KEY_DOOR, weapon=WEAPONS.GATLING_GUN),
    SETObject(ObjectType.FLOOR_WEAPON, Levels.STAGE_LETHAL_HIGHWAY, 322, '322', 
        region=REGION_INDICES.LETHAL_HIGHWAY_KEY_DOOR, weapon=WEAPONS.GATLING_GUN),
    SETObject(ObjectType.ENVIRONMENT_WEAPON, Levels.STAGE_LETHAL_HIGHWAY, 335, '335', 
        region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.LETHAL_POLE),
    SETObject(ObjectType.ENVIRONMENT_WEAPON, Levels.STAGE_LETHAL_HIGHWAY, 336, '336', 
        region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.LETHAL_POLE),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 344, '344', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_TWO, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.ENVIRONMENT_WEAPON, Levels.STAGE_LETHAL_HIGHWAY, 346, '346', 
        region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL, weapon=WEAPONS.LETHAL_POLE),
    SETObject(ObjectType.ENVIRONMENT_WEAPON, Levels.STAGE_LETHAL_HIGHWAY, 353, '353', 
        region=REGION_INDICES.LETHAL_HIGHWAY_THREE_FALL, weapon=WEAPONS.LETHAL_POLE),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 364, '364', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ONE, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 368, '368', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 382, '382', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_ZERO, weapon=WEAPONS.PISTOL),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 420, '420', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 421, '421', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 514, '514', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, weapon=WEAPONS.SUB_MACHINE_GUN),
    #SETObject(ObjectType.FLOOR_WEAPON, Levels.STAGE_LETHAL_HIGHWAY, 515, '515',
    #    region=REGION_INDICES.FLASH_SHOT, weapon=WEAPONS.FLASH_SHOT),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 517, '517', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_FOUR, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 520, '520', 
        region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.FLASH_SHOT),
    #SETObject(ObjectType.FLOOR_WEAPON, Levels.STAGE_LETHAL_HIGHWAY, 521, '521',
    #    region=REGION_INDICES.FLASH_SHOT, weapon=WEAPONS.UNKNOWN),
    SETObject(ObjectType.WEAPON_BOX, Levels.STAGE_LETHAL_HIGHWAY, 522, '522', 
        region=REGION_INDICES.LETHAL_HIGHWAY_FIVE_ROCKET, weapon=WEAPONS.FLASH_SHOT),
    SETObject(ObjectType.FLOOR_WEAPON, Levels.STAGE_LETHAL_HIGHWAY, 540, '540', 
        region=REGION_INDICES.LETHAL_HIGHWAY_CHECKPOINT_THREE, weapon=WEAPONS.FLASH_SHOT),
]