from . import Levels
from .ObjectTypes import ObjectType, SETObject
from .Names import REGION_INDICIES
from .Weapons import WEAPONS

DESIRABLE_OBJECTS_PRISON_ISLAND  = [

    # Prison Island

    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND,
              164, "Air Saucer 1 Enemy", vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER,
              region=0),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_PRISON_ISLAND, 462,
              "Air Saucer 1 Despawn", vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER),
    SETObject(ObjectType.BOMB, Levels.STAGE_PRISON_ISLAND, 266, "Key 2 Bomb 1"),
    SETObject(ObjectType.BOMB, Levels.STAGE_PRISON_ISLAND, 278, "Key 2 Bomb 2"),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_PRISON_ISLAND, 282, "Air Saucer @ Key 2",
              vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER,
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_PRISON_ISLAND, 383, "Special Weapon Box 1",
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER, weapon=WEAPONS.HEAVY_MACHINE_GUN),
    SETObject(ObjectType.KEY_DOOR, Levels.STAGE_PRISON_ISLAND, 432, "Secret Door",
              region=REGION_INDICIES.PRISON_ISLAND_KEY_DOOR),

    SETObject(ObjectType.STANDARD_PULLEY, Levels.STAGE_PRISON_ISLAND, 565, "Pulley 1"),

    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_PRISON_ISLAND, 379, "Special Weapon Box 2",
              region=REGION_INDICIES.PRISON_ISLAND_PULLEY_EASY, weapon=WEAPONS.RING_SHOT),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_PRISON_ISLAND, 514, "Special Weapon Box 3",
              region=REGION_INDICIES.PRISON_ISLAND_PULLEY_EASY, weapon=WEAPONS.RING_SHOT),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_PRISON_ISLAND, 551, "Air Saucer 2 Despawn",
              vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER),

    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND,
              562, "Air Saucer 2 Enemy", vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER,
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),

    SETObject(ObjectType.ENERGY_CORE, Levels.STAGE_PRISON_ISLAND, 597, "Dark Energy Core",
              region=REGION_INDICIES.PRISON_ISLAND_PULLEY_EASY),

    SETObject(ObjectType.VEHICLE, Levels.STAGE_PRISON_ISLAND, 586, "Air Saucer Dark Split",
              vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER,
              region=REGION_INDICIES.PRISON_ISLAND_PULLEY_EASY),

    SETObject(ObjectType.VEHICLE, Levels.STAGE_PRISON_ISLAND, 577, "Air Saucer Hero Split",
              vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER,
              region=REGION_INDICIES.PRISON_ISLAND_PULLEY_EASY),

    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND,
              330, "Air Saucer Hero Split 2 Enemy 1", vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER,
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND,
              331, "Air Saucer Hero Split 2 Enemy 2", vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER,
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),

    SETObject(ObjectType.VEHICLE, Levels.STAGE_PRISON_ISLAND, 337, "Air Saucer Hero Split 2 (Enemy)",
              vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_PRISON_ISLAND, 344, "Air Saucer Hero Split 3",
              vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER),

    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_PRISON_ISLAND, 598, "Special Weapon Box 4",
              region=REGION_INDICIES.PRISON_ISLAND_PULLEY_EASY, weapon=WEAPONS.RING_SHOT),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND,
              567, "Air Saucer 3 Enemy", vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER,
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_PRISON_ISLAND, 544, "Air Saucer 3 Despawn",
              vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_PRISON_ISLAND, 520, "Air Saucer After 3",
              vehicle=ObjectType.ObjectTypeVehicle.AIR_SAUCER,
              region=REGION_INDICIES.PRISON_ISLAND_PULLEY_EASY),

    SETObject(ObjectType.PRISON_ISLAND_DISC, Levels.STAGE_PRISON_ISLAND,
              606, "Secret Disc 1",
              region=0),
    SETObject(ObjectType.PRISON_ISLAND_DISC, Levels.STAGE_PRISON_ISLAND,
              603, "Secret Disc 2",
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.PRISON_ISLAND_DISC, Levels.STAGE_PRISON_ISLAND,
              610, "Secret Disc 3",
              region=REGION_INDICIES.PRISON_ISLAND_PULLEY_EASY),
    SETObject(ObjectType.PRISON_ISLAND_DISC, Levels.STAGE_PRISON_ISLAND,
              608, "Secret Disc 4",
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.PRISON_ISLAND_DISC, Levels.STAGE_PRISON_ISLAND,
              609, "Secret Disc 5",
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),

    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 129, '0', region=0),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 459, '1', region=0),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 103, '2', region=0),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 600, '3', region=0),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 21, '4', region=0),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 444, '5', region=0),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 163, '6', region=0),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 263, '7',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_PRISON_ISLAND, 259, '8',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER, count=6),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 274, '9',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 275, '10',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 267, '11',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 269, '12',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_PRISON_ISLAND, 272, '13',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER, count=6),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 299, '14',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 298, '15',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 304, '17',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 363, '18',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 364, '19',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 303, '20',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 351, '21',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_PRISON_ISLAND, 582, '22',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER, count=6),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 583, '23',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 584, '24',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 381, '25',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 171, '26',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 172, '27',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 178, '28',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 177, '29',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 184, '30',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 99, '31',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_PRISON_ISLAND, 433, '32',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER, count=4),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 97, '33',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 93, '34',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 148, '35',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_PRISON_ISLAND, 431, '36',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER, count=4),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_PRISON_ISLAND, 243, '37',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 438, '38',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 436, '39',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_PRISON_ISLAND, 434, '40',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER, count=3),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 437, '41',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 439, '42',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 440, '43',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 592, '44',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_PRISON_ISLAND, 435, '45',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER, count=5),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_PRISON_ISLAND, 25, '46',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 443, '47',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 390, '48',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 36, '49',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 35, '50',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_PRISON_ISLAND, 19, '51',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER, count=3),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_PRISON_ISLAND, 33, '52',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER, count=3),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 564, '53',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 47, '54',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 44, '55',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 535, '56',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 40, '57',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 122, '58',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 190, '59',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 545, '60',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 546, '61',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 574, '62',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 547, '63',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 575, '64',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 309, '65',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 71, '66',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 555, '67',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 72, '68',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 73, '69',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 89, '70',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 102, '71',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 59, '72',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 558, '73',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 559, '74',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 399, '75',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 104, '76',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 105, '77',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GOLD_BEETLE, Levels.STAGE_PRISON_ISLAND, 522, 'Gold Beetle',
              region=REGION_INDICIES.PRISON_ISLAND_GOLD_BEETLE),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 405, '79',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_PRISON_ISLAND, 408, '80',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 445, '81',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 414, '82',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 589, '83',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 119, '84',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 588, '85',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 117, '86',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 347, '87',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_PRISON_ISLAND, 348, '88',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 350, '89',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 349, '90',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 213, '91',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_PRISON_ISLAND, 341, '92',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_PRISON_ISLAND, 234, '93',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 235, '94',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 232, '95',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_PRISON_ISLAND, 238, '96',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_PRISON_ISLAND, 239, '97',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_PRISON_ISLAND, 400, '98',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),

    SETObject(ObjectType.KEY, Levels.STAGE_PRISON_ISLAND, 517, 'Key 1', region=0),
    SETObject(ObjectType.KEY, Levels.STAGE_PRISON_ISLAND, 258, 'Key 2', region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.KEY, Levels.STAGE_PRISON_ISLAND, 384, 'Key 3', region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.KEY, Levels.STAGE_PRISON_ISLAND, 385, 'Key 4', region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.KEY, Levels.STAGE_PRISON_ISLAND, 518, 'Key 5', region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.GOAL_RING, Levels.STAGE_PRISON_ISLAND, 607, 'Goal Ring',region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_PRISON_ISLAND, 150, 'At Start',
              region=0),
    SETObject(ObjectType.ITEM_IN_BOX, Levels.STAGE_PRISON_ISLAND, 601, 'After Spring',
              region=0),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_PRISON_ISLAND, 460, 'In Side Jump',
              region=0),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_PRISON_ISLAND, 157, 'Jump Pad',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),

    SETObject(ObjectType.ITEM_IN_BOX, Levels.STAGE_PRISON_ISLAND, 296, 'Hero Route Up',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_PRISON_ISLAND, 382, 'Down Route Down',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_PRISON_ISLAND, 92, 'Behind Key',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.ITEM_IN_BOX, Levels.STAGE_PRISON_ISLAND, 169, 'After Check 3',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.ITEM_IN_BOX, Levels.STAGE_PRISON_ISLAND, 465, 'Under',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_PRISON_ISLAND, 313, 'Box Past Key 4',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_PRISON_ISLAND, 106, 'Life on Dark Path',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_PRISON_ISLAND, 427, 'At Check 5',
              region=REGION_INDICIES.PRISON_ISLAND_AIR_SAUCER),
    ]