from . import Levels
from .ObjectTypes import ObjectType, SETObject
from .Names import REGION_INDICIES
from .Weapons import WEAPONS

DESIRABLE_OBJECTS_DEATH_RUINS  = [

    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_DEATH_RUINS, 283, "Special Weapons Box 1",
              region=0, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE),
    SETObject(ObjectType.STANDARD_PULLEY, Levels.STAGE_DEATH_RUINS, 153, "Pulley 1"),
    SETObject(ObjectType.WARP_HOLE, Levels.STAGE_DEATH_RUINS, 341, "Warp Hole Exit"),
    SETObject(ObjectType.KEY_DOOR, Levels.STAGE_DEATH_RUINS, 3, "Secret Door",
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR),
    SETObject(ObjectType.WARP_HOLE, Levels.STAGE_DEATH_RUINS, 380, "Warp Hole Entrance"),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_DEATH_RUINS, 294, "Special Weapons Box 2",
              region=REGION_INDICIES.DEATH_RUINS_WALLS, weapon=WEAPONS.GRENADE_LAUNCHER),
    SETObject(ObjectType.STANDARD_PULLEY, Levels.STAGE_DEATH_RUINS, 86, "Pulley 2"),
    SETObject(ObjectType.STANDARD_PULLEY, Levels.STAGE_DEATH_RUINS, 40, "Pulley 3"),

    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 382, '0', region=0),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 383, '1', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 426, '2', region=0),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 428, '3', region=0),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 384, '4', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 376, '5',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 377, '6',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 388, '6.1',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 387, '6.2',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 314, '7',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 385, '8',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 386, '9',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 363, '10',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 323, '11',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 316, '12',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 320, '13',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 321, '14',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 318, '15',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),

    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 312, '16.1',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY, is_hard=True),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 311, '16.2',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY, is_hard=True),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 366, '16.3',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY, is_hard=True),

    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 369, '16',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY, is_hard=True),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 379, '17',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY, is_hard=True),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 313, '18',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY, is_hard=True),
    SETObject(ObjectType.GOLD_BEETLE, Levels.STAGE_DEATH_RUINS, 394, 'Gold Beetle',
              region=REGION_INDICIES.DEATH_RUINS_GOLD_BEETLE),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 395, '20',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY, is_hard=True),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 353, '21',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 356, '22',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 392, '23',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 391, '24',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 368, '25',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 307, '26',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),

    #SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 418, '26.1',
    #          region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    #SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 419, '26.2',
    #          region=REGION_INDICIES.DEATH_RUINS_PULLEY),

    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_DEATH_RUINS, 349, '27',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY, count=4),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 331, '28',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_DEATH_RUINS, 415, '29',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY, count=10),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_DEATH_RUINS, 330, '30', region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 417, '31',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 332, '32',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 416, '33',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 336, '34',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 364, '35',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 378, '37',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 420, '38',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 334, '39',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 350, '40',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_DEATH_RUINS, 337, '41',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_DEATH_RUINS, 367, '42',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 339, '43',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 338, '44',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_DEATH_RUINS, 340, '45',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BLACK_LARVAE, Levels.STAGE_DEATH_RUINS, 423, '46',
              region=REGION_INDICIES.DEATH_RUINS_WALLS, count=5),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 421, '47', region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_DEATH_RUINS, 422, '48', region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 345, '49',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 351, '50',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 346, '51',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 333, '52',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.BLACK_WARRIOR, Levels.STAGE_DEATH_RUINS, 375, '53',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),

    SETObject(ObjectType.KEY, Levels.STAGE_DEATH_RUINS, 282, 'Key 1', region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.KEY, Levels.STAGE_DEATH_RUINS, 284, 'Key 2', region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.KEY, Levels.STAGE_DEATH_RUINS, 299, 'Key 3', region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.KEY, Levels.STAGE_DEATH_RUINS, 301, 'Key 4', region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.KEY, Levels.STAGE_DEATH_RUINS, 303, 'Key 5', region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.GOAL_RING, Levels.STAGE_DEATH_RUINS, 458, 'Goal Ring',region=REGION_INDICIES.DEATH_RUINS_WALLS),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 315, 'Start',
              region=0),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 342, 'After Pulley',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 365, 'Behind Check 3',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 357, 'First Platform Off Rails',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 296, 'In Gun Case',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BALLOON_ITEM, Levels.STAGE_DEATH_RUINS, 319, 'Below Platform 1',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 354, 'Lower A',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.BALLOON_ITEM, Levels.STAGE_DEATH_RUINS, 374, 'Lower B',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 224, 'Lower C',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 327, 'Lower D',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 326, 'Near Checkpoint 4',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 329, 'Rails BA Platform A',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 355, 'Rails BA Platform B',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 264, 'Below Shaft',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 317, 'Off Before Check 5',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 335, 'Lower Route after Check 5',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 362, 'At Check 6',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 360, 'Under Path',
              region=REGION_INDICIES.DEATH_RUINS_PULLEY),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 344, 'Pole Descend A',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 343, 'Pole Descend B',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 347, 'Final BA Section A',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 348, 'Final BA Section B',
              region=REGION_INDICIES.DEATH_RUINS_WALLS),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 401, 'Key Life 1',
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR),
    SETObject(ObjectType.BALLOON_ITEM, Levels.STAGE_DEATH_RUINS, 402, 'Key Balloon 1',
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR),
    SETObject(ObjectType.BALLOON_ITEM, Levels.STAGE_DEATH_RUINS, 404, 'Key Balloon 2',
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 408, 'Key Trail 1',
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 407, 'Key Trail 2',
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 406, 'Key Trail 3',
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 405, 'Key Trail 4',
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 411, 'Key Life 2',
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 412, 'Key Trail 5',
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_DEATH_RUINS, 410, 'Key Trail 6',
              region=REGION_INDICIES.DEATH_RUINS_KEY_DOOR)


]