from . import Levels
from .ObjectTypes import ObjectType, SETObject
from .Names import REGION_INDICIES
from .Weapons import WEAPONS

DESIRABLE_OBJECTS_LOST_IMPACT = [

    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_LOST_IMPACT,
              158, "Special Weapons Box 1", region=0, weapon=WEAPONS.SUB_MACHINE_GUN),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LOST_IMPACT,
              345, "Gun Lift 1 (First Room)", vehicle=ObjectType.ObjectTypeVehicle.GUN_LIFT,
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.BOMB, Levels.STAGE_LOST_IMPACT,
              211, "Bomb (Lift Room 1)"),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LOST_IMPACT,
              342, "Gun Lift 2 (Second Room)", vehicle=ObjectType.ObjectTypeVehicle.GUN_LIFT,
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.BOMB, Levels.STAGE_LOST_IMPACT,
              216, "Side Room Bomb"),
    SETObject(ObjectType.STANDARD_PULLEY, Levels.STAGE_LOST_IMPACT,
              107, "Pulley To Secret Door"),
    SETObject(ObjectType.KEY_DOOR, Levels.STAGE_LOST_IMPACT,
              106, "Secret Door", region=REGION_INDICIES.LOST_IMPACT_KEY_DOOR),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LOST_IMPACT,
              317, "Secret Door Armored Car", vehicle=ObjectType.ObjectTypeVehicle.ARMORED_CAR,
              region=REGION_INDICIES.LOST_IMPACT_KEY_DOOR),
    SETObject(ObjectType.BOMB, Levels.STAGE_LOST_IMPACT,
              236, "Bomb (Between 2 AC)"),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LOST_IMPACT,
              340, "Gun Lift 3 (Fourth Room)", vehicle=ObjectType.ObjectTypeVehicle.GUN_LIFT,
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LOST_IMPACT,
              341, "Gun Lift 4 (Fifth Room)", vehicle=ObjectType.ObjectTypeVehicle.GUN_LIFT,
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ROCKET, Levels.STAGE_LOST_IMPACT,
              320, "Rocket to Key 3"),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LOST_IMPACT,
              340, "Gun Lift 5 (Seventh Room)", vehicle=ObjectType.ObjectTypeVehicle.GUN_LIFT,
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LOST_IMPACT,
              339, "Gun Lift 6 (Eighth Room)", vehicle=ObjectType.ObjectTypeVehicle.GUN_LIFT,
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.VEHICLE, Levels.STAGE_LOST_IMPACT,
              325, "Gun Lift 7 (Outer Room)", vehicle=ObjectType.ObjectTypeVehicle.GUN_LIFT,
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.BOMB, Levels.STAGE_LOST_IMPACT,
              277, "Bomb In Final Room"),

    SETObject(ObjectType.VEHICLE, Levels.STAGE_LOST_IMPACT, 55, '60', region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT,
              vehicle=ObjectType.ObjectTypeVehicle.GUN_LIFT_FAST),

    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 168, '1', region=0),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 196, '1.1', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 162, '2', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 171, '3', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 297, '4', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 195, '5', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 197, '6', region=0),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LOST_IMPACT, 185, '7', region=0),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 184, '8', region=0),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 191, '9', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 186, '10', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 190, '11', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 189, '12', region=0),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 188, '13', region=0),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 173, '14',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LOST_IMPACT, 175, '15',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 174, '16',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LOST_IMPACT, 176, '17',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 177, '18',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 178, '19',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LOST_IMPACT, 199, '20',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 198, '21',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 193, '22',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LOST_IMPACT, 203, '23',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 194, '24',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 192, '25',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 166, '26',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 210, '27',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 307, '28',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 206, '29',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 204, '30', region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 205, '31', region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 207, '32',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 308, '33',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 217, '34',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 218, '35',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 220, '36',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 229, '37',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 226, '38',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 228, '39',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 299, '40',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 234, '41',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 235, '42',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 232, '43',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 233, '44',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 300, '45',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LOST_IMPACT, 302, '46',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 237, '47',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LOST_IMPACT, 239, '48',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 238, '49',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LOST_IMPACT, 240, '50',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 242, '51',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 241, '52',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    #SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_LOST_IMPACT, 230, '52.1',
    #          region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    #SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_LOST_IMPACT, 231, '52.2',
    #          region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 165, '53',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 311, '54',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 270, '55',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 289, '56',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 288, '58',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 290, '59',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 312, '61',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 293, '62',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 294, '63',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 295, '64',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 296, '65',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 271, '66',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_LOST_IMPACT, 274, '67',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 272, '68',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 273, '69',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GUN_SOLDIER, Levels.STAGE_LOST_IMPACT, 310, '70.0',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 283, '70',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ARTIFICIAL_CHAOS, Levels.STAGE_LOST_IMPACT, 286, '71',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.GOLD_BEETLE, Levels.STAGE_LOST_IMPACT, 281, 'Gold Beetle',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),

    SETObject(ObjectType.KEY, Levels.STAGE_LOST_IMPACT, 126, 'Key 1', region=0),
    SETObject(ObjectType.KEY, Levels.STAGE_LOST_IMPACT, 101, 'Key 2', region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.KEY, Levels.STAGE_LOST_IMPACT, 323, 'Key 3', region=REGION_INDICIES.LOST_IMPACT_ROCKET),
    SETObject(ObjectType.KEY, Levels.STAGE_LOST_IMPACT, 116, 'Key 4', region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.KEY, Levels.STAGE_LOST_IMPACT, 117, 'Key 5', region=REGION_INDICIES.LOST_IMPACT_BOMB_WALL),
    SETObject(ObjectType.GOAL_RING, Levels.STAGE_LOST_IMPACT, 352, 'Goal Ring',region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 180, 'Near Shadow Box 1',
              region=0),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 309, 'Up Lift 1 A',
              region=0),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 248, 'Up Lift 1 B',
              region=0),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_LOST_IMPACT, 328, 'Lift Section 1A',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_LOST_IMPACT, 330, 'Lift Section 1B',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_LOST_IMPACT, 329, 'Lift Section 1C',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_LOST_IMPACT, 161, 'Room After Lift A',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_LOST_IMPACT, 179, 'Room After Lift B',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 214, '3 Right At Turn A',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 224, '3 Right At Turn B',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 316, '3 Right At Turn C',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 315, 'With Bomb Jump A',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 132, 'With Bomb Jump B',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 222, 'Left Way A',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 219, 'Left Way B',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 227, 'Near Keydoor',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 301, 'Side Room A',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 303, 'Side Room B',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 125, 'Before Meteors A',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 243, 'Before Meteors B',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 244, 'Before Meteors C',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),

    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 124, 'Room Corners A',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 247, 'Room Corners B',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 135, 'Room Corners C',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),
    SETObject(ObjectType.ITEM_IN_METAL_BOX, Levels.STAGE_LOST_IMPACT, 225, 'Room Corners D',
              region=REGION_INDICIES.LOST_IMPACT_GUN_LIFT),

    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_LOST_IMPACT, 279, 'Key 5 Room A',
              region=REGION_INDICIES.LOST_IMPACT_BOMB_WALL),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_LOST_IMPACT, 278, 'Key 5 Room B',
              region=REGION_INDICIES.LOST_IMPACT_BOMB_WALL)


]