from . import Levels
from .ObjectTypes import ObjectType, SETObject
from .Names import REGION_INDICIES
from .Weapons import WEAPONS

DESIRABLE_OBJECTS_MAD_MATRIX  = [

    SETObject(ObjectType.WARP_HOLE, Levels.STAGE_MAD_MATRIX, 165, "Warp Hole Into Green Tower"),
    SETObject(ObjectType.WARP_HOLE, Levels.STAGE_MAD_MATRIX, 163, "Warp Hole Exit Of Green Tower"),
    SETObject(ObjectType.WARP_HOLE_ANTI_TRAP, Levels.STAGE_MAD_MATRIX, 312, "Warp Hole Exit Of Red Tower"),
    SETObject(ObjectType.WARP_HOLE_ANTI_TRAP, Levels.STAGE_MAD_MATRIX, 324, "Warp Hole Exit From Top Of Red Tower"),
    SETObject(ObjectType.WARP_HOLE, Levels.STAGE_MAD_MATRIX, 107, "Warp Hole Into Yellow Tower"),

    SETObject(ObjectType.LIGHT_DASH_TRAIL_ANTI_TRAP, Levels.STAGE_MAD_MATRIX, 330, "Light Dash Near Green"),
    SETObject(ObjectType.LIGHT_DASH_TRAIL, Levels.STAGE_MAD_MATRIX, 269, "Light Dash Into Red"),
    SETObject(ObjectType.LIGHT_DASH_TRAIL, Levels.STAGE_MAD_MATRIX, 350, "Light Dash Out Of Red"),
    SETObject(ObjectType.LIGHT_DASH_TRAIL, Levels.STAGE_MAD_MATRIX, 552, "Light Dash Within Yellow"),
    SETObject(ObjectType.LIGHT_DASH_TRAIL_ANTI_TRAP, Levels.STAGE_MAD_MATRIX, 328, 'Light Dash Near Red/Yellow',
              region=REGION_INDICIES.MAD_MATRIX_GUN),

    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_MAD_MATRIX, 500, "Shadow Box Near Red",
              region=REGION_INDICIES.MAD_MATRIX_GUN, weapon=WEAPONS.WIDE_WORM_SHOOTER),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_MAD_MATRIX, 452, "Shadow Box Near Secret Door",
              region=REGION_INDICIES.MAD_MATRIX_GUN, weapon=WEAPONS.EGG_BAZOOKA),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_MAD_MATRIX, 444, "Shadow Box Near Blue",
              region=REGION_INDICIES.MAD_MATRIX_GUN, weapon=WEAPONS.EGG_BAZOOKA),
    SETObject(ObjectType.ENERGY_CORE, Levels.STAGE_MAD_MATRIX, 443, "Hero Core",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.KEY_DOOR, Levels.STAGE_MAD_MATRIX, 332, "Secret Door",
              region=REGION_INDICIES.MAD_MATRIX_KEY_DOOR),

    SETObject(ObjectType.MAD_MATRIX_TERMINAL, Levels.STAGE_MAD_MATRIX, 63, "Blue Terminal",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_TERMINAL, Levels.STAGE_MAD_MATRIX, 66, "Yellow Terminal",
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.MAD_MATRIX_TERMINAL, Levels.STAGE_MAD_MATRIX, 67, "Green Terminal",
              region=REGION_INDICIES.MAD_MATRIX_GREEN_PROGRESSION),
    SETObject(ObjectType.MAD_MATRIX_TERMINAL, Levels.STAGE_MAD_MATRIX, 68, "Red Terminal",
              region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),

    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 576, "Bomb Blue F",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 581, "Bomb Blue LL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 583, "Bomb Blue LLLFL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 580, "Bomb Blue RR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 582, "Bomb Blue RRRFR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 586, "Bomb Yellow RFFFR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 584, "Bomb Yellow RFFFFFFL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 592, "Bomb Yellow LFRL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 578, "Bomb Yellow LFLLFL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 595, "Bomb Yellow LFLLFFR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 588, "Bomb Yellow LFRRLL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 591, "Bomb Yellow LFRRLLFLL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 579, "Bomb Yellow RFLRRL^RL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 577, "Bomb YellowGreen RFL RLRLRL L",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 587, "Bomb Green LFFFL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 585, "Bomb Green LFFFFFFR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 593, "Bomb Green RFLR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 596, "Bomb Green RFRRFR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 594, "Bomb Green RFRRFFL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 589, "Bomb Green RFLLRR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 590, "Bomb Green RFLLRRFRR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 680, "Bomb Green LFRLLR^LR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 601, "Bomb Red LFLL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 599, "Bomb Red LFRRL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 597, "Bomb Red LFRRLRLRRL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 603, "Bomb Red LFLLRLFRL",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 602, "Bomb Red RFRR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 600, "Bomb Red RFLLR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 598, "Bomb Red RFLLRLRLLR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.MAD_MATRIX_BOMB, Levels.STAGE_MAD_MATRIX, 604, "Bomb Red RFRRRLRFLR",
              region=REGION_INDICIES.MAD_MATRIX_GUN),


    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 570, '0', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 571, '1', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 7, '2', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 14, '3', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 15, '4', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 52, '5', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 53, '6', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 51, '7', region=0),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 50, '8', region=0),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_MAD_MATRIX, 347, '9', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 329, '10', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 502, '11', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 503, '12', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 327, '13', region=REGION_INDICIES.MAD_MATRIX_GUN),

    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 445, '15', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 451, '16', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 449, '17', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 450, '18', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 446, '19', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_MAD_MATRIX, 344, '20', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 511, '21', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 510, '22', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.BLACK_WING, Levels.STAGE_MAD_MATRIX, 456, '23', region=REGION_INDICIES.MAD_MATRIX_GUN, is_hard=True),
    SETObject(ObjectType.BLACK_WING, Levels.STAGE_MAD_MATRIX, 455, '24', region=REGION_INDICIES.MAD_MATRIX_GUN, is_hard=True),
    SETObject(ObjectType.BLACK_WORM, Levels.STAGE_MAD_MATRIX, 117, '25',
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 119, '26',
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 120, '27',
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 151, '28',
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 152, '29',
              region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 181, '31',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 179, '32',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 182, '33',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 187, '34',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY, is_hard=True),
    SETObject(ObjectType.BLACK_HAWK, Levels.STAGE_MAD_MATRIX, 188, '35',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY, is_hard=True),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 205, '36',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 206, '37',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 203, '38',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 238, '39',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_PROGRESSION),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 306, '40', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 308, '41', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 285, '42', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 286, '43', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 287, '44', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.EGG_PAWN, Levels.STAGE_MAD_MATRIX, 289, '45',
              region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),

    SETObject(ObjectType.ENERGY_CORE_IN_WOOD_BOX, Levels.STAGE_MAD_MATRIX, 504, 'Dark Core in Box',
              region=REGION_INDICIES.MAD_MATRIX_GUN),
SETObject(ObjectType.WARP_HOLE, Levels.STAGE_MAD_MATRIX, 105, 'Other Warp Hole',
              region=REGION_INDICIES.MAD_MATRIX_GUN),

    SETObject(ObjectType.KEY, Levels.STAGE_MAD_MATRIX, 442, 'Key 1', region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.KEY, Levels.STAGE_MAD_MATRIX, 454, 'Key 2', region=REGION_INDICIES.MAD_MATRIX_YELLOW_ENTRY),
    SETObject(ObjectType.KEY, Levels.STAGE_MAD_MATRIX, 453, 'Key 3', region=REGION_INDICIES.MAD_MATRIX_GREEN_PROGRESSION),
    SETObject(ObjectType.KEY, Levels.STAGE_MAD_MATRIX, 457, 'Key 4', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.KEY, Levels.STAGE_MAD_MATRIX, 448, 'Key 5', region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),
    SETObject(ObjectType.GOAL_RING, Levels.STAGE_MAD_MATRIX, 606, 'Goal Ring',region=REGION_INDICIES.MAD_MATRIX_RED_ENTRY),


    SETObject(ObjectType.ITEM_IN_BOX, Levels.STAGE_MAD_MATRIX, 172, 'Green Entrance',
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.ITEM_IN_BOX, Levels.STAGE_MAD_MATRIX, 505, 'Near Key Door',
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.ITEM_IN_BOX, Levels.STAGE_MAD_MATRIX, 498, 'Shield Box In Red',
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.ITEM_IN_BOX, Levels.STAGE_MAD_MATRIX, 501, '5 Ring Box In Red',
              region=REGION_INDICIES.MAD_MATRIX_GUN),
    SETObject(ObjectType.ITEM_CAPSULE, Levels.STAGE_MAD_MATRIX, 204, 'Near Check 5',
              region=REGION_INDICIES.MAD_MATRIX_GREEN_ENTRY)

]