# Sonic Mission Definitions
city_escape_1        = "City Escape - 1"
city_escape_2        = "City Escape - 2"
city_escape_3        = "City Escape - 3"
city_escape_4        = "City Escape - 4"
city_escape_5        = "City Escape - 5"
city_escape_upgrade  = "City Escape - Upgrade"
metal_harbor_1       = "Metal Harbor - 1"
metal_harbor_2       = "Metal Harbor - 2"
metal_harbor_3       = "Metal Harbor - 3"
metal_harbor_4       = "Metal Harbor - 4"
metal_harbor_5       = "Metal Harbor - 5"
metal_harbor_upgrade = "Metal Harbor - Upgrade"
green_jungle_1       = "Green Jungle - 1"
green_jungle_2       = "Green Jungle - 2"
green_jungle_3       = "Green Jungle - 3"
green_jungle_4       = "Green Jungle - 4"
green_jungle_5       = "Green Jungle - 5"
green_jungle_upgrade = "Green Jungle - Upgrade"
pyramid_cave_1       = "Pyramid Cave - 1"
pyramid_cave_2       = "Pyramid Cave - 2"
pyramid_cave_3       = "Pyramid Cave - 3"
pyramid_cave_4       = "Pyramid Cave - 4"
pyramid_cave_5       = "Pyramid Cave - 5"
pyramid_cave_upgrade = "Pyramid Cave - Upgrade"
crazy_gadget_1       = "Crazy Gadget - 1"
crazy_gadget_2       = "Crazy Gadget - 2"
crazy_gadget_3       = "Crazy Gadget - 3"
crazy_gadget_4       = "Crazy Gadget - 4"
crazy_gadget_5       = "Crazy Gadget - 5"
crazy_gadget_upgrade = "Crazy Gadget - Upgrade"
final_rush_1         = "Final Rush - 1"
final_rush_2         = "Final Rush - 2"
final_rush_3         = "Final Rush - 3"
final_rush_4         = "Final Rush - 4"
final_rush_5         = "Final Rush - 5"
final_rush_upgrade   = "Final Rush - Upgrade"

# Tails Mission Definitions
prison_lane_1          = "Prison Lane - 1"
prison_lane_2          = "Prison Lane - 2"
prison_lane_3          = "Prison Lane - 3"
prison_lane_4          = "Prison Lane - 4"
prison_lane_5          = "Prison Lane - 5"
prison_lane_upgrade    = "Prison Lane - Upgrade"
mission_street_1       = "Mission Street - 1"
mission_street_2       = "Mission Street - 2"
mission_street_3       = "Mission Street - 3"
mission_street_4       = "Mission Street - 4"
mission_street_5       = "Mission Street - 5"
mission_street_upgrade = "Mission Street - Upgrade"
route_101_1            = "Route 101 - 1"
route_101_2            = "Route 101 - 2"
route_101_3            = "Route 101 - 3"
route_101_4            = "Route 101 - 4"
route_101_5            = "Route 101 - 5"
hidden_base_1          = "Hidden Base - 1"
hidden_base_2          = "Hidden Base - 2"
hidden_base_3          = "Hidden Base - 3"
hidden_base_4          = "Hidden Base - 4"
hidden_base_5          = "Hidden Base - 5"
hidden_base_upgrade    = "Hidden Base - Upgrade"
eternal_engine_1       = "Eternal Engine - 1"
eternal_engine_2       = "Eternal Engine - 2"
eternal_engine_3       = "Eternal Engine - 3"
eternal_engine_4       = "Eternal Engine - 4"
eternal_engine_5       = "Eternal Engine - 5"
eternal_engine_upgrade = "Eternal Engine - Upgrade"

# Knuckles Mission Definitions
wild_canyon_1         = "Wild Canyon - 1"
wild_canyon_2         = "Wild Canyon - 2"
wild_canyon_3         = "Wild Canyon - 3"
wild_canyon_4         = "Wild Canyon - 4"
wild_canyon_5         = "Wild Canyon - 5"
wild_canyon_upgrade   = "Wild Canyon - Upgrade"
pumpkin_hill_1        = "Pumpkin Hill - 1"
pumpkin_hill_2        = "Pumpkin Hill - 2"
pumpkin_hill_3        = "Pumpkin Hill - 3"
pumpkin_hill_4        = "Pumpkin Hill - 4"
pumpkin_hill_5        = "Pumpkin Hill - 5"
pumpkin_hill_upgrade  = "Pumpkin Hill - Upgrade"
aquatic_mine_1        = "Aquatic Mine - 1"
aquatic_mine_2        = "Aquatic Mine - 2"
aquatic_mine_3        = "Aquatic Mine - 3"
aquatic_mine_4        = "Aquatic Mine - 4"
aquatic_mine_5        = "Aquatic Mine - 5"
aquatic_mine_upgrade  = "Aquatic Mine - Upgrade"
death_chamber_1       = "Death Chamber - 1"
death_chamber_2       = "Death Chamber - 2"
death_chamber_3       = "Death Chamber - 3"
death_chamber_4       = "Death Chamber - 4"
death_chamber_5       = "Death Chamber - 5"
death_chamber_upgrade = "Death Chamber - Upgrade"
meteor_herd_1         = "Meteor Herd - 1"
meteor_herd_2         = "Meteor Herd - 2"
meteor_herd_3         = "Meteor Herd - 3"
meteor_herd_4         = "Meteor Herd - 4"
meteor_herd_5         = "Meteor Herd - 5"
meteor_herd_upgrade   = "Meteor Herd - Upgrade"


# Shadow Mission Definitions
radical_highway_1       = "Radical Highway - 1"
radical_highway_2       = "Radical Highway - 2"
radical_highway_3       = "Radical Highway - 3"
radical_highway_4       = "Radical Highway - 4"
radical_highway_5       = "Radical Highway - 5"
radical_highway_upgrade = "Radical Highway - Upgrade"
white_jungle_1          = "White Jungle - 1"
white_jungle_2          = "White Jungle - 2"
white_jungle_3          = "White Jungle - 3"
white_jungle_4          = "White Jungle - 4"
white_jungle_5          = "White Jungle - 5"
white_jungle_upgrade    = "White Jungle - Upgrade"
sky_rail_1              = "Sky Rail - 1"
sky_rail_2              = "Sky Rail - 2"
sky_rail_3              = "Sky Rail - 3"
sky_rail_4              = "Sky Rail - 4"
sky_rail_5              = "Sky Rail - 5"
sky_rail_upgrade        = "Sky Rail - Upgrade"
final_chase_1           = "Final Chase - 1"
final_chase_2           = "Final Chase - 2"
final_chase_3           = "Final Chase - 3"
final_chase_4           = "Final Chase - 4"
final_chase_5           = "Final Chase - 5"
final_chase_upgrade     = "Final Chase - Upgrade"

# Eggman Mission Definitions
iron_gate_1         = "Iron Gate - 1"
iron_gate_2         = "Iron Gate - 2"
iron_gate_3         = "Iron Gate - 3"
iron_gate_4         = "Iron Gate - 4"
iron_gate_5         = "Iron Gate - 5"
iron_gate_upgrade   = "Iron Gate - Upgrade"
sand_ocean_1        = "Sand Ocean - 1"
sand_ocean_2        = "Sand Ocean - 2"
sand_ocean_3        = "Sand Ocean - 3"
sand_ocean_4        = "Sand Ocean - 4"
sand_ocean_5        = "Sand Ocean - 5"
sand_ocean_upgrade  = "Sand Ocean - Upgrade"
lost_colony_1       = "Lost Colony - 1"
lost_colony_2       = "Lost Colony - 2"
lost_colony_3       = "Lost Colony - 3"
lost_colony_4       = "Lost Colony - 4"
lost_colony_5       = "Lost Colony - 5"
lost_colony_upgrade = "Lost Colony - Upgrade"
weapons_bed_1       = "Weapons Bed - 1"
weapons_bed_2       = "Weapons Bed - 2"
weapons_bed_3       = "Weapons Bed - 3"
weapons_bed_4       = "Weapons Bed - 4"
weapons_bed_5       = "Weapons Bed - 5"
weapons_bed_upgrade = "Weapons Bed - Upgrade"
cosmic_wall_1       = "Cosmic Wall - 1"
cosmic_wall_2       = "Cosmic Wall - 2"
cosmic_wall_3       = "Cosmic Wall - 3"
cosmic_wall_4       = "Cosmic Wall - 4"
cosmic_wall_5       = "Cosmic Wall - 5"
cosmic_wall_upgrade = "Cosmic Wall - Upgrade"

# Rouge Mission Definitions
dry_lagoon_1          = "Dry Lagoon - 1"
dry_lagoon_2          = "Dry Lagoon - 2"
dry_lagoon_3          = "Dry Lagoon - 3"
dry_lagoon_4          = "Dry Lagoon - 4"
dry_lagoon_5          = "Dry Lagoon - 5"
dry_lagoon_upgrade    = "Dry Lagoon - Upgrade"
egg_quarters_1        = "Egg Quarters - 1"
egg_quarters_2        = "Egg Quarters - 2"
egg_quarters_3        = "Egg Quarters - 3"
egg_quarters_4        = "Egg Quarters - 4"
egg_quarters_5        = "Egg Quarters - 5"
egg_quarters_upgrade  = "Egg Quarters - Upgrade"
security_hall_1       = "Security Hall - 1"
security_hall_2       = "Security Hall - 2"
security_hall_3       = "Security Hall - 3"
security_hall_4       = "Security Hall - 4"
security_hall_5       = "Security Hall - 5"
security_hall_upgrade = "Security Hall - Upgrade"
route_280_1           = "Route 280 - 1"
route_280_2           = "Route 280 - 2"
route_280_3           = "Route 280 - 3"
route_280_4           = "Route 280 - 4"
route_280_5           = "Route 280 - 5"
mad_space_1           = "Mad Space - 1"
mad_space_2           = "Mad Space - 2"
mad_space_3           = "Mad Space - 3"
mad_space_4           = "Mad Space - 4"
mad_space_5           = "Mad Space - 5"
mad_space_upgrade     = "Mad Space - Upgrade"

# Final Mission Definitions
cannon_core_1 = "Cannon Core - 1"
cannon_core_2 = "Cannon Core - 2"
cannon_core_3 = "Cannon Core - 3"
cannon_core_4 = "Cannon Core - 4"
cannon_core_5 = "Cannon Core - 5"

# Chao Garden Definitions
chao_beginner_race   = "Chao Garden - Beginner Race"
chao_jewel_race      = "Chao Garden - Jewel Race"
chao_challenge_race  = "Chao Garden - Challenge Race"
chao_hero_race       = "Chao Garden - Hero Race"
chao_dark_race       = "Chao Garden - Dark Race"
chao_beginner_karate = "Chao Garden - Beginner Karate"
chao_standard_karate = "Chao Garden - Standard Karate"
chao_expert_karate   = "Chao Garden - Expert Karate"
chao_super_karate    = "Chao Garden - Super Karate"

# Other Definitions
green_hill = "Green Hill"


# Region Definitions
menu_region  = "Menu"

city_escape_region  = "City Escape"
metal_harbor_region = "Metal Harbor"
green_jungle_region = "Green Jungle"
pyramid_cave_region = "Pyramid Cave"
crazy_gadget_region = "Crazy Gadget"
final_rush_region   = "Final Rush"

prison_lane_region    = "Prison Lane"
mission_street_region = "Mission Street"
route_101_region      = "Route 101"
hidden_base_region    = "Hidden Base"
eternal_engine_region = "Eternal Engine"

wild_canyon_region   = "Wild Canyon"
pumpkin_hill_region  = "Pumpkin Hill"
aquatic_mine_region  = "Aquatic Mine"
death_chamber_region = "Death Chamber"
meteor_herd_region   = "Meteor Herd"

radical_highway_region = "Radical Highway"
white_jungle_region    = "White Jungle"
sky_rail_region        = "Sky Rail"
final_chase_region     = "Final Chase"

iron_gate_region   = "Iron Gate"
sand_ocean_region  = "Sand Ocean"
lost_colony_region = "Lost Colony"
weapons_bed_region = "Weapons Bed"
cosmic_wall_region = "Cosmic Wall"

dry_lagoon_region    = "Dry Lagoon"
egg_quarters_region  = "Egg Quarters"
security_hall_region = "Security Hall"
route_280_region     = "Route 280"
mad_space_region     = "Mad Space"

cannon_core_region = "Cannon Core"

chao_garden_region = "Chao Garden"
