text_mapping = {
    "°": 0x00, # New lines

    "A": 0x41, "B": 0x42, "C": 0x43, "D": 0x44, "E": 0x45, "F": 0x46, "G": 0x47, "H": 0x48, "I": 0x49, "J": 0x4A,
    "K": 0x4B, "L": 0x4C, "M": 0x4D, "N": 0x4E, "O": 0x4F, "P": 0x50, "Q": 0x51, "R": 0x52, "S": 0x53, "T": 0x54,
    "U": 0x55, "V": 0x56, "W": 0x57, "X": 0x58, "Y": 0x59, "Z": 0x5A, "Ñ": 0x4E,

    "!": 0x21, ".": 0x2E, "-": 0x2D, ",": 0x2C, "?": 0x3F, " ": 0x20, ":": 0x3A, ";": 0x3B, "<": 0x3C, "=": 0x3D,
    ">": 0x3E, "/": 0x2F, '"': 0x22, "%": 0x25, "&": 0x26, "'": 0x27, "(": 0x28, ")": 0x29, "*": 0x2A, "+": 0x2B,
    "$": 0x24, "@": 0x40, "#": 0x24,

    "0": 0x30, "1": 0x31, "2": 0x32, "3": 0x33, "4": 0x34, "5": 0x35, "6": 0x36, "7": 0x37, "8": 0x38, "9": 0x39,

    "a": 0x61, "b": 0x62, "c": 0x63, "d": 0x64, "e": 0x65, "f": 0x66, "g": 0x67, "h": 0x68, "i": 0x69, "j": 0x6A,
    "k": 0x6B, "l": 0x6C, "m": 0x6D, "n": 0x6E, "o": 0x6F, "p": 0x70, "q": 0x71, "r": 0x72, "s": 0x73, "t": 0x74,
    "u": 0x75, "v": 0x76, "w": 0x77, "x": 0x78, "y": 0x79, "z": 0x7A, "ñ": 0x6E,
}

goal_texts = {
    "flying_krock_items" : [
       #"********************************"
        "",
        "",
        "",
        "",
        "Yo Ho Ho! Landlubber monkeys!",
        "Lost some animals and abilities?",
        "Maybe you'll find them somewhere",
        "alongside my airship. Don't be",
        "hasty! I'm thinking of doing",
        "some good ol' keelhauling later",
        "Har-har-har-har!",
        "",
        "                Kaptain K.Rool  ",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    "flying_krock_tokens": [
        #"********************************"
        "",
        "",
        "",
        "",
        "Yo Ho Ho! Krock got your ape?",
        "I've taken your abilities!",
        "I've taken your pets!",
        "You'll need to defeat TOKENS of my",
        "seadogs to reach my airship.",
        "Donkey Kong will walk the Plank",
        "Har-har-har-har!",
        "",
        "                Kaptain K.Rool  ",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    "lost_world": [
        #"********************************"
        "",
        "",
        "",
        "",
        "Har-har-har you pesky apes!",
        "Your abilities and pets are mine",
        "I've hidden ROCKS rocks to reach ",
        "the kore of the island. Find",
        "them or else... but I warn ya!",
        "Dead monkeys tell no tales in",
        "Crocodile Isle! Har-har-har!",
        "",
        "                Kaptain K.Rool  ",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    "kompletionist_item": [
        #"********************************"
        "",
        "",
        "",
        "",
        "Har-har-har you scurvy dogs!",
        "You'll have to beat me twice to",
        "save that son of a banana eater.",
        "Find my airship and ROCKS Lost",
        "World Rocks or my krew will",
        "blow the ape down!",
        "Har-har-har-har!",
        "",
        "                Kaptain K.Rool  ",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    "kompletionist_tokens": [
        #"********************************"
        "",
        "",
        "",
        "",
        "Avast ye monkey reading this!",
        "I've taken your abilities, pets",
        "and that banana carouser ape!",
        "You'll face this old salt twice!",
        "Reach my airship by defeating TOKENS",
        "of my scallywags and find ROCKS",
        "rocks for the kore or I'll make",
        "some ape shark bait! Har-har-har",
        "",
        "                Kaptain K.Rool  ",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
}

def string_to_bytes(input_string):
    out_array = bytearray()
    for letter in input_string:
        out_array.append(text_mapping[letter] if letter in text_mapping else text_mapping["*"])
    
    return out_array
