# WHISPERING ROCK SUMMER CAMP
# Sasha's Underground Lab (CASA) 
BehindFurnitureCard = "(CA Lab) Behind Furniture"
StaircaseLedgesCard = "(CA Lab) Staircase Ledges"
UpperLedgeFossil = "(CA Lab) Upper Ledge"

# GPC and Wilderness (CAGP) 
TopofGPCCard = "(CA GPC) Top of GPC"
UnderGPCCard = "(CA GPC) Under GPC"
MountainLionLogBridgeCard = "(CA GPC) Mountain Lion Log Bridge"
AboveEntranceLakeCard = "(CA GPC) Above Entrance to Lake"
RockWallBehindTreeCard = "(CA GPC) Rock Wall Behind Tree"
RockWallTopPirateScope = "(CA GPC) Rock Wall Top"
TreeNearFenceCard = "(CA GPC) Tree Near Fence"
TreeNearGeyserCard = "(CA GPC) Tree Near Geyser"
FenceBehindGPCCard = "(CA GPC) Fence Behind GPC"
NeartheBearCard = "(CA GPC) Near the Bear"
RockyPlatformsBehindGPCRightCard = "(CA GPC) Rocky Platforms Behind GPC Right"
RockyPlatformsBehindGPCLeftCard = "(CA GPC) Rocky Platforms Behind GPC Left"
TopofLogFlumeCard = "(CA GPC) Top of Log Flume"
RidetheLogFlumeCard = "(CA GPC) Ride the Log Flume"
BottomofLogFlumeCard = "(CA GPC) Bottom of Log Flume"
BigRockNearFordCard = "(CA GPC) Big Rock Near Ford"
RuinedCabinChallengeMarker = "(CA GPC) Inside the Ruined Cabin"
BranchSwingingCourseStartCard = "(CA GPC) Branch Swinging Course Start"
BranchSwingingCourseMidCard = "(CA GPC) Branch Swinging Course Mid"
BranchSwingingCourseEndChallengeMarker = "(CA GPC) Branch Swinging Course End"
BranchAboveSquirrelCard = "(CA GPC) Branch Above Squirrel"
CreekGrateGlassEye = "(CA GPC) Creek Grate"
SquirrelsAcornGoldenAcorn = "(CA GPC) Squirrel's Acorn"
GeyserMinersSkull = "(CA GPC) Wedged in the Geyser"
DeepAHInRiverBeforeGrate = "(CA GPC Deep AH) In River Before Grate"
DeepAHInsideGPCFenceNorth = "(CA GPC Deep AH) Inside GPC Fence North"
DeepAHNearStumpDeep = "(CA GPC Deep AH) Near Stump"
DeepAHTreeNearSquirrel = "(CA GPC Deep AH) Near Squirrel"
DeepAHRiverNearRuinedCabin = "(CA GPC Deep AH) In River Near Ruined Cabin"
DeepAHInsideGPCFenceSouthWest = "(CA GPC Deep AH) Inside GPC Fence South West"
DeepAHLargerBoulderByLake = "(CA GPC Deep AH) Larger Rock by Lake Entrance"
DeepAHGeyser = "(CA GPC Deep AH) Near Geyser"
DeepAHNearBear = "(CA GPC Deep AH) Near Bear"
DeepAHBigRockNearFord = "(CA GPC Deep AH) Big Rock Near Ford"
DeepAHOppositeRiverFromStump = "(CA GPC Deep AH) Opposite River From Stump"
DeepAHBeforeCampEntrance = "(CA GPC Deep AH) Before Entrance to Camp"
DeepAHBeforeLakeEntrance = "(CA GPC Deep AH) Before Entrance to Lake"
DeepAHSmallerBoulderByLake = "(CA GPC Deep AH) Smaller Rock by Lake Entrance"
DeepAHInsideGPCFenceSouthEast = "(CA GPC Deep AH) Inside GPC Fence South East"

# Main Campgrounds (CAMA) 
FenceNearKidsCabinsCard = "(CA Main) Fence Near Kids' Cabins"
UnderLodgeFrontStepsCard = "(CA Main) Under Lodge Front Steps"
BehindTreeNearLodgeCard = "(CA Main) Behind Tree Near Lodge"
UndertheLodgeGoldDoubloon = "(CA Main) Under the Lodge"
Loudspeaker1PlatformCard = "(CA Main) Loudspeaker 1 Platform"
UnderLodgeMetalRoofCard = "(CA Main) Under Lodge Metal Roof"
LoudspeakerTightropeWalkCard = "(CA Main) Loudspeaker Tightrope Walk"
Loudspeaker2PlatformCard = "(CA Main) Loudspeaker 2 Platform"
LodgeRoofChallengeMarker = "(CA Main) Lodge Roof"
MetalRoofOutcroppingCard = "(CA Main) Metal Roof Outcropping"
LoudspeakerAboveStumpCard = "(CA Main) Loudspeaker Above Stump"
TreePlatformLeftCard = "(CA Main) Tree Platform Left"
TreePlatformRightEagleClaw = "(CA Main) Tree Platform Right"
RockWallTopCard = "(CA Main) Rock Wall Top"
ParkingLotArchCard = "(CA Main) Parking Lot Arch"
ParkingLotSmallLogCard = "(CA Main) Parking Lot Small Log"
OleandersCarCard = "(CA Main) Oleander's Car"
ParkingLotBasketballHoopCard = "(CA Main) Parking Lot Basketball Hoop"
ParkingLotHistoryBoardCard = "(CA Main) Parking Lot History Board"
ParkingLotOuthouseCard = "(CA Main) Parking Lot Outhouse"
RockNearBenchCard = "(CA Main) Rock Near Bench"
DeepAHTrashCanNorthOfLodge = "(CA Main Deep AH) Trash Can North of Lodge"
DeepAHMainLodgeWalkway = "(CA Main Deep AH) Lodge Front Steps Corner"
DeepAHUnderStartOfLakeBridge = "(CA Main Deep AH) Under Lake Bridge"  # Under the start of the bridge to be specific
DeepAHGPCPathBeforeCougar = "(CA Main Deep AH) GPC Path Before Cougar"
DeepAHWestOfStump = "(CA Main Deep AH) West of Stump"
DeepAHReceptionEntrance = "(CA Main Deep AH) Reception Entrance"
DeepAHParkingLotLogFence = "(CA Main Deep AH) Parking Lot Log Fence"
DeepAHUnderMainLodge = "(CA Main Deep AH) Under the Lodge"
DeepAHRockWallTop = "(CA Main Deep AH) Rock Wall Top"

# Kids' Cabins (CAKC) 
GrindingontheRootsCard = "(CA Cabins) Grinding on the Roots"
UnderStairsCard = "(CA Cabins) Under Stairs"
TopotheLoudspeakerCard = "(CA Cabins) Top of Loudspeaker"
CabinRoof1Card = "(CA Cabins) Cabin Roof 1"
TrampolineAboveOuthouseCard = "(CA Cabins) Trampoline Above Outhouse"
TrampolinePlatformChallengeMarker = "(CA Cabins) Trampoline Platform"
CabinsOuthouseCard = "(CA Cabins) Cabins Outhouse"
BehindCabinCard = "(CA Cabins) Behind Cabin"
RoofofCabin2Card = "(CA Cabins) Roof of Cabin 2"
CaveEntranceCard = "(CA Cabins) Cave Entrance"
DeepCavePathCard = "(CA Cabins) Deep Cave Path"
DeepCaveLadderCard = "(CA Cabins) Deep Cave Ladder"
HighUpTightropeCard = "(CA Cabins) High-Up Tightrope"
CaveRefrigeratorTurkeySandwich = "(CA Cabins) Cave Refrigerator"

# Reception Area (CARE) 
GraveyardBearCard = "(CA Reception) Graveyard Bear"
NearBeehiveCard = "(CA Reception) Near Beehive"
MineshaftTrailerEntranceCard = "(CA Reception) Mineshaft Trailer Entrance"
TightropeStartCard = "(CA Reception) Tightrope Start"
TightropeEndCard = "(CA Reception) Tightrope End"
RocksNearTrailerCard = "(CA Reception) Rocks Near Trailer"
FireplaceTreeLowerCard = "(CA Reception) Fireplace Tree Lower"
FireplaceTreeRockCard = "(CA Reception) Fireplace Tree Rock"
SwampSkinnyPolesCard = "(CA Reception) Swamp Skinny Poles"
BigLogPlatformCard = "(CA Reception) Big Log Platform"
AboveWaterfallLeftCard = "(CA Reception) Above Waterfall Left"
AboveWaterfallRightCard = "(CA Reception) Above Waterfall Right"
BehindtheWaterfallCard = "(CA Reception) Behind the Waterfall"
WeirdTreeLeftCherryWoodPipe = "(CA Reception) Weird Tree Left"
WeirdTreeRightCard = "(CA Reception) Weird Tree Right"
LogHillTopCard = "(CA Reception) Log Hill Top"
LogHillBehindCard = "(CA Reception) Log Hill Behind"
MineshaftGrindRailCard = "(CA Reception) Mineshaft Grind Rail"
MineshaftUpperEntranceCard = "(CA Reception) Mineshaft Upper Entrance"
MineshaftAboveUpperEntranceCard = "(CA Reception) Mineshaft Above Upper Entrance"
InsideMineshaftCard = "(CA Reception) Inside Mineshaft"
MineshaftBearCard = "(CA Reception) Mineshaft Bear"
SwampBirdsNestCondorEgg = "(CA Reception) Swamp Bird's Nest"
CollapsedCaveChallengeMarker = "(CA Reception) Collapsed Cave"
FireplaceTreeTopDinosaurBone = "(CA Reception) Fireplace Tree Top"
HornetNestFertilityIdol = "(CA Reception) Hornet Nest"
DeepAHMineshaftBear = "(CA Reception Deep AH) Mineshaft Bear"
DeepAHShallowWaterEast = "(CA Reception Deep AH) Shallow Water East"
DeepAHShallowWaterWest = "(CA Reception Deep AH) Shallow Water West"
DeepAHCollapsedCave = "(CA Reception Deep AH) Collapsed Cave"
DeepAHFireplaceTree = "(CA Reception Deep AH) Fireplace Tree"
DeepAHSouthOfTrailer = "(CA Reception Deep AH) South of Trailer"
DeepAHEastOfTrailer = "(CA Reception Deep AH) East of Trailer"
DeepAHGraveyardTree = "(CA Reception Deep AH) Graveyard Tree"
DeepAHInFrontOfGraveyard = "(CA Reception Deep AH) In Front of Graveyard"
DeepAHGraveyardCorner = "(CA Reception Deep AH) Graveyard Corner"
DeepAHWestOfCampfire = "(CA Reception Deep AH) West of Campfire"
DeepAHNorthEastOfCampfire = "(CA Reception Deep AH) North East of Campfire"
DeepAHMineshaftLowerEntrance = "(CA Reception Deep AH) Mineshaft Lower Entrance"
DeepAHByStumpCARE = "(CA Reception Deep AH) By Stump"
DeepAHWaterfallRiverSplit = "(CA Reception Deep AH) Waterfall River Split"
DeepAHLogHillInFront = "(CA Reception Deep AH) Log Hill Lower"
DeepAHLogHillTop = "(CA Reception Deep AH) Log Hill Top"
DeepAHBelowTightropePlatform = "(CA Reception Deep AH) Below Tightrope Platform"

# Lake and Boathouse (CABH) 
UndertheFirstBridgeCard = "(CA Lake) Under the First Bridge"
BehindStumpCard = "(CA Lake) Behind Stump"
LeftofEntranceRockWallCard = "(CA Lake) Left of Entrance Rock Wall"
PolesonLakeCard = "(CA Lake) Poles on Lake"
BathysphereRoofCard = "(CA Lake) Bathysphere Roof"
BathysphereDockCard = "(CA Lake) Bathysphere Dock"
MetalRoofAboveFordCard = "(CA Lake) Metal Roof Above Docks"
AboveFordRopesCard = "(CA Lake) Above Ford Ropes"
AboveFordCabinPlatformCard = "(CA Lake) Above Ford Cabin Platform"
OutsideCougarCaveCard = "(CA Lake) Outside Cougar Cave"
InsideCougarCaveDiversHelmet = "(CA Lake) Inside Cougar Cave"
BulletinBoardBushesCard = "(CA Lake) Bulletin Board Bushes"
PinkTreesPlatformLeftCard = "(CA Lake) Pink Trees Platform Left"
PinkTreesPlatformRightCard = "(CA Lake) Pink Trees Platform Right"
RockWallUpperCard = "(CA Lake) Rock Wall Upper"
LakeShoreCard = "(CA Lake) Lake Shore"
TinyIslandCard = "(CA Lake) Tiny Island"
TopofBigRockChallengeMarker = "(CA Lake) Top of Big Rock"
RockWallGapPsychonautsComic1 = "(CA Lake) Rock Wall Gap"
LungfishBossComplete = "(CA Lake) Lungfish Boss Complete"
DeepAHByStumpCABH = "(CA Lake Deep AH) By Stump"
DeepAHLakeShore = "(CA Lake Deep AH) Lake Shore"
DeepAHBathysphereRock = "(CA Lake Deep AH) Bathysphere Rock"
DeepAHGPCTunnelEntrance = "(CA Lake Deep AH) GPC Tunnel Entrance"
DeepAHRockWallUpper = "(CA Lake Deep AH) Rock Wall Upper"
DeepAHBoathouseEntrance = "(CA Lake Deep AH) Boathouse Entrance"
DeepAHRightOfEntrance = "(CA Lake Deep AH) Right of Entrance"

# Main Lodge (CALI) 
MainLodgeRaftersVoodooDoll = "(CA Lodge) Main Lodge Rafters"

# Ford's Sanctuary (CAJA) 
TopofSanctuaryCard = "(CA Ford) Top of Sanctuary"
BottomofSanctuaryCard = "(CA Ford) Bottom of Sanctuary"
# for redeemeing the required brain jars
RedeemedBrainsEvent = "(CA Ford) Redeemed Required Brains"

# Rando Only Rank Checks (RANK) 
PSIRank05 = "(Rank) PSI Rank 05"
PSIRank10 = "(Rank) PSI Rank 10"
PSIRank15 = "(Rank) PSI Rank 15"
PSIRank20 = "(Rank) PSI Rank 20"
PSIRank25 = "(Rank) PSI Rank 25"
PSIRank30 = "(Rank) PSI Rank 30"
PSIRank35 = "(Rank) PSI Rank 35"
PSIRank40 = "(Rank) PSI Rank 40"
PSIRank45 = "(Rank) PSI Rank 45"
PSIRank50 = "(Rank) PSI Rank 50"
PSIRank55 = "(Rank) PSI Rank 55"
PSIRank60 = "(Rank) PSI Rank 60"
PSIRank65 = "(Rank) PSI Rank 65"
PSIRank70 = "(Rank) PSI Rank 70"
PSIRank75 = "(Rank) PSI Rank 75"
PSIRank80 = "(Rank) PSI Rank 80"
PSIRank85 = "(Rank) PSI Rank 85"
PSIRank90 = "(Rank) PSI Rank 90"
PSIRank95 = "(Rank) PSI Rank 95"
PSIRank101 = "(Rank) PSI Rank 101"

# Asylum Grounds [ASGR] 
RockWallBottom = "(AS Grounds) Rock Wall Bottom"
RockWallLadder = "(AS Grounds) Rock Wall Ladder"
OutsideFrontGate = "(AS Grounds) Outside Front Gate"
PillarAboveGate = "(AS Grounds) Pillar Above Gate"
FountainTop = "(AS Grounds) Fountain Top"
HedgeAlcove = "(AS Grounds) Hedge Alcove"
AsylumDoorsRight = "(AS Grounds) Asylum Doors Right"
AsylumDoorsLeft = "(AS Grounds) Asylum Doors Left"
CornerNearFence = "(AS Grounds) Corner Near Fence"
LedgeBeforeGloria = "(AS Grounds) Ledge Before Gloria"

# Asylum Lower Level [ASCO] 
AboveElevator = "(AS Courtyard) Above Elevator"
CrowsBasket = "(AS Courtyard) Crow's Basket"
LedgeAboveFredLeft = "(AS Courtyard) Ledge Above Fred Left"
LedgeAboveFredRight = "(AS Courtyard) Ledge Above Fred Right"
LedgeOppositeElevator = "(AS Courtyard) Ledge Opposite Elevator"
EdgarsRoom = "(AS Courtyard) Edgar's Room"
BehindElevator = "(AS Courtyard) Behind Elevator"
JunkCorner = "(AS Courtyard) Junk Corner"
AboveEdgar = "(AS Courtyard) Above Edgar"

# Asylum Upper Level [ASUP] 
BehindMattressWall = "(AS Upper) Behind Mattress Wall"
CheckeredBathroom = "(AS Upper) Checkered Bathroom"
RoomNearCheckeredBathroom = "(AS Upper) Room Near Checkered Bathroom"
ElevatorShaft = "(AS Upper) Elevator Shaft"
RoomLeftOfPipeSlide = "(AS Upper) Room Left of Pipe Slide"
FloatingInHole = "(AS Upper) Floating in Hole"
NextToHole = "(AS Upper) Next to Hole"
CrumblingOuterWallPlanks = "(AS Upper) Crumbling Outer Wall Planks"
CrumblingOuterWallPillar = "(AS Upper) Crumbling Outer Wall Pillar"
CrumblingOuterWallBelowPlatform = "(AS Upper) Crumbling Outer Wall Below Platform"
CrumblingOuterWallPlatform = "(AS Upper) Crumbling Outer Wall Platform"
RoomAboveTiltedStairs = "(AS Upper) Room Above Tilted Stairs"
AcidRoomFloor = "(AS Upper) Acid Room Floor"
AcidRoomTable = "(AS Upper) Acid Room Table"
AcidRoomWindow = "(AS Upper) Acid Room Window"
AcidRoomOverhang = "(AS Upper) Acid Room Overhang"
SmallWindowsLedge = "(AS Upper) Small Windows Ledge"
RoundWoodPlatform = "(AS Upper) Round Wood Platform"
GrateClimbBottom = "(AS Upper) Grate Climb Bottom"
GrateClimbMid = "(AS Upper) Grate Climb Mid"
SinkPlatformLeft = "(AS Upper) Sink Platform Left"
SinkPlatformRight = "(AS Upper) Sink Platform Right"
PipesBelowChairDoor = "(AS Upper) Pipes Below Chair Door"
RoomOppositeChairDoor = "(AS Upper) Room Opposite Chair Door"
PipeSlideNearChairDoor = "(AS Upper) Pipe Slide Near Chair Door"
RaftersAboveChairDoor = "(AS Upper) Rafters Above Chair Door"

# Dr. Loboto's Laboratory [ASLB] 
LabCagedCrowLeft = "(AS Lab) Lab Caged Crow Left"
LabCagedCrowRight = "(AS Lab) Lab Caged Crow Right"
NextToPokeylope = "(AS Lab) Next to Pokeylope"
LabTopRailingLeft1 = "(AS Lab) Lab Top Railing Left 1"
LabTopRailingLeft2 = "(AS Lab) Lab Top Railing Left 2"
LabTopElevator = "(AS Lab) Lab Top Elevator"
LabTopRailingRight = "(AS Lab) Lab Top Railing Right"
TeaRoom = "(AS Lab) Tea Room"
OleanderBrainTankBossEvent = "(AS Lab) Oleander Boss Defeated"

# Obstacle Course 1 [BBA1] 
JumpingTutorial1 = "(BB Area 1) Jumping Tutorial 1"
JumpingTutorial2 = "(BB Area 1) Jumping Tutorial 2"
PoleClimbingTutorialFloor = "(BB Area 1) Pole-Climbing Tutorial Floor"
BelowTheTripleTrampolines = "(BB Area 1) Below the Triple Trampolines"

# Obstacle Course 2 [BBA2] 
GiantSoldierCutOut = "(BB Area 2) Giant Soldier Cut-Out"
DodgingBullets1 = "(BB Area 2) Dodging Bullets 1"
DodgingBullets2 = "(BB Area 2) Dodging Bullets 2"
MachineGunTurret = "(BB Area 2) Machine Gun Turret"
PoleSwingingTutorial = "(BB Area 2) Pole-Swinging Tutorial"
TrapezeCobweb = "(BB Area 2) Trapeze Cobweb"
TrapezePlatform = "(BB Area 2) Trapeze Platform"
InsidePlaneWreckage = "(BB Area 2) Inside Plane Wreckage"
CobwebTrapezeCobweb = "(BB Area 2 Cobweb) Trapeze Cobweb"
CobwebTightropeTutorial = "(BB Area 2 Cobweb) Tightrope Tutorial"
CobwebGrindrailWall = "(BB Area 2 Cobweb) Grindrail Wall"

# Obstacle Course Finale [BBLT] 
EndOfObstacleCourseLeft = "(BB Finale) End of Obstacle Course Left"
EndOfObstacleCourseRight = "(BB Finale) End of Obstacle Course Right"
BasicBrainingComplete = "(BB Finale) Basic Braining Complete"
CobwebBunnyRoomDoor = "(BB Finale Cobweb) Bunny Room Door"
CobwebTunnelOfLogsEnd = "(BB Finale Cobweb) Tunnel of Logs End"

# Sasha's Shooting Gallery [SACU]
# Face 1
OnTheBed = "(SA Main) On the Bed"
OnThePillow = "(SA Main) On the Pillow"
BuildingBlocksLeft = "(SA Main) Building Blocks Left"
BuildingBlocksBelow = "(SA Main) Building Blocks Below"
BuildingBlocksRight = "(SA Main) Building Blocks Right"
TopOfBedFrame = "(SA Main) Top of Bed Frame"
CobwebBlockArchLeft = "(SA Main Cobweb) Block Arch Left"
CobwebBlockArchRight = "(SA Main Cobweb) Block Arch Right"
# Face 2
RoundPlatformsBottom = "(SA Main) Round Platforms Bottom"
RoundPlatformsNearValve = "(SA Main) Round Platforms Near Valve"
RoundPlatformsFarFromValve = "(SA Main) Round Platforms Far from Valve"
# Face 3
SideOfCubeFace3 = "(SA Main) Side of Cube Face 3"
BottomOfShoeboxLadder = "(SA Main) Bottom of Shoebox Ladder"
ShoeboxPedestal = "(SA Main) Shoebox Pedestal"
ShoeboxTowerTop = "(SA Main) Shoebox Tower Top"
CobwebBackOfShoeboxTower = "(SA Main Cobweb) Back of Shoebox Tower"
CobwebShoeboxTower = "(SA Main Cobweb) Shoebox Tower"
# Face 4
FlameTowerSteps = "(SA Main) Flame Tower Steps"
FlameTowerTop1 = "(SA Main) Flame Tower Top 1"
FlameTowerTop2 = "(SA Main) Flame Tower Top 2"
CobwebFlameTowerArch = "(SA Main) Flame Tower Arch"
# Completion
SashasShootingGalleryComplete = "(SA Main) Sasha's Shooting Gallery Complete"

# The Lounge [MIFL] 
IntroRingsTutorial = "(MI Area 1) Intro Rings Tutorial"
DancingCamperPlatform1 = "(MI Area 1) Dancing Camper Platform 1"
DemonRoom = "(MI Area 1) Demon Room"
WindyLadderBottom = "(MI Area 1) Windy Ladder Bottom"
PinballPlunger = "(MI Area 1) Pinball Plunger"
PlungerPartyLedge = "(MI Area 1) Plunger Party Ledge"
GrindrailRings = "(MI Area 1) Grindrail Rings"
CensorHallway = "(MI Area 1) Censor Hallway"
PinkBowlBottom = "(MI Area 1) Pink Bowl Bottom"
PinkBowlSmallPlatform = "(MI Area 1) Pink Bowl Small Platform"
CobwebIntroStatueCorner = "(MI Area 1 Cobweb) Intro Statue Corner"
CobwebBehindPinballLadder = "(MI Area 1 Cobweb) Behind Pinball Ladder"
CobwebGrindrailRings = "(MI Area 1 Cobweb) Grindrail Rings"

# The Party [MILL] 
BubblyFanBottom = "(MI Finale) Bubbly Fan Bottom"
BubblyFanPlatform = "(MI Finale) Bubbly Fan Platform"
BubblyFanTop = "(MI Finale) Bubbly Fan Top"
MillasPartyRoom = "(MI Finale) Milla's Party Room"
MillasDancePartyComplete = "(MI Finale) Milla's Dance Party Complete"
CobwebFanRoomEntrance = "(MI Finale Cobweb) Fan Room Entrance"
CobwebPartyRoomFloor = "(MI Finale Cobweb) Party Room Floor"

# The Nightmare Woods [NIMP] 
OutsideCaravan = "(BT Main) Outside Caravan"
BehindTheEgg = "(BT Main) Behind the Egg"
ShadowMonsterPath = "(BT Main) Shadow Monster Path"
ShadowMonsterBlueMushrooms = "(BT Main) Shadow Monster Blue Mushrooms"
LedgeBehindShadowMonster = "(BT Main) Ledge Behind Shadow Monster"
BelowTheSteepLedge = "(BT Main) Below the Steep Ledge"
ForestPathBlueMushrooms = "(BT Main) Forest Path Blue Mushrooms"
ForestBlueLedge = "(BT Main) Forest Blue Ledge"
ForestHighPlatform = "(BT Main) Forest High Platform"
ForestPathThorns = "(BT Main) Forest Path Thorns"
BehindThornTowerLeft = "(BT Main) Behind Thorn Tower Left"
BehindThornTowerMid = "(BT Main) Behind Thorn Tower Mid"
BehindThornTowerRight = "(BT Main) Behind Thorn Tower Right"
CobwebShadowMonsterMeat = "(BT Main Cobweb) Shadow Monster Meat"
CobwebForestHighPlatform = "(BT Main Cobweb) Forest High Platform"
CobwebForestPathThorns = "(BT Main Cobweb) Forest Path Thorns"
CobwebBathtubDrain = "(BT Main Cobweb) Bathtub Drain"
CobwebThornTowerRight = "(BT Main Cobweb) Thorn Tower Right"
BrainTumblerExperimentComplete = "(BT Boss) Brain Tumbler Experiment Complete"

# Lungfishopolis City [LOMA] 
SkyscraperStart = "(LO Main) Skyscraper Start"
CornerNearJail = "(LO Main) Corner Near First Jail"
SkyscraperBeforeDam = "(LO Main) Skyscraper before Dam"
BehindLasersLeft1 = "(LO Main) Behind Lasers Left 1"
BehindLasersLeft2 = "(LO Main) Behind Lasers Left 2"
BehindLasersRight = "(LO Main) Behind Lasers Right"
BlimpHop = "(LO Main) Blimp Hop"
EndOfDam = "(LO Main) End of Dam"
EndOfDamPlatform = "(LO Main) End of Dam Platform"
SkyscraperAfterDam = "(LO Main) Skyscraper after Dam"
NearBattleships = "(LO Main) Near Battleships"
OnTheBridge = "(LO Main) On the Bridge"
GroundAfterBridge = "(LO Main) Ground after Bridge"
SkyscraperAfterBridge = "(LO Main) Skyscraper after Bridge"
TunnelSuitcaseTag = "(LO Main) Train Tunnel"
FinalSkyscrapersLeft = "(LO Main) Final Skyscrapers Left"
FinalSkyscrapersRight = "(LO Main) Final Skyscrapers Right"
CobwebSkyscraperBeforeDam = "(LO Main Cobweb) Skyscraper Before Dam"
CobwebSkyscrapersBeforeTunnel = "(LO Main Cobweb) Skyscrapers Before Tunnel"
CobwebBehindLasers = "(LO Main Cobweb) Behind Lasers"
CobwebEndOfDam = "(LO Main Cobweb) End of Dam"
CobwebGroundAfterBridge = "(LO Main Cobweb) Ground after Bridge"

# Kochamara Arena [LOCB] 
KochamaraIntroLeft = "(LO Boss) Kochamara Intro Left"
KochamaraIntroRight = "(LO Boss) Kochamara Intro Right"
LungfishopolisComplete = "(LO Boss) Lungfishopolis Complete"

# The Neighborhood 1 [MMI1] 
BoydsFridgeClv = "(MM Neighborhood) Boyd's Fridge"
FirstHouseDufflebagTag = "(MM Neighborhood) Inside First House"
SecondHouseRollingPin = "(MM Neighborhood) Inside Second House"
CarTrunk1StopSign = "(MM Neighborhood) Car Trunk 1"
RoofAfterRoadCrewPurseTag = "(MM Neighborhood) Roof after Road Crew"
CarTrunk2HedgeTrimmers = "(MM Neighborhood) Car Trunk 2"
CarHouseBackyardSteamertrunkTag = "(MM Neighborhood) Car House Backyard"
InsideWebbedGarageHatbox = "(MM Neighborhood) Inside Webbed Garage"
GraveyardPatioVault = "(MM Neighborhood) Graveyard Patio"
GraveyardBehindTreeOneUp = "(MM Neighborhood) Graveyard Behind Tree"
BehindGraveyardDufflebag = "(MM Neighborhood) Behind Graveyard"
HedgeMazeFlowers = "(MM Neighborhood) Hedge Maze"
CarTrunk3WateringCan = "(MM Neighborhood) Car Trunk 3"
PostOfficeRoofOneUp = "(MM Neighborhood) Post Office Roof"
PostOfficeLobbySuitcase = "(MM Neighborhood) Post Office Lobby"
PostOfficeBasementPlunger = "(MM Neighborhood) Post Office Basement"
LandscapersHouseBackyardSuitcaseTag = "(MM Neighborhood) Landscapers House Backyard"
LandscapersHouseTablePurse = "(MM Neighborhood) Landscapers House Table"
LandscapersHouseKitchenAmmoUp = "(MM Neighborhood) Landscapers House Kitchen"
PowerlineIslandSandboxHatboxTag = "(MM Neighborhood) Powerline Island Sandbox"
PowerlineIslandLeftMemoryVault = "(MM Neighborhood) Powerline Island Left"
PowerlineIslandRightMaxLives = "(MM Neighborhood) Powerline Island Right"
CobwebThirdHouse = "(MM Neighborhood Cobweb) Third House"
CobwebPostOfficeLobby = "(MM Neighborhood Cobweb) Post Office Lobby"
CobwebRightHouseBeforePostOffice = "(MM Neighborhood Cobweb) Right House before Post Office"
CobwebWebbedGarage = "(MM Neighborhood Cobweb) Webbed Garage"

# The Neighborhood 2 [MMI2] 
BehindBookDepositorySteamerTrunk = "(MM Depository) Behind Book Depository"
MilkmanComplete = "(MM Depository) Milkman Complete"
CobwebBookDepository = "(MM Depository Cobweb) Book Depository"

# The Stage [THMS] 
NearTheCriticPurse = "(TH Stage) Near the Critic"
InTheAudienceAmmoUp = "(TH Stage) In the Audience"
BelowTheSpotlightSteamertrunkTag = "(TH Stage) Below the Spotlight"
BehindStagePurseTag = "(TH Stage) Behind Stage"
BehindStageCobwebSuitcase = "(TH Stage) Behind Stage Cobweb"
StorageRoomFloorVault = "(TH Stage) Storage Room Floor"
StorageRoomLeftSteamertrunk = "(TH Stage) Storage Room Left"
StorageRoomRightLowerSuitcaseTag = "(TH Stage) Storage Room Right Lower"
StorageRoomRightUpperCandle1 = "(TH Stage) Storage Room Right Upper"
BonitasRoom = "(TH Stage) Bonita's Room"
CobwebBackstageCorridor = "(TH Stage Cobweb) Backstage Corridor"
CobwebBelowTeleporter = "(TH Stage Cobweb) Below Teleporter"
CobwebStorageRoomLeft = "(TH Stage Cobweb) Storage Room Left"
CobwebInTheAudience = "(TH Stage Cobweb) In the Audience"
CobwebBelowTheCritic = "(TH Stage Cobweb) Below the Critic"
CobwebBehindStage = "(TH Stage Cobweb) Behind Stage"
CobwebStorageRoomRight = "(TH Stage Cobweb) Storage Room Right"

# The Catwalks [THCW] 
DoghouseSlicersDufflebagTag = "(TH Catwalks) Doghouse Slicers"
BigPlatform1Hatbox = "(TH Catwalks) Big Platform 1"
BigPlatform2Vault = "(TH Catwalks) Big Platform 2"
BigPlatform3OneUp = "(TH Catwalks) Big Platform 3"
BigPlatformAboveHatboxTag = "(TH Catwalks) Big Platform Above"
NextToOatmealDufflebag = "(TH Catwalks) Next to Oatmeal"
CandleBasketCandle2 = "(TH Catwalks) Candle Basket"
CurtainSlideConfusionAmmoUp = "(TH Catwalks) Curtain Slide"
GloriasTheaterComplete = "(TH Catwalks) Gloria's Theater Complete"

# WATERLOO WORLD [WWMA] 
FredsRoomHatboxTag = "(WW Main) Fred's Room"
TheFireplacePricelessCoin = "(WW Main) The Fireplace"
GameBoardSuitcaseTag = "(WW Main) Game Board"
CarpentersRoofVault = "(WW Main) Carpenter's Roof"
TightropeRoomDufflebag = "(WW Main) Tightrope Room"
OutsideVillager1HouseOneUp = "(WW Main) Outside Villager 1 House"
SmallArchTopMaxLives = "(WW Main) Small Arch Top"
SmallArchBelowPurseTag = "(WW Main) Small Arch Below"
TopOfVillager2sHouseDufflebagTag = "(WW Main) Top of Villager 2's House"
TopOfVillager3sHouseAmmoUp = "(WW Main) Top of Villager 3's House"
TopOfKnightsHouseConfusionAmmoUp = "(WW Main) Top of Knight's House"
CastleTowerOneUp = "(WW Main) Castle Tower"
CastleInsideVault = "(WW Main) Castle Inside"
CastleWallSteamertrunk = "(WW Main) Castle Wall"
UnderTheGuillotineSuitcase = "(WW Main) Under the Guillotine"
FredsHouseBasementHatbox = "(WW Main) Fred's House Basement"
BlacksmithsLeftBuildingPurse = "(WW Main) Blacksmith's Left Building"
BlacksmithsRightBuildingSteamertrunkTag = "(WW Main) Blacksmith's Right Building"
BlacksmithsHaybaleTheMusket = "(WW Main) Blacksmith's Haybale"
HelpTheCarpenter = "(WW Main) Help the Carpenter"
HelpVillager1 = "(WW Main) Help Villager 1"
HelpTheKnight = "(WW Main) Help the Knight"
HelpVillager2 = "(WW Main) Help Villager 2"
HelpVillager3 = "(WW Main) Help Villager 3"
WaterlooWorldComplete = "(WW Main) Waterloo World Complete"
CobwebBeneathSmallArch = "(WW Main Cobweb) Beneath Small Arch"
CobwebBlacksmithsRightBuildingWindow = "(WW Main Cobweb) Blacksmith's Right Building Window"
CobwebBlacksmithsLeftBuilding = "(WW Main Cobweb) Blacksmith's Left Building"
CobwebBlacksmithsRightBuildingRoof = "(WW Main Cobweb) Blacksmith's Right Building Roof"
CobwebCarpentersHouse = "(WW Main Cobweb) Carpenter's House"
CobwebFredsHouseBasement = "(WW Main Cobweb) Fred's House Basement"
CobwebUnderTheGuillotine = "(WW Main Cobweb) Under the Guillotine"

# Running Against the Bull [BVRB] 
ClubStreetLadySteamertrunk = "(BV Streets) Club Street Lady"
ClubStreetMetalBalconyDufflebagTag = "(BV Streets) Club Street Metal Balcony"
HeartStreetHIGHBalconyAmmoUp = "(BV Streets) Heart Street HIGH Balcony"
AlleywaysLedgeHatboxTag = "(BV Streets) Alleyways Ledge"
SewersMainVault = "(BV Streets) Sewers Main"
ClubStreetGatedSteamerTrunkTag = "(BV Streets) Club Street Gated"
BurnTheLogsDufflebag = "(BV Streets) Burn the Logs"
TheGardenVault = "(BV Streets) The Garden"
NearDiegosHouseMaxLives = "(BV Streets) Near Diego's House"
DiegosBedSuitcaseTag = "(BV Streets) Diego's Bed"
DiegosRoomHatbox = "(BV Streets) Diego's Room"
DiegosHouseGrindrailSuitcase = "(BV Streets) Diego's House Grindrail"
GrindrailBalconyConfusionAmmoUp = "(BV Streets) Grindrail Balcony"
CobwebDiegosHouseGrindrail = "(BV Streets Cobweb) Diego's House Grindrail"
CobwebDiegosHouse = "(BV Streets Cobweb) Diego's House"
CobwebSewerShowerTunnel = "(BV Streets Cobweb) Sewer Shower Tunnel"
CobwebAboveQueenOfHearts = "(BV Streets Cobweb) Above Queen of Hearts"
CobwebSewerBeforeGate = "(BV Streets Cobweb) Sewer Before Gate"
CobwebDiegosHouseFireplace = "(BV Streets Cobweb) Diego's House Fireplace"
CobwebNearDiegosHouse = "(BV Streets Cobweb) Near Diego's House"

# Edgar's Sanctuary [BVES] 
SanctuaryBalconyPurseTag = "(BV Edgar) Sanctuary Balcony"
SanctuaryGroundPurse = "(BV Edgar) Sanctuary Ground"
TigerWrestler = "(BV Edgar) Tiger Wrestler"
DragonWrestler = "(BV Edgar) Dragon Wrestler"
EagleWrestler = "(BV Edgar) Eagle Wrestler"
CobraWrestler = "(BV Edgar) Cobra Wrestler"
BlackVelvetopiaComplete = "(BV Edgar) Black Velvetopia Complete"

# Meat Circus Main [MCTC] 
EntranceAwningSteamertrunkTag = "(MC Main) Entrance Awning"
CrumblingPathSteamertrunk = "(MC Main) Crumbling Path"
CrumblingPathEndRightHatboxTag = "(MC Main) Crumbling Path End Right"
CrumblingPathEndLeftConfusionAmmoUp = "(MC Main) Crumbling Path End Left"
OllieEscortFloorSuitcaseTag = "(MC Main) Ollie Escort Floor"
OllieEscortMiddleHatbox = "(MC Main) Ollie Escort Middle"
OllieEscortTopLeftVault = "(MC Main) Ollie Escort Top Left"
OllieEscortTopRightPurseTag = "(MC Main) Ollie Escort Top Right"
TunnelOfLoveStartPurse = "(MC Main) Tunnel of Love Start"
TunnelOfLoveCornerSuitcase = "(MC Main) Tunnel of Love Corner"
TunnelOfLoveRailDufflebagTag = "(MC Main) Tunnel of Love Rail"
NextToTheFatLadyDufflebag = "(MC Main) Next to the Final Door"
CobwebTunnelOfLoveOllieEscortExit = "(MC Main Cobweb) Tunnel of Love Ollie Escort Exit"
CobwebEntranceHall1 = "(MC Main Cobweb) Entrance Hall 1"
CobwebEntranceHall2 = "(MC Main Cobweb) Entrance Hall 2"
MeatCircusFinalBossEvent = "(MC Boss) Final Boss Defeated"

# Ford's Shop, only a location if Cobweb Duster vanilla
ShopCobwebDuster = "(CA Lodge) Ford's Shop Cobweb Duster"
