<CampaignScroll>
    scroll_type: ["content", "bars"]
    bar_width: dp(12)
    effect_cls: "ScrollEffect"

<MultiCampaignLayout>
    cols: 1
    size_hint_y: None

<CampaignLayout>:
    cols: 1

<MissionLayout>:
    rows: 1

<MissionCategory>:
    cols: 1
    padding: [10,5,10,5]
    spacing: [0,5]

<MissionButton>:
    text_size: self.size
    markup: True
    halign: 'center'
    valign: 'middle'
    padding_x: 5
    markup: True
    outline_width: 1
