FORBIDDEN = [
    # MAX_ARROWS_UPGRADE, MAX_BOMBS_UPGRADE, MAX_POWDER_UPGRADE
    # arrows and bombs will be matched to arrow and bomb respectively through pluralization
    "ARROWS",
    "BOMBS",
    "MAX",
    "UPGRADE",

    "TAIL",     # TAIL_KEY
    "ANGLER",   # ANGLER_KEY
    "FACE",     # FACE_KEY
    "BIRD",     # BIRD_KEY
    "SLIME",    # SLIME_KEY
    "NIGHTMARE",# NIGHTMARE_KEY

    "BLUE",     # BLUE_TUNIC
    "RED",      # RED_TUNIC
    
    "TRADING",  # TRADING_ITEM_*
    "ITEM",     # TRADING_ITEM_*
    
    "BAD",      # BAD_HEART_CONTAINER
    "GOLD",     # GOLD_LEAF
    "MAGIC",    # MAGIC_POWDER, MAGIC_ROD
    "MESSAGE",  # MESSAGE (Master Stalfos' Message)
    "PEGASUS",  # PEGASUS_BOOTS
    "PIECE",    # HEART_PIECE, PIECE_OF_POWER
    "POWER",    # POWER_BRACELET, PIECE_OF_POWER
    "SINGLE",   # SINGLE_ARROW
    "STONE",    # STONE_BEAK
]

SYNONYMS = {
    'ANKLET': 'POWER_BRACELET',
    'ARMLET': 'POWER_BRACELET',
    'BAND': 'POWER_BRACELET',
    'BANGLE': 'POWER_BRACELET',
    'BRACER': 'POWER_BRACELET',
    'CARRY': 'POWER_BRACELET',
    'CIRCLET': 'POWER_BRACELET',
    'CROISSANT': 'POWER_BRACELET',
    'GAUNTLET': 'POWER_BRACELET',
    'GLOVE': 'POWER_BRACELET',
    'RING': 'POWER_BRACELET',
    'STRENGTH': 'POWER_BRACELET',
    'AEGIS': 'SHIELD',
    'AEGISSHIELD': 'SHIELD', # Final Fantasy 1
    'BUCKLER': 'SHIELD',
    'SHLD': 'SHIELD',
    'BALLISTA': 'BOW',
    'GRAPPLE': 'HOOKSHOT',
    'GRAPPLING': 'HOOKSHOT',
    'ROPE': 'HOOKSHOT',
    'BEAM': 'MAGIC_ROD',
    'CANE': 'MAGIC_ROD',
    'STAFF': 'MAGIC_ROD',
    'WAND': 'MAGIC_ROD',
    'BOOT': 'PEGASUS_BOOTS',
    'GREAVES': 'PEGASUS_BOOTS',
    'RUN': 'PEGASUS_BOOTS',
    'SHOE': 'PEGASUS_BOOTS',
    'SPEED': 'PEGASUS_BOOTS',
    'FLUTE': 'OCARINA',
    'RECORDER': 'OCARINA',
    'JUMP': 'FEATHER',
    'PLUME': 'FEATHER',
    'WING': 'FEATHER',
    'DIG': 'SHOVEL',
    'BAG': 'MAGIC_POWDER',
    'CASE': 'MAGIC_POWDER',
    'DUST': 'MAGIC_POWDER',
    'POUCH': 'MAGIC_POWDER',
    'SACK': 'MAGIC_POWDER',
    'BOMBCHU': 'BOMB',
    'TNT': 'BOMB',
    'BLADE': 'SWORD',
    'CUT': 'SWORD',
    'DAGGER': 'SWORD',
    'DIRK': 'SWORD',
    'EDGE': 'SWORD',
    'EPEE': 'SWORD',
    'EXCALIBUR': 'SWORD',
    'FALCHION': 'SWORD',
    'KATANA': 'SWORD',
    'KNIFE': 'SWORD',
    'MACHETE': 'SWORD',
    'MASAMUNE': 'SWORD',
    'MURASAME': 'SWORD',
    'SABER': 'SWORD',
    'SABRE': 'SWORD',
    'SCIMITAR': 'SWORD',
    'SLASH': 'SWORD',
    'VORPAL': 'SWORD', # Final Fantasy 1
    'XCALBER': 'SWORD', # Final Fantasy 1
    'FLIPPER': 'FLIPPERS',
    'SWIM': 'FLIPPERS',
    'BOTTLE': 'MEDICINE',
    'FLASK': 'MEDICINE',
    'LEMONADE': 'MEDICINE',
    'OXYALE': 'MEDICINE', # Final Fantasy 1
    'POTION': 'MEDICINE',
    'TEA': 'MEDICINE',
    'HERB': 'GOLD_LEAF',
    'CARAPACE': 'SEASHELL',
    'CONCH': 'SEASHELL',
    'SHELL': 'SEASHELL',
    'BOOMER': 'BOOMERANG',
    'BEAST': 'BOWWOW',
    'PET': 'BOWWOW',
    'MISSILE': 'SINGLE_ARROW',
    'QUIVER': 'SINGLE_ARROW',
    'BIRD': 'ROOSTER',
    'CHICKEN': 'ROOSTER',
    'COJIRO': 'ROOSTER', # Ocarina of Time
    'CUCCO': 'ROOSTER',
    'FLY': 'ROOSTER',
    'GRIFFIN': 'ROOSTER',
    'GRYPHON': 'ROOSTER',
    'ARMOR': 'BLUE_TUNIC',
    'DRAGONARMOR': 'BLUE_TUNIC', # Final Fantasy 1
    'MAIL': 'BLUE_TUNIC',
    'SUIT': 'BLUE_TUNIC',
    'TANK': 'HEART_CONTAINER',
    'FUNGAL': 'TOADSTOOL',
    'FUNGUS': 'TOADSTOOL',
    'MUSHROOM': 'TOADSTOOL',
    'SHROOM': 'TOADSTOOL',
    'NUT': 'GUARDIAN_ACORN',
    'SEED': 'GUARDIAN_ACORN',
    'KEY': 'KEY', # Without this, keys show up as nightmare keys
    'FOSSIL': 'STONE_BEAK',
    'RELIC': 'STONE_BEAK',
    'BOLERO': 'SONG1',
    'LULLABY': 'SONG1',
    'MELODY': 'SONG1',
    'MINUET': 'SONG1',
    'NOCTURNE': 'SONG1',
    'PRELUDE': 'SONG1',
    'REQUIEM': 'SONG1',
    'SERENADE': 'SONG1',
    'SONG': 'SONG1',
    'FISH': 'SONG2',
    'SURF': 'SONG2',
    'FROG': 'SONG3',
    'CELLO': 'INSTRUMENT1',
    'GUITAR': 'INSTRUMENT1',
    'LUTE': 'INSTRUMENT1',
    'VIOLIN': 'INSTRUMENT1',
    'HORN': 'INSTRUMENT2',
    'BELL': 'INSTRUMENT3',
    'CHIME': 'INSTRUMENT3',
    'HARP': 'INSTRUMENT4',
    'MARIMBA': 'INSTRUMENT5',
    'XYLOPHONE': 'INSTRUMENT5',
    'TRIANGLE': 'INSTRUMENT6',
    'KEYBOARD': 'INSTRUMENT7',
    'ORGAN': 'INSTRUMENT7',
    'PIANO': 'INSTRUMENT7',
    'DRUM': 'INSTRUMENT8',
    'DINOSAUR': 'TRADING_ITEM_YOSHI_DOLL',
    'DRAGON': 'TRADING_ITEM_YOSHI_DOLL',
    'TOY': 'TRADING_ITEM_YOSHI_DOLL',
    'HAIRBAND': 'TRADING_ITEM_RIBBON',
    'HAIRPIN': 'TRADING_ITEM_RIBBON',
    'CAN': 'TRADING_ITEM_DOG_FOOD',
    'BANANA': 'TRADING_ITEM_BANANAS',
    'BRANCH': 'TRADING_ITEM_STICK',
    'TWIG': 'TRADING_ITEM_STICK',
    'BEEHIVE': 'TRADING_ITEM_HONEYCOMB',
    'HIVE': 'TRADING_ITEM_HONEYCOMB',
    'HONEY': 'TRADING_ITEM_HONEYCOMB',
    'FRUIT': 'TRADING_ITEM_PINEAPPLE',
    'FLOWER': 'TRADING_ITEM_HIBISCUS',
    'PETAL': 'TRADING_ITEM_HIBISCUS',
    'CARD': 'TRADING_ITEM_LETTER',
    'MESSAGE': 'TRADING_ITEM_LETTER',
    'SWEEP': 'TRADING_ITEM_BROOM',
    'CLAW': 'TRADING_ITEM_FISHING_HOOK',
    'AMULET': 'TRADING_ITEM_NECKLACE',
    'BEADS': 'TRADING_ITEM_NECKLACE',
    'PEARLS': 'TRADING_ITEM_NECKLACE',
    'PENDANT': 'TRADING_ITEM_NECKLACE',
    'ROSARY': 'TRADING_ITEM_NECKLACE',
    'FINDER': 'TRADING_ITEM_MAGNIFYING_GLASS',
    'LENS': 'TRADING_ITEM_MAGNIFYING_GLASS',
    'MIRROR': 'TRADING_ITEM_MAGNIFYING_GLASS',
    'SCOPE': 'TRADING_ITEM_MAGNIFYING_GLASS',
    'CHAOS': 'PIECE_OF_POWER', # Chaos emerald
    'POWER': 'PIECE_OF_POWER',
    'STAR': 'PIECE_OF_POWER',
    'TRIFORCE': 'PIECE_OF_POWER',

    #SMZ3
    'BIGKEY': 'NIGHTMARE_KEY',
    'SANCTUARYHEARTCONTAINER': 'HEART_CONTAINER',
    'BOSSHEARTCONTAINER': 'HEART_CONTAINER',
    'HEARTCONTAINER': 'HEART_CONTAINER',
    'ENERGYTANK': 'HEART_CONTAINER',
    'BLUEBOOMERANG': 'BOOMERANG',
    'MAGICMIRROR': 'TRADING_ITEM_MAGNIFYING_GLASS',

    # TODO: Also use AP item name
}

PHRASES = {
    'BIG KEY': 'NIGHTMARE_KEY',
    'BOSS KEY': 'NIGHTMARE_KEY',
    'HEART PIECE': 'HEART_PIECE',
    'PIECE OF HEART': 'HEART_PIECE',
}