intro_stage_boss = "Maoh the Giant Defeated"
intro_stage_mini_boss = "Mac Defeated"
intro_stage_hp_1 = "Hunter Base Stage - HP Pickup 1 (Right of first ladder)"
intro_stage_hp_2 = "Hunter Base Stage - HP Pickup 2 (Bottom of falling spike balls section)"

blizzard_buffalo_boss = "Blizzard Buffalo Defeated"
blizzard_buffalo_clear = "Blizzard Buffalo Stage Clear"
blizzard_buffalo_heart_tank = "Blizzard Buffalo Stage - Heart Tank"
blizzard_buffalo_sub_tank = "Blizzard Buffalo Stage - Sub Tank"
blizzard_buffalo_legs = "Blizzard Buffalo Stage - Legs Capsule"
blizzard_buffalo_hp_1 = "Blizzard Buffalo Stage - HP Pickup 1 (Roof after first ladder)"
blizzard_buffalo_hp_2 = "Blizzard Buffalo Stage - HP Pickup 2 (Before Bit & Byte room)"
blizzard_buffalo_hp_3 = "Blizzard Buffalo Stage - HP Pickup 3 (Top of slope in dark room)"
blizzard_buffalo_hp_4 = "Blizzard Buffalo Stage - HP Pickup 4 (After dark room)"
blizzard_buffalo_hp_5 = "Blizzard Buffalo Stage - HP Pickup 5 (Before boss room)"

toxic_seahorse_boss = "Toxic Seahorse Defeated"
toxic_seahorse_clear = "Toxic Seahorse Stage Clear"
toxic_seahorse_mini_boss = "Hotareeca Defeated"
toxic_seahorse_heart_tank = "Toxic Seahorse Stage - Heart Tank"
toxic_seahorse_kangaroo_ride = "Toxic Seahorse Stage - Kangaroo Ride Armor"
toxic_seahorse_leg = "Toxic Seahorse Stage - Leg Chip Capsule"
toxic_seahorse_hp_1 = "Toxic Seahorse Stage - HP Pickup 1 (Bottom of falling water section)"
toxic_seahorse_hp_2 = "Toxic Seahorse Stage - HP Pickup 2 (In moving water)"
toxic_seahorse_hp_3 = "Toxic Seahorse Stage - HP Pickup 3 (After Hotareeca room)"

tunnel_rhino_boss = "Tunnel Rhino Defeated"
tunnel_rhino_clear = "Tunnel Rhino Stage Clear"
tunnel_rhino_mini_boss = "Hell Crusher Defeated"
tunnel_rhino_heart_tank = "Tunnel Rhino Stage - Heart Tank"
tunnel_rhino_sub_tank = "Tunnel Rhino Stage - Sub Tank"
tunnel_rhino_helmet = "Tunnel Rhino Stage - Helmet Capsule"
tunnel_rhino_energy_1 = "Tunnel Rhino Stage - Weapon Energy Pickup (Before Bit & Byte room)"
tunnel_rhino_hp_1 = "Tunnel Rhino Stage - HP Pickup (Before falling rocks section)"

volt_catfish_boss = "Volt Catfish Defeated"
volt_catfish_clear = "Volt Catfish Stage Clear"
volt_catfish_heart_tank = "Volt Catfish Stage - Heart Tank"
volt_catfish_sub_tank = "Volt Catfish Stage - Sub Tank"
volt_catfish_body = "Volt Catfish Stage - Body Capsule"
volt_catfish_energy_1 = "Volt Catfish Stage - Weapon Energy Pickup 1 (Left of Sub Tank)"
volt_catfish_energy_2 = "Volt Catfish Stage - Weapon Energy Pickup 2 (Right of Sub Tank)"
volt_catfish_energy_3 = "Volt Catfish Stage - Weapon Energy Pickup 3 (In power plant section)"
volt_catfish_hp_1 = "Volt Catfish Stage - HP Pickup 2 (In first elevator)"
volt_catfish_hp_2 = "Volt Catfish Stage - HP Pickup 1 (In first elevator)"
volt_catfish_hp_3 = "Volt Catfish Stage - HP Pickup 3 (Right of Sub Tank)"
volt_catfish_hp_4 = "Volt Catfish Stage - HP Pickup 4 (Left of Sub Tank)"
volt_catfish_hp_5 = "Volt Catfish Stage - HP Pickup 5 (In power plant section)"

crush_crawfish_boss = "Crush Crawfish Defeated"
crush_crawfish_clear = "Crush Crawfish Stage Clear"
crush_crawfish_heart_tank = "Crush Crawfish Stage - Heart Tank"
crush_crawfish_hawk_ride = "Crush Crawfish Stage - Hawk Ride Armor"
crush_crawfish_body = "Crush Crawfish Stage - Body Chip Capsule"
crush_crawfish_1up_1 = "Crush Crawfish Stage - 1up Pickup 1 (Top right of conveyor belts section)"
crush_crawfish_1up_2 = "Crush Crawfish Stage - 1up Pickup 2 (Top right of conveyor belts section)"
crush_crawfish_energy_1 = "Crush Crawfish Stage - Weapon Energy Pickup (Top left of conveyor belts section)"
crush_crawfish_hp_1 = "Crush Crawfish Stage - HP Pickup 1 (Top of third crane)"
crush_crawfish_hp_2 = "Crush Crawfish Stage - HP Pickup 2 (Below third crane)"
crush_crawfish_hp_3 = "Crush Crawfish Stage - HP Pickup 3 (After Bit & Byte room)"
crush_crawfish_hp_4 = "Crush Crawfish Stage - HP Pickup 4 (Before ship)"
crush_crawfish_hp_5 = "Crush Crawfish Stage - HP Pickup 5 (Bottom left of conveyor belts section)"
crush_crawfish_hp_6 = "Crush Crawfish Stage - HP Pickup 6 (Bottom left of conveyor belts section)"

neon_tiger_boss = "Neon Tiger Defeated"
neon_tiger_clear = "Neon Tiger Stage Clear"
neon_tiger_mini_boss = "Worm Seeker-R Defeated"
neon_tiger_heart_tank = "Neon Tiger Stage - Heart Tank"
neon_tiger_sub_tank = "Neon Tiger Stage - Sub Tank"
neon_tiger_arms = "Neon Tiger Stage - Arms Capsule"
neon_tiger_hp_1 = "Neon Tiger Stage - HP Pickup 1 (Below first ladder)"
neon_tiger_hp_2 = "Neon Tiger Stage - HP Pickup 2 (Below Sub Tank)"
neon_tiger_hp_3 = "Neon Tiger Stage - HP Pickup 3 (Before Worm Seeker-R room)"

gravity_beetle_boss = "Gravity Beetle Defeated"
gravity_beetle_clear = "Gravity Beetle Stage Clear"
gravity_beetle_heart_tank = "Gravity Beetle Stage - Heart Tank"
gravity_beetle_frog_ride = "Gravity Beetle Stage - Frog Ride Armor"
gravity_beetle_arms = "Gravity Beetle Stage - Arms Chip Capsule"
gravity_beetle_1up = "Gravity Beetle Stage - 1up Pickup (In elevator)"
gravity_beetle_energy_1 = "Gravity Beetle Stage - Weapon Energy Pickup 1 (In elevator)"
gravity_beetle_energy_2 = "Gravity Beetle Stage - Weapon Energy Pickup 2 (In elevator)"
gravity_beetle_hp_1 = "Gravity Beetle Stage - HP Pickup 1 (In cranes and boxes room)"
gravity_beetle_hp_2 = "Gravity Beetle Stage - HP Pickup 2 (Before elevator)"
gravity_beetle_hp_3 = "Gravity Beetle Stage - HP Pickup 3 (In elevator)"
gravity_beetle_hp_4 = "Gravity Beetle Stage - HP Pickup 4 (In elevator)"
gravity_beetle_hp_5 = "Gravity Beetle Stage - HP Pickup 5 (In elevator)"
gravity_beetle_hp_6 = "Gravity Beetle Stage - HP Pickup 6 (After falling missiles)"

blast_hornet_boss = "Blast Hornet Defeated"
blast_hornet_clear = "Blast Hornet Stage Clear"
blast_hornet_mini_boss = "Shurikein Defeated"
blast_hornet_heart_tank = "Blast Hornet Stage - Heart Tank"
blast_hornet_chimera_ride = "Blast Hornet Stage - Chimera Ride Armor"
blast_hornet_helmet = "Blast Hornet Stage - Helmet Chip Capsule"
blast_hornet_hp_1 = "Blast Hornet Stage - HP Pickup 1 (Bottom left of conveyor belts section)"
blast_hornet_hp_2 = "Blast Hornet Stage - HP Pickup 2 (Hidden in left wall of third hangar)"

doppler_lab_1_boss = "Dr. Doppler's Lab 1 Boss Defeated"
doppler_lab_1_clear = "Dr. Doppler's Lab Stage 1 Clear"
doppler_lab_1_mini_boss = "REX-2000 Defeated"
doppler_lab_1_energy = "Dr. Doppler's Lab 1 - Weapon Energy Pickup (Before REX-2000 room)"
doppler_lab_1_hp_1 = "Dr. Doppler's Lab 1 - HP Pickup 1 (Before REX-2000 room)"
doppler_lab_1_hp_2 = "Dr. Doppler's Lab 1 - HP Pickup 2 (Below Ride Armor pad)"

doppler_lab_2_boss = "Dr. Doppler's Lab 2 Boss Defeated"
doppler_lab_2_clear = "Dr. Doppler's Lab 2 Clear"
doppler_lab_2_mini_boss = "Dr. Doppler's Lab 2 - Mosquitus Defeated"
doppler_lab_2_z_saber = "Dr. Doppler's Lab 2 - Z-Saber"

doppler_lab_3_boss = "Dr. Doppler Defeated"
doppler_lab_3_clear = "Dr. Doppler's Lab 3 Clear"
doppler_lab_3_blizzard_buffalo = "Dr. Doppler's Lab 3 - Blizzard Buffalo Rematch"
doppler_lab_3_toxic_seahorse = "Dr. Doppler's Lab 3 - Toxic Seahorse Rematch"
doppler_lab_3_tunnel_rhino = "Dr. Doppler's Lab 3 - Tunnel Rhino Rematch"
doppler_lab_3_volt_catfish = "Dr. Doppler's Lab 3 - Volt Catfish Rematch"
doppler_lab_3_crush_crawfish = "Dr. Doppler's Lab 3 - Crush Crawfish Rematch"
doppler_lab_3_neon_tiger = "Dr. Doppler's Lab 3 - Neon Tiger Rematch"
doppler_lab_3_gravity_beetle = "Dr. Doppler's Lab 3 - Gravity Beetle Rematch"
doppler_lab_3_blast_hornet = "Dr. Doppler's Lab 3 - Blast Hornet Rematch"
doppler_lab_3_energy_dispenser = "Dr. Doppler's Lab 3 - Energy Dispenser Destroyed"
doppler_lab_3_hp = "Dr. Doppler's Lab 3 - HP Pickup (Before Dr. Doppler room)"

victory = "Dr. Doppler's Lab 4 - Sigma Defeated"

vile_stage_boss = "Vile Defeated"
vile_stage_energy = "Vile's Stage - Weapon Energy Pickup (Below boss room)"
vile_stage_hp_1 = "Vile's Stage - HP Pickup 1 (In first elevator)"
vile_stage_hp_2 = "Vile's Stage - HP Pickup 2 (In first elevator)"
vile_stage_hp_3 = "Vile's Stage - HP Pickup 3 (In first elevator)"
vile_stage_hp_4 = "Vile's Stage - HP Pickup 4 (In first elevator)"
vile_stage_hp_5 = "Vile's Stage - HP Pickup 5 (After boss room)"
vile_stage_hp_6 = "Vile's Stage - HP Pickup 6 (After boss)"
vile_stage_hp_7 = "Vile's Stage - HP Pickup 7 (After boss)"
vile_stage_hp_8 = "Vile's Stage - HP Pickup 8 (In second elevator)"
vile_stage_hp_9 = "Vile's Stage - HP Pickup 9 (Before falling platforms section)"
vile_stage_1up = "Vile's Stage - 1up Pickup (After boss)"

bit_defeat = "Bit Defeated"
byte_defeat = "Byte Defeated"
