# Robot Master Weapons
gemini_laser = "Gemini Laser"
needle_cannon = "Needle Cannon"
hard_knuckle = "Hard Knuckle"
magnet_missile = "Magnet Missile"
top_spin = "Top Spin"
search_snake = "Search Snake"
spark_shock = "Spark Shock"
shadow_blade = "Shadow Blade"

# Rush
rush_coil = "Rush Coil"
rush_jet = "Rush Jet"
rush_marine = "Rush Marine"

# Access Codes
needle_man_stage = "Needle Man Access Codes"
magnet_man_stage = "Magnet Man Access Codes"
gemini_man_stage = "Gemini Man Access Codes"
hard_man_stage = "Hard Man Access Codes"
top_man_stage = "Top Man Access Codes"
snake_man_stage = "Snake Man Access Codes"
spark_man_stage = "Spark Man Access Codes"
shadow_man_stage = "Shadow Man Access Codes"
doc_needle_stage = "Doc Robot (Needle) Access Codes"
doc_gemini_stage = "Doc Robot (Gemini) Access Codes"
doc_spark_stage = "Doc Robot (Spark) Access Codes"
doc_shadow_stage = "Doc Robot (Shadow) Access Codes"

# Misc. Items
one_up = "1-Up"
weapon_energy = "Weapon Energy (L)"
health_energy = "Health Energy (L)"
e_tank = "E-Tank"

needle_man = "Needle Man - Defeated"
magnet_man = "Magnet Man - Defeated"
gemini_man = "Gemini Man - Defeated"
hard_man = "Hard Man - Defeated"
top_man = "Top Man - Defeated"
snake_man = "Snake Man - Defeated"
spark_man = "Spark Man - Defeated"
shadow_man = "Shadow Man - Defeated"
doc_air = "Doc Robot (Air) - Defeated"
doc_crash = "Doc Robot (Crash) - Defeated"
doc_flash = "Doc Robot (Flash) - Defeated"
doc_bubble = "Doc Robot (Bubble) - Defeated"
doc_wood = "Doc Robot (Wood) - Defeated"
doc_heat = "Doc Robot (Heat) - Defeated"
doc_metal = "Doc Robot (Metal) - Defeated"
doc_quick = "Doc Robot (Quick) - Defeated"
break_man = "Break Man - Defeated"
wily_1_boss = "Kamegoro Maker - Defeated"
wily_2_boss = "Yellow Devil MK-II - Defeated"
wily_3_boss = "Holograph Mega Man - Defeated"
wily_5_boss = "Wily Machine 3 - Defeated"
gamma = "Gamma - Defeated"

get_gemini_laser = "Gemini Laser - Received"
get_needle_cannon = "Needle Cannon - Received"
get_hard_knuckle = "Hard Knuckle - Received"
get_magnet_missile = "Magnet Missile - Received"
get_top_spin = "Top Spin - Received"
get_search_snake = "Search Snake - Received"
get_spark_shock = "Spark Shock - Received"
get_shadow_blade = "Shadow Blade - Received"
get_rush_jet = "Rush Jet - Received"
get_rush_marine = "Rush Marine - Received"

# Wily Stage Event Items
doc_needle = "Doc Robot (Needle) - Completed"
doc_gemini = "Doc Robot (Gemini) - Completed"
doc_spark = "Doc Robot (Spark) - Completed"
doc_shadow = "Doc Robot (Shadow) - Completed"
break_stage = "Break Man"
wily_stage_1 = "Wily Stage 1 - Completed"
wily_stage_2 = "Wily Stage 2 - Completed"
wily_stage_3 = "Wily Stage 3 - Completed"
wily_stage_4 = "Wily Stage 4 - Completed"
wily_stage_5 = "Wily Stage 5 - Completed"

# TODO: Consumable Locations
needle_man_c1 = "Needle Man Stage - Weapon Energy 1"
needle_man_c2 = "Needle Man Stage - E-Tank"
magnet_man_c1 = "Magnet Man Stage - Health Energy 1"
magnet_man_c2 = "Magnet Man Stage - Health Energy 2"
magnet_man_c3 = "Magnet Man Stage - Health Energy 3"
magnet_man_c4 = "Magnet Man Stage - Health Energy 4"
magnet_man_c5 = "Magnet Man Stage - Weapon Energy 1"
magnet_man_c6 = "Magnet Man Stage - Weapon Energy 2"
magnet_man_c7 = "Magnet Man Stage - Weapon Energy 3"
magnet_man_c8 = "Magnet Man Stage - Health Energy 4"
gemini_man_c1 = "Gemini Man Stage - 1-Up 1"
gemini_man_c2 = "Gemini Man Stage - Health Energy 1"
gemini_man_c3 = "Gemini Man Stage - Mystery Tank"
gemini_man_c4 = "Gemini Man Stage - Weapon Energy 1"
gemini_man_c5 = "Gemini Man Stage - Health Energy 2"
gemini_man_c6 = "Gemini Man Stage - 1-Up 2"
gemini_man_c7 = "Gemini Man Stage - E-Tank 1"
gemini_man_c8 = "Gemini Man Stage - Weapon Energy 2"
gemini_man_c9 = "Gemini Man Stage - Weapon Energy 3"
gemini_man_c10 = "Gemini Man Stage - E-Tank 2"
hard_man_c1 = "Hard Man Stage - Health Energy 1"
hard_man_c2 = "Hard Man Stage - Health Energy 2"
hard_man_c3 = "Hard Man Stage - E-Tank"
hard_man_c4 = "Hard Man Stage - Health Energy 3"
hard_man_c5 = "Hard Man Stage - Health Energy 4"
hard_man_c6 = "Hard Man Stage - Health Energy 5"
hard_man_c7 = "Hard Man Stage - Health Energy 6"
top_man_c1 = "Top Man Stage - Health Energy 1"
top_man_c2 = "Top Man Stage - Health Energy 2"
top_man_c3 = "Top Man Stage - Health Energy 3"
top_man_c4 = "Top Man Stage - Health Energy 4"
top_man_c5 = "Top Man Stage - Weapon Energy 1"
top_man_c6 = "Top Man Stage - 1-Up"
top_man_c7 = "Top Man Stage - Health Energy 5"
top_man_c8 = "Top Man Stage - Health Energy 6"
snake_man_c1 = "Snake Man Stage - Health Energy 1"
snake_man_c2 = "Snake Man Stage - Health Energy 2"
snake_man_c3 = "Snake Man Stage - Mystery Tank 1"
snake_man_c4 = "Snake Man Stage - Mystery Tank 2"
snake_man_c5 = "Snake Man Stage - Health Energy 3"
spark_man_c1 = "Spark Man Stage - Health Energy 1"
spark_man_c2 = "Spark Man Stage - Weapon Energy 1"
spark_man_c3 = "Spark Man Stage - Weapon Energy 2"
spark_man_c4 = "Spark Man Stage - Weapon Energy 3"
spark_man_c5 = "Spark Man Stage - Weapon Energy 4"
spark_man_c6 = "Spark Man Stage - Weapon Energy 5"
shadow_man_c1 = "Shadow Man Stage - Weapon Energy 1"
shadow_man_c2 = "Shadow Man Stage - Weapon Energy 2"
shadow_man_c3 = "Shadow Man Stage - Weapon Energy 3"
shadow_man_c4 = "Shadow Man Stage - Weapon Energy 4"

wily_2_c1 = "Wily Stage 2 - Weapon Energy 1"
wily_2_c2 = "Wily Stage 2 - Weapon Energy 2"
wily_2_c3 = "Wily Stage 2 - 1-Up 1"
wily_2_c4 = "Wily Stage 2 - Weapon Energy 3"
