"""Flag locations for the check_flags command."""

location_flag_to_name = {
    1: "Japes Lanky Grape Gate Barrel",
    2: "Japes Tiny Feather Gate Barrel",
    3: "Japes Donkey Baboon Blast",
    4: "Japes in Front of Diddy Cage",
    5: "Japes Free Diddy Item",
    6: "Kong Unlocked: Diddy",
    8: "Japes Tiny Stump",
    9: "Japes Tiny Beehive",
    10: "Japes Lanky Painting Room Zingers",
    11: "Japes Lanky Slope Barrel",
    12: "Japes Chunky Underground",
    18: "Japes Diddy Timed Cage Banana",
    19: "Japes Lanky Timed Cage Banana",
    20: "Japes Donkey Floor Cage Banana",
    21: "Japes Tiny Timed Cage Banana",
    22: "Japes Chunky Timed Cage Banana",
    23: "Japes Diddy Top of Mountain",
    24: "Japes Diddy Minecart",
    25: "Japes Chunky Boulder",
    26: "Japes Boss Defeated",
    28: "Japes Chunky Giant Bonus Barrel",
    31: "Japes Diddy Peanut Tunnel",
    49: "Aztec Chunky Vases",
    51: "Aztec Donkey Free Llama Blast",
    52: "Aztec Chunky Giant Caged Barrel",
    54: "Aztec Diddy Ram Gongs",
    56: "Aztec Diddy 5 Door Temple",
    57: "Aztec Donkey 5 Door Temple",
    58: "Aztec Tiny 5 Door Temple",
    59: "Aztec Chunky 5 Door Temple",
    60: "Aztec Lanky 5 Door Temple",
    62: "Aztec Donkey Sealed Quicksand Tunnel Barrel",
    63: "Aztec Diddy Vulture Race",
    64: "Aztec Chunky Klaptrap Room",
    65: "Aztec Tiny Klaptrap Room",
    66: "Kong Unlocked: Tiny",
    67: "Aztec Free Tiny Item",
    68: "Aztec Lanky Vulture Shooting",
    70: "Kong Unlocked: Lanky",
    71: "Aztec Tiny Llama Temple Lava Pedestals",
    72: "Aztec Lanky Matching Game",
    73: "Aztec Lanky Llama Temple Barrel",
    74: "Aztec Boss Defeated",
    75: "Aztec Tiny Beetle Race",
    77: "Aztec Free Lanky Item",
    112: "Factory Donkey Power Hut",
    113: "Factory Diddy Production Spring",
    114: "Factory Chunky Production Timer",
    115: "Factory Lanky Production Handstand",
    116: "Factory Tiny Production Twirl",
    117: "Kong Unlocked: Chunky",
    118: "Factory Free Chunky Item",
    121: "Factory Chunky Dark Room",
    122: "Factory Donkey Number Game",
    123: "Factory Tiny Mini by Arcade",
    124: "Factory Tiny Dartboard",
    125: "Factory Lanky Piano Game",
    126: "Factory Diddy Charge Enemies",
    127: "Factory Chunky Toy Monster",
    128: "Factory Donkey Crusher Room",
    130: "Factory Donkey DK Arcade Round 1",
    132: "DK Arcade Round 2",
    134: "Factory Diddy Storage Room Barrel",
    135: "Factory Diddy Block Tower",
    136: "Factory Chunky Barrel by Arcade",
    137: "Factory Lanky Testing Room Barrel",
    138: "Factory Boss Defeated",
    139: "Factory Tiny Car Race",
    154: "Galleon Chunky Cannon Game",
    157: "Galleon Donkey Lighthouse",
    163: "Galleon Diddy Gold Tower Barrel",
    164: "Galleon Lanky Gold Tower Barrel",
    165: "Galleon Donkey Seal Race",
    166: "Galleon Chunky Seasick",
    167: "Galleon Diddy Mechfish",
    168: "Galleon Boss Defeated",
    182: "Galleon Chunky Chest",
    183: "Galleon Lanky 2 Door Ship",
    184: "Galleon Tiny 2 Door Ship",
    191: "Galleon Tiny Mermaid Reward",
    192: "Galleon Lanky Enguarde Chest",
    193: "Galleon Donkey Free the Seal",
    197: "Galleon Chunky 5 Door Ship",
    198: "Galleon Diddy 5 Door Ship",
    199: "Galleon Lanky 5 Door Ship",
    200: "Galleon Donkey 5 Door Ship",
    201: "Galleon Tiny 5 Door Ship",
    202: "Galleon Tiny Submarine Barrel",
    204: "Galleon Diddy Top of Lighthouse",
    205: "Forest Tiny Anthill Banana",
    209: "Forest Tiny Top of the Beanstalk",
    211: "Forest Diddy Top of Mushroom Barrel",
    214: "Forest Diddy Winch Cage",
    215: "Forest Chunky Minecart",
    216: "Forest Diddy Dark Rafters",
    217: "Forest Lanky Attic Shooting",
    219: "Forest Donkey Mill Levers",
    221: "Forest Chunky Keg Crushing",
    224: "Forest Lanky Colored Mushroom Slam",
    225: "Forest Chunky Face Puzzle",
    226: "Forest Lanky Zinger Bounce",
    227: "Forest Tiny Mushroom Barrel",
    228: "Forest Donkey Mushroom Cannons",
    235: "Forest Donkey Thornvine Barn Barrel",
    236: "Forest Boss Defeated",
    247: "Forest Tiny Spider Boss",
    249: "Forest Lanky Rabbit Race",
    250: "Forest Diddy Owl Race",
    253: "Forest Chunky Apple Rescue",
    254: "Forest Donkey Baboon Blast",
    259: "Caves Lanky Beetle Race",
    260: "Caves Tiny 5 Door Cabin",
    261: "Caves Donkey 5 Door Cabin",
    262: "Caves Diddy 5 Door Cabin Lower",
    263: "Caves Chunky 5 Door Cabin",
    264: "Caves Lanky Sprint Cabin",
    268: "Caves Chunky Gorilla Gone",
    270: "Caves Chunky Transparent Igloo",
    271: "Caves Lanky Ice Castle Slam Challenge",
    274: "Caves Diddy 5 Door Igloo",
    275: "Caves Donkey 5 Door Igloo",
    276: "Caves Donkey Rotating Cabin",
    278: "Caves Chunky 5 Door Igloo",
    279: "Caves Tiny 5 Door Igloo",
    281: "Caves Lanky 5 Door Igloo",
    292: "Caves Boss Defeated",
    293: "Caves Diddy 5 Door Cabin Upper",
    294: "Caves Diddy Jetpack Barrel",
    295: "Caves Tiny Mini Cave Barrel",
    297: "Caves Tiny Monkeyport Igloo",
    298: "Caves Donkey Baboon Blast",
    301: "Returning the Banana Fairies",
    305: "Castle Diddy Ballroom",
    306: "Castle Lanky Tower",
    308: "Castle Lanky Mausoleum",
    309: "Castle Tiny Mausoleum",
    310: "Castle Diddy Crypt",
    311: "Castle Chunky Crypt",
    313: "Castle Donkey Library",
    314: "Castle Chunky Museum",
    315: "Castle Tiny Over Chasm",
    316: "Castle Lanky Dungeon",
    317: "Castle Boss Defeated",
    318: "Castle Donkey Minecart",
    319: "Castle Chunky Tree Sniping Barrel",
    320: "Castle Donkey Tree Sniping",
    322: "Castle Chunky Shed",
    323: "Castle Lanky Greenhouse",
    325: "Castle Tiny Car Race",
    326: "Castle Donkey Dungeon",
    350: "Castle Diddy Above Castle",
    351: "Castle Tiny Trash Can",
    353: "Castle Diddy Dungeon",
    379: "Jetpac",
    380: "The End of Helm",
    381: "Isles Japes Lobby Entrance Item",
    385: "Kong Unlocked: Donkey",
    398: "Isles Lanky Japes Instrument",
    402: "Isles Tiny Aztec Lobby Barrel",
    403: "Isles Tiny Galleon Lobby Swim",
    404: "Isles Donkey Bongos Pad",
    406: "Isles Chunky Helm Lobby Barrel",
    410: "Isles Diddy Guitar Pad",
    411: "Isles Donkey Caves Lava",
    415: "Isles Lanky Castle Lobby Barrel",
    416: "Isles Diddy Snides Spring Barrel",
    419: "Isles Donkey Coconut Cage",
    420: "Isles Tiny Feather Cage",
    421: "Isles Lanky Grape Cage",
    422: "Isles Chunky Pineapple Cage",
    423: "Isles Diddy Peanut Cage",
    424: "Isles Chunky Triangle Pad",
    425: "Isles Tiny Saxophone Pad",
    428: "Isles Diddy Summit Barrel",
    429: "Isles Lanky Sprint Cage",
    431: "Isles Chunky Pound the X",
    444: "Key 1 Turned",
    445: "Key 2 Turned",
    446: "Key 3 Turned",
    447: "Key 4 Turned",
    448: "Key 5 Turned",
    449: "Key 6 Turned",
    450: "Key 7 Turned",
    451: "Key 8 Turned",
    469: "Japes Kasplat: Hive Tunnel Lower",
    470: "Japes Kasplat: Near Painting Room",
    471: "Japes Kasplat: By Lanky Slope Bonus",
    472: "Japes Kasplat: Hive Tunnel Upper",
    473: "Japes Kasplat: Underground",
    474: "Aztec Kasplat: Behind DK Stone Door",
    475: "Aztec Kasplat: On Tiny Temple",
    476: "Aztec Kasplat: Llama Temple Lava",
    477: "Aztec Kasplat: Hunky Chunky Barrel",
    478: "Aztec Kasplat: Chunky 5-Door Temple",
    479: "Factory Kasplat: Upper Production Pipe",
    480: "Factory Kasplat: Base of Production",
    481: "Factory Kasplat: Research and Development",
    482: "Factory Kasplat: Pole to Arcade",
    483: "Factory Kasplat: Block Tower",
    484: "Galleon Kasplat: Diddy Gold Tower",
    485: "Galleon Kasplat: Lighthouse Alcove",
    486: "Galleon Kasplat: Cannon Game Room",
    487: "Galleon Kasplat: Past Vines",
    488: "Galleon Kasplat: Musical Cactus",
    489: "Forest Kasplat: Behind DK's Barn",
    490: "Forest Kasplat: Inside Giant Mushroom",
    491: "Forest Kasplat: Under Owl Tree",
    492: "Forest Kasplat: Low Mushroom Exterior",
    493: "Forest Kasplat: Mushroom Night Door",
    494: "Caves Kasplat: Near Ice Castle",
    495: "Caves Kasplat: Mini Room by Funky",
    496: "Caves Kasplat: On the Pillar",
    497: "Caves Kasplat: By the Far Warp 2",
    498: "Caves Kasplat: On 5-Door Igloo",
    499: "Castle Kasplat: Inside the Tree",
    500: "Castle Kasplat: Lower Cave Center",
    501: "Castle Kasplat: Near Upper Warp 2",
    502: "Castle Kasplat: On a lone platform",
    503: "Castle Kasplat: Near Candy's",
    504: "Isles Kasplat: Helm Lobby",
    505: "Isles Kasplat: Castle Lobby",
    506: "Isles Kasplat: Caves Lobby Punch",
    507: "Isles Kasplat: Factory Lobby Box",
    508: "Isles Kasplat: Galleon Lobby",
    509: "Turn In Jungle Japes Donkey Blueprint",
    510: "Turn In Jungle Japes Diddy Blueprint",
    511: "Turn In Jungle Japes Lanky Blueprint",
    512: "Turn In Jungle Japes Tiny Blueprint",
    513: "Turn In Jungle Japes Chunky Blueprint",
    514: "Turn In Angry Aztec Donkey Blueprint",
    515: "Turn In Angry Aztec Diddy Blueprint",
    516: "Turn In Angry Aztec Lanky Blueprint",
    517: "Turn In Angry Aztec Tiny Blueprint",
    518: "Turn In Angry Aztec Chunky Blueprint",
    519: "Turn In Frantic Factory Donkey Blueprint",
    520: "Turn In Frantic Factory Diddy Blueprint",
    521: "Turn In Frantic Factory Lanky Blueprint",
    522: "Turn In Frantic Factory Tiny Blueprint",
    523: "Turn In Frantic Factory Chunky Blueprint",
    524: "Turn In Gloomy Galleon Donkey Blueprint",
    525: "Turn In Gloomy Galleon Diddy Blueprint",
    526: "Turn In Gloomy Galleon Lanky Blueprint",
    527: "Turn In Gloomy Galleon Tiny Blueprint",
    528: "Turn In Gloomy Galleon Chunky Blueprint",
    529: "Turn In Forest Forest Donkey Blueprint",
    530: "Turn In Forest Forest Diddy Blueprint",
    531: "Turn In Forest Forest Lanky Blueprint",
    532: "Turn In Forest Forest Tiny Blueprint",
    533: "Turn In Forest Forest Chunky Blueprint",
    534: "Turn In Crystal Caves Donkey Blueprint",
    535: "Turn In Crystal Caves Diddy Blueprint",
    536: "Turn In Crystal Caves Lanky Blueprint",
    537: "Turn In Crystal Caves Tiny Blueprint",
    538: "Turn In Crystal Caves Chunky Blueprint",
    539: "Turn In Creepy Castle Donkey Blueprint",
    540: "Turn In Creepy Castle Diddy Blueprint",
    541: "Turn In Creepy Castle Lanky Blueprint",
    542: "Turn In Creepy Castle Tiny Blueprint",
    543: "Turn In Creepy Castle Chunky Blueprint",
    544: "Turn In Donkey Isles Donkey Blueprint",
    545: "Turn In Donkey Isles Diddy Blueprint",
    546: "Turn In Donkey Isles Lanky Blueprint",
    547: "Turn In Donkey Isles Tiny Blueprint",
    548: "Turn In Donkey Isles Chunky Blueprint",
    549: "Japes Donkey Medal",
    550: "Japes Diddy Medal",
    551: "Japes Lanky Medal",
    552: "Japes Tiny Medal",
    553: "Japes Chunky Medal",
    554: "Aztec Donkey Medal",
    555: "Aztec Diddy Medal",
    556: "Aztec Lanky Medal",
    557: "Aztec Tiny Medal",
    558: "Aztec Chunky Medal",
    559: "Factory Donkey Medal",
    560: "Factory Diddy Medal",
    561: "Factory Lanky Medal",
    562: "Factory Tiny Medal",
    563: "Factory Chunky Medal",
    564: "Galleon Donkey Medal",
    565: "Galleon Diddy Medal",
    566: "Galleon Lanky Medal",
    567: "Galleon Tiny Medal",
    568: "Galleon Chunky Medal",
    569: "Forest Donkey Medal",
    570: "Forest Diddy Medal",
    571: "Forest Lanky Medal",
    572: "Forest Tiny Medal",
    573: "Forest Chunky Medal",
    574: "Caves Donkey Medal",
    575: "Caves Diddy Medal",
    576: "Caves Lanky Medal",
    577: "Caves Tiny Medal",
    578: "Caves Chunky Medal",
    579: "Castle Donkey Medal",
    580: "Castle Diddy Medal",
    581: "Castle Lanky Medal",
    582: "Castle Tiny Medal",
    583: "Castle Chunky Medal",
    584: "Helm Donkey Medal",
    585: "Helm Diddy Medal",
    586: "Helm Lanky Medal",
    587: "Helm Tiny Medal",
    588: "Helm Chunky Medal",
    589: "Japes Fairy (Rambi Door Pool)",
    590: "Japes Fairy (Painting Room)",
    591: "Factory Fairy (Near Funky's)",
    592: "Galleon Fairy (In Punch Chest)",
    593: "Isles Fairy (Factory Lobby)",
    594: "Isles Fairy (Forest Lobby)",
    595: "Forest Fairy (Dark Rafters)",
    596: "Forest Fairy (Thornvine Barn)",
    597: "Caves Fairy (Tiny Igloo)",
    598: "Helm Fairy (Key 8 Room (1))",
    599: "Helm Fairy (Key 8 Room (2))",
    600: "Aztec Fairy (Llama Temple)",
    601: "Aztec Fairy (Tiny 5-Door Temple)",
    602: "Factory Fairy (Number Game)",
    603: "Galleon Fairy (In Tiny's 5-Door Ship)",
    604: "Castle Fairy (Near Car Race)",
    605: "Castle Fairy (Tree Sniper Room)",
    606: "Isles Fairy (Small Island)",
    607: "Isles Fairy (Upper Krem Isles)",
    608: "Caves Fairy (Diddy Candles Cabin)",
    609: "Japes Battle Arena (Near Funky)",
    610: "Aztec Battle Arena (Tiny Temple: Vulture Room)",
    611: "Factory Battle Arena (Under R and D Grate)",
    612: "Galleon Battle Arena (Under Cranky)",
    613: "Forest Battle Arena (Giant Mushroom High Ladder Platform)",
    614: "Isles Battle Arena 2 (Fungi Lobby: Gorilla Gone Box)",
    615: "Isles Battle Arena 1 (Snide's Room: Under Rock)",
    616: "Caves Battle Arena (Rotating Room: Left Portion)",
    617: "Castle Battle Arena (Greenhouse: Center)",
    618: "Helm Battle Arena (Top of Blast-o-Matic)",
    670: "Japes Dirt: Painting Hill",
    671: "Aztec Dirt: Chunky Temple",
    672: "Factory Dirt: Dark Room",
    673: "Isles Dirt: Cabin Isle",
    674: "Isles Dirt: Under Caves Lobby",
    675: "Isles Dirt: Aztec Roof",
    676: "Aztec Dirt: Oasis",
    677: "Forest Dirt: Mills Grass",
    678: "Forest Dirt: Beanstalk",
    679: "Galleon Dirt: Lighthouse",
    680: "Caves Dirt: Giant Kosha",
    681: "Castle Dirt: Top Floor",
    682: "Isles Dirt: Back of Prison",
    683: "Isles Dirt: Training Grounds Rear Tunnel",
    684: "Isles Dirt: Banana Hoard",
    685: "Isles Dirt: Castle Lobby",
    900: "Japes Donkey Hint Door",
    901: "Japes Diddy Hint Door",
    902: "Japes Lanky Hint Door",
    903: "Japes Tiny Hint Door",
    904: "Japes Chunky Hint Door",
    905: "Aztec Donkey Hint Door",
    906: "Aztec Diddy Hint Door",
    907: "Aztec Lanky Hint Door",
    908: "Aztec Tiny Hint Door",
    909: "Aztec Chunky Hint Door",
    910: "Factory Donkey Hint Door",
    911: "Factory Diddy Hint Door",
    912: "Factory Lanky Hint Door",
    913: "Factory Tiny Hint Door",
    914: "Factory Chunky Hint Door",
    915: "Galleon Donkey Hint Door",
    916: "Galleon Diddy Hint Door",
    917: "Galleon Lanky Hint Door",
    918: "Galleon Tiny Hint Door",
    919: "Galleon Chunky Hint Door",
    920: "Forest Donkey Hint Door",
    921: "Forest Diddy Hint Door",
    922: "Forest Lanky Hint Door",
    923: "Forest Tiny Hint Door",
    924: "Forest Chunky Hint Door",
    925: "Caves Donkey Hint Door",
    926: "Caves Diddy Hint Door",
    927: "Caves Lanky Hint Door",
    928: "Caves Tiny Hint Door",
    929: "Caves Chunky Hint Door",
    930: "Castle Donkey Hint Door",
    931: "Castle Diddy Hint Door",
    932: "Castle Lanky Hint Door",
    933: "Castle Tiny Hint Door",
    934: "Castle Chunky Hint Door",
}

location_name_to_flag = {v: k for k, v in location_flag_to_name.items()}
