# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Custom .apworlds

on:
  pull_request:
    types: [synchronize, edited, closed]
    branches:
      - ashipelago

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building custom .apworlds for Ashipelago

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        token: '${{ github.token }}'
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.6
    - name: Get current date
      if: startsWith(github.event.pull_request.title, 'Worlds/') == true
      id: date
      run: echo "NOW=$(TZ=":America/New_York" date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Create Release
      if: startsWith(github.event.pull_request.title, 'Worlds/') == true
      uses: softprops/action-gh-release@v2.5.0
      with:
        draft: true
        prerelease: false
        name: "Custom Worlds ${{ env.NOW }}"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Read custom .apworlds file
      id: read_apworlds
      run: |
        tr '\n\r' ' ' < custom_worlds.txt > cleaned_custom_worlds.txt
        FILE_CONTENTS=$(cat cleaned_custom_worlds.txt)
        echo "world_list=$FILE_CONTENTS" >> $GITHUB_OUTPUT
      shell: bash
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        python ModuleUpdate.py --yes --force --append "WebHostLib/requirements.txt"
    - name: Build APWorlds
      run: |
        source venv/bin/activate
        export PYTHONPATH=$(pwd)
        timeout 600 python Launcher.py "Build Custom APWorlds" ${{steps.read_apworlds.outputs.world_list}}
        WORLD_COUNT=$(find "build/apworlds" -maxdepth 1 -mindepth 1 | wc -l)
        echo "Built $WORLD_COUNT .apworlds"
        TRACKER_COUNT=$(find "build/pop_trackers" -maxdepth 1 -mindepth 1 | wc -l)
        echo "Built $TRACKER_COUNT pop tracker packs"
    - name: Add to Release
      if: startsWith(github.event.pull_request.title, 'Worlds/') == true
      uses: softprops/action-gh-release@v2.5.0
      with:
        draft: true
        prerelease: false
        name: "Custom Worlds ${{ env.NOW }}"
        files: |
          build/apworlds/*
          build/pop_trackers/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
