name: Fuzz-LM-World
on:
  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "~3.12.6"
        cache: pip
    - name: Fuzzer-Check-1-yml
      uses: Eijebong/ap-actions/fuzz@main
      with:
        apworld-path: worlds/luigismansion
        ap-version: '0.6.1'
        python-version: '3.12'
        runs: 1000
        yamls-per-run: 1
  fuzz-3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "~3.12.6"
        cache: pip
    - name: Fuzzer-Check-3-yml
      uses: Eijebong/ap-actions/fuzz@main
      with:
        apworld-path: worlds/luigismansion
        ap-version: '0.6.1'
        python-version: '3.12'
        runs: 1000
        yamls-per-run: 3
