name: Build APWorld
on:
  push:
    branches:
      - Luigi's-Mansion-AP

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "~3.12.6"
        cache: pip
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Creates the LM APWorld
        id: apworld
        uses: Eijebong/ap-actions/package-apworld@main
        with:
          path: ${{ github.repository }}/worlds/luigismansion

      - uses: actions/upload-artifact@v4
        with:
          name: apworld
          path: ${{ steps.apworld.outputs.apworld }}

