name: Build APWorld
on:
  push:
    branches:
      - Luigi's-Mansion-AP

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "~3.12.6"
        cache: pip

  fuzz-1000-1:
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/ap-actions/fuzz@main
        with:
          apworld-path: worlds/pokemon_crystal
          ap-version: '0.6.1'
          python-version: '3.12'
          runs: 1000
          yamls-per-run: 1

  fuzz-1000-3:
    needs: [fuzz-1000-1]
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/ap-actions/fuzz@main
        with:
          apworld-path: worlds/pokemon_crystal
          ap-version: '0.6.1'
          python-version: '3.12'
          runs: 1000
          yamls-per-run: 3

  package:
    needs: [fuzz-1000-1, fuzz-1000-3]
    runs-on: ubuntu-latest
    steps:
      - name: Creates the LM APWorld
        id: apworld
        uses: Eijebong/ap-actions/package-apworld@main
        with:
          path: ${{ github.repository }}/worlds/luigismansion
      - uses: actions/upload-artifact@v4
        with:
          name: apworld
          path: ${{ steps.apworld.outputs.apworld }}

  publish:
    runs-on: ubuntu-latest
    needs: [package]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: apworld

      - uses: ncipollo/release-action@v1
        with:
          artifacts: '*'
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          draft: true