name: LM-Release-World
on:
  push:
    branches:
      - Luigi's-Mansion-AP
  workflow_dispatch:
    inputs:
      tag:
        description: "Required tag to create the pre-draft."
        required: true

jobs:
  windows-deps:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "~3.12.10"
        cache: pip
    - name: Clear pip cache
      run: pip cache purge
    - name: Create Lib-Windows
      run: mkdir lib-windows
    - name: Install Windows-Deps
      run: pip install -r ${{github.workspace}}/worlds/luigismansion/requirements.txt --target ./lib-windows --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: lib-windows
        path: ./lib-windows/**
  
  linux-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "~3.12.10"
        cache: pip
    - name: Clear pip cache
      run: pip cache purge
    - name: Create Lib-Linux
      run: mkdir lib-linux
    - name: Install Linux-Deps
      run: pip install -r ${{github.workspace}}/worlds/luigismansion/requirements.txt --target ./lib-linux --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: lib-linux
        path: ./lib-linux/**

  fuzz:
    needs: [windows-deps, linux-deps]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "~3.12.10"
        cache: pip
    - name: Fuzzer-Check-1-yml
      uses: Eijebong/ap-actions/fuzz@main
      with:
        apworld-path: worlds/luigismansion
        ap-version: '0.6.3'
        python-version: '3.12'
        runs: 1000
        yamls-per-run: 1
    - name: Fuzzer-Check-3-yml
      uses: Eijebong/ap-actions/fuzz@main
      with:
        apworld-path: worlds/luigismansion
        ap-version: '0.6.3'
        python-version: '3.12'
        runs: 1000
        yamls-per-run: 3

  package:
    needs: [windows-deps, linux-deps]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compress Directory
        run: Compress-Archive -Path ./worlds/luigismansion -DestinationPath ./luigismansion.apworld
        shell: pwsh 
      
      - uses: actions/upload-artifact@v4
        with:
          name: apworld
          path: luigismansion.apworld

  publish:
    runs-on: ubuntu-latest
    needs: [package]
    permissions:
      contents: write
    steps:
      - name: Create Local Artifact Folder
        run: mkdir tmp-artifacts
      - name: Create Local Windows Lib Folder
        run: mkdir tmp-windows-lib
      - name: Create Local Linux Lib Folder
        run: mkdir tmp-linux-lib
      
      - uses: actions/download-artifact@v4
        with:
          name: lib-windows
          path: tmp-windows-lib
      - uses: actions/download-artifact@v4
        with:
          name: lib-linux
          path: tmp-linux-lib
      - uses: actions/download-artifact@v4
        with:
          name: apworld
          path: tmp-artifacts

      - name: Zip Lib Windows folder
        run: cd tmp-windows-lib && zip -r ../tmp-artifacts/lib-windows.zip * && cd ../
      - name: Zip Lib Linux folder
        run: cd tmp-linux-lib && zip -r ../tmp-artifacts/lib-linux.zip * && cd ../

      - if: ${{inputs.tag != '' }}
        name: Create Manual Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          draft: true
          prerelease: false
          name: Luigis Mansion AP ${{inputs.tag}}
          files: |
            tmp-artifacts/*
      - if: ${{inputs.tag == '' }}
        name: Create Manual Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          draft: true
          prerelease: false
          name: Luigis Mansion AP ${{github.ref_name}}
          files: |
            tmp-artifacts/*
