name: Release APWorld
on:
  push:
    tags:
      - '**'
jobs:
  release:
    uses: Eijebong/ap-actions/.github/workflows/release-apworld.yml@main
    with:
      apworld-path: worlds/medievil
      ap-version: '0.6.2'
      python-version: '3.12'
      prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc')}}