intro_hp_1 = "Intro Stage - HP Pickup 1"
intro_hp_2 = "Intro Stage - HP Pickup 2"
intro_completed = "Intro Stage - Get Defeated By Vile"
intro_mini_boss_1 = "Intro Stage - Defeated Bee Blader #1"
intro_mini_boss_2 = "Intro Stage - Defeated Bee Blader #2"

armored_armadillo_boss = "Defeated Armored Armadillo"
armored_armadillo_clear = "Armored Armadillo Clear"
armored_armadillo_sub_tank = "Armored Armadillo - Sub Tank"
armored_armadillo_hp_1 = "Armored Armadillo - HP Pickup 1"
armored_armadillo_hp_2 = "Armored Armadillo - HP Pickup 2"
armored_armadillo_heart_tank = "Armored Armadillo - Heart Tank"
armored_armadillo_hp_3 = "Armored Armadillo - HP Pickup 3"
armored_armadillo_hadouken = "Armored Armadillo - Hadouken Capsule"
armored_armadillo_mini_boss_1 = "Defeated Mole Borer #1"
armored_armadillo_mini_boss_2 = "Defeated Mole Borer #2"

chill_penguin_boss = "Defeated Chill Penguin"
chill_penguin_clear = "Chill Penguin Clear"
chill_penguin_legs = "Chill Penguin Stage - Legs Capsule"
chill_penguin_heart_tank = "Chill Penguin Stage - Heart Tank"

spark_mandrill_boss = "Defeated Spark Mandrill"
spark_mandrill_clear = "Spark Mandrill Clear"
spark_mandrill_mini_boss = "Defeated Thunder Slimer"
spark_mandrill_sub_tank = "Spark Mandrill Stage - Sub Tank"
spark_mandrill_heart_tank = "Spark Mandrill Stage - Heart Tank"

launch_octopus_boss = "Defeated Launch Octopus"
launch_octopus_clear = "Launch Octopus Clear"
launch_octopus_mini_boss_1 = "Defeated Anglerge #1"
launch_octopus_mini_boss_2 = "Defeated Anglerge #2"
launch_octopus_mini_boss_3 = "Defeated Utuboros #1"
launch_octopus_mini_boss_4 = "Defeated Utuboros #2"
launch_octopus_hp_1 = "Launch Octopus - HP Pickup 1"
launch_octopus_heart_tank = "Launch Octopus Stage - Heart Tank"

boomer_kuwanger_boss = "Defeated Boomer Kuwanger"
boomer_kuwanger_clear = "Boomer Kuwanger Clear"
boomer_kuwanger_heart_tank = "Boomer Kuwanger Stage - Heart Tank"

sting_chameleon_boss = "Defeated Sting Chameleon"
sting_chameleon_clear = "Sting Chameleon Clear"
sting_chameleon_heart_tank = "Sting Chameleon - Heart Tank"
sting_chameleon_body = "Sting Chameleon Stage - Body Capsule"
sting_chameleon_1up = "Sting Chameleon Stage - 1-Up"
sting_chameleon_hp_1 = "Sting Chameleon Stage - HP Pickup 1"

storm_eagle_boss = "Defeated Storm Eagle"
storm_eagle_clear = "Storm Eagle Clear"
storm_eagle_heart_tank = "Storm Eagle Stage - Heart Tank"
storm_eagle_sub_tank = "Storm Eagle Stage - Sub Tank"
storm_eagle_helmet = "Storm Eagle Stage - Helmet Capsule"
storm_eagle_1up = "Storm Eagle Stage - 1-Up"
storm_eagle_hp_1 = "Storm Eagle Stage - HP Pickup 1"
storm_eagle_energy_1 = "Storm Eagle Stage - Weapon Energy Pickup 1"

flame_mammoth_boss = "Defeated Flame Mammoth"
flame_mammoth_clear = "Flame Mammoth Clear"
flame_mammoth_hp_1 = "Flame Mammoth Stage - HP Pickup 1"
flame_mammoth_arms = "Flame Mammoth Stage - Arms Capsule"
flame_mammoth_heart_tank = "Flame Mammoth Stage - Heart Tank"
flame_mammoth_hp_2 = "Flame Mammoth Stage - HP Pickup 2"
flame_mammoth_1up = "Flame Mammoth Stage - 1-Up"
flame_mammoth_sub_tank = "Flame Mammoth Stage - Sub Tank"

sigma_fortress_1_bospider = "Defeated Bospider"
sigma_fortress_1_vile = "Defeated Vile"
sigma_fortress_1_boomer_kuwanger = "Defeated Boomer Kuwanger (Rematch)"

sigma_fortress_2_chill_penguin = "Defeated Chill Penguin (Rematch)"
sigma_fortress_2_storm_eagle = "Defeated Storm Eagle (Rematch)"
sigma_fortress_2_rangda_bangda = "Defeated Rangda Bangda"

sigma_fortress_3_armored_armadillo = "Defeated Armored Armadillo (Rematch)"
sigma_fortress_3_hp_1 = "Sigma's Fortress 3 Stage - HP Pickup 1"
sigma_fortress_3_sting_chameleon = "Defeated Sting Chameleon (Rematch)"
sigma_fortress_3_hp_2 = "Sigma's Fortress 3 Stage - HP Pickup 2"
sigma_fortress_3_energy_1 = "Sigma's Fortress 3 Stage - Weapon Energy Pickup 1"
sigma_fortress_3_spark_mandrill = "Defeated Armored Spark Mandrill (Rematch)"
sigma_fortress_3_hp_3 = "Sigma's Fortress 3 Stage - HP Pickup 3"
sigma_fortress_3_energy_2 = "Sigma's Fortress 3 Stage - Weapon Energy Pickup 2"
sigma_fortress_3_launch_octopus = "Defeated Launch Octopus (Rematch)"
sigma_fortress_3_hp_4 = "Sigma's Fortress 3 Stage - HP Pickup 4"
sigma_fortress_3_energy_3 = "Sigma's Fortress 3 Stage - Weapon Energy Pickup 3"
sigma_fortress_3_1up = "Sigma's Fortress 3 Stage - 1-Up"
sigma_fortress_3_flame_mammoth = "Defeated Flame Mammoth (Rematch)"
sigma_fortress_3_d_rex = "Defeated D-Rex"

sigma_fortress_4_velguarder = "Defeated Velguarder"
sigma_fortress_4_sigma = "Defeated Sigma"
